/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Contact_BodyInputs */

const en_demo_narrative_client_intake_contact_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Contact_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The built-in form asks how the organization should reach the visitor and accepts a refusal, with a phone number, an email address and an option to send nothing as the three answers. [[#client-data #privacy]]
**What a contact detail becomes.** The answer is encrypted with the rest of the submission and nothing else is made of it. The client record a submission creates carries a generated alias and no phone row, no email row and no match hash, so a web submission is not compared against any other record until someone in the organization opens it and writes a contact value onto the case. [Duplicate client records](#dashboard/merge-candidates) covers the hashes that comparison needs and where they come from. [[#encryption #client-data]]
**Returning with an account.** A visitor can choose a username and password during submission, and the browser derives the keys for it before anything is sent. There is no password reset, and a forgotten password ends the thread rather than locking it, because nothing on the server can re-open what that password unlocked. [The client account](#client-account/sign-in) covers what the account opens afterward. [[#keys #failure-states]]
**Returning with a link.** The other option is a link that opens the same conversation with no account at all. The material that unlocks it rides in the fragment of the URL, which a browser does not send to a server, so possession of the link is the whole of the access check and a copy of it is as good as the original. Losing it ends the thread the same way a forgotten password does. [The channel lifecycle](#deep-dive/portal-channel-lifecycle) covers what the channel is. [[#keys #portal]]
**Why only one of the two.** Opening either option closes the other, and a submission carrying both is resolved in favor of the account. The two mint different channels for the same conversation, and one conversation with two ways in would widen the access set for no gain the visitor asked for. [[#permissions #portal]]
**The contact step and the two mint paths.** The contact answers are assembled in \`handleSubmit\` in \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\` with labels pinned to the organization's base locale so queue-facing text reads the same whatever language the form was filled in. The account branch is \`buildAccountPayload\` and the link branch \`buildContinuationPayload\`, both in \`intake-crypto.ts\`, and the server writes them in \`handleAccountStep\` and \`handleContinuationStep\` in \`packages/server/src/portal/intake-service.ts\`. [[#portal #server-holds]]`)
};

const es_demo_narrative_client_intake_contact_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Contact_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El formulario integrado pregunta cómo debe contactar la organización con el visitante y acepta una negativa, con un número de teléfono, una dirección de correo y la opción de no dejar nada como las tres respuestas. [[#client-data #privacy]]
**En qué se convierte un dato de contacto.** La respuesta se cifra junto con el resto del envío y no se hace nada más con ella. El registro de cliente que crea un envío lleva un alias generado y ninguna fila de teléfono, ninguna fila de correo y ningún hash de coincidencia, así que un envío web no se compara con ningún otro registro hasta que alguien de la organización lo abre y escribe un dato de contacto en el caso. [Registros de cliente duplicados](#dashboard/merge-candidates) trata los hashes que necesita esa comparación y de dónde salen. [[#encryption #client-data]]
**Volver con una cuenta.** El visitante puede elegir un nombre de usuario y una contraseña durante el envío, y el navegador deriva sus claves antes de que se envíe nada. No hay restablecimiento de contraseña, y olvidarla termina la conversación en lugar de bloquearla, porque nada en el servidor puede reabrir lo que esa contraseña desbloqueaba. [La cuenta del cliente](#client-account/sign-in) trata lo que abre la cuenta después. [[#keys #failure-states]]
**Volver con un enlace.** La otra opción es un enlace que abre la misma conversación sin ninguna cuenta. El material que la desbloquea viaja en el fragmento de la URL, que el navegador no envía a ningún servidor, así que tener el enlace es toda la comprobación de acceso y una copia suya sirve igual que el original. Perderlo termina la conversación igual que una contraseña olvidada. [El ciclo de vida del canal](#deep-dive/portal-channel-lifecycle) trata qué es el canal. [[#keys #portal]]
**Por qué solo una de las dos.** Abrir cualquiera de las dos opciones cierra la otra, y un envío que lleve ambas se resuelve a favor de la cuenta. Las dos acuñan canales distintos para la misma conversación, y una conversación con dos vías de entrada ampliaría el conjunto de acceso sin que el visitante haya pedido nada a cambio. [[#permissions #portal]]
**El paso de contacto y las dos vías de acuñación.** Las respuestas de contacto se ensamblan en \`handleSubmit\`, en \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\`, con las etiquetas fijadas al idioma base de la organización para que el texto que ve la cola se lea igual sea cual sea el idioma en que se rellenó el formulario. La rama de la cuenta es \`buildAccountPayload\` y la del enlace \`buildContinuationPayload\`, ambas en \`intake-crypto.ts\`, y el servidor las escribe en \`handleAccountStep\` y \`handleContinuationStep\`, en \`packages/server/src/portal/intake-service.ts\`. [[#portal #server-holds]]`)
};

const en_xa2_demo_narrative_client_intake_contact_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Contact_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè bùìlt-ìn fòrm àsks hòw thè òrgànìzàtìòn shòùld rèàch thè vìsìtòr ànd àccèpts à rèfùsàl, wìth à phònè nùmbèr, àn èmàìl àddrèss ànd àn òptìòn tò sènd nòthìng às thè thrèè ànswèrs. [[#clìènt-dàtà #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt à còntàct dètàìl bècòmès. •••••••••** Thè ànswèr ìs èncryptèd wìth thè rèst òf thè sùbmìssìòn ànd nòthìng èlsè ìs màdè òf ìt. Thè clìènt rècòrd à sùbmìssìòn crèàtès càrrìès à gènèràtèd àlìàs ànd nò phònè ròw, nò èmàìl ròw ànd nò màtch hàsh, sò à wèb sùbmìssìòn ìs nòt còmpàrèd àgàìnst àny òthèr rècòrd ùntìl sòmèònè ìn thè òrgànìzàtìòn òpèns ìt ànd wrìtès à còntàct vàlùè òntò thè càsè. [Dùplìcàtè clìènt rècòrds](#dàshbòàrd/mèrgè-càndìdàtès) còvèrs thè hàshès thàt còmpàrìsòn nèèds ànd whèrè thèy còmè fròm. [[#èncryptìòn #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rètùrnìng wìth àn àccòùnt. ••••••••** À vìsìtòr càn chòòsè à ùsèrnàmè ànd pàsswòrd dùrìng sùbmìssìòn, ànd thè bròwsèr dèrìvès thè kèys fòr ìt bèfòrè ànythìng ìs sènt. Thèrè ìs nò pàsswòrd rèsèt, ànd à fòrgòttèn pàsswòrd ènds thè thrèàd ràthèr thàn lòckìng ìt, bècàùsè nòthìng òn thè sèrvèr càn rè-òpèn whàt thàt pàsswòrd ùnlòckèd. [Thè clìènt àccòùnt](#clìènt-àccòùnt/sìgn-ìn) còvèrs whàt thè àccòùnt òpèns àftèrwàrd. [[#kèys #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rètùrnìng wìth à lìnk. •••••••** Thè òthèr òptìòn ìs à lìnk thàt òpèns thè sàmè cònvèrsàtìòn wìth nò àccòùnt àt àll. Thè màtèrìàl thàt ùnlòcks ìt rìdès ìn thè fràgmènt òf thè ÙRL, whìch à bròwsèr dòès nòt sènd tò à sèrvèr, sò pòssèssìòn òf thè lìnk ìs thè whòlè òf thè àccèss chèck ànd à còpy òf ìt ìs às gòòd às thè òrìgìnàl. Lòsìng ìt ènds thè thrèàd thè sàmè wày à fòrgòttèn pàsswòrd dòès. [Thè chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs whàt thè chànnèl ìs. [[#kèys #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why ònly ònè òf thè twò. ••••••••** Òpènìng èìthèr òptìòn clòsès thè òthèr, ànd à sùbmìssìòn càrryìng bòth ìs rèsòlvèd ìn fàvòr òf thè àccòùnt. Thè twò mìnt dìffèrènt chànnèls fòr thè sàmè cònvèrsàtìòn, ànd ònè cònvèrsàtìòn wìth twò wàys ìn wòùld wìdèn thè àccèss sèt fòr nò gàìn thè vìsìtòr àskèd fòr. [[#pèrmìssìòns #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còntàct stèp ànd thè twò mìnt pàths. ••••••••••••** Thè còntàct ànswèrs àrè àssèmblèd ìn \`hàndlèSùbmìt\` ìn \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/ÌntàkèFòrmBòdy.svèltè\` wìth làbèls pìnnèd tò thè òrgànìzàtìòn's bàsè lòcàlè sò qùèùè-fàcìng tèxt rèàds thè sàmè whàtèvèr làngùàgè thè fòrm wàs fìllèd ìn. Thè àccòùnt brànch ìs \`bùìldÀccòùntPàylòàd\` ànd thè lìnk brànch \`bùìldCòntìnùàtìònPàylòàd\`, bòth ìn \`ìntàkè-cryptò.ts\`, ànd thè sèrvèr wrìtès thèm ìn \`hàndlèÀccòùntStèp\` ànd \`hàndlèCòntìnùàtìònStèp\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-sèrvìcè.ts\`. [[#pòrtàl #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The built-in form asks how the organization should reach the visitor and accepts a refusal, with a phone number, an email address and an option to send nothi..." |
*
* @param {Demo_Narrative_Client_Intake_Contact_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_contact_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Contact_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Contact_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_contact_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_contact_body(inputs)
	return en_demo_narrative_client_intake_contact_body(inputs)
});