/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Phone_Lines_BodyInputs */

const en_demo_narrative_admin_phone_lines_body = /** @type {(inputs: Demo_Narrative_Admin_Phone_Lines_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Phone lines are the numbers an organization's provider account holds. Each number carries a provider-assigned ID that the server uses to tell them apart. One line can be designated for outbound calls and texts to clients, and another for automated system messages. An organization with only one number needs no assignment, because both purposes fall through to that number automatically. [[#telephony]]
**How does the server pick a line?** A system message tries the system line first, then the outbound line, then the first provisioned number. An outbound call or text tries the outbound line first, then the first provisioned number. When no number is provisioned at all, the server refuses the request rather than placing a call on an unintended number. The client sees the organization's line as the caller ID, not the user's own number. The server resolves the client's number from the ticket itself. [The telephony relay](#deep-dive/the-telephony-relay) covers what happens once a call is placed. [[#privacy #failure-states]]
**What does the assignment store?** Two provider IDs in plaintext columns on the organization's config row. The numbers themselves stay inside the sealed provider configuration, so the tenant database records which line serves which purpose without recording what either number is. [Provider connection](#admin-comms/provider) covers that sealed configuration. [[#server-holds #metadata]]
**The purpose resolver and the exclusion rule.** \`createPhoneResolver\` in \`packages/server/src/telephony/phone-resolver.ts\` owns the fallback chain. The purpose SIDs are \`phone_outbound_sid\` and \`phone_system_sid\` on the tenant \`org_config\` row (migration 022). \`lookupProvisionedPhones\` in \`config-service.ts\` excludes any number that carries no provider ID rather than falling through to the first provisioned number while a deliberate assignment is on file. Greetings are keyed by line ID, so replacing a number on a line carries every greeting forward. [Greetings](#admin-comms/greetings) covers those recordings. [[#failure-states]]`)
};

const es_demo_narrative_admin_phone_lines_body = /** @type {(inputs: Demo_Narrative_Admin_Phone_Lines_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Las líneas telefónicas son los números que tiene la cuenta de proveedor de una organización. Cada número lleva un ID asignado por el proveedor que el servidor usa para distinguirlos. Se puede designar una línea para llamadas y mensajes salientes a los clientes, y otra para los mensajes automáticos del sistema. Una organización con un solo número no necesita asignar ninguna, porque ambas funciones recaen en ese número automáticamente. [[#telephony]]
**¿Cómo elige el servidor una línea?** Un mensaje del sistema prueba la línea de sistema primero, luego la línea saliente y luego el primer número aprovisionado. Una llamada o un mensaje saliente prueban la línea saliente primero y luego el primer número aprovisionado. Cuando no hay ningún número aprovisionado, el servidor rechaza la solicitud en lugar de hacer una llamada desde un número no previsto. El cliente ve el número de la organización como identificador de llamada, no el número propio de la persona usuaria. El servidor resuelve el número del cliente a partir del propio ticket. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que ocurre una vez que se hace la llamada. [[#privacy #failure-states]]
**¿Qué guarda la asignación?** Dos IDs de proveedor en columnas en texto plano de la fila de configuración de la organización. Los números en sí se quedan dentro de la configuración sellada del proveedor, así que la base de datos del inquilino registra qué línea cumple qué función sin registrar cuál es cada número. [Conexión con el proveedor](#admin-comms/provider) trata esa configuración sellada. [[#server-holds #metadata]]
**El resolutor de función y la regla de exclusión.** \`createPhoneResolver\`, en \`packages/server/src/telephony/phone-resolver.ts\`, tiene la cadena de respaldo. Los SIDs de función son \`phone_outbound_sid\` y \`phone_system_sid\` en la fila \`org_config\` del inquilino (migración 022). \`lookupProvisionedPhones\`, en \`config-service.ts\`, excluye cualquier número que no lleve ID de proveedor en lugar de caer al primer número aprovisionado mientras hay una asignación deliberada guardada. Los saludos se indexan por ID de línea, así que reemplazar el número de una línea conserva todos los saludos. [Saludos](#admin-comms/greetings) trata esas grabaciones. [[#failure-states]]`)
};

const en_xa2_demo_narrative_admin_phone_lines_body = /** @type {(inputs: Demo_Narrative_Admin_Phone_Lines_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Phònè lìnès àrè thè nùmbèrs àn òrgànìzàtìòn's pròvìdèr àccòùnt hòlds. Èàch nùmbèr càrrìès à pròvìdèr-àssìgnèd ÌD thàt thè sèrvèr ùsès tò tèll thèm àpàrt. Ònè lìnè càn bè dèsìgnàtèd fòr òùtbòùnd càlls ànd tèxts tò clìènts, ànd ànòthèr fòr àùtòmàtèd systèm mèssàgès. Àn òrgànìzàtìòn wìth ònly ònè nùmbèr nèèds nò àssìgnmènt, bècàùsè bòth pùrpòsès fàll thròùgh tò thàt nùmbèr àùtòmàtìcàlly. [[#tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè sèrvèr pìck à lìnè? ••••••••••** À systèm mèssàgè trìès thè systèm lìnè fìrst, thèn thè òùtbòùnd lìnè, thèn thè fìrst pròvìsìònèd nùmbèr. Àn òùtbòùnd càll òr tèxt trìès thè òùtbòùnd lìnè fìrst, thèn thè fìrst pròvìsìònèd nùmbèr. Whèn nò nùmbèr ìs pròvìsìònèd àt àll, thè sèrvèr rèfùsès thè rèqùèst ràthèr thàn plàcìng à càll òn àn ùnìntèndèd nùmbèr. Thè clìènt sèès thè òrgànìzàtìòn's lìnè às thè càllèr ÌD, nòt thè ùsèr's òwn nùmbèr. Thè sèrvèr rèsòlvès thè clìènt's nùmbèr fròm thè tìckèt ìtsèlf. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt hàppèns òncè à càll ìs plàcèd. [[#prìvàcy #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè àssìgnmènt stòrè? ••••••••••** Twò pròvìdèr ÌDs ìn plàìntèxt còlùmns òn thè òrgànìzàtìòn's cònfìg ròw. Thè nùmbèrs thèmsèlvès stày ìnsìdè thè sèàlèd pròvìdèr cònfìgùràtìòn, sò thè tènànt dàtàbàsè rècòrds whìch lìnè sèrvès whìch pùrpòsè wìthòùt rècòrdìng whàt èìthèr nùmbèr ìs. [Pròvìdèr cònnèctìòn](#àdmìn-còmms/pròvìdèr) còvèrs thàt sèàlèd cònfìgùràtìòn. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pùrpòsè rèsòlvèr ànd thè èxclùsìòn rùlè. ••••••••••••••** \`crèàtèPhònèRèsòlvèr\` ìn \`pàckàgès/sèrvèr/src/tèlèphòny/phònè-rèsòlvèr.ts\` òwns thè fàllbàck chàìn. Thè pùrpòsè SÌDs àrè \`phònè_òùtbòùnd_sìd\` ànd \`phònè_systèm_sìd\` òn thè tènànt \`òrg_cònfìg\` ròw (mìgràtìòn 022). \`lòòkùpPròvìsìònèdPhònès\` ìn \`cònfìg-sèrvìcè.ts\` èxclùdès àny nùmbèr thàt càrrìès nò pròvìdèr ÌD ràthèr thàn fàllìng thròùgh tò thè fìrst pròvìsìònèd nùmbèr whìlè à dèlìbèràtè àssìgnmènt ìs òn fìlè. Grèètìngs àrè kèyèd by lìnè ÌD, sò rèplàcìng à nùmbèr òn à lìnè càrrìès èvèry grèètìng fòrwàrd. [Grèètìngs](#àdmìn-còmms/grèètìngs) còvèrs thòsè rècòrdìngs. [[#fàìlùrè-stàtès]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Phone lines are the numbers an organization's provider account holds. Each number carries a provider-assigned ID that the server uses to tell them apart. One..." |
*
* @param {Demo_Narrative_Admin_Phone_Lines_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_phone_lines_body = /** @type {((inputs?: Demo_Narrative_Admin_Phone_Lines_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Phone_Lines_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_phone_lines_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_phone_lines_body(inputs)
	return en_demo_narrative_admin_phone_lines_body(inputs)
});