/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Twofa_Sms_BodyInputs */

const en_demo_narrative_topic_twofa_sms_body = /** @type {(inputs: Demo_Narrative_Topic_Twofa_Sms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A six-digit code is sent by text to the phone number enrolled on the account. The code is valid for five minutes. A third wrong entry uses the code up. The next attempt starts from a fresh code. Each wrong entry also counts toward the five-per-session limit. [[#telephony #failure-states]]
**Number verification before activation.** Enrolling a phone number stores it inactive and sends a code to it. The method activates only after a code sent to that number comes back correct. Removing the method clears the stored number and its lookup hash in the same write. [[#failure-states #server-holds]]
**What does the server store for an enrolled number?** The server stores the phone number encrypted under its operational key. The server holds that key, so the running server can read the number back at any time. That is what allows it to pass the number to a telephony provider and send the text. The encryption protects the number in a database dump or backup taken without the key. It does not protect the number from the server itself. The server also stores a keyed hash of the number, used to detect the same number enrolled on two accounts. A database dump shows that an account has an SMS factor and that two accounts share a number. It does not show what the number is. [[#server-holds #metadata]]
**Delivery cost and request limits.** One code per ninety seconds per account, and three in an hour. These limits are tighter than the email code limits because every text message is billed to the organization. [[#telephony #failure-states]]
**Why is this the weakest option?** A phone number can be moved to an attacker's device by convincing the carrier to transfer it. The text message itself is readable by the carrier and by the telephony provider that delivers it, neither of which is inside the encryption boundary. Of the methods offered, this one protects least. It is kept for accounts where an authenticator app or a security key is not workable. [The telephony relay](#deep-dive/the-telephony-relay) covers what leaves the boundary on the phone side. [[#telephony #trust-boundary]]
**SMS code service and enrollment columns.** The service is \`packages/server/src/auth/sms-code.ts\` with the code row in \`sms_codes\`. The method registry carries the \`encrypted_sms_phone\` and \`sms_phone_hash\` columns. Both tables are in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. Enrollment and removal are \`storePendingSmsPhone\` and the method-removal path in \`packages/server/src/auth/two-factor-service.ts\`. [[#telephony #server-holds]]`)
};

const es_demo_narrative_topic_twofa_sms_body = /** @type {(inputs: Demo_Narrative_Topic_Twofa_Sms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Se envía un código de seis dígitos por mensaje de texto al número de teléfono registrado en la cuenta. El código es válido durante cinco minutos. Un tercer intento incorrecto agota el código. El siguiente intento comienza con un código nuevo. Cada intento incorrecto cuenta también para el límite de cinco por sesión. [[#telephony #failure-states]]
**Verificación del número antes de la activación.** Registrar un número de teléfono lo almacena como inactivo y le envía un código. El método se activa solo cuando un código enviado a ese número regresa correcto. Eliminar el método borra el número almacenado y su hash de búsqueda en la misma escritura. [[#failure-states #server-holds]]
**¿Qué almacena el servidor para un número registrado?** El servidor almacena el número de teléfono cifrado bajo su clave operativa. El servidor posee esa clave, por lo que puede leer el número en cualquier momento. Eso es lo que le permite pasar el número a un proveedor de telefonía y enviar el mensaje. El cifrado protege el número en un volcado de base de datos o una copia de seguridad tomada sin la clave. No protege el número del propio servidor. El servidor también almacena un hash con clave del número, usado para detectar el mismo número registrado en dos cuentas. Un volcado de base de datos muestra que una cuenta tiene un factor SMS y que dos cuentas comparten un número. No muestra cuál es el número. [[#server-holds #metadata]]
**Costo de envío y límites de solicitud.** Un código cada noventa segundos por cuenta, y tres en una hora. Estos límites son más estrictos que los del código por correo electrónico porque cada mensaje de texto se factura a la organización. [[#telephony #failure-states]]
**¿Por qué es la opción más débil?** Un número de teléfono puede transferirse al dispositivo de un atacante convenciendo al operador de realizar la transferencia. El mensaje de texto en sí es legible por el operador y por el proveedor de telefonía que lo entrega, ninguno de los cuales está dentro del límite de cifrado. De los métodos ofrecidos, este es el que menos protege. Se mantiene para cuentas en las que una aplicación de autenticación o una llave de seguridad no es viable. [El relay de telefonía](#deep-dive/the-telephony-relay) cubre qué sale del límite de cifrado en el lado del teléfono. [[#telephony #trust-boundary]]
**Servicio de códigos SMS y columnas de registro.** El servicio es \`packages/server/src/auth/sms-code.ts\` con la fila del código en \`sms_codes\`. El registro de métodos tiene las columnas \`encrypted_sms_phone\` y \`sms_phone_hash\`. Ambas tablas están en \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. El registro y la eliminación son \`storePendingSmsPhone\` y la ruta de eliminación de métodos en \`packages/server/src/auth/two-factor-service.ts\`. [[#telephony #server-holds]]`)
};

const en_xa2_demo_narrative_topic_twofa_sms_body = /** @type {(inputs: Demo_Narrative_Topic_Twofa_Sms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À sìx-dìgìt còdè ìs sènt by tèxt tò thè phònè nùmbèr ènròllèd òn thè àccòùnt. Thè còdè ìs vàlìd fòr fìvè mìnùtès. À thìrd wròng èntry ùsès thè còdè ùp. Thè nèxt àttèmpt stàrts fròm à frèsh còdè. Èàch wròng èntry àlsò còùnts tòwàrd thè fìvè-pèr-sèssìòn lìmìt. [[#tèlèphòny #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Nùmbèr vèrìfìcàtìòn bèfòrè àctìvàtìòn. ••••••••••••** Ènròllìng à phònè nùmbèr stòrès ìt ìnàctìvè ànd sènds à còdè tò ìt. Thè mèthòd àctìvàtès ònly àftèr à còdè sènt tò thàt nùmbèr còmès bàck còrrèct. Rèmòvìng thè mèthòd clèàrs thè stòrèd nùmbèr ànd ìts lòòkùp hàsh ìn thè sàmè wrìtè. [[#fàìlùrè-stàtès #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè fòr àn ènròllèd nùmbèr? •••••••••••••••** Thè sèrvèr stòrès thè phònè nùmbèr èncryptèd ùndèr ìts òpèràtìònàl kèy. Thè sèrvèr hòlds thàt kèy, sò thè rùnnìng sèrvèr càn rèàd thè nùmbèr bàck àt àny tìmè. Thàt ìs whàt àllòws ìt tò pàss thè nùmbèr tò à tèlèphòny pròvìdèr ànd sènd thè tèxt. Thè èncryptìòn pròtècts thè nùmbèr ìn à dàtàbàsè dùmp òr bàckùp tàkèn wìthòùt thè kèy. Ìt dòès nòt pròtèct thè nùmbèr fròm thè sèrvèr ìtsèlf. Thè sèrvèr àlsò stòrès à kèyèd hàsh òf thè nùmbèr, ùsèd tò dètèct thè sàmè nùmbèr ènròllèd òn twò àccòùnts. À dàtàbàsè dùmp shòws thàt àn àccòùnt hàs àn SMS fàctòr ànd thàt twò àccòùnts shàrè à nùmbèr. Ìt dòès nòt shòw whàt thè nùmbèr ìs. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dèlìvèry còst ànd rèqùèst lìmìts. ••••••••••** Ònè còdè pèr nìnèty sècònds pèr àccòùnt, ànd thrèè ìn àn hòùr. Thèsè lìmìts àrè tìghtèr thàn thè èmàìl còdè lìmìts bècàùsè èvèry tèxt mèssàgè ìs bìllèd tò thè òrgànìzàtìòn. [[#tèlèphòny #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why ìs thìs thè wèàkèst òptìòn? ••••••••••** À phònè nùmbèr càn bè mòvèd tò àn àttàckèr's dèvìcè by cònvìncìng thè càrrìèr tò trànsfèr ìt. Thè tèxt mèssàgè ìtsèlf ìs rèàdàblè by thè càrrìèr ànd by thè tèlèphòny pròvìdèr thàt dèlìvèrs ìt, nèìthèr òf whìch ìs ìnsìdè thè èncryptìòn bòùndàry. Òf thè mèthòds òffèrèd, thìs ònè pròtècts lèàst. Ìt ìs kèpt fòr àccòùnts whèrè àn àùthèntìcàtòr àpp òr à sècùrìty kèy ìs nòt wòrkàblè. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt lèàvès thè bòùndàry òn thè phònè sìdè. [[#tèlèphòny #trùst-bòùndàry]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**SMS còdè sèrvìcè ànd ènròllmènt còlùmns. ••••••••••••** Thè sèrvìcè ìs \`pàckàgès/sèrvèr/src/àùth/sms-còdè.ts\` wìth thè còdè ròw ìn \`sms_còdès\`. Thè mèthòd règìstry càrrìès thè \`èncryptèd_sms_phònè\` ànd \`sms_phònè_hàsh\` còlùmns. Bòth tàblès àrè ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`. Ènròllmènt ànd rèmòvàl àrè \`stòrèPèndìngSmsPhònè\` ànd thè mèthòd-rèmòvàl pàth ìn \`pàckàgès/sèrvèr/src/àùth/twò-fàctòr-sèrvìcè.ts\`. [[#tèlèphòny #sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A six-digit code is sent by text to the phone number enrolled on the account. The code is valid for five minutes. A third wrong entry uses the code up. The n..." |
*
* @param {Demo_Narrative_Topic_Twofa_Sms_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_twofa_sms_body = /** @type {((inputs?: Demo_Narrative_Topic_Twofa_Sms_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Twofa_Sms_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_twofa_sms_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_twofa_sms_body(inputs)
	return en_demo_narrative_topic_twofa_sms_body(inputs)
});