/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Filters_BodyInputs */

const en_demo_narrative_topic_filters_body = /** @type {(inputs: Demo_Narrative_Topic_Filters_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The ticket list can be filtered by status, queue, priority, assignee, creation date range, unread only, and needs attention only. Several dimensions can be active at once, and a badge counts how many are active. Clearing all filters resets every dimension but leaves the sort alone. [[#metadata]]
**The four statuses.** The status filter offers New, Active, On Hold, and Closed. The server stores only open and closed, plus an on-hold flag. New and Active are both open tickets; the browser tells them apart by whether the ticket has any client or volunteer contact. Selecting New together with Active is one server query for open tickets. When exactly one of the two is selected, the browser narrows the result further. On Hold maps to the on-hold flag. Closed maps to the closed status. [[#server-holds #client-data]]
**Which side evaluates what?** The server evaluates status, queue, priority, assignee, and creation date range, all of which are plaintext columns on the ticket row. The browser evaluates unread and needs attention, and separates New from Active. Before any filter runs, the server restricts the query to the queues the account has access to. A filter can only narrow what the account already has permission to see, and queue membership is what grants that access. [The permission system](#deep-dive/the-permission-system) covers where access comes from. The server returns 50 tickets per page. The default sort is most recent activity first. [Sorting](#tickets/sort) covers the sort options. [[#metadata #trust-boundary #permissions]]
**What does a filter request reveal?** A filter the server evaluates is a filter the server can read. The request states which queue, which priority, which assignee, and which date window the account is browsing, and when. Keeping unread in the browser hides how much of a ticket an account has read. It does not hide that the account opened the ticket. A read-cursor row exists for every ticket an account has opened, and only the position inside it is encrypted. [The trust boundary](#deep-dive/the-trust-boundary) covers that row and the others like it. [[#server-holds #privacy #metadata]]
**How does the browser decide unread?** A ticket is unread when its read cursor decrypts to a real position and someone other than the signed-in account has added activity since. A ticket nobody has opened has no cursor row and is not unread; its New mark already says so. The server excludes the account's own replies from both read-state sources, so an account's own reply is not unread to that account. Read cursors are encrypted per account. Decryption happens in the crypto worker, and the decrypted state lives only in the browser until the account signs out or the tab closes. When the idle timer zeroes the keys, that state is cleared and the unread filter is unavailable until the next sign-in. The browser never sends anything derived from read state to the server. [[#client-data #encryption #privacy #keys]]
**How does the browser decide needs attention?** The ticket must be open, not on hold, and marked urgent or high priority. It then qualifies if it is unassigned, or if it is assigned to the signed-in account and unread. The dashboard bucket of the same name reads this same rule rather than a second copy, so the two surfaces cannot disagree. [[#metadata]]
**Unread beyond the loaded page.** The list holds one page at a time, so an unread filter reading only loaded rows would miss unread tickets on later pages. A separate sweep enumerates the account's cursor rows across every open ticket the account has access to, paging until exhausted. It reports which unloaded tickets are unread, not how many replies each holds. Those tickets are fetched and merged in only after they pass the same filters the loaded rows passed. [[#client-data #failure-states]]
**What survives a reload?** Filter selections live in memory and reset with the tab. A saved filter reapplies a combination in one step, and also carries the sort. [Saved filters](#tickets/saved-filters) covers that surface. [[#client-data]]
**The filter store and query path.** The store holding the dimensions and mapping them to server parameters is \`packages/client/src/lib/stores/filters.svelte.ts\`. The browser-side narrowing runs in \`packages/client/src/routes/(app)/tickets/+page.svelte\` over \`packages/client/src/lib/tickets/create-list-read-state.svelte.ts\`. The needs-attention rule is \`isNeedsAttention\` in \`packages/client/src/lib/components/dashboard/filters.ts\`. The server clauses are in \`packages/server/src/tickets/ticket-service.ts\`. [[#trust-boundary]]`)
};

const es_demo_narrative_topic_filters_body = /** @type {(inputs: Demo_Narrative_Topic_Filters_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La lista de tickets se puede filtrar por estado, cola, prioridad, persona asignada, rango de fechas de creación, solo no leídos y solo necesita atención. Varias dimensiones pueden estar activas a la vez, y una insignia cuenta cuántas están activas. Borrar todos los filtros reinicia cada dimensión pero deja el orden intacto. [[#metadata]]
**Los cuatro estados.** El filtro de estado ofrece Nuevo, Activo, En espera y Cerrado. El servidor almacena solo abierto y cerrado, más una marca de en espera. Nuevo y Activo son tickets abiertos; el navegador los distingue por si el ticket tiene contacto de cliente o de persona voluntaria. Seleccionar Nuevo junto con Activo es una sola consulta al servidor por tickets abiertos. Cuando se selecciona exactamente uno de los dos, el navegador acota el resultado. En espera corresponde a la marca de en espera. Cerrado corresponde al estado cerrado. [[#server-holds #client-data]]
**¿Qué lado evalúa qué?** El servidor evalúa estado, cola, prioridad, persona asignada y rango de fechas de creación, todos columnas en texto plano de la fila del ticket. El navegador evalúa no leídos y necesita atención, y separa Nuevo de Activo. Antes de que se ejecute cualquier filtro, el servidor restringe la consulta a las colas a las que la cuenta tiene acceso. Un filtro solo puede reducir lo que la cuenta ya tiene permiso para ver, y la pertenencia a una cola es lo que concede ese acceso. [El sistema de permisos](#deep-dive/the-permission-system) trata de dónde viene el acceso. El servidor devuelve 50 tickets por página. El orden predeterminado es actividad más reciente primero. [Ordenación](#tickets/sort) trata las opciones de orden. [[#metadata #trust-boundary #permissions]]
**¿Qué revela una petición de filtro?** Un filtro que evalúa el servidor es un filtro que el servidor puede leer. La petición indica qué cola, qué prioridad, qué persona asignada y qué ventana de fechas está consultando la cuenta, y cuándo. Mantener el estado de no leídos en el navegador oculta cuánto de un ticket ha leído una cuenta. No oculta que la cuenta abrió el ticket. Existe una fila de cursor de lectura por cada ticket que una cuenta ha abierto, y solo la posición dentro de ella está cifrada. [La frontera de confianza](#deep-dive/the-trust-boundary) trata esa fila y las demás de su tipo. [[#server-holds #privacy #metadata]]
**¿Cómo determina el navegador lo no leído?** Un ticket cuenta como no leído cuando su cursor de lectura se descifra a una posición real y alguien distinto de la cuenta que ha iniciado sesión ha añadido actividad desde entonces. Un ticket que nadie ha abierto no tiene fila de cursor y no cuenta como no leído; su marca de Nuevo ya lo indica. El servidor excluye las respuestas propias de la cuenta de ambas fuentes de estado de lectura, de modo que la respuesta propia de una cuenta no queda como no leída para esa cuenta. Los cursores de lectura están cifrados por cuenta. El descifrado ocurre en el worker de criptografía, y el estado descifrado vive solo en el navegador hasta que la cuenta cierra sesión o se cierra la pestaña. Cuando el temporizador de inactividad pone las claves a cero, ese estado se borra y el filtro de no leídos no está disponible hasta el siguiente inicio de sesión. El navegador no envía nada derivado del estado de lectura al servidor. [[#client-data #encryption #privacy #keys]]
**¿Cómo determina el navegador «necesita atención»?** El ticket debe estar abierto, no en espera, y marcado con prioridad urgente o alta. Entonces califica si no tiene persona asignada, o si está asignado a la cuenta que ha iniciado sesión y no se ha leído. El grupo del mismo nombre en el panel principal lee esta misma regla en lugar de una segunda copia, de modo que las dos superficies no pueden diferir. [[#metadata]]
**No leídos más allá de la página cargada.** La lista contiene una página a la vez, de modo que un filtro de no leídos que leyera solo las filas cargadas omitiría tickets no leídos en páginas posteriores. Un barrido aparte enumera las filas de cursor de la cuenta en todos los tickets abiertos a los que la cuenta tiene acceso, paginando hasta agotar. Informa qué tickets no cargados están sin leer, no cuántas respuestas tiene cada uno. Esos tickets se recuperan e incorporan solo después de pasar los mismos filtros que pasaron las filas cargadas. [[#client-data #failure-states]]
**¿Qué sobrevive a una recarga?** Las selecciones de filtro viven en memoria y se reinician con la pestaña. Un filtro guardado vuelve a aplicar una combinación en un solo paso, y también lleva el orden. [Filtros guardados](#tickets/saved-filters) trata esa superficie. [[#client-data]]
**El almacén y la ruta de consulta de filtros.** El almacén que contiene las dimensiones y las traduce a parámetros del servidor es \`packages/client/src/lib/stores/filters.svelte.ts\`. El acotamiento del lado del navegador se ejecuta en \`packages/client/src/routes/(app)/tickets/+page.svelte\` sobre \`packages/client/src/lib/tickets/create-list-read-state.svelte.ts\`. La regla de necesita atención es \`isNeedsAttention\` en \`packages/client/src/lib/components/dashboard/filters.ts\`. Las cláusulas del servidor están en \`packages/server/src/tickets/ticket-service.ts\`. [[#trust-boundary]]`)
};

const en_xa2_demo_narrative_topic_filters_body = /** @type {(inputs: Demo_Narrative_Topic_Filters_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè tìckèt lìst càn bè fìltèrèd by stàtùs, qùèùè, prìòrìty, àssìgnèè, crèàtìòn dàtè ràngè, ùnrèàd ònly, ànd nèèds àttèntìòn ònly. Sèvèràl dìmènsìòns càn bè àctìvè àt òncè, ànd à bàdgè còùnts hòw màny àrè àctìvè. Clèàrìng àll fìltèrs rèsèts èvèry dìmènsìòn bùt lèàvès thè sòrt àlònè. [[#mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fòùr stàtùsès. ••••••** Thè stàtùs fìltèr òffèrs Nèw, Àctìvè, Òn Hòld, ànd Clòsèd. Thè sèrvèr stòrès ònly òpèn ànd clòsèd, plùs àn òn-hòld flàg. Nèw ànd Àctìvè àrè bòth òpèn tìckèts; thè bròwsèr tèlls thèm àpàrt by whèthèr thè tìckèt hàs àny clìènt òr vòlùntèèr còntàct. Sèlèctìng Nèw tògèthèr wìth Àctìvè ìs ònè sèrvèr qùèry fòr òpèn tìckèts. Whèn èxàctly ònè òf thè twò ìs sèlèctèd, thè bròwsèr nàrròws thè rèsùlt fùrthèr. Òn Hòld màps tò thè òn-hòld flàg. Clòsèd màps tò thè clòsèd stàtùs. [[#sèrvèr-hòlds #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whìch sìdè èvàlùàtès whàt? ••••••••** Thè sèrvèr èvàlùàtès stàtùs, qùèùè, prìòrìty, àssìgnèè, ànd crèàtìòn dàtè ràngè, àll òf whìch àrè plàìntèxt còlùmns òn thè tìckèt ròw. Thè bròwsèr èvàlùàtès ùnrèàd ànd nèèds àttèntìòn, ànd sèpàràtès Nèw fròm Àctìvè. Bèfòrè àny fìltèr rùns, thè sèrvèr rèstrìcts thè qùèry tò thè qùèùès thè àccòùnt hàs àccèss tò. À fìltèr càn ònly nàrròw whàt thè àccòùnt àlrèàdy hàs pèrmìssìòn tò sèè, ànd qùèùè mèmbèrshìp ìs whàt grànts thàt àccèss. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs whèrè àccèss còmès fròm. Thè sèrvèr rètùrns 50 tìckèts pèr pàgè. Thè dèfàùlt sòrt ìs mòst rècènt àctìvìty fìrst. [Sòrtìng](#tìckèts/sòrt) còvèrs thè sòrt òptìòns. [[#mètàdàtà #trùst-bòùndàry #pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à fìltèr rèqùèst rèvèàl? •••••••••••** À fìltèr thè sèrvèr èvàlùàtès ìs à fìltèr thè sèrvèr càn rèàd. Thè rèqùèst stàtès whìch qùèùè, whìch prìòrìty, whìch àssìgnèè, ànd whìch dàtè wìndòw thè àccòùnt ìs bròwsìng, ànd whèn. Kèèpìng ùnrèàd ìn thè bròwsèr hìdès hòw mùch òf à tìckèt àn àccòùnt hàs rèàd. Ìt dòès nòt hìdè thàt thè àccòùnt òpènèd thè tìckèt. À rèàd-cùrsòr ròw èxìsts fòr èvèry tìckèt àn àccòùnt hàs òpènèd, ànd ònly thè pòsìtìòn ìnsìdè ìt ìs èncryptèd. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thàt ròw ànd thè òthèrs lìkè ìt. [[#sèrvèr-hòlds #prìvàcy #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè bròwsèr dècìdè ùnrèàd? •••••••••••** À tìckèt ìs ùnrèàd whèn ìts rèàd cùrsòr dècrypts tò à rèàl pòsìtìòn ànd sòmèònè òthèr thàn thè sìgnèd-ìn àccòùnt hàs àddèd àctìvìty sìncè. À tìckèt nòbòdy hàs òpènèd hàs nò cùrsòr ròw ànd ìs nòt ùnrèàd; ìts Nèw màrk àlrèàdy sàys sò. Thè sèrvèr èxclùdès thè àccòùnt's òwn rèplìès fròm bòth rèàd-stàtè sòùrcès, sò àn àccòùnt's òwn rèply ìs nòt ùnrèàd tò thàt àccòùnt. Rèàd cùrsòrs àrè èncryptèd pèr àccòùnt. Dècryptìòn hàppèns ìn thè cryptò wòrkèr, ànd thè dècryptèd stàtè lìvès ònly ìn thè bròwsèr ùntìl thè àccòùnt sìgns òùt òr thè tàb clòsès. Whèn thè ìdlè tìmèr zèròès thè kèys, thàt stàtè ìs clèàrèd ànd thè ùnrèàd fìltèr ìs ùnàvàìlàblè ùntìl thè nèxt sìgn-ìn. Thè bròwsèr nèvèr sènds ànythìng dèrìvèd fròm rèàd stàtè tò thè sèrvèr. [[#clìènt-dàtà #èncryptìòn #prìvàcy #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè bròwsèr dècìdè nèèds àttèntìòn? ••••••••••••••** Thè tìckèt mùst bè òpèn, nòt òn hòld, ànd màrkèd ùrgènt òr hìgh prìòrìty. Ìt thèn qùàlìfìès ìf ìt ìs ùnàssìgnèd, òr ìf ìt ìs àssìgnèd tò thè sìgnèd-ìn àccòùnt ànd ùnrèàd. Thè dàshbòàrd bùckèt òf thè sàmè nàmè rèàds thìs sàmè rùlè ràthèr thàn à sècònd còpy, sò thè twò sùrfàcès cànnòt dìsàgrèè. [[#mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ùnrèàd bèyònd thè lòàdèd pàgè. •••••••••** Thè lìst hòlds ònè pàgè àt à tìmè, sò àn ùnrèàd fìltèr rèàdìng ònly lòàdèd ròws wòùld mìss ùnrèàd tìckèts òn làtèr pàgès. À sèpàràtè swèèp ènùmèràtès thè àccòùnt's cùrsòr ròws àcròss èvèry òpèn tìckèt thè àccòùnt hàs àccèss tò, pàgìng ùntìl èxhàùstèd. Ìt rèpòrts whìch ùnlòàdèd tìckèts àrè ùnrèàd, nòt hòw màny rèplìès èàch hòlds. Thòsè tìckèts àrè fètchèd ànd mèrgèd ìn ònly àftèr thèy pàss thè sàmè fìltèrs thè lòàdèd ròws pàssèd. [[#clìènt-dàtà #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt sùrvìvès à rèlòàd? •••••••** Fìltèr sèlèctìòns lìvè ìn mèmòry ànd rèsèt wìth thè tàb. À sàvèd fìltèr rèàpplìès à còmbìnàtìòn ìn ònè stèp, ànd àlsò càrrìès thè sòrt. [Sàvèd fìltèrs](#tìckèts/sàvèd-fìltèrs) còvèrs thàt sùrfàcè. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fìltèr stòrè ànd qùèry pàth. ••••••••••** Thè stòrè hòldìng thè dìmènsìòns ànd màppìng thèm tò sèrvèr pàràmètèrs ìs \`pàckàgès/clìènt/src/lìb/stòrès/fìltèrs.svèltè.ts\`. Thè bròwsèr-sìdè nàrròwìng rùns ìn \`pàckàgès/clìènt/src/ròùtès/(àpp)/tìckèts/+pàgè.svèltè\` òvèr \`pàckàgès/clìènt/src/lìb/tìckèts/crèàtè-lìst-rèàd-stàtè.svèltè.ts\`. Thè nèèds-àttèntìòn rùlè ìs \`ìsNèèdsÀttèntìòn\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/dàshbòàrd/fìltèrs.ts\`. Thè sèrvèr clàùsès àrè ìn \`pàckàgès/sèrvèr/src/tìckèts/tìckèt-sèrvìcè.ts\`. [[#trùst-bòùndàry]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The ticket list can be filtered by status, queue, priority, assignee, creation date range, unread only, and needs attention only. Several dimensions can be a..." |
*
* @param {Demo_Narrative_Topic_Filters_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_filters_body = /** @type {((inputs?: Demo_Narrative_Topic_Filters_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Filters_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_filters_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_filters_body(inputs)
	return en_demo_narrative_topic_filters_body(inputs)
});