/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Library_Editor_BodyInputs */

const en_demo_narrative_topic_library_editor_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Editor_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`An article is a structured document that the browser encrypts with the organization key before sending. The editor accepts headings, lists, blockquotes, code blocks, tables, links, images, and figures with captions. Writing and editing require the Edit knowledge base permission. [[#permissions #encryption]]
**What does saving encrypt?** Saving serializes the document to JSON and encrypts three separate values in the browser. Those values are the title, the full body, and an excerpt derived from the first 150 characters of the document's text content. The excerpt is encrypted the same way as the title and body before it leaves the browser. Lists and search read the excerpt without fetching the body. All three reach the server as ciphertext it cannot read. [[#encryption #server-holds]]
**How large can an article be?** The browser rejects a serialized document larger than 500 KB before encryption. The server enforces a ceiling on ciphertext size and validates that the encoding is well-formed. [[#encryption #client-data]]
**What does a first save do?** A new article sends title, body, and excerpt ciphertexts in one create call. Each pending inline image then uploads against the new article identifier. A second update replaces the body and excerpt with the final attachment references. A failed image upload is reported before the article is published. Saving again after a failure updates the same article rather than creating a duplicate. A non-image file requires an existing article identifier before the server accepts it, so it cannot be attached until after the first save. [File attachments](#library/attachments) covers the upload path. [[#failure-states]]
**Accessibility checks.** The editor scans the document in the browser for heading levels that skip a rank, headings with no text, images without alt text, and link labels too generic to be useful. Alt text is requested before each image is inserted, with an option to mark the image as decorative. Nothing in the scan reaches the server. [[#client-data]]
**The ProseMirror document model and save path.** The schema is in \`packages/client/src/lib/editor/prosemirror-schema.ts\`. The accessibility scan is \`checkDocument\` in \`editor/atag-checks.ts\`. The save is \`handleSave\` in \`packages/client/src/lib/components/library/ArticleEditor.svelte\`, calling \`createItem\` and \`updateItem\` in \`packages/server/src/routes/kb.ts\`. [The trust boundary](#deep-dive/the-trust-boundary) covers the full server schema. [[#client-data]]`)
};

const es_demo_narrative_topic_library_editor_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Editor_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un artículo es un documento estructurado que el navegador cifra con la clave de organización antes de enviarlo. El editor acepta encabezados, listas, citas, bloques de código, tablas, enlaces, imágenes y figuras con pie de imagen. Escribir y editar requiere el permiso Editar base de conocimiento. [[#permissions #encryption]]
**¿Qué cifra el guardado?** Guardar serializa el documento a JSON y cifra tres valores separados en el navegador. Esos valores son el título, el cuerpo completo y un extracto derivado de los primeros 150 caracteres del texto del documento. El extracto se cifra igual que el título y el cuerpo antes de salir del navegador. Las listas y la búsqueda leen el extracto sin descargar el cuerpo. Los tres llegan al servidor como texto cifrado que no puede leer. [[#encryption #server-holds]]
**¿Cuánto puede ocupar un artículo?** El navegador rechaza un documento serializado mayor de 500 KB antes del cifrado. El servidor impone un techo sobre el tamaño del texto cifrado y valida que la codificación esté bien formada. [[#encryption #client-data]]
**¿Qué hace el primer guardado?** Un artículo nuevo envía los textos cifrados de título, cuerpo y extracto en una sola llamada de creación. Cada imagen en línea pendiente se sube contra el nuevo identificador del artículo. Una segunda actualización reemplaza el cuerpo y el extracto con las referencias finales a los adjuntos. Un fallo en la subida de una imagen se reporta antes de que el artículo se publique. Guardar de nuevo tras un fallo actualiza el mismo artículo en lugar de crear un duplicado. Un archivo que no es imagen necesita un identificador de artículo existente para que el servidor lo acepte, por lo que no se puede adjuntar hasta después del primer guardado. [Archivos adjuntos](#library/attachments) trata la ruta de subida. [[#failure-states]]
**Comprobaciones de accesibilidad.** El editor analiza el documento en el navegador en busca de niveles de encabezado que saltan un rango, encabezados sin texto, imágenes sin texto alternativo y etiquetas de enlace demasiado genéricas para ser útiles. Se solicita texto alternativo antes de insertar cada imagen, con la opción de marcarla como decorativa. Nada en el análisis llega al servidor. [[#client-data]]
**El modelo de documento ProseMirror y la ruta de guardado.** El esquema está en \`packages/client/src/lib/editor/prosemirror-schema.ts\`. El análisis de accesibilidad es \`checkDocument\` en \`editor/atag-checks.ts\`. El guardado es \`handleSave\` en \`packages/client/src/lib/components/library/ArticleEditor.svelte\`, que llama a \`createItem\` y \`updateItem\` en \`packages/server/src/routes/kb.ts\`. [La frontera de confianza](#deep-dive/the-trust-boundary) trata el esquema completo del servidor. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_library_editor_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Editor_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Àn àrtìclè ìs à strùctùrèd dòcùmènt thàt thè bròwsèr èncrypts wìth thè òrgànìzàtìòn kèy bèfòrè sèndìng. Thè èdìtòr àccèpts hèàdìngs, lìsts, blòckqùòtès, còdè blòcks, tàblès, lìnks, ìmàgès, ànd fìgùrès wìth càptìòns. Wrìtìng ànd èdìtìng rèqùìrè thè Èdìt knòwlèdgè bàsè pèrmìssìòn. [[#pèrmìssìòns #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès sàvìng èncrypt? ••••••••** Sàvìng sèrìàlìzès thè dòcùmènt tò JSÒN ànd èncrypts thrèè sèpàràtè vàlùès ìn thè bròwsèr. Thòsè vàlùès àrè thè tìtlè, thè fùll bòdy, ànd àn èxcèrpt dèrìvèd fròm thè fìrst 150 chàràctèrs òf thè dòcùmènt's tèxt còntènt. Thè èxcèrpt ìs èncryptèd thè sàmè wày às thè tìtlè ànd bòdy bèfòrè ìt lèàvès thè bròwsèr. Lìsts ànd sèàrch rèàd thè èxcèrpt wìthòùt fètchìng thè bòdy. Àll thrèè rèàch thè sèrvèr às cìphèrtèxt ìt cànnòt rèàd. [[#èncryptìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw làrgè càn àn àrtìclè bè? •••••••••** Thè bròwsèr rèjècts à sèrìàlìzèd dòcùmènt làrgèr thàn 500 KB bèfòrè èncryptìòn. Thè sèrvèr ènfòrcès à cèìlìng òn cìphèrtèxt sìzè ànd vàlìdàtès thàt thè èncòdìng ìs wèll-fòrmèd. [[#èncryptìòn #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à fìrst sàvè dò? ••••••••** À nèw àrtìclè sènds tìtlè, bòdy, ànd èxcèrpt cìphèrtèxts ìn ònè crèàtè càll. Èàch pèndìng ìnlìnè ìmàgè thèn ùplòàds àgàìnst thè nèw àrtìclè ìdèntìfìèr. À sècònd ùpdàtè rèplàcès thè bòdy ànd èxcèrpt wìth thè fìnàl àttàchmènt rèfèrèncès. À fàìlèd ìmàgè ùplòàd ìs rèpòrtèd bèfòrè thè àrtìclè ìs pùblìshèd. Sàvìng àgàìn àftèr à fàìlùrè ùpdàtès thè sàmè àrtìclè ràthèr thàn crèàtìng à dùplìcàtè. À nòn-ìmàgè fìlè rèqùìrès àn èxìstìng àrtìclè ìdèntìfìèr bèfòrè thè sèrvèr àccèpts ìt, sò ìt cànnòt bè àttàchèd ùntìl àftèr thè fìrst sàvè. [Fìlè àttàchmènts](#lìbràry/àttàchmènts) còvèrs thè ùplòàd pàth. [[#fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àccèssìbìlìty chècks. •••••••** Thè èdìtòr scàns thè dòcùmènt ìn thè bròwsèr fòr hèàdìng lèvèls thàt skìp à rànk, hèàdìngs wìth nò tèxt, ìmàgès wìthòùt àlt tèxt, ànd lìnk làbèls tòò gènèrìc tò bè ùsèfùl. Àlt tèxt ìs rèqùèstèd bèfòrè èàch ìmàgè ìs ìnsèrtèd, wìth àn òptìòn tò màrk thè ìmàgè às dècòràtìvè. Nòthìng ìn thè scàn rèàchès thè sèrvèr. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè PròsèMìrròr dòcùmènt mòdèl ànd sàvè pàth. ••••••••••••••** Thè schèmà ìs ìn \`pàckàgès/clìènt/src/lìb/èdìtòr/pròsèmìrròr-schèmà.ts\`. Thè àccèssìbìlìty scàn ìs \`chèckDòcùmènt\` ìn \`èdìtòr/àtàg-chècks.ts\`. Thè sàvè ìs \`hàndlèSàvè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/lìbràry/ÀrtìclèÈdìtòr.svèltè\`, càllìng \`crèàtèÌtèm\` ànd \`ùpdàtèÌtèm\` ìn \`pàckàgès/sèrvèr/src/ròùtès/kb.ts\`. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè fùll sèrvèr schèmà. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "An article is a structured document that the browser encrypts with the organization key before sending. The editor accepts headings, lists, blockquotes, code..." |
*
* @param {Demo_Narrative_Topic_Library_Editor_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_library_editor_body = /** @type {((inputs?: Demo_Narrative_Topic_Library_Editor_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Library_Editor_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_library_editor_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_library_editor_body(inputs)
	return en_demo_narrative_topic_library_editor_body(inputs)
});