/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Response_Export_BodyInputs */

const en_demo_narrative_admin_response_export_body = /** @type {(inputs: Demo_Narrative_Admin_Response_Export_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The browser assembles the CSV from responses it has already decrypted. The server sends nothing new for the export, and no plaintext leaves the device until the user saves the file. The export button is disabled while any row is still decrypting. [[#encryption #client-data]]
**What goes into the file?** The first column is the submission timestamp, followed by one column per field the form currently defines, in the form's field order. Rows the user could not decrypt are excluded, not exported blank. A confirmation dialog reports how many responses will be exported and how many will be skipped. Only pages already loaded in the viewer are in scope. Responses from unloaded pages do not appear in the file and are not reflected in the skip count. [Response cards](#admin-responses/responses) covers how pages load. [[#failure-states]]
**Answers to removed or relabelled fields.** The viewer and the export both read field labels from the form's current definition. Each save replaces the full field list, so an answer to a relabelled field appears under the new question and an answer to a removed field appears as "Unknown field" in the viewer with no column in the CSV. A form edited between submission and export can produce a file narrower than what visitors actually submitted. [Field list](#admin-forms/builder) covers what changing a field does. [[#client-data]]
**The file is plaintext.** The confirmation dialog states that the file contains unencrypted client data before the download starts. The encryption that protects answers inside CARE-Y covers the path up to this point, not the file afterwards. Where the file goes after download is a decision made outside the system. Cells that would otherwise trigger formula interpretation in a spreadsheet are prefixed so they are treated as text. [The trust boundary](#deep-dive/the-trust-boundary) covers where encryption applies and where it stops. [[#privacy #encryption]]
**The assembler and the audit record.** \`assembleIntakeCsv\` in \`packages/client/src/lib/export/intake-csv.ts\` handles quoting and formula prefixing, following RFC 4180 and the OWASP CSV injection guidance cited in the module. \`logExport\` in \`packages/server/src/routes/intake-forms.ts\` records the form ID and both counts before the file is offered. The download proceeds even when the audit write fails, so a plaintext export can complete with no audit trace. [Audit log](#admin-logs/audit) covers the log itself. [[#metadata]]`)
};

const es_demo_narrative_admin_response_export_body = /** @type {(inputs: Demo_Narrative_Admin_Response_Export_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El navegador arma el CSV a partir de las respuestas que ya descifró. El servidor no envía nada nuevo para la exportación, y ningún texto en claro sale del dispositivo hasta que la persona usuaria guarda el archivo. El botón de exportación se deshabilita mientras alguna fila sigue descifrándose. [[#encryption #client-data]]
**¿Qué entra en el archivo?** La primera columna es la marca de tiempo del envío, seguida de una columna por cada campo que el formulario define actualmente, en el orden del formulario. Las filas que la persona usuaria no pudo descifrar se excluyen en lugar de exportarse en blanco. Un diálogo de confirmación informa cuántas respuestas se exportarán y cuántas se omitirán. Solo entran las páginas ya cargadas en el visor. Las respuestas de páginas no cargadas no aparecen en el archivo ni se reflejan en el recuento de omitidas. [Tarjetas de respuesta](#admin-responses/responses) trata cómo se cargan las páginas. [[#failure-states]]
**Respuestas a campos eliminados o renombrados.** El visor y la exportación leen las etiquetas de campo de la definición actual del formulario. Cada guardado reemplaza la lista completa de campos, de modo que una respuesta a un campo renombrado aparece bajo la pregunta nueva y una respuesta a un campo eliminado aparece como "Campo desconocido" en el visor, sin columna en el CSV. Un formulario editado entre el envío y la exportación puede producir un archivo más estrecho que lo que los visitantes enviaron. [Lista de campos](#admin-forms/builder) trata qué ocurre al modificar un campo. [[#client-data]]
**El archivo es texto plano.** El diálogo de confirmación indica que el archivo contiene datos de clientes sin cifrar antes de que comience la descarga. El cifrado que protege las respuestas dentro de CARE-Y cubre el camino hasta este punto, no el archivo posterior. Adónde va el archivo tras la descarga es una decisión que se toma fuera del sistema. Las celdas que de otro modo activarían la interpretación de fórmulas en una hoja de cálculo llevan un prefijo para que se traten como texto. [La frontera de confianza](#deep-dive/the-trust-boundary) trata dónde se aplica el cifrado y dónde termina. [[#privacy #encryption]]
**El ensamblador y el registro de auditoría.** \`assembleIntakeCsv\`, en \`packages/client/src/lib/export/intake-csv.ts\`, se encarga del entrecomillado y del prefijo de fórmulas, siguiendo la RFC 4180 y la guía de OWASP sobre inyección CSV citada en el módulo. \`logExport\`, en \`packages/server/src/routes/intake-forms.ts\`, registra el ID del formulario y ambos recuentos antes de ofrecer el archivo. La descarga sigue adelante aunque la escritura de auditoría falle, de modo que una exportación en texto plano puede completarse sin traza de auditoría. [Registro de auditoría](#admin-logs/audit) trata el registro en sí. [[#metadata]]`)
};

const en_xa2_demo_narrative_admin_response_export_body = /** @type {(inputs: Demo_Narrative_Admin_Response_Export_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè bròwsèr àssèmblès thè CSV fròm rèspònsès ìt hàs àlrèàdy dècryptèd. Thè sèrvèr sènds nòthìng nèw fòr thè èxpòrt, ànd nò plàìntèxt lèàvès thè dèvìcè ùntìl thè ùsèr sàvès thè fìlè. Thè èxpòrt bùttòn ìs dìsàblèd whìlè àny ròw ìs stìll dècryptìng. [[#èncryptìòn #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt gòès ìntò thè fìlè? ••••••••** Thè fìrst còlùmn ìs thè sùbmìssìòn tìmèstàmp, fòllòwèd by ònè còlùmn pèr fìèld thè fòrm cùrrèntly dèfìnès, ìn thè fòrm's fìèld òrdèr. Ròws thè ùsèr còùld nòt dècrypt àrè èxclùdèd, nòt èxpòrtèd blànk. À cònfìrmàtìòn dìàlòg rèpòrts hòw màny rèspònsès wìll bè èxpòrtèd ànd hòw màny wìll bè skìppèd. Ònly pàgès àlrèàdy lòàdèd ìn thè vìèwèr àrè ìn scòpè. Rèspònsès fròm ùnlòàdèd pàgès dò nòt àppèàr ìn thè fìlè ànd àrè nòt rèflèctèd ìn thè skìp còùnt. [Rèspònsè càrds](#àdmìn-rèspònsès/rèspònsès) còvèrs hòw pàgès lòàd. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ànswèrs tò rèmòvèd òr rèlàbèllèd fìèlds. ••••••••••••** Thè vìèwèr ànd thè èxpòrt bòth rèàd fìèld làbèls fròm thè fòrm's cùrrènt dèfìnìtìòn. Èàch sàvè rèplàcès thè fùll fìèld lìst, sò àn ànswèr tò à rèlàbèllèd fìèld àppèàrs ùndèr thè nèw qùèstìòn ànd àn ànswèr tò à rèmòvèd fìèld àppèàrs às "Ùnknòwn fìèld" ìn thè vìèwèr wìth nò còlùmn ìn thè CSV. À fòrm èdìtèd bètwèèn sùbmìssìòn ànd èxpòrt càn pròdùcè à fìlè nàrròwèr thàn whàt vìsìtòrs àctùàlly sùbmìttèd. [Fìèld lìst](#àdmìn-fòrms/bùìldèr) còvèrs whàt chàngìng à fìèld dòès. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fìlè ìs plàìntèxt. •••••••** Thè cònfìrmàtìòn dìàlòg stàtès thàt thè fìlè còntàìns ùnèncryptèd clìènt dàtà bèfòrè thè dòwnlòàd stàrts. Thè èncryptìòn thàt pròtècts ànswèrs ìnsìdè CÀRÈ-Y còvèrs thè pàth ùp tò thìs pòìnt, nòt thè fìlè àftèrwàrds. Whèrè thè fìlè gòès àftèr dòwnlòàd ìs à dècìsìòn màdè òùtsìdè thè systèm. Cèlls thàt wòùld òthèrwìsè trìggèr fòrmùlà ìntèrprètàtìòn ìn à sprèàdshèèt àrè prèfìxèd sò thèy àrè trèàtèd às tèxt. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whèrè èncryptìòn àpplìès ànd whèrè ìt stòps. [[#prìvàcy #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè àssèmblèr ànd thè àùdìt rècòrd. •••••••••••** \`àssèmblèÌntàkèCsv\` ìn \`pàckàgès/clìènt/src/lìb/èxpòrt/ìntàkè-csv.ts\` hàndlès qùòtìng ànd fòrmùlà prèfìxìng, fòllòwìng RFC 4180 ànd thè ÒWÀSP CSV ìnjèctìòn gùìdàncè cìtèd ìn thè mòdùlè. \`lògÈxpòrt\` ìn \`pàckàgès/sèrvèr/src/ròùtès/ìntàkè-fòrms.ts\` rècòrds thè fòrm ÌD ànd bòth còùnts bèfòrè thè fìlè ìs òffèrèd. Thè dòwnlòàd pròcèèds èvèn whèn thè àùdìt wrìtè fàìls, sò à plàìntèxt èxpòrt càn còmplètè wìth nò àùdìt tràcè. [Àùdìt lòg](#àdmìn-lògs/àùdìt) còvèrs thè lòg ìtsèlf. [[#mètàdàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The browser assembles the CSV from responses it has already decrypted. The server sends nothing new for the export, and no plaintext leaves the device until ..." |
*
* @param {Demo_Narrative_Admin_Response_Export_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_response_export_body = /** @type {((inputs?: Demo_Narrative_Admin_Response_Export_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Response_Export_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_response_export_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_response_export_body(inputs)
	return en_demo_narrative_admin_response_export_body(inputs)
});