/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Exposure_Hints_BodyInputs */

const en_demo_narrative_topic_exposure_hints_body = /** @type {(inputs: Demo_Narrative_Topic_Exposure_Hints_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Sending a text or placing a call leaves the encrypted path. The browser warns once per channel per session that the phone provider can read or hear the content. Email carries its own warnings on the compose surface and on each inbound message. [[#privacy #telephony]]
**The two passing notices.** The text notice says that SMS is not encrypted and that the phone provider can read it. The call notice says the call routes through the phone provider and that the provider can hear it. Both name the phone provider rather than calling the channel insecure, because the exposure is to a specific company that keeps records and answers legal demands. [The telephony relay](#deep-dive/the-telephony-relay) covers what the carrier and the provider hold. [[#telephony #server-holds]]
**When does each notice appear?** The text notice appears when the user picks the text option from the compose menu, before any message is drafted. The call notice appears before the call starts, when the user chooses to place it. Each channel type triggers its warning only once; navigating away from the ticket and returning does not repeat it, but reloading the page does. Neither notice prevents the action from completing. A notice disappears after six seconds or when the user dismisses it. [[#failure-states]]
**Email warnings.** Choosing email does not trigger a passing notice. The email compose surface carries a persistent warning that the channel is unencrypted, and every inbound email follow-up carries a separate caution that a sender's address is easy to fake. [Email in the conversation](#ticket-detail/email-thread) covers both. [[#privacy]]
**What do the notices leave out?** The notices name the party that gains access to the content. They do not address delivery confirmation or anything that happens on the receiving end after the content leaves the provider. [Share link status](#ticket-detail/share-status) covers delivery reporting for share links. [[#failure-states]]
**The composable and the component.** \`create-exposure-hint.svelte.ts\` in \`packages/client/src/lib/composables/ticket-detail/\` holds the shown set at module scope, outside the factory function, so it outlasts any single component mount. \`ExposureHint.svelte\` in \`packages/client/src/lib/components/tickets/\` renders the notice. The client-side equivalent is [How the reader is protected](#client-share/exposure-hint). [[#client-data]]`)
};

const es_demo_narrative_topic_exposure_hints_body = /** @type {(inputs: Demo_Narrative_Topic_Exposure_Hints_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Enviar un mensaje de texto o realizar una llamada sale del camino cifrado. El navegador avisa una vez por canal y por sesión de que el proveedor de telefonía puede leer u oír el contenido. El correo electrónico lleva sus propias advertencias en la superficie de composición y en cada mensaje entrante. [[#privacy #telephony]]
**Los dos avisos pasajeros.** El aviso del mensaje de texto dice que los SMS no están cifrados y que el proveedor de telefonía puede leerlos. El aviso de la llamada dice que la llamada pasa por el proveedor de telefonía y que el proveedor puede oírla. Ambos nombran al proveedor en lugar de llamar inseguro al canal, porque la exposición es ante una empresa concreta que guarda registros y responde a requerimientos legales. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que guardan la operadora y el proveedor. [[#telephony #server-holds]]
**¿Cuándo aparece cada aviso?** El aviso del mensaje de texto aparece cuando la persona usuaria elige la opción de texto en el menú de composición, antes de redactar nada. El aviso de la llamada aparece antes de que la llamada comience, cuando la persona usuaria elige realizarla. Cada tipo de canal activa su advertencia solo una vez; salir del ticket y volver no la repite, pero recargar la página sí. Ninguno de los dos avisos impide que la acción se complete. El aviso desaparece a los seis segundos o cuando la persona usuaria lo cierra. [[#failure-states]]
**Advertencias del correo electrónico.** Elegir correo electrónico no activa un aviso pasajero. La superficie de composición de correo lleva una advertencia permanente de que el canal no está cifrado, y cada correo entrante lleva una advertencia aparte de que la dirección del remitente es fácil de falsificar. [Correo electrónico en la conversación](#ticket-detail/email-thread) trata ambas. [[#privacy]]
**¿Qué omiten los avisos?** Los avisos nombran a la parte que obtiene acceso al contenido. No cubren la confirmación de entrega ni lo que ocurra en el extremo receptor una vez que el contenido sale del proveedor. [Estado del enlace compartido](#ticket-detail/share-status) trata la notificación de entrega para los enlaces compartidos. [[#failure-states]]
**El composable y el componente.** \`create-exposure-hint.svelte.ts\` en \`packages/client/src/lib/composables/ticket-detail/\` guarda el conjunto de tipos mostrados a nivel de módulo, fuera de la función fábrica, de modo que sobrevive al desmontaje de cualquier componente individual. \`ExposureHint.svelte\` en \`packages/client/src/lib/components/tickets/\` muestra el aviso. El equivalente del lado del cliente es [Cómo se protege al lector](#client-share/exposure-hint). [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_exposure_hints_body = /** @type {(inputs: Demo_Narrative_Topic_Exposure_Hints_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Sèndìng à tèxt òr plàcìng à càll lèàvès thè èncryptèd pàth. Thè bròwsèr wàrns òncè pèr chànnèl pèr sèssìòn thàt thè phònè pròvìdèr càn rèàd òr hèàr thè còntènt. Èmàìl càrrìès ìts òwn wàrnìngs òn thè còmpòsè sùrfàcè ànd òn èàch ìnbòùnd mèssàgè. [[#prìvàcy #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè twò pàssìng nòtìcès. ••••••••** Thè tèxt nòtìcè sàys thàt SMS ìs nòt èncryptèd ànd thàt thè phònè pròvìdèr càn rèàd ìt. Thè càll nòtìcè sàys thè càll ròùtès thròùgh thè phònè pròvìdèr ànd thàt thè pròvìdèr càn hèàr ìt. Bòth nàmè thè phònè pròvìdèr ràthèr thàn càllìng thè chànnèl ìnsècùrè, bècàùsè thè èxpòsùrè ìs tò à spècìfìc còmpàny thàt kèèps rècòrds ànd ànswèrs lègàl dèmànds. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt thè càrrìèr ànd thè pròvìdèr hòld. [[#tèlèphòny #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn dòès èàch nòtìcè àppèàr? •••••••••** Thè tèxt nòtìcè àppèàrs whèn thè ùsèr pìcks thè tèxt òptìòn fròm thè còmpòsè mènù, bèfòrè àny mèssàgè ìs dràftèd. Thè càll nòtìcè àppèàrs bèfòrè thè càll stàrts, whèn thè ùsèr chòòsès tò plàcè ìt. Èàch chànnèl typè trìggèrs ìts wàrnìng ònly òncè; nàvìgàtìng àwày fròm thè tìckèt ànd rètùrnìng dòès nòt rèpèàt ìt, bùt rèlòàdìng thè pàgè dòès. Nèìthèr nòtìcè prèvènts thè àctìòn fròm còmplètìng. À nòtìcè dìsàppèàrs àftèr sìx sècònds òr whèn thè ùsèr dìsmìssès ìt. [[#fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èmàìl wàrnìngs. •••••** Chòòsìng èmàìl dòès nòt trìggèr à pàssìng nòtìcè. Thè èmàìl còmpòsè sùrfàcè càrrìès à pèrsìstènt wàrnìng thàt thè chànnèl ìs ùnèncryptèd, ànd èvèry ìnbòùnd èmàìl fòllòw-ùp càrrìès à sèpàràtè càùtìòn thàt à sèndèr's àddrèss ìs èàsy tò fàkè. [Èmàìl ìn thè cònvèrsàtìòn](#tìckèt-dètàìl/èmàìl-thrèàd) còvèrs bòth. [[#prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dò thè nòtìcès lèàvè òùt? •••••••••** Thè nòtìcès nàmè thè pàrty thàt gàìns àccèss tò thè còntènt. Thèy dò nòt àddrèss dèlìvèry cònfìrmàtìòn òr ànythìng thàt hàppèns òn thè rècèìvìng ènd àftèr thè còntènt lèàvès thè pròvìdèr. [Shàrè lìnk stàtùs](#tìckèt-dètàìl/shàrè-stàtùs) còvèrs dèlìvèry rèpòrtìng fòr shàrè lìnks. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còmpòsàblè ànd thè còmpònènt. ••••••••••** \`crèàtè-èxpòsùrè-hìnt.svèltè.ts\` ìn \`pàckàgès/clìènt/src/lìb/còmpòsàblès/tìckèt-dètàìl/\` hòlds thè shòwn sèt àt mòdùlè scòpè, òùtsìdè thè fàctòry fùnctìòn, sò ìt òùtlàsts àny sìnglè còmpònènt mòùnt. \`ÈxpòsùrèHìnt.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/tìckèts/\` rèndèrs thè nòtìcè. Thè clìènt-sìdè èqùìvàlènt ìs [Hòw thè rèàdèr ìs pròtèctèd](#clìènt-shàrè/èxpòsùrè-hìnt). [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Sending a text or placing a call leaves the encrypted path. The browser warns once per channel per session that the phone provider can read or hear the conte..." |
*
* @param {Demo_Narrative_Topic_Exposure_Hints_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_exposure_hints_body = /** @type {((inputs?: Demo_Narrative_Topic_Exposure_Hints_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Exposure_Hints_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_exposure_hints_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_exposure_hints_body(inputs)
	return en_demo_narrative_topic_exposure_hints_body(inputs)
});