/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Key_Derivation_BodyInputs */

const en_demo_narrative_topic_key_derivation_body = /** @type {(inputs: Demo_Narrative_Topic_Key_Derivation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The browser stretches the password with Argon2id using 64 MB of memory and four passes before producing any key material. This cost makes each offline guess expensive for anyone running passwords against a stolen database. [[#keys #encryption]]
**Argon2id cost floor.** A minimum cost is compiled into the browser code. The server suggests its own value, and the browser accepts it only when it is higher. A compromised server can make the stretching slower but cannot make it cheaper. [[#keys #server-holds]]
**Account salt and enumeration defense.** The server provides a unique salt per account. A request for an account that does not exist returns a deterministic fake salt that a caller cannot distinguish from a real one. [Username and password](#login/credentials) covers the part of the password that the server receives. [[#keys #server-holds]]
**Blinded input to the two servers.** The stretched password does not leave the browser. The browser mixes a random number into the value and sends only the blinded result. Only the browser knows the random number. Two independent servers each compute on this blinded input. Neither server learns the original password, the stretched value, the final output, or what the other server contributed. When the servers reply, the browser removes the random number to recover the true result. Each server holds one share of a key that never exists whole in one place. This technique is called an oblivious pseudorandom function (OPRF). [How keys are derived](#deep-dive/how-keys-are-derived) covers the full protocol and the key hierarchy it feeds. [[#keys #encryption]]
**Server isolation and jurisdiction split.** Each of the two servers runs its share inside a privilege-dropped process. The share is held in locked, read-only memory. The two servers operate in different legal jurisdictions. One is in the EU and one is in Iceland. They communicate over mutually authenticated TLS, not a local socket. A legal order served in one country reaches at most one of the two servers. Both shares are re-randomized every twenty-four hours. A share copied during one period is incompatible with its counterpart in the next. [[#trust-boundary #keys]]
**Derived keys and their separation.** The combined output from the two servers is expanded into two results: a personal keypair and the key that unwraps the organization's shared key. Each is derived under its own label. Neither can be computed from the other. Until this derivation finishes, the browser tab holds nothing that can decrypt a case. [[#encryption #keys]]
**What does a database dump contain?** Nothing derived from the password is stored. A database dump contains no key material. An attacker would need both servers' shares, the account's password, and the account's second factor. The derivation begins only after the second factor has been accepted. [The trust boundary](#deep-dive/the-trust-boundary) covers what a dump does contain. [[#trust-boundary #server-holds]]
**Key-derivation pipeline source.** The browser pipeline is \`packages/client/src/lib/auth/login-crypto.ts\` running inside \`packages/client/src/lib/workers/crypto.worker.ts\`. The primitives are \`packages/crypto/src/derive.ts\` and \`packages/crypto/src/oprf.ts\`. The per-server OPRF processes are \`packages/server/src/crypto/oprf-process.ts\` and \`oprf-server.ts\`, reached through \`oprf-ipc.ts\`. Rate limiting and proof-of-work gating are in \`oprf-evaluate-service.ts\`. [[#keys #server-holds]]`)
};

const es_demo_narrative_topic_key_derivation_body = /** @type {(inputs: Demo_Narrative_Topic_Key_Derivation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El navegador estira la contraseña con Argon2id usando 64 MB de memoria y cuatro pasadas antes de producir cualquier material de clave. Este coste encarece cada intento fuera de línea para quien ejecute contraseñas contra una base de datos robada. [[#keys #encryption]]
**Umbral de coste de Argon2id.** Un coste mínimo está compilado en el código del navegador. El servidor sugiere su propio valor, y el navegador lo acepta solo cuando es mayor. Un servidor comprometido puede hacer el proceso más lento, pero no puede abaratarlo. [[#keys #server-holds]]
**Sal por cuenta y defensa contra enumeración.** El servidor proporciona una sal única por cuenta. Una solicitud de una cuenta que no existe devuelve una sal falsa determinista que quien consulta no puede distinguir de una real. [Nombre de usuario y contraseña](#login/credentials) cubre la parte de la contraseña que el servidor recibe. [[#keys #server-holds]]
**Entrada cegada para los dos servidores.** La contraseña estirada no sale del navegador. El navegador mezcla un número aleatorio en el valor y envía solo el resultado cegado. Solo el navegador conoce el número aleatorio. Dos servidores independientes computan sobre esta entrada cegada. Ningún servidor conoce la contraseña original, el valor estirado, el resultado final ni la contribución del otro servidor. Cuando los servidores responden, el navegador elimina el número aleatorio para recuperar el resultado verdadero. Cada servidor posee un fragmento de una clave que nunca existe completa en un solo lugar. Esta técnica se denomina función pseudoaleatoria inconsciente (OPRF, por sus siglas en inglés). [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) cubre el protocolo completo y la jerarquía de claves que alimenta. [[#keys #encryption]]
**Aislamiento de servidores y separación jurisdiccional.** Cada uno de los dos servidores ejecuta su fragmento dentro de un proceso con privilegios reducidos. El fragmento se mantiene en memoria bloqueada y de solo lectura. Los dos servidores operan en jurisdicciones legales distintas. Uno está en la UE y el otro en Islandia. Se comunican mediante TLS con autenticación mutua, no por un socket local. Una orden judicial emitida en un país alcanza como máximo a uno de los dos servidores. Ambos fragmentos se re-aleatorizan cada veinticuatro horas. Un fragmento copiado durante un periodo es incompatible con su par en el siguiente. [[#trust-boundary #keys]]
**Claves derivadas y su separación.** La salida combinada de los dos servidores se expande en dos resultados: un par de claves personal y la clave que desenvuelve la clave compartida de la organización. Cada una se deriva bajo su propia etiqueta. Ninguna puede calcularse a partir de la otra. Hasta que esta derivación termine, la pestaña del navegador no contiene nada que pueda descifrar un caso. [[#encryption #keys]]
**¿Qué contiene un volcado de base de datos?** Nada derivado de la contraseña se almacena. Un volcado de la base de datos no contiene material de clave. Un atacante necesitaría los fragmentos de ambos servidores, la contraseña de la cuenta y el segundo factor de la cuenta. La derivación comienza solo después de que el segundo factor haya sido aceptado. [El límite de confianza](#deep-dive/the-trust-boundary) cubre lo que un volcado sí contiene. [[#trust-boundary #server-holds]]
**Código fuente del pipeline de derivación de claves.** El pipeline del navegador es \`packages/client/src/lib/auth/login-crypto.ts\` ejecutándose dentro de \`packages/client/src/lib/workers/crypto.worker.ts\`. Las primitivas son \`packages/crypto/src/derive.ts\` y \`packages/crypto/src/oprf.ts\`. Los procesos OPRF por servidor son \`packages/server/src/crypto/oprf-process.ts\` y \`oprf-server.ts\`, alcanzados a través de \`oprf-ipc.ts\`. La limitación de tasa y la validación de prueba de trabajo están en \`oprf-evaluate-service.ts\`. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_topic_key_derivation_body = /** @type {(inputs: Demo_Narrative_Topic_Key_Derivation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè bròwsèr strètchès thè pàsswòrd wìth Àrgòn2ìd ùsìng 64 MB òf mèmòry ànd fòùr pàssès bèfòrè pròdùcìng àny kèy màtèrìàl. Thìs còst màkès èàch òfflìnè gùèss èxpènsìvè fòr ànyònè rùnnìng pàsswòrds àgàìnst à stòlèn dàtàbàsè. [[#kèys #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àrgòn2ìd còst flòòr. ••••••** À mìnìmùm còst ìs còmpìlèd ìntò thè bròwsèr còdè. Thè sèrvèr sùggèsts ìts òwn vàlùè, ànd thè bròwsèr àccèpts ìt ònly whèn ìt ìs hìghèr. À còmpròmìsèd sèrvèr càn màkè thè strètchìng slòwèr bùt cànnòt màkè ìt chèàpèr. [[#kèys #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àccòùnt sàlt ànd ènùmèràtìòn dèfènsè. ••••••••••••** Thè sèrvèr pròvìdès à ùnìqùè sàlt pèr àccòùnt. À rèqùèst fòr àn àccòùnt thàt dòès nòt èxìst rètùrns à dètèrmìnìstìc fàkè sàlt thàt à càllèr cànnòt dìstìngùìsh fròm à rèàl ònè. [Ùsèrnàmè ànd pàsswòrd](#lògìn/crèdèntìàls) còvèrs thè pàrt òf thè pàsswòrd thàt thè sèrvèr rècèìvès. [[#kèys #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Blìndèd ìnpùt tò thè twò sèrvèrs. ••••••••••** Thè strètchèd pàsswòrd dòès nòt lèàvè thè bròwsèr. Thè bròwsèr mìxès à ràndòm nùmbèr ìntò thè vàlùè ànd sènds ònly thè blìndèd rèsùlt. Ònly thè bròwsèr knòws thè ràndòm nùmbèr. Twò ìndèpèndènt sèrvèrs èàch còmpùtè òn thìs blìndèd ìnpùt. Nèìthèr sèrvèr lèàrns thè òrìgìnàl pàsswòrd, thè strètchèd vàlùè, thè fìnàl òùtpùt, òr whàt thè òthèr sèrvèr còntrìbùtèd. Whèn thè sèrvèrs rèply, thè bròwsèr rèmòvès thè ràndòm nùmbèr tò rècòvèr thè trùè rèsùlt. Èàch sèrvèr hòlds ònè shàrè òf à kèy thàt nèvèr èxìsts whòlè ìn ònè plàcè. Thìs tèchnìqùè ìs càllèd àn òblìvìòùs psèùdòràndòm fùnctìòn (ÒPRF). [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs thè fùll pròtòcòl ànd thè kèy hìèràrchy ìt fèèds. [[#kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèrvèr ìsòlàtìòn ànd jùrìsdìctìòn splìt. ••••••••••••** Èàch òf thè twò sèrvèrs rùns ìts shàrè ìnsìdè à prìvìlègè-dròppèd pròcèss. Thè shàrè ìs hèld ìn lòckèd, rèàd-ònly mèmòry. Thè twò sèrvèrs òpèràtè ìn dìffèrènt lègàl jùrìsdìctìòns. Ònè ìs ìn thè ÈÙ ànd ònè ìs ìn Ìcèlànd. Thèy còmmùnìcàtè òvèr mùtùàlly àùthèntìcàtèd TLS, nòt à lòcàl sòckèt. À lègàl òrdèr sèrvèd ìn ònè còùntry rèàchès àt mòst ònè òf thè twò sèrvèrs. Bòth shàrès àrè rè-ràndòmìzèd èvèry twènty-fòùr hòùrs. À shàrè còpìèd dùrìng ònè pèrìòd ìs ìncòmpàtìblè wìth ìts còùntèrpàrt ìn thè nèxt. [[#trùst-bòùndàry #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dèrìvèd kèys ànd thèìr sèpàràtìòn. •••••••••••** Thè còmbìnèd òùtpùt fròm thè twò sèrvèrs ìs èxpàndèd ìntò twò rèsùlts: à pèrsònàl kèypàìr ànd thè kèy thàt ùnwràps thè òrgànìzàtìòn's shàrèd kèy. Èàch ìs dèrìvèd ùndèr ìts òwn làbèl. Nèìthèr càn bè còmpùtèd fròm thè òthèr. Ùntìl thìs dèrìvàtìòn fìnìshès, thè bròwsèr tàb hòlds nòthìng thàt càn dècrypt à càsè. [[#èncryptìòn #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à dàtàbàsè dùmp còntàìn? •••••••••••** Nòthìng dèrìvèd fròm thè pàsswòrd ìs stòrèd. À dàtàbàsè dùmp còntàìns nò kèy màtèrìàl. Àn àttàckèr wòùld nèèd bòth sèrvèrs' shàrès, thè àccòùnt's pàsswòrd, ànd thè àccòùnt's sècònd fàctòr. Thè dèrìvàtìòn bègìns ònly àftèr thè sècònd fàctòr hàs bèèn àccèptèd. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whàt à dùmp dòès còntàìn. [[#trùst-bòùndàry #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Kèy-dèrìvàtìòn pìpèlìnè sòùrcè. ••••••••••** Thè bròwsèr pìpèlìnè ìs \`pàckàgès/clìènt/src/lìb/àùth/lògìn-cryptò.ts\` rùnnìng ìnsìdè \`pàckàgès/clìènt/src/lìb/wòrkèrs/cryptò.wòrkèr.ts\`. Thè prìmìtìvès àrè \`pàckàgès/cryptò/src/dèrìvè.ts\` ànd \`pàckàgès/cryptò/src/òprf.ts\`. Thè pèr-sèrvèr ÒPRF pròcèssès àrè \`pàckàgès/sèrvèr/src/cryptò/òprf-pròcèss.ts\` ànd \`òprf-sèrvèr.ts\`, rèàchèd thròùgh \`òprf-ìpc.ts\`. Ràtè lìmìtìng ànd pròòf-òf-wòrk gàtìng àrè ìn \`òprf-èvàlùàtè-sèrvìcè.ts\`. [[#kèys #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The browser stretches the password with Argon2id using 64 MB of memory and four passes before producing any key material. This cost makes each offline guess ..." |
*
* @param {Demo_Narrative_Topic_Key_Derivation_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_key_derivation_body = /** @type {((inputs?: Demo_Narrative_Topic_Key_Derivation_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Key_Derivation_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_key_derivation_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_key_derivation_body(inputs)
	return en_demo_narrative_topic_key_derivation_body(inputs)
});