/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Message_Actions_BodyInputs */

const en_demo_narrative_topic_message_actions_body = /** @type {(inputs: Demo_Narrative_Topic_Message_Actions_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A long press on an entry in the thread opens a menu of the actions that entry allows. Shift+F10 opens the same menu from a keyboard. An entry with nothing encrypted in it does not receive the menu. [[#permissions #client-data]]
**What does each entry offer?** Copy appears in the menu for every entry that opens one. Editing is offered on a message sent by a volunteer when the signed-in account is the author; a message sent over the phone network cannot be edited. Editing and deleting are offered on an internal note to the account that wrote it. Removing another account's note requires the Delete others' notes permission; the holder can remove it but cannot change its words. [Internal notes](#ticket-detail/notes) covers the note rules, and [Edit sent message](#ticket-detail/outbound-edit) covers what an edit replaces. [[#permissions]]
**What does a copy take with it?** A copy writes the entry's decrypted content to the device clipboard. The application does not control the clipboard once the write completes. [Selecting messages](#ticket-detail/message-select) covers the same limit for several entries at once. [[#privacy]]
**Server-side re-check.** The server checks each edit or delete request independently against the account making it: access to the ticket, the entry's type, whether the entry has already been deleted, and whether the account is the author or holds the required permission. A request that passes the client menu but fails any server check is refused. [The permission system](#deep-dive/the-permission-system) covers where those checks come from. [[#permissions #trust-boundary]]
**What does a delete leave behind?** Deleting an entry hides it from every later read. The encrypted content is not erased at deletion; retention removes it later. Editing a note replaces what was stored and keeps no copy of the original. Nothing about a deletion reaches the client's own thread. [Data retention](#deep-dive/data-retention) covers the removal. [[#retention #server-holds]]
**The eligibility function and server guards.** \`context-menu-actions.ts\` in \`packages/client/src/lib/components/tickets/\` decides which actions an entry offers from its type, its source, and its author. \`create-context-menu.svelte.ts\` in \`packages/client/src/lib/composables/ticket-detail/\` dispatches the chosen action. The server guards are \`updateOutboundMessage\`, \`updateInternalNote\`, and \`softDeleteInternalNote\` in \`packages/server/src/tickets/followup-service.ts\`. [[#client-data]]`)
};

const es_demo_narrative_topic_message_actions_body = /** @type {(inputs: Demo_Narrative_Topic_Message_Actions_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Una pulsación larga sobre una entrada del hilo abre un menú con las acciones que esa entrada permite. Shift+F10 abre el mismo menú desde un teclado. Una entrada sin nada cifrado no recibe el menú. [[#permissions #client-data]]
**¿Qué ofrece cada entrada?** Copiar aparece en el menú para toda entrada que abre uno. Editar se ofrece en un mensaje enviado por una persona voluntaria cuando la cuenta que ha iniciado sesión es la autora; un mensaje enviado por la red telefónica no se puede editar. Editar y eliminar se ofrecen en una nota interna a la cuenta que la escribió. Eliminar la nota de otra cuenta requiere el permiso Eliminar notas de otros; quien lo tiene puede eliminarla, pero no cambiar su contenido. [Notas internas](#ticket-detail/notes) trata las reglas de notas, y [Editar mensaje enviado](#ticket-detail/outbound-edit) trata lo que una edición reemplaza. [[#permissions]]
**¿Qué se lleva una copia?** Una copia escribe el contenido descifrado de la entrada al portapapeles del dispositivo. La aplicación no controla el portapapeles una vez completada la escritura. [Seleccionar mensajes](#ticket-detail/message-select) trata el mismo límite para varias entradas a la vez. [[#privacy]]
**Verificación en el servidor.** El servidor verifica cada solicitud de edición o eliminación de forma independiente contra la cuenta que la hace: acceso al ticket, el tipo de la entrada, si la entrada ya fue eliminada, y si la cuenta es la autora o tiene el permiso requerido. Una solicitud que pasa el menú del cliente pero falla cualquier verificación del servidor se rechaza. [El sistema de permisos](#deep-dive/the-permission-system) explica de dónde vienen esas verificaciones. [[#permissions #trust-boundary]]
**¿Qué deja una eliminación?** Eliminar una entrada la oculta de toda lectura posterior. El contenido cifrado no se borra con la eliminación; la retención lo elimina después. La edición de una nota reemplaza lo almacenado y no conserva copia del original. Nada sobre una eliminación llega al hilo propio del cliente. [Retención de datos](#deep-dive/data-retention) trata la eliminación. [[#retention #server-holds]]
**La función de elegibilidad y las guardas del servidor.** \`context-menu-actions.ts\` en \`packages/client/src/lib/components/tickets/\` decide qué acciones ofrece una entrada a partir de su tipo, su origen y su autoría. \`create-context-menu.svelte.ts\` en \`packages/client/src/lib/composables/ticket-detail/\` despacha la acción elegida. Las guardas del servidor son \`updateOutboundMessage\`, \`updateInternalNote\` y \`softDeleteInternalNote\` en \`packages/server/src/tickets/followup-service.ts\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_message_actions_body = /** @type {(inputs: Demo_Narrative_Topic_Message_Actions_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À lòng prèss òn àn èntry ìn thè thrèàd òpèns à mènù òf thè àctìòns thàt èntry àllòws. Shìft+F10 òpèns thè sàmè mènù fròm à kèybòàrd. Àn èntry wìth nòthìng èncryptèd ìn ìt dòès nòt rècèìvè thè mènù. [[#pèrmìssìòns #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès èàch èntry òffèr? •••••••••** Còpy àppèàrs ìn thè mènù fòr èvèry èntry thàt òpèns ònè. Èdìtìng ìs òffèrèd òn à mèssàgè sènt by à vòlùntèèr whèn thè sìgnèd-ìn àccòùnt ìs thè àùthòr; à mèssàgè sènt òvèr thè phònè nètwòrk cànnòt bè èdìtèd. Èdìtìng ànd dèlètìng àrè òffèrèd òn àn ìntèrnàl nòtè tò thè àccòùnt thàt wròtè ìt. Rèmòvìng ànòthèr àccòùnt's nòtè rèqùìrès thè Dèlètè òthèrs' nòtès pèrmìssìòn; thè hòldèr càn rèmòvè ìt bùt cànnòt chàngè ìts wòrds. [Ìntèrnàl nòtès](#tìckèt-dètàìl/nòtès) còvèrs thè nòtè rùlès, ànd [Èdìt sènt mèssàgè](#tìckèt-dètàìl/òùtbòùnd-èdìt) còvèrs whàt àn èdìt rèplàcès. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à còpy tàkè wìth ìt? •••••••••** À còpy wrìtès thè èntry's dècryptèd còntènt tò thè dèvìcè clìpbòàrd. Thè àpplìcàtìòn dòès nòt còntròl thè clìpbòàrd òncè thè wrìtè còmplètès. [Sèlèctìng mèssàgès](#tìckèt-dètàìl/mèssàgè-sèlèct) còvèrs thè sàmè lìmìt fòr sèvèràl èntrìès àt òncè. [[#prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèrvèr-sìdè rè-chèck. •••••••** Thè sèrvèr chècks èàch èdìt òr dèlètè rèqùèst ìndèpèndèntly àgàìnst thè àccòùnt màkìng ìt: àccèss tò thè tìckèt, thè èntry's typè, whèthèr thè èntry hàs àlrèàdy bèèn dèlètèd, ànd whèthèr thè àccòùnt ìs thè àùthòr òr hòlds thè rèqùìrèd pèrmìssìòn. À rèqùèst thàt pàssès thè clìènt mènù bùt fàìls àny sèrvèr chèck ìs rèfùsèd. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs whèrè thòsè chècks còmè fròm. [[#pèrmìssìòns #trùst-bòùndàry]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à dèlètè lèàvè bèhìnd? ••••••••••** Dèlètìng àn èntry hìdès ìt fròm èvèry làtèr rèàd. Thè èncryptèd còntènt ìs nòt èràsèd àt dèlètìòn; rètèntìòn rèmòvès ìt làtèr. Èdìtìng à nòtè rèplàcès whàt wàs stòrèd ànd kèèps nò còpy òf thè òrìgìnàl. Nòthìng àbòùt à dèlètìòn rèàchès thè clìènt's òwn thrèàd. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thè rèmòvàl. [[#rètèntìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè èlìgìbìlìty fùnctìòn ànd sèrvèr gùàrds. •••••••••••••** \`còntèxt-mènù-àctìòns.ts\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/tìckèts/\` dècìdès whìch àctìòns àn èntry òffèrs fròm ìts typè, ìts sòùrcè, ànd ìts àùthòr. \`crèàtè-còntèxt-mènù.svèltè.ts\` ìn \`pàckàgès/clìènt/src/lìb/còmpòsàblès/tìckèt-dètàìl/\` dìspàtchès thè chòsèn àctìòn. Thè sèrvèr gùàrds àrè \`ùpdàtèÒùtbòùndMèssàgè\`, \`ùpdàtèÌntèrnàlNòtè\`, ànd \`sòftDèlètèÌntèrnàlNòtè\` ìn \`pàckàgès/sèrvèr/src/tìckèts/fòllòwùp-sèrvìcè.ts\`. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A long press on an entry in the thread opens a menu of the actions that entry allows. Shift+F10 opens the same menu from a keyboard. An entry with nothing en..." |
*
* @param {Demo_Narrative_Topic_Message_Actions_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_message_actions_body = /** @type {((inputs?: Demo_Narrative_Topic_Message_Actions_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Message_Actions_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_message_actions_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_message_actions_body(inputs)
	return en_demo_narrative_topic_message_actions_body(inputs)
});