/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Settings_Password_BodyInputs */

const en_demo_narrative_settings_password_body = /** @type {(inputs: Demo_Narrative_Settings_Password_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A password change rebuilds the encryption keys from the new password and re-wraps every sealed copy those keys protect. The browser derives both the old and new key sets, re-wraps each sealed copy for the new keys, and sends a single request carrying the results. The server stores none of the private keys and cannot open anything it receives. [[#keys #encryption]]
**What gets re-wrapped?** Every ticket key the user can read, and the user's copy of the organization key. Each ticket keeps its own key, and only the sealed copy for this user changes. A user holding a thousand tickets re-wraps a thousand small keys, not a thousand tickets of ciphertext. The browser processes ticket keys in batches of forty. [How keys are derived](#deep-dive/how-keys-are-derived) covers where both key sets come from. [[#keys #encryption]]
**What does the server receive?** The current password, the new password, a new salt, a new public key, and the re-wrapped sealed copies. The server verifies the current password against its stored hash, stores a hash of the new one, replaces the salt and public key, and writes the new sealed copies. It receives no private key and nothing it can unwrap. [Username and password](#login/credentials) covers what the server holds of a password. [[#server-holds #keys]]
**Other sessions.** The same transaction that stores the new hash deletes every other session on the account. A session opened on another device stops working at the moment of the change. The browser that performed the change re-derives its keys from the new password and continues without a second sign-in. [[#failure-states #privacy]]
**When is a change refused?** The server allows five requests per minute per account and IP address. A wrong current password rejects the request before any state changes. The server also refuses a change while any intake submission or portal reply anywhere in the organization is still sealed to the current organization key and awaiting conversion, because rotating past those wraps would leave them unopenable. Every refusing check runs before the password hash is stored, so a refused change leaves the old password and keys working. [[#failure-states #keys]]
**The orchestrator and the rotation service.** The browser sequence is \`changePassword\` in \`packages/client/src/lib/settings/password-change.ts\`, which spawns a second short-lived crypto worker for the new keys and processes ticket keys in batches of forty. The server side is \`profile.changePassword\` in \`packages/server/src/routes/profile.ts\` over \`packages/server/src/crypto/key-rotation.ts\`, whose \`rotation_lock\` column prevents new ticket key wraps from being sealed to a public key the account is about to discard. The password hash update and the key rotation run as a single transaction, so a crash rolls back both. [[#keys #server-holds]]`)
};

const es_demo_narrative_settings_password_body = /** @type {(inputs: Demo_Narrative_Settings_Password_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un cambio de contraseña reconstruye las claves de cifrado a partir de la contraseña nueva y reenvuelve cada copia sellada que esas claves protegen. El navegador deriva los dos juegos de claves, el anterior y el nuevo, reenvuelve cada copia sellada para las claves nuevas y envía una sola petición con los resultados. El servidor no guarda ninguna clave privada y no puede abrir nada de lo que recibe. [[#keys #encryption]]
**¿Qué se reenvuelve?** Cada clave de ticket que la persona usuaria puede leer, y su copia de la clave de la organización. Cada ticket conserva su propia clave, y solo cambia la copia sellada para esa persona. Una persona con mil tickets reenvuelve mil claves pequeñas, no mil tickets de texto cifrado. El navegador procesa las claves de ticket en lotes de cuarenta. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata de dónde salen los dos juegos de claves. [[#keys #encryption]]
**¿Qué recibe el servidor?** La contraseña actual, la contraseña nueva, una sal nueva, una clave pública nueva y las copias selladas reenvueltas. El servidor comprueba la contraseña actual contra el hash que guarda, guarda un hash de la nueva, sustituye la sal y la clave pública y escribe las copias selladas nuevas. No recibe ninguna clave privada ni nada que pueda desenvolver. [Nombre de usuario y contraseña](#login/credentials) trata lo que el servidor guarda de una contraseña. [[#server-holds #keys]]
**Otras sesiones.** La misma transacción que guarda el hash nuevo elimina todas las demás sesiones de la cuenta. Una sesión abierta en otro dispositivo deja de funcionar en el momento del cambio. El navegador que realizó el cambio vuelve a derivar sus claves a partir de la contraseña nueva y continúa sin un segundo inicio de sesión. [[#failure-states #privacy]]
**¿Cuándo se rechaza un cambio?** El servidor permite cinco peticiones por minuto por cuenta y dirección IP. Una contraseña actual incorrecta rechaza la petición antes de que cambie cualquier estado. El servidor también rechaza un cambio mientras alguna solicitud de admisión o respuesta del portal en cualquier parte de la organización siga sellada con la clave de la organización actual y pendiente de conversión, porque rotar más allá de esas envolturas las dejaría sin poder abrirse. Toda comprobación que pueda rechazar se ejecuta antes de guardar el hash de la contraseña, de modo que un cambio rechazado deja funcionando la contraseña y las claves anteriores. [[#failure-states #keys]]
**El orquestador y el servicio de rotación.** La secuencia del navegador es \`changePassword\` en \`packages/client/src/lib/settings/password-change.ts\`, que lanza un segundo worker criptográfico efímero para las claves nuevas y procesa las claves de ticket en lotes de cuarenta. El lado del servidor es \`profile.changePassword\` en \`packages/server/src/routes/profile.ts\` sobre \`packages/server/src/crypto/key-rotation.ts\`, cuya columna \`rotation_lock\` impide que se sellen nuevas envolturas de clave de ticket para una clave pública que la cuenta está a punto de descartar. La actualización del hash de contraseña y la rotación de claves son una sola transacción, de modo que un fallo revierte ambas. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_settings_password_body = /** @type {(inputs: Demo_Narrative_Settings_Password_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À pàsswòrd chàngè rèbùìlds thè èncryptìòn kèys fròm thè nèw pàsswòrd ànd rè-wràps èvèry sèàlèd còpy thòsè kèys pròtèct. Thè bròwsèr dèrìvès bòth thè òld ànd nèw kèy sèts, rè-wràps èàch sèàlèd còpy fòr thè nèw kèys, ànd sènds à sìnglè rèqùèst càrryìng thè rèsùlts. Thè sèrvèr stòrès nònè òf thè prìvàtè kèys ànd cànnòt òpèn ànythìng ìt rècèìvès. [[#kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt gèts rè-wràppèd? •••••••** Èvèry tìckèt kèy thè ùsèr càn rèàd, ànd thè ùsèr's còpy òf thè òrgànìzàtìòn kèy. Èàch tìckèt kèèps ìts òwn kèy, ànd ònly thè sèàlèd còpy fòr thìs ùsèr chàngès. À ùsèr hòldìng à thòùsànd tìckèts rè-wràps à thòùsànd smàll kèys, nòt à thòùsànd tìckèts òf cìphèrtèxt. Thè bròwsèr pròcèssès tìckèt kèys ìn bàtchès òf fòrty. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs whèrè bòth kèy sèts còmè fròm. [[#kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr rècèìvè? •••••••••** Thè cùrrènt pàsswòrd, thè nèw pàsswòrd, à nèw sàlt, à nèw pùblìc kèy, ànd thè rè-wràppèd sèàlèd còpìès. Thè sèrvèr vèrìfìès thè cùrrènt pàsswòrd àgàìnst ìts stòrèd hàsh, stòrès à hàsh òf thè nèw ònè, rèplàcès thè sàlt ànd pùblìc kèy, ànd wrìtès thè nèw sèàlèd còpìès. Ìt rècèìvès nò prìvàtè kèy ànd nòthìng ìt càn ùnwràp. [Ùsèrnàmè ànd pàsswòrd](#lògìn/crèdèntìàls) còvèrs whàt thè sèrvèr hòlds òf à pàsswòrd. [[#sèrvèr-hòlds #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Òthèr sèssìòns. •••••** Thè sàmè trànsàctìòn thàt stòrès thè nèw hàsh dèlètès èvèry òthèr sèssìòn òn thè àccòùnt. À sèssìòn òpènèd òn ànòthèr dèvìcè stòps wòrkìng àt thè mòmènt òf thè chàngè. Thè bròwsèr thàt pèrfòrmèd thè chàngè rè-dèrìvès ìts kèys fròm thè nèw pàsswòrd ànd còntìnùès wìthòùt à sècònd sìgn-ìn. [[#fàìlùrè-stàtès #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn ìs à chàngè rèfùsèd? ••••••••** Thè sèrvèr àllòws fìvè rèqùèsts pèr mìnùtè pèr àccòùnt ànd ÌP àddrèss. À wròng cùrrènt pàsswòrd rèjècts thè rèqùèst bèfòrè àny stàtè chàngès. Thè sèrvèr àlsò rèfùsès à chàngè whìlè àny ìntàkè sùbmìssìòn òr pòrtàl rèply ànywhèrè ìn thè òrgànìzàtìòn ìs stìll sèàlèd tò thè cùrrènt òrgànìzàtìòn kèy ànd àwàìtìng cònvèrsìòn, bècàùsè ròtàtìng pàst thòsè wràps wòùld lèàvè thèm ùnòpènàblè. Èvèry rèfùsìng chèck rùns bèfòrè thè pàsswòrd hàsh ìs stòrèd, sò à rèfùsèd chàngè lèàvès thè òld pàsswòrd ànd kèys wòrkìng. [[#fàìlùrè-stàtès #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè òrchèstràtòr ànd thè ròtàtìòn sèrvìcè. •••••••••••••** Thè bròwsèr sèqùèncè ìs \`chàngèPàsswòrd\` ìn \`pàckàgès/clìènt/src/lìb/sèttìngs/pàsswòrd-chàngè.ts\`, whìch spàwns à sècònd shòrt-lìvèd cryptò wòrkèr fòr thè nèw kèys ànd pròcèssès tìckèt kèys ìn bàtchès òf fòrty. Thè sèrvèr sìdè ìs \`pròfìlè.chàngèPàsswòrd\` ìn \`pàckàgès/sèrvèr/src/ròùtès/pròfìlè.ts\` òvèr \`pàckàgès/sèrvèr/src/cryptò/kèy-ròtàtìòn.ts\`, whòsè \`ròtàtìòn_lòck\` còlùmn prèvènts nèw tìckèt kèy wràps fròm bèìng sèàlèd tò à pùblìc kèy thè àccòùnt ìs àbòùt tò dìscàrd. Thè pàsswòrd hàsh ùpdàtè ànd thè kèy ròtàtìòn rùn às à sìnglè trànsàctìòn, sò à cràsh ròlls bàck bòth. [[#kèys #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A password change rebuilds the encryption keys from the new password and re-wraps every sealed copy those keys protect. The browser derives both the old and ..." |
*
* @param {Demo_Narrative_Settings_Password_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_settings_password_body = /** @type {((inputs?: Demo_Narrative_Settings_Password_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Settings_Password_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_settings_password_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_settings_password_body(inputs)
	return en_demo_narrative_settings_password_body(inputs)
});