/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Credentials_BodyInputs */

const en_demo_narrative_topic_credentials_body = /** @type {(inputs: Demo_Narrative_Topic_Credentials_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A user signs in with a username and a password. The username is a login name rather than an email address, chosen by the person accepting an invitation or set by an administrator who creates the account by hand.
**Password requirements.** A password on an organization's own user account has to be at least 16 characters and at most 256, checked by the browser and again by the server. Client portal accounts are governed by their own rules, which the client account entries describe.
**What the server holds.** The server keeps a scrypt hash of the password and never the password itself, so a stolen database cannot be turned back into anyone's credentials, and guessing against that hash is deliberately expensive. The password does travel to the server under TLS at each sign in, where it is checked against the stored hash.
**What the browser does.** Signing in also runs a key derivation in the browser from the password, and that leg never reveals the password to the server. It puts the password through Argon2id first, a function fixed at 64 MB of memory and four passes so every guess costs an attacker real hardware time, and the parameters sit in the browser's own code rather than arriving from the server, so a compromised server cannot ask for a cheaper setting. On a running CARE-Y server the pause during sign in is that cost being paid, while this handbook runs the real derivation behind a scripted pace so each step stays on screen long enough to read.
**Brute force defense.** On a running CARE-Y server, sign in attempts are capped at five a minute from one address, and the key derivation request carries its own ceilings of ten per account and fifty per address in any fifteen minutes. Once an account passes five derivation attempts inside that window the server demands a proof of work puzzle the browser has to solve before the request is answered, that puzzle hardens as attempts accumulate, and waits of two, five, and ten seconds are added from the sixth, the eighth, and the tenth attempt. The friction counts attempts rather than failures on purpose, because the derivation step is blind by design and the server cannot tell a correct password guess from a wrong one. This handbook wires every one of those limiters to accept whatever it is given, so nothing in it is ever throttled.
**Account lockout.** No amount of failed guessing locks a CARE-Y account, because the product carries no lockout state at all, so nobody can use the sign in screen to shut a user out of their own account, and the rate limits that do apply expire on their own.
**Unknown usernames.** An attacker cannot use the sign in screen to learn which usernames exist, because an attempt on a username that does not exist follows the same path as one on a real account. The browser needs a salt belonging to the account before it can stretch the password, and for a name that does not exist the server computes a deterministic fake salt from an internal key rather than returning an error, while the password check runs against a throwaway hash so the timing matches. On a running CARE-Y server that salt lookup is capped at twenty requests a minute from one address, a cap this handbook leaves open.
**Recovery.** There is no way to recover a forgotten password. No reset link exists, no copy of a user's own keys is kept anywhere to restore from, and an administrator cannot set a new password on someone else's account either, because changing a password requires the current one.
**If it fails.** A refused sign in shows the same message, "Invalid username or password", whether the username was wrong, the password was wrong, or the account does not exist, and a sign in stopped by the rate limit is no more specific, because CARE-Y withholds the detail by policy wherever a fuller message would give an attacker information worth having.`)
};

const es_demo_narrative_topic_credentials_body = /** @type {(inputs: Demo_Narrative_Topic_Credentials_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Se inicia sesión con un nombre de usuario y una contraseña. El nombre de usuario es un identificador de acceso y no una dirección de correo, y lo elige la persona usuaria al aceptar una invitación, o lo fija un administrador que crea la cuenta a mano.
**Requisitos de la contraseña.** La contraseña de una cuenta de usuario de la organización debe tener al menos 16 caracteres y como máximo 256, y lo comprueban tanto el navegador como el servidor. Las cuentas del portal de clientes se rigen por sus propias reglas, que describen las entradas de cuenta de cliente.
**Lo que guarda el servidor.** El servidor conserva un hash scrypt de la contraseña y nunca la contraseña en sí, de modo que una base de datos robada no puede convertirse de nuevo en las credenciales de nadie, y probar conjeturas contra ese hash resulta deliberadamente costoso. La contraseña sí viaja al servidor bajo TLS en cada inicio de sesión, y allí se compara con el hash almacenado.
**Lo que hace el navegador.** Iniciar sesión ejecuta además una derivación de claves en el navegador a partir de la contraseña, y esa vía no revela la contraseña al servidor. Primero pasa la contraseña por Argon2id, una función fijada en 64 MB de memoria y cuatro pasadas para que cada conjetura le cueste a un atacante tiempo real de hardware, y los parámetros están en el código del propio navegador y no llegan desde el servidor, así que un servidor comprometido no puede pedir una configuración más barata. En un servidor CARE-Y en funcionamiento la pausa al iniciar sesión es ese coste pagándose, mientras que este manual ejecuta la derivación real detrás de un ritmo recreado para que cada paso permanezca en pantalla el tiempo suficiente para leerlo.
**Defensa contra fuerza bruta.** En un servidor CARE-Y en funcionamiento, los intentos de inicio de sesión están limitados a cinco por minuto desde una misma dirección, y la petición de derivación de claves tiene sus propios techos de diez por cuenta y cincuenta por dirección en cualquier ventana de quince minutos. Cuando una cuenta supera cinco intentos de derivación dentro de esa ventana, el servidor exige una prueba de trabajo que el navegador debe resolver antes de recibir respuesta, esa prueba se endurece a medida que se acumulan los intentos, y se añaden esperas de dos, cinco y diez segundos a partir del sexto, el octavo y el décimo intento. La fricción cuenta intentos y no fallos a propósito, porque el paso de derivación es ciego por diseño y el servidor no puede distinguir una contraseña acertada de una equivocada. Este manual conecta todos esos limitadores para que acepten lo que reciban, así que aquí nunca se frena nada.
**Bloqueo de cuenta.** Ninguna cantidad de intentos fallidos bloquea una cuenta de CARE-Y, porque el producto no tiene estado de bloqueo alguno, de modo que nadie puede usar la pantalla de inicio de sesión para dejar a una persona usuaria fuera de su propia cuenta, y los límites de peticiones que sí se aplican se disuelven solos.
**Nombres de usuario inexistentes.** Un atacante no puede usar la pantalla de inicio de sesión para averiguar qué nombres de usuario existen, porque un intento con un nombre inexistente recorre el mismo camino que uno con una cuenta real. El navegador necesita una sal propia de la cuenta antes de poder estirar la contraseña, y para un nombre que no existe el servidor calcula una sal falsa determinista con una clave interna en lugar de devolver un error, mientras que la comprobación de la contraseña se ejecuta contra un hash de relleno para que los tiempos coincidan. En un servidor CARE-Y en funcionamiento esa consulta de sal está limitada a veinte peticiones por minuto desde una misma dirección, un límite que este manual deja abierto.
**Recuperación.** No hay manera de recuperar una contraseña olvidada. No existe enlace de restablecimiento, no se guarda en ninguna parte una copia de las claves propias de la persona usuaria para restaurarlas, y un administrador tampoco puede fijar una contraseña nueva en la cuenta de otra persona, porque cambiarla exige conocer la actual.
**Si falla.** Un inicio de sesión rechazado muestra siempre el mismo mensaje, "Usuario o contraseña incorrectos", tanto si el nombre de usuario era erróneo como si lo era la contraseña o si la cuenta no existe, y un inicio de sesión detenido por el límite de peticiones no es más específico, porque CARE-Y omite ese detalle por norma allí donde un mensaje más completo le daría a un atacante información aprovechable.`)
};

/**
* | output |
* | --- |
* | "A user signs in with a username and a password. The username is a login name rather than an email address, chosen by the person accepting an invitation or se..." |
*
* @param {Demo_Narrative_Topic_Credentials_BodyInputs} inputs
* @param {{ locale?: "en" | "es" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_credentials_body = /** @type {((inputs?: Demo_Narrative_Topic_Credentials_BodyInputs, options?: { locale?: "en" | "es" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Credentials_BodyInputs, { locale?: "en" | "es" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_credentials_body(inputs)
	return en_demo_narrative_topic_credentials_body(inputs)
});