/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Conversation_BodyInputs */

const en_demo_narrative_topic_conversation_body = /** @type {(inputs: Demo_Narrative_Topic_Conversation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The unified case thread carries everything said on a ticket in one sequence: what the client sent, what the organization sent back, the notes written about it, and the events the ticket recorded. [[#client-data]]
**One sequence, several channels.** A text message, a reply typed into the application, an email, and a voicemail are separate kinds of follow-up in the same thread. Whether the client or an account wrote a follow-up decides which side it sits on. The type is a plaintext column, so the server knows a ticket received four texts and sent one email at given times, and holds the words of none of them. [The telephony relay](#deep-dive/the-telephony-relay) covers what the carrier saw of a text before it arrived. [[#metadata #server-holds #telephony]]
**How are follow-ups sealed?** Each follow-up is sealed individually with the ticket key and bound to its own slot. A ciphertext moved to another follow-up or another ticket fails to open rather than opening in the wrong place. Replies a client sends from their portal arrive under a one-off key that is unwrapped and converged into the ticket key on first reading. [How encryption works](#deep-dive/how-encryption-works) covers the slot binding. [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers the one-off key convergence. [[#encryption #keys]]
**Paging through a long thread.** The thread opens on the most recent fifty follow-ups and fetches older pages of fifty as reading moves back, holding the reading position steady as each page is added. When unread follow-ups are further back than the first page, pages are fetched until the last read point is in view. A refresh of the newest page merges by follow-up rather than replacing the page, so an older page already loaded is not split at its boundary. [Date separators](#ticket-detail/date-separators) covers the day boundaries. [System events](#ticket-detail/system-events) covers the recorded events. [[#failure-states]]
**The paginator and the follow-up row.** \`packages/client/src/lib/tickets/chat-paginator.svelte.ts\` is the shared paging implementation behind both this thread and the client portal thread. Both call sites pass a page size of fifty. The row is \`packages/server/src/db/migrations/tenant/026_create_followups.ts\` with \`encrypted_content\` as \`bytea\` beside plaintext \`source\`, \`type\`, and \`created_at\`. [[#client-data #server-holds]]`)
};

const es_demo_narrative_topic_conversation_body = /** @type {(inputs: Demo_Narrative_Topic_Conversation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El hilo de caso unificado reúne todo lo dicho en un ticket en una sola secuencia: lo que envió el cliente, lo que respondió la organización, las notas escritas al respecto y los eventos que registró el ticket. [[#client-data]]
**Una secuencia, varios canales.** Un mensaje de texto, una respuesta escrita en la aplicación, un correo electrónico y un buzón de voz son tipos distintos de seguimiento en el mismo hilo. Si lo escribió el cliente o una cuenta determina de qué lado aparece el seguimiento. El tipo es una columna en texto plano, así que el servidor sabe que un ticket recibió cuatro textos y envió un correo a ciertas horas, y no conserva las palabras de ninguno. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que el operador vio de un texto antes de que llegara. [[#metadata #server-holds #telephony]]
**¿Cómo se sellan los seguimientos?** Cada seguimiento se sella individualmente con la clave del ticket y se vincula a su propia ranura. Un texto cifrado movido a otro seguimiento o a otro ticket no se abre en lugar de abrirse en el lugar equivocado. Las respuestas que un cliente envía desde su portal llegan bajo una clave de un solo uso que se desenvuelve y se converge en la clave del ticket en la primera lectura. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la vinculación a la ranura. [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata la convergencia de la clave de un solo uso. [[#encryption #keys]]
**Paginación en un hilo largo.** El hilo abre con los cincuenta seguimientos más recientes y carga páginas anteriores de cincuenta conforme la lectura retrocede, manteniendo la posición de lectura estable mientras se añade cada página. Cuando hay seguimientos no leídos más atrás que la primera página, se cargan páginas hasta que el último punto de lectura queda visible. Una actualización de la página más reciente fusiona por seguimiento en vez de reemplazar la página, así que una página anterior ya cargada no se corta en su límite. [Separadores de fecha](#ticket-detail/date-separators) trata los límites de día. [Eventos del sistema](#ticket-detail/system-events) trata los eventos registrados. [[#failure-states]]
**El paginador y la fila de seguimiento.** \`packages/client/src/lib/tickets/chat-paginator.svelte.ts\` es la implementación de paginación compartida detrás de este hilo y del hilo del portal del cliente. Ambos puntos de llamada pasan un tamaño de página de cincuenta. La fila es \`packages/server/src/db/migrations/tenant/026_create_followups.ts\` con \`encrypted_content\` como \`bytea\` junto a las columnas en texto plano \`source\`, \`type\` y \`created_at\`. [[#client-data #server-holds]]`)
};

const en_xa2_demo_narrative_topic_conversation_body = /** @type {(inputs: Demo_Narrative_Topic_Conversation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ùnìfìèd càsè thrèàd càrrìès èvèrythìng sàìd òn à tìckèt ìn ònè sèqùèncè: whàt thè clìènt sènt, whàt thè òrgànìzàtìòn sènt bàck, thè nòtès wrìttèn àbòùt ìt, ànd thè èvènts thè tìckèt rècòrdèd. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ònè sèqùèncè, sèvèràl chànnèls. ••••••••••** À tèxt mèssàgè, à rèply typèd ìntò thè àpplìcàtìòn, àn èmàìl, ànd à vòìcèmàìl àrè sèpàràtè kìnds òf fòllòw-ùp ìn thè sàmè thrèàd. Whèthèr thè clìènt òr àn àccòùnt wròtè à fòllòw-ùp dècìdès whìch sìdè ìt sìts òn. Thè typè ìs à plàìntèxt còlùmn, sò thè sèrvèr knòws à tìckèt rècèìvèd fòùr tèxts ànd sènt ònè èmàìl àt gìvèn tìmès, ànd hòlds thè wòrds òf nònè òf thèm. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt thè càrrìèr sàw òf à tèxt bèfòrè ìt àrrìvèd. [[#mètàdàtà #sèrvèr-hòlds #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw àrè fòllòw-ùps sèàlèd? ••••••••** Èàch fòllòw-ùp ìs sèàlèd ìndìvìdùàlly wìth thè tìckèt kèy ànd bòùnd tò ìts òwn slòt. À cìphèrtèxt mòvèd tò ànòthèr fòllòw-ùp òr ànòthèr tìckèt fàìls tò òpèn ràthèr thàn òpènìng ìn thè wròng plàcè. Rèplìès à clìènt sènds fròm thèìr pòrtàl àrrìvè ùndèr à ònè-òff kèy thàt ìs ùnwràppèd ànd cònvèrgèd ìntò thè tìckèt kèy òn fìrst rèàdìng. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè slòt bìndìng. [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thè ònè-òff kèy cònvèrgèncè. [[#èncryptìòn #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pàgìng thròùgh à lòng thrèàd. •••••••••** Thè thrèàd òpèns òn thè mòst rècènt fìfty fòllòw-ùps ànd fètchès òldèr pàgès òf fìfty às rèàdìng mòvès bàck, hòldìng thè rèàdìng pòsìtìòn stèàdy às èàch pàgè ìs àddèd. Whèn ùnrèàd fòllòw-ùps àrè fùrthèr bàck thàn thè fìrst pàgè, pàgès àrè fètchèd ùntìl thè làst rèàd pòìnt ìs ìn vìèw. À rèfrèsh òf thè nèwèst pàgè mèrgès by fòllòw-ùp ràthèr thàn rèplàcìng thè pàgè, sò àn òldèr pàgè àlrèàdy lòàdèd ìs nòt splìt àt ìts bòùndàry. [Dàtè sèpàràtòrs](#tìckèt-dètàìl/dàtè-sèpàràtòrs) còvèrs thè dày bòùndàrìès. [Systèm èvènts](#tìckèt-dètàìl/systèm-èvènts) còvèrs thè rècòrdèd èvènts. [[#fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pàgìnàtòr ànd thè fòllòw-ùp ròw. •••••••••••** \`pàckàgès/clìènt/src/lìb/tìckèts/chàt-pàgìnàtòr.svèltè.ts\` ìs thè shàrèd pàgìng ìmplèmèntàtìòn bèhìnd bòth thìs thrèàd ànd thè clìènt pòrtàl thrèàd. Bòth càll sìtès pàss à pàgè sìzè òf fìfty. Thè ròw ìs \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/026_crèàtè_fòllòwùps.ts\` wìth \`èncryptèd_còntènt\` às \`bytèà\` bèsìdè plàìntèxt \`sòùrcè\`, \`typè\`, ànd \`crèàtèd_àt\`. [[#clìènt-dàtà #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The unified case thread carries everything said on a ticket in one sequence: what the client sent, what the organization sent back, the notes written about i..." |
*
* @param {Demo_Narrative_Topic_Conversation_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_conversation_body = /** @type {((inputs?: Demo_Narrative_Topic_Conversation_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Conversation_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_conversation_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_conversation_body(inputs)
	return en_demo_narrative_topic_conversation_body(inputs)
});