/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs */

const en_demo_narrative_deepdive_telephony_relay_body = /** @type {(inputs: Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Phone calls and text messages are the one part of CARE-Y where plaintext has to exist on the server, because a phone number and a message body have to be handed to a phone company in a form it can act on. The relay is the narrow place where that happens, and it is built to hold that plaintext for as short a time as possible and to keep no record of it. [[#telephony #encryption]]
For an outbound text, the user's browser decrypts the reply and posts it with the case id to a single relay endpoint. The server resolves and decrypts the client's phone number itself rather than accepting one from the browser, hands number and body to the telephony provider, and then wipes the memory it used. The relay does not write the message anywhere, does not log the request, and does not put the content in an error response if something fails. The browser separately encrypts its own copy and stores that on the case thread, so the readable record of the conversation lives where only the case's users can open it. Outbound email follows the same shape through a relay endpoint of its own. An outbound call carries no message body, and the browser submits the user's own callback number, which the server refuses unless it hashes to the number that account verified, while the client's number is resolved server-side the same way. [[#telephony #server-holds]]
Inbound messages follow the same shape in reverse. A text arrives at the provider, the provider posts it to CARE-Y, and the server encrypts the body before storing anything, then wipes the plaintext. There is no moment at which an inbound message sits readable in the database. CARE-Y then asks the provider to delete its own log of that message, and retries if the request fails. [[#telephony #encryption]]
What no amount of care on CARE-Y's side can change is that the message was already readable by other people before it arrived. The client's phone carrier saw it. The telephony provider saw it, and holds phone number and delivery metadata under its own retention rules and its own legal obligations whatever CARE-Y requests. A subpoena to the provider produces that metadata and does not produce message content, because CARE-Y's stored copy is encrypted and the provider's copy of the log is what CARE-Y asked it to delete. Clients who need the channel itself protected, and not only the organization's copy of it, are better served by an encrypted channel in their browser, and [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers those. [[#telephony #failure-states #privacy]]
**Why the relay is not part of the main API.** The relay endpoints are raw HTTP handlers rather than tRPC procedures, because the tRPC JSON parser produces JavaScript strings and a string cannot be zeroed. The handlers read the request body as a \`Buffer\`, use it, and call \`.fill(0)\` in \`finally\` blocks on every buffer that touched plaintext. That covers the raw body, the phone number buffer, the message buffer and the case id buffer. Authentication uses the same session functions as the rest of the API, called directly, and the endpoints mount under a \`/relay/\` prefix with a maximum body size. [[#telephony #server-holds]]
**Inbound handling in detail.** An inbound text runs through six steps before the handler returns. [[#telephony #encryption]]
1. The webhook signature is validated before anything else happens, in development as well as in production, and a request with a missing or invalid signature is rejected. [[#telephony #failure-states]]
2. The request is deduplicated by provider message id. [[#telephony]]
3. The client is resolved or created by blind index on the phone number. [[#telephony #client-data]]
4. The case is resolved or created. [[#telephony #client-data]]
5. The body is encrypted under a per-case key, and both plaintext and key are zeroed in \`finally\` blocks. [[#telephony #encryption]]
6. When the client has an active encrypted portal channel, a copy of the message is sealed to the channel's public key so that the client's view of the conversation matches the organization's. [[#telephony #portal]]
That portal copy is the one message class on the portal that the server rather than a browser seals. Voicemail audio is fetched from the provider, encrypted, stored, and then deleted at the provider, and a recording that cannot be routed to a case is encrypted and held in a quarantine for an administrator rather than being left in plaintext at the provider or silently discarded. [[#telephony #encryption #portal]]
**Provider boundary.** Everything provider-specific sits behind one interface covering sending messages, placing calls, validating webhooks, and deleting call, message and recording logs. Twilio is the implemented provider. SignalWire has a validated configuration shape and no provider module, so selecting it is not yet a working path. A mock provider stands in for development and for this handbook. Switching providers is configuration rather than code, and provider credentials live in the operational tier where the server can read them, which is the one tier the server has keys for. [[#telephony #server-holds]]
**Contributor pointers.** The relay, the webhook path and the provider layer sit in separate places. [[#telephony]]
- Relay handlers are \`packages/server/src/routes/relay.ts\`, which mounts one endpoint each for a text, an email, a call, a WebRTC token, a phone lookup and a consultant verification, with shared parsing and authentication in \`relay-utils.ts\`. [[#telephony #server-holds]]
- Webhook intake is \`packages/server/src/routes/webhooks.ts\`, dispatching to \`packages/server/src/telephony/inbound-sms.ts\`, \`inbound-mms.ts\`, \`inbound-call.ts\` and \`recording-handler.ts\`. [[#telephony]]
- The provider interface is \`packages/server/src/telephony/provider.ts\` with \`twilio.ts\`, \`provider-http.ts\` and \`mock-provider.ts\` behind it and \`factory.ts\` selecting one. [[#telephony]]
- Log deletion is \`packages/server/src/jobs/log-deletion.ts\` with helpers in \`telephony/log-deletion-helpers.ts\`. [[#telephony #retention]]
Anyone adding a relay endpoint keeps to the same discipline, which is \`Buffer\` rather than string, no logging of bodies, no plaintext in errors, and a \`finally\` block that zeroes. [[#telephony #server-holds]]`)
};

const es_demo_narrative_deepdive_telephony_relay_body = /** @type {(inputs: Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Las llamadas y los mensajes de texto son la única parte de CARE-Y donde el texto plano tiene que existir en el servidor, porque un número de teléfono y el cuerpo de un mensaje tienen que entregarse a una compañía telefónica en una forma sobre la que pueda actuar. El relay es el lugar estrecho donde eso ocurre, y está construido para retener ese texto plano el menor tiempo posible y para no dejar ningún registro de él. [[#telephony #encryption]]
Para un mensaje de texto saliente, el navegador de la persona usuaria descifra la respuesta y la envía junto con el identificador del caso a un único endpoint de relay. El servidor resuelve y descifra el número de teléfono del cliente por sí mismo en lugar de aceptar uno del navegador, entrega número y cuerpo al proveedor de telefonía y después borra la memoria que usó. El relay no escribe el mensaje en ningún sitio, no registra la solicitud y no pone el contenido en una respuesta de error si algo falla. El navegador cifra por separado su propia copia y la guarda en el hilo del caso, así que el registro legible de la conversación vive donde solo las personas usuarias del caso pueden abrirlo. El correo saliente sigue la misma forma a través de un endpoint de relay propio. Una llamada saliente no lleva cuerpo de mensaje, y el navegador envía el número de devolución de llamada de la propia persona usuaria, que el servidor rechaza salvo que su hash coincida con el número que esa cuenta verificó, mientras que el número del cliente se resuelve en el servidor de la misma manera. [[#telephony #server-holds]]
Los mensajes entrantes siguen la misma forma al revés. Un mensaje de texto llega al proveedor, el proveedor lo publica en CARE-Y, y el servidor cifra el cuerpo antes de almacenar nada y después borra el texto plano. No hay ningún momento en el que un mensaje entrante esté legible en la base de datos. CARE-Y pide entonces al proveedor que elimine su propio registro de ese mensaje, y reintenta si la solicitud falla. [[#telephony #encryption]]
Lo que ningún cuidado del lado de CARE-Y puede cambiar es que el mensaje ya era legible por otras personas antes de llegar. La compañía telefónica del cliente lo vio. El proveedor de telefonía lo vio, y conserva el número de teléfono y los metadatos de entrega bajo sus propias reglas de retención y sus propias obligaciones legales, pida CARE-Y lo que pida. Una orden judicial al proveedor produce esos metadatos y no produce el contenido de los mensajes, porque la copia que CARE-Y almacena está cifrada y la copia del registro que tenía el proveedor es la que CARE-Y le pidió eliminar. Los clientes que necesitan que el canal mismo esté protegido, y no solo la copia de la organización, quedan mejor servidos por un canal cifrado en su navegador, y [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata esos canales. [[#telephony #failure-states #privacy]]
**Por qué el relay no forma parte de la API principal.** Los endpoints de relay son manejadores HTTP crudos en lugar de procedimientos tRPC, porque el analizador JSON de tRPC produce cadenas JavaScript y una cadena no se puede poner a cero. Los manejadores leen el cuerpo de la solicitud como un \`Buffer\`, lo usan y llaman a \`.fill(0)\` en bloques \`finally\` sobre cada búfer que tocó texto plano. Eso cubre el cuerpo crudo, el búfer del número de teléfono, el búfer del mensaje y el búfer del identificador del caso. La autenticación usa las mismas funciones de sesión que el resto de la API, llamadas directamente, y los endpoints se montan bajo un prefijo \`/relay/\` con un tamaño máximo de cuerpo. [[#telephony #server-holds]]
**El manejo de lo entrante en detalle.** Un mensaje de texto entrante pasa por seis pasos antes de que el manejador devuelva una respuesta. [[#telephony #encryption]]
1. La firma del webhook se valida antes de que ocurra cualquier otra cosa, tanto en desarrollo como en producción, y una solicitud con firma ausente o inválida se rechaza. [[#telephony #failure-states]]
2. La solicitud se deduplica por el identificador de mensaje del proveedor. [[#telephony]]
3. El cliente se resuelve o se crea mediante el índice ciego del número de teléfono. [[#telephony #client-data]]
4. El caso se resuelve o se crea. [[#telephony #client-data]]
5. El cuerpo se cifra con una clave por caso, y tanto el texto plano como la clave se ponen a cero en bloques \`finally\`. [[#telephony #encryption]]
6. Cuando el cliente tiene un canal del portal cifrado activo, una copia del mensaje se sella con la clave pública del canal para que la vista de la conversación que tiene el cliente coincida con la de la organización. [[#telephony #portal]]
Esa copia del portal es la única clase de mensaje del portal que sella el servidor en lugar de un navegador. El audio de los correos de voz se obtiene del proveedor, se cifra, se almacena y después se elimina en el proveedor, y una grabación que no se puede encaminar a un caso se cifra y se retiene en una cuarentena para una persona administradora en lugar de quedar en texto plano en el proveedor o descartarse en silencio. [[#telephony #encryption #portal]]
**La frontera con el proveedor.** Todo lo específico del proveedor está detrás de una única interfaz que cubre el envío de mensajes, la realización de llamadas, la validación de webhooks y la eliminación de registros de llamadas, mensajes y grabaciones. Twilio es el proveedor implementado. SignalWire tiene una forma de configuración validada y ningún módulo de proveedor, así que seleccionarlo aún no es un camino que funcione. Un proveedor simulado hace de sustituto para el desarrollo y para este manual. Cambiar de proveedor es configuración y no código, y las credenciales del proveedor viven en el nivel operativo donde el servidor puede leerlas, que es el único nivel para el que el servidor tiene claves. [[#telephony #server-holds]]
**Indicaciones para quien contribuye.** El relay, la ruta de los webhooks y la capa del proveedor están en lugares separados. [[#telephony]]
- Los manejadores de relay son \`packages/server/src/routes/relay.ts\`, que monta un endpoint para cada cosa: un mensaje de texto, un correo, una llamada, un token de WebRTC, una consulta de número y una verificación de la persona consultora, con el análisis y la autenticación compartidos en \`relay-utils.ts\`. [[#telephony #server-holds]]
- La recepción de webhooks es \`packages/server/src/routes/webhooks.ts\`, que despacha a \`packages/server/src/telephony/inbound-sms.ts\`, \`inbound-mms.ts\`, \`inbound-call.ts\` y \`recording-handler.ts\`. [[#telephony]]
- La interfaz del proveedor es \`packages/server/src/telephony/provider.ts\` con \`twilio.ts\`, \`provider-http.ts\` y \`mock-provider.ts\` detrás de ella y \`factory.ts\` seleccionando uno. [[#telephony]]
- La eliminación de registros es \`packages/server/src/jobs/log-deletion.ts\` con ayudantes en \`telephony/log-deletion-helpers.ts\`. [[#telephony #retention]]
Quien añada un endpoint de relay se ciñe a la misma disciplina, que es \`Buffer\` en lugar de cadena, ningún registro de los cuerpos, ningún texto plano en los errores y un bloque \`finally\` que pone a cero. [[#telephony #server-holds]]`)
};

/**
* | output |
* | --- |
* | "Phone calls and text messages are the one part of CARE-Y where plaintext has to exist on the server, because a phone number and a message body have to be han..." |
*
* @param {Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs} inputs
* @param {{ locale?: "en" | "es" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_telephony_relay_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs, options?: { locale?: "en" | "es" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs, { locale?: "en" | "es" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_telephony_relay_body(inputs)
	return en_demo_narrative_deepdive_telephony_relay_body(inputs)
});