/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Note_Types_BodyInputs */

const en_demo_narrative_admin_note_types_body = /** @type {(inputs: Demo_Narrative_Admin_Note_Types_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Note types are the categories a note can be filed under, and an organization defines its own set, each with a name, an icon and an optional description, alongside eight types the product writes by itself for things like a status change or a call. [[#client-data]]
**What an organization sets on a type.** Each configurable type carries three notification switches, one for administrators, one for managers and one for everyone with access to the case, and a switch that makes a note of that type required before the case can be closed. It also carries a minimum role for seeing notes of that type and a minimum role for writing one, so a category for sensitive material can be kept to managers or administrators. [Internal notes](#ticket-detail/notes) covers writing one. [[#permissions]]
**The four an organization starts with.** Comment, Resolution, Safety Concern and Request are ordinary configurable types rather than protected ones, so an organization renames, re-points or retires them like any other. Comment is the type a new note starts on, Resolution is the one required before closing, and Safety Concern and Request notify administrators and managers as well as everyone with access to the case, while Comment and Resolution notify only the last of those. [[#client-data]]
**What the server can read about a type.** The name, the icon and the description are sealed to the organization key, and the server stores them as bytes it has no way to open. The notification targets are the exception: they are encrypted under the server's own operational key and decrypted at notification time, because working out who to notify is the server's job, so a running server can tell that some category escalates to administrators without knowing which category that is. The two role thresholds, the required-on-close flag and the active flag are plaintext columns, so a dump shows how many categories an organization runs and how tightly each is gated. [The trust boundary](#deep-dive/the-trust-boundary) covers what else it yields. [[#server-holds #encryption #metadata]]
**Retiring rather than deleting.** A type is deactivated rather than removed, so notes already filed under it keep their category and stay filterable, and the type currently set as the organization's default is refused deactivation, which is what keeps at least one category available to write against. [[#failure-states]]
**Who defines the set.** Configuring note types requires the Manage note types permission, which sits with Admin by default. [[#permissions]]
**The note type row and its two encryptors.** \`packages/server/src/tickets/note-type-service.ts\` holds both sides, sealing names and icons to the organization public key and encrypting the notification targets with the operational secrets key, and its \`DEFAULT_NOTE_TYPES\` is where the starting four are defined. The columns come from \`packages/server/src/db/migrations/tenant/058_create_note_types.ts\`, with the description added in \`061\` and the two role thresholds in \`062\`, and the default pointer is \`org_config.default_note_type_id\` from \`060\`. [[#server-holds #client-data]]`)
};

const es_demo_narrative_admin_note_types_body = /** @type {(inputs: Demo_Narrative_Admin_Note_Types_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los tipos de nota son las categorías bajo las que se puede archivar una nota, y cada organización define su propio conjunto, cada tipo con un nombre, un icono y una descripción opcional, junto a ocho tipos que el producto escribe por su cuenta para cosas como un cambio de estado o una llamada. [[#client-data]]
**Qué configura una organización en un tipo.** Cada tipo configurable lleva tres interruptores de notificación, uno para administradores, otro para gestores y otro para todas las personas con acceso al caso, y un interruptor que hace obligatoria una nota de ese tipo antes de poder cerrar el caso. Lleva además un rol mínimo para ver las notas de ese tipo y un rol mínimo para escribir una, de modo que una categoría para material delicado puede quedar reservada a gestores o administradores. [Notas internas](#ticket-detail/notes) trata la escritura de una nota. [[#permissions]]
**Los cuatro con los que empieza una organización.** Comentario, Resolución, Preocupación de seguridad y Petición son tipos configurables corrientes y no protegidos, así que una organización los renombra, los reorienta o los retira como a cualquier otro. Comentario es el tipo con el que empieza una nota nueva, Resolución es el que se exige antes de cerrar, y Preocupación de seguridad y Petición notifican a administradores y gestores además de a todas las personas con acceso al caso, mientras que Comentario y Resolución notifican solo a estas últimas. [[#client-data]]
**Qué puede leer el servidor de un tipo.** El nombre, el icono y la descripción van sellados con la clave de la organización, y el servidor los guarda como bytes que no tiene forma de abrir. Los destinatarios de las notificaciones son la excepción: se cifran con la clave operativa del propio servidor y se descifran en el momento de notificar, porque averiguar a quién avisar es tarea del servidor, de modo que un servidor en marcha puede saber que alguna categoría escala a administradores sin saber cuál es esa categoría. Los dos umbrales de rol, la marca de nota obligatoria al cerrar y la marca de actividad son columnas en texto plano, así que un volcado muestra cuántas categorías tiene una organización y con cuánta restricción está cada una. [La frontera de confianza](#deep-dive/the-trust-boundary) trata lo demás que revela. [[#server-holds #encryption #metadata]]
**Retirar en lugar de borrar.** Un tipo se desactiva en vez de eliminarse, así que las notas ya archivadas bajo él conservan su categoría y se siguen pudiendo filtrar, y al tipo que está puesto como predeterminado de la organización se le rechaza la desactivación, que es lo que mantiene al menos una categoría disponible para escribir. [[#failure-states]]
**Quién define el conjunto.** Configurar los tipos de nota requiere el permiso de gestionar tipos de nota, que corresponde a Admin de forma predeterminada. [[#permissions]]
**La fila del tipo de nota y sus dos cifradores.** \`packages/server/src/tickets/note-type-service.ts\` contiene los dos lados, sellando nombres e iconos con la clave pública de la organización y cifrando los destinatarios de notificación con la clave de secretos operativos, y su \`DEFAULT_NOTE_TYPES\` es donde están definidos los cuatro iniciales. Las columnas vienen de \`packages/server/src/db/migrations/tenant/058_create_note_types.ts\`, con la descripción añadida en \`061\` y los dos umbrales de rol en \`062\`, y el puntero al predeterminado es \`org_config.default_note_type_id\`, de \`060\`. [[#server-holds #client-data]]`)
};

const en_xa2_demo_narrative_admin_note_types_body = /** @type {(inputs: Demo_Narrative_Admin_Note_Types_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Nòtè typès àrè thè càtègòrìès à nòtè càn bè fìlèd ùndèr, ànd àn òrgànìzàtìòn dèfìnès ìts òwn sèt, èàch wìth à nàmè, àn ìcòn ànd àn òptìònàl dèscrìptìòn, àlòngsìdè èìght typès thè pròdùct wrìtès by ìtsèlf fòr thìngs lìkè à stàtùs chàngè òr à càll. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt àn òrgànìzàtìòn sèts òn à typè. •••••••••••** Èàch cònfìgùràblè typè càrrìès thrèè nòtìfìcàtìòn swìtchès, ònè fòr àdmìnìstràtòrs, ònè fòr mànàgèrs ànd ònè fòr èvèryònè wìth àccèss tò thè càsè, ànd à swìtch thàt màkès à nòtè òf thàt typè rèqùìrèd bèfòrè thè càsè càn bè clòsèd. Ìt àlsò càrrìès à mìnìmùm ròlè fòr sèèìng nòtès òf thàt typè ànd à mìnìmùm ròlè fòr wrìtìng ònè, sò à càtègòry fòr sènsìtìvè màtèrìàl càn bè kèpt tò mànàgèrs òr àdmìnìstràtòrs. [Ìntèrnàl nòtès](#tìckèt-dètàìl/nòtès) còvèrs wrìtìng ònè. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fòùr àn òrgànìzàtìòn stàrts wìth. ••••••••••••** Còmmènt, Rèsòlùtìòn, Sàfèty Còncèrn ànd Rèqùèst àrè òrdìnàry cònfìgùràblè typès ràthèr thàn pròtèctèd ònès, sò àn òrgànìzàtìòn rènàmès, rè-pòìnts òr rètìrès thèm lìkè àny òthèr. Còmmènt ìs thè typè à nèw nòtè stàrts òn, Rèsòlùtìòn ìs thè ònè rèqùìrèd bèfòrè clòsìng, ànd Sàfèty Còncèrn ànd Rèqùèst nòtìfy àdmìnìstràtòrs ànd mànàgèrs às wèll às èvèryònè wìth àccèss tò thè càsè, whìlè Còmmènt ànd Rèsòlùtìòn nòtìfy ònly thè làst òf thòsè. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè sèrvèr càn rèàd àbòùt à typè. ••••••••••••** Thè nàmè, thè ìcòn ànd thè dèscrìptìòn àrè sèàlèd tò thè òrgànìzàtìòn kèy, ànd thè sèrvèr stòrès thèm às bytès ìt hàs nò wày tò òpèn. Thè nòtìfìcàtìòn tàrgèts àrè thè èxcèptìòn: thèy àrè èncryptèd ùndèr thè sèrvèr's òwn òpèràtìònàl kèy ànd dècryptèd àt nòtìfìcàtìòn tìmè, bècàùsè wòrkìng òùt whò tò nòtìfy ìs thè sèrvèr's jòb, sò à rùnnìng sèrvèr càn tèll thàt sòmè càtègòry èscàlàtès tò àdmìnìstràtòrs wìthòùt knòwìng whìch càtègòry thàt ìs. Thè twò ròlè thrèshòlds, thè rèqùìrèd-òn-clòsè flàg ànd thè àctìvè flàg àrè plàìntèxt còlùmns, sò à dùmp shòws hòw màny càtègòrìès àn òrgànìzàtìòn rùns ànd hòw tìghtly èàch ìs gàtèd. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whàt èlsè ìt yìèlds. [[#sèrvèr-hòlds #èncryptìòn #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rètìrìng ràthèr thàn dèlètìng. •••••••••** À typè ìs dèàctìvàtèd ràthèr thàn rèmòvèd, sò nòtès àlrèàdy fìlèd ùndèr ìt kèèp thèìr càtègòry ànd stày fìltèràblè, ànd thè typè cùrrèntly sèt às thè òrgànìzàtìòn's dèfàùlt ìs rèfùsèd dèàctìvàtìòn, whìch ìs whàt kèèps àt lèàst ònè càtègòry àvàìlàblè tò wrìtè àgàìnst. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò dèfìnès thè sèt. ••••••** Cònfìgùrìng nòtè typès rèqùìrès thè Mànàgè nòtè typès pèrmìssìòn, whìch sìts wìth Àdmìn by dèfàùlt. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••**Thè nòtè typè ròw ànd ìts twò èncryptòrs. •••••••••••••** \`pàckàgès/sèrvèr/src/tìckèts/nòtè-typè-sèrvìcè.ts\` hòlds bòth sìdès, sèàlìng nàmès ànd ìcòns tò thè òrgànìzàtìòn pùblìc kèy ànd èncryptìng thè nòtìfìcàtìòn tàrgèts wìth thè òpèràtìònàl sècrèts kèy, ànd ìts \`DÈFÀÙLT_NÒTÈ_TYPÈS\` ìs whèrè thè stàrtìng fòùr àrè dèfìnèd. Thè còlùmns còmè fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/058_crèàtè_nòtè_typès.ts\`, wìth thè dèscrìptìòn àddèd ìn \`061\` ànd thè twò ròlè thrèshòlds ìn \`062\`, ànd thè dèfàùlt pòìntèr ìs \`òrg_cònfìg.dèfàùlt_nòtè_typè_ìd\` fròm \`060\`. [[#sèrvèr-hòlds #clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Note types are the categories a note can be filed under, and an organization defines its own set, each with a name, an icon and an optional description, alon..." |
*
* @param {Demo_Narrative_Admin_Note_Types_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_note_types_body = /** @type {((inputs?: Demo_Narrative_Admin_Note_Types_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Note_Types_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_note_types_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_note_types_body(inputs)
	return en_demo_narrative_admin_note_types_body(inputs)
});