/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Keys_BodyInputs */

const en_demo_narrative_admin_keys_body = /** @type {(inputs: Demo_Narrative_Admin_Keys_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Each account in an organization holds its own wrapped copy of one organization key. This page reports whether the user's account has that copy and offers escrow export and key rotation. [The organization key lifecycle](#deep-dive/organization-key-lifecycle) covers how the key is created, distributed and restored from escrow. [[#keys]]
**What happens without a wrapped copy?** A user whose account has enrolled keys but holds no wrapped copy of the organization key cannot decrypt queue names, note type names, custom terminology, or display names on the roster. Case content wrapped to that account individually remains readable. A wrapped copy arrives automatically: any signed-in user holding the Manage keys permission polls every five minutes for enrolled accounts that lack one and wraps the key for each. A duplicate wrap from a second session is discarded silently. Until a session with that permission runs, the account stays in that state. [Roster tools](#admin-people/roster-tools) covers the filter that finds those accounts. [[#keys #failure-states]]
**Escrow export.** Export produces a single JSON file containing its format identifier, key derivation parameters, salt, nonce, and ciphertext, so the file can be parsed on an air-gapped machine without CARE-Y code. The passphrase must be at least 20 characters, and a strength estimate sized for offline attack rejects a weak one. The derivation is Argon2id at 256 MB and four passes, tuned for a workstation rather than a sign-in. The file's SHA-256 fingerprint is split into four-character groups so two copies can be compared visually. Both the passphrase bytes and the organization secret key are zeroed after the export finishes or fails. Possessing the file is equivalent to possessing the organization's data. Escrow restores key material, not database rows: anything [the retention policy](#admin-org/retention) deleted is absent from an escrow recovery. [[#keys #encryption]]
**How does rotation work?** The browser generates a new Curve25519 keypair, seals the outgoing secret key under the incoming one as a generation record, wraps the new secret for each active account that holds a public key, and submits all wraps in a single request. The sealed chain keeps pre-rotation data readable: each ciphertext row carries the generation it was sealed under, and decryption walks the chain backward to reach it. Inactive accounts and accounts that have never signed in receive no wrap. The people-identifying rows reseal to the new key immediately:
- Client records
- Account rows
- Sessions
- The blocklist
- Consultants
- The two tables of wrapped case keys
The remaining organization configuration converges afterward through a sweep that any later sign-in holding the Manage keys permission resumes where it left off. The browser then fetches and unwraps its own copy through the standard sign-in path instead of trusting the key it just generated. [How keys are derived](#deep-dive/how-keys-are-derived) covers where the organization key sits in the key hierarchy. [[#keys #encryption #failure-states]]
**Who can export and rotate?** Escrow export and key rotation both require the Manage keys permission, one of three grants locked to the administrator role regardless of role configuration. A database row granting it to another role produces no effect. [The permission system](#deep-dive/the-permission-system) covers the other two locked grants. [[#permissions]]
**The generation table and the reseal service.** \`packages/server/src/db/migrations/tenant/113_org_key_generations.ts\` creates \`org_key_generations\`, one row per generation carrying the public key and the previous secret sealed under it. Every table holding organization-sealed ciphertext gains an \`org_key_generation\` stamp. Re-encryption runs through \`packages/server/src/crypto/org-reseal-service.ts\`, which cannot verify the plaintext it receives because the server holds no organization key. Its guarantee is structural: a row accepts an update only while its stamp is below the current generation, the stamp advances in the same update, and the browser declares any rows it could not decrypt rather than passing over them. [[#keys #server-holds]]`)
};

const es_demo_narrative_admin_keys_body = /** @type {(inputs: Demo_Narrative_Admin_Keys_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cada cuenta de una organización guarda su propia copia envuelta de una sola clave de la organización. Esta página informa de si la cuenta de la persona usuaria tiene esa copia y ofrece la exportación de custodia y la rotación de claves. [El ciclo de vida de la clave de la organización](#deep-dive/organization-key-lifecycle) trata cómo se crea, se distribuye y se restaura la clave desde custodia. [[#keys]]
**¿Qué ocurre sin una copia envuelta?** Una persona usuaria cuya cuenta ha inscrito sus claves pero no tiene copia envuelta de la clave de la organización no puede descifrar los nombres de las colas, los nombres de los tipos de nota, la terminología personalizada ni los nombres visibles del directorio. El contenido de los casos envuelto individualmente para esa cuenta sigue siendo legible. La copia envuelta llega de forma automática: cualquier persona con sesión iniciada que tenga el permiso de gestionar claves comprueba cada cinco minutos si hay cuentas inscritas sin copia y envuelve la clave para cada una. Un envoltorio duplicado de una segunda sesión se descarta en silencio. Hasta que se ejecute una sesión con ese permiso, la cuenta se queda en ese estado. [Herramientas del directorio](#admin-people/roster-tools) trata el filtro que localiza esas cuentas. [[#keys #failure-states]]
**Exportación de custodia.** La exportación produce un único archivo JSON que contiene su identificador de formato, los parámetros de derivación de clave, la sal, el nonce y el texto cifrado, de modo que el archivo se puede analizar en una máquina aislada sin código de CARE-Y. La frase de contraseña debe tener al menos 20 caracteres, y una estimación de fortaleza calibrada para ataque sin conexión rechaza una débil. La derivación es Argon2id con 256 MB y cuatro pasadas, ajustada para una estación de trabajo y no para un inicio de sesión. La huella SHA-256 del archivo se divide en grupos de cuatro caracteres para poder comparar dos copias visualmente. Tanto los bytes de la frase de contraseña como la clave secreta de la organización se ponen a cero cuando la exportación termina o falla. Poseer el archivo equivale a poseer los datos de la organización. La custodia restaura material de claves, no filas de la base de datos: lo que [la política de retención](#admin-org/retention) haya eliminado no aparece en una recuperación de custodia. [[#keys #encryption]]
**¿Cómo funciona la rotación?** El navegador genera un nuevo par de claves Curve25519, sella la clave secreta saliente con la entrante como registro de generación, envuelve la nueva clave secreta una vez por cada cuenta activa que tenga clave pública y envía todos los envoltorios en una sola petición. La cadena sellada mantiene legibles los datos anteriores a la rotación: cada fila de texto cifrado lleva la generación con la que se selló, y el descifrado recorre la cadena hacia atrás para alcanzarla. Las cuentas inactivas y las que nunca han iniciado sesión no reciben envoltorio. Las filas que identifican personas se resellan con la clave nueva de inmediato:
- Registros de clientes
- Filas de cuentas
- Sesiones
- La lista de bloqueo
- Personas consultoras
- Las dos tablas de claves de caso envueltas
El resto de la configuración de la organización converge después mediante un barrido que cualquier inicio de sesión posterior con el permiso de gestionar claves retoma donde se quedó. Luego el navegador obtiene y desenvuelve su propia copia por la vía estándar de inicio de sesión en lugar de fiarse de la clave que acaba de generar. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) explica dónde encaja la clave de la organización en la jerarquía de claves. [[#keys #encryption #failure-states]]
**¿Quién puede exportar y rotar?** La exportación de custodia y la rotación de claves requieren ambas el permiso de gestionar claves, una de las tres concesiones fijadas al rol de administrador con independencia de la configuración de roles. Una fila de la base de datos que lo conceda a otro rol no produce efecto. [El sistema de permisos](#deep-dive/the-permission-system) trata las otras dos concesiones fijadas. [[#permissions]]
**La tabla de generaciones y el servicio de resellado.** \`packages/server/src/db/migrations/tenant/113_org_key_generations.ts\` crea \`org_key_generations\`, una fila por generación con la clave pública y la secreta anterior sellada con ella. Cada tabla que guarda texto cifrado sellado para la organización recibe una marca \`org_key_generation\`. El recifrado pasa por \`packages/server/src/crypto/org-reseal-service.ts\`, que no puede verificar el texto claro que recibe porque el servidor no tiene la clave de la organización. Su garantía es estructural: una fila solo acepta una actualización mientras su marca esté por debajo de la generación actual, la marca avanza dentro de la misma actualización, y el navegador declara las filas que no pudo descifrar en vez de pasarlas por alto. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_admin_keys_body = /** @type {(inputs: Demo_Narrative_Admin_Keys_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èàch àccòùnt ìn àn òrgànìzàtìòn hòlds ìts òwn wràppèd còpy òf ònè òrgànìzàtìòn kèy. Thìs pàgè rèpòrts whèthèr thè ùsèr's àccòùnt hàs thàt còpy ànd òffèrs èscròw èxpòrt ànd kèy ròtàtìòn. [Thè òrgànìzàtìòn kèy lìfècyclè](#dèèp-dìvè/òrgànìzàtìòn-kèy-lìfècyclè) còvèrs hòw thè kèy ìs crèàtèd, dìstrìbùtèd ànd rèstòrèd fròm èscròw. [[#kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns wìthòùt à wràppèd còpy? •••••••••••** À ùsèr whòsè àccòùnt hàs ènròllèd kèys bùt hòlds nò wràppèd còpy òf thè òrgànìzàtìòn kèy cànnòt dècrypt qùèùè nàmès, nòtè typè nàmès, cùstòm tèrmìnòlògy, òr dìsplày nàmès òn thè ròstèr. Càsè còntènt wràppèd tò thàt àccòùnt ìndìvìdùàlly rèmàìns rèàdàblè. À wràppèd còpy àrrìvès àùtòmàtìcàlly: àny sìgnèd-ìn ùsèr hòldìng thè Mànàgè kèys pèrmìssìòn pòlls èvèry fìvè mìnùtès fòr ènròllèd àccòùnts thàt làck ònè ànd wràps thè kèy fòr èàch. À dùplìcàtè wràp fròm à sècònd sèssìòn ìs dìscàrdèd sìlèntly. Ùntìl à sèssìòn wìth thàt pèrmìssìòn rùns, thè àccòùnt stàys ìn thàt stàtè. [Ròstèr tòòls](#àdmìn-pèòplè/ròstèr-tòòls) còvèrs thè fìltèr thàt fìnds thòsè àccòùnts. [[#kèys #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èscròw èxpòrt. •••••** Èxpòrt pròdùcès à sìnglè JSÒN fìlè còntàìnìng ìts fòrmàt ìdèntìfìèr, kèy dèrìvàtìòn pàràmètèrs, sàlt, nòncè, ànd cìphèrtèxt, sò thè fìlè càn bè pàrsèd òn àn àìr-gàppèd màchìnè wìthòùt CÀRÈ-Y còdè. Thè pàssphràsè mùst bè àt lèàst 20 chàràctèrs, ànd à strèngth èstìmàtè sìzèd fòr òfflìnè àttàck rèjècts à wèàk ònè. Thè dèrìvàtìòn ìs Àrgòn2ìd àt 256 MB ànd fòùr pàssès, tùnèd fòr à wòrkstàtìòn ràthèr thàn à sìgn-ìn. Thè fìlè's SHÀ-256 fìngèrprìnt ìs splìt ìntò fòùr-chàràctèr gròùps sò twò còpìès càn bè còmpàrèd vìsùàlly. Bòth thè pàssphràsè bytès ànd thè òrgànìzàtìòn sècrèt kèy àrè zèròèd àftèr thè èxpòrt fìnìshès òr fàìls. Pòssèssìng thè fìlè ìs èqùìvàlènt tò pòssèssìng thè òrgànìzàtìòn's dàtà. Èscròw rèstòrès kèy màtèrìàl, nòt dàtàbàsè ròws: ànythìng [thè rètèntìòn pòlìcy](#àdmìn-òrg/rètèntìòn) dèlètèd ìs àbsènt fròm àn èscròw rècòvèry. [[#kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès ròtàtìòn wòrk? •••••••** Thè bròwsèr gènèràtès à nèw Cùrvè25519 kèypàìr, sèàls thè òùtgòìng sècrèt kèy ùndèr thè ìncòmìng ònè às à gènèràtìòn rècòrd, wràps thè nèw sècrèt fòr èàch àctìvè àccòùnt thàt hòlds à pùblìc kèy, ànd sùbmìts àll wràps ìn à sìnglè rèqùèst. Thè sèàlèd chàìn kèèps prè-ròtàtìòn dàtà rèàdàblè: èàch cìphèrtèxt ròw càrrìès thè gènèràtìòn ìt wàs sèàlèd ùndèr, ànd dècryptìòn wàlks thè chàìn bàckwàrd tò rèàch ìt. Ìnàctìvè àccòùnts ànd àccòùnts thàt hàvè nèvèr sìgnèd ìn rècèìvè nò wràp. Thè pèòplè-ìdèntìfyìng ròws rèsèàl tò thè nèw kèy ìmmèdìàtèly:
- Clìènt rècòrds
- Àccòùnt ròws
- Sèssìòns
- Thè blòcklìst
- Cònsùltànts
- Thè twò tàblès òf wràppèd càsè kèys
Thè rèmàìnìng òrgànìzàtìòn cònfìgùràtìòn cònvèrgès àftèrwàrd thròùgh à swèèp thàt àny làtèr sìgn-ìn hòldìng thè Mànàgè kèys pèrmìssìòn rèsùmès whèrè ìt lèft òff. Thè bròwsèr thèn fètchès ànd ùnwràps ìts òwn còpy thròùgh thè stàndàrd sìgn-ìn pàth ìnstèàd òf trùstìng thè kèy ìt jùst gènèràtèd. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs whèrè thè òrgànìzàtìòn kèy sìts ìn thè kèy hìèràrchy. [[#kèys #èncryptìòn #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn èxpòrt ànd ròtàtè? ••••••••** Èscròw èxpòrt ànd kèy ròtàtìòn bòth rèqùìrè thè Mànàgè kèys pèrmìssìòn, ònè òf thrèè grànts lòckèd tò thè àdmìnìstràtòr ròlè règàrdlèss òf ròlè cònfìgùràtìòn. À dàtàbàsè ròw gràntìng ìt tò ànòthèr ròlè pròdùcès nò èffèct. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs thè òthèr twò lòckèd grànts. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè gènèràtìòn tàblè ànd thè rèsèàl sèrvìcè. ••••••••••••••** \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/113_òrg_kèy_gènèràtìòns.ts\` crèàtès \`òrg_kèy_gènèràtìòns\`, ònè ròw pèr gènèràtìòn càrryìng thè pùblìc kèy ànd thè prèvìòùs sècrèt sèàlèd ùndèr ìt. Èvèry tàblè hòldìng òrgànìzàtìòn-sèàlèd cìphèrtèxt gàìns àn \`òrg_kèy_gènèràtìòn\` stàmp. Rè-èncryptìòn rùns thròùgh \`pàckàgès/sèrvèr/src/cryptò/òrg-rèsèàl-sèrvìcè.ts\`, whìch cànnòt vèrìfy thè plàìntèxt ìt rècèìvès bècàùsè thè sèrvèr hòlds nò òrgànìzàtìòn kèy. Ìts gùàràntèè ìs strùctùràl: à ròw àccèpts àn ùpdàtè ònly whìlè ìts stàmp ìs bèlòw thè cùrrènt gènèràtìòn, thè stàmp àdvàncès ìn thè sàmè ùpdàtè, ànd thè bròwsèr dèclàrès àny ròws ìt còùld nòt dècrypt ràthèr thàn pàssìng òvèr thèm. [[#kèys #sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Each account in an organization holds its own wrapped copy of one organization key. This page reports whether the user's account has that copy and offers esc..." |
*
* @param {Demo_Narrative_Admin_Keys_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_keys_body = /** @type {((inputs?: Demo_Narrative_Admin_Keys_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Keys_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_keys_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_keys_body(inputs)
	return en_demo_narrative_admin_keys_body(inputs)
});