/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Share_Link_BodyInputs */

const en_demo_narrative_topic_share_link_body = /** @type {(inputs: Demo_Narrative_Topic_Share_Link_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A share link carries one message to someone outside the system, over an address that stops working after the first read or after 72 hours, whichever comes first. [[#portal #encryption #privacy]]
**Two copies under two keys.** The message is sealed with a key generated for that one share and bound to the share's identifier. The key is placed after the \`#\` in the address. Browsers never include that part of an address in a request to a server. A second copy is sealed with the ticket key and written to the [Conversation thread](#ticket-detail/conversation) in the same transaction. The server stores both copies and cannot open either. [Single use access](#client-share/one-time) covers what the recipient sees. [[#encryption #keys #server-holds]]
**How does the link go out?** When a phone number is on file and texting is enabled for the organization, the link is sent through the organization's line. Otherwise the link goes to the clipboard for the signed-in account to deliver by another method. The share row and the thread entry are written before delivery. A text that fails leaves a live link and a complete record rather than a lost message, and the failure is reported as its own state. Sending requires the Manage share links permission and the organization's share-link switch in [Channel policy](#admin-comms/channel-policy) set to on. [[#failure-states #permissions]]
**What does the server store?** The row holds the ticket it belongs to, the ciphertext, a creation time, an expiry, and a read time. There is no author column; authorship lives in the thread entry. A single conditional update settles the first successful read. One reader among several racing gets the content, and the rest are told it was already opened. The update empties the ciphertext column at that moment, leaving a tombstone until the expiry sweep. The browser caps the message at 64,000 bytes. The server independently refuses any ciphertext over 88,000 base64 characters. Neither side trusts the other's check. [Data retention](#deep-dive/data-retention) covers the sweep that removes the spent rows. [[#server-holds #metadata #trust-boundary]]
**The compose path and the share service.** The form is \`ShareLinkSheet.svelte\` with \`share-crypto.ts\` for the share key, and the server side is \`packages/server/src/portal/share-service.ts\` with the row from \`091_share_links.ts\`. [[#encryption]]`)
};

const es_demo_narrative_topic_share_link_body = /** @type {(inputs: Demo_Narrative_Topic_Share_Link_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un enlace compartido lleva un solo mensaje a alguien de fuera del sistema, por una dirección que deja de funcionar tras la primera lectura o a las 72 horas, lo que ocurra antes. [[#portal #encryption #privacy]]
**Dos copias con dos claves.** El mensaje se sella con una clave generada para ese único enlace compartido y ligada a su identificador. La clave se coloca después del \`#\` en la dirección. Los navegadores nunca incluyen esa parte de una dirección en una petición al servidor. Una segunda copia se sella con la clave del ticket y se escribe en el [Hilo de conversación](#ticket-detail/conversation) dentro de la misma transacción. El servidor guarda ambas copias y no puede abrir ninguna. [Acceso de un solo uso](#client-share/one-time) trata lo que ve quien lo recibe. [[#encryption #keys #server-holds]]
**¿Cómo sale el enlace?** Cuando hay un número de teléfono registrado y los mensajes de texto están habilitados para la organización, el enlace sale por la línea de la organización. Si no, va al portapapeles para que la cuenta que ha iniciado sesión lo entregue por otro medio. La fila del enlace compartido y la entrada del hilo se escriben antes de la entrega. Un mensaje de texto fallido deja un enlace vivo y un registro completo en lugar de un mensaje perdido, y el fallo se informa como estado propio. Enviar requiere el permiso Gestionar enlaces compartidos y que el interruptor de enlaces compartidos en [Política de canales](#admin-comms/channel-policy) esté activo. [[#failure-states #permissions]]
**¿Qué almacena el servidor?** La fila contiene el ticket al que pertenece, el texto cifrado, una fecha de creación, una de caducidad y una de lectura. No hay columna de autoría; la autoría vive en la entrada del hilo. Una sola actualización condicional resuelve la primera lectura con éxito. Entre varias lecturas simultáneas una obtiene el contenido, y a las demás se les indica que ya se había abierto. La actualización vacía la columna del texto cifrado en ese momento y deja una fila residual hasta el barrido de caducidad. El navegador limita el mensaje a 64.000 bytes. El servidor rechaza de forma independiente cualquier texto cifrado de más de 88.000 caracteres base64. Ninguno de los dos confía en la comprobación del otro. [Retención de datos](#deep-dive/data-retention) trata el barrido que retira las filas gastadas. [[#server-holds #metadata #trust-boundary]]
**La ruta de composición y el servicio del enlace compartido.** El formulario es \`ShareLinkSheet.svelte\` con \`share-crypto.ts\` para la clave del enlace compartido, y el lado del servidor es \`packages/server/src/portal/share-service.ts\` con la fila de \`091_share_links.ts\`. [[#encryption]]`)
};

const en_xa2_demo_narrative_topic_share_link_body = /** @type {(inputs: Demo_Narrative_Topic_Share_Link_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À shàrè lìnk càrrìès ònè mèssàgè tò sòmèònè òùtsìdè thè systèm, òvèr àn àddrèss thàt stòps wòrkìng àftèr thè fìrst rèàd òr àftèr 72 hòùrs, whìchèvèr còmès fìrst. [[#pòrtàl #èncryptìòn #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Twò còpìès ùndèr twò kèys. ••••••••** Thè mèssàgè ìs sèàlèd wìth à kèy gènèràtèd fòr thàt ònè shàrè ànd bòùnd tò thè shàrè's ìdèntìfìèr. Thè kèy ìs plàcèd àftèr thè \`#\` ìn thè àddrèss. Bròwsèrs nèvèr ìnclùdè thàt pàrt òf àn àddrèss ìn à rèqùèst tò à sèrvèr. À sècònd còpy ìs sèàlèd wìth thè tìckèt kèy ànd wrìttèn tò thè [Cònvèrsàtìòn thrèàd](#tìckèt-dètàìl/cònvèrsàtìòn) ìn thè sàmè trànsàctìòn. Thè sèrvèr stòrès bòth còpìès ànd cànnòt òpèn èìthèr. [Sìnglè ùsè àccèss](#clìènt-shàrè/ònè-tìmè) còvèrs whàt thè rècìpìènt sèès. [[#èncryptìòn #kèys #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè lìnk gò òùt? ••••••••** Whèn à phònè nùmbèr ìs òn fìlè ànd tèxtìng ìs ènàblèd fòr thè òrgànìzàtìòn, thè lìnk ìs sènt thròùgh thè òrgànìzàtìòn's lìnè. Òthèrwìsè thè lìnk gòès tò thè clìpbòàrd fòr thè sìgnèd-ìn àccòùnt tò dèlìvèr by ànòthèr mèthòd. Thè shàrè ròw ànd thè thrèàd èntry àrè wrìttèn bèfòrè dèlìvèry. À tèxt thàt fàìls lèàvès à lìvè lìnk ànd à còmplètè rècòrd ràthèr thàn à lòst mèssàgè, ànd thè fàìlùrè ìs rèpòrtèd às ìts òwn stàtè. Sèndìng rèqùìrès thè Mànàgè shàrè lìnks pèrmìssìòn ànd thè òrgànìzàtìòn's shàrè-lìnk swìtch ìn [Chànnèl pòlìcy](#àdmìn-còmms/chànnèl-pòlìcy) sèt tò òn. [[#fàìlùrè-stàtès #pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè? •••••••••** Thè ròw hòlds thè tìckèt ìt bèlòngs tò, thè cìphèrtèxt, à crèàtìòn tìmè, àn èxpìry, ànd à rèàd tìmè. Thèrè ìs nò àùthòr còlùmn; àùthòrshìp lìvès ìn thè thrèàd èntry. À sìnglè còndìtìònàl ùpdàtè sèttlès thè fìrst sùccèssfùl rèàd. Ònè rèàdèr àmòng sèvèràl ràcìng gèts thè còntènt, ànd thè rèst àrè tòld ìt wàs àlrèàdy òpènèd. Thè ùpdàtè èmptìès thè cìphèrtèxt còlùmn àt thàt mòmènt, lèàvìng à tòmbstònè ùntìl thè èxpìry swèèp. Thè bròwsèr càps thè mèssàgè àt 64,000 bytès. Thè sèrvèr ìndèpèndèntly rèfùsès àny cìphèrtèxt òvèr 88,000 bàsè64 chàràctèrs. Nèìthèr sìdè trùsts thè òthèr's chèck. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thè swèèp thàt rèmòvès thè spènt ròws. [[#sèrvèr-hòlds #mètàdàtà #trùst-bòùndàry]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còmpòsè pàth ànd thè shàrè sèrvìcè. ••••••••••••** Thè fòrm ìs \`ShàrèLìnkShèèt.svèltè\` wìth \`shàrè-cryptò.ts\` fòr thè shàrè kèy, ànd thè sèrvèr sìdè ìs \`pàckàgès/sèrvèr/src/pòrtàl/shàrè-sèrvìcè.ts\` wìth thè ròw fròm \`091_shàrè_lìnks.ts\`. [[#èncryptìòn]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A share link carries one message to someone outside the system, over an address that stops working after the first read or after 72 hours, whichever comes fi..." |
*
* @param {Demo_Narrative_Topic_Share_Link_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_share_link_body = /** @type {((inputs?: Demo_Narrative_Topic_Share_Link_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Share_Link_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_share_link_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_share_link_body(inputs)
	return en_demo_narrative_topic_share_link_body(inputs)
});