/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Field_Config_BodyInputs */

const en_demo_narrative_admin_field_config_body = /** @type {(inputs: Demo_Narrative_Admin_Field_Config_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Each field type carries its own settings. All types share a label and optional help text in each language and a required switch. Text and long text fields add a placeholder and a maximum character length. Single pick and multiple pick fields add an editable option list. The standalone checkbox adds a switch that makes ticking it a condition of submitting the form. [[#client-data]]
**What does a role do?** A role tells the system what an answer means so the system can act on it. A phone number marked with the phone-contact role becomes the ticket's contact method. An option marked with queue-routing becomes the queue the ticket lands in. The identity and contact roles (phone contact, email contact, real name, pronouns, contact safety, consent, language preference) may each appear at most once per form. The editor validates every role against its field type in the browser and again on the server. When a role conflicts with the current field type, the editor states the mismatch, blocks saving, and offers the compatible type, carrying the existing options and queue mapping across. [Custom form fields](#client-intake/fields) covers what a visitor does with them. [[#client-data #metadata]]
**What does a database dump show?** The role column and the queues an option routes to are stored in plaintext, because the submitting browser resolves them and the server routes on them. A dump reveals which role a field carries and which queue each option leads to. The server encrypts the list of users a field escalates to under its operational key. [Queue management](#admin-people/queues) covers what a queue grants. [[#server-holds #metadata]]
**Conditional visibility.** The user can set a field to appear only when answers to earlier fields match stated values. Rules are grouped: all rules in a group must hold for the group to pass, and the field appears when any group passes. Single pick, multiple pick, checkbox, text, long text, and date fields can drive a rule. Only fields earlier in the form order qualify, so two fields cannot create a cycle. [[#client-data]]
**Switching a field's type.** The editor stashes the configuration of the outgoing type. Switching back restores it instead of starting from defaults. The editor clears a role the incoming type cannot carry at all. It keeps a role that is displayable but incompatible, so it can show the conflict rather than silently discarding the routing work. [[#failure-states]]
**The compatibility tables and save schema.** \`ROLE_WIDGET_COMPATIBILITY\` and \`UNIQUE_ROLES_PER_FORM\` in \`packages/shared/src/schemas/intake-forms.ts\` define both rules. \`IntakeFieldConfigSheet.svelte\` reads them for the live conflict notice. The save schema applies them as refinements, so a form assembled outside the editor is held to the same constraints. [[#client-data]]`)
};

const es_demo_narrative_admin_field_config_body = /** @type {(inputs: Demo_Narrative_Admin_Field_Config_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cada tipo de campo tiene su propia configuración. Todos los tipos comparten una etiqueta y un texto de ayuda opcional en cada idioma, y un interruptor de obligatoriedad. Los campos de texto y texto largo añaden un texto de ejemplo y una longitud máxima de caracteres. Los campos de selección simple y selección múltiple añaden una lista de opciones editable. La casilla independiente añade un interruptor que convierte marcarla en condición para enviar el formulario. [[#client-data]]
**¿Qué hace un rol?** Un rol le indica al sistema qué significa una respuesta para que pueda actuar sobre ella. Un número de teléfono marcado con el rol de contacto telefónico se convierte en la vía de contacto del ticket. Una opción marcada con encaminamiento de cola se convierte en la cola donde aterriza el ticket. Los roles de identidad y contacto (contacto telefónico, contacto por correo, nombre real, pronombres, seguridad del contacto, consentimiento, preferencia de idioma) solo pueden aparecer una vez por formulario cada uno. El editor valida cada rol contra su tipo de campo en el navegador y otra vez en el servidor. Cuando un rol entra en conflicto con el tipo de campo actual, el editor indica la incompatibilidad, bloquea el guardado y ofrece el tipo compatible, trasladando las opciones existentes y la correspondencia de colas. [Campos de formulario personalizado](#client-intake/fields) trata lo que hace un visitante con ellos. [[#client-data #metadata]]
**¿Qué muestra un volcado de la base de datos?** La columna del rol y las colas a las que encamina una opción se almacenan en texto plano, porque el navegador que envía los resuelve y el servidor encamina con ellos. Un volcado revela qué rol lleva un campo y a qué cola conduce cada opción. El servidor cifra la lista de personas usuarias a las que escala un campo con su clave operativa. [Gestión de colas](#admin-people/queues) trata lo que concede una cola. [[#server-holds #metadata]]
**Visibilidad condicional.** La persona usuaria puede configurar un campo para que aparezca solo cuando las respuestas a campos anteriores coincidan con valores indicados. Las reglas se agrupan: todas las reglas del grupo deben cumplirse para que el grupo pase, y el campo aparece cuando pasa cualquier grupo. Los campos de selección simple, selección múltiple, casilla, texto, texto largo y fecha pueden gobernar una regla. Solo califican los campos anteriores en el orden del formulario, de modo que dos campos no pueden crear un ciclo. [[#client-data]]
**Cambiar el tipo de un campo.** El editor guarda la configuración del tipo saliente. Volver a ese tipo la restaura en lugar de partir de los valores predeterminados. El editor elimina un rol que el tipo entrante no puede llevar en absoluto. Conserva un rol que puede mostrar pero no guardar, para indicar el conflicto en vez de descartar el trabajo de encaminamiento sin aviso. [[#failure-states]]
**Las tablas de compatibilidad y el esquema de guardado.** \`ROLE_WIDGET_COMPATIBILITY\` y \`UNIQUE_ROLES_PER_FORM\` en \`packages/shared/src/schemas/intake-forms.ts\` definen ambas reglas. \`IntakeFieldConfigSheet.svelte\` las lee para el aviso de conflicto en vivo. El esquema de guardado las aplica como refinamientos, así que un formulario ensamblado fuera del editor queda sujeto a las mismas restricciones. [[#client-data]]`)
};

const en_xa2_demo_narrative_admin_field_config_body = /** @type {(inputs: Demo_Narrative_Admin_Field_Config_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èàch fìèld typè càrrìès ìts òwn sèttìngs. Àll typès shàrè à làbèl ànd òptìònàl hèlp tèxt ìn èàch làngùàgè ànd à rèqùìrèd swìtch. Tèxt ànd lòng tèxt fìèlds àdd à plàcèhòldèr ànd à màxìmùm chàràctèr lèngth. Sìnglè pìck ànd mùltìplè pìck fìèlds àdd àn èdìtàblè òptìòn lìst. Thè stàndàlònè chèckbòx àdds à swìtch thàt màkès tìckìng ìt à còndìtìòn òf sùbmìttìng thè fòrm. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à ròlè dò? ••••••** À ròlè tèlls thè systèm whàt àn ànswèr mèàns sò thè systèm càn àct òn ìt. À phònè nùmbèr màrkèd wìth thè phònè-còntàct ròlè bècòmès thè tìckèt's còntàct mèthòd. Àn òptìòn màrkèd wìth qùèùè-ròùtìng bècòmès thè qùèùè thè tìckèt lànds ìn. Thè ìdèntìty ànd còntàct ròlès (phònè còntàct, èmàìl còntàct, rèàl nàmè, prònòùns, còntàct sàfèty, cònsènt, làngùàgè prèfèrèncè) mày èàch àppèàr àt mòst òncè pèr fòrm. Thè èdìtòr vàlìdàtès èvèry ròlè àgàìnst ìts fìèld typè ìn thè bròwsèr ànd àgàìn òn thè sèrvèr. Whèn à ròlè cònflìcts wìth thè cùrrènt fìèld typè, thè èdìtòr stàtès thè mìsmàtch, blòcks sàvìng, ànd òffèrs thè còmpàtìblè typè, càrryìng thè èxìstìng òptìòns ànd qùèùè màppìng àcròss. [Cùstòm fòrm fìèlds](#clìènt-ìntàkè/fìèlds) còvèrs whàt à vìsìtòr dòès wìth thèm. [[#clìènt-dàtà #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à dàtàbàsè dùmp shòw? ••••••••••** Thè ròlè còlùmn ànd thè qùèùès àn òptìòn ròùtès tò àrè stòrèd ìn plàìntèxt, bècàùsè thè sùbmìttìng bròwsèr rèsòlvès thèm ànd thè sèrvèr ròùtès òn thèm. À dùmp rèvèàls whìch ròlè à fìèld càrrìès ànd whìch qùèùè èàch òptìòn lèàds tò. Thè sèrvèr èncrypts thè lìst òf ùsèrs à fìèld èscàlàtès tò ùndèr ìts òpèràtìònàl kèy. [Qùèùè mànàgèmènt](#àdmìn-pèòplè/qùèùès) còvèrs whàt à qùèùè grànts. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Còndìtìònàl vìsìbìlìty. •••••••** Thè ùsèr càn sèt à fìèld tò àppèàr ònly whèn ànswèrs tò èàrlìèr fìèlds màtch stàtèd vàlùès. Rùlès àrè gròùpèd: àll rùlès ìn à gròùp mùst hòld fòr thè gròùp tò pàss, ànd thè fìèld àppèàrs whèn àny gròùp pàssès. Sìnglè pìck, mùltìplè pìck, chèckbòx, tèxt, lòng tèxt, ànd dàtè fìèlds càn drìvè à rùlè. Ònly fìèlds èàrlìèr ìn thè fòrm òrdèr qùàlìfy, sò twò fìèlds cànnòt crèàtè à cyclè. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Swìtchìng à fìèld's typè. ••••••••** Thè èdìtòr stàshès thè cònfìgùràtìòn òf thè òùtgòìng typè. Swìtchìng bàck rèstòrès ìt ìnstèàd òf stàrtìng fròm dèfàùlts. Thè èdìtòr clèàrs à ròlè thè ìncòmìng typè cànnòt càrry àt àll. Ìt kèèps à ròlè thàt ìs dìsplàyàblè bùt ìncòmpàtìblè, sò ìt càn shòw thè cònflìct ràthèr thàn sìlèntly dìscàrdìng thè ròùtìng wòrk. [[#fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còmpàtìbìlìty tàblès ànd sàvè schèmà. •••••••••••••** \`RÒLÈ_WÌDGÈT_CÒMPÀTÌBÌLÌTY\` ànd \`ÙNÌQÙÈ_RÒLÈS_PÈR_FÒRM\` ìn \`pàckàgès/shàrèd/src/schèmàs/ìntàkè-fòrms.ts\` dèfìnè bòth rùlès. \`ÌntàkèFìèldCònfìgShèèt.svèltè\` rèàds thèm fòr thè lìvè cònflìct nòtìcè. Thè sàvè schèmà àpplìès thèm às rèfìnèmènts, sò à fòrm àssèmblèd òùtsìdè thè èdìtòr ìs hèld tò thè sàmè cònstràìnts. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Each field type carries its own settings. All types share a label and optional help text in each language and a required switch. Text and long text fields ad..." |
*
* @param {Demo_Narrative_Admin_Field_Config_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_field_config_body = /** @type {((inputs?: Demo_Narrative_Admin_Field_Config_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Field_Config_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_field_config_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_field_config_body(inputs)
	return en_demo_narrative_admin_field_config_body(inputs)
});