/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Sort_BodyInputs */

const en_demo_narrative_topic_sort_body = /** @type {(inputs: Demo_Narrative_Topic_Sort_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The ticket list can be sorted by creation date, priority, last activity, queue, follow-up count, client, title, assignee, and status. Which side performs the sort depends on whether the server can read the field's values or only the browser can. [[#metadata #trust-boundary]]
**Server-paged order.** Creation date, priority, last activity, queue, and follow-up count are plaintext columns, so the server sorts and pages results with creation time and ticket ID as tiebreakers. A sort request tells the server which field and direction the account selected, the same way a filter request does. [Filters](#tickets/filters) covers what else a list request carries. [[#server-holds #metadata]]
**Sorting after decrypt.** Client, title, and assignee are encrypted under the organization key or the ticket key. The New-versus-Active status distinction is derived from a ticket's follow-up count in the browser; the server only stores open and closed. The browser orders these fields over decrypted values after the rows arrive. A row still waiting for its decrypt sorts to the front rather than dropping out of the list. [[#encryption #client-data]]
**Partial-list sorting.** Sorting by a browser-side field while pages remain unfetched orders only the rows already loaded. The list states this and offers to fetch the rest before sorting again. Switching to a server-sorted field hands the entire sort back to the server. [[#failure-states]]
**New replies first.** New-replies-first puts tickets carrying replies the account has not read ahead of the rest, within whatever sort is otherwise active. Read state is encrypted per account, so the server cannot sort by it or detect that the option is on. [Unread badges](#tickets/unread-badges) covers how a reply counts as unread. [[#privacy #client-data]]
**Server query, browser comparator, and field-set gate.** The server clauses are the \`ORDER BY\` and keyset blocks of \`list\` in \`packages/server/src/tickets/ticket-service.ts\`. The browser comparator is \`sortTickets\` in \`packages/client/src/lib/tickets/sort-tickets.ts\`, which mirrors the server's tiebreakers so a partly-server, partly-browser list does not contradict itself. The field set that forces the browser path is \`CLIENT_ONLY_SORT_FIELDS\` in \`packages/client/src/routes/(app)/tickets/+page.svelte\`. [[#client-data]]`)
};

const es_demo_narrative_topic_sort_body = /** @type {(inputs: Demo_Narrative_Topic_Sort_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La lista de tickets se puede ordenar por fecha de creación, prioridad, última actividad, cola, número de seguimientos, cliente, título, persona asignada y estado. El lado que ejecuta la ordenación depende de si el servidor puede leer los valores del campo o solo el navegador puede hacerlo. [[#metadata #trust-boundary]]
**Orden paginado del servidor.** La fecha de creación, la prioridad, la última actividad, la cola y el número de seguimientos son columnas en texto plano, así que el servidor ordena y pagina los resultados con la fecha de creación y el identificador del ticket como desempate. Una petición de orden indica al servidor qué campo y dirección eligió la cuenta, igual que una petición de filtro. [Filtros](#tickets/filters) trata lo demás que lleva una petición de lista. [[#server-holds #metadata]]
**Ordenación tras descifrado.** El cliente, el título y la persona asignada están cifrados con la clave de la organización o con la del ticket. La distinción entre Nuevo y Activo se deriva del número de seguimientos en el navegador; el servidor solo almacena abierto y cerrado. El navegador ordena estos campos sobre los valores descifrados una vez llegan las filas. Una fila que aún espera su descifrado se ordena al principio en lugar de desaparecer de la lista. [[#encryption #client-data]]
**Ordenación parcial de la lista.** Ordenar por un campo del navegador mientras quedan páginas sin recuperar ordena solo las filas ya cargadas. La lista lo indica y ofrece recuperar el resto antes de volver a ordenar. Elegir un campo que el servidor puede ordenar devuelve la ordenación entera al servidor. [[#failure-states]]
**Nuevas respuestas primero.** La opción de nuevas respuestas primero antepone los tickets con respuestas que la cuenta no ha leído al resto, bajo el orden que esté vigente. El estado de lectura está cifrado por cuenta, así que el servidor no puede ordenar por él ni detectar que la opción está activa. [Insignias de no leídos](#tickets/unread-badges) trata cuándo una respuesta cuenta como no leída. [[#privacy #client-data]]
**Consulta del servidor, comparador del navegador y conjunto de campos.** Las cláusulas del servidor son los bloques \`ORDER BY\` y de conjunto de claves de \`list\` en \`packages/server/src/tickets/ticket-service.ts\`. El comparador del navegador es \`sortTickets\` en \`packages/client/src/lib/tickets/sort-tickets.ts\`, que reproduce los desempates del servidor para que una lista mixta no se contradiga. El conjunto de campos que obliga a la ruta del navegador es \`CLIENT_ONLY_SORT_FIELDS\` en \`packages/client/src/routes/(app)/tickets/+page.svelte\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_sort_body = /** @type {(inputs: Demo_Narrative_Topic_Sort_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè tìckèt lìst càn bè sòrtèd by crèàtìòn dàtè, prìòrìty, làst àctìvìty, qùèùè, fòllòw-ùp còùnt, clìènt, tìtlè, àssìgnèè, ànd stàtùs. Whìch sìdè pèrfòrms thè sòrt dèpènds òn whèthèr thè sèrvèr càn rèàd thè fìèld's vàlùès òr ònly thè bròwsèr càn. [[#mètàdàtà #trùst-bòùndàry]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèrvèr-pàgèd òrdèr. ••••••** Crèàtìòn dàtè, prìòrìty, làst àctìvìty, qùèùè, ànd fòllòw-ùp còùnt àrè plàìntèxt còlùmns, sò thè sèrvèr sòrts ànd pàgès rèsùlts wìth crèàtìòn tìmè ànd tìckèt ÌD às tìèbrèàkèrs. À sòrt rèqùèst tèlls thè sèrvèr whìch fìèld ànd dìrèctìòn thè àccòùnt sèlèctèd, thè sàmè wày à fìltèr rèqùèst dòès. [Fìltèrs](#tìckèts/fìltèrs) còvèrs whàt èlsè à lìst rèqùèst càrrìès. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sòrtìng àftèr dècrypt. •••••••** Clìènt, tìtlè, ànd àssìgnèè àrè èncryptèd ùndèr thè òrgànìzàtìòn kèy òr thè tìckèt kèy. Thè Nèw-vèrsùs-Àctìvè stàtùs dìstìnctìòn ìs dèrìvèd fròm à tìckèt's fòllòw-ùp còùnt ìn thè bròwsèr; thè sèrvèr ònly stòrès òpèn ànd clòsèd. Thè bròwsèr òrdèrs thèsè fìèlds òvèr dècryptèd vàlùès àftèr thè ròws àrrìvè. À ròw stìll wàìtìng fòr ìts dècrypt sòrts tò thè frònt ràthèr thàn dròppìng òùt òf thè lìst. [[#èncryptìòn #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pàrtìàl-lìst sòrtìng. •••••••** Sòrtìng by à bròwsèr-sìdè fìèld whìlè pàgès rèmàìn ùnfètchèd òrdèrs ònly thè ròws àlrèàdy lòàdèd. Thè lìst stàtès thìs ànd òffèrs tò fètch thè rèst bèfòrè sòrtìng àgàìn. Swìtchìng tò à sèrvèr-sòrtèd fìèld hànds thè èntìrè sòrt bàck tò thè sèrvèr. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Nèw rèplìès fìrst. ••••••** Nèw-rèplìès-fìrst pùts tìckèts càrryìng rèplìès thè àccòùnt hàs nòt rèàd àhèàd òf thè rèst, wìthìn whàtèvèr sòrt ìs òthèrwìsè àctìvè. Rèàd stàtè ìs èncryptèd pèr àccòùnt, sò thè sèrvèr cànnòt sòrt by ìt òr dètèct thàt thè òptìòn ìs òn. [Ùnrèàd bàdgès](#tìckèts/ùnrèàd-bàdgès) còvèrs hòw à rèply còùnts às ùnrèàd. [[#prìvàcy #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèrvèr qùèry, bròwsèr còmpàràtòr, ànd fìèld-sèt gàtè. ••••••••••••••••** Thè sèrvèr clàùsès àrè thè \`ÒRDÈR BY\` ànd kèysèt blòcks òf \`lìst\` ìn \`pàckàgès/sèrvèr/src/tìckèts/tìckèt-sèrvìcè.ts\`. Thè bròwsèr còmpàràtòr ìs \`sòrtTìckèts\` ìn \`pàckàgès/clìènt/src/lìb/tìckèts/sòrt-tìckèts.ts\`, whìch mìrròrs thè sèrvèr's tìèbrèàkèrs sò à pàrtly-sèrvèr, pàrtly-bròwsèr lìst dòès nòt còntràdìct ìtsèlf. Thè fìèld sèt thàt fòrcès thè bròwsèr pàth ìs \`CLÌÈNT_ÒNLY_SÒRT_FÌÈLDS\` ìn \`pàckàgès/clìènt/src/ròùtès/(àpp)/tìckèts/+pàgè.svèltè\`. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The ticket list can be sorted by creation date, priority, last activity, queue, follow-up count, client, title, assignee, and status. Which side performs the..." |
*
* @param {Demo_Narrative_Topic_Sort_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_sort_body = /** @type {((inputs?: Demo_Narrative_Topic_Sort_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Sort_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_sort_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_sort_body(inputs)
	return en_demo_narrative_topic_sort_body(inputs)
});