/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Submit_BodyInputs */

const en_demo_narrative_client_intake_submit_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Submit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The browser encrypts every answer, composes the ticket title and body from them, and sends only ciphertext to the server. The server creates the ticket, assigns it to a queue, and notifies that queue's members. A failed submission creates nothing and notifies nobody. [[#encryption #server-holds]]
**Multi-page validation.** A form split into pages validates the current page before advancing and lists each problem with the question it belongs to. The visitor can advance past problems on any page except the last. On the last page, validation runs across all pages, lists each problem with its page number, and blocks submission until all are resolved. Pages whose fields depend on an earlier answer that was not given are skipped, and the progress count reflects only the pages that apply. [[#failure-states #client-data]]
**Rate limit.** The server limits submissions per network address per hour. The limit is configured per deployment. A refused visitor sees a message stating how long to wait and can retry without losing what was typed. An organization can also enable a proof-of-work puzzle that the browser solves before each submission. The puzzle is off unless a difficulty is configured. Shared-network visitors are not refused when a single device on the same address has already submitted. [[#failure-states #portal]]
**Where does a submission go?** The ticket goes to the queue named by a routing-role answer when the form has one, then falls back to the form's destination queue, then to the organization's intake queue. Intake cannot be enabled without a queue configured at one of those levels. A missing queue triggers a warning on the administration side. [Queue management](#admin-people/queues) covers queue membership and its effect on access. [[#permissions #metadata]]
**What does the visitor receive?** A successful submission returns a reference code. The code is the generated alias for the new client record, sealed as ciphertext. The form's own confirmation message appears when one is configured. [[#client-data #privacy]]
**The encryption and submission path.** \`handleSubmit\` in \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\` calls \`encryptIntake\` and \`resolveSubmitMetadata\` in \`intake-crypto.ts\`. The server route is \`submitIntake\` in \`packages/server/src/routes/client-portal.ts\`, which checks the rate limit and the puzzle gate before reading any payload. The ticket insert, key wrap, form response, and notification intent run in one transaction in \`createIntakeTicket\` in \`packages/server/src/portal/intake-service.ts\`, so a rollback discards all four. [[#server-holds #failure-states]]`)
};

const es_demo_narrative_client_intake_submit_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Submit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El navegador cifra cada respuesta, compone a partir de ellas el título y el cuerpo del ticket y envía solo texto cifrado al servidor. El servidor crea el ticket, lo asigna a una cola y notifica a los miembros de esa cola. Un envío fallido no crea nada ni notifica a nadie. [[#encryption #server-holds]]
**Validación en varias páginas.** Un formulario dividido en páginas valida la página actual antes de avanzar y lista cada problema con la pregunta a la que pertenece. El visitante puede avanzar a pesar de los problemas en cualquier página salvo la última. En la última página, la validación abarca todas las páginas, lista cada problema con su número de página y bloquea el envío hasta que todos se resuelvan. Las páginas cuyos campos dependen de una respuesta anterior que no se dio se omiten, y el recuento de avance refleja solo las páginas que aplican. [[#failure-states #client-data]]
**Límite de frecuencia.** El servidor limita los envíos por dirección de red por hora. El límite se configura por despliegue. El visitante rechazado ve un mensaje que indica cuánto esperar y puede reintentar sin perder lo que escribió. Una organización también puede activar un rompecabezas de prueba de trabajo que el navegador resuelve antes de cada envío. El rompecabezas está desactivado salvo que se configure una dificultad. Los visitantes en una red compartida no son rechazados cuando un solo dispositivo en la misma dirección ya ha enviado. [[#failure-states #portal]]
**¿Adónde va un envío?** El ticket va a la cola que indica una respuesta con rol de enrutamiento cuando el formulario tiene una, luego recurre a la cola de destino del formulario y luego a la cola de admisión de la organización. La admisión no se puede activar sin tener una cola configurada en alguno de esos niveles. Una cola ausente genera un aviso en el lado de administración. [Gestión de colas](#admin-people/queues) trata la membresía de cola y su efecto sobre el acceso. [[#permissions #metadata]]
**¿Qué recibe el visitante?** Cuando el envío es correcto, el servidor devuelve un código de referencia. El código es el alias generado para el nuevo registro de cliente, sellado como texto cifrado. El mensaje de confirmación del formulario aparece cuando hay uno configurado. [[#client-data #privacy]]
**La ruta de cifrado y envío.** \`handleSubmit\` en \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\` llama a \`encryptIntake\` y \`resolveSubmitMetadata\` en \`intake-crypto.ts\`. La ruta del servidor es \`submitIntake\` en \`packages/server/src/routes/client-portal.ts\`, que comprueba el límite de frecuencia y la barrera del rompecabezas antes de leer cualquier dato. La inserción del ticket, la envoltura de clave, la respuesta del formulario y la intención de notificación se ejecutan en una sola transacción en \`createIntakeTicket\` en \`packages/server/src/portal/intake-service.ts\`, de modo que una reversión descarta las cuatro. [[#server-holds #failure-states]]`)
};

const en_xa2_demo_narrative_client_intake_submit_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Submit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè bròwsèr èncrypts èvèry ànswèr, còmpòsès thè tìckèt tìtlè ànd bòdy fròm thèm, ànd sènds ònly cìphèrtèxt tò thè sèrvèr. Thè sèrvèr crèàtès thè tìckèt, àssìgns ìt tò à qùèùè, ànd nòtìfìès thàt qùèùè's mèmbèrs. À fàìlèd sùbmìssìòn crèàtès nòthìng ànd nòtìfìès nòbòdy. [[#èncryptìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Mùltì-pàgè vàlìdàtìòn. •••••••** À fòrm splìt ìntò pàgès vàlìdàtès thè cùrrènt pàgè bèfòrè àdvàncìng ànd lìsts èàch pròblèm wìth thè qùèstìòn ìt bèlòngs tò. Thè vìsìtòr càn àdvàncè pàst pròblèms òn àny pàgè èxcèpt thè làst. Òn thè làst pàgè, vàlìdàtìòn rùns àcròss àll pàgès, lìsts èàch pròblèm wìth ìts pàgè nùmbèr, ànd blòcks sùbmìssìòn ùntìl àll àrè rèsòlvèd. Pàgès whòsè fìèlds dèpènd òn àn èàrlìèr ànswèr thàt wàs nòt gìvèn àrè skìppèd, ànd thè prògrèss còùnt rèflècts ònly thè pàgès thàt àpply. [[#fàìlùrè-stàtès #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ràtè lìmìt. ••••** Thè sèrvèr lìmìts sùbmìssìòns pèr nètwòrk àddrèss pèr hòùr. Thè lìmìt ìs cònfìgùrèd pèr dèplòymènt. À rèfùsèd vìsìtòr sèès à mèssàgè stàtìng hòw lòng tò wàìt ànd càn rètry wìthòùt lòsìng whàt wàs typèd. Àn òrgànìzàtìòn càn àlsò ènàblè à pròòf-òf-wòrk pùzzlè thàt thè bròwsèr sòlvès bèfòrè èàch sùbmìssìòn. Thè pùzzlè ìs òff ùnlèss à dìffìcùlty ìs cònfìgùrèd. Shàrèd-nètwòrk vìsìtòrs àrè nòt rèfùsèd whèn à sìnglè dèvìcè òn thè sàmè àddrèss hàs àlrèàdy sùbmìttèd. [[#fàìlùrè-stàtès #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèrè dòès à sùbmìssìòn gò? •••••••••** Thè tìckèt gòès tò thè qùèùè nàmèd by à ròùtìng-ròlè ànswèr whèn thè fòrm hàs ònè, thèn fàlls bàck tò thè fòrm's dèstìnàtìòn qùèùè, thèn tò thè òrgànìzàtìòn's ìntàkè qùèùè. Ìntàkè cànnòt bè ènàblèd wìthòùt à qùèùè cònfìgùrèd àt ònè òf thòsè lèvèls. À mìssìng qùèùè trìggèrs à wàrnìng òn thè àdmìnìstràtìòn sìdè. [Qùèùè mànàgèmènt](#àdmìn-pèòplè/qùèùès) còvèrs qùèùè mèmbèrshìp ànd ìts èffèct òn àccèss. [[#pèrmìssìòns #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè vìsìtòr rècèìvè? •••••••••** À sùccèssfùl sùbmìssìòn rètùrns à rèfèrèncè còdè. Thè còdè ìs thè gènèràtèd àlìàs fòr thè nèw clìènt rècòrd, sèàlèd às cìphèrtèxt. Thè fòrm's òwn cònfìrmàtìòn mèssàgè àppèàrs whèn ònè ìs cònfìgùrèd. [[#clìènt-dàtà #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè èncryptìòn ànd sùbmìssìòn pàth. •••••••••••** \`hàndlèSùbmìt\` ìn \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/ÌntàkèFòrmBòdy.svèltè\` càlls \`èncryptÌntàkè\` ànd \`rèsòlvèSùbmìtMètàdàtà\` ìn \`ìntàkè-cryptò.ts\`. Thè sèrvèr ròùtè ìs \`sùbmìtÌntàkè\` ìn \`pàckàgès/sèrvèr/src/ròùtès/clìènt-pòrtàl.ts\`, whìch chècks thè ràtè lìmìt ànd thè pùzzlè gàtè bèfòrè rèàdìng àny pàylòàd. Thè tìckèt ìnsèrt, kèy wràp, fòrm rèspònsè, ànd nòtìfìcàtìòn ìntènt rùn ìn ònè trànsàctìòn ìn \`crèàtèÌntàkèTìckèt\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-sèrvìcè.ts\`, sò à ròllbàck dìscàrds àll fòùr. [[#sèrvèr-hòlds #fàìlùrè-stàtès]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The browser encrypts every answer, composes the ticket title and body from them, and sends only ciphertext to the server. The server creates the ticket, assi..." |
*
* @param {Demo_Narrative_Client_Intake_Submit_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_submit_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Submit_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Submit_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_submit_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_submit_body(inputs)
	return en_demo_narrative_client_intake_submit_body(inputs)
});