/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Fields_BodyInputs */

const en_demo_narrative_client_intake_fields_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Fields_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A published form carries its own questions, and the page renders whatever field set the organization saved in place of the built-in one. Text, long text, dropdowns, checkboxes, dates, numbers and an availability picker are the shapes a question can take. [[#portal #client-data]]
**How a question is protected.** Field labels, help text and configuration are stored encrypted under a key derived from the organization's public key. Anyone who can read that public key can derive that key, so the encryption keeps a stolen database from listing what a crisis line asks its callers and does not hide the questions from the server that serves them. The answers are encrypted under a key the server has no way to derive. [How encryption works](#deep-dive/how-encryption-works) covers the two key trees. [[#encryption #server-holds]]
**Questions that depend on an earlier answer.** A field can be set to appear only when another field holds a particular value, and a field that stays hidden is left out of the encrypted answer set and out of the case text. The server is never handed an answer to a question the visitor was not shown. [[#client-data #privacy]]
**What a field role tells the server.** Most questions carry no role and produce nothing the server can read. A question given a routing, urgency or escalation role works differently, because the browser resolves the chosen option to a queue, a priority or an alert level and sends that single resolved value in the clear, while the answer text stays encrypted like every other. Someone reading a database dump learns which queue a case went to and not the sentence that sent it there. [Field roles and mappings](#admin-forms/field-config) covers how a role is configured. [[#metadata #server-holds]]
**What the visitor is told about each field.** A field carrying a role that produces a server-visible signal is marked as producing one, a field whose role produces nothing readable is marked as encrypted, and a field with no role carries no mark. The distinction is made where the visitor is deciding what to type rather than in a policy page. [[#privacy #metadata]]
**The field rows and the derived key.** Field definitions live in \`intake_form_fields\` from \`packages/server/src/db/migrations/tenant/089_intake_forms.ts\`, where \`encrypted_label\` and \`encrypted_config\` are ciphertext, \`role\` is a plaintext tag and \`routing_queue_ids\` is a plaintext allow-list the server checks a resolved queue against. The key comes from \`deriveClientBrandingKey\` in \`packages/crypto/src/branding.ts\` and the four encrypt and decrypt functions are in \`packages/crypto/src/intake-form.ts\`, so a second producer cannot restate the associated data by hand. Visibility evaluation and page slicing are \`packages/client/src/routes/(client)/intake/intake-form-logic.ts\`. [[#server-holds #encryption]]`)
};

const es_demo_narrative_client_intake_fields_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Fields_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un formulario publicado lleva sus propias preguntas, y la página muestra el conjunto de campos que la organización haya guardado en lugar del integrado. Texto, texto largo, listas desplegables, casillas, fechas, números y un selector de disponibilidad son las formas que puede tomar una pregunta. [[#portal #client-data]]
**Cómo se protege una pregunta.** Las etiquetas de campo, el texto de ayuda y la configuración se guardan cifrados con una clave derivada de la clave pública de la organización. Cualquiera que pueda leer esa clave pública puede derivarla, así que el cifrado impide que una base de datos robada enumere lo que una línea de crisis pregunta a quien llama y no oculta las preguntas al servidor que las sirve. Las respuestas se cifran con una clave que el servidor no tiene forma de derivar. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata los dos árboles de claves. [[#encryption #server-holds]]
**Preguntas que dependen de una respuesta anterior.** Un campo puede configurarse para aparecer solo cuando otro campo tiene un valor determinado, y un campo que permanece oculto queda fuera del conjunto de respuestas cifradas y fuera del texto del caso. Al servidor nunca se le entrega una respuesta a una pregunta que el visitante no vio. [[#client-data #privacy]]
**Lo que el rol de un campo le dice al servidor.** La mayoría de las preguntas no llevan rol y no producen nada que el servidor pueda leer. Una pregunta con un rol de enrutamiento, urgencia o escalamiento funciona de otro modo, porque el navegador resuelve la opción elegida a una cola, una prioridad o un nivel de alerta y envía ese único valor resuelto en claro, mientras que el texto de la respuesta sigue cifrado como todos los demás. Quien lea un volcado de la base de datos sabe a qué cola fue un caso y no la frase que lo mandó allí. [Roles de campo y asignaciones](#admin-forms/field-config) trata cómo se configura un rol. [[#metadata #server-holds]]
**Lo que se le dice al visitante sobre cada campo.** Un campo con un rol que produce una señal visible para el servidor se marca como tal, un campo cuyo rol no produce nada legible se marca como cifrado, y un campo sin rol no se marca. La distinción se hace donde el visitante decide qué escribir y no en una página de políticas. [[#privacy #metadata]]
**Las filas de campo y la clave derivada.** Las definiciones de campo viven en \`intake_form_fields\`, de \`packages/server/src/db/migrations/tenant/089_intake_forms.ts\`, donde \`encrypted_label\` y \`encrypted_config\` son texto cifrado, \`role\` es una etiqueta en texto plano y \`routing_queue_ids\` es una lista de permitidos en texto plano contra la que el servidor comprueba una cola resuelta. La clave sale de \`deriveClientBrandingKey\`, en \`packages/crypto/src/branding.ts\`, y las cuatro funciones de cifrado y descifrado están en \`packages/crypto/src/intake-form.ts\`, de modo que un segundo productor no puede reescribir a mano los datos asociados. La evaluación de visibilidad y el reparto en páginas están en \`packages/client/src/routes/(client)/intake/intake-form-logic.ts\`. [[#server-holds #encryption]]`)
};

const en_xa2_demo_narrative_client_intake_fields_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Fields_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Whèn thè òrgànìzàtìòn hàs pùblìshèd à cùstòm ìntàkè fòrm, thè ìntàkè pàgè shòws ìts cònfìgùrèd fìèlds ìnstèàd òf thè bùìlt-ìn dèfàùlt.
 •••••••••••••••••••••••••••••••••••••••••**Còndìtìònàl fìèlds. ••••••** Thè sèrvèr nèvèr rècèìvès àn ànswèr thè vìsìtòr dìd nòt sèè, bècàùsè à fìèld wìth à vìsìbìlìty còndìtìòn stàys hìddèn ùntìl thè còntròllìng fìèld hàs thè rèqùìrèd vàlùè, ànd hìddèn fìèlds àrè èxclùdèd fròm bòth thè èncryptèd rèspònsè ànd thè tìckèt tèxt.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pàgìng. •••** Whèn thè fòrm hàs pàgè brèàks thè nèxt bùttòn vàlìdàtès thè cùrrènt pàgè's vìsìblè fìèlds bèfòrè àdvàncìng, ànd thè sùbmìt bùttòn àppèàrs ònly òn thè fìnàl pàgè.
 •••••••••••••••••••••••••••••••••••••••••••••••••**Èncryptìòn. ••••** Ònly sòmèònè whò hòlds thè òrgànìzàtìòn's prìvàtè kèy càn rèàd à sùbmìttèd ànswèr, bècàùsè thè ìntàkè fòrm gènèràtès à frèsh symmètrìc còntènt kèy fòr èàch sùbmìssìòn, èncrypts èvèry fìèld vàlùè wìth thàt kèy, ànd sèàls thè còntènt kèy tò thè òrgànìzàtìòn's pùblìc kèy. Fìèld làbèls ànd hèlp tèxt àrè èncryptèd ùndèr à kèy àny vìsìtòr's bròwsèr càn dèrìvè fròm pùblìcly àvàìlàblè ìnfòrmàtìòn, whìch pròtècts thèm ìn à dàtàbàsè dùmp bùt nòt àgàìnst à lìvè sèrvèr.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Prìvàcy ìndìcàtòr. ••••••** Fìèlds thàt càrry à sèmàntìc ròlè shòw à pèr-fìèld ìndìcàtòr òn thè ìntàkè fòrm. À fìèld whòsè ròlè ìs bròwsèr-ònly shòws thàt thè ànswèr ìs èncryptèd ànd thè sèrvèr cànnòt rèàd ìt, ànd à fìèld thàt càrrìès à ròùtìng ròlè shòws thàt thè ànswèr ìs èncryptèd bùt thè vìsìtòr's sèlèctìòn shàrès à dèrìvèd sìgnàl wìth thè sèrvèr, bècàùsè thè bròwsèr rèsòlvès thè sèlèctèd òptìòn tò à qùèùè, prìòrìty, òr èscàlàtìòn vàlùè ànd sènds thàt dèrìvèd sìgnàl ìn thè clèàr whìlè thè ànswèr tèxt stàys èncryptèd. Fìèlds wìth nò sèmàntìc ròlè shòw nò ìndìcàtòr àt àll. •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A published form carries its own questions, and the page renders whatever field set the organization saved in place of the built-in one. Text, long text, dro..." |
*
* @param {Demo_Narrative_Client_Intake_Fields_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_fields_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Fields_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Fields_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_fields_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_fields_body(inputs)
	return en_demo_narrative_client_intake_fields_body(inputs)
});