/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Protection_BodyInputs */

const en_demo_narrative_client_intake_protection_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Protection_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The page states what it protects before the visitor types anything, because the decision it asks for is whether typing here is safe at all. Every value is encrypted in the browser, the server receives ciphertext it holds no key for, and nobody outside the organization can open it. [[#privacy #encryption]]
**Who can open a fresh submission.** A submission arrives with no relationship to any particular person in the organization, so its key is sealed to the organization's public key and every holder of the organization's private key can open it. Once someone first opens the case, the key is re-wrapped for the people working it and the organization-wide wrap is deleted, so access narrows from that moment and does not narrow before it. [How encryption works](#deep-dive/how-encryption-works) covers the organization key. [[#keys #permissions]]
**When the per-person wraps are minted.** Nothing is wrapped per person at submission time. The first open converts the sealed wrap into one wrap per queue member and per holder of the intake-response permission, and a later request can mint wraps for principals a conversion missed, which is how someone added to the queue afterward gains a key without the visitor being involved. [The permission system](#deep-dive/the-permission-system) covers who those holders are. [[#keys #permissions]]
**What the server is left with.** The row carries the ciphertext, the sealed key, a generated alias for the new client record and the timestamps of the writes. A database dump shows that a submission happened, when, and which queue it landed in, and none of what was said. [The trust boundary](#deep-dive/the-trust-boundary) covers what else stays readable in the schema. [[#server-holds #metadata]]
**The seal, the conversion and the interim row.** The browser seals the per-submission key in \`encryptIntake\` in \`packages/client/src/routes/(client)/intake/intake-crypto.ts\`, the server stores it in \`intake_key_wraps\` from \`packages/server/src/db/migrations/tenant/089_intake_forms.ts\`, and \`packages/server/src/portal/intake-conversion-service.ts\` replaces it with per-holder wraps and deletes the interim row in one transaction. The later minting path is \`backfillWraps\` in \`packages/server/src/portal/intake-response-service.ts\`. [[#keys #server-holds]]`)
};

const es_demo_narrative_client_intake_protection_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Protection_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La página declara qué protege antes de que el visitante escriba nada, porque la decisión que le pide es si escribir aquí es seguro. Cada valor se cifra en el navegador, el servidor recibe texto cifrado para el que no tiene ninguna clave y nadie fuera de la organización puede abrirlo. [[#privacy #encryption]]
**Quién puede abrir un envío recién llegado.** Un envío llega sin relación con ninguna persona concreta de la organización, así que su clave se sella con la clave pública de la organización y cualquiera que tenga la clave privada de la organización puede abrirlo. Cuando alguien abre el caso por primera vez, la clave se vuelve a envolver para las personas que lo trabajan y se elimina la envoltura de toda la organización, de modo que el acceso se restringe a partir de ese momento y no antes. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la clave de la organización. [[#keys #permissions]]
**Cuándo se acuñan las envolturas por persona.** En el momento del envío no se envuelve nada por persona. La primera apertura convierte la envoltura sellada en una envoltura por cada miembro de la cola y por cada titular del permiso de respuestas de admisión, y una petición posterior puede acuñar envolturas para los principales que una conversión no cubrió, que es como alguien añadido a la cola después obtiene una clave sin que el visitante intervenga. [El sistema de permisos](#deep-dive/the-permission-system) trata quiénes son esos titulares. [[#keys #permissions]]
**Con qué se queda el servidor.** La fila lleva el texto cifrado, la clave sellada, un alias generado para el nuevo registro de cliente y las marcas de tiempo de las escrituras. Un volcado de la base de datos muestra que hubo un envío, cuándo y en qué cola cayó, y nada de lo que se dijo. [La frontera de confianza](#deep-dive/the-trust-boundary) trata qué más queda legible en el esquema. [[#server-holds #metadata]]
**El sellado, la conversión y la fila interina.** El navegador sella la clave de cada envío en \`encryptIntake\`, en \`packages/client/src/routes/(client)/intake/intake-crypto.ts\`; el servidor la guarda en \`intake_key_wraps\`, de \`packages/server/src/db/migrations/tenant/089_intake_forms.ts\`; y \`packages/server/src/portal/intake-conversion-service.ts\` la sustituye por envolturas por titular y elimina la fila interina en una sola transacción. La vía de acuñación posterior es \`backfillWraps\`, en \`packages/server/src/portal/intake-response-service.ts\`. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_client_intake_protection_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Protection_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè pàgè stàtès whàt ìt pròtècts bèfòrè thè vìsìtòr typès ànythìng, bècàùsè thè dècìsìòn ìt àsks fòr ìs whèthèr typìng hèrè ìs sàfè àt àll. Èvèry vàlùè ìs èncryptèd ìn thè bròwsèr, thè sèrvèr rècèìvès cìphèrtèxt ìt hòlds nò kèy fòr, ànd nòbòdy òùtsìdè thè òrgànìzàtìòn càn òpèn ìt. [[#prìvàcy #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn òpèn à frèsh sùbmìssìòn. ••••••••••** À sùbmìssìòn àrrìvès wìth nò rèlàtìònshìp tò àny pàrtìcùlàr pèrsòn ìn thè òrgànìzàtìòn, sò ìts kèy ìs sèàlèd tò thè òrgànìzàtìòn's pùblìc kèy ànd èvèry hòldèr òf thè òrgànìzàtìòn's prìvàtè kèy càn òpèn ìt. Òncè sòmèònè fìrst òpèns thè càsè, thè kèy ìs rè-wràppèd fòr thè pèòplè wòrkìng ìt ànd thè òrgànìzàtìòn-wìdè wràp ìs dèlètèd, sò àccèss nàrròws fròm thàt mòmènt ànd dòès nòt nàrròw bèfòrè ìt. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè òrgànìzàtìòn kèy. [[#kèys #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn thè pèr-pèrsòn wràps àrè mìntèd. ••••••••••••** Nòthìng ìs wràppèd pèr pèrsòn àt sùbmìssìòn tìmè. Thè fìrst òpèn cònvèrts thè sèàlèd wràp ìntò ònè wràp pèr qùèùè mèmbèr ànd pèr hòldèr òf thè ìntàkè-rèspònsè pèrmìssìòn, ànd à làtèr rèqùèst càn mìnt wràps fòr prìncìpàls à cònvèrsìòn mìssèd, whìch ìs hòw sòmèònè àddèd tò thè qùèùè àftèrwàrd gàìns à kèy wìthòùt thè vìsìtòr bèìng ìnvòlvèd. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs whò thòsè hòldèrs àrè. [[#kèys #pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè sèrvèr ìs lèft wìth. •••••••••** Thè ròw càrrìès thè cìphèrtèxt, thè sèàlèd kèy, à gènèràtèd àlìàs fòr thè nèw clìènt rècòrd ànd thè tìmèstàmps òf thè wrìtès. À dàtàbàsè dùmp shòws thàt à sùbmìssìòn hàppènèd, whèn, ànd whìch qùèùè ìt làndèd ìn, ànd nònè òf whàt wàs sàìd. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whàt èlsè stàys rèàdàblè ìn thè schèmà. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè sèàl, thè cònvèrsìòn ànd thè ìntèrìm ròw. ••••••••••••••** Thè bròwsèr sèàls thè pèr-sùbmìssìòn kèy ìn \`èncryptÌntàkè\` ìn \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/ìntàkè-cryptò.ts\`, thè sèrvèr stòrès ìt ìn \`ìntàkè_kèy_wràps\` fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/089_ìntàkè_fòrms.ts\`, ànd \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-cònvèrsìòn-sèrvìcè.ts\` rèplàcès ìt wìth pèr-hòldèr wràps ànd dèlètès thè ìntèrìm ròw ìn ònè trànsàctìòn. Thè làtèr mìntìng pàth ìs \`bàckfìllWràps\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-rèspònsè-sèrvìcè.ts\`. [[#kèys #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The page states what it protects before the visitor types anything, because the decision it asks for is whether typing here is safe at all. Every value is en..." |
*
* @param {Demo_Narrative_Client_Intake_Protection_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_protection_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Protection_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Protection_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_protection_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_protection_body(inputs)
	return en_demo_narrative_client_intake_protection_body(inputs)
});