/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Fields_BodyInputs */

const en_demo_narrative_client_intake_fields_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Fields_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Each organization can replace the built-in form with one carrying its own fields. The data field types are text, text area, dropdown, checkboxes, checkbox, date, and availability. Page break and text block shape the form without collecting an answer. Everything written into a form is public to anyone who opens the form's public page. The answers a visitor types are encrypted under a per-case key the server cannot derive. [[#portal #client-data]]
**Conditional fields.** A field can depend on an earlier answer. When its condition is not met, the field stays hidden and its value is excluded from the encrypted answers. The browser submits answers only for fields the visitor was shown. [[#client-data #privacy]]
**What does a field role store readably?** Most fields have no role and produce no server-readable metadata. A field assigned a routing, urgency, or escalation role changes that. For those fields, the browser looks up the visitor's selection in a mapping and sends the result (a queue ID, a priority level, or an alert level) without encryption. When each option maps to a different value, the stored result identifies which option the visitor picked. The answer text stays encrypted, but the mapping can narrow it to one possibility. [Field settings](#admin-forms/field-config) covers how a role is configured. [[#metadata #server-holds]]
**What does each field tell the visitor?** A field whose role produces server-readable metadata carries a notice stating that. A field whose role produces nothing readable carries a notice stating the answer is encrypted. A field with no role carries no notice. [[#privacy #metadata]]
**The field table and the key path.** Field definitions live in \`intake_form_fields\` (migration \`089_intake_forms.ts\`), where \`role\` is a plaintext tag and \`routing_queue_ids\` is a plaintext allow-list. Answers are encrypted by \`encryptIntake\` in \`packages/client/src/routes/(client)/intake/intake-crypto.ts\`. The helpers for form field definitions and form metadata are in \`packages/crypto/src/intake-form.ts\`. Visibility evaluation and page slicing are in \`packages/client/src/routes/(client)/intake/intake-form-logic.ts\`. [[#server-holds #encryption]]`)
};

const es_demo_narrative_client_intake_fields_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Fields_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cada organización puede reemplazar el formulario predeterminado con uno que lleve sus propios campos. Los tipos de campo de datos son texto, área de texto, lista desplegable, casillas de verificación, casilla de verificación, fecha y disponibilidad. Salto de página y bloque de texto dan forma al formulario sin recoger una respuesta. Todo lo que se escribe en un formulario es público para cualquier persona que abra la página pública del formulario. Las respuestas que escribe el visitante se cifran con una clave por caso que el servidor no puede derivar. [[#portal #client-data]]
**Campos condicionales.** Un campo puede depender de una respuesta anterior. Cuando su condición no se cumple, el campo permanece oculto y su valor queda excluido de las respuestas cifradas. El navegador envía respuestas solo para los campos que se mostraron al visitante. [[#client-data #privacy]]
**¿Qué almacena un rol de campo de forma legible?** La mayoría de los campos no tienen rol y no producen metadatos legibles por el servidor. Un campo con rol de enrutamiento, urgencia o escalamiento cambia eso. Para esos campos, el navegador busca la selección del visitante en un mapeo y envía el resultado (un ID de cola, un nivel de prioridad o un nivel de alerta) sin cifrar. Cuando cada opción apunta a un valor diferente, el resultado almacenado identifica qué opción eligió el visitante. El texto de la respuesta permanece cifrado, pero el mapeo puede reducirlo a una sola posibilidad. [Configuración de campo](#admin-forms/field-config) trata cómo se configura un rol. [[#metadata #server-holds]]
**¿Qué le indica cada campo al visitante?** Un campo cuyo rol produce metadatos legibles por el servidor lleva un aviso que lo indica. Un campo cuyo rol no produce nada legible lleva un aviso que indica que la respuesta está cifrada. Un campo sin rol no lleva aviso. [[#privacy #metadata]]
**La tabla de campos y la ruta de la clave.** Las definiciones de campo residen en \`intake_form_fields\` (migración \`089_intake_forms.ts\`), donde \`role\` es una etiqueta en texto claro y \`routing_queue_ids\` es una lista blanca en texto claro. Las respuestas se cifran con \`encryptIntake\` en \`packages/client/src/routes/(client)/intake/intake-crypto.ts\`. Los ayudantes para las definiciones de campo y los metadatos del formulario están en \`packages/crypto/src/intake-form.ts\`. La evaluación de visibilidad y la división en páginas están en \`packages/client/src/routes/(client)/intake/intake-form-logic.ts\`. [[#server-holds #encryption]]`)
};

const en_xa2_demo_narrative_client_intake_fields_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Fields_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èàch òrgànìzàtìòn càn rèplàcè thè bùìlt-ìn fòrm wìth ònè càrryìng ìts òwn fìèlds. Thè dàtà fìèld typès àrè tèxt, tèxt àrèà, dròpdòwn, chèckbòxès, chèckbòx, dàtè, ànd àvàìlàbìlìty. Pàgè brèàk ànd tèxt blòck shàpè thè fòrm wìthòùt còllèctìng àn ànswèr. Èvèrythìng wrìttèn ìntò à fòrm ìs pùblìc tò ànyònè whò òpèns thè fòrm's pùblìc pàgè. Thè ànswèrs à vìsìtòr typès àrè èncryptèd ùndèr à pèr-càsè kèy thè sèrvèr cànnòt dèrìvè. [[#pòrtàl #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Còndìtìònàl fìèlds. ••••••** À fìèld càn dèpènd òn àn èàrlìèr ànswèr. Whèn ìts còndìtìòn ìs nòt mèt, thè fìèld stàys hìddèn ànd ìts vàlùè ìs èxclùdèd fròm thè èncryptèd ànswèrs. Thè bròwsèr sùbmìts ànswèrs ònly fòr fìèlds thè vìsìtòr wàs shòwn. [[#clìènt-dàtà #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à fìèld ròlè stòrè rèàdàbly? ••••••••••••** Mòst fìèlds hàvè nò ròlè ànd pròdùcè nò sèrvèr-rèàdàblè mètàdàtà. À fìèld àssìgnèd à ròùtìng, ùrgèncy, òr èscàlàtìòn ròlè chàngès thàt. Fòr thòsè fìèlds, thè bròwsèr lòòks ùp thè vìsìtòr's sèlèctìòn ìn à màppìng ànd sènds thè rèsùlt (à qùèùè ÌD, à prìòrìty lèvèl, òr àn àlèrt lèvèl) wìthòùt èncryptìòn. Whèn èàch òptìòn màps tò à dìffèrènt vàlùè, thè stòrèd rèsùlt ìdèntìfìès whìch òptìòn thè vìsìtòr pìckèd. Thè ànswèr tèxt stàys èncryptèd, bùt thè màppìng càn nàrròw ìt tò ònè pòssìbìlìty. [Fìèld sèttìngs](#àdmìn-fòrms/fìèld-cònfìg) còvèrs hòw à ròlè ìs cònfìgùrèd. [[#mètàdàtà #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès èàch fìèld tèll thè vìsìtòr? ••••••••••••** À fìèld whòsè ròlè pròdùcès sèrvèr-rèàdàblè mètàdàtà càrrìès à nòtìcè stàtìng thàt. À fìèld whòsè ròlè pròdùcès nòthìng rèàdàblè càrrìès à nòtìcè stàtìng thè ànswèr ìs èncryptèd. À fìèld wìth nò ròlè càrrìès nò nòtìcè. [[#prìvàcy #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fìèld tàblè ànd thè kèy pàth. ••••••••••** Fìèld dèfìnìtìòns lìvè ìn \`ìntàkè_fòrm_fìèlds\` (mìgràtìòn \`089_ìntàkè_fòrms.ts\`), whèrè \`ròlè\` ìs à plàìntèxt tàg ànd \`ròùtìng_qùèùè_ìds\` ìs à plàìntèxt àllòw-lìst. Ànswèrs àrè èncryptèd by \`èncryptÌntàkè\` ìn \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/ìntàkè-cryptò.ts\`. Thè hèlpèrs fòr fòrm fìèld dèfìnìtìòns ànd fòrm mètàdàtà àrè ìn \`pàckàgès/cryptò/src/ìntàkè-fòrm.ts\`. Vìsìbìlìty èvàlùàtìòn ànd pàgè slìcìng àrè ìn \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/ìntàkè-fòrm-lògìc.ts\`. [[#sèrvèr-hòlds #èncryptìòn]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Each organization can replace the built-in form with one carrying its own fields. The data field types are text, text area, dropdown, checkboxes, checkbox, d..." |
*
* @param {Demo_Narrative_Client_Intake_Fields_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_fields_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Fields_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Fields_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_fields_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_fields_body(inputs)
	return en_demo_narrative_client_intake_fields_body(inputs)
});