/* eslint-disable */
import * as registry from '../registry.js'
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Permission_System_BodyInputs */

const en_demo_narrative_deepdive_permission_system_body = /** @type {(inputs: Demo_Narrative_Deepdive_Permission_System_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Every organization divides work differently, so CARE-Y ships three roles with sensible defaults and lets the organization move almost every individual ability between them. The three roles are Volunteer, Manager and Admin. What each one can actually do is a set of fifty keys across eight capability groups, and an administrator can hand a key to a role that did not have it or take one away from a role that did. [[#permissions]]
The keys are grouped by the kind of work they govern rather than by seniority. [[#permissions]]
- Keys for the case record separate reading a case from acting on one, so viewing, opening, editing the summary, writing notes, changing status, linking, claiming, assigning, deleting someone else's note and downloading media each move on their own. [[#permissions #client-data]]
- Keys for reaching a client are split by channel, one each for texting, email, calling and messaging in the portal, so an organization can staff them differently, with one key for sending files that applies across every channel. [[#permissions #telephony]]
- Keys for the client's own access to their case cover share links, portal channels, login resets and revoking reply links. [[#permissions #portal]]
- Keys for client records cover viewing clients, viewing their personal information, editing contact details, editing aliases, merging and deleting. [[#permissions #client-data]]
- Keys for the knowledge base cover reading, writing, managing categories and deleting articles. [[#permissions]]
- Keys for queues separate queue management, queue membership and queue notifications. [[#permissions]]
- Keys for intake separate designing forms from viewing submitted responses. [[#permissions]]
- Keys for running the organization cover roles, users, identity, channel routing, retention, note types, encryption keys, infrastructure, greetings, automatic replies, voicemail quarantine, escalation, presets, reports and the audit log. [[#permissions]]
Defaults are chosen so that turning the system on changes nobody's day. Each key sits at the level that gated the same operation before the keys existed, which is why the client-contact keys start at Volunteer level even though an organization might prefer otherwise. Reaching a client used to require only a session, so starting those keys anywhere higher would have meant a fresh install where nobody can answer anyone. An organization that wants a back-office role withholds those keys deliberately. [[#permissions]]
Managing encryption keys, managing roles, and managing infrastructure stay with Admin whatever anyone configures, so that no role can ever grant itself permissions. That lock is enforced when an override is written and again when permissions are read, so a row inserted directly into the database granting one of the three to another role has no effect. [[#permissions #failure-states]]
Permissions govern actions, not visibility of already-released material. Someone holding the intake responses key receives a key wrap for each submission at the moment it arrives, so taking the key away stops future wraps and leaves the ones already issued intact, and the matrix marks that row as a capability rather than a view toggle for exactly that reason. One key is declared for an operation that does not exist yet, so seeing "View own shifts" in the list does not mean a feature is behind it. [[#permissions #failure-states #encryption]]
**How an effective set is computed.** Each role has a default set in server-side configuration, and per-organization overrides live in \`role_permission_overrides\`, one sparse row per role and permission with an enabled flag. Setting a permission back to its default deletes the row rather than storing it. The merge then runs in four steps. [[#permissions #server-holds]]
1. Start from the role's default set. [[#permissions]]
2. Apply each override row as an add or a remove. [[#permissions]]
3. Ignore override rows naming an unknown permission, so removed or future names do not break the merge. [[#permissions]]
4. Enforce the locks by force-adding all three locked keys to Admin and force-removing them from every other role. [[#permissions #failure-states]]
Role ids in the database are deliberately opaque strings rather than readable names, so a database-only attacker cannot infer the organization's structure from them, and the human-readable name lives server-side until encrypted admin configuration carries it. [[#permissions #server-holds]]
**Caching and its deployment constraint.** Effective sets are cached per organization in process memory, filled for all three roles in one query on a miss, and invalidated by every override mutation so a revoked permission stops working on the next request rather than after a timeout. That cache is process-local, which means a multi-instance deployment would let one instance keep serving a revoked set after another instance invalidated its own copy. The server refuses to boot with multiple instances enabled for exactly that reason, and a shared-store cache is the prerequisite for lifting the restriction. [[#permissions #failure-states]]
**Queue membership is a separate grant.** Membership in a queue grants read access to every case in that queue, and it is governed by its own key rather than riding on queue management or on notification routing. Keeping those three apart is what keeps the access grant visible as a grant. Notification routing determines who gets pinged and grants no access on its own. [[#permissions #trust-boundary]]
**Contributor pointers.** The names, the enforcement and the surfaces sit in four places. [[#permissions]]
- \`packages/shared/src/roles.ts\` holds the \`Permission\` enum and its grouping, and it is append-only after deployment because renaming a member orphans every override row that names it. [[#permissions]]
- \`packages/server/src/auth/roles.ts\` holds role defaults, the lock set, the merge function, the cache, the override repository and the permission-holder queries that intake and notification targeting use, with request-time gating in \`role-middleware.ts\`. [[#permissions]]
- \`packages/server/src/db/migrations/tenant/086_create_role_permission_overrides.ts\` defines the override table. [[#permissions #server-holds]]
- \`packages/client/src/lib/components/admin/RolePermissionsSection.svelte\` is the administrative surface, and \`packages/client/src/lib/shell/section-registry.ts\` maps sections to permissions for client-side gating. [[#permissions]]`)
};

const es_demo_narrative_deepdive_permission_system_body = /** @type {(inputs: Demo_Narrative_Deepdive_Permission_System_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cada organización reparte el trabajo de forma distinta, así que CARE-Y viene con tres roles con valores predeterminados sensatos y deja que la organización mueva casi cualquier capacidad individual entre ellos. Los tres roles son Voluntario, Gestor y Administrador. Lo que cada uno puede hacer realmente es un conjunto de cincuenta llaves repartidas en ocho grupos de capacidades, y una persona administradora puede entregar una llave a un rol que no la tenía o quitarla a un rol que sí. [[#permissions]]
Las llaves se agrupan por el tipo de trabajo que gobiernan y no por antigüedad. [[#permissions]]
- Las llaves del expediente del caso separan leer un caso de actuar sobre él, así que ver, abrir, editar el resumen, escribir notas, cambiar el estado, vincular, reclamar, asignar, eliminar la nota de otra persona y descargar archivos multimedia se mueven cada una por su cuenta. [[#permissions #client-data]]
- Las llaves para contactar a un cliente están divididas por canal, una para los mensajes de texto, otra para el correo, otra para las llamadas y otra para escribir en el portal, para que una organización pueda dotarlas de personal de forma distinta, con una sola llave para enviar archivos que se aplica a todos los canales. [[#permissions #telephony]]
- Las llaves del acceso del cliente a su propio caso cubren los enlaces de compartición, los canales del portal, los restablecimientos de inicio de sesión y la revocación de enlaces de respuesta. [[#permissions #portal]]
- Las llaves de los registros de clientes cubren ver clientes, ver sus datos personales, editar datos de contacto, editar alias, fusionar y eliminar. [[#permissions #client-data]]
- Las llaves de la base de conocimiento cubren leer, escribir, gestionar categorías y eliminar artículos. [[#permissions]]
- Las llaves de las colas separan la gestión de colas, la membresía de colas y las notificaciones de colas. [[#permissions]]
- Las llaves de ingreso separan el diseño de formularios de la consulta de las respuestas enviadas. [[#permissions]]
- Las llaves para administrar la organización cubren los roles, las personas usuarias, la identidad, el enrutamiento de canales, la retención, los tipos de nota, las claves de cifrado, la infraestructura, los saludos, las respuestas automáticas, la cuarentena de correos de voz, la escalada, los ajustes preestablecidos, los reportes y el registro de auditoría. [[#permissions]]
Los valores predeterminados están elegidos para que encender el sistema no cambie el día a nadie. Cada llave queda en el nivel que controlaba esa misma operación antes de que existieran las llaves, y por eso las llaves de contacto con el cliente empiezan en el nivel de Voluntario aunque una organización pudiera preferir otra cosa. Contactar a un cliente antes solo requería una sesión, así que empezar esas llaves en cualquier nivel más alto habría significado una instalación nueva donde nadie puede responder a nadie. Una organización que quiere un rol de trastienda retiene esas llaves deliberadamente. [[#permissions]]
Cuidar las claves de cifrado, gestionar roles y gestionar infraestructura se quedan con Administrador por más que alguien configure otra cosa, para que ningún rol pueda concederse permisos a sí mismo. Ese bloqueo se aplica cuando se escribe una excepción y otra vez cuando se leen los permisos, así que una fila insertada directamente en la base de datos que conceda una de las tres a otro rol no tiene efecto. [[#permissions #failure-states]]
Los permisos gobiernan acciones, no la visibilidad del material ya entregado. Quien tiene la llave de las respuestas de ingreso recibe una envoltura de clave por cada envío en el momento en que llega, así que quitarle la llave detiene las envolturas futuras y deja intactas las ya emitidas, y la matriz marca esa fila como una capacidad y no como un interruptor de visibilidad precisamente por eso. Una llave está declarada para una operación que aún no existe, así que ver "Ver mis turnos" en la lista no significa que haya una función detrás. [[#permissions #failure-states #encryption]]
**Cómo se calcula un conjunto efectivo.** Cada rol tiene un conjunto predeterminado en la configuración del lado del servidor, y las excepciones por organización viven en \`role_permission_overrides\`, una fila dispersa por rol y permiso con una marca de activación. Devolver un permiso a su valor predeterminado elimina la fila en lugar de almacenarla. La combinación corre entonces en cuatro pasos. [[#permissions #server-holds]]
1. Se parte del conjunto predeterminado del rol. [[#permissions]]
2. Se aplica cada fila de excepción como una adición o una retirada. [[#permissions]]
3. Se ignoran las filas de excepción que nombran un permiso desconocido, para que los nombres retirados o futuros no rompan la combinación. [[#permissions]]
4. Se imponen los bloqueos añadiendo por fuerza las tres llaves bloqueadas a Administrador y retirándolas por fuerza de todos los demás roles. [[#permissions #failure-states]]
Los identificadores de rol en la base de datos son cadenas opacas a propósito y no nombres legibles, para que un atacante que solo tenga la base de datos no pueda inferir de ellos la estructura de la organización, y el nombre legible vive en el servidor hasta que la configuración de administración cifrada lo lleve. [[#permissions #server-holds]]
**La caché y su restricción de despliegue.** Los conjuntos efectivos se guardan en caché por organización en la memoria del proceso, se rellenan para los tres roles en una sola consulta cuando fallan, y se invalidan con cada mutación de excepciones para que un permiso revocado deje de funcionar en la siguiente solicitud y no tras un tiempo de espera. Esa caché es local al proceso, lo que significa que un despliegue con varias instancias dejaría que una instancia siguiera sirviendo un conjunto revocado después de que otra instancia invalidara su propia copia. El servidor se niega a arrancar con varias instancias habilitadas precisamente por eso, y una caché en un almacén compartido es el requisito previo para levantar la restricción. [[#permissions #failure-states]]
**La membresía de cola es una concesión aparte.** La membresía en una cola concede acceso de lectura a todos los casos de esa cola, y está gobernada por su propia llave en lugar de ir montada sobre la gestión de colas o sobre el enrutamiento de notificaciones. Mantener esas tres cosas separadas es lo que mantiene la concesión de acceso visible como una concesión. El enrutamiento de notificaciones determina a quién se avisa y no concede ningún acceso por sí mismo. [[#permissions #trust-boundary]]
**Indicaciones para quien contribuye.** Los nombres, la aplicación de las reglas y las superficies están en cuatro lugares. [[#permissions]]
- \`packages/shared/src/roles.ts\` contiene la enumeración \`Permission\` y su agrupación, y es de solo añadir después del despliegue porque renombrar un miembro deja huérfana toda fila de excepción que lo nombre. [[#permissions]]
- \`packages/server/src/auth/roles.ts\` contiene los valores predeterminados de los roles, el conjunto bloqueado, la función de combinación, la caché, el repositorio de excepciones y las consultas de quién tiene un permiso que usan el ingreso y la selección de destinatarios de notificaciones, con la comprobación en tiempo de solicitud en \`role-middleware.ts\`. [[#permissions]]
- \`packages/server/src/db/migrations/tenant/086_create_role_permission_overrides.ts\` define la tabla de excepciones. [[#permissions #server-holds]]
- \`packages/client/src/lib/components/admin/RolePermissionsSection.svelte\` es la superficie de administración, y \`packages/client/src/lib/shell/section-registry.ts\` asigna secciones a permisos para la comprobación del lado del cliente. [[#permissions]]`)
};

const en_xa2_demo_narrative_deepdive_permission_system_body = /** @type {(inputs: Demo_Narrative_Deepdive_Permission_System_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èvèry òrgànìzàtìòn dìvìdès wòrk dìffèrèntly, sò CÀRÈ-Y shìps thrèè ròlès wìth sènsìblè dèfàùlts ànd lèts thè òrgànìzàtìòn mòvè àlmòst èvèry ìndìvìdùàl àbìlìty bètwèèn thèm. Thè thrèè ròlès àrè Vòlùntèèr, Mànàgèr ànd Àdmìn. Whàt èàch ònè càn àctùàlly dò ìs à sèt òf fìfty kèys àcròss èìght càpàbìlìty gròùps, ànd àn àdmìnìstràtòr càn hànd à kèy tò à ròlè thàt dìd nòt hàvè ìt òr tàkè ònè àwày fròm à ròlè thàt dìd. [[#pèrmìssìòns]]
Thè kèys àrè gròùpèd by thè kìnd òf wòrk thèy gòvèrn ràthèr thàn by sènìòrìty. [[#pèrmìssìòns]]
- Kèys fòr thè càsè rècòrd sèpàràtè rèàdìng à càsè fròm àctìng òn ònè, sò vìèwìng, òpènìng, èdìtìng thè sùmmàry, wrìtìng nòtès, chàngìng stàtùs, lìnkìng, clàìmìng, àssìgnìng, dèlètìng sòmèònè èlsè's nòtè ànd dòwnlòàdìng mèdìà èàch mòvè òn thèìr òwn. [[#pèrmìssìòns #clìènt-dàtà]]
- Kèys fòr rèàchìng à clìènt àrè splìt by chànnèl, ònè èàch fòr tèxtìng, èmàìl, càllìng ànd mèssàgìng ìn thè pòrtàl, sò àn òrgànìzàtìòn càn stàff thèm dìffèrèntly, wìth ònè kèy fòr sèndìng fìlès thàt àpplìès àcròss èvèry chànnèl. [[#pèrmìssìòns #tèlèphòny]]
- Kèys fòr thè clìènt's òwn àccèss tò thèìr càsè còvèr shàrè lìnks, pòrtàl chànnèls, lògìn rèsèts ànd rèvòkìng rèply lìnks. [[#pèrmìssìòns #pòrtàl]]
- Kèys fòr clìènt rècòrds còvèr vìèwìng clìènts, vìèwìng thèìr pèrsònàl ìnfòrmàtìòn, èdìtìng còntàct dètàìls, èdìtìng àlìàsès, mèrgìng ànd dèlètìng. [[#pèrmìssìòns #clìènt-dàtà]]
- Kèys fòr thè knòwlèdgè bàsè còvèr rèàdìng, wrìtìng, mànàgìng càtègòrìès ànd dèlètìng àrtìclès. [[#pèrmìssìòns]]
- Kèys fòr qùèùès sèpàràtè qùèùè mànàgèmènt, qùèùè mèmbèrshìp ànd qùèùè nòtìfìcàtìòns. [[#pèrmìssìòns]]
- Kèys fòr ìntàkè sèpàràtè dèsìgnìng fòrms fròm vìèwìng sùbmìttèd rèspònsès. [[#pèrmìssìòns]]
- Kèys fòr rùnnìng thè òrgànìzàtìòn còvèr ròlès, ùsèrs, ìdèntìty, chànnèl ròùtìng, rètèntìòn, nòtè typès, èncryptìòn kèys, ìnfràstrùctùrè, grèètìngs, àùtòmàtìc rèplìès, vòìcèmàìl qùàràntìnè, èscàlàtìòn, prèsèts, rèpòrts ànd thè àùdìt lòg. [[#pèrmìssìòns]]
Dèfàùlts àrè chòsèn sò thàt tùrnìng thè systèm òn chàngès nòbòdy's dày. Èàch kèy sìts àt thè lèvèl thàt gàtèd thè sàmè òpèràtìòn bèfòrè thè kèys èxìstèd, whìch ìs why thè clìènt-còntàct kèys stàrt àt Vòlùntèèr lèvèl èvèn thòùgh àn òrgànìzàtìòn mìght prèfèr òthèrwìsè. Rèàchìng à clìènt ùsèd tò rèqùìrè ònly à sèssìòn, sò stàrtìng thòsè kèys ànywhèrè hìghèr wòùld hàvè mèànt à frèsh ìnstàll whèrè nòbòdy càn ànswèr ànyònè. Àn òrgànìzàtìòn thàt wànts à bàck-òffìcè ròlè wìthhòlds thòsè kèys dèlìbèràtèly. [[#pèrmìssìòns]]
Mànàgìng èncryptìòn kèys, mànàgìng ròlès, ànd mànàgìng ìnfràstrùctùrè stày wìth Àdmìn whàtèvèr ànyònè cònfìgùrès, sò thàt nò ròlè càn èvèr grànt ìtsèlf pèrmìssìòns. Thàt lòck ìs ènfòrcèd whèn àn òvèrrìdè ìs wrìttèn ànd àgàìn whèn pèrmìssìòns àrè rèàd, sò à ròw ìnsèrtèd dìrèctly ìntò thè dàtàbàsè gràntìng ònè òf thè thrèè tò ànòthèr ròlè hàs nò èffèct. [[#pèrmìssìòns #fàìlùrè-stàtès]]
Pèrmìssìòns gòvèrn àctìòns, nòt vìsìbìlìty òf àlrèàdy-rèlèàsèd màtèrìàl. Sòmèònè hòldìng thè ìntàkè rèspònsès kèy rècèìvès à kèy wràp fòr èàch sùbmìssìòn àt thè mòmènt ìt àrrìvès, sò tàkìng thè kèy àwày stòps fùtùrè wràps ànd lèàvès thè ònès àlrèàdy ìssùèd ìntàct, ànd thè màtrìx màrks thàt ròw às à càpàbìlìty ràthèr thàn à vìèw tògglè fòr èxàctly thàt rèàsòn. Ònè kèy ìs dèclàrèd fòr àn òpèràtìòn thàt dòès nòt èxìst yèt, sò sèèìng "Vìèw òwn shìfts" ìn thè lìst dòès nòt mèàn à fèàtùrè ìs bèhìnd ìt. [[#pèrmìssìòns #fàìlùrè-stàtès #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw àn èffèctìvè sèt ìs còmpùtèd. ••••••••••** Èàch ròlè hàs à dèfàùlt sèt ìn sèrvèr-sìdè cònfìgùràtìòn, ànd pèr-òrgànìzàtìòn òvèrrìdès lìvè ìn \`ròlè_pèrmìssìòn_òvèrrìdès\`, ònè spàrsè ròw pèr ròlè ànd pèrmìssìòn wìth àn ènàblèd flàg. Sèttìng à pèrmìssìòn bàck tò ìts dèfàùlt dèlètès thè ròw ràthèr thàn stòrìng ìt. Thè mèrgè thèn rùns ìn fòùr stèps. [[#pèrmìssìòns #sèrvèr-hòlds]]
1. Stàrt fròm thè ròlè's dèfàùlt sèt. [[#pèrmìssìòns]]
2. Àpply èàch òvèrrìdè ròw às àn àdd òr à rèmòvè. [[#pèrmìssìòns]]
3. Ìgnòrè òvèrrìdè ròws nàmìng àn ùnknòwn pèrmìssìòn, sò rèmòvèd òr fùtùrè nàmès dò nòt brèàk thè mèrgè. [[#pèrmìssìòns]]
4. Ènfòrcè thè lòcks by fòrcè-àddìng àll thrèè lòckèd kèys tò Àdmìn ànd fòrcè-rèmòvìng thèm fròm èvèry òthèr ròlè. [[#pèrmìssìòns #fàìlùrè-stàtès]]
Ròlè ìds ìn thè dàtàbàsè àrè dèlìbèràtèly òpàqùè strìngs ràthèr thàn rèàdàblè nàmès, sò à dàtàbàsè-ònly àttàckèr cànnòt ìnfèr thè òrgànìzàtìòn's strùctùrè fròm thèm, ànd thè hùmàn-rèàdàblè nàmè lìvès sèrvèr-sìdè ùntìl èncryptèd àdmìn cònfìgùràtìòn càrrìès ìt. [[#pèrmìssìòns #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Càchìng ànd ìts dèplòymènt cònstràìnt. ••••••••••••** Èffèctìvè sèts àrè càchèd pèr òrgànìzàtìòn ìn pròcèss mèmòry, fìllèd fòr àll thrèè ròlès ìn ònè qùèry òn à mìss, ànd ìnvàlìdàtèd by èvèry òvèrrìdè mùtàtìòn sò à rèvòkèd pèrmìssìòn stòps wòrkìng òn thè nèxt rèqùèst ràthèr thàn àftèr à tìmèòùt. Thàt càchè ìs pròcèss-lòcàl, whìch mèàns à mùltì-ìnstàncè dèplòymènt wòùld lèt ònè ìnstàncè kèèp sèrvìng à rèvòkèd sèt àftèr ànòthèr ìnstàncè ìnvàlìdàtèd ìts òwn còpy. Thè sèrvèr rèfùsès tò bòòt wìth mùltìplè ìnstàncès ènàblèd fòr èxàctly thàt rèàsòn, ànd à shàrèd-stòrè càchè ìs thè prèrèqùìsìtè fòr lìftìng thè rèstrìctìòn. [[#pèrmìssìòns #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Qùèùè mèmbèrshìp ìs à sèpàràtè grànt. ••••••••••••** Mèmbèrshìp ìn à qùèùè grànts rèàd àccèss tò èvèry càsè ìn thàt qùèùè, ànd ìt ìs gòvèrnèd by ìts òwn kèy ràthèr thàn rìdìng òn qùèùè mànàgèmènt òr òn nòtìfìcàtìòn ròùtìng. Kèèpìng thòsè thrèè àpàrt ìs whàt kèèps thè àccèss grànt vìsìblè às à grànt. Nòtìfìcàtìòn ròùtìng dètèrmìnès whò gèts pìngèd ànd grànts nò àccèss òn ìts òwn. [[#pèrmìssìòns #trùst-bòùndàry]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Còntrìbùtòr pòìntèrs. •••••••** Thè nàmès, thè ènfòrcèmènt ànd thè sùrfàcès sìt ìn fòùr plàcès. [[#pèrmìssìòns]]
- \`pàckàgès/shàrèd/src/ròlès.ts\` hòlds thè \`Pèrmìssìòn\` ènùm ànd ìts gròùpìng, ànd ìt ìs àppènd-ònly àftèr dèplòymènt bècàùsè rènàmìng à mèmbèr òrphàns èvèry òvèrrìdè ròw thàt nàmès ìt. [[#pèrmìssìòns]]
- \`pàckàgès/sèrvèr/src/àùth/ròlès.ts\` hòlds ròlè dèfàùlts, thè lòck sèt, thè mèrgè fùnctìòn, thè càchè, thè òvèrrìdè rèpòsìtòry ànd thè pèrmìssìòn-hòldèr qùèrìès thàt ìntàkè ànd nòtìfìcàtìòn tàrgètìng ùsè, wìth rèqùèst-tìmè gàtìng ìn \`ròlè-mìddlèwàrè.ts\`. [[#pèrmìssìòns]]
- \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/086_crèàtè_ròlè_pèrmìssìòn_òvèrrìdès.ts\` dèfìnès thè òvèrrìdè tàblè. [[#pèrmìssìòns #sèrvèr-hòlds]]
- \`pàckàgès/clìènt/src/lìb/còmpònènts/àdmìn/RòlèPèrmìssìònsSèctìòn.svèltè\` ìs thè àdmìnìstràtìvè sùrfàcè, ànd \`pàckàgès/clìènt/src/lìb/shèll/sèctìòn-règìstry.ts\` màps sèctìòns tò pèrmìssìòns fòr clìènt-sìdè gàtìng. [[#pèrmìssìòns]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Every organization divides work differently, so CARE-Y ships three roles with sensible defaults and lets the organization move almost every individual abilit..." |
*
* @param {Demo_Narrative_Deepdive_Permission_System_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_permission_system_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Permission_System_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Permission_System_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_permission_system_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_permission_system_body(inputs)
	return en_demo_narrative_deepdive_permission_system_body(inputs)
});