/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Funds_BodyInputs */

const en_demo_narrative_admin_funds_body = /** @type {(inputs: Demo_Narrative_Admin_Funds_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The Funds section on the Organization page lists every fund the organization has created, active and deactivated. Tapping a row opens its name and currency for editing. The section and its editor require the Manage funds permission, held by Admin by default, and Manage funds includes View funds. [[#permissions #client-data]]
**Creating a fund.** A new fund starts at zero. The browser seals the fund's name and currency with the organization key before sending the request. The server stores the ciphertext and cannot read either value. [[#encryption #server-holds]]
**Editing a fund.** The name can be changed at any time. The currency is locked once the fund has a ledger entry, because changing it would relabel every past amount. Amounts follow the currency's own ISO 4217 decimal places. [[#client-data]]
**Deactivation.** Deactivating a fund clears every queue mapping that pointed to it and removes the fund from the disbursement sheet's picker. Cases in those queues lose their fund line and their disbursement action until a different fund is mapped. Ledger entries already recorded against the fund survive. The [fund ledger](#admin-org/fund-ledger) still shows deactivated funds and their history. Deactivation is reversible. [[#failure-states #metadata]]
**Recording an adjustment.** An adjustment adds or removes money outside the disbursement flow. Each adjustment writes one ledger entry and the fund's resealed balance, with no case note. Adjustments serve as initial deposits, out-of-case corrections, and reconciliation entries. [[#client-data]]
**Entry notifications.** A toggle on the section controls whether every fund entry triggers a notification to each holder of Manage funds other than the person who recorded it. The notification is a ticketless event that names no case, delivered through every channel the recipient's preferences allow. That toggle is stored as a plaintext boolean in the organization's configuration, so the server sees whether the organization has notifications on. [Notification preferences](#settings/notifications) covers per-user channel choices. [[#server-holds #metadata]]
**What does the server store about a fund?** The name and currency are organization-key ciphertext. The running balance is a separate sealed column. The server holds the active flag, the sort position, the creation and modification timestamps, the balance version counter, and the key generation, all in plaintext. Deactivated fund rows stay in the database permanently. [What the server holds about money](#deep-dive/fund-records) covers the full storage picture. [[#server-holds #encryption #metadata]]
**The section and its service.** \`FundsSection.svelte\` in \`packages/client/src/lib/components/admin/\` renders the fund list and the create, edit, and adjustment sheets. The notification toggle reads and writes \`notify_fund_managers\` on the organization's configuration row through \`org-config-service.ts\`. Balance writes use a compare-and-set on the version counter, and a stale version triggers a refetch-and-retry before surfacing an error. [[#client-data #permissions]]`)
};

const es_demo_narrative_admin_funds_body = /** @type {(inputs: Demo_Narrative_Admin_Funds_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La sección Fondos en la página Organización lista todos los fondos que la organización ha creado, activos y desactivados. Al pulsar una fila se abren su nombre y moneda para edición. La sección y su editor requieren el permiso Gestionar fondos, asignado a Admin por defecto, y Gestionar fondos incluye Ver fondos. [[#permissions #client-data]]
**Crear un fondo.** Un fondo nuevo empieza en cero. El navegador sella el nombre y la moneda del fondo con la clave de organización antes de enviar la solicitud. El servidor almacena el texto cifrado y no puede leer ninguno de los dos valores. [[#encryption #server-holds]]
**Editar un fondo.** El nombre se puede cambiar en cualquier momento. La moneda queda bloqueada cuando el fondo tiene un asiento en el libro mayor, porque cambiarla reetiquetaría todos los importes anteriores. Los importes siguen las posiciones decimales propias de la moneda según ISO 4217. [[#client-data]]
**Desactivación.** Desactivar un fondo elimina todas las asignaciones de cola que apuntaban a él y retira el fondo del selector de desembolsos. Los casos en esas colas pierden su línea de fondo y su acción de desembolso hasta que se asigne otro fondo. Los asientos ya registrados contra el fondo se conservan. El [libro mayor de fondos](#admin-org/fund-ledger) sigue mostrando los fondos desactivados y su historial. La desactivación es reversible. [[#failure-states #metadata]]
**Registrar un ajuste.** Un ajuste añade o retira dinero fuera del flujo de desembolsos. Cada ajuste escribe un asiento en el libro mayor y el saldo resellado del fondo, sin nota de caso. Los ajustes sirven como depósitos iniciales, correcciones fuera de caso y entradas de conciliación. [[#client-data]]
**Notificaciones de asientos.** Un interruptor en la sección controla si cada asiento de fondo dispara una notificación a cada titular de Gestionar fondos que no sea la persona que lo registró. La notificación es un evento sin caso que no nombra ningún expediente, entregado por cada canal que las preferencias del destinatario permitan. Ese interruptor se almacena como un booleano en texto plano en la configuración de la organización, de modo que el servidor ve si la organización tiene las notificaciones activadas. [Preferencias de notificación](#settings/notifications) trata las opciones de canal por persona. [[#server-holds #metadata]]
**¿Qué almacena el servidor sobre un fondo?** El nombre y la moneda son texto cifrado con la clave de organización. El saldo vigente es una columna sellada aparte. El servidor conserva en texto plano la marca de activo, la posición de orden, las marcas de tiempo de creación y modificación, el contador de versión de saldo y la generación de clave. Las filas de fondos desactivados permanecen en la base de datos de forma permanente. [Lo que el servidor guarda sobre el dinero](#deep-dive/fund-records) trata el panorama completo de almacenamiento. [[#server-holds #encryption #metadata]]
**La sección y su servicio.** \`FundsSection.svelte\` en \`packages/client/src/lib/components/admin/\` renderiza la lista de fondos y las hojas de creación, edición y ajuste. El interruptor de notificaciones lee y escribe \`notify_fund_managers\` en la fila de configuración de la organización a través de \`org-config-service.ts\`. Las escrituras de saldo usan un compare-and-set sobre el contador de versión, y una versión obsoleta dispara una recarga y reintento antes de mostrar un error. [[#client-data #permissions]]`)
};

const en_xa2_demo_narrative_admin_funds_body = /** @type {(inputs: Demo_Narrative_Admin_Funds_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè Fùnds sèctìòn òn thè Òrgànìzàtìòn pàgè lìsts èvèry fùnd thè òrgànìzàtìòn hàs crèàtèd, àctìvè ànd dèàctìvàtèd. Tàppìng à ròw òpèns ìts nàmè ànd cùrrèncy fòr èdìtìng. Thè sèctìòn ànd ìts èdìtòr rèqùìrè thè Mànàgè fùnds pèrmìssìòn, hèld by Àdmìn by dèfàùlt, ànd Mànàgè fùnds ìnclùdès Vìèw fùnds. [[#pèrmìssìòns #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Crèàtìng à fùnd. •••••** À nèw fùnd stàrts àt zèrò. Thè bròwsèr sèàls thè fùnd's nàmè ànd cùrrèncy wìth thè òrgànìzàtìòn kèy bèfòrè sèndìng thè rèqùèst. Thè sèrvèr stòrès thè cìphèrtèxt ànd cànnòt rèàd èìthèr vàlùè. [[#èncryptìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èdìtìng à fùnd. •••••** Thè nàmè càn bè chàngèd àt àny tìmè. Thè cùrrèncy ìs lòckèd òncè thè fùnd hàs à lèdgèr èntry, bècàùsè chàngìng ìt wòùld rèlàbèl èvèry pàst àmòùnt. Àmòùnts fòllòw thè cùrrèncy's òwn ÌSÒ 4217 dècìmàl plàcès. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dèàctìvàtìòn. ••••** Dèàctìvàtìng à fùnd clèàrs èvèry qùèùè màppìng thàt pòìntèd tò ìt ànd rèmòvès thè fùnd fròm thè dìsbùrsèmènt shèèt's pìckèr. Càsès ìn thòsè qùèùès lòsè thèìr fùnd lìnè ànd thèìr dìsbùrsèmènt àctìòn ùntìl à dìffèrènt fùnd ìs màppèd. Lèdgèr èntrìès àlrèàdy rècòrdèd àgàìnst thè fùnd sùrvìvè. Thè [fùnd lèdgèr](#àdmìn-òrg/fùnd-lèdgèr) stìll shòws dèàctìvàtèd fùnds ànd thèìr hìstòry. Dèàctìvàtìòn ìs rèvèrsìblè. [[#fàìlùrè-stàtès #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rècòrdìng àn àdjùstmènt. ••••••••** Àn àdjùstmènt àdds òr rèmòvès mònèy òùtsìdè thè dìsbùrsèmènt flòw. Èàch àdjùstmènt wrìtès ònè lèdgèr èntry ànd thè fùnd's rèsèàlèd bàlàncè, wìth nò càsè nòtè. Àdjùstmènts sèrvè às ìnìtìàl dèpòsìts, òùt-òf-càsè còrrèctìòns, ànd rècòncìlìàtìòn èntrìès. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èntry nòtìfìcàtìòns. ••••••** À tògglè òn thè sèctìòn còntròls whèthèr èvèry fùnd èntry trìggèrs à nòtìfìcàtìòn tò èàch hòldèr òf Mànàgè fùnds òthèr thàn thè pèrsòn whò rècòrdèd ìt. Thè nòtìfìcàtìòn ìs à tìckètlèss èvènt thàt nàmès nò càsè, dèlìvèrèd thròùgh èvèry chànnèl thè rècìpìènt's prèfèrèncès àllòw. Thàt tògglè ìs stòrèd às à plàìntèxt bòòlèàn ìn thè òrgànìzàtìòn's cònfìgùràtìòn, sò thè sèrvèr sèès whèthèr thè òrgànìzàtìòn hàs nòtìfìcàtìòns òn. [Nòtìfìcàtìòn prèfèrèncès](#sèttìngs/nòtìfìcàtìòns) còvèrs pèr-ùsèr chànnèl chòìcès. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè àbòùt à fùnd? ••••••••••••** Thè nàmè ànd cùrrèncy àrè òrgànìzàtìòn-kèy cìphèrtèxt. Thè rùnnìng bàlàncè ìs à sèpàràtè sèàlèd còlùmn. Thè sèrvèr hòlds thè àctìvè flàg, thè sòrt pòsìtìòn, thè crèàtìòn ànd mòdìfìcàtìòn tìmèstàmps, thè bàlàncè vèrsìòn còùntèr, ànd thè kèy gènèràtìòn, àll ìn plàìntèxt. Dèàctìvàtèd fùnd ròws stày ìn thè dàtàbàsè pèrmànèntly. [Whàt thè sèrvèr hòlds àbòùt mònèy](#dèèp-dìvè/fùnd-rècòrds) còvèrs thè fùll stòràgè pìctùrè. [[#sèrvèr-hòlds #èncryptìòn #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè sèctìòn ànd ìts sèrvìcè. •••••••••** \`FùndsSèctìòn.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/àdmìn/\` rèndèrs thè fùnd lìst ànd thè crèàtè, èdìt, ànd àdjùstmènt shèèts. Thè nòtìfìcàtìòn tògglè rèàds ànd wrìtès \`nòtìfy_fùnd_mànàgèrs\` òn thè òrgànìzàtìòn's cònfìgùràtìòn ròw thròùgh \`òrg-cònfìg-sèrvìcè.ts\`. Bàlàncè wrìtès ùsè à còmpàrè-ànd-sèt òn thè vèrsìòn còùntèr, ànd à stàlè vèrsìòn trìggèrs à rèfètch-ànd-rètry bèfòrè sùrfàcìng àn èrròr. [[#clìènt-dàtà #pèrmìssìòns]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The Funds section on the Organization page lists every fund the organization has created, active and deactivated. Tapping a row opens its name and currency f..." |
*
* @param {Demo_Narrative_Admin_Funds_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_funds_body = /** @type {((inputs?: Demo_Narrative_Admin_Funds_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Funds_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_funds_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_funds_body(inputs)
	return en_demo_narrative_admin_funds_body(inputs)
});