/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Intake_Forms_BodyInputs */

const en_demo_narrative_admin_intake_forms_body = /** @type {(inputs: Demo_Narrative_Admin_Intake_Forms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The intake forms list holds every form an organization has built, and one switch beside it takes web intake off for the whole organization at once. [[#portal]]
**Saving a form does not publish it.** A form is created unpublished and stays unreachable until it is activated, activation is its own operation rather than a side effect of saving, and editing a live form therefore cannot take it off the public site by accident. Deactivating stops new submissions and leaves the form and every answer already given to it in place. [The form builder](#admin-forms/builder) covers what a save writes. [[#failure-states #portal]]
**What answers the public address when nothing is published.** With web intake on and no active form of the organization's own marked as the default, a built-in form of two fields, a name and a message, stands in so the public address always answers, in whichever of the two languages the visitor's browser asks for. That stand-in is switched off on its own, separately from the organization-wide switch. [The public intake form](#client-intake/form) covers what a visitor is asked for. [[#portal #client-data]]
**What the list row discloses and what it does not.** A form's internal name, its public slug, whether it is active, whether it is the default and which queue it feeds are plaintext columns. Everything a visitor reads, meaning the field labels, the field configuration and the form's own description and messages, is encrypted. A database dump therefore shows how many forms an organization runs, what it calls them internally, which public addresses they answer on and how many fields each one holds, and none of the wording of any question. [The trust boundary](#deep-dive/the-trust-boundary) covers the rest of that picture. [[#server-holds #metadata]]
**The key that opens a definition is not the key that opens an answer.** Form definitions are encrypted under a key anyone can derive from the organization's public key, which is what lets an anonymous visitor's browser render a form without an account while the stored bytes stay opaque. Answers are encrypted to a key that exists per case and is wrapped to individual accounts, so building and publishing a form gives no access to what anyone submitted through it. [Form responses](#admin-responses/responses) covers reading the answers. [[#encryption #keys]]
**Duplicating and deleting.** Duplicating loads a form, mints fresh field and option keys, suffixes the name and clears the slug, so the copy cannot collide with the original on a public address and shares none of its key material. Deleting is refused once any response exists, so the record a form produced cannot be removed by removing the form. [[#failure-states #encryption]]
**Two permissions that do not imply each other.** Manage intake forms is a Manager default and View intake responses is an Admin default, and neither carries the other, so an account that builds and publishes a form reads nothing submitted to it unless the organization grants the second permission too. [The permission system](#deep-dive/the-permission-system) covers moving either one. [[#permissions]]
**The forms table and the audit trail.** \`packages/server/src/portal/intake-form-service.ts\` holds the whole-form save, the slug uniqueness check, the atomic default swap and the single writer of the active flag, and \`packages/server/src/routes/intake-forms.ts\` gates every procedure on one of the two permissions. Saving, deleting and both of the switches write audit entries; activating and deactivating a form currently writes none. [[#server-holds #failure-states]]`)
};

const es_demo_narrative_admin_intake_forms_body = /** @type {(inputs: Demo_Narrative_Admin_Intake_Forms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La lista de formularios de admisión contiene todos los formularios que ha construido una organización, y un interruptor a su lado desactiva la admisión web de toda la organización de una vez. [[#portal]]
**Guardar un formulario no lo publica.** Un formulario se crea sin publicar y no es accesible hasta que se activa, la activación es una operación propia y no un efecto secundario de guardar, y por eso editar un formulario en uso no puede retirarlo del sitio público por descuido. Desactivarlo detiene los envíos nuevos y deja en su sitio el formulario y todas las respuestas que ya recibió. [El constructor de formularios](#admin-forms/builder) trata lo que escribe un guardado. [[#failure-states #portal]]
**Qué responde en la dirección pública cuando no hay nada publicado.** Con la admisión web activada y sin ningún formulario propio activo marcado como predeterminado, un formulario integrado de dos campos, un nombre y un mensaje, hace de suplente para que la dirección pública responda siempre, en el idioma que pida el navegador del visitante de los dos disponibles. Ese suplente se desactiva por su cuenta, aparte del interruptor de toda la organización. [El formulario público de admisión](#client-intake/form) trata lo que se le pide a un visitante. [[#portal #client-data]]
**Qué revela la fila de la lista y qué no.** El nombre interno de un formulario, su identificador público, si está activo, si es el predeterminado y a qué cola alimenta son columnas en texto plano. Todo lo que lee un visitante, es decir las etiquetas de los campos, su configuración y la descripción y los mensajes del propio formulario, va cifrado. Un volcado de la base de datos muestra entonces cuántos formularios tiene una organización, cómo los llama internamente, en qué direcciones públicas responden y cuántos campos tiene cada uno, y ninguna palabra de ninguna pregunta. [La frontera de confianza](#deep-dive/the-trust-boundary) trata el resto de ese panorama. [[#server-holds #metadata]]
**La clave que abre una definición no es la clave que abre una respuesta.** Las definiciones de formulario se cifran con una clave que cualquiera puede derivar de la clave pública de la organización, que es lo que permite que el navegador de un visitante anónimo dibuje un formulario sin cuenta mientras los bytes almacenados siguen siendo opacos. Las respuestas se cifran con una clave que existe por caso y se envuelve para cuentas concretas, así que construir y publicar un formulario no da ningún acceso a lo que alguien envió por él. [Respuestas de formularios](#admin-responses/responses) trata la lectura de las respuestas. [[#encryption #keys]]
**Duplicar y borrar.** Duplicar carga un formulario, acuña claves nuevas de campo y de opción, añade un sufijo al nombre y vacía el identificador público, de modo que la copia no puede chocar con el original en una dirección pública ni comparte su material de claves. Borrar se rechaza en cuanto existe una respuesta, así que el registro que produjo un formulario no se puede eliminar eliminando el formulario. [[#failure-states #encryption]]
**Dos permisos que no se implican.** Gestionar formularios de admisión corresponde por defecto al nivel de gestión y ver respuestas de admisión corresponde por defecto a Admin, y ninguno arrastra al otro, así que una cuenta que construye y publica un formulario no lee nada de lo enviado a él salvo que la organización conceda también el segundo permiso. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se traslada cualquiera de los dos. [[#permissions]]
**La tabla de formularios y el rastro de auditoría.** \`packages/server/src/portal/intake-form-service.ts\` contiene el guardado del formulario completo, la comprobación de unicidad del identificador, el cambio atómico de predeterminado y el único sitio que escribe la marca de activo, y \`packages/server/src/routes/intake-forms.ts\` protege cada procedimiento con uno de los dos permisos. Guardar, borrar y los dos interruptores escriben entradas de auditoría; activar y desactivar un formulario hoy no escribe ninguna. [[#server-holds #failure-states]]`)
};

const en_xa2_demo_narrative_admin_intake_forms_body = /** @type {(inputs: Demo_Narrative_Admin_Intake_Forms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ìntàkè fòrms lìst hòlds èvèry fòrm àn òrgànìzàtìòn hàs bùìlt, ànd ònè swìtch bèsìdè ìt tàkès wèb ìntàkè òff fòr thè whòlè òrgànìzàtìòn àt òncè. [[#pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••**Sàvìng à fòrm dòès nòt pùblìsh ìt. •••••••••••** À fòrm ìs crèàtèd ùnpùblìshèd ànd stàys ùnrèàchàblè ùntìl ìt ìs àctìvàtèd, àctìvàtìòn ìs ìts òwn òpèràtìòn ràthèr thàn à sìdè èffèct òf sàvìng, ànd èdìtìng à lìvè fòrm thèrèfòrè cànnòt tàkè ìt òff thè pùblìc sìtè by àccìdènt. Dèàctìvàtìng stòps nèw sùbmìssìòns ànd lèàvès thè fòrm ànd èvèry ànswèr àlrèàdy gìvèn tò ìt ìn plàcè. [Thè fòrm bùìldèr](#àdmìn-fòrms/bùìldèr) còvèrs whàt à sàvè wrìtès. [[#fàìlùrè-stàtès #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt ànswèrs thè pùblìc àddrèss whèn nòthìng ìs pùblìshèd. ••••••••••••••••••** Wìth wèb ìntàkè òn ànd nò àctìvè fòrm òf thè òrgànìzàtìòn's òwn màrkèd às thè dèfàùlt, à bùìlt-ìn fòrm òf twò fìèlds, à nàmè ànd à mèssàgè, stànds ìn sò thè pùblìc àddrèss àlwàys ànswèrs, ìn whìchèvèr òf thè twò làngùàgès thè vìsìtòr's bròwsèr àsks fòr. Thàt stànd-ìn ìs swìtchèd òff òn ìts òwn, sèpàràtèly fròm thè òrgànìzàtìòn-wìdè swìtch. [Thè pùblìc ìntàkè fòrm](#clìènt-ìntàkè/fòrm) còvèrs whàt à vìsìtòr ìs àskèd fòr. [[#pòrtàl #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè lìst ròw dìsclòsès ànd whàt ìt dòès nòt. •••••••••••••••** À fòrm's ìntèrnàl nàmè, ìts pùblìc slùg, whèthèr ìt ìs àctìvè, whèthèr ìt ìs thè dèfàùlt ànd whìch qùèùè ìt fèèds àrè plàìntèxt còlùmns. Èvèrythìng à vìsìtòr rèàds, mèànìng thè fìèld làbèls, thè fìèld cònfìgùràtìòn ànd thè fòrm's òwn dèscrìptìòn ànd mèssàgès, ìs èncryptèd. À dàtàbàsè dùmp thèrèfòrè shòws hòw màny fòrms àn òrgànìzàtìòn rùns, whàt ìt càlls thèm ìntèrnàlly, whìch pùblìc àddrèssès thèy ànswèr òn ànd hòw màny fìèlds èàch ònè hòlds, ànd nònè òf thè wòrdìng òf àny qùèstìòn. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè rèst òf thàt pìctùrè. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè kèy thàt òpèns à dèfìnìtìòn ìs nòt thè kèy thàt òpèns àn ànswèr. •••••••••••••••••••••** Fòrm dèfìnìtìòns àrè èncryptèd ùndèr à kèy ànyònè càn dèrìvè fròm thè òrgànìzàtìòn's pùblìc kèy, whìch ìs whàt lèts àn ànònymòùs vìsìtòr's bròwsèr rèndèr à fòrm wìthòùt àn àccòùnt whìlè thè stòrèd bytès stày òpàqùè. Ànswèrs àrè èncryptèd tò à kèy thàt èxìsts pèr càsè ànd ìs wràppèd tò ìndìvìdùàl àccòùnts, sò bùìldìng ànd pùblìshìng à fòrm gìvès nò àccèss tò whàt ànyònè sùbmìttèd thròùgh ìt. [Fòrm rèspònsès](#àdmìn-rèspònsès/rèspònsès) còvèrs rèàdìng thè ànswèrs. [[#èncryptìòn #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dùplìcàtìng ànd dèlètìng. ••••••••** Dùplìcàtìng lòàds à fòrm, mìnts frèsh fìèld ànd òptìòn kèys, sùffìxès thè nàmè ànd clèàrs thè slùg, sò thè còpy cànnòt còllìdè wìth thè òrìgìnàl òn à pùblìc àddrèss ànd shàrès nònè òf ìts kèy màtèrìàl. Dèlètìng ìs rèfùsèd òncè àny rèspònsè èxìsts, sò thè rècòrd à fòrm pròdùcèd cànnòt bè rèmòvèd by rèmòvìng thè fòrm. [[#fàìlùrè-stàtès #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Twò pèrmìssìòns thàt dò nòt ìmply èàch òthèr. ••••••••••••••** Mànàgè ìntàkè fòrms ìs à Mànàgèr dèfàùlt ànd Vìèw ìntàkè rèspònsès ìs àn Àdmìn dèfàùlt, ànd nèìthèr càrrìès thè òthèr, sò àn àccòùnt thàt bùìlds ànd pùblìshès à fòrm rèàds nòthìng sùbmìttèd tò ìt ùnlèss thè òrgànìzàtìòn grànts thè sècònd pèrmìssìòn tòò. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs mòvìng èìthèr ònè. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fòrms tàblè ànd thè àùdìt tràìl. •••••••••••** \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-fòrm-sèrvìcè.ts\` hòlds thè whòlè-fòrm sàvè, thè slùg ùnìqùènèss chèck, thè àtòmìc dèfàùlt swàp ànd thè sìnglè wrìtèr òf thè àctìvè flàg, ànd \`pàckàgès/sèrvèr/src/ròùtès/ìntàkè-fòrms.ts\` gàtès èvèry pròcèdùrè òn ònè òf thè twò pèrmìssìòns. Sàvìng, dèlètìng ànd bòth òf thè swìtchès wrìtè àùdìt èntrìès; àctìvàtìng ànd dèàctìvàtìng à fòrm cùrrèntly wrìtès nònè. [[#sèrvèr-hòlds #fàìlùrè-stàtès]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The intake forms list holds every form an organization has built, and one switch beside it takes web intake off for the whole organization at once. [[#portal..." |
*
* @param {Demo_Narrative_Admin_Intake_Forms_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_intake_forms_body = /** @type {((inputs?: Demo_Narrative_Admin_Intake_Forms_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Intake_Forms_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_intake_forms_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_intake_forms_body(inputs)
	return en_demo_narrative_admin_intake_forms_body(inputs)
});