/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Fields_BodyInputs */

const en_demo_narrative_client_intake_fields_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Fields_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A published form carries its own questions, and the page renders whatever field set the organization saved in place of the built-in one. Text, long text, dropdowns, checkboxes, dates, numbers and an availability picker are the shapes a question can take. [[#portal #client-data]]
**How a question is protected.** Field labels, help text and configuration are stored encrypted under a key derived from the organization's public key. Anyone who can read that public key can derive that key, so the encryption keeps a stolen database from listing what a crisis line asks its callers and does not hide the questions from the server that serves them. The answers are encrypted under a key the server has no way to derive. [How encryption works](#deep-dive/how-encryption-works) covers the two key trees. [[#encryption #server-holds]]
**Questions that depend on an earlier answer.** A field can be set to appear only when another field holds a particular value, and a field that stays hidden is left out of the encrypted answer set and out of the case text. The server is never handed an answer to a question the visitor was not shown. [[#client-data #privacy]]
**What a field role tells the server.** Most questions carry no role and produce nothing the server can read. A question given a routing, urgency or escalation role works differently, because the browser resolves the chosen option to a queue, a priority or an alert level and sends that single resolved value in the clear, while the answer text stays encrypted like every other. Someone reading a database dump learns which queue a case went to and not the sentence that sent it there. [Field roles and mappings](#admin-forms/field-config) covers how a role is configured. [[#metadata #server-holds]]
**What the visitor is told about each field.** A field carrying a role that produces a server-visible signal is marked as producing one, a field whose role produces nothing readable is marked as encrypted, and a field with no role carries no mark. The distinction is made where the visitor is deciding what to type rather than in a policy page. [[#privacy #metadata]]
**The field rows and the derived key.** Field definitions live in \`intake_form_fields\` from \`packages/server/src/db/migrations/tenant/089_intake_forms.ts\`, where \`encrypted_label\` and \`encrypted_config\` are ciphertext, \`role\` is a plaintext tag and \`routing_queue_ids\` is a plaintext allow-list the server checks a resolved queue against. The key comes from \`deriveClientBrandingKey\` in \`packages/crypto/src/branding.ts\` and the four encrypt and decrypt functions are in \`packages/crypto/src/intake-form.ts\`, so a second producer cannot restate the associated data by hand. Visibility evaluation and page slicing are \`packages/client/src/routes/(client)/intake/intake-form-logic.ts\`. [[#server-holds #encryption]]`)
};

const es_demo_narrative_client_intake_fields_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Fields_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un formulario publicado lleva sus propias preguntas, y la página muestra el conjunto de campos que la organización haya guardado en lugar del integrado. Texto, texto largo, listas desplegables, casillas, fechas, números y un selector de disponibilidad son las formas que puede tomar una pregunta. [[#portal #client-data]]
**Cómo se protege una pregunta.** Las etiquetas de campo, el texto de ayuda y la configuración se guardan cifrados con una clave derivada de la clave pública de la organización. Cualquiera que pueda leer esa clave pública puede derivarla, así que el cifrado impide que una base de datos robada enumere lo que una línea de crisis pregunta a quien llama y no oculta las preguntas al servidor que las sirve. Las respuestas se cifran con una clave que el servidor no tiene forma de derivar. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata los dos árboles de claves. [[#encryption #server-holds]]
**Preguntas que dependen de una respuesta anterior.** Un campo puede configurarse para aparecer solo cuando otro campo tiene un valor determinado, y un campo que permanece oculto queda fuera del conjunto de respuestas cifradas y fuera del texto del caso. Al servidor nunca se le entrega una respuesta a una pregunta que el visitante no vio. [[#client-data #privacy]]
**Lo que el rol de un campo le dice al servidor.** La mayoría de las preguntas no llevan rol y no producen nada que el servidor pueda leer. Una pregunta con un rol de enrutamiento, urgencia o escalamiento funciona de otro modo, porque el navegador resuelve la opción elegida a una cola, una prioridad o un nivel de alerta y envía ese único valor resuelto en claro, mientras que el texto de la respuesta sigue cifrado como todos los demás. Quien lea un volcado de la base de datos sabe a qué cola fue un caso y no la frase que lo mandó allí. [Roles de campo y asignaciones](#admin-forms/field-config) trata cómo se configura un rol. [[#metadata #server-holds]]
**Lo que se le dice al visitante sobre cada campo.** Un campo con un rol que produce una señal visible para el servidor se marca como tal, un campo cuyo rol no produce nada legible se marca como cifrado, y un campo sin rol no se marca. La distinción se hace donde el visitante decide qué escribir y no en una página de políticas. [[#privacy #metadata]]
**Las filas de campo y la clave derivada.** Las definiciones de campo viven en \`intake_form_fields\`, de \`packages/server/src/db/migrations/tenant/089_intake_forms.ts\`, donde \`encrypted_label\` y \`encrypted_config\` son texto cifrado, \`role\` es una etiqueta en texto plano y \`routing_queue_ids\` es una lista de permitidos en texto plano contra la que el servidor comprueba una cola resuelta. La clave sale de \`deriveClientBrandingKey\`, en \`packages/crypto/src/branding.ts\`, y las cuatro funciones de cifrado y descifrado están en \`packages/crypto/src/intake-form.ts\`, de modo que un segundo productor no puede reescribir a mano los datos asociados. La evaluación de visibilidad y el reparto en páginas están en \`packages/client/src/routes/(client)/intake/intake-form-logic.ts\`. [[#server-holds #encryption]]`)
};

const en_xa2_demo_narrative_client_intake_fields_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Fields_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À pùblìshèd fòrm càrrìès ìts òwn qùèstìòns, ànd thè pàgè rèndèrs whàtèvèr fìèld sèt thè òrgànìzàtìòn sàvèd ìn plàcè òf thè bùìlt-ìn ònè. Tèxt, lòng tèxt, dròpdòwns, chèckbòxès, dàtès, nùmbèrs ànd àn àvàìlàbìlìty pìckèr àrè thè shàpès à qùèstìòn càn tàkè. [[#pòrtàl #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw à qùèstìòn ìs pròtèctèd. •••••••••** Fìèld làbèls, hèlp tèxt ànd cònfìgùràtìòn àrè stòrèd èncryptèd ùndèr à kèy dèrìvèd fròm thè òrgànìzàtìòn's pùblìc kèy. Ànyònè whò càn rèàd thàt pùblìc kèy càn dèrìvè thàt kèy, sò thè èncryptìòn kèèps à stòlèn dàtàbàsè fròm lìstìng whàt à crìsìs lìnè àsks ìts càllèrs ànd dòès nòt hìdè thè qùèstìòns fròm thè sèrvèr thàt sèrvès thèm. Thè ànswèrs àrè èncryptèd ùndèr à kèy thè sèrvèr hàs nò wày tò dèrìvè. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè twò kèy trèès. [[#èncryptìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Qùèstìòns thàt dèpènd òn àn èàrlìèr ànswèr. •••••••••••••** À fìèld càn bè sèt tò àppèàr ònly whèn ànòthèr fìèld hòlds à pàrtìcùlàr vàlùè, ànd à fìèld thàt stàys hìddèn ìs lèft òùt òf thè èncryptèd ànswèr sèt ànd òùt òf thè càsè tèxt. Thè sèrvèr ìs nèvèr hàndèd àn ànswèr tò à qùèstìòn thè vìsìtòr wàs nòt shòwn. [[#clìènt-dàtà #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt à fìèld ròlè tèlls thè sèrvèr. •••••••••••** Mòst qùèstìòns càrry nò ròlè ànd pròdùcè nòthìng thè sèrvèr càn rèàd. À qùèstìòn gìvèn à ròùtìng, ùrgèncy òr èscàlàtìòn ròlè wòrks dìffèrèntly, bècàùsè thè bròwsèr rèsòlvès thè chòsèn òptìòn tò à qùèùè, à prìòrìty òr àn àlèrt lèvèl ànd sènds thàt sìnglè rèsòlvèd vàlùè ìn thè clèàr, whìlè thè ànswèr tèxt stàys èncryptèd lìkè èvèry òthèr. Sòmèònè rèàdìng à dàtàbàsè dùmp lèàrns whìch qùèùè à càsè wènt tò ànd nòt thè sèntèncè thàt sènt ìt thèrè. [Fìèld ròlès ànd màppìngs](#àdmìn-fòrms/fìèld-cònfìg) còvèrs hòw à ròlè ìs cònfìgùrèd. [[#mètàdàtà #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè vìsìtòr ìs tòld àbòùt èàch fìèld. •••••••••••••** À fìèld càrryìng à ròlè thàt pròdùcès à sèrvèr-vìsìblè sìgnàl ìs màrkèd às pròdùcìng ònè, à fìèld whòsè ròlè pròdùcès nòthìng rèàdàblè ìs màrkèd às èncryptèd, ànd à fìèld wìth nò ròlè càrrìès nò màrk. Thè dìstìnctìòn ìs màdè whèrè thè vìsìtòr ìs dècìdìng whàt tò typè ràthèr thàn ìn à pòlìcy pàgè. [[#prìvàcy #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fìèld ròws ànd thè dèrìvèd kèy. •••••••••••** Fìèld dèfìnìtìòns lìvè ìn \`ìntàkè_fòrm_fìèlds\` fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/089_ìntàkè_fòrms.ts\`, whèrè \`èncryptèd_làbèl\` ànd \`èncryptèd_cònfìg\` àrè cìphèrtèxt, \`ròlè\` ìs à plàìntèxt tàg ànd \`ròùtìng_qùèùè_ìds\` ìs à plàìntèxt àllòw-lìst thè sèrvèr chècks à rèsòlvèd qùèùè àgàìnst. Thè kèy còmès fròm \`dèrìvèClìèntBràndìngKèy\` ìn \`pàckàgès/cryptò/src/bràndìng.ts\` ànd thè fòùr èncrypt ànd dècrypt fùnctìòns àrè ìn \`pàckàgès/cryptò/src/ìntàkè-fòrm.ts\`, sò à sècònd pròdùcèr cànnòt rèstàtè thè àssòcìàtèd dàtà by hànd. Vìsìbìlìty èvàlùàtìòn ànd pàgè slìcìng àrè \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/ìntàkè-fòrm-lògìc.ts\`. [[#sèrvèr-hòlds #èncryptìòn]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A published form carries its own questions, and the page renders whatever field set the organization saved in place of the built-in one. Text, long text, dro..." |
*
* @param {Demo_Narrative_Client_Intake_Fields_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_fields_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Fields_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Fields_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_fields_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_fields_body(inputs)
	return en_demo_narrative_client_intake_fields_body(inputs)
});