/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Credentials_BodyInputs */

const en_demo_narrative_topic_credentials_body = /** @type {(inputs: Demo_Narrative_Topic_Credentials_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Signing in requires a username and a password. The username is a login identifier, not an email address. An admin can set the username when creating accounts directly, or the admin can send invite links instead and the user chooses their own username and password during enrollment. One copy of the password authenticates with the server. A second copy stays in the browser and feeds the key derivation that unlocks the organization's encrypted data. [[#keys #privacy]]
**Server-side password storage.** The account row holds a scrypt hash that can confirm a correct password but cannot be reversed to reveal it. The process that turns a password into encryption keys runs entirely in the browser. The browser's own code enforces a minimum difficulty for that process. The server can raise the difficulty but cannot lower it. An attacker with full server access cannot reduce the cost of guessing a password. [How keys are derived](#deep-dive/how-keys-are-derived) covers the browser's derivation path. [[#server-holds #keys]]
**Server-side username storage.** The users table stores no plaintext username. It holds a blind index hash for lookup and a sealed copy that only the browser can decrypt. When a request arrives for a username that does not exist, the server returns a deterministic fake salt derived from a server-held secret. The response is indistinguishable from a response for a real account. [[#server-holds #metadata]]
**Key lifetime.** The keys produced from the password live in the crypto worker's memory until the user signs out or closes the browser. They are zeroed at that point. Nothing derived from the password is written to disk or transmitted. A seized server contains no key material. [[#encryption #keys]]
**Password loss.** There is no reset link and no recovery question. An administrator sets the initial password when creating an account directly but cannot read or replace it afterward. Changing a password requires the current one. To restore access, an administrator removes the account and creates a new one, or sends a new invite link for the user. Cases the locked account could access remain readable to every other account with access. Each case key is wrapped individually per account, not shared across the organization. [[#failure-states #keys]]
**The login and key-derivation code.** Browser-side login and key derivation: \`packages/client/src/lib/auth/login-crypto.ts\`. Argon2 parameter floor: \`enforceArgon2Floor\` in \`packages/crypto/src/derive.ts\`. Server-side authentication: \`packages/server/src/auth/service.ts\` and \`packages/server/src/auth/password.ts\`. Username enumeration defense: \`packages/server/src/auth/salt-defense.ts\`. Password change: \`packages/server/src/routes/profile.ts\` and \`packages/client/src/lib/settings/password-change.ts\`. [[#keys #server-holds]]`)
};

const es_demo_narrative_topic_credentials_body = /** @type {(inputs: Demo_Narrative_Topic_Credentials_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Iniciar sesión requiere un nombre de usuario y una contraseña. El nombre de usuario es un identificador de inicio de sesión, no una dirección de correo electrónico. Un administrador puede establecer el nombre de usuario cuando crea cuentas directamente, o puede enviar enlaces de invitación y el usuario elige su propio nombre de usuario y contraseña durante la inscripción. Una copia de la contraseña se usa para autenticarse con el servidor. Una segunda copia permanece en el navegador y alimenta la derivación de claves que desbloquea los datos cifrados de la organización. [[#keys #privacy]]
**Almacenamiento de contraseñas en el servidor.** La fila de la cuenta contiene un hash scrypt que puede confirmar una contraseña correcta, pero no puede revertirse para revelarla. El proceso que convierte una contraseña en claves de cifrado se ejecuta completamente en el navegador. El código del navegador impone una dificultad mínima para ese proceso. El servidor puede aumentar la dificultad, pero no puede reducirla. Un atacante con acceso total al servidor no puede reducir el coste de adivinar una contraseña. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) cubre la ruta de derivación del navegador. [[#server-holds #keys]]
**Almacenamiento de nombres de usuario en el servidor.** La tabla de usuarios no almacena nombres de usuario en texto plano. Contiene un hash de índice ciego para búsquedas y una copia sellada que solo el navegador puede descifrar. Cuando llega una solicitud con un nombre de usuario que no existe, el servidor devuelve un salt falso determinista derivado de un secreto del servidor. La respuesta es indistinguible de una respuesta para una cuenta real. [[#server-holds #metadata]]
**Vida útil de las claves.** Las claves producidas a partir de la contraseña viven en la memoria del worker criptográfico hasta que el usuario cierra sesión o cierra el navegador. Se eliminan de la memoria en ese momento. Nada derivado de la contraseña se escribe en disco ni se transmite. Un servidor incautado no contiene material de claves. [[#encryption #keys]]
**Pérdida de contraseña.** No hay enlace de restablecimiento ni pregunta de recuperación. Un administrador establece la contraseña inicial cuando crea una cuenta directamente, pero no puede leerla ni reemplazarla después. Cambiar la contraseña requiere la contraseña actual. Para restaurar el acceso, un administrador elimina la cuenta y crea una nueva, o envía un nuevo enlace de invitación para el usuario. Los casos a los que la cuenta bloqueada tenía acceso siguen siendo legibles para todas las demás cuentas con acceso. Cada clave de caso se envuelve individualmente por cuenta, no se comparte en toda la organización. [[#failure-states #keys]]
**El código de inicio de sesión y derivación de claves.** Inicio de sesión y derivación de claves en el navegador: \`packages/client/src/lib/auth/login-crypto.ts\`. Mínimo de parámetros de Argon2: \`enforceArgon2Floor\` en \`packages/crypto/src/derive.ts\`. Autenticación en el servidor: \`packages/server/src/auth/service.ts\` y \`packages/server/src/auth/password.ts\`. Defensa contra enumeración de nombres de usuario: \`packages/server/src/auth/salt-defense.ts\`. Cambio de contraseña: \`packages/server/src/routes/profile.ts\` y \`packages/client/src/lib/settings/password-change.ts\`. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_topic_credentials_body = /** @type {(inputs: Demo_Narrative_Topic_Credentials_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Sìgnìng ìn rèqùìrès à ùsèrnàmè ànd à pàsswòrd. Thè ùsèrnàmè ìs à lògìn ìdèntìfìèr, nòt àn èmàìl àddrèss. Àn àdmìn càn sèt thè ùsèrnàmè whèn crèàtìng àccòùnts dìrèctly, òr thè àdmìn càn sènd ìnvìtè lìnks ìnstèàd ànd thè ùsèr chòòsès thèìr òwn ùsèrnàmè ànd pàsswòrd dùrìng ènròllmènt. Ònè còpy òf thè pàsswòrd àùthèntìcàtès wìth thè sèrvèr. À sècònd còpy stàys ìn thè bròwsèr ànd fèèds thè kèy dèrìvàtìòn thàt ùnlòcks thè òrgànìzàtìòn's èncryptèd dàtà. [[#kèys #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèrvèr-sìdè pàsswòrd stòràgè. •••••••••** Thè àccòùnt ròw hòlds à scrypt hàsh thàt càn cònfìrm à còrrèct pàsswòrd bùt cànnòt bè rèvèrsèd tò rèvèàl ìt. Thè pròcèss thàt tùrns à pàsswòrd ìntò èncryptìòn kèys rùns èntìrèly ìn thè bròwsèr. Thè bròwsèr's òwn còdè ènfòrcès à mìnìmùm dìffìcùlty fòr thàt pròcèss. Thè sèrvèr càn ràìsè thè dìffìcùlty bùt cànnòt lòwèr ìt. Àn àttàckèr wìth fùll sèrvèr àccèss cànnòt rèdùcè thè còst òf gùèssìng à pàsswòrd. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs thè bròwsèr's dèrìvàtìòn pàth. [[#sèrvèr-hòlds #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèrvèr-sìdè ùsèrnàmè stòràgè. •••••••••** Thè ùsèrs tàblè stòrès nò plàìntèxt ùsèrnàmè. Ìt hòlds à blìnd ìndèx hàsh fòr lòòkùp ànd à sèàlèd còpy thàt ònly thè bròwsèr càn dècrypt. Whèn à rèqùèst àrrìvès fòr à ùsèrnàmè thàt dòès nòt èxìst, thè sèrvèr rètùrns à dètèrmìnìstìc fàkè sàlt dèrìvèd fròm à sèrvèr-hèld sècrèt. Thè rèspònsè ìs ìndìstìngùìshàblè fròm à rèspònsè fòr à rèàl àccòùnt. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Kèy lìfètìmè. ••••** Thè kèys pròdùcèd fròm thè pàsswòrd lìvè ìn thè cryptò wòrkèr's mèmòry ùntìl thè ùsèr sìgns òùt òr clòsès thè bròwsèr. Thèy àrè zèròèd àt thàt pòìnt. Nòthìng dèrìvèd fròm thè pàsswòrd ìs wrìttèn tò dìsk òr trànsmìttèd. À sèìzèd sèrvèr còntàìns nò kèy màtèrìàl. [[#èncryptìòn #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pàsswòrd lòss. •••••** Thèrè ìs nò rèsèt lìnk ànd nò rècòvèry qùèstìòn. Àn àdmìnìstràtòr sèts thè ìnìtìàl pàsswòrd whèn crèàtìng àn àccòùnt dìrèctly bùt cànnòt rèàd òr rèplàcè ìt àftèrwàrd. Chàngìng à pàsswòrd rèqùìrès thè cùrrènt ònè. Tò rèstòrè àccèss, àn àdmìnìstràtòr rèmòvès thè àccòùnt ànd crèàtès à nèw ònè, òr sènds à nèw ìnvìtè lìnk fòr thè ùsèr. Càsès thè lòckèd àccòùnt còùld àccèss rèmàìn rèàdàblè tò èvèry òthèr àccòùnt wìth àccèss. Èàch càsè kèy ìs wràppèd ìndìvìdùàlly pèr àccòùnt, nòt shàrèd àcròss thè òrgànìzàtìòn. [[#fàìlùrè-stàtès #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè lògìn ànd kèy-dèrìvàtìòn còdè. •••••••••••** Bròwsèr-sìdè lògìn ànd kèy dèrìvàtìòn: \`pàckàgès/clìènt/src/lìb/àùth/lògìn-cryptò.ts\`. Àrgòn2 pàràmètèr flòòr: \`ènfòrcèÀrgòn2Flòòr\` ìn \`pàckàgès/cryptò/src/dèrìvè.ts\`. Sèrvèr-sìdè àùthèntìcàtìòn: \`pàckàgès/sèrvèr/src/àùth/sèrvìcè.ts\` ànd \`pàckàgès/sèrvèr/src/àùth/pàsswòrd.ts\`. Ùsèrnàmè ènùmèràtìòn dèfènsè: \`pàckàgès/sèrvèr/src/àùth/sàlt-dèfènsè.ts\`. Pàsswòrd chàngè: \`pàckàgès/sèrvèr/src/ròùtès/pròfìlè.ts\` ànd \`pàckàgès/clìènt/src/lìb/sèttìngs/pàsswòrd-chàngè.ts\`. [[#kèys #sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Signing in requires a username and a password. The username is a login identifier, not an email address. An admin can set the username when creating accounts..." |
*
* @param {Demo_Narrative_Topic_Credentials_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_credentials_body = /** @type {((inputs?: Demo_Narrative_Topic_Credentials_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Credentials_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_credentials_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_credentials_body(inputs)
	return en_demo_narrative_topic_credentials_body(inputs)
});