/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Correction_Status_BodyInputs */

const en_demo_narrative_topic_correction_status_body = /** @type {(inputs: Demo_Narrative_Topic_Correction_Status_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A contact correction reaches the unified case thread as its own kind of follow-up, carrying the phone number or the email address a client says is theirs now. [[#client-data]]
**What does the follow-up carry?** A versioned record with a phone, an email, or both. The record is sealed with the ticket key like any other follow-up. Only browsers the ticket key is wrapped for can read the corrected value. The follow-up type and the fact that a client wrote it are plaintext columns. A database dump shows that a client corrected contact details on a ticket at a given minute, but neither the old value nor the new one. [The trust boundary](#deep-dive/the-trust-boundary) lists the columns a dump reaches. [[#encryption #server-holds #metadata]]
**Applying a correction.** The follow-up offers to carry each value into the matching contact row. That opens the edit path with the value already filled in. The save is left to the user who opened it, because a correction arrives over the same channel anyone could reach the organization on. A save that lands marks the correction handled. [The full case record](#ticket-detail/case-panel) covers what happens when the saved value already belongs to another client record. [[#client-data #privacy]]
**Handling and the compose warning.** Handling is an acknowledge reaction on the follow-up, one row per account. The line names the first user who left one. The reaction row holds the follow-up, the account, and the time in plaintext. The server can see who reviewed a correction and when, but not the value they reviewed. With an unacknowledged correction on the ticket, composing a text and opening the call options both report it, because both are about to use a number the client may have just replaced. [Channel warnings](#ticket-detail/exposure-hints) covers the compose bar's warning surface. [[#metadata #server-holds #telephony]]
**The payload schema and renderer.** \`packages/shared/src/schemas/contact-correction-payload.ts\` defines the record and parses it. \`CorrectionBody.svelte\` renders it on the ticket thread and on the client's own thread from one implementation. Content that does not parse as a correction record renders as ordinary text, which is what corrections written before the record existed decrypt to. [[#client-data #failure-states]]`)
};

const es_demo_narrative_topic_correction_status_body = /** @type {(inputs: Demo_Narrative_Topic_Correction_Status_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Una corrección de contacto llega al hilo de caso unificado como un tipo propio de seguimiento, con el número de teléfono o la dirección de correo electrónico que el cliente dice que ahora es suya. [[#client-data]]
**¿Qué contiene el seguimiento?** Un registro versionado con un teléfono, un correo electrónico o ambos. El registro se sella con la clave del ticket como cualquier otro seguimiento. Solo los navegadores para los que la clave del ticket está envuelta pueden leer el valor corregido. El tipo de seguimiento y el hecho de que lo escribió un cliente son columnas en texto plano. Un volcado de base de datos muestra que un cliente corrigió datos de contacto en un ticket en un minuto determinado, pero no el valor anterior ni el nuevo. [La frontera de confianza](#deep-dive/the-trust-boundary) enumera las columnas que un volcado alcanza. [[#encryption #server-holds #metadata]]
**Aplicar una corrección.** El seguimiento ofrece trasladar cada valor a la fila de contacto correspondiente. Eso abre la ruta de edición con el valor ya rellenado. Guardar queda en manos de la persona usuaria que lo abrió, porque una corrección llega por el mismo canal que cualquier persona podría usar para contactar a la organización. Un guardado exitoso marca la corrección como gestionada. [El expediente completo](#ticket-detail/case-panel) trata lo que ocurre cuando el valor guardado ya pertenece a otro registro de cliente. [[#client-data #privacy]]
**Gestión y el aviso en la composición.** La gestión es una reacción de confirmación sobre el seguimiento, una fila por cuenta. La línea nombra la primera persona que dejó una. La fila de la reacción contiene el seguimiento, la cuenta y la hora en texto plano. El servidor puede ver quién revisó una corrección y cuándo, pero no el valor que revisó. Con una corrección sin confirmar en el ticket, redactar un texto y abrir las opciones de llamada informan de ello, porque ambas acciones van a usar un número que el cliente puede haber reemplazado. [Avisos de canal](#ticket-detail/exposure-hints) trata la superficie de aviso de la barra de composición. [[#metadata #server-holds #telephony]]
**El esquema del contenido y el renderizador.** \`packages/shared/src/schemas/contact-correction-payload.ts\` define el registro y lo analiza. \`CorrectionBody.svelte\` lo renderiza en el hilo del ticket y en el hilo propio del cliente desde una sola implementación. El contenido que no se analiza como un registro de corrección se muestra como texto ordinario. Las correcciones escritas antes de que el registro existiera se descifran como texto sin estructura. [[#client-data #failure-states]]`)
};

const en_xa2_demo_narrative_topic_correction_status_body = /** @type {(inputs: Demo_Narrative_Topic_Correction_Status_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À còntàct còrrèctìòn rèàchès thè ùnìfìèd càsè thrèàd às ìts òwn kìnd òf fòllòw-ùp, càrryìng thè phònè nùmbèr òr thè èmàìl àddrèss à clìènt sàys ìs thèìrs nòw. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè fòllòw-ùp càrry? •••••••••** À vèrsìònèd rècòrd wìth à phònè, àn èmàìl, òr bòth. Thè rècòrd ìs sèàlèd wìth thè tìckèt kèy lìkè àny òthèr fòllòw-ùp. Ònly bròwsèrs thè tìckèt kèy ìs wràppèd fòr càn rèàd thè còrrèctèd vàlùè. Thè fòllòw-ùp typè ànd thè fàct thàt à clìènt wròtè ìt àrè plàìntèxt còlùmns. À dàtàbàsè dùmp shòws thàt à clìènt còrrèctèd còntàct dètàìls òn à tìckèt àt à gìvèn mìnùtè, bùt nèìthèr thè òld vàlùè nòr thè nèw ònè. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) lìsts thè còlùmns à dùmp rèàchès. [[#èncryptìòn #sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àpplyìng à còrrèctìòn. •••••••** Thè fòllòw-ùp òffèrs tò càrry èàch vàlùè ìntò thè màtchìng còntàct ròw. Thàt òpèns thè èdìt pàth wìth thè vàlùè àlrèàdy fìllèd ìn. Thè sàvè ìs lèft tò thè ùsèr whò òpènèd ìt, bècàùsè à còrrèctìòn àrrìvès òvèr thè sàmè chànnèl ànyònè còùld rèàch thè òrgànìzàtìòn òn. À sàvè thàt lànds màrks thè còrrèctìòn hàndlèd. [Thè fùll càsè rècòrd](#tìckèt-dètàìl/càsè-pànèl) còvèrs whàt hàppèns whèn thè sàvèd vàlùè àlrèàdy bèlòngs tò ànòthèr clìènt rècòrd. [[#clìènt-dàtà #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hàndlìng ànd thè còmpòsè wàrnìng. ••••••••••** Hàndlìng ìs àn àcknòwlèdgè rèàctìòn òn thè fòllòw-ùp, ònè ròw pèr àccòùnt. Thè lìnè nàmès thè fìrst ùsèr whò lèft ònè. Thè rèàctìòn ròw hòlds thè fòllòw-ùp, thè àccòùnt, ànd thè tìmè ìn plàìntèxt. Thè sèrvèr càn sèè whò rèvìèwèd à còrrèctìòn ànd whèn, bùt nòt thè vàlùè thèy rèvìèwèd. Wìth àn ùnàcknòwlèdgèd còrrèctìòn òn thè tìckèt, còmpòsìng à tèxt ànd òpènìng thè càll òptìòns bòth rèpòrt ìt, bècàùsè bòth àrè àbòùt tò ùsè à nùmbèr thè clìènt mày hàvè jùst rèplàcèd. [Chànnèl wàrnìngs](#tìckèt-dètàìl/èxpòsùrè-hìnts) còvèrs thè còmpòsè bàr's wàrnìng sùrfàcè. [[#mètàdàtà #sèrvèr-hòlds #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pàylòàd schèmà ànd rèndèrèr. ••••••••••** \`pàckàgès/shàrèd/src/schèmàs/còntàct-còrrèctìòn-pàylòàd.ts\` dèfìnès thè rècòrd ànd pàrsès ìt. \`CòrrèctìònBòdy.svèltè\` rèndèrs ìt òn thè tìckèt thrèàd ànd òn thè clìènt's òwn thrèàd fròm ònè ìmplèmèntàtìòn. Còntènt thàt dòès nòt pàrsè às à còrrèctìòn rècòrd rèndèrs às òrdìnàry tèxt, whìch ìs whàt còrrèctìòns wrìttèn bèfòrè thè rècòrd èxìstèd dècrypt tò. [[#clìènt-dàtà #fàìlùrè-stàtès]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A contact correction reaches the unified case thread as its own kind of follow-up, carrying the phone number or the email address a client says is theirs now..." |
*
* @param {Demo_Narrative_Topic_Correction_Status_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_correction_status_body = /** @type {((inputs?: Demo_Narrative_Topic_Correction_Status_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Correction_Status_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_correction_status_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_correction_status_body(inputs)
	return en_demo_narrative_topic_correction_status_body(inputs)
});