/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Form_BodyInputs */

const en_demo_narrative_client_intake_form_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Form_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The intake page accepts a request for help from a visitor with no account and no existing relationship to the organization. Nothing is asked before the form itself. [[#portal #privacy]]
**The built-in form.** An organization without a published form gets one that asks for a name, a message, and a preferred way to be reached. The name is optional and the message is required. Labels and placeholders are bilingual, so a visitor reading in Spanish sees Spanish field text throughout. [Contact method and follow-up options](#client-intake/contact-method) covers the reach-back step. [[#client-data]]
**Published forms.** A published form takes the place of the built-in one, carries its own link name and destination queue, and routes submissions independently. Multiple published forms can be active at the same time. A link name that does not match any active form returns the same not-available notice that disabling web intake produces, so a guessed address reveals nothing about what else exists. [Custom form fields](#client-intake/fields) covers available field types, and [Intake forms list](#admin-org/intake-forms) covers the organization-wide switches. [[#portal #metadata]]
**Written content on a form.** Each form supports an introduction, a banner image, a confirmation message, and a closing message. All four are stored in plaintext, because the page is public and anyone who loads it can read the content. The server serves the banner as an ordinary image. [Field list](#admin-forms/builder) covers where the content is authored. [[#server-holds]]
**What stays on the device?** The form itself stores nothing in the browser. Values the visitor typed remain in memory and disappear when the tab closes. Outside the form, the language picker writes a cookie and the color-scheme toggle saves a preference to local storage. A browser history entry is also created by the navigation. [Quick exit](#client-portal/quick-exit) covers the control that abandons the page immediately. [[#privacy #client-data]]
**When is no form available?** The page shows a not-available notice when web intake is off for the organization, when the link name does not match any active form, or when the built-in form is disabled and no custom default replaces it. A separate notice explains the JavaScript requirement when scripting is disabled, because the browser performs the encryption. A load or decryption failure offers a retry button, and a missing organization public key tells the visitor encryption is unavailable and suggests calling. [Closed form](#client-intake/closed-form) covers what a closing date produces. [[#failure-states]]
**The public read and the page component.** \`resolvePublicForm\` in \`packages/server/src/portal/intake-form-service.ts\` handles the public read and returns field labels and configuration in plaintext. The page component is \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\`, whose fallback field set is \`DEFAULT_INTAKE_FORM\`. Banner images are served by \`packages/server/src/routes/form-assets.ts\`, which limits the content type to PNG, JPEG, and WebP. [[#server-holds #portal]]`)
};

const es_demo_narrative_client_intake_form_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Form_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La página de admisión acepta una petición de ayuda de un visitante sin cuenta ni relación previa con la organización. No se pide nada antes del propio formulario. [[#portal #privacy]]
**El formulario integrado.** Una organización sin formulario publicado recibe uno que pregunta un nombre, un mensaje y la forma preferida de contacto. El nombre es opcional y el mensaje es obligatorio. Las etiquetas y los textos de ayuda son bilingües, de modo que quien lee en español ve las preguntas en español en todo momento. [Método de contacto y opciones de seguimiento](#client-intake/contact-method) trata el paso de contacto. [[#client-data]]
**Formularios publicados.** Un formulario publicado ocupa el lugar del integrado, lleva su propio nombre de enlace y cola de destino y encamina los envíos de forma independiente. Varios formularios publicados pueden estar activos al mismo tiempo. Un nombre de enlace que no coincide con ningún formulario activo devuelve el mismo aviso de no disponible que produce desactivar la admisión web, de modo que una dirección adivinada no revela nada sobre lo que existe. [Campos de formulario personalizado](#client-intake/fields) trata los tipos de campo disponibles, y [Lista de formularios de admisión](#admin-org/intake-forms) trata los interruptores de toda la organización. [[#portal #metadata]]
**Contenido redactado en un formulario.** Cada formulario admite una introducción, una imagen de portada, un mensaje de confirmación y un mensaje de cierre. Los cuatro se almacenan en texto plano, porque la página es pública y cualquiera que la cargue puede leer el contenido. El servidor sirve la portada como una imagen corriente. [Lista de campos](#admin-forms/builder) trata dónde se redacta ese contenido. [[#server-holds]]
**¿Qué queda en el dispositivo?** El formulario en sí no almacena nada en el navegador. Los valores que escribió el visitante permanecen en memoria y desaparecen al cerrar la pestaña. Fuera del formulario, el selector de idioma escribe una cookie y el conmutador de esquema de color guarda una preferencia en el almacenamiento local. La navegación también crea una entrada en el historial del navegador. [Salida rápida](#client-portal/quick-exit) trata el control que abandona la página de inmediato. [[#privacy #client-data]]
**¿Cuándo no hay formulario disponible?** La página muestra un aviso de no disponible cuando la admisión web está desactivada para la organización, cuando el nombre de enlace no coincide con ningún formulario activo, o cuando el formulario integrado está desactivado y ningún formulario personalizado predeterminado lo sustituye. Un aviso aparte explica el requisito de JavaScript cuando el scripting está desactivado, porque el navegador realiza el cifrado. Un fallo de carga o de descifrado ofrece un botón de reintento, y la ausencia de la clave pública de la organización informa al visitante de que el cifrado no está disponible y sugiere llamar. [Formulario cerrado](#client-intake/closed-form) trata lo que produce una fecha de cierre. [[#failure-states]]
**La lectura pública y el componente de página.** \`resolvePublicForm\`, en \`packages/server/src/portal/intake-form-service.ts\`, gestiona la lectura pública y devuelve etiquetas y configuración de campo en texto plano. El componente de página es \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\`, cuyo conjunto de campos de reserva es \`DEFAULT_INTAKE_FORM\`. Las imágenes de portada las sirve \`packages/server/src/routes/form-assets.ts\`, que limita el tipo de contenido a PNG, JPEG y WebP. [[#server-holds #portal]]`)
};

const en_xa2_demo_narrative_client_intake_form_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Form_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ìntàkè pàgè àccèpts à rèqùèst fòr hèlp fròm à vìsìtòr wìth nò àccòùnt ànd nò èxìstìng rèlàtìònshìp tò thè òrgànìzàtìòn. Nòthìng ìs àskèd bèfòrè thè fòrm ìtsèlf. [[#pòrtàl #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè bùìlt-ìn fòrm. ••••••** Àn òrgànìzàtìòn wìthòùt à pùblìshèd fòrm gèts ònè thàt àsks fòr à nàmè, à mèssàgè, ànd à prèfèrrèd wày tò bè rèàchèd. Thè nàmè ìs òptìònàl ànd thè mèssàgè ìs rèqùìrèd. Làbèls ànd plàcèhòldèrs àrè bìlìngùàl, sò à vìsìtòr rèàdìng ìn Spànìsh sèès Spànìsh fìèld tèxt thròùghòùt. [Còntàct mèthòd ànd fòllòw-ùp òptìòns](#clìènt-ìntàkè/còntàct-mèthòd) còvèrs thè rèàch-bàck stèp. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pùblìshèd fòrms. •••••** À pùblìshèd fòrm tàkès thè plàcè òf thè bùìlt-ìn ònè, càrrìès ìts òwn lìnk nàmè ànd dèstìnàtìòn qùèùè, ànd ròùtès sùbmìssìòns ìndèpèndèntly. Mùltìplè pùblìshèd fòrms càn bè àctìvè àt thè sàmè tìmè. À lìnk nàmè thàt dòès nòt màtch àny àctìvè fòrm rètùrns thè sàmè nòt-àvàìlàblè nòtìcè thàt dìsàblìng wèb ìntàkè pròdùcès, sò à gùèssèd àddrèss rèvèàls nòthìng àbòùt whàt èlsè èxìsts. [Cùstòm fòrm fìèlds](#clìènt-ìntàkè/fìèlds) còvèrs àvàìlàblè fìèld typès, ànd [Ìntàkè fòrms lìst](#àdmìn-òrg/ìntàkè-fòrms) còvèrs thè òrgànìzàtìòn-wìdè swìtchès. [[#pòrtàl #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Wrìttèn còntènt òn à fòrm. ••••••••** Èàch fòrm sùppòrts àn ìntròdùctìòn, à bànnèr ìmàgè, à cònfìrmàtìòn mèssàgè, ànd à clòsìng mèssàgè. Àll fòùr àrè stòrèd ìn plàìntèxt, bècàùsè thè pàgè ìs pùblìc ànd ànyònè whò lòàds ìt càn rèàd thè còntènt. Thè sèrvèr sèrvès thè bànnèr às àn òrdìnàry ìmàgè. [Fìèld lìst](#àdmìn-fòrms/bùìldèr) còvèrs whèrè thè còntènt ìs àùthòrèd. [[#sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt stàys òn thè dèvìcè? ••••••••** Thè fòrm ìtsèlf stòrès nòthìng ìn thè bròwsèr. Vàlùès thè vìsìtòr typèd rèmàìn ìn mèmòry ànd dìsàppèàr whèn thè tàb clòsès. Òùtsìdè thè fòrm, thè làngùàgè pìckèr wrìtès à còòkìè ànd thè còlòr-schèmè tògglè sàvès à prèfèrèncè tò lòcàl stòràgè. À bròwsèr hìstòry èntry ìs àlsò crèàtèd by thè nàvìgàtìòn. [Qùìck èxìt](#clìènt-pòrtàl/qùìck-èxìt) còvèrs thè còntròl thàt àbàndòns thè pàgè ìmmèdìàtèly. [[#prìvàcy #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn ìs nò fòrm àvàìlàblè? ••••••••** Thè pàgè shòws à nòt-àvàìlàblè nòtìcè whèn wèb ìntàkè ìs òff fòr thè òrgànìzàtìòn, whèn thè lìnk nàmè dòès nòt màtch àny àctìvè fòrm, òr whèn thè bùìlt-ìn fòrm ìs dìsàblèd ànd nò cùstòm dèfàùlt rèplàcès ìt. À sèpàràtè nòtìcè èxplàìns thè JàvàScrìpt rèqùìrèmènt whèn scrìptìng ìs dìsàblèd, bècàùsè thè bròwsèr pèrfòrms thè èncryptìòn. À lòàd òr dècryptìòn fàìlùrè òffèrs à rètry bùttòn, ànd à mìssìng òrgànìzàtìòn pùblìc kèy tèlls thè vìsìtòr èncryptìòn ìs ùnàvàìlàblè ànd sùggèsts càllìng. [Clòsèd fòrm](#clìènt-ìntàkè/clòsèd-fòrm) còvèrs whàt à clòsìng dàtè pròdùcès. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pùblìc rèàd ànd thè pàgè còmpònènt. ••••••••••••** \`rèsòlvèPùblìcFòrm\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-fòrm-sèrvìcè.ts\` hàndlès thè pùblìc rèàd ànd rètùrns fìèld làbèls ànd cònfìgùràtìòn ìn plàìntèxt. Thè pàgè còmpònènt ìs \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/ÌntàkèFòrmBòdy.svèltè\`, whòsè fàllbàck fìèld sèt ìs \`DÈFÀÙLT_ÌNTÀKÈ_FÒRM\`. Bànnèr ìmàgès àrè sèrvèd by \`pàckàgès/sèrvèr/src/ròùtès/fòrm-àssèts.ts\`, whìch lìmìts thè còntènt typè tò PNG, JPÈG, ànd WèbP. [[#sèrvèr-hòlds #pòrtàl]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The intake page accepts a request for help from a visitor with no account and no existing relationship to the organization. Nothing is asked before the form ..." |
*
* @param {Demo_Narrative_Client_Intake_Form_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_form_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Form_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Form_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_form_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_form_body(inputs)
	return en_demo_narrative_client_intake_form_body(inputs)
});