/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_System_Events_BodyInputs */

const en_demo_narrative_topic_system_events_body = /** @type {(inputs: Demo_Narrative_Topic_System_Events_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Assignments, status changes, priority and queue moves, holds, and merges are recorded in the conversation thread as follow-ups of their own, so what was done to a ticket sits in the same sequence as what was said on it. The server writes these follow-ups, and the server holds no key that can seal ticket content, so each one is a type and a few parameters in plaintext with an empty content column. A database dump shows that an account was assigned a ticket on a given morning, that its priority changed from normal to urgent an hour later, and which queue it moved to, while the words of the ticket stay closed. [The trust boundary](#deep-dive/the-trust-boundary) covers the rest of what a dump reaches. [[#client-data #server-holds #metadata #encryption]]
**How does the browser resolve the names?** The parameters store accounts and queues by identifier. The browser resolves each identifier against organization-key ciphertext it already holds, so the readable sentence exists only where the organization key is present. An identifier the browser cannot resolve reads as an unnamed account or queue rather than as a failure. [[#failure-states #client-data]]
**Grouping consecutive follow-ups.** Consecutive follow-ups of one type within ten minutes of each other collapse into a single line with a count. Only hold placed, hold removed, status opened, and status closed are eligible. A priority or queue change carries before-and-after values that cannot be summed, so each one stays separate. [[#client-data]]
**What writes each follow-up?** Each follow-up is written by the operation that records it, not by the component that draws it. An assignment made from the ticket list, from the panel, or by an automatic rule produces the same follow-up. Who may perform each operation is a separate permission. [The permission system](#deep-dive/the-permission-system) covers those grants. [[#permissions]]
**The label map and the event column.** \`system-event-label.ts\` maps each type to its sentence and \`SystemEvent.svelte\` draws it. The parameters live in the \`event_params\` column from \`080_add_followup_event_params.ts\`. Hold, priority, queue, and status writes are in \`ticket-service.ts\`; assignment writes are in \`assignment.ts\`; merge writes are in \`merge-service.ts\`; the shared reopen path is in \`ticket-reopen.ts\`. [[#client-data]]`)
};

const es_demo_narrative_topic_system_events_body = /** @type {(inputs: Demo_Narrative_Topic_System_Events_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Las asignaciones, los cambios de estado, los movimientos de prioridad y cola, las esperas y las fusiones se registran en el hilo de conversación como seguimientos propios, de modo que lo que se hizo a un ticket queda en la misma secuencia que lo que se dijo en él. El servidor escribe estos seguimientos, y el servidor no tiene clave que pueda sellar el contenido del ticket, así que cada uno es un tipo y unos pocos parámetros en texto plano con una columna de contenido vacía. Un volcado de base de datos muestra que una cuenta fue asignada a un ticket en una mañana determinada, que su prioridad pasó de normal a urgente una hora después y a qué cola se movió, mientras las palabras del ticket permanecen cerradas. [La frontera de confianza](#deep-dive/the-trust-boundary) trata el resto de lo que un volcado alcanza. [[#client-data #server-holds #metadata #encryption]]
**¿Cómo resuelve el navegador los nombres?** Los parámetros almacenan cuentas y colas por identificador. El navegador resuelve cada identificador contra el texto cifrado con la clave de la organización que ya tiene, así que la frase legible existe solo donde la clave de la organización está presente. Un identificador que el navegador no puede resolver se lee como una cuenta o cola sin nombre en lugar de como un error. [[#failure-states #client-data]]
**Agrupación de seguimientos consecutivos.** Los seguimientos consecutivos del mismo tipo en un intervalo de diez minutos se comprimen en una sola línea con un conteo. Solo espera puesta, espera retirada, estado abierto y estado cerrado son elegibles. Un cambio de prioridad o cola lleva valores de antes y después que no se pueden sumar, así que cada uno queda separado. [[#client-data]]
**¿Qué escribe cada seguimiento?** Cada seguimiento lo escribe la operación que lo registra, no el componente que lo dibuja. Una asignación hecha desde la lista de tickets, desde el panel o por una regla automática produce el mismo seguimiento. Quién puede realizar cada operación es un permiso separado. [El sistema de permisos](#deep-dive/the-permission-system) trata esas concesiones. [[#permissions]]
**El mapa de etiquetas y la columna de evento.** \`system-event-label.ts\` asigna a cada tipo su frase y \`SystemEvent.svelte\` lo dibuja. Los parámetros viven en la columna \`event_params\` de \`080_add_followup_event_params.ts\`. Las escrituras de espera, prioridad, cola y estado están en \`ticket-service.ts\`; las de asignación en \`assignment.ts\`; las de fusión en \`merge-service.ts\`; la ruta compartida de reapertura en \`ticket-reopen.ts\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_system_events_body = /** @type {(inputs: Demo_Narrative_Topic_System_Events_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Àssìgnmènts, stàtùs chàngès, prìòrìty ànd qùèùè mòvès, hòlds, ànd mèrgès àrè rècòrdèd ìn thè cònvèrsàtìòn thrèàd às fòllòw-ùps òf thèìr òwn, sò whàt wàs dònè tò à tìckèt sìts ìn thè sàmè sèqùèncè às whàt wàs sàìd òn ìt. Thè sèrvèr wrìtès thèsè fòllòw-ùps, ànd thè sèrvèr hòlds nò kèy thàt càn sèàl tìckèt còntènt, sò èàch ònè ìs à typè ànd à fèw pàràmètèrs ìn plàìntèxt wìth àn èmpty còntènt còlùmn. À dàtàbàsè dùmp shòws thàt àn àccòùnt wàs àssìgnèd à tìckèt òn à gìvèn mòrnìng, thàt ìts prìòrìty chàngèd fròm nòrmàl tò ùrgènt àn hòùr làtèr, ànd whìch qùèùè ìt mòvèd tò, whìlè thè wòrds òf thè tìckèt stày clòsèd. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè rèst òf whàt à dùmp rèàchès. [[#clìènt-dàtà #sèrvèr-hòlds #mètàdàtà #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè bròwsèr rèsòlvè thè nàmès? ••••••••••••** Thè pàràmètèrs stòrè àccòùnts ànd qùèùès by ìdèntìfìèr. Thè bròwsèr rèsòlvès èàch ìdèntìfìèr àgàìnst òrgànìzàtìòn-kèy cìphèrtèxt ìt àlrèàdy hòlds, sò thè rèàdàblè sèntèncè èxìsts ònly whèrè thè òrgànìzàtìòn kèy ìs prèsènt. Àn ìdèntìfìèr thè bròwsèr cànnòt rèsòlvè rèàds às àn ùnnàmèd àccòùnt òr qùèùè ràthèr thàn às à fàìlùrè. [[#fàìlùrè-stàtès #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Gròùpìng cònsècùtìvè fòllòw-ùps. ••••••••••** Cònsècùtìvè fòllòw-ùps òf ònè typè wìthìn tèn mìnùtès òf èàch òthèr còllàpsè ìntò à sìnglè lìnè wìth à còùnt. Ònly hòld plàcèd, hòld rèmòvèd, stàtùs òpènèd, ànd stàtùs clòsèd àrè èlìgìblè. À prìòrìty òr qùèùè chàngè càrrìès bèfòrè-ànd-àftèr vàlùès thàt cànnòt bè sùmmèd, sò èàch ònè stàys sèpàràtè. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt wrìtès èàch fòllòw-ùp? •••••••••** Èàch fòllòw-ùp ìs wrìttèn by thè òpèràtìòn thàt rècòrds ìt, nòt by thè còmpònènt thàt dràws ìt. Àn àssìgnmènt màdè fròm thè tìckèt lìst, fròm thè pànèl, òr by àn àùtòmàtìc rùlè pròdùcès thè sàmè fòllòw-ùp. Whò mày pèrfòrm èàch òpèràtìòn ìs à sèpàràtè pèrmìssìòn. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs thòsè grànts. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè làbèl màp ànd thè èvènt còlùmn. •••••••••••** \`systèm-èvènt-làbèl.ts\` màps èàch typè tò ìts sèntèncè ànd \`SystèmÈvènt.svèltè\` dràws ìt. Thè pàràmètèrs lìvè ìn thè \`èvènt_pàràms\` còlùmn fròm \`080_àdd_fòllòwùp_èvènt_pàràms.ts\`. Hòld, prìòrìty, qùèùè, ànd stàtùs wrìtès àrè ìn \`tìckèt-sèrvìcè.ts\`; àssìgnmènt wrìtès àrè ìn \`àssìgnmènt.ts\`; mèrgè wrìtès àrè ìn \`mèrgè-sèrvìcè.ts\`; thè shàrèd rèòpèn pàth ìs ìn \`tìckèt-rèòpèn.ts\`. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Assignments, status changes, priority and queue moves, holds, and merges are recorded in the conversation thread as follow-ups of their own, so what was done..." |
*
* @param {Demo_Narrative_Topic_System_Events_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_system_events_body = /** @type {((inputs?: Demo_Narrative_Topic_System_Events_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_System_Events_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_system_events_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_system_events_body(inputs)
	return en_demo_narrative_topic_system_events_body(inputs)
});