/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Select_Mode_BodyInputs */

const en_demo_narrative_topic_select_mode_body = /** @type {(inputs: Demo_Narrative_Topic_Select_Mode_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Select mode lets an account pick several tickets so one action applies to all of them. The Select control beside the filters turns select mode on. A long press on a row also enters select mode and selects that row. [[#client-data]]
**What does each action write?** The bulk actions are assigning a ticket to an account, putting a ticket on hold, changing priority, and moving a ticket to another queue. Each action writes a plaintext column on the ticket row, so ticket content stays encrypted. A database dump shows a group of tickets that changed the same way at the same moment. Each action also writes a system event into that ticket's timeline. A priority or queue change that would leave the value unchanged writes nothing. [The trust boundary](#deep-dive/the-trust-boundary) sets out which columns each action writes. [[#server-holds #metadata]]
**Per-ticket sequencing.** A bulk action sends one request per ticket rather than a single wide write. The run stops at the first refusal and reports how many succeeded, so earlier tickets are changed and the rest are untouched. The selection clears whether the run finished or stopped. Running the same action again over the remaining tickets finishes the job. [[#failure-states]]
**Permission gates.** Assigning requires the Assign cases permission. Putting on hold, changing priority, and moving between queues require the Change case status permission. Every account sees all the bulk actions. The server refuses, ticket by ticket, any action whose permission the account lacks and any ticket outside the queues the account can access. [The permission system](#deep-dive/the-permission-system) covers where permissions come from. [[#permissions]]
**Selection state and batch runner.** The mode is \`createMultiSelect\` in \`packages/client/src/lib/composables/ticket-list/create-multi-select.svelte.ts\`, which holds the selected ticket IDs and nothing else. The sequencing is \`batchMutate\` in \`packages/client/src/lib/composables/ticket-list/create-bulk-actions.svelte.ts\`, which returns on the first thrown error with a count of successes. Both belong to the tickets list only, and the overview's rows carry single-ticket actions instead, covered in [Quick actions](#tickets/quick-actions). [[#client-data]]`)
};

const es_demo_narrative_topic_select_mode_body = /** @type {(inputs: Demo_Narrative_Topic_Select_Mode_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El modo de selección permite a una cuenta escoger varios tickets para que una acción se aplique a todos ellos. El control Seleccionar junto a los filtros activa el modo de selección. Una pulsación larga sobre una fila también entra en el modo de selección y escoge esa fila. [[#client-data]]
**¿Qué escribe cada acción?** Las acciones masivas son asignar un ticket a una cuenta, poner un ticket en espera, cambiar la prioridad y trasladar un ticket a otra cola. Cada acción escribe una columna en texto plano de la fila del ticket, así que el contenido del ticket sigue cifrado. Un volcado de la base de datos muestra un grupo de tickets que cambiaron de la misma manera en el mismo momento. Cada acción escribe además un evento de sistema en la línea de tiempo de ese ticket. Un cambio de prioridad o de cola que dejaría el valor igual no escribe nada. [La frontera de confianza](#deep-dive/the-trust-boundary) expone qué columnas escribe cada acción. [[#server-holds #metadata]]
**Secuenciación por ticket.** Una acción masiva envía una petición por ticket en lugar de una sola escritura ancha. La ejecución se detiene ante el primer rechazo e informa de cuántas se completaron, de modo que los tickets anteriores quedan cambiados y el resto intactos. La selección se vacía tanto si la ejecución terminó como si se detuvo. Repetir la misma acción sobre los tickets restantes completa el trabajo. [[#failure-states]]
**Comprobación de permisos.** Asignar requiere el permiso Asignar casos. Poner en espera, cambiar la prioridad y mover entre colas requieren el permiso Cambiar estado del caso. Todas las cuentas ven todas las acciones masivas. El servidor rechaza, ticket a ticket, cualquier acción cuyo permiso la cuenta no posee y cualquier ticket fuera de las colas a las que la cuenta tiene acceso. [El sistema de permisos](#deep-dive/the-permission-system) trata de dónde salen los permisos. [[#permissions]]
**Estado de selección y ejecutor por lotes.** El modo es \`createMultiSelect\`, en \`packages/client/src/lib/composables/ticket-list/create-multi-select.svelte.ts\`, que guarda los identificadores de ticket escogidos y nada más. La secuenciación es \`batchMutate\`, en \`packages/client/src/lib/composables/ticket-list/create-bulk-actions.svelte.ts\`, que retorna ante el primer error lanzado con un conteo de aciertos. Ambos son propios de la lista de tickets, y las filas del resumen llevan en su lugar las acciones de un solo ticket, tratadas en [Acciones rápidas](#tickets/quick-actions). [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_select_mode_body = /** @type {(inputs: Demo_Narrative_Topic_Select_Mode_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Sèlèct mòdè lèts àn àccòùnt pìck sèvèràl tìckèts sò ònè àctìòn àpplìès tò àll òf thèm. Thè Sèlèct còntròl bèsìdè thè fìltèrs tùrns sèlèct mòdè òn. À lòng prèss òn à ròw àlsò èntèrs sèlèct mòdè ànd sèlècts thàt ròw. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès èàch àctìòn wrìtè? •••••••••** Thè bùlk àctìòns àrè àssìgnìng à tìckèt tò àn àccòùnt, pùttìng à tìckèt òn hòld, chàngìng prìòrìty, ànd mòvìng à tìckèt tò ànòthèr qùèùè. Èàch àctìòn wrìtès à plàìntèxt còlùmn òn thè tìckèt ròw, sò tìckèt còntènt stàys èncryptèd. À dàtàbàsè dùmp shòws à gròùp òf tìckèts thàt chàngèd thè sàmè wày àt thè sàmè mòmènt. Èàch àctìòn àlsò wrìtès à systèm èvènt ìntò thàt tìckèt's tìmèlìnè. À prìòrìty òr qùèùè chàngè thàt wòùld lèàvè thè vàlùè ùnchàngèd wrìtès nòthìng. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) sèts òùt whìch còlùmns èàch àctìòn wrìtès. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pèr-tìckèt sèqùèncìng. •••••••** À bùlk àctìòn sènds ònè rèqùèst pèr tìckèt ràthèr thàn à sìnglè wìdè wrìtè. Thè rùn stòps àt thè fìrst rèfùsàl ànd rèpòrts hòw màny sùccèèdèd, sò èàrlìèr tìckèts àrè chàngèd ànd thè rèst àrè ùntòùchèd. Thè sèlèctìòn clèàrs whèthèr thè rùn fìnìshèd òr stòppèd. Rùnnìng thè sàmè àctìòn àgàìn òvèr thè rèmàìnìng tìckèts fìnìshès thè jòb. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pèrmìssìòn gàtès. ••••••** Àssìgnìng rèqùìrès thè Àssìgn càsès pèrmìssìòn. Pùttìng òn hòld, chàngìng prìòrìty, ànd mòvìng bètwèèn qùèùès rèqùìrè thè Chàngè càsè stàtùs pèrmìssìòn. Èvèry àccòùnt sèès àll thè bùlk àctìòns. Thè sèrvèr rèfùsès, tìckèt by tìckèt, àny àctìòn whòsè pèrmìssìòn thè àccòùnt làcks ànd àny tìckèt òùtsìdè thè qùèùès thè àccòùnt càn àccèss. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs whèrè pèrmìssìòns còmè fròm. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèlèctìòn stàtè ànd bàtch rùnnèr. ••••••••••** Thè mòdè ìs \`crèàtèMùltìSèlèct\` ìn \`pàckàgès/clìènt/src/lìb/còmpòsàblès/tìckèt-lìst/crèàtè-mùltì-sèlèct.svèltè.ts\`, whìch hòlds thè sèlèctèd tìckèt ÌDs ànd nòthìng èlsè. Thè sèqùèncìng ìs \`bàtchMùtàtè\` ìn \`pàckàgès/clìènt/src/lìb/còmpòsàblès/tìckèt-lìst/crèàtè-bùlk-àctìòns.svèltè.ts\`, whìch rètùrns òn thè fìrst thròwn èrròr wìth à còùnt òf sùccèssès. Bòth bèlòng tò thè tìckèts lìst ònly, ànd thè òvèrvìèw's ròws càrry sìnglè-tìckèt àctìòns ìnstèàd, còvèrèd ìn [Qùìck àctìòns](#tìckèts/qùìck-àctìòns). [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Select mode lets an account pick several tickets so one action applies to all of them. The Select control beside the filters turns select mode on. A long pre..." |
*
* @param {Demo_Narrative_Topic_Select_Mode_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_select_mode_body = /** @type {((inputs?: Demo_Narrative_Topic_Select_Mode_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Select_Mode_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_select_mode_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_select_mode_body(inputs)
	return en_demo_narrative_topic_select_mode_body(inputs)
});