/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Kanban_Board_BodyInputs */

const en_demo_narrative_topic_kanban_board_body = /** @type {(inputs: Demo_Narrative_Topic_Kanban_Board_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The Kanban board is one of the ticket list's view modes, selected from the "View as" switcher. It arranges tickets as cards in the Grid card style in columns by workflow stage. It adds actions for moving tickets through stages. [View modes](#tickets/view-modes) covers the other modes. [[#client-data]]
**Stages.** The default stages are Unassigned, Assigned, Reached Out, Meeting Scheduled, Interviewed, Request Submitted, Request Fulfilled, Continue Support, and Closed. Organizations can add, rename, reorder, and remove stages. Each stage is mapped to a trigger event chosen from a catalog. [[#metadata]]
**Auto-move.** An auto-move engine runs in the browser after the tickets are decrypted. It walks each ticket's event history and places the ticket in the highest stage whose trigger event has occurred. Auto-move only moves tickets forward. If an event is undone (for example an assignment is removed), the ticket stays in its current stage until someone moves it manually. [[#client-data]]
**Manual moves and locking.** Volunteers can move a ticket to any stage in either direction. On desktop and tablet that is drag and drop; on mobile it is a "Move to..." action on the ticket. Managers can lock a ticket to its current stage, which stops auto-move for that ticket and persists until a manager unlocks it. [[#failure-states]]
**Visibility and filtering.** Volunteers see their assigned tickets on the board. Managers see all tickets. Column headers show the stage label and a ticket count. The board shares the ticket list's filter controls, and filtering runs in the browser after decryption. [[#privacy #server-holds]]
**Layout.** Desktop and tablet show a horizontal board whose columns scroll vertically when a column holds more tickets than fit. Mobile has a tab layout and a swimlane layout. The tab layout shows a scrollable row of stage tabs with count badges and the selected stage's tickets below. The swimlane layout shows one collapsible section per stage, and the browser saves the account's layout choice. [[#client-data]]
**Privacy and encryption.** A ticket's stage and its lock flag are encrypted with that ticket's own key, the same key that protects its content. [Ticket decryption](#tickets/decryption) covers that key. The board's stage configuration (the stage labels and the trigger mapping) is encrypted under the organization key. The server stores no readable stage, lock, or configuration data, so it cannot learn where a ticket sits in the workflow. A stage such as Request Submitted would otherwise tell an attacker that a government filing is in progress for that case. [How encryption works](#deep-dive/how-encryption-works) covers the key hierarchy. [[#encryption #keys]]
**Status.** A coming-soon placeholder is shown while this feature is in development. A saved Kanban board view preference loads back unchanged when the feature ships. [[#client-data]]`)
};

const es_demo_narrative_topic_kanban_board_body = /** @type {(inputs: Demo_Narrative_Topic_Kanban_Board_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El tablero kanban es uno de los modos de vista de la lista de tickets, seleccionado desde el conmutador «Ver como». Dispone los tickets como tarjetas en el estilo de tarjeta de cuadrícula en columnas por etapa del flujo de trabajo. Añade acciones para mover tickets entre etapas. [Modos de vista](#tickets/view-modes) cubre los demás modos. [[#client-data]]
**Etapas.** Las etapas predeterminadas son Sin asignar, Asignado, Contactado, Reunión programada, Entrevistado, Solicitud enviada, Solicitud cumplida, Continuar apoyo y Cerrado. Las organizaciones pueden añadir, renombrar, reordenar y eliminar etapas. Cada etapa está vinculada a un evento disparador elegido de un catálogo. [[#metadata]]
**Movimiento automático.** Un motor de movimiento automático se ejecuta en el navegador después de descifrar los tickets. Recorre el historial de eventos de cada ticket y coloca el ticket en la etapa más alta cuyo evento disparador haya ocurrido. El movimiento automático solo avanza tickets. Si un evento se deshace (por ejemplo, se retira una asignación), el ticket permanece en su etapa actual hasta que alguien lo mueva manualmente. [[#client-data]]
**Movimientos manuales y bloqueo.** Las personas voluntarias pueden mover un ticket a cualquier etapa en cualquier dirección. En escritorio y tableta se hace con arrastrar y soltar; en móvil se hace con la acción «Mover a...» del ticket. Las personas administradoras pueden bloquear un ticket en su etapa actual, lo que detiene el movimiento automático para ese ticket y persiste hasta que una persona administradora lo desbloquee. [[#failure-states]]
**Visibilidad y filtrado.** Las personas voluntarias ven sus tickets asignados en el tablero. Las personas administradoras ven todos los tickets. Los encabezados de columna muestran la etiqueta de la etapa y un conteo de tickets. El tablero comparte los controles de filtro de la lista de tickets, y el filtrado se ejecuta en el navegador después del descifrado. [[#privacy #server-holds]]
**Disposición.** En escritorio y tableta se muestra un tablero horizontal cuyas columnas se desplazan verticalmente cuando una columna contiene más tickets de los que caben. En móvil hay una disposición de pestañas y una disposición de carriles. La disposición de pestañas muestra una fila desplazable de pestañas de etapa con insignias de conteo y los tickets de la etapa seleccionada debajo. La disposición de carriles muestra una sección plegable por etapa, y el navegador guarda la disposición elegida por la cuenta. [[#client-data]]
**Privacidad y cifrado.** La etapa de un ticket y su indicador de bloqueo se cifran con la clave propia del ticket, la misma clave que protege su contenido. [Descifrado de tickets](#tickets/decryption) cubre esa clave. La configuración de etapas del tablero (las etiquetas de etapa y el mapeo de disparadores) se cifra con la clave de la organización. El servidor no almacena datos legibles de etapa, bloqueo ni configuración, por lo que no puede saber dónde se encuentra un ticket en el flujo de trabajo. Una etapa como Solicitud enviada revelaría de otro modo a un atacante que una tramitación gubernamental está en curso para ese caso. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) cubre la jerarquía de claves. [[#encryption #keys]]
**Estado.** Se muestra un marcador de posición mientras esta funcionalidad está en desarrollo. Una preferencia de vista de tablero kanban guardada se restaura sin cambios cuando la funcionalidad se publique. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_kanban_board_body = /** @type {(inputs: Demo_Narrative_Topic_Kanban_Board_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè Kànbàn bòàrd ìs ònè òf thè tìckèt lìst's vìèw mòdès, sèlèctèd fròm thè "Vìèw às" swìtchèr. Ìt àrràngès tìckèts às càrds ìn thè Grìd càrd stylè ìn còlùmns by wòrkflòw stàgè. Ìt àdds àctìòns fòr mòvìng tìckèts thròùgh stàgès. [Vìèw mòdès](#tìckèts/vìèw-mòdès) còvèrs thè òthèr mòdès. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Stàgès. •••** Thè dèfàùlt stàgès àrè Ùnàssìgnèd, Àssìgnèd, Rèàchèd Òùt, Mèètìng Schèdùlèd, Ìntèrvìèwèd, Rèqùèst Sùbmìttèd, Rèqùèst Fùlfìllèd, Còntìnùè Sùppòrt, ànd Clòsèd. Òrgànìzàtìòns càn àdd, rènàmè, rèòrdèr, ànd rèmòvè stàgès. Èàch stàgè ìs màppèd tò à trìggèr èvènt chòsèn fròm à càtàlòg. [[#mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àùtò-mòvè. •••** Àn àùtò-mòvè èngìnè rùns ìn thè bròwsèr àftèr thè tìckèts àrè dècryptèd. Ìt wàlks èàch tìckèt's èvènt hìstòry ànd plàcès thè tìckèt ìn thè hìghèst stàgè whòsè trìggèr èvènt hàs òccùrrèd. Àùtò-mòvè ònly mòvès tìckèts fòrwàrd. Ìf àn èvènt ìs ùndònè (fòr èxàmplè àn àssìgnmènt ìs rèmòvèd), thè tìckèt stàys ìn ìts cùrrènt stàgè ùntìl sòmèònè mòvès ìt mànùàlly. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Mànùàl mòvès ànd lòckìng. ••••••••** Vòlùntèèrs càn mòvè à tìckèt tò àny stàgè ìn èìthèr dìrèctìòn. Òn dèsktòp ànd tàblèt thàt ìs dràg ànd dròp; òn mòbìlè ìt ìs à "Mòvè tò..." àctìòn òn thè tìckèt. Mànàgèrs càn lòck à tìckèt tò ìts cùrrènt stàgè, whìch stòps àùtò-mòvè fòr thàt tìckèt ànd pèrsìsts ùntìl à mànàgèr ùnlòcks ìt. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Vìsìbìlìty ànd fìltèrìng. ••••••••** Vòlùntèèrs sèè thèìr àssìgnèd tìckèts òn thè bòàrd. Mànàgèrs sèè àll tìckèts. Còlùmn hèàdèrs shòw thè stàgè làbèl ànd à tìckèt còùnt. Thè bòàrd shàrès thè tìckèt lìst's fìltèr còntròls, ànd fìltèrìng rùns ìn thè bròwsèr àftèr dècryptìòn. [[#prìvàcy #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Làyòùt. •••** Dèsktòp ànd tàblèt shòw à hòrìzòntàl bòàrd whòsè còlùmns scròll vèrtìcàlly whèn à còlùmn hòlds mòrè tìckèts thàn fìt. Mòbìlè hàs à tàb làyòùt ànd à swìmlànè làyòùt. Thè tàb làyòùt shòws à scròllàblè ròw òf stàgè tàbs wìth còùnt bàdgès ànd thè sèlèctèd stàgè's tìckèts bèlòw. Thè swìmlànè làyòùt shòws ònè còllàpsìblè sèctìòn pèr stàgè, ànd thè bròwsèr sàvès thè àccòùnt's làyòùt chòìcè. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Prìvàcy ànd èncryptìòn. •••••••** À tìckèt's stàgè ànd ìts lòck flàg àrè èncryptèd wìth thàt tìckèt's òwn kèy, thè sàmè kèy thàt pròtècts ìts còntènt. [Tìckèt dècryptìòn](#tìckèts/dècryptìòn) còvèrs thàt kèy. Thè bòàrd's stàgè cònfìgùràtìòn (thè stàgè làbèls ànd thè trìggèr màppìng) ìs èncryptèd ùndèr thè òrgànìzàtìòn kèy. Thè sèrvèr stòrès nò rèàdàblè stàgè, lòck, òr cònfìgùràtìòn dàtà, sò ìt cànnòt lèàrn whèrè à tìckèt sìts ìn thè wòrkflòw. À stàgè sùch às Rèqùèst Sùbmìttèd wòùld òthèrwìsè tèll àn àttàckèr thàt à gòvèrnmènt fìlìng ìs ìn prògrèss fòr thàt càsè. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè kèy hìèràrchy. [[#èncryptìòn #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Stàtùs. •••** À còmìng-sòòn plàcèhòldèr ìs shòwn whìlè thìs fèàtùrè ìs ìn dèvèlòpmènt. À sàvèd Kànbàn bòàrd vìèw prèfèrèncè lòàds bàck ùnchàngèd whèn thè fèàtùrè shìps. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The Kanban board is one of the ticket list's view modes, selected from the \"View as\" switcher. It arranges tickets as cards in the Grid card style in columns..." |
*
* @param {Demo_Narrative_Topic_Kanban_Board_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_kanban_board_body = /** @type {((inputs?: Demo_Narrative_Topic_Kanban_Board_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Kanban_Board_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_kanban_board_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_kanban_board_body(inputs)
	return en_demo_narrative_topic_kanban_board_body(inputs)
});