/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Portal_Composer_BodyInputs */

const en_demo_narrative_client_portal_composer_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Composer_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The client encrypts each reply in the browser before sending it. The server receives and stores ciphertext it cannot open. [[#portal #encryption]]
**Who can read a reply?** The browser makes a temporary key for the message and encrypts the text under it. It seals one copy of that key to the channel key, letting the client reread the message later, and seals a second copy to the organization's public key. Before the first member of the organization opens the reply, any member whose account holds the organization key can decrypt it. The server delivers the reply only to a user who is assigned to the ticket, watching it, or a member of its queue. The first user to open the reply re-encrypts the content under the ticket's key, and the server deletes the organization-key copy in that same write. After that point, only a user whose account holds a copy of the ticket's key can read it. [How encryption works](#deep-dive/how-encryption-works) covers the key hierarchy. [[#encryption #keys #server-holds]]
**What happens when the client sends a reply?** Sending a reply on a closed ticket reopens it. A stored reply always produces a notification to the organization. On failure the composer restores the text and reports the error for the client to retry. The composer does not indicate whether a stored reply has been read. [[#failure-states #portal]]
**Rate limits.** A conversation accepts thirty replies per hour. A reply from the organization resets that window, so an active two-sided exchange runs without interruption. A second, broader cap tallies writes per address per hour but exempts any channel where the organization has responded within the last hour. That cap bounds flooding without the server tracking which address corresponds to which conversation. A refusal states how long to wait. [[#failure-states #privacy]]
**When are replies turned off?** An organization that disables the secure link channel at the policy level keeps existing links readable but refuses new replies. The composer reports the channel is off rather than letting a send fail silently. [Channel policy](#admin-comms/channel-policy) covers the setting. [[#permissions #portal]]
**Unsent text.** A draft is held in tab memory, keyed to the channel. It persists across navigation within the session and disappears when the tab closes. Nothing unsent reaches the device's storage. [[#privacy #client-data]]
**The compose path and the wrap tables.** \`PortalComposer.svelte\` and the in-memory draft store \`packages/client/src/lib/tickets/draft-store.svelte.ts\` handle the browser side. Encryption runs in the portal worker under \`packages/client/src/lib/workers/\`. On the server, \`clientReply\` in \`packages/server/src/portal/portal-message-service.ts\` persists the follow-up row, the sealed organization-key wrap and the client's self-copy in a single transaction, and enqueues the notification in that same transaction so the two commit together. \`packages/server/src/tickets/rewrap-service.ts\` deletes the organization-key wrap after convergence. [[#portal #encryption]]`)
};

const es_demo_narrative_client_portal_composer_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Composer_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El cliente cifra cada respuesta en el navegador antes de enviarla. El servidor recibe y almacena texto cifrado que no puede abrir. [[#portal #encryption]]
**¿Quién puede leer una respuesta?** El navegador crea una clave temporal para el mensaje y cifra el texto con ella. Sella una copia de esa clave con la clave del canal, lo que permite al cliente releer el mensaje posteriormente, y sella una segunda copia con la clave pública de la organización. Antes de que el primer miembro de la organización abra la respuesta, cualquier miembro cuya cuenta tenga la clave de la organización puede descifrarla. El servidor entrega la respuesta solo a un usuario asignado al ticket, observándolo o miembro de su cola. El primer usuario que abre la respuesta vuelve a cifrar el contenido con la clave del ticket, y el servidor elimina la copia de la clave de la organización en esa misma escritura. A partir de ese momento, solo un usuario cuya cuenta tenga una copia de la clave del ticket puede leerla. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la jerarquía de claves. [[#encryption #keys #server-holds]]
**¿Qué ocurre cuando el cliente envía una respuesta?** Enviar una respuesta en un ticket cerrado lo reabre. Una respuesta almacenada siempre produce una notificación a la organización. Si el envío falla, el compositor restaura el texto e informa del error para que el cliente lo reintente. El compositor no indica si una respuesta almacenada ha sido leída. [[#failure-states #portal]]
**Límites de frecuencia.** Una conversación acepta treinta respuestas por hora. Una respuesta de la organización reinicia esa ventana, de modo que un intercambio activo entre ambas partes no se interrumpe. Un segundo límite, más amplio, contabiliza las escrituras por dirección y por hora, pero exime a todo canal donde la organización haya respondido en la última hora. Ese límite acota una inundación sin que el servidor registre a qué conversación corresponde cada dirección. El rechazo indica cuánto hay que esperar. [[#failure-states #privacy]]
**¿Cuándo se desactivan las respuestas?** Una organización que desactiva el canal de enlace seguro a nivel de política mantiene legibles los enlaces existentes pero rechaza las respuestas nuevas. El compositor informa de que el canal está desactivado en lugar de dejar que un envío falle en silencio. [Política de canales](#admin-comms/channel-policy) trata esa configuración. [[#permissions #portal]]
**Texto sin enviar.** Un borrador se guarda en la memoria de la pestaña, asociado al canal. Persiste durante la navegación dentro de la sesión y desaparece al cerrar la pestaña. Nada sin enviar llega al almacenamiento del dispositivo. [[#privacy #client-data]]
**La ruta de composición y las tablas de envolturas.** \`PortalComposer.svelte\` y el almacén de borradores en memoria \`packages/client/src/lib/tickets/draft-store.svelte.ts\` son el lado del navegador. El cifrado corre en el worker del portal, bajo \`packages/client/src/lib/workers/\`. En el servidor, \`clientReply\` en \`packages/server/src/portal/portal-message-service.ts\` persiste la fila de seguimiento, la envoltura sellada de la clave de la organización y la copia propia del cliente en una sola transacción, y encola la notificación en esa misma transacción para que ambas se confirmen juntas. \`packages/server/src/tickets/rewrap-service.ts\` elimina la envoltura de la clave de la organización tras la convergencia. [[#portal #encryption]]`)
};

const en_xa2_demo_narrative_client_portal_composer_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Composer_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè clìènt èncrypts èàch rèply ìn thè bròwsèr bèfòrè sèndìng ìt. Thè sèrvèr rècèìvès ànd stòrès cìphèrtèxt ìt cànnòt òpèn. [[#pòrtàl #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••**Whò càn rèàd à rèply? •••••••** Thè bròwsèr màkès à tèmpòràry kèy fòr thè mèssàgè ànd èncrypts thè tèxt ùndèr ìt. Ìt sèàls ònè còpy òf thàt kèy tò thè chànnèl kèy, lèttìng thè clìènt rèrèàd thè mèssàgè làtèr, ànd sèàls à sècònd còpy tò thè òrgànìzàtìòn's pùblìc kèy. Bèfòrè thè fìrst mèmbèr òf thè òrgànìzàtìòn òpèns thè rèply, àny mèmbèr whòsè àccòùnt hòlds thè òrgànìzàtìòn kèy càn dècrypt ìt. Thè sèrvèr dèlìvèrs thè rèply ònly tò à ùsèr whò ìs àssìgnèd tò thè tìckèt, wàtchìng ìt, òr à mèmbèr òf ìts qùèùè. Thè fìrst ùsèr tò òpèn thè rèply rè-èncrypts thè còntènt ùndèr thè tìckèt's kèy, ànd thè sèrvèr dèlètès thè òrgànìzàtìòn-kèy còpy ìn thàt sàmè wrìtè. Àftèr thàt pòìnt, ònly à ùsèr whòsè àccòùnt hòlds à còpy òf thè tìckèt's kèy càn rèàd ìt. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè kèy hìèràrchy. [[#èncryptìòn #kèys #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn thè clìènt sènds à rèply? •••••••••••••** Sèndìng à rèply òn à clòsèd tìckèt rèòpèns ìt. À stòrèd rèply àlwàys pròdùcès à nòtìfìcàtìòn tò thè òrgànìzàtìòn. Òn fàìlùrè thè còmpòsèr rèstòrès thè tèxt ànd rèpòrts thè èrròr fòr thè clìènt tò rètry. Thè còmpòsèr dòès nòt ìndìcàtè whèthèr à stòrèd rèply hàs bèèn rèàd. [[#fàìlùrè-stàtès #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ràtè lìmìts. ••••** À cònvèrsàtìòn àccèpts thìrty rèplìès pèr hòùr. À rèply fròm thè òrgànìzàtìòn rèsèts thàt wìndòw, sò àn àctìvè twò-sìdèd èxchàngè rùns wìthòùt ìntèrrùptìòn. À sècònd, bròàdèr càp tàllìès wrìtès pèr àddrèss pèr hòùr bùt èxèmpts àny chànnèl whèrè thè òrgànìzàtìòn hàs rèspòndèd wìthìn thè làst hòùr. Thàt càp bòùnds flòòdìng wìthòùt thè sèrvèr tràckìng whìch àddrèss còrrèspònds tò whìch cònvèrsàtìòn. À rèfùsàl stàtès hòw lòng tò wàìt. [[#fàìlùrè-stàtès #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn àrè rèplìès tùrnèd òff? •••••••••** Àn òrgànìzàtìòn thàt dìsàblès thè sècùrè lìnk chànnèl àt thè pòlìcy lèvèl kèèps èxìstìng lìnks rèàdàblè bùt rèfùsès nèw rèplìès. Thè còmpòsèr rèpòrts thè chànnèl ìs òff ràthèr thàn lèttìng à sènd fàìl sìlèntly. [Chànnèl pòlìcy](#àdmìn-còmms/chànnèl-pòlìcy) còvèrs thè sèttìng. [[#pèrmìssìòns #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ùnsènt tèxt. ••••** À dràft ìs hèld ìn tàb mèmòry, kèyèd tò thè chànnèl. Ìt pèrsìsts àcròss nàvìgàtìòn wìthìn thè sèssìòn ànd dìsàppèàrs whèn thè tàb clòsès. Nòthìng ùnsènt rèàchès thè dèvìcè's stòràgè. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còmpòsè pàth ànd thè wràp tàblès. ••••••••••••** \`PòrtàlCòmpòsèr.svèltè\` ànd thè ìn-mèmòry dràft stòrè \`pàckàgès/clìènt/src/lìb/tìckèts/dràft-stòrè.svèltè.ts\` hàndlè thè bròwsèr sìdè. Èncryptìòn rùns ìn thè pòrtàl wòrkèr ùndèr \`pàckàgès/clìènt/src/lìb/wòrkèrs/\`. Òn thè sèrvèr, \`clìèntRèply\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/pòrtàl-mèssàgè-sèrvìcè.ts\` pèrsìsts thè fòllòw-ùp ròw, thè sèàlèd òrgànìzàtìòn-kèy wràp ànd thè clìènt's sèlf-còpy ìn à sìnglè trànsàctìòn, ànd ènqùèùès thè nòtìfìcàtìòn ìn thàt sàmè trànsàctìòn sò thè twò còmmìt tògèthèr. \`pàckàgès/sèrvèr/src/tìckèts/rèwràp-sèrvìcè.ts\` dèlètès thè òrgànìzàtìòn-kèy wràp àftèr cònvèrgèncè. [[#pòrtàl #èncryptìòn]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The client encrypts each reply in the browser before sending it. The server receives and stores ciphertext it cannot open. [[#portal #encryption]] **Who can ..." |
*
* @param {Demo_Narrative_Client_Portal_Composer_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_portal_composer_body = /** @type {((inputs?: Demo_Narrative_Client_Portal_Composer_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Portal_Composer_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_portal_composer_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_portal_composer_body(inputs)
	return en_demo_narrative_client_portal_composer_body(inputs)
});