/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Library_Categories_BodyInputs */

const en_demo_narrative_topic_library_categories_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Categories_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Knowledge base articles are grouped by category, one category per article. The organization defines whatever categories it needs. Creating, renaming, reordering or deleting a category requires the Manage knowledge base categories permission. Listing them requires the View knowledge base permission. [[#permissions]]
**What does a category row hold?** Name and optional description are sealed with the organization key and decrypted in the browser. Sort order, creation timestamp and last-edit timestamp are stored as plaintext, and the sort order carries a unique constraint per organization. A seized database reveals the number of categories, their ordering, each one's age, and how many articles are filed under each, but no name or description. [How encryption works](#deep-dive/how-encryption-works) covers the organization key. [[#encryption #server-holds #metadata]]
**What happens when a category still has articles?** The server and the browser both refuse to remove a category that still has articles under it, so a stale page or a modified client cannot bypass the guard. The browser checks the loaded article count before sending the request. Any failed delete, regardless of cause, reports the same message asking the account to move or remove the articles first. Reassigning them to another category is the prerequisite. [Browsing articles](#library/browse) covers the article list. [[#failure-states]]
**The category service and its migrations.** The five category operations live in \`createKBCategoryService\` in \`packages/server/src/kb/service.ts\`. A foreign key with restrict on \`kb_items.category_id\` prevents the row from being removed while any article references it. Reordering wraps all affected rows in a single transaction, setting each to a negative sort order first and then applying the intended values, which prevents the unique constraint from rejecting an intermediate state. Migration \`037_create_kb_categories.ts\` created the table. \`046_encrypt_kb_category_names.ts\` replaced the plaintext name with an encrypted column and introduced the sort order column. [[#encryption]]`)
};

const es_demo_narrative_topic_library_categories_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Categories_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los artículos de la base de conocimiento se agrupan por categoría, una categoría por artículo. La organización define las categorías que necesita. Crear, renombrar, reordenar o eliminar una categoría requiere el permiso Gestionar categorías de la base de conocimiento. Listarlas requiere el permiso Ver base de conocimiento. [[#permissions]]
**¿Qué contiene una fila de categoría?** El nombre y la descripción opcional están sellados con la clave de organización y se descifran en el navegador. El orden, la marca de tiempo de creación y la de última edición se almacenan como texto plano, y el orden lleva una restricción de unicidad por organización. Una base de datos incautada revela la cantidad de categorías, su ordenamiento, la antigüedad de cada una y cuántos artículos hay archivados en cada una, pero ningún nombre ni descripción. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la clave de organización. [[#encryption #server-holds #metadata]]
**¿Qué pasa cuando una categoría todavía tiene artículos?** El servidor y el navegador rechazan eliminar una categoría que aún tiene artículos asociados, de modo que una página desactualizada o un cliente modificado no puede saltarse la protección. El navegador comprueba el conteo de artículos cargado antes de enviar la solicitud. Cualquier eliminación fallida, sin importar la causa, muestra el mismo mensaje pidiendo a la cuenta que mueva o elimine los artículos primero. Reasignarlos a otra categoría es el prerrequisito. [Navegar artículos](#library/browse) trata la lista de artículos. [[#failure-states]]
**El servicio de categorías y sus migraciones.** Las cinco operaciones de categoría viven en \`createKBCategoryService\` en \`packages/server/src/kb/service.ts\`. Una clave foránea con restrict en \`kb_items.category_id\` impide eliminar la fila mientras algún artículo la referencie. La reordenación envuelve todas las filas afectadas en una sola transacción, asignando a cada una un orden negativo primero y luego aplicando los valores definitivos, lo que evita que la restricción de unicidad rechace un estado intermedio. La migración \`037_create_kb_categories.ts\` creó la tabla. \`046_encrypt_kb_category_names.ts\` reemplazó el nombre en texto plano por una columna cifrada e introdujo la columna de orden. [[#encryption]]`)
};

const en_xa2_demo_narrative_topic_library_categories_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Categories_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Knòwlèdgè bàsè àrtìclès àrè gròùpèd by càtègòry, ònè càtègòry pèr àrtìclè. Thè òrgànìzàtìòn dèfìnès whàtèvèr càtègòrìès ìt nèèds. Crèàtìng, rènàmìng, rèòrdèrìng òr dèlètìng à càtègòry rèqùìrès thè Mànàgè knòwlèdgè bàsè càtègòrìès pèrmìssìòn. Lìstìng thèm rèqùìrès thè Vìèw knòwlèdgè bàsè pèrmìssìòn. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à càtègòry ròw hòld? •••••••••** Nàmè ànd òptìònàl dèscrìptìòn àrè sèàlèd wìth thè òrgànìzàtìòn kèy ànd dècryptèd ìn thè bròwsèr. Sòrt òrdèr, crèàtìòn tìmèstàmp ànd làst-èdìt tìmèstàmp àrè stòrèd às plàìntèxt, ànd thè sòrt òrdèr càrrìès à ùnìqùè cònstràìnt pèr òrgànìzàtìòn. À sèìzèd dàtàbàsè rèvèàls thè nùmbèr òf càtègòrìès, thèìr òrdèrìng, èàch ònè's àgè, ànd hòw màny àrtìclès àrè fìlèd ùndèr èàch, bùt nò nàmè òr dèscrìptìòn. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè òrgànìzàtìòn kèy. [[#èncryptìòn #sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn à càtègòry stìll hàs àrtìclès? •••••••••••••••** Thè sèrvèr ànd thè bròwsèr bòth rèfùsè tò rèmòvè à càtègòry thàt stìll hàs àrtìclès ùndèr ìt, sò à stàlè pàgè òr à mòdìfìèd clìènt cànnòt bypàss thè gùàrd. Thè bròwsèr chècks thè lòàdèd àrtìclè còùnt bèfòrè sèndìng thè rèqùèst. Àny fàìlèd dèlètè, règàrdlèss òf càùsè, rèpòrts thè sàmè mèssàgè àskìng thè àccòùnt tò mòvè òr rèmòvè thè àrtìclès fìrst. Rèàssìgnìng thèm tò ànòthèr càtègòry ìs thè prèrèqùìsìtè. [Bròwsìng àrtìclès](#lìbràry/bròwsè) còvèrs thè àrtìclè lìst. [[#fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè càtègòry sèrvìcè ànd ìts mìgràtìòns. ••••••••••••** Thè fìvè càtègòry òpèràtìòns lìvè ìn \`crèàtèKBCàtègòrySèrvìcè\` ìn \`pàckàgès/sèrvèr/src/kb/sèrvìcè.ts\`. À fòrèìgn kèy wìth rèstrìct òn \`kb_ìtèms.càtègòry_ìd\` prèvènts thè ròw fròm bèìng rèmòvèd whìlè àny àrtìclè rèfèrèncès ìt. Rèòrdèrìng wràps àll àffèctèd ròws ìn à sìnglè trànsàctìòn, sèttìng èàch tò à nègàtìvè sòrt òrdèr fìrst ànd thèn àpplyìng thè ìntèndèd vàlùès, whìch prèvènts thè ùnìqùè cònstràìnt fròm rèjèctìng àn ìntèrmèdìàtè stàtè. Mìgràtìòn \`037_crèàtè_kb_càtègòrìès.ts\` crèàtèd thè tàblè. \`046_èncrypt_kb_càtègòry_nàmès.ts\` rèplàcèd thè plàìntèxt nàmè wìth àn èncryptèd còlùmn ànd ìntròdùcèd thè sòrt òrdèr còlùmn. [[#èncryptìòn]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Knowledge base articles are grouped by category, one category per article. The organization defines whatever categories it needs. Creating, renaming, reorder..." |
*
* @param {Demo_Narrative_Topic_Library_Categories_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_library_categories_body = /** @type {((inputs?: Demo_Narrative_Topic_Library_Categories_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Library_Categories_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_library_categories_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_library_categories_body(inputs)
	return en_demo_narrative_topic_library_categories_body(inputs)
});