/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Twofa_Totp_BodyInputs */

const en_demo_narrative_topic_twofa_totp_body = /** @type {(inputs: Demo_Narrative_Topic_Twofa_Totp_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A six digit code generated by an authenticator app on the volunteer's device.
**Compatible apps.** Standard TOTP apps all work, and enrollment is done by scanning a QR code that shares a secret between the app and CARE-Y.
**How it works.** After enrollment, the authenticator generates a new code every thirty seconds using that shared secret. Generating the code requires no network connection, which makes this method reliable even with poor connectivity.
**Time drift.** CARE-Y accepts the current code and a small window around it to account for minor time differences between the device and the server. Each code can only be used once.`)
};

const es_demo_narrative_topic_twofa_totp_body = /** @type {(inputs: Demo_Narrative_Topic_Twofa_Totp_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un código de seis dígitos generado por una aplicación de autenticación en el dispositivo del voluntario.
**Aplicaciones compatibles.** Todas las aplicaciones TOTP estándar funcionan, y el registro se realiza escaneando un código QR que comparte un secreto entre la aplicación y CARE-Y.
**Cómo funciona.** Después del registro, el autenticador genera un nuevo código cada treinta segundos usando ese secreto compartido. Generar el código no requiere conexión a internet, lo que hace este método fiable incluso con mala conectividad.
**Desfase horario.** CARE-Y acepta el código actual y una pequeña ventana alrededor para compensar pequeñas diferencias de tiempo entre el dispositivo y el servidor. Cada código solo puede usarse una vez.`)
};

/**
* | output |
* | --- |
* | "A six digit code generated by an authenticator app on the volunteer's device. **Compatible apps.** Standard TOTP apps all work, and enrollment is done by sca..." |
*
* @param {Demo_Narrative_Topic_Twofa_Totp_BodyInputs} inputs
* @param {{ locale?: "en" | "es" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_twofa_totp_body = /** @type {((inputs?: Demo_Narrative_Topic_Twofa_Totp_BodyInputs, options?: { locale?: "en" | "es" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Twofa_Totp_BodyInputs, { locale?: "en" | "es" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "en") return en_demo_narrative_topic_twofa_totp_body(inputs)
	return es_demo_narrative_topic_twofa_totp_body(inputs)
});