/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Privacy_Notice_BodyInputs */

const en_demo_narrative_client_privacy_notice_body = /** @type {(inputs: Demo_Narrative_Client_Privacy_Notice_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The privacy notice is a fixed page linked from the drawer on every client page. It states who collects a submission, what data is gathered, who can read it, how long it is kept, what rights the visitor holds, and what cookies the site uses. Only the organization's name changes between deployments. [[#privacy #client-data]]
**What does the notice promise about reading a submission?** The notice says that volunteers open submissions on their own devices, that the organization key gives access until someone first takes the case, and that afterward only the people working on it can read it. Before that first open, any member holding the organization key can unseal the submission, and the server restricts it to members of the destination queue. The intake form states the same claim in the same wording. [How the visitor is protected](#client-intake/how-protected) covers the encryption behind that claim. [[#keys #privacy]]
**What does the notice say about the telephony provider?** The provider is named along with the country it operates in. The notice states the provider's own retention terms for the telephony provider the deployment uses. The notice also states that CARE-Y asks the provider to delete each call, message, and recording log after processing. A cross-border transfer disclosure names the contractual basis for the transfer. [The telephony relay](#deep-dive/the-telephony-relay) covers what exits the encryption boundary on a call. [[#telephony #trust-boundary]]
**What does the notice say about retention?** Encrypted data is described as kept while the case is open plus any retention period the organization chooses. Automatic deletion is off until an administrator enables it, so closed cases are kept indefinitely by default. The notice states that default. [Data retention](#deep-dive/data-retention) covers the deletion order, and [Retention policy](#admin-org/retention) covers where the window is configured. [[#retention #server-holds]]
**What rights does the notice offer?** The notice lists the rights the organization can fulfil. The visitor is told to quote the reference code returned after submission. The organization stores a generated alias, not a searchable name, and without the code it has no way to locate the record. [Submission](#client-intake/submit) covers where the code originates. [[#client-data #metadata]]
**What does the notice say about cookies?** Only session and security cookies required for the form are set, and the notice confirms none of them track the visitor. Outside the form itself, the language picker stores a preference cookie and the color-scheme toggle persists its choice in local storage. [The intake page](#client-intake/form) covers what traces a visit leaves on the device. [[#privacy #client-data]]
**The page component and its one substitution.** The page is \`packages/client/src/routes/(client)/intake/privacy/+page.svelte\`, rendering the \`intake_privacy_*\` messages and embedding \`intake_retention_disclosure\` within the retention section. The organization's name comes from the public branding response or from a value injected into the page at build time, stored as plaintext because branding is not a secret. No key material is present on the page. A language switch re-renders the entire notice in the new language without reloading. [[#server-holds #privacy]]`)
};

const es_demo_narrative_client_privacy_notice_body = /** @type {(inputs: Demo_Narrative_Client_Privacy_Notice_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El aviso de privacidad es una página fija enlazada desde el panel lateral en todas las páginas del cliente. Indica quién recoge un envío, qué datos se recopilan, quién puede leerlos, cuánto tiempo se conservan, qué derechos tiene el visitante y qué cookies usa el sitio. Solo el nombre de la organización cambia entre despliegues. [[#privacy #client-data]]
**¿Qué promete el aviso sobre la lectura de un envío?** El aviso dice que las personas voluntarias abren los envíos en sus propios dispositivos, que la clave de la organización da acceso hasta que alguien toma el caso por primera vez y que a partir de ese momento solo quienes lo trabajan pueden leerlo. Antes de esa primera apertura, cualquier miembro que tenga la clave de la organización puede abrir el envío, y el servidor lo restringe a los miembros de la cola de destino. El formulario de admisión enuncia la misma afirmación con la misma redacción. [Cómo se protege al visitante](#client-intake/how-protected) trata el cifrado detrás de esa afirmación. [[#keys #privacy]]
**¿Qué dice el aviso sobre el proveedor de telefonía?** Se nombra al proveedor junto con el país en el que opera. El aviso indica los plazos de retención propios del proveedor de telefonía que usa el despliegue. El aviso también indica que CARE-Y pide al proveedor que elimine cada registro de llamada, mensaje y grabación tras el procesamiento. Una divulgación de transferencia internacional nombra la base contractual de la transferencia. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que sale de la frontera de cifrado en una llamada. [[#telephony #trust-boundary]]
**¿Qué dice el aviso sobre la retención?** Los datos cifrados se describen como conservados mientras el caso esté abierto más cualquier periodo de retención que la organización elija. La eliminación automática está desactivada hasta que la persona administradora la active, así que por defecto los casos cerrados se conservan indefinidamente. El aviso indica ese valor predeterminado. [Retención de datos](#deep-dive/data-retention) trata el orden de eliminación, y [Política de retención](#admin-org/retention) trata dónde se configura la ventana. [[#retention #server-holds]]
**¿Qué derechos ofrece el aviso?** El aviso enumera los derechos que la organización puede cumplir. Se indica al visitante que cite el código de referencia devuelto tras el envío. La organización almacena un alias generado, no un nombre buscable, y sin el código no tiene forma de localizar el registro. [Envío](#client-intake/submit) trata de dónde proviene el código. [[#client-data #metadata]]
**¿Qué dice el aviso sobre las cookies?** Solo se establecen cookies de sesión y seguridad necesarias para el formulario, y el aviso confirma que ninguna rastrea al visitante. Fuera del formulario, el selector de idioma almacena una cookie de preferencia y el conmutador de esquema de color guarda su elección en el almacenamiento local. [La página de admisión](#client-intake/form) trata los rastros que deja una visita en el dispositivo. [[#privacy #client-data]]
**El componente de página y su única sustitución.** La página es \`packages/client/src/routes/(client)/intake/privacy/+page.svelte\`, que muestra los mensajes \`intake_privacy_*\` e inserta \`intake_retention_disclosure\` dentro de la sección de retención. El nombre de la organización proviene de la respuesta de identidad pública o de un valor inyectado en la página en tiempo de compilación, almacenado como texto plano porque la identidad visual no es secreta. No hay material de claves en la página. Un cambio de idioma vuelve a representar el aviso completo en el nuevo idioma sin recargar. [[#server-holds #privacy]]`)
};

const en_xa2_demo_narrative_client_privacy_notice_body = /** @type {(inputs: Demo_Narrative_Client_Privacy_Notice_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè prìvàcy nòtìcè ìs à fìxèd pàgè lìnkèd fròm thè dràwèr òn èvèry clìènt pàgè. Ìt stàtès whò còllècts à sùbmìssìòn, whàt dàtà ìs gàthèrèd, whò càn rèàd ìt, hòw lòng ìt ìs kèpt, whàt rìghts thè vìsìtòr hòlds, ànd whàt còòkìès thè sìtè ùsès. Ònly thè òrgànìzàtìòn's nàmè chàngès bètwèèn dèplòymènts. [[#prìvàcy #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè nòtìcè pròmìsè àbòùt rèàdìng à sùbmìssìòn? •••••••••••••••••** Thè nòtìcè sàys thàt vòlùntèèrs òpèn sùbmìssìòns òn thèìr òwn dèvìcès, thàt thè òrgànìzàtìòn kèy gìvès àccèss ùntìl sòmèònè fìrst tàkès thè càsè, ànd thàt àftèrwàrd ònly thè pèòplè wòrkìng òn ìt càn rèàd ìt. Bèfòrè thàt fìrst òpèn, àny mèmbèr hòldìng thè òrgànìzàtìòn kèy càn ùnsèàl thè sùbmìssìòn, ànd thè sèrvèr rèstrìcts ìt tò mèmbèrs òf thè dèstìnàtìòn qùèùè. Thè ìntàkè fòrm stàtès thè sàmè clàìm ìn thè sàmè wòrdìng. [Hòw thè vìsìtòr ìs pròtèctèd](#clìènt-ìntàkè/hòw-pròtèctèd) còvèrs thè èncryptìòn bèhìnd thàt clàìm. [[#kèys #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè nòtìcè sày àbòùt thè tèlèphòny pròvìdèr? •••••••••••••••••** Thè pròvìdèr ìs nàmèd àlòng wìth thè còùntry ìt òpèràtès ìn. Thè nòtìcè stàtès thè pròvìdèr's òwn rètèntìòn tèrms fòr thè tèlèphòny pròvìdèr thè dèplòymènt ùsès. Thè nòtìcè àlsò stàtès thàt CÀRÈ-Y àsks thè pròvìdèr tò dèlètè èàch càll, mèssàgè, ànd rècòrdìng lòg àftèr pròcèssìng. À cròss-bòrdèr trànsfèr dìsclòsùrè nàmès thè còntràctùàl bàsìs fòr thè trànsfèr. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt èxìts thè èncryptìòn bòùndàry òn à càll. [[#tèlèphòny #trùst-bòùndàry]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè nòtìcè sày àbòùt rètèntìòn? •••••••••••••** Èncryptèd dàtà ìs dèscrìbèd às kèpt whìlè thè càsè ìs òpèn plùs àny rètèntìòn pèrìòd thè òrgànìzàtìòn chòòsès. Àùtòmàtìc dèlètìòn ìs òff ùntìl àn àdmìnìstràtòr ènàblès ìt, sò clòsèd càsès àrè kèpt ìndèfìnìtèly by dèfàùlt. Thè nòtìcè stàtès thàt dèfàùlt. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thè dèlètìòn òrdèr, ànd [Rètèntìòn pòlìcy](#àdmìn-òrg/rètèntìòn) còvèrs whèrè thè wìndòw ìs cònfìgùrèd. [[#rètèntìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt rìghts dòès thè nòtìcè òffèr? •••••••••••** Thè nòtìcè lìsts thè rìghts thè òrgànìzàtìòn càn fùlfìl. Thè vìsìtòr ìs tòld tò qùòtè thè rèfèrèncè còdè rètùrnèd àftèr sùbmìssìòn. Thè òrgànìzàtìòn stòrès à gènèràtèd àlìàs, nòt à sèàrchàblè nàmè, ànd wìthòùt thè còdè ìt hàs nò wày tò lòcàtè thè rècòrd. [Sùbmìssìòn](#clìènt-ìntàkè/sùbmìt) còvèrs whèrè thè còdè òrìgìnàtès. [[#clìènt-dàtà #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè nòtìcè sày àbòùt còòkìès? ••••••••••••** Ònly sèssìòn ànd sècùrìty còòkìès rèqùìrèd fòr thè fòrm àrè sèt, ànd thè nòtìcè cònfìrms nònè òf thèm tràck thè vìsìtòr. Òùtsìdè thè fòrm ìtsèlf, thè làngùàgè pìckèr stòrès à prèfèrèncè còòkìè ànd thè còlòr-schèmè tògglè pèrsìsts ìts chòìcè ìn lòcàl stòràgè. [Thè ìntàkè pàgè](#clìènt-ìntàkè/fòrm) còvèrs whàt tràcès à vìsìt lèàvès òn thè dèvìcè. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pàgè còmpònènt ànd ìts ònè sùbstìtùtìòn. ••••••••••••••** Thè pàgè ìs \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/prìvàcy/+pàgè.svèltè\`, rèndèrìng thè \`ìntàkè_prìvàcy_*\` mèssàgès ànd èmbèddìng \`ìntàkè_rètèntìòn_dìsclòsùrè\` wìthìn thè rètèntìòn sèctìòn. Thè òrgànìzàtìòn's nàmè còmès fròm thè pùblìc bràndìng rèspònsè òr fròm à vàlùè ìnjèctèd ìntò thè pàgè àt bùìld tìmè, stòrèd às plàìntèxt bècàùsè bràndìng ìs nòt à sècrèt. Nò kèy màtèrìàl ìs prèsènt òn thè pàgè. À làngùàgè swìtch rè-rèndèrs thè èntìrè nòtìcè ìn thè nèw làngùàgè wìthòùt rèlòàdìng. [[#sèrvèr-hòlds #prìvàcy]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The privacy notice is a fixed page linked from the drawer on every client page. It states who collects a submission, what data is gathered, who can read it, ..." |
*
* @param {Demo_Narrative_Client_Privacy_Notice_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_privacy_notice_body = /** @type {((inputs?: Demo_Narrative_Client_Privacy_Notice_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Privacy_Notice_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_privacy_notice_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_privacy_notice_body(inputs)
	return en_demo_narrative_client_privacy_notice_body(inputs)
});