/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_New_Ticket_BodyInputs */

const en_demo_narrative_topic_new_ticket_body = /** @type {(inputs: Demo_Narrative_Topic_New_Ticket_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Creating a ticket seals its title and description in the browser under a ticket key minted there. The server files the ciphertext and never holds the key. [[#encryption #keys]]
**What does the form ask for?** A title, a queue and a client are required. The description is optional. The priority starts at normal. [[#client-data]]
**One ticket per client at a time.** A client has at most one open ticket. A creation for a client that already has one is refused and the form sends the reader to the existing ticket. That check runs when a looked-up phone number resolves to a client during selection and again before anything is encrypted. A closed ticket is reopened under its existing identifier, keeping its key generation and re-wrapping the ticket key for the destination queue. A new client gets a fresh identifier. The identifier is bound into the encryption as associated data. Content sealed against the wrong identifier would not decrypt. [Closing and reopening](#ticket-detail/close-reopen) covers the reopened path. [[#failure-states #keys]]
**Who can read it afterwards?** The ticket key is wrapped for the creator and for each active member of the destination queue. The creator is added as a watcher. A member who has not finished setting up their account has no public key yet, so nothing is wrapped for that member. A wrap set with no recipients is refused. A member who joins the queue later holds no wrap and receives one through the backfill a teammate's browser runs. [Ticket decryption](#tickets/decryption) covers both paths. [[#keys #permissions]]
**Permission gates.** Creating a ticket requires permission to open cases. The lookup that resolves the target ticket requires permission to view cases. The server refuses a queue that is absent or inactive, and a client record that is absent or already merged into another. [[#permissions]]
**What does the new row hold in plaintext?** The priority, the status, the key generation and the creation time are stored as readable plaintext. The queue and the client are stored as opaque references. A dump can tell that two tickets sit in the same queue or concern the same client, but cannot tell which queue or which client. The title and the description are ciphertext columns. [The trust boundary](#deep-dive/the-trust-boundary) sets out the full row. [[#server-holds #metadata]]
**The form and the creation service.** The form is \`NewTicketForm.svelte\` in \`packages/client/src/lib/components/tickets/\`. It fetches the destination queue's member keys and asks the crypto worker for one sealed copy of the ticket key per recipient. The server side is \`create\` in \`packages/server/src/tickets/ticket-service.ts\`. The row and its wraps are written in one transaction. [[#encryption]]`)
};

const es_demo_narrative_topic_new_ticket_body = /** @type {(inputs: Demo_Narrative_Topic_New_Ticket_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Crear un ticket cifra su título y descripción en el navegador con una clave de ticket generada allí. El servidor almacena el texto cifrado y nunca posee la clave. [[#encryption #keys]]
**¿Qué pide el formulario?** Se requieren un título, una cola y un cliente. La descripción es opcional. La prioridad comienza en normal. [[#client-data]]
**Un ticket por cliente a la vez.** Un cliente tiene como máximo un ticket abierto. Una creación para un cliente que ya tiene uno es rechazada y el formulario envía al lector al ticket existente. Esa verificación se ejecuta cuando un número de teléfono buscado corresponde a un cliente durante la selección y de nuevo antes de cifrar nada. Un ticket cerrado se reabre con su identificador existente, conservando su generación de clave y re-envolviendo la clave del ticket para la cola de destino. Un cliente nuevo recibe un identificador nuevo. El identificador se vincula al cifrado como dato asociado. El contenido cifrado contra el identificador incorrecto no se podría descifrar. [Cierre y reapertura](#ticket-detail/close-reopen) trata la ruta de reapertura. [[#failure-states #keys]]
**¿Quién puede leerlo después?** La clave de ticket se envuelve para la persona creadora y para cada miembro activo de la cola de destino. La persona creadora se añade como observadora. Un miembro que no ha terminado de configurar su cuenta no tiene clave pública aún, así que nada se envuelve para ese miembro. Un conjunto de envolturas sin destinatarios se rechaza. Un miembro que se une a la cola después no tiene envoltura y recibe una a través del rellenado retroactivo que ejecuta el navegador de un compañero. [Descifrado de tickets](#tickets/decryption) trata ambas rutas. [[#keys #permissions]]
**Puertas de permiso.** Crear un ticket requiere permiso para abrir casos. La consulta que resuelve el ticket destino requiere permiso para ver casos. El servidor rechaza una cola ausente o inactiva, y un registro de cliente ausente o ya fusionado con otro. [[#permissions]]
**¿Qué guarda la fila nueva en texto plano?** La prioridad, el estado, la generación de clave y la hora de creación se almacenan como texto plano legible. La cola y el cliente se almacenan como referencias opacas. Un volcado puede determinar que dos tickets están en la misma cola o conciernen al mismo cliente, pero no puede determinar cuál cola ni cuál cliente. El título y la descripción son columnas cifradas. [La frontera de confianza](#deep-dive/the-trust-boundary) presenta la fila completa. [[#server-holds #metadata]]
**El formulario y el servicio de creación.** El formulario es \`NewTicketForm.svelte\` en \`packages/client/src/lib/components/tickets/\`. Obtiene las claves de los miembros de la cola de destino y solicita al crypto worker una copia cifrada de la clave de ticket por destinatario. El lado del servidor es \`create\` en \`packages/server/src/tickets/ticket-service.ts\`. La fila y sus envolturas se escriben en una sola transacción. [[#encryption]]`)
};

const en_xa2_demo_narrative_topic_new_ticket_body = /** @type {(inputs: Demo_Narrative_Topic_New_Ticket_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Crèàtìng à tìckèt sèàls ìts tìtlè ànd dèscrìptìòn ìn thè bròwsèr ùndèr à tìckèt kèy mìntèd thèrè. Thè sèrvèr fìlès thè cìphèrtèxt ànd nèvèr hòlds thè kèy. [[#èncryptìòn #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè fòrm àsk fòr? •••••••••** À tìtlè, à qùèùè ànd à clìènt àrè rèqùìrèd. Thè dèscrìptìòn ìs òptìònàl. Thè prìòrìty stàrts àt nòrmàl. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••**Ònè tìckèt pèr clìènt àt à tìmè. ••••••••••** À clìènt hàs àt mòst ònè òpèn tìckèt. À crèàtìòn fòr à clìènt thàt àlrèàdy hàs ònè ìs rèfùsèd ànd thè fòrm sènds thè rèàdèr tò thè èxìstìng tìckèt. Thàt chèck rùns whèn à lòòkèd-ùp phònè nùmbèr rèsòlvès tò à clìènt dùrìng sèlèctìòn ànd àgàìn bèfòrè ànythìng ìs èncryptèd. À clòsèd tìckèt ìs rèòpènèd ùndèr ìts èxìstìng ìdèntìfìèr, kèèpìng ìts kèy gènèràtìòn ànd rè-wràppìng thè tìckèt kèy fòr thè dèstìnàtìòn qùèùè. À nèw clìènt gèts à frèsh ìdèntìfìèr. Thè ìdèntìfìèr ìs bòùnd ìntò thè èncryptìòn às àssòcìàtèd dàtà. Còntènt sèàlèd àgàìnst thè wròng ìdèntìfìèr wòùld nòt dècrypt. [Clòsìng ànd rèòpènìng](#tìckèt-dètàìl/clòsè-rèòpèn) còvèrs thè rèòpènèd pàth. [[#fàìlùrè-stàtès #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn rèàd ìt àftèrwàrds? •••••••••** Thè tìckèt kèy ìs wràppèd fòr thè crèàtòr ànd fòr èàch àctìvè mèmbèr òf thè dèstìnàtìòn qùèùè. Thè crèàtòr ìs àddèd às à wàtchèr. À mèmbèr whò hàs nòt fìnìshèd sèttìng ùp thèìr àccòùnt hàs nò pùblìc kèy yèt, sò nòthìng ìs wràppèd fòr thàt mèmbèr. À wràp sèt wìth nò rècìpìènts ìs rèfùsèd. À mèmbèr whò jòìns thè qùèùè làtèr hòlds nò wràp ànd rècèìvès ònè thròùgh thè bàckfìll à tèàmmàtè's bròwsèr rùns. [Tìckèt dècryptìòn](#tìckèts/dècryptìòn) còvèrs bòth pàths. [[#kèys #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pèrmìssìòn gàtès. ••••••** Crèàtìng à tìckèt rèqùìrès pèrmìssìòn tò òpèn càsès. Thè lòòkùp thàt rèsòlvès thè tàrgèt tìckèt rèqùìrès pèrmìssìòn tò vìèw càsès. Thè sèrvèr rèfùsès à qùèùè thàt ìs àbsènt òr ìnàctìvè, ànd à clìènt rècòrd thàt ìs àbsènt òr àlrèàdy mèrgèd ìntò ànòthèr. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè nèw ròw hòld ìn plàìntèxt? ••••••••••••** Thè prìòrìty, thè stàtùs, thè kèy gènèràtìòn ànd thè crèàtìòn tìmè àrè stòrèd às rèàdàblè plàìntèxt. Thè qùèùè ànd thè clìènt àrè stòrèd às òpàqùè rèfèrèncès. À dùmp càn tèll thàt twò tìckèts sìt ìn thè sàmè qùèùè òr còncèrn thè sàmè clìènt, bùt cànnòt tèll whìch qùèùè òr whìch clìènt. Thè tìtlè ànd thè dèscrìptìòn àrè cìphèrtèxt còlùmns. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) sèts òùt thè fùll ròw. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fòrm ànd thè crèàtìòn sèrvìcè. •••••••••••** Thè fòrm ìs \`NèwTìckètFòrm.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/tìckèts/\`. Ìt fètchès thè dèstìnàtìòn qùèùè's mèmbèr kèys ànd àsks thè cryptò wòrkèr fòr ònè sèàlèd còpy òf thè tìckèt kèy pèr rècìpìènt. Thè sèrvèr sìdè ìs \`crèàtè\` ìn \`pàckàgès/sèrvèr/src/tìckèts/tìckèt-sèrvìcè.ts\`. Thè ròw ànd ìts wràps àrè wrìttèn ìn ònè trànsàctìòn. [[#èncryptìòn]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Creating a ticket seals its title and description in the browser under a ticket key minted there. The server files the ciphertext and never holds the key. [[..." |
*
* @param {Demo_Narrative_Topic_New_Ticket_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_new_ticket_body = /** @type {((inputs?: Demo_Narrative_Topic_New_Ticket_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_New_Ticket_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_new_ticket_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_new_ticket_body(inputs)
	return en_demo_narrative_topic_new_ticket_body(inputs)
});