/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Response_Key_Not_Held_BodyInputs */

const en_demo_narrative_admin_response_key_not_held_body = /** @type {(inputs: Demo_Narrative_Admin_Response_Key_Not_Held_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A submission the user cannot decrypt still appears in the list with its arrival time and no answers. A second state reports a submission whose key material is present but whose decryption failed. The two states are separated because a missing wrap can be resolved and a corrupted one cannot. [[#keys #failure-states]]
**How does a submission get its readers?** The public form seals each submission's key to the organization's public key. During that window, any account that can open the organization key can read the submission. The first user to open the ticket converts the sealed copy into one wrapped copy per reader, covering active members of the destination queue and holders of the View intake responses permission who have published a key. The sealed copy is deleted after conversion. [How encryption works](#deep-dive/how-encryption-works) covers the sealing and the per-account wrapping. [[#encryption #keys #portal]]
**Who lacks a wrap after conversion?** An account that joined the queue after the conversion ran, received the View intake responses permission after it, or had not published a key at the time. The submission stays listed and unreadable for that account until another user who holds the key opens the viewer, at which point the browser mints the missing wraps against the current queue membership and permission sets. [Response cards](#admin-responses/responses) covers that backfill. [[#keys]]
**What does the View intake responses permission control?** Granting the permission adds the account to the wrap set for all queues, so the account receives keys to submissions in queues it does not belong to. Revoking the permission stops new wraps from that point forward. Wraps already issued stay usable indefinitely. [Permission matrix](#admin-people/role-permissions) covers where the permission sits and what it warns about. [[#permissions #keys #privacy]]
**The conversion transaction and its guards.** \`convertIntakeKeyWrap\` in \`packages/server/src/portal/intake-conversion-service.ts\` acquires the interim row with a delete-returning lock, serializing concurrent callers. It checks each target against queue membership and permission holders, and restores the sealed row on any insert failure. The backfill path for missing wraps after conversion runs through \`packages/server/src/tickets/wrap-backfill-service.ts\` for general ticket wraps and through \`backfillWraps\` on the intake forms router for intake-specific wraps. [Ticket decryption](#tickets/decryption) covers per-ticket wrapping for tickets that did not start on a form. [[#keys]]`)
};

const es_demo_narrative_admin_response_key_not_held_body = /** @type {(inputs: Demo_Narrative_Admin_Response_Key_Not_Held_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un envío que la persona usuaria no puede descifrar sigue apareciendo en la lista con su hora de llegada y sin respuestas. Un segundo estado informa de un envío cuyo material de clave está presente pero cuyo descifrado falló. Los dos estados se separan porque un envoltorio ausente se puede resolver y uno corrupto no. [[#keys #failure-states]]
**¿Cómo consigue lectores un envío?** El formulario público sella la clave de cada envío con la clave pública de la organización. Durante esa ventana, cualquier cuenta que pueda abrir la clave de la organización puede leer el envío. La primera persona que abre el ticket convierte la copia sellada en una copia envuelta por lectora, cubriendo miembros activos de la cola de destino y titulares del permiso Ver respuestas de ingreso que hayan publicado una clave. La copia sellada se elimina tras la conversión. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata el sellado y el envoltorio por cuenta. [[#encryption #keys #portal]]
**¿Quién se queda sin envoltorio tras la conversión?** Una cuenta que entró en la cola después de ejecutarse la conversión, que recibió el permiso Ver respuestas de ingreso después de ella, o que no había publicado una clave en ese momento. El envío sigue en la lista como ilegible para esa cuenta hasta que otra persona que tenga la clave abre el visor, momento en que el navegador genera los envoltorios que faltan contra los conjuntos actuales de cola y de permisos. [Tarjetas de respuesta](#admin-responses/responses) trata ese relleno. [[#keys]]
**¿Qué controla el permiso Ver respuestas de ingreso?** Conceder el permiso añade la cuenta al conjunto de envoltorios de todas las colas, de modo que la cuenta recibe claves de envíos de colas a las que no pertenece. Revocar el permiso detiene los envoltorios nuevos desde ese momento. Los envoltorios ya emitidos siguen siendo utilizables indefinidamente. [Matriz de permisos](#admin-people/role-permissions) trata dónde se sitúa el permiso y de qué avisa. [[#permissions #keys #privacy]]
**La transacción de conversión y sus resguardos.** \`convertIntakeKeyWrap\`, en \`packages/server/src/portal/intake-conversion-service.ts\`, adquiere la fila provisional con un bloqueo delete-returning, serializando llamadas concurrentes. Verifica cada destinatario contra la pertenencia a la cola y los titulares del permiso, y restaura la fila sellada ante cualquier fallo de inserción. La ruta de relleno para envoltorios que faltan después de la conversión pasa por \`packages/server/src/tickets/wrap-backfill-service.ts\` para envoltorios generales de tickets y por \`backfillWraps\` en el enrutador de formularios de admisión para envoltorios específicos de admisión. [Descifrado de tickets](#tickets/decryption) trata el envoltorio por ticket de los casos que no empezaron en un formulario. [[#keys]]`)
};

const en_xa2_demo_narrative_admin_response_key_not_held_body = /** @type {(inputs: Demo_Narrative_Admin_Response_Key_Not_Held_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À sùbmìssìòn thè ùsèr cànnòt dècrypt stìll àppèàrs ìn thè lìst wìth ìts àrrìvàl tìmè ànd nò ànswèrs. À sècònd stàtè rèpòrts à sùbmìssìòn whòsè kèy màtèrìàl ìs prèsènt bùt whòsè dècryptìòn fàìlèd. Thè twò stàtès àrè sèpàràtèd bècàùsè à mìssìng wràp càn bè rèsòlvèd ànd à còrrùptèd ònè cànnòt. [[#kèys #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès à sùbmìssìòn gèt ìts rèàdèrs? ••••••••••••** Thè pùblìc fòrm sèàls èàch sùbmìssìòn's kèy tò thè òrgànìzàtìòn's pùblìc kèy. Dùrìng thàt wìndòw, àny àccòùnt thàt càn òpèn thè òrgànìzàtìòn kèy càn rèàd thè sùbmìssìòn. Thè fìrst ùsèr tò òpèn thè tìckèt cònvèrts thè sèàlèd còpy ìntò ònè wràppèd còpy pèr rèàdèr, còvèrìng àctìvè mèmbèrs òf thè dèstìnàtìòn qùèùè ànd hòldèrs òf thè Vìèw ìntàkè rèspònsès pèrmìssìòn whò hàvè pùblìshèd à kèy. Thè sèàlèd còpy ìs dèlètèd àftèr cònvèrsìòn. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè sèàlìng ànd thè pèr-àccòùnt wràppìng. [[#èncryptìòn #kèys #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò làcks à wràp àftèr cònvèrsìòn? •••••••••••** Àn àccòùnt thàt jòìnèd thè qùèùè àftèr thè cònvèrsìòn ràn, rècèìvèd thè Vìèw ìntàkè rèspònsès pèrmìssìòn àftèr ìt, òr hàd nòt pùblìshèd à kèy àt thè tìmè. Thè sùbmìssìòn stàys lìstèd ànd ùnrèàdàblè fòr thàt àccòùnt ùntìl ànòthèr ùsèr whò hòlds thè kèy òpèns thè vìèwèr, àt whìch pòìnt thè bròwsèr mìnts thè mìssìng wràps àgàìnst thè cùrrènt qùèùè mèmbèrshìp ànd pèrmìssìòn sèts. [Rèspònsè càrds](#àdmìn-rèspònsès/rèspònsès) còvèrs thàt bàckfìll. [[#kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè Vìèw ìntàkè rèspònsès pèrmìssìòn còntròl? •••••••••••••••••** Gràntìng thè pèrmìssìòn àdds thè àccòùnt tò thè wràp sèt fòr àll qùèùès, sò thè àccòùnt rècèìvès kèys tò sùbmìssìòns ìn qùèùès ìt dòès nòt bèlòng tò. Rèvòkìng thè pèrmìssìòn stòps nèw wràps fròm thàt pòìnt fòrwàrd. Wràps àlrèàdy ìssùèd stày ùsàblè ìndèfìnìtèly. [Pèrmìssìòn màtrìx](#àdmìn-pèòplè/ròlè-pèrmìssìòns) còvèrs whèrè thè pèrmìssìòn sìts ànd whàt ìt wàrns àbòùt. [[#pèrmìssìòns #kèys #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè cònvèrsìòn trànsàctìòn ànd ìts gùàrds. •••••••••••••** \`cònvèrtÌntàkèKèyWràp\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-cònvèrsìòn-sèrvìcè.ts\` àcqùìrès thè ìntèrìm ròw wìth à dèlètè-rètùrnìng lòck, sèrìàlìzìng còncùrrènt càllèrs. Ìt chècks èàch tàrgèt àgàìnst qùèùè mèmbèrshìp ànd pèrmìssìòn hòldèrs, ànd rèstòrès thè sèàlèd ròw òn àny ìnsèrt fàìlùrè. Thè bàckfìll pàth fòr mìssìng wràps àftèr cònvèrsìòn rùns thròùgh \`pàckàgès/sèrvèr/src/tìckèts/wràp-bàckfìll-sèrvìcè.ts\` fòr gènèràl tìckèt wràps ànd thròùgh \`bàckfìllWràps\` òn thè ìntàkè fòrms ròùtèr fòr ìntàkè-spècìfìc wràps. [Tìckèt dècryptìòn](#tìckèts/dècryptìòn) còvèrs pèr-tìckèt wràppìng fòr tìckèts thàt dìd nòt stàrt òn à fòrm. [[#kèys]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A submission the user cannot decrypt still appears in the list with its arrival time and no answers. A second state reports a submission whose key material i..." |
*
* @param {Demo_Narrative_Admin_Response_Key_Not_Held_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_response_key_not_held_body = /** @type {((inputs?: Demo_Narrative_Admin_Response_Key_Not_Held_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Response_Key_Not_Held_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_response_key_not_held_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_response_key_not_held_body(inputs)
	return en_demo_narrative_admin_response_key_not_held_body(inputs)
});