/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Data_Retention_BodyInputs */

const en_demo_narrative_deepdive_data_retention_body = /** @type {(inputs: Demo_Narrative_Deepdive_Data_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Data an organization no longer needs can still be taken from it. For a population targeted by a state-level adversary, a case record from three years ago remains a live risk to a person who may have moved, changed names, or gone quiet. Encryption protects what is stored; retention decides whether it is stored at all. The two are different defenses and an organization needs both. [[#retention #privacy]]
Automatic deletion is off until an administrator turns it on, and turning it on means choosing a window between 1 and 3,650 days. A daily job hard-deletes every closed case whose last activity is older than that window, removing its stored files before its rows and asking the telephony provider to delete its own call and message logs for the case. A client record, together with its contact, portal channel and account rows, goes only when the last case for that client goes, so a client with an open or a recent case is untouched, and an organization that has never set a window is skipped. Enabling the policy and changing the window both ask for confirmation, and the confirmation states that deleted data cannot be recovered even from the escrow file, because escrow protects keys and not rows. With the policy off, everything is kept until someone deletes it by hand. [[#retention]]
The policy is one setting for the whole organization rather than a choice per queue or per case type. A per-queue window would be a decision someone has to get right on the day they create a queue. Configuring the policy requires the Manage retention permission, which sits with Admin by default and can be moved. [The permission system](#deep-dive/the-permission-system) covers how that moves. [[#retention #permissions]]
Retention cannot delete what a third party holds. It cannot delete a copy a client kept on their own phone either. For clients on a monitored device that copy is often the more dangerous one. Deletion is permanent; nothing the policy removes can be restored. [[#retention #failure-states]]
**Separate lifetimes.** Portal message copies, one-time share links, and telephony provider logs each follow their own schedule independent of the organization-wide window. [[#retention #portal #telephony]]
- Portal message copies on the client side are deleted after 30 days of channel inactivity, measured from the later of the last-seen and created timestamps. That sweep removes portal messages, portal attachments and portal recordings while leaving the organization's own record intact. [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers the channel model. [[#retention #portal]]
- One-time share links expire 72 hours after creation or on first read, whichever comes first. The ciphertext column is cleared at read time while the row survives as a tombstone until an expiry sweep removes it. [[#retention #portal]]
- Telephony logs are deleted at the provider. CARE-Y asks the provider to delete each call, message or recording log after processing, with retries when the request fails. [[#retention #telephony]]
**What survives a deletion?** [[#retention #metadata #server-holds]]
- Foreign key relationships and row counts remain readable in the tables that are left. [[#retention #metadata]]
- A deleted case removes its own ciphertext and its key wraps. A key wrap without its case cannot be recovered. [[#retention #encryption]]
- Deleting a note from a case thread overwrites the note's ciphertext at delete time. [[#retention #failure-states]]
- Escrow holds key material rather than data, so no escrow ceremony brings back a deleted row. [[#retention #keys]]
**The retention column and the purge jobs.** [[#retention]]
- The organization-wide window is \`org_config.pii_retention_days\`, an integer column from \`packages/server/src/db/migrations/tenant/003_create_org_config.ts\`, written through \`setPiiRetentionDays\` in \`packages/server/src/auth/service.ts\` behind a permission-gated tRPC procedure in \`packages/server/src/routes/auth.ts\`, and read back for display through the hub status query. [[#retention #permissions]]
- The purge itself is \`packages/server/src/jobs/pii-retention.ts\`, which exports \`purgeTicket\` and \`purgeClient\` so manual deletion runs the same cascade. [[#retention]]
- The independent sweeps live in \`packages/server/src/jobs/\`, where \`portal-message-expiry.ts\` handles the 30-day portal window across tenant schemas and \`log-deletion.ts\` dispatches provider log deletions with backoff. [[#retention #portal #telephony]]
- Share link expiry logic is in \`packages/server/src/portal/share-service.ts\`. [[#retention #portal]]`)
};

const es_demo_narrative_deepdive_data_retention_body = /** @type {(inputs: Demo_Narrative_Deepdive_Data_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los datos que una organización ya no necesita todavía se le pueden arrebatar. Para una población perseguida por un adversario con recursos de un estado, un expediente de caso de hace tres años sigue siendo un riesgo vivo para una persona que puede haberse mudado, haber cambiado de nombre o haber callado. El cifrado protege lo que está almacenado; la retención decide si se almacena en absoluto. Son dos defensas distintas y una organización necesita las dos. [[#retention #privacy]]
La eliminación automática está apagada hasta que una persona administradora la enciende, y encenderla implica elegir una ventana de entre 1 y 3.650 días. Un trabajo diario elimina de forma definitiva cada caso cerrado cuya última actividad sea más antigua que esa ventana, retirando sus archivos almacenados antes que sus filas y pidiendo al proveedor de telefonía que elimine sus propios registros de llamadas y mensajes del caso. El registro de un cliente, junto con sus filas de contacto, de canal del portal y de cuenta, se va solo cuando se va el último caso de ese cliente, así que un cliente con un caso abierto o reciente queda intacto, y una organización que nunca ha fijado una ventana se omite. Tanto activar la política como cambiar la ventana piden confirmación, y la confirmación declara que los datos eliminados no se pueden recuperar ni desde el archivo de custodia, porque la custodia protege claves y no filas. Con la política apagada, todo se conserva hasta que alguien lo elimina a mano. [[#retention]]
La política es un único ajuste para toda la organización y no una elección por cola o por tipo de caso. Una ventana por cola sería una decisión que alguien tendría que acertar el día en que crea una cola. Configurar la política requiere el permiso Definir cuánto tiempo se conservan los datos, que está con Administrador de forma predeterminada y se puede mover. [El sistema de permisos](#deep-dive/the-permission-system) explica cómo se mueve. [[#retention #permissions]]
La retención no puede eliminar lo que tiene una tercera parte. Tampoco puede eliminar una copia que un cliente guardó en su propio teléfono. Para clientes con un dispositivo vigilado, esa copia es a menudo la más peligrosa. La eliminación es definitiva; nada de lo que la política quita se puede restaurar. [[#retention #failure-states]]
**Vidas separadas.** Las copias de mensajes del portal, los enlaces de compartición de un solo uso y los registros del proveedor de telefonía siguen cada uno su propio calendario con independencia de la ventana de toda la organización. [[#retention #portal #telephony]]
- Las copias de mensajes del portal del lado del cliente se eliminan tras 30 días de inactividad del canal, medidos desde la más tardía de las marcas de última vista y de creación. Ese barrido retira los mensajes del portal, los adjuntos del portal y las grabaciones del portal mientras deja intacto el registro propio de la organización. [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata el modelo de canal. [[#retention #portal]]
- Los enlaces de compartición de un solo uso caducan 72 horas después de su creación o en la primera lectura, lo que ocurra primero. La columna de texto cifrado se vacía en el momento de la lectura mientras la fila sobrevive como lápida hasta que un barrido de caducidad la retira. [[#retention #portal]]
- Los registros de telefonía se eliminan en el proveedor. CARE-Y pide al proveedor que elimine cada registro de llamada, mensaje o grabación después de procesarlo, con reintentos cuando la solicitud falla. [[#retention #telephony]]
**¿Qué sobrevive a una eliminación?** [[#retention #metadata #server-holds]]
- Las relaciones de claves externas y el número de filas siguen siendo legibles en las tablas que quedan. [[#retention #metadata]]
- Un caso eliminado retira su propio texto cifrado y sus envolturas de clave. Una envoltura de clave sin su caso no es recuperable. [[#retention #encryption]]
- Eliminar una nota de un hilo de caso sobreescribe el texto cifrado de la nota en el momento de la eliminación. [[#retention #failure-states]]
- La custodia guarda material de claves y no datos, así que ninguna ceremonia de custodia devuelve una fila eliminada. [[#retention #keys]]
**La columna de retención y los trabajos de purga.** [[#retention]]
- La ventana de toda la organización es \`org_config.pii_retention_days\`, una columna entera de \`packages/server/src/db/migrations/tenant/003_create_org_config.ts\`, escrita mediante \`setPiiRetentionDays\` en \`packages/server/src/auth/service.ts\` detrás de un procedimiento tRPC protegido por permiso en \`packages/server/src/routes/auth.ts\`, y leída de vuelta para mostrarla mediante la consulta de estado del hub. [[#retention #permissions]]
- La purga en sí es \`packages/server/src/jobs/pii-retention.ts\`, que exporta \`purgeTicket\` y \`purgeClient\` para que la eliminación manual recorra la misma cascada. [[#retention]]
- Los barridos independientes viven en \`packages/server/src/jobs/\`, donde \`portal-message-expiry.ts\` se encarga de la ventana de 30 días del portal en todos los esquemas de inquilino y \`log-deletion.ts\` despacha las eliminaciones de registros del proveedor con reintentos escalonados. [[#retention #portal #telephony]]
- La lógica de caducidad de los enlaces de compartición está en \`packages/server/src/portal/share-service.ts\`. [[#retention #portal]]`)
};

const en_xa2_demo_narrative_deepdive_data_retention_body = /** @type {(inputs: Demo_Narrative_Deepdive_Data_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Dàtà àn òrgànìzàtìòn nò lòngèr nèèds càn stìll bè tàkèn fròm ìt. Fòr à pòpùlàtìòn tàrgètèd by à stàtè-lèvèl àdvèrsàry, à càsè rècòrd fròm thrèè yèàrs àgò rèmàìns à lìvè rìsk tò à pèrsòn whò mày hàvè mòvèd, chàngèd nàmès, òr gònè qùìèt. Èncryptìòn pròtècts whàt ìs stòrèd; rètèntìòn dècìdès whèthèr ìt ìs stòrèd àt àll. Thè twò àrè dìffèrènt dèfènsès ànd àn òrgànìzàtìòn nèèds bòth. [[#rètèntìòn #prìvàcy]]
Àùtòmàtìc dèlètìòn ìs òff ùntìl àn àdmìnìstràtòr tùrns ìt òn, ànd tùrnìng ìt òn mèàns chòòsìng à wìndòw bètwèèn 1 ànd 3,650 dàys. À dàìly jòb hàrd-dèlètès èvèry clòsèd càsè whòsè làst àctìvìty ìs òldèr thàn thàt wìndòw, rèmòvìng ìts stòrèd fìlès bèfòrè ìts ròws ànd àskìng thè tèlèphòny pròvìdèr tò dèlètè ìts òwn càll ànd mèssàgè lògs fòr thè càsè. À clìènt rècòrd, tògèthèr wìth ìts còntàct, pòrtàl chànnèl ànd àccòùnt ròws, gòès ònly whèn thè làst càsè fòr thàt clìènt gòès, sò à clìènt wìth àn òpèn òr à rècènt càsè ìs ùntòùchèd, ànd àn òrgànìzàtìòn thàt hàs nèvèr sèt à wìndòw ìs skìppèd. Ènàblìng thè pòlìcy ànd chàngìng thè wìndòw bòth àsk fòr cònfìrmàtìòn, ànd thè cònfìrmàtìòn stàtès thàt dèlètèd dàtà cànnòt bè rècòvèrèd èvèn fròm thè èscròw fìlè, bècàùsè èscròw pròtècts kèys ànd nòt ròws. Wìth thè pòlìcy òff, èvèrythìng ìs kèpt ùntìl sòmèònè dèlètès ìt by hànd. [[#rètèntìòn]]
Thè pòlìcy ìs ònè sèttìng fòr thè whòlè òrgànìzàtìòn ràthèr thàn à chòìcè pèr qùèùè òr pèr càsè typè. À pèr-qùèùè wìndòw wòùld bè à dècìsìòn sòmèònè hàs tò gèt rìght òn thè dày thèy crèàtè à qùèùè. Cònfìgùrìng thè pòlìcy rèqùìrès thè Mànàgè rètèntìòn pèrmìssìòn, whìch sìts wìth Àdmìn by dèfàùlt ànd càn bè mòvèd. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw thàt mòvès. [[#rètèntìòn #pèrmìssìòns]]
Rètèntìòn cànnòt dèlètè whàt à thìrd pàrty hòlds. Ìt cànnòt dèlètè à còpy à clìènt kèpt òn thèìr òwn phònè èìthèr. Fòr clìènts òn à mònìtòrèd dèvìcè thàt còpy ìs òftèn thè mòrè dàngèròùs ònè. Dèlètìòn ìs pèrmànènt; nòthìng thè pòlìcy rèmòvès càn bè rèstòrèd. [[#rètèntìòn #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèpàràtè lìfètìmès. ••••••** Pòrtàl mèssàgè còpìès, ònè-tìmè shàrè lìnks, ànd tèlèphòny pròvìdèr lògs èàch fòllòw thèìr òwn schèdùlè ìndèpèndènt òf thè òrgànìzàtìòn-wìdè wìndòw. [[#rètèntìòn #pòrtàl #tèlèphòny]]
- Pòrtàl mèssàgè còpìès òn thè clìènt sìdè àrè dèlètèd àftèr 30 dàys òf chànnèl ìnàctìvìty, mèàsùrèd fròm thè làtèr òf thè làst-sèèn ànd crèàtèd tìmèstàmps. Thàt swèèp rèmòvès pòrtàl mèssàgès, pòrtàl àttàchmènts ànd pòrtàl rècòrdìngs whìlè lèàvìng thè òrgànìzàtìòn's òwn rècòrd ìntàct. [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thè chànnèl mòdèl. [[#rètèntìòn #pòrtàl]]
- Ònè-tìmè shàrè lìnks èxpìrè 72 hòùrs àftèr crèàtìòn òr òn fìrst rèàd, whìchèvèr còmès fìrst. Thè cìphèrtèxt còlùmn ìs clèàrèd àt rèàd tìmè whìlè thè ròw sùrvìvès às à tòmbstònè ùntìl àn èxpìry swèèp rèmòvès ìt. [[#rètèntìòn #pòrtàl]]
- Tèlèphòny lògs àrè dèlètèd àt thè pròvìdèr. CÀRÈ-Y àsks thè pròvìdèr tò dèlètè èàch càll, mèssàgè òr rècòrdìng lòg àftèr pròcèssìng, wìth rètrìès whèn thè rèqùèst fàìls. [[#rètèntìòn #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt sùrvìvès à dèlètìòn? ••••••••** [[#rètèntìòn #mètàdàtà #sèrvèr-hòlds]]
- Fòrèìgn kèy rèlàtìònshìps ànd ròw còùnts rèmàìn rèàdàblè ìn thè tàblès thàt àrè lèft. [[#rètèntìòn #mètàdàtà]]
- À dèlètèd càsè rèmòvès ìts òwn cìphèrtèxt ànd ìts kèy wràps. À kèy wràp wìthòùt ìts càsè cànnòt bè rècòvèrèd. [[#rètèntìòn #èncryptìòn]]
- Dèlètìng à nòtè fròm à càsè thrèàd òvèrwrìtès thè nòtè's cìphèrtèxt àt dèlètè tìmè. [[#rètèntìòn #fàìlùrè-stàtès]]
- Èscròw hòlds kèy màtèrìàl ràthèr thàn dàtà, sò nò èscròw cèrèmòny brìngs bàck à dèlètèd ròw. [[#rètèntìòn #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rètèntìòn còlùmn ànd thè pùrgè jòbs. ••••••••••••** [[#rètèntìòn]]
- Thè òrgànìzàtìòn-wìdè wìndòw ìs \`òrg_cònfìg.pìì_rètèntìòn_dàys\`, àn ìntègèr còlùmn fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/003_crèàtè_òrg_cònfìg.ts\`, wrìttèn thròùgh \`sètPììRètèntìònDàys\` ìn \`pàckàgès/sèrvèr/src/àùth/sèrvìcè.ts\` bèhìnd à pèrmìssìòn-gàtèd tRPC pròcèdùrè ìn \`pàckàgès/sèrvèr/src/ròùtès/àùth.ts\`, ànd rèàd bàck fòr dìsplày thròùgh thè hùb stàtùs qùèry. [[#rètèntìòn #pèrmìssìòns]]
- Thè pùrgè ìtsèlf ìs \`pàckàgès/sèrvèr/src/jòbs/pìì-rètèntìòn.ts\`, whìch èxpòrts \`pùrgèTìckèt\` ànd \`pùrgèClìènt\` sò mànùàl dèlètìòn rùns thè sàmè càscàdè. [[#rètèntìòn]]
- Thè ìndèpèndènt swèèps lìvè ìn \`pàckàgès/sèrvèr/src/jòbs/\`, whèrè \`pòrtàl-mèssàgè-èxpìry.ts\` hàndlès thè 30-dày pòrtàl wìndòw àcròss tènànt schèmàs ànd \`lòg-dèlètìòn.ts\` dìspàtchès pròvìdèr lòg dèlètìòns wìth bàckòff. [[#rètèntìòn #pòrtàl #tèlèphòny]]
- Shàrè lìnk èxpìry lògìc ìs ìn \`pàckàgès/sèrvèr/src/pòrtàl/shàrè-sèrvìcè.ts\`. [[#rètèntìòn #pòrtàl]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Data an organization no longer needs can still be taken from it. For a population targeted by a state-level adversary, a case record from three years ago rem..." |
*
* @param {Demo_Narrative_Deepdive_Data_Retention_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_data_retention_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Data_Retention_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Data_Retention_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_data_retention_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_data_retention_body(inputs)
	return en_demo_narrative_deepdive_data_retention_body(inputs)
});