/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Correction_Status_BodyInputs */

const en_demo_narrative_topic_correction_status_body = /** @type {(inputs: Demo_Narrative_Topic_Correction_Status_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A contact correction appears in the unified case thread as its own follow-up type. It carries the phone number or email address a client reports as current. [[#client-data]]
**What does the follow-up carry?** A versioned record with a phone, an email, or both. The record is sealed with the ticket key, like any other follow-up. Only browsers the ticket key is wrapped for can read the corrected value. The follow-up type and the authoring role are stored in plaintext. A database dump shows that a client submitted a contact correction on a ticket at a given minute, but neither the old value nor the new one. [The trust boundary](#deep-dive/the-trust-boundary) lists the columns a dump reaches. [[#encryption #server-holds #metadata]]
**Applying a correction.** Each corrected value can be carried into the matching contact record. The edit path opens with the value already filled in. The save is left to the user who opened it, because a correction arrives over the same channel anyone could reach the organization on. A save that lands marks the correction handled. [The full case record](#ticket-detail/case-panel) covers what happens when the saved value already belongs to another client record. [[#client-data #privacy]]
**Handling and the compose warning.** Handling is an acknowledge reaction on the follow-up, one per account. The line names the first user who left one. The reaction record stores the follow-up, the account, and the time in plaintext. The server can see who reviewed a correction and when, but not the value reviewed. While a correction on the ticket remains unacknowledged, composing a text or opening the call options reports it. Both actions are about to use a number the client may have replaced. [Channel warnings](#ticket-detail/exposure-hints) covers the compose bar's warning surface. [[#metadata #server-holds #telephony]]
**The payload schema and renderer.** \`packages/shared/src/schemas/contact-correction-payload.ts\` defines the record and parses it. \`CorrectionBody.svelte\` renders it on the ticket thread and on the client's own thread from one implementation. Content that does not parse as a correction record renders as ordinary text. Corrections written before the record format existed decrypt to plain text. [[#client-data #failure-states]]`)
};

const es_demo_narrative_topic_correction_status_body = /** @type {(inputs: Demo_Narrative_Topic_Correction_Status_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Una corrección de contacto aparece en el hilo de caso unificado como un tipo propio de seguimiento. Lleva el número de teléfono o la dirección de correo electrónico que el cliente indica como actual. [[#client-data]]
**¿Qué contiene el seguimiento?** Un registro versionado con un teléfono, un correo electrónico o ambos. El registro se sella con la clave del ticket, como cualquier otro seguimiento. Solo los navegadores para los que la clave del ticket está envuelta pueden leer el valor corregido. El tipo de seguimiento y el rol de autoría se almacenan en texto plano. Un volcado de base de datos muestra que un cliente envió una corrección de contacto en un ticket en un minuto determinado, pero no el valor anterior ni el nuevo. [La frontera de confianza](#deep-dive/the-trust-boundary) enumera las columnas que un volcado alcanza. [[#encryption #server-holds #metadata]]
**Aplicar una corrección.** Cada valor corregido se puede trasladar al registro de contacto correspondiente. La ruta de edición se abre con el valor ya rellenado. Guardar queda en manos de la persona usuaria que lo abrió, porque una corrección llega por el mismo canal que cualquier persona podría usar para contactar a la organización. Un guardado exitoso marca la corrección como gestionada. [El expediente completo](#ticket-detail/case-panel) trata lo que ocurre cuando el valor guardado ya pertenece a otro registro de cliente. [[#client-data #privacy]]
**Gestión y el aviso en la composición.** La gestión es una reacción de confirmación sobre el seguimiento, una por cuenta. La línea nombra la primera persona que dejó una. El registro de la reacción almacena el seguimiento, la cuenta y la hora en texto plano. El servidor puede ver quién revisó una corrección y cuándo, pero no el valor revisado. Mientras una corrección en el ticket permanece sin confirmar, redactar un texto o abrir las opciones de llamada lo informa. Ambas acciones van a usar un número que el cliente puede haber reemplazado. [Avisos de canal](#ticket-detail/exposure-hints) trata la superficie de aviso de la barra de composición. [[#metadata #server-holds #telephony]]
**El esquema del contenido y el renderizador.** \`packages/shared/src/schemas/contact-correction-payload.ts\` define el registro y lo analiza. \`CorrectionBody.svelte\` lo renderiza en el hilo del ticket y en el hilo propio del cliente desde una sola implementación. El contenido que no se analiza como un registro de corrección se muestra como texto ordinario. Las correcciones escritas antes de que el formato existiera se descifran como texto sin estructura. [[#client-data #failure-states]]`)
};

const en_xa2_demo_narrative_topic_correction_status_body = /** @type {(inputs: Demo_Narrative_Topic_Correction_Status_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À còntàct còrrèctìòn àppèàrs ìn thè ùnìfìèd càsè thrèàd às ìts òwn fòllòw-ùp typè. Ìt càrrìès thè phònè nùmbèr òr èmàìl àddrèss à clìènt rèpòrts às cùrrènt. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè fòllòw-ùp càrry? •••••••••** À vèrsìònèd rècòrd wìth à phònè, àn èmàìl, òr bòth. Thè rècòrd ìs sèàlèd wìth thè tìckèt kèy, lìkè àny òthèr fòllòw-ùp. Ònly bròwsèrs thè tìckèt kèy ìs wràppèd fòr càn rèàd thè còrrèctèd vàlùè. Thè fòllòw-ùp typè ànd thè àùthòrìng ròlè àrè stòrèd ìn plàìntèxt. À dàtàbàsè dùmp shòws thàt à clìènt sùbmìttèd à còntàct còrrèctìòn òn à tìckèt àt à gìvèn mìnùtè, bùt nèìthèr thè òld vàlùè nòr thè nèw ònè. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) lìsts thè còlùmns à dùmp rèàchès. [[#èncryptìòn #sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àpplyìng à còrrèctìòn. •••••••** Èàch còrrèctèd vàlùè càn bè càrrìèd ìntò thè màtchìng còntàct rècòrd. Thè èdìt pàth òpèns wìth thè vàlùè àlrèàdy fìllèd ìn. Thè sàvè ìs lèft tò thè ùsèr whò òpènèd ìt, bècàùsè à còrrèctìòn àrrìvès òvèr thè sàmè chànnèl ànyònè còùld rèàch thè òrgànìzàtìòn òn. À sàvè thàt lànds màrks thè còrrèctìòn hàndlèd. [Thè fùll càsè rècòrd](#tìckèt-dètàìl/càsè-pànèl) còvèrs whàt hàppèns whèn thè sàvèd vàlùè àlrèàdy bèlòngs tò ànòthèr clìènt rècòrd. [[#clìènt-dàtà #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hàndlìng ànd thè còmpòsè wàrnìng. ••••••••••** Hàndlìng ìs àn àcknòwlèdgè rèàctìòn òn thè fòllòw-ùp, ònè pèr àccòùnt. Thè lìnè nàmès thè fìrst ùsèr whò lèft ònè. Thè rèàctìòn rècòrd stòrès thè fòllòw-ùp, thè àccòùnt, ànd thè tìmè ìn plàìntèxt. Thè sèrvèr càn sèè whò rèvìèwèd à còrrèctìòn ànd whèn, bùt nòt thè vàlùè rèvìèwèd. Whìlè à còrrèctìòn òn thè tìckèt rèmàìns ùnàcknòwlèdgèd, còmpòsìng à tèxt òr òpènìng thè càll òptìòns rèpòrts ìt. Bòth àctìòns àrè àbòùt tò ùsè à nùmbèr thè clìènt mày hàvè rèplàcèd. [Chànnèl wàrnìngs](#tìckèt-dètàìl/èxpòsùrè-hìnts) còvèrs thè còmpòsè bàr's wàrnìng sùrfàcè. [[#mètàdàtà #sèrvèr-hòlds #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pàylòàd schèmà ànd rèndèrèr. ••••••••••** \`pàckàgès/shàrèd/src/schèmàs/còntàct-còrrèctìòn-pàylòàd.ts\` dèfìnès thè rècòrd ànd pàrsès ìt. \`CòrrèctìònBòdy.svèltè\` rèndèrs ìt òn thè tìckèt thrèàd ànd òn thè clìènt's òwn thrèàd fròm ònè ìmplèmèntàtìòn. Còntènt thàt dòès nòt pàrsè às à còrrèctìòn rècòrd rèndèrs às òrdìnàry tèxt. Còrrèctìòns wrìttèn bèfòrè thè rècòrd fòrmàt èxìstèd dècrypt tò plàìn tèxt. [[#clìènt-dàtà #fàìlùrè-stàtès]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A contact correction appears in the unified case thread as its own follow-up type. It carries the phone number or email address a client reports as current. ..." |
*
* @param {Demo_Narrative_Topic_Correction_Status_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_correction_status_body = /** @type {((inputs?: Demo_Narrative_Topic_Correction_Status_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Correction_Status_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_correction_status_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_correction_status_body(inputs)
	return en_demo_narrative_topic_correction_status_body(inputs)
});