/* eslint-disable */
import * as registry from '../registry.js'
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Search_Overlay_BodyInputs */

const en_demo_narrative_search_overlay_body = /** @type {(inputs: Demo_Narrative_Search_Overlay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Global search is an overlay. Before the user enters any search term it shows two lists: the searches the user has made since signing in and recently opened cases and articles. Results appear once the user has typed at least two characters. [[#privacy #client-data #search]]
**The recent searches list.** It holds ten terms at most. The terms are held in memory only. They are gone as soon as the user signs out or reloads the page. No search term is written to the device or sent anywhere. A browser handed to someone else carries no record of what was searched for. [[#privacy #client-data]]
**The recently viewed list.** It is one envelope on the server. The envelope is sealed to the user's own public key and opens only in that user's browser. It holds the IDs of up to twenty recent cases and articles. It also holds the times they were opened. It holds none of their titles. The server stores the sealed envelope and cannot read which case any ID inside it belongs to. No other account can open the envelope. [How encryption works](#deep-dive/how-encryption-works) covers the key it is sealed to. [[#encryption #server-holds]]
**Why an entry falls out of the list.** The overlay looks each ID up with the same searches it runs for a query. An entry the account no longer has access to is not found and is not shown. A password change replaces the keys the envelope was sealed to and makes it unopenable. The app reads an unopenable envelope as an empty history and overwrites it with the next entry rather than reporting a failure. [Password and key re-wrap](#settings/password) covers that rotation. [[#failure-states #keys]]
**How results are grouped.** Results are grouped by the kind of record they are. The group matching the surface the search was opened from is placed first, so the same query answers differently from the case list than from the library. Each group reports how many of its records were searched against the total. That shows the user when an answer is partial. [What global search covers](#search/entities) covers the kinds. [[#client-data #metadata]]
**The overlay and its lists.** The provider registry is \`packages/client/src/lib/search/registry.svelte.ts\`. The session term list is \`recents.svelte.ts\`. The recently viewed envelope is \`recent-views.ts\` against \`user_recent_views\` from \`packages/server/src/db/migrations/tenant/079_create_user_recent_views.ts\`. That table is one row per account with no timestamp column of its own. [[#server-holds #client-data]]`)
};

const es_demo_narrative_search_overlay_body = /** @type {(inputs: Demo_Narrative_Search_Overlay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La búsqueda global es una ventana superpuesta. Antes de que la persona usuaria escriba ningún término de búsqueda, muestra dos listas: las búsquedas que la persona usuaria ha hecho desde que inició sesión y los casos y artículos abiertos hace poco. Los resultados aparecen cuando la persona usuaria ha escrito al menos dos caracteres. [[#privacy #client-data #search]]
**La lista de búsquedas recientes.** Guarda diez términos como mucho. Los términos se guardan solo en memoria. Desaparecen en cuanto la persona usuaria cierra sesión o recarga la página. Ningún término de búsqueda se escribe en el dispositivo ni se envía a ninguna parte. Un navegador prestado a otra persona no lleva constancia de qué se buscó. [[#privacy #client-data]]
**La lista de vistos recientemente.** Es un único sobre en el servidor. El sobre está sellado con la clave pública de la propia persona usuaria y solo se abre en el navegador de esa persona. Contiene los ID de hasta veinte casos y artículos recientes. Contiene también la hora en que se abrieron. No contiene ninguno de sus títulos. El servidor guarda el sobre sellado y no puede leer a qué caso pertenece ninguno de los ID que hay dentro. Ninguna otra cuenta puede abrir el sobre. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la clave con la que se sella. [[#encryption #server-holds]]
**Por qué una entrada sale de la lista.** La ventana busca cada ID con las mismas búsquedas que ejecuta para una consulta. Una entrada a la que la cuenta ya no tiene acceso no se encuentra y no se muestra. Un cambio de contraseña sustituye las claves con las que se selló el sobre y lo deja sin poder abrirse. La aplicación interpreta un sobre que no se puede abrir como un historial vacío y lo sobrescribe con la entrada siguiente en lugar de informar de un fallo. [Contraseña y reenvoltura de claves](#settings/password) trata esa rotación. [[#failure-states #keys]]
**Cómo se agrupan los resultados.** Los resultados se agrupan por la clase de registro que son. El grupo que corresponde a la superficie desde la que se abrió la búsqueda se coloca primero, de modo que la misma consulta responde de otra manera desde la lista de casos que desde la biblioteca. Cada grupo indica cuántos de sus registros se examinaron sobre el total. Eso le indica a la persona usuaria cuándo una respuesta es parcial. [Qué cubre la búsqueda global](#search/entities) trata las clases. [[#client-data #metadata]]
**La ventana y sus listas.** El registro de proveedores es \`packages/client/src/lib/search/registry.svelte.ts\`. La lista de términos de la sesión es \`recents.svelte.ts\`. El sobre de vistos recientemente es \`recent-views.ts\` contra \`user_recent_views\`, creado en \`packages/server/src/db/migrations/tenant/079_create_user_recent_views.ts\`. Esa tabla es una fila por cuenta y sin columna propia de fecha. [[#server-holds #client-data]]`)
};

const en_xa2_demo_narrative_search_overlay_body = /** @type {(inputs: Demo_Narrative_Search_Overlay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Glòbàl sèàrch ìs àn òvèrlày. Bèfòrè thè ùsèr èntèrs àny sèàrch tèrm ìt shòws twò lìsts: thè sèàrchès thè ùsèr hàs màdè sìncè sìgnìng ìn ànd rècèntly òpènèd càsès ànd àrtìclès. Rèsùlts àppèàr òncè thè ùsèr hàs typèd àt lèàst twò chàràctèrs. [[#prìvàcy #clìènt-dàtà #sèàrch]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rècènt sèàrchès lìst. ••••••••** Ìt hòlds tèn tèrms àt mòst. Thè tèrms àrè hèld ìn mèmòry ònly. Thèy àrè gònè às sòòn às thè ùsèr sìgns òùt òr rèlòàds thè pàgè. Nò sèàrch tèrm ìs wrìttèn tò thè dèvìcè òr sènt ànywhèrè. À bròwsèr hàndèd tò sòmèònè èlsè càrrìès nò rècòrd òf whàt wàs sèàrchèd fòr. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rècèntly vìèwèd lìst. ••••••••** Ìt ìs ònè ènvèlòpè òn thè sèrvèr. Thè ènvèlòpè ìs sèàlèd tò thè ùsèr's òwn pùblìc kèy ànd òpèns ònly ìn thàt ùsèr's bròwsèr. Ìt hòlds thè ÌDs òf ùp tò twènty rècènt càsès ànd àrtìclès. Ìt àlsò hòlds thè tìmès thèy wèrè òpènèd. Ìt hòlds nònè òf thèìr tìtlès. Thè sèrvèr stòrès thè sèàlèd ènvèlòpè ànd cànnòt rèàd whìch càsè àny ÌD ìnsìdè ìt bèlòngs tò. Nò òthèr àccòùnt càn òpèn thè ènvèlòpè. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè kèy ìt ìs sèàlèd tò. [[#èncryptìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why àn èntry fàlls òùt òf thè lìst. •••••••••••** Thè òvèrlày lòòks èàch ÌD ùp wìth thè sàmè sèàrchès ìt rùns fòr à qùèry. Àn èntry thè àccòùnt nò lòngèr hàs àccèss tò ìs nòt fòùnd ànd ìs nòt shòwn. À pàsswòrd chàngè rèplàcès thè kèys thè ènvèlòpè wàs sèàlèd tò ànd màkès ìt ùnòpènàblè. Thè àpp rèàds àn ùnòpènàblè ènvèlòpè às àn èmpty hìstòry ànd òvèrwrìtès ìt wìth thè nèxt èntry ràthèr thàn rèpòrtìng à fàìlùrè. [Pàsswòrd ànd kèy rè-wràp](#sèttìngs/pàsswòrd) còvèrs thàt ròtàtìòn. [[#fàìlùrè-stàtès #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw rèsùlts àrè gròùpèd. ••••••••** Rèsùlts àrè gròùpèd by thè kìnd òf rècòrd thèy àrè. Thè gròùp màtchìng thè sùrfàcè thè sèàrch wàs òpènèd fròm ìs plàcèd fìrst, sò thè sàmè qùèry ànswèrs dìffèrèntly fròm thè càsè lìst thàn fròm thè lìbràry. Èàch gròùp rèpòrts hòw màny òf ìts rècòrds wèrè sèàrchèd àgàìnst thè tòtàl. Thàt shòws thè ùsèr whèn àn ànswèr ìs pàrtìàl. [Whàt glòbàl sèàrch còvèrs](#sèàrch/èntìtìès) còvèrs thè kìnds. [[#clìènt-dàtà #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè òvèrlày ànd ìts lìsts. ••••••••** Thè pròvìdèr règìstry ìs \`pàckàgès/clìènt/src/lìb/sèàrch/règìstry.svèltè.ts\`. Thè sèssìòn tèrm lìst ìs \`rècènts.svèltè.ts\`. Thè rècèntly vìèwèd ènvèlòpè ìs \`rècènt-vìèws.ts\` àgàìnst \`ùsèr_rècènt_vìèws\` fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/079_crèàtè_ùsèr_rècènt_vìèws.ts\`. Thàt tàblè ìs ònè ròw pèr àccòùnt wìth nò tìmèstàmp còlùmn òf ìts òwn. [[#sèrvèr-hòlds #clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Global search is an overlay. Before the user enters any search term it shows two lists: the searches the user has made since signing in and recently opened c..." |
*
* @param {Demo_Narrative_Search_Overlay_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_search_overlay_body = /** @type {((inputs?: Demo_Narrative_Search_Overlay_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Search_Overlay_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_search_overlay_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_search_overlay_body(inputs)
	return en_demo_narrative_search_overlay_body(inputs)
});