/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Branding_BodyInputs */

const en_demo_narrative_admin_branding_body = /** @type {(inputs: Demo_Narrative_Admin_Branding_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Branding holds the organization's logo, its two brand colors, the welcome text a visitor reads on the intake form, and the support label a client sees on portal messages. All fields are stored without encryption, because the pages that use them are reached before anyone signs in. [[#server-holds #portal]]
**Why is none of it encrypted?** The organization's subdomain arrives in the clear on every request, and the server resolves it by comparing a plaintext slug. A database dump already lists every organization on the server regardless of what these columns hold. The logo is served by an unauthenticated route to pages a visitor reaches without an account. A previous design encrypted these columns under a key whose public half sat in the same row, which protected neither of those two facts and placed decryption inside a web process that otherwise holds no key material. [The trust boundary](#deep-dive/the-trust-boundary) covers what else a dump reveals. [[#encryption #server-holds]]
**How is a logo sanitized?** The browser redraws every accepted upload (PNG, JPEG, or SVG) to a resized PNG, so no markup or script travels inside the image. The server validates the file type and enforces its own 2 MB ceiling before storing the result. App icons for the installed app and the home screen are generated in a separate step after the save, and a failure there raises its own notice while the saved logo stands. [[#failure-states]]
**How are colors kept readable?** The app stores a brand color as chosen and derives two working colors from it, a text color and a fill color. Each working color has its lightness adjusted until it clears the WCAG AA contrast ratio of 4.5:1 against the worst surface it can land on, separately for light mode and dark mode. A chosen shade that falls close to the red reserved for urgency or the ochre reserved for care draws a notice offering a shifted alternative, and saving the original is allowed. [[#failure-states]]
**Editing branding.** Editing branding requires the Manage org identity permission, the same grant that covers [General info](#admin-org/general). [[#permissions]]
**The branding columns and the icon route.** The plaintext columns were introduced by \`packages/server/src/db/migrations/tenant/107_branding_plaintext.ts\`, which dropped the encrypted counterpart for each and left \`encrypted_terminology\`, the org public key, and the icon blob keys untouched. Reads and writes go through \`packages/server/src/branding/branding-service.ts\`. Icons are served without authentication by \`packages/server/src/routes/branding-icons.ts\`, which uses the blob key as the ETag. The rasterizer in \`packages/client/src/lib/branding/rasterize.ts\` scales to a 512-pixel maximum before upload. The contrast derivation and proximity check are in \`packages/client/src/lib/branding/konsta-palette.ts\`, and the server-side validation (magic bytes and size cap) is in \`validateMagicBytes\` from \`packages/server/src/telephony/attachment-validator.ts\`. [[#server-holds]]`)
};

const es_demo_narrative_admin_branding_body = /** @type {(inputs: Demo_Narrative_Admin_Branding_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La marca contiene el logotipo de la organización, sus dos colores de marca, el texto de bienvenida que el visitante lee en el formulario de admisión y la etiqueta de soporte que el cliente ve en los mensajes del portal. Los campos se almacenan sin cifrado, porque las páginas que los usan se alcanzan antes de que nadie inicie sesión. [[#server-holds #portal]]
**¿Por qué nada de esto va cifrado?** El subdominio de la organización llega en claro en cada petición, y el servidor lo resuelve comparando un slug en texto plano. Un volcado de la base de datos ya enumera todas las organizaciones del servidor con independencia del contenido de estas columnas. El logotipo lo sirve una ruta sin autenticación a páginas a las que el visitante llega sin cuenta. Un diseño anterior cifraba estas columnas con una clave cuya mitad pública estaba en la misma fila, lo cual no protegía ninguno de esos dos hechos y ponía el descifrado en un proceso web que por lo demás no guarda material de claves. [La frontera de confianza](#deep-dive/the-trust-boundary) trata lo que más revela un volcado. [[#encryption #server-holds]]
**¿Cómo se sanea un logotipo?** El navegador redibuja cada archivo aceptado (PNG, JPEG o SVG) como un PNG redimensionado, de modo que no viaja marcado ni código dentro de la imagen. El servidor valida el tipo de archivo y aplica su propio tope de 2 MB antes de almacenar el resultado. Los iconos de la aplicación para la instalación y la pantalla de inicio se generan en un paso separado después del guardado, y un fallo en ese paso levanta su propio aviso mientras el logotipo guardado se mantiene. [[#failure-states]]
**¿Cómo se mantienen legibles los colores?** La aplicación almacena el color de marca tal como se elige y deriva de él dos colores de trabajo, uno de texto y uno de relleno. A cada color de trabajo se le ajusta la luminosidad hasta que supera la relación de contraste WCAG AA de 4,5:1 frente a la peor superficie en la que puede aparecer, por separado en modo claro y en modo oscuro. Un tono elegido que se acerca al rojo reservado para la urgencia o al ocre reservado para el cuidado recibe un aviso con una alternativa desplazada, y se permite guardar el original. [[#failure-states]]
**Editar la marca.** Editar la marca requiere el permiso Gestionar identidad de la organización, la misma concesión que cubre [Información general](#admin-org/general). [[#permissions]]
**Las columnas de marca y la ruta de iconos.** Las columnas en texto plano las introdujo \`packages/server/src/db/migrations/tenant/107_branding_plaintext.ts\`, que eliminó la contraparte cifrada de cada una y dejó intactos \`encrypted_terminology\`, la clave pública de la organización y las claves de los blobs de iconos. Las lecturas y escrituras pasan por \`packages/server/src/branding/branding-service.ts\`. Los iconos se sirven sin autenticación por \`packages/server/src/routes/branding-icons.ts\`, que usa la clave del blob como ETag. El rasterizador en \`packages/client/src/lib/branding/rasterize.ts\` escala a un máximo de 512 píxeles antes de la carga. El cálculo de contraste y proximidad está en \`packages/client/src/lib/branding/konsta-palette.ts\`, y la validación del lado del servidor (bytes iniciales y tope de tamaño) está en \`validateMagicBytes\` de \`packages/server/src/telephony/attachment-validator.ts\`. [[#server-holds]]`)
};

const en_xa2_demo_narrative_admin_branding_body = /** @type {(inputs: Demo_Narrative_Admin_Branding_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Bràndìng hòlds thè òrgànìzàtìòn's lògò, ìts twò brànd còlòrs, thè wèlcòmè tèxt à vìsìtòr rèàds òn thè ìntàkè fòrm, ànd thè sùppòrt làbèl à clìènt sèès òn pòrtàl mèssàgès. Àll fìèlds àrè stòrèd wìthòùt èncryptìòn, bècàùsè thè pàgès thàt ùsè thèm àrè rèàchèd bèfòrè ànyònè sìgns ìn. [[#sèrvèr-hòlds #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why ìs nònè òf ìt èncryptèd? •••••••••** Thè òrgànìzàtìòn's sùbdòmàìn àrrìvès ìn thè clèàr òn èvèry rèqùèst, ànd thè sèrvèr rèsòlvès ìt by còmpàrìng à plàìntèxt slùg. À dàtàbàsè dùmp àlrèàdy lìsts èvèry òrgànìzàtìòn òn thè sèrvèr règàrdlèss òf whàt thèsè còlùmns hòld. Thè lògò ìs sèrvèd by àn ùnàùthèntìcàtèd ròùtè tò pàgès à vìsìtòr rèàchès wìthòùt àn àccòùnt. À prèvìòùs dèsìgn èncryptèd thèsè còlùmns ùndèr à kèy whòsè pùblìc hàlf sàt ìn thè sàmè ròw, whìch pròtèctèd nèìthèr òf thòsè twò fàcts ànd plàcèd dècryptìòn ìnsìdè à wèb pròcèss thàt òthèrwìsè hòlds nò kèy màtèrìàl. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whàt èlsè à dùmp rèvèàls. [[#èncryptìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìs à lògò sànìtìzèd? ••••••••** Thè bròwsèr rèdràws èvèry àccèptèd ùplòàd (PNG, JPÈG, òr SVG) tò à rèsìzèd PNG, sò nò màrkùp òr scrìpt tràvèls ìnsìdè thè ìmàgè. Thè sèrvèr vàlìdàtès thè fìlè typè ànd ènfòrcès ìts òwn 2 MB cèìlìng bèfòrè stòrìng thè rèsùlt. Àpp ìcòns fòr thè ìnstàllèd àpp ànd thè hòmè scrèèn àrè gènèràtèd ìn à sèpàràtè stèp àftèr thè sàvè, ànd à fàìlùrè thèrè ràìsès ìts òwn nòtìcè whìlè thè sàvèd lògò stànds. [[#fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw àrè còlòrs kèpt rèàdàblè? •••••••••** Thè àpp stòrès à brànd còlòr às chòsèn ànd dèrìvès twò wòrkìng còlòrs fròm ìt, à tèxt còlòr ànd à fìll còlòr. Èàch wòrkìng còlòr hàs ìts lìghtnèss àdjùstèd ùntìl ìt clèàrs thè WCÀG ÀÀ còntràst ràtìò òf 4.5:1 àgàìnst thè wòrst sùrfàcè ìt càn lànd òn, sèpàràtèly fòr lìght mòdè ànd dàrk mòdè. À chòsèn shàdè thàt fàlls clòsè tò thè rèd rèsèrvèd fòr ùrgèncy òr thè òchrè rèsèrvèd fòr càrè dràws à nòtìcè òffèrìng à shìftèd àltèrnàtìvè, ànd sàvìng thè òrìgìnàl ìs àllòwèd. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èdìtìng bràndìng. ••••••** Èdìtìng bràndìng rèqùìrès thè Mànàgè òrg ìdèntìty pèrmìssìòn, thè sàmè grànt thàt còvèrs [Gènèràl ìnfò](#àdmìn-òrg/gènèràl). [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••**Thè bràndìng còlùmns ànd thè ìcòn ròùtè. ••••••••••••** Thè plàìntèxt còlùmns wèrè ìntròdùcèd by \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/107_bràndìng_plàìntèxt.ts\`, whìch dròppèd thè èncryptèd còùntèrpàrt fòr èàch ànd lèft \`èncryptèd_tèrmìnòlògy\`, thè òrg pùblìc kèy, ànd thè ìcòn blòb kèys ùntòùchèd. Rèàds ànd wrìtès gò thròùgh \`pàckàgès/sèrvèr/src/bràndìng/bràndìng-sèrvìcè.ts\`. Ìcòns àrè sèrvèd wìthòùt àùthèntìcàtìòn by \`pàckàgès/sèrvèr/src/ròùtès/bràndìng-ìcòns.ts\`, whìch ùsès thè blòb kèy às thè ÈTàg. Thè ràstèrìzèr ìn \`pàckàgès/clìènt/src/lìb/bràndìng/ràstèrìzè.ts\` scàlès tò à 512-pìxèl màxìmùm bèfòrè ùplòàd. Thè còntràst dèrìvàtìòn ànd pròxìmìty chèck àrè ìn \`pàckàgès/clìènt/src/lìb/bràndìng/kònstà-pàlèttè.ts\`, ànd thè sèrvèr-sìdè vàlìdàtìòn (màgìc bytès ànd sìzè càp) ìs ìn \`vàlìdàtèMàgìcBytès\` fròm \`pàckàgès/sèrvèr/src/tèlèphòny/àttàchmènt-vàlìdàtòr.ts\`. [[#sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Branding holds the organization's logo, its two brand colors, the welcome text a visitor reads on the intake form, and the support label a client sees on por..." |
*
* @param {Demo_Narrative_Admin_Branding_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_branding_body = /** @type {((inputs?: Demo_Narrative_Admin_Branding_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Branding_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_branding_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_branding_body(inputs)
	return en_demo_narrative_admin_branding_body(inputs)
});