/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Contact_BodyInputs */

const en_demo_narrative_client_intake_contact_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Contact_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The default form accepts a phone number, an email address, or a refusal as the visitor's contact preference. The answer is encrypted alongside the submission. A new client record carries only a generated alias, with nothing the server could use to match this person against other records. The submission stays unmatched until a user opens the case and writes a contact value onto it. [Possible duplicates](#dashboard/merge-candidates) covers the hashes that comparison needs. [[#client-data #privacy]]
**What does the account option open?** The visitor can set a username and password while filling out the form. The browser derives all keys before sending anything to the server. No password reset exists. A client who forgets the password loses their own copy of the conversation and the channel it traveled through. The organization's ticket stays, and a user holding the Reset client login permission can delete the old account so a new channel can be set up. When the visitor also refused to leave contact details, the organization has no way to reach them, so a forgotten password ends the exchange entirely. [Account sign in](#client-account/sign-in) covers what the client opens afterward. [[#keys #failure-states]]
**What does the link option open?** The alternative is a link that reopens the same conversation without an account. The key travels in the URL fragment after the \`#\`, a portion that browsers do not transmit. Holding the link is the entire access check. Losing the link has the same cost as forgetting a password. The organization can set up a new link if it has another way to reach the client. [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers what the channel is. [[#keys #portal]]
**Why only one of the two?** Expanding one option collapses the other. When a submission carries both, the account takes precedence. Each option creates a separate channel for the same conversation, and two channels would mean two sets of keys that can read it. [[#permissions #portal]]
**The contact assembly and the two channel paths.** \`handleSubmit\` in \`IntakeFormBody.svelte\` collects the contact answers. Labels resolve to the organization's base locale so that queue-facing text is uniform regardless of form language. \`buildAccountPayload\` and \`buildContinuationPayload\` in \`intake-crypto.ts\` prepare the two branches. On the server, \`handleAccountStep\` and \`handleContinuationStep\` in \`packages/server/src/portal/intake-service.ts\` write them inside the submission transaction. [[#portal #server-holds]]`)
};

const es_demo_narrative_client_intake_contact_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Contact_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El formulario predeterminado acepta un número de teléfono, una dirección de correo electrónico o una negativa como preferencia de contacto del visitante. La respuesta se cifra junto con el resto del envío. El registro de cliente nuevo lleva solo un alias generado, sin nada que el servidor pueda usar para vincular a esta persona con otros registros. El envío permanece sin comparar hasta que la persona usuaria abre el caso y escribe un dato de contacto en él. [Posibles duplicados](#dashboard/merge-candidates) trata los hashes que necesita esa comparación. [[#client-data #privacy]]
**¿Qué abre la opción de cuenta?** El visitante puede fijar un nombre de usuario y una contraseña mientras completa el formulario. El navegador deriva todas las claves antes de enviar nada al servidor. No existe restablecimiento de contraseña. Quien olvida la contraseña pierde su copia de la conversación y el canal por el que viajaba. El ticket de la organización permanece, y la persona usuaria con el permiso Restablecer acceso del cliente puede eliminar la cuenta anterior para que se pueda configurar un canal nuevo. Cuando el visitante también rehusó dejar datos de contacto, la organización no tiene forma de comunicarse, así que una contraseña olvidada termina el intercambio por completo. [Inicio de sesión de cuenta](#client-account/sign-in) trata lo que abre el cliente después. [[#keys #failure-states]]
**¿Qué abre la opción de enlace?** La alternativa es un enlace que reabre la misma conversación sin cuenta. La clave viaja en el fragmento de la URL después del \`#\`, una porción que los navegadores no transmiten. Tener el enlace es toda la comprobación de acceso. Perder el enlace tiene el mismo costo que olvidar la contraseña. La organización puede configurar un enlace nuevo si tiene otra forma de comunicarse con el cliente. [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata qué es el canal. [[#keys #portal]]
**¿Por qué solo una de las dos?** Abrir una opción cierra la otra. Cuando un envío lleva ambas, la cuenta tiene prioridad. Cada opción crea un canal distinto para la misma conversación, y dos canales significarían dos conjuntos de claves con acceso de lectura. [[#permissions #portal]]
**El ensamblado de contacto y las dos rutas de canal.** \`handleSubmit\` en \`IntakeFormBody.svelte\` recoge las respuestas de contacto. Las etiquetas se resuelven al idioma base de la organización para que el texto que ve la cola sea uniforme sin importar el idioma del formulario. \`buildAccountPayload\` y \`buildContinuationPayload\` en \`intake-crypto.ts\` preparan las dos ramas. En el servidor, \`handleAccountStep\` y \`handleContinuationStep\` en \`packages/server/src/portal/intake-service.ts\` las escriben dentro de la transacción del envío. [[#portal #server-holds]]`)
};

const en_xa2_demo_narrative_client_intake_contact_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Contact_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè dèfàùlt fòrm àccèpts à phònè nùmbèr, àn èmàìl àddrèss, òr à rèfùsàl às thè vìsìtòr's còntàct prèfèrèncè. Thè ànswèr ìs èncryptèd àlòngsìdè thè sùbmìssìòn. À nèw clìènt rècòrd càrrìès ònly à gènèràtèd àlìàs, wìth nòthìng thè sèrvèr còùld ùsè tò màtch thìs pèrsòn àgàìnst òthèr rècòrds. Thè sùbmìssìòn stàys ùnmàtchèd ùntìl à ùsèr òpèns thè càsè ànd wrìtès à còntàct vàlùè òntò ìt. [Pòssìblè dùplìcàtès](#dàshbòàrd/mèrgè-càndìdàtès) còvèrs thè hàshès thàt còmpàrìsòn nèèds. [[#clìènt-dàtà #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè àccòùnt òptìòn òpèn? •••••••••••** Thè vìsìtòr càn sèt à ùsèrnàmè ànd pàsswòrd whìlè fìllìng òùt thè fòrm. Thè bròwsèr dèrìvès àll kèys bèfòrè sèndìng ànythìng tò thè sèrvèr. Nò pàsswòrd rèsèt èxìsts. À clìènt whò fòrgèts thè pàsswòrd lòsès thèìr òwn còpy òf thè cònvèrsàtìòn ànd thè chànnèl ìt tràvèlèd thròùgh. Thè òrgànìzàtìòn's tìckèt stàys, ànd à ùsèr hòldìng thè Rèsèt clìènt lògìn pèrmìssìòn càn dèlètè thè òld àccòùnt sò à nèw chànnèl càn bè sèt ùp. Whèn thè vìsìtòr àlsò rèfùsèd tò lèàvè còntàct dètàìls, thè òrgànìzàtìòn hàs nò wày tò rèàch thèm, sò à fòrgòttèn pàsswòrd ènds thè èxchàngè èntìrèly. [Àccòùnt sìgn ìn](#clìènt-àccòùnt/sìgn-ìn) còvèrs whàt thè clìènt òpèns àftèrwàrd. [[#kèys #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè lìnk òptìòn òpèn? ••••••••••** Thè àltèrnàtìvè ìs à lìnk thàt rèòpèns thè sàmè cònvèrsàtìòn wìthòùt àn àccòùnt. Thè kèy tràvèls ìn thè ÙRL fràgmènt àftèr thè \`#\`, à pòrtìòn thàt bròwsèrs dò nòt trànsmìt. Hòldìng thè lìnk ìs thè èntìrè àccèss chèck. Lòsìng thè lìnk hàs thè sàmè còst às fòrgèttìng à pàsswòrd. Thè òrgànìzàtìòn càn sèt ùp à nèw lìnk ìf ìt hàs ànòthèr wày tò rèàch thè clìènt. [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs whàt thè chànnèl ìs. [[#kèys #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why ònly ònè òf thè twò? ••••••••** Èxpàndìng ònè òptìòn còllàpsès thè òthèr. Whèn à sùbmìssìòn càrrìès bòth, thè àccòùnt tàkès prècèdèncè. Èàch òptìòn crèàtès à sèpàràtè chànnèl fòr thè sàmè cònvèrsàtìòn, ànd twò chànnèls wòùld mèàn twò sèts òf kèys thàt càn rèàd ìt. [[#pèrmìssìòns #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còntàct àssèmbly ànd thè twò chànnèl pàths. •••••••••••••••** \`hàndlèSùbmìt\` ìn \`ÌntàkèFòrmBòdy.svèltè\` còllècts thè còntàct ànswèrs. Làbèls rèsòlvè tò thè òrgànìzàtìòn's bàsè lòcàlè sò thàt qùèùè-fàcìng tèxt ìs ùnìfòrm règàrdlèss òf fòrm làngùàgè. \`bùìldÀccòùntPàylòàd\` ànd \`bùìldCòntìnùàtìònPàylòàd\` ìn \`ìntàkè-cryptò.ts\` prèpàrè thè twò brànchès. Òn thè sèrvèr, \`hàndlèÀccòùntStèp\` ànd \`hàndlèCòntìnùàtìònStèp\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-sèrvìcè.ts\` wrìtè thèm ìnsìdè thè sùbmìssìòn trànsàctìòn. [[#pòrtàl #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The default form accepts a phone number, an email address, or a refusal as the visitor's contact preference. The answer is encrypted alongside the submission..." |
*
* @param {Demo_Narrative_Client_Intake_Contact_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_contact_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Contact_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Contact_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_contact_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_contact_body(inputs)
	return en_demo_narrative_client_intake_contact_body(inputs)
});