/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Account_Password_BodyInputs */

const en_demo_narrative_client_account_password_body = /** @type {(inputs: Demo_Narrative_Client_Account_Password_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The client's encryption keys derive from the password, so changing the password rebuilds the keys and re-encrypts the conversation. A minimum of eight characters is required. The change either completes entirely or has no effect; a failure partway through leaves the password and the conversation unchanged. [[#keys #portal]]
**Why does a password change re-encrypt messages?** Each message on the channel is sealed to a key pair derived from the password. The browser proves the current password, derives a fresh key pair, decrypts the messages it can open, and re-encrypts each one to the new key. Any message the device could not decrypt stays sealed to the old key and becomes permanently unreadable under the new one. Before submitting, the client is told how many earlier messages would be left out of the change, with a way to back out. [How keys are derived](#deep-dive/how-keys-are-derived) covers the derivation, which follows the same path as sign-in. [[#keys #encryption]]
**What happens when a message arrives mid-change?** The server checks that the re-encrypted messages and the declared-unreadable messages together account for every message on the channel. A message that arrived while the browser was working belongs to neither group, so the server refuses the change. [[#failure-states #encryption]]
**Other sessions.** The change signs out every other session on the account. A session open on another device stops working at that moment. The client's account ID does not change, because it identifies the client rather than the key. [[#server-holds #keys]]
**No password reset.** There is no way for the client to recover a forgotten password. A member of the organization holding the Reset client login permission can delete the account so a new way back in can be set up, at the cost of the client's message copies. [Durable thread](#client-account/thread) covers what the deletion removes. [[#failure-states #retention]]
**The form and its services.** The form is \`AccountSettings.svelte\`. The browser rebuilds registration material through \`buildAccountRegistration\` in \`packages/client/src/lib/portal/account-crypto.ts\`, and the server side is \`changePassword\` in \`packages/server/src/portal/account-service.ts\`. The server runs the credential update, the re-encrypted messages, and the session deletion in a single transaction, so a failure at any step rolls back the whole operation. A member of staff changing their own password follows a different service path on the same derivation shape, which [Password and key re-wrap](#settings/password) covers. [[#keys #server-holds]]`)
};

const es_demo_narrative_client_account_password_body = /** @type {(inputs: Demo_Narrative_Client_Account_Password_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Las claves de cifrado del cliente se derivan de la contraseña, así que cambiar la contraseña reconstruye las claves y vuelve a cifrar la conversación. Se requieren al menos ocho caracteres. El cambio se completa íntegramente o no tiene efecto; un fallo a mitad del proceso deja la contraseña y la conversación sin alterar. [[#keys #portal]]
**¿Por qué cambiar la contraseña vuelve a cifrar los mensajes?** Cada mensaje del canal está sellado con un par de claves derivado de la contraseña. El navegador acredita la contraseña actual, deriva un par de claves nuevo, descifra los mensajes que puede abrir y vuelve a cifrar cada uno con la clave nueva. Los mensajes que el dispositivo no pudo descifrar quedan sellados con la clave anterior y pasan a ser permanentemente ilegibles con la nueva. Antes del envío, se informa al cliente de cuántos mensajes anteriores quedarían fuera del cambio, con la opción de retroceder. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata la derivación, que sigue la misma ruta que el inicio de sesión. [[#keys #encryption]]
**¿Qué pasa cuando un mensaje llega durante el cambio?** El servidor comprueba que los mensajes vueltos a cifrar y los declarados ilegibles cubren juntos cada mensaje del canal. Un mensaje que llegó mientras el navegador trabajaba no pertenece a ninguno de los dos grupos, así que el servidor rechaza el cambio. [[#failure-states #encryption]]
**Otras sesiones.** El cambio cierra todas las demás sesiones de la cuenta. Una sesión abierta en otro dispositivo deja de funcionar en ese momento. El identificador de cuenta del cliente no cambia, porque identifica al cliente y no a su clave. [[#server-holds #keys]]
**Sin restablecimiento de contraseña.** El cliente no tiene forma de recuperar una contraseña olvidada. La persona usuaria con el permiso Restablecer acceso del cliente puede eliminar la cuenta para que se pueda configurar una nueva vía de acceso, a costa de las copias de mensajes del cliente. [Hilo duradero](#client-account/thread) trata lo que elimina esa operación. [[#failure-states #retention]]
**El formulario y sus servicios.** El formulario es \`AccountSettings.svelte\`. El navegador reconstruye el material de registro a través de \`buildAccountRegistration\` en \`packages/client/src/lib/portal/account-crypto.ts\`, y el lado del servidor es \`changePassword\` en \`packages/server/src/portal/account-service.ts\`. El servidor ejecuta la actualización de credenciales, los mensajes vueltos a cifrar y la eliminación de sesiones en una sola transacción, de modo que un fallo en cualquier paso revierte toda la operación. Una persona del personal que cambia su propia contraseña sigue una ruta de servicio distinta sobre la misma forma de derivación, que trata [Contraseña y re-envolvimiento de claves](#settings/password). [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_client_account_password_body = /** @type {(inputs: Demo_Narrative_Client_Account_Password_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè clìènt's èncryptìòn kèys dèrìvè fròm thè pàsswòrd, sò chàngìng thè pàsswòrd rèbùìlds thè kèys ànd rè-èncrypts thè cònvèrsàtìòn. À mìnìmùm òf èìght chàràctèrs ìs rèqùìrèd. Thè chàngè èìthèr còmplètès èntìrèly òr hàs nò èffèct; à fàìlùrè pàrtwày thròùgh lèàvès thè pàsswòrd ànd thè cònvèrsàtìòn ùnchàngèd. [[#kèys #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why dòès à pàsswòrd chàngè rè-èncrypt mèssàgès? •••••••••••••••** Èàch mèssàgè òn thè chànnèl ìs sèàlèd tò à kèy pàìr dèrìvèd fròm thè pàsswòrd. Thè bròwsèr pròvès thè cùrrènt pàsswòrd, dèrìvès à frèsh kèy pàìr, dècrypts thè mèssàgès ìt càn òpèn, ànd rè-èncrypts èàch ònè tò thè nèw kèy. Àny mèssàgè thè dèvìcè còùld nòt dècrypt stàys sèàlèd tò thè òld kèy ànd bècòmès pèrmànèntly ùnrèàdàblè ùndèr thè nèw ònè. Bèfòrè sùbmìttìng, thè clìènt ìs tòld hòw màny èàrlìèr mèssàgès wòùld bè lèft òùt òf thè chàngè, wìth à wày tò bàck òùt. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs thè dèrìvàtìòn, whìch fòllòws thè sàmè pàth às sìgn-ìn. [[#kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn à mèssàgè àrrìvès mìd-chàngè? •••••••••••••••** Thè sèrvèr chècks thàt thè rè-èncryptèd mèssàgès ànd thè dèclàrèd-ùnrèàdàblè mèssàgès tògèthèr àccòùnt fòr èvèry mèssàgè òn thè chànnèl. À mèssàgè thàt àrrìvèd whìlè thè bròwsèr wàs wòrkìng bèlòngs tò nèìthèr gròùp, sò thè sèrvèr rèfùsès thè chàngè. [[#fàìlùrè-stàtès #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Òthèr sèssìòns. •••••** Thè chàngè sìgns òùt èvèry òthèr sèssìòn òn thè àccòùnt. À sèssìòn òpèn òn ànòthèr dèvìcè stòps wòrkìng àt thàt mòmènt. Thè clìènt's àccòùnt ÌD dòès nòt chàngè, bècàùsè ìt ìdèntìfìès thè clìènt ràthèr thàn thè kèy. [[#sèrvèr-hòlds #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Nò pàsswòrd rèsèt. ••••••** Thèrè ìs nò wày fòr thè clìènt tò rècòvèr à fòrgòttèn pàsswòrd. À mèmbèr òf thè òrgànìzàtìòn hòldìng thè Rèsèt clìènt lògìn pèrmìssìòn càn dèlètè thè àccòùnt sò à nèw wày bàck ìn càn bè sèt ùp, àt thè còst òf thè clìènt's mèssàgè còpìès. [Dùràblè thrèàd](#clìènt-àccòùnt/thrèàd) còvèrs whàt thè dèlètìòn rèmòvès. [[#fàìlùrè-stàtès #rètèntìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fòrm ànd ìts sèrvìcès. ••••••••** Thè fòrm ìs \`ÀccòùntSèttìngs.svèltè\`. Thè bròwsèr rèbùìlds règìstràtìòn màtèrìàl thròùgh \`bùìldÀccòùntRègìstràtìòn\` ìn \`pàckàgès/clìènt/src/lìb/pòrtàl/àccòùnt-cryptò.ts\`, ànd thè sèrvèr sìdè ìs \`chàngèPàsswòrd\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/àccòùnt-sèrvìcè.ts\`. Thè sèrvèr rùns thè crèdèntìàl ùpdàtè, thè rè-èncryptèd mèssàgès, ànd thè sèssìòn dèlètìòn ìn à sìnglè trànsàctìòn, sò à fàìlùrè àt àny stèp ròlls bàck thè whòlè òpèràtìòn. À mèmbèr òf stàff chàngìng thèìr òwn pàsswòrd fòllòws à dìffèrènt sèrvìcè pàth òn thè sàmè dèrìvàtìòn shàpè, whìch [Pàsswòrd ànd kèy rè-wràp](#sèttìngs/pàsswòrd) còvèrs. [[#kèys #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The client's encryption keys derive from the password, so changing the password rebuilds the keys and re-encrypts the conversation. A minimum of eight charac..." |
*
* @param {Demo_Narrative_Client_Account_Password_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_account_password_body = /** @type {((inputs?: Demo_Narrative_Client_Account_Password_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Account_Password_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_account_password_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_account_password_body(inputs)
	return en_demo_narrative_client_account_password_body(inputs)
});