/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Settings_Notifications_BodyInputs */

const en_demo_narrative_settings_notifications_body = /** @type {(inputs: Demo_Narrative_Settings_Notifications_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Each event type has a separate switch for push, email and text message, and the user controls which channels carry which events. The in-app feed delivers all events whether or not any switch is on, and a user who has turned off the three switchable channels still sees events when the app is open. An account with no stored preferences has all switches on. [[#privacy #client-data]]
**What does a queue or ticket override do?** A queue override applies to events in that queue and takes priority over the global switch. A per-ticket override takes priority over both. Setting a ticket override requires the user to hold that ticket's key, and the server refuses a ticket the user cannot read and a ticket that does not exist with the same response, so the refusal reveals nothing about whether the ticket exists. [The permission system](#deep-dive/the-permission-system) covers where that access comes from. [[#permissions #metadata]]
**When does a preference not hold?** When the user enabled text messages for an event but has no verified number, the event is skipped for that channel rather than rerouted to email. [[#failure-states #telephony]]
**What does a notification email contain?** An email names the event type and links to the sign-in page. It carries no ticket title, no client alias and no message text. The mail provider learns the address and the time. [What the network sees](#deep-dive/what-the-network-sees) covers what other observers learn from notifications. [[#server-holds #privacy]]
**Where does the notification address come from?** The notification address is visible and manageable from the notification settings. The user can view, change or clear it at any time. [Two factor enrollment](#settings/two-factor) covers how the email second-factor method shares the notification address. [[#server-holds #privacy]]
**What does a database copy show about notification settings?** Each preference row stores the user's ID, the scope, the event type, the channel and whether it is on or off. A database copy shows which queues a user set overrides for and which events a user silenced, which maps what the user watches. [The trust boundary](#deep-dive/the-trust-boundary) covers the rest of the unencrypted schema. [[#metadata #server-holds]]
**The preference cascade and email column.** Cascade resolution and the reset path are in \`packages/server/src/notifications/preferences.ts\`, the table is \`notification_preferences\` in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`, and the fan-out that reads the allow lists is \`packages/server/src/notifications/service.ts\`. Preferences are resolved when a notification is queued, not when it is sent, so a retried delivery uses the original recipient set. Email is sent to \`users.encrypted_notification_addr\`. [[#server-holds]]`)
};

const es_demo_narrative_settings_notifications_body = /** @type {(inputs: Demo_Narrative_Settings_Notifications_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cada tipo de evento tiene un interruptor separado para push, correo electrónico y mensaje de texto, y la persona usuaria controla qué canales llevan qué eventos. Las alertas en la aplicación entregan todos los eventos sin importar el estado de los interruptores, y una persona usuaria que haya apagado los tres canales conmutables sigue viendo los eventos con la aplicación abierta. Una cuenta sin preferencias almacenadas tiene todos los interruptores activados. [[#privacy #client-data]]
**¿Qué hace una excepción de cola o de ticket?** Una excepción de cola se aplica a los eventos de esa cola y tiene prioridad sobre el interruptor global. Una excepción por ticket tiene prioridad sobre ambas. Configurar una excepción de ticket requiere que la persona usuaria posea la clave de ese ticket, y el servidor rechaza un ticket que la persona usuaria no puede leer y un ticket que no existe con la misma respuesta, de modo que el rechazo no revela si el ticket existe. [El sistema de permisos](#deep-dive/the-permission-system) trata de dónde proviene ese acceso. [[#permissions #metadata]]
**¿Cuándo no se respeta una preferencia?** Cuando la persona usuaria activó mensajes de texto para un evento pero no tiene un número verificado, el evento se omite en ese canal en lugar de redirigirse al correo electrónico. [[#failure-states #telephony]]
**¿Qué contiene un correo de notificación?** Un correo nombra el tipo de evento y enlaza a la página de inicio de sesión. No lleva título de ticket, ni alias de cliente ni texto de mensaje. El proveedor de correo conoce la dirección y la hora. [Lo que ve la red](#deep-dive/what-the-network-sees) trata lo que otros observadores aprenden de las notificaciones. [[#server-holds #privacy]]
**¿De dónde viene la dirección de notificación?** La dirección de notificación se puede ver, cambiar y borrar desde las preferencias de notificaciones. La persona usuaria puede consultarla, modificarla o eliminarla en cualquier momento. [Registro de segundo factor](#settings/two-factor) trata cómo el método de segundo factor por correo comparte la dirección de notificación. [[#server-holds #privacy]]
**¿Qué muestra una copia de la base de datos sobre las preferencias de notificación?** Cada fila de preferencia almacena el ID de la persona usuaria, el alcance, el tipo de evento, el canal y si está activado o no. Una copia de la base de datos muestra para qué colas la persona usuaria configuró excepciones y qué eventos silenció, lo que traza un mapa de lo que observa. [La frontera de confianza](#deep-dive/the-trust-boundary) trata el resto del esquema sin cifrar. [[#metadata #server-holds]]
**La cascada de preferencias y la columna de correo.** La resolución de cascada y la ruta de restablecimiento están en \`packages/server/src/notifications/preferences.ts\`, la tabla es \`notification_preferences\`, en \`packages/server/src/db/migrations/tenant/001_baseline.ts\`, y el fan-out que lee las listas de permitidos está en \`packages/server/src/notifications/service.ts\`. Las preferencias se resuelven cuando se encola una notificación, no cuando se envía, de modo que un reintento de entrega usa el conjunto original de destinatarios. El correo se envía a \`users.encrypted_notification_addr\`. [[#server-holds]]`)
};

const en_xa2_demo_narrative_settings_notifications_body = /** @type {(inputs: Demo_Narrative_Settings_Notifications_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èàch èvènt typè hàs à sèpàràtè swìtch fòr pùsh, èmàìl ànd tèxt mèssàgè, ànd thè ùsèr còntròls whìch chànnèls càrry whìch èvènts. Thè ìn-àpp fèèd dèlìvèrs àll èvènts whèthèr òr nòt àny swìtch ìs òn, ànd à ùsèr whò hàs tùrnèd òff thè thrèè swìtchàblè chànnèls stìll sèès èvènts whèn thè àpp ìs òpèn. Àn àccòùnt wìth nò stòrèd prèfèrèncès hàs àll swìtchès òn. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à qùèùè òr tìckèt òvèrrìdè dò? ••••••••••••** À qùèùè òvèrrìdè àpplìès tò èvènts ìn thàt qùèùè ànd tàkès prìòrìty òvèr thè glòbàl swìtch. À pèr-tìckèt òvèrrìdè tàkès prìòrìty òvèr bòth. Sèttìng à tìckèt òvèrrìdè rèqùìrès thè ùsèr tò hòld thàt tìckèt's kèy, ànd thè sèrvèr rèfùsès à tìckèt thè ùsèr cànnòt rèàd ànd à tìckèt thàt dòès nòt èxìst wìth thè sàmè rèspònsè, sò thè rèfùsàl rèvèàls nòthìng àbòùt whèthèr thè tìckèt èxìsts. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs whèrè thàt àccèss còmès fròm. [[#pèrmìssìòns #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn dòès à prèfèrèncè nòt hòld? ••••••••••** Whèn thè ùsèr ènàblèd tèxt mèssàgès fòr àn èvènt bùt hàs nò vèrìfìèd nùmbèr, thè èvènt ìs skìppèd fòr thàt chànnèl ràthèr thàn rèròùtèd tò èmàìl. [[#fàìlùrè-stàtès #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à nòtìfìcàtìòn èmàìl còntàìn? ••••••••••••** Àn èmàìl nàmès thè èvènt typè ànd lìnks tò thè sìgn-ìn pàgè. Ìt càrrìès nò tìckèt tìtlè, nò clìènt àlìàs ànd nò mèssàgè tèxt. Thè màìl pròvìdèr lèàrns thè àddrèss ànd thè tìmè. [Whàt thè nètwòrk sèès](#dèèp-dìvè/whàt-thè-nètwòrk-sèès) còvèrs whàt òthèr òbsèrvèrs lèàrn fròm nòtìfìcàtìòns. [[#sèrvèr-hòlds #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèrè dòès thè nòtìfìcàtìòn àddrèss còmè fròm? ••••••••••••••** Thè nòtìfìcàtìòn àddrèss ìs vìsìblè ànd mànàgèàblè fròm thè nòtìfìcàtìòn sèttìngs. Thè ùsèr càn vìèw, chàngè òr clèàr ìt àt àny tìmè. [Twò fàctòr ènròllmènt](#sèttìngs/twò-fàctòr) còvèrs hòw thè èmàìl sècònd-fàctòr mèthòd shàrès thè nòtìfìcàtìòn àddrèss. [[#sèrvèr-hòlds #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à dàtàbàsè còpy shòw àbòùt nòtìfìcàtìòn sèttìngs? ••••••••••••••••••** Èàch prèfèrèncè ròw stòrès thè ùsèr's ÌD, thè scòpè, thè èvènt typè, thè chànnèl ànd whèthèr ìt ìs òn òr òff. À dàtàbàsè còpy shòws whìch qùèùès à ùsèr sèt òvèrrìdès fòr ànd whìch èvènts à ùsèr sìlèncèd, whìch màps whàt thè ùsèr wàtchès. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè rèst òf thè ùnèncryptèd schèmà. [[#mètàdàtà #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè prèfèrèncè càscàdè ànd èmàìl còlùmn. ••••••••••••** Càscàdè rèsòlùtìòn ànd thè rèsèt pàth àrè ìn \`pàckàgès/sèrvèr/src/nòtìfìcàtìòns/prèfèrèncès.ts\`, thè tàblè ìs \`nòtìfìcàtìòn_prèfèrèncès\` ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`, ànd thè fàn-òùt thàt rèàds thè àllòw lìsts ìs \`pàckàgès/sèrvèr/src/nòtìfìcàtìòns/sèrvìcè.ts\`. Prèfèrèncès àrè rèsòlvèd whèn à nòtìfìcàtìòn ìs qùèùèd, nòt whèn ìt ìs sènt, sò à rètrìèd dèlìvèry ùsès thè òrìgìnàl rècìpìènt sèt. Èmàìl ìs sènt tò \`ùsèrs.èncryptèd_nòtìfìcàtìòn_àddr\`. [[#sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Each event type has a separate switch for push, email and text message, and the user controls which channels carry which events. The in-app feed delivers all..." |
*
* @param {Demo_Narrative_Settings_Notifications_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_settings_notifications_body = /** @type {((inputs?: Demo_Narrative_Settings_Notifications_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Settings_Notifications_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_settings_notifications_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_settings_notifications_body(inputs)
	return en_demo_narrative_settings_notifications_body(inputs)
});