/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Deployment_BodyInputs */

const en_demo_narrative_deepdive_deployment_body = /** @type {(inputs: Demo_Narrative_Deepdive_Deployment_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`CARE-Y ships as one codebase and one Docker image that runs in two deployment types. A hosted multi-tenant deployment at care-y.app serves many organizations. A self-hosted single-tenant deployment serves one organization on its own infrastructure. Instances do not communicate with each other. [[#deep-dive #encryption #server-holds]]
**What differs between the two?** [[#deep-dive #trust-boundary]]
- On the hosted deployment, each organization gets its own PostgreSQL schema. The application server runs on a Hetzner VPS in Germany with full-disk encryption behind a Caddy reverse proxy. The key used during sign-in is split into two shares held by two separate servers joined by mutually authenticated TLS. One server is in the EU and one is in Iceland. Compelling both requires separate legal processes in separate jurisdictions. Both shares are re-randomized every twenty-four hours, and a share taken from one epoch is useless against the other server's share from a different epoch. When either server misses three consecutive heartbeats from the other (forty-five minutes), the surviving server destroys its own share and refuses all sign-in key evaluations until the operator restores from offline escrow. [[#trust-boundary #server-holds #keys]]
- On a self-hosted deployment, one organization runs one schema in the same schema-per-organization design. The sign-in key is split into the same two shares, held by two separate processes. By default both processes run on the operator's machine. The operator can move the second process to a separate server, ideally in a different jurisdiction, following the same procedure as the hosted deployment. Share refresh and the heartbeat monitor activate once the two shares are on separate machines. [[#trust-boundary #server-holds #keys]]
- A self-hosted operator brings its own telephony provider account. The hosted deployment offers both managed and self-managed telephony. [Provider connection](#admin-comms/provider) covers the modes. [[#telephony]]
- The hosted deployment enables the version check by default. Self-hosted instances enable it through a configuration variable and can mirror the version file. The operator of the hosted deployment may publish a signed warrant canary. [[#privacy #server-holds]]
**What applies to both?** Each release carries a manifest of file hashes signed with an offline Ed25519 key. The browser's service worker checks the manifest on install, and a mismatch keeps the old version and shows a warning that cannot be dismissed. An organization can enable a Tor onion address that reaches the same backend. [[#privacy #server-holds]]
**What does choosing between them weigh?** One sign-in key serves every organization on the hosted deployment. Seizing both shares within one twenty-four-hour period would let an attacker attempt offline password guesses against every organization on it at once. Each password is still stretched through a deliberately slow, memory-intensive function that makes each guess expensive. A self-hosted deployment holds one organization's key material only, so a seizure on the hosted side cannot reach it, and a seizure of the self-hosted instance cannot reach anyone else. Organizations facing the strongest adversaries are expected to self-host. The tradeoff is the operational burden of running and patching the instance. [[#deep-dive #encryption #keys]]
[How keys are derived](#deep-dive/how-keys-are-derived) covers the split, the refresh, and the Lagrange combination. [The trust boundary](#deep-dive/the-trust-boundary) covers what any server can read regardless of deployment type. [What CARE-Y is](#deep-dive/what-is-care-y) covers the schema isolation and the contributor package map. [[#deep-dive]]
**The OPRF processes and socket configuration.** [[#keys #server-holds]]
- \`packages/server/src/crypto/oprf-process.ts\` runs evaluation, reached through \`oprf-ipc.ts\`. \`dead-man-switch.ts\` implements the heartbeat monitor and share destruction. [[#keys #server-holds]]
- \`packages/server/src/env.ts\` defines the two OPRF share-server socket settings, defaulting to Unix sockets on one machine. [[#keys #server-holds]]`)
};

const es_demo_narrative_deepdive_deployment_body = /** @type {(inputs: Demo_Narrative_Deepdive_Deployment_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`CARE-Y se distribuye como un solo código base y una sola imagen Docker que funciona en dos tipos de despliegue. Un despliegue alojado multiinquilino en care-y.app sirve a muchas organizaciones. Un despliegue autoalojado sirve a una sola organización en su propia infraestructura. Las instancias no se comunican entre sí. [[#deep-dive #encryption #server-holds]]
**¿Qué difiere entre los dos?** [[#deep-dive #trust-boundary]]
- En el despliegue alojado, cada organización recibe su propio esquema de PostgreSQL. El servidor de aplicación es un VPS de Hetzner en Alemania, con disco cifrado y Caddy como proxy inverso. La clave utilizada durante el inicio de sesión se divide en dos fragmentos custodiados por dos servidores separados unidos por TLS con autenticación mutua. Uno está en la UE y otro en Islandia. Obligar a entregar ambos requiere procesos legales separados en jurisdicciones distintas. Ambos fragmentos se re-aleatorizan cada veinticuatro horas, y un fragmento tomado de una época no sirve contra el fragmento del otro servidor en una época diferente. Cuando cualquiera de los dos servidores pierde tres latidos consecutivos del otro (cuarenta y cinco minutos), el servidor superviviente destruye su propio fragmento y rechaza todas las evaluaciones de clave de inicio de sesión hasta que el operador restaure desde la custodia fuera de línea. [[#trust-boundary #server-holds #keys]]
- En un despliegue autoalojado, una organización ejecuta un esquema en el mismo diseño de esquema por organización. La clave de inicio de sesión se divide en los mismos dos fragmentos, mantenidos por dos procesos separados. Por defecto ambos procesos corren en la máquina del operador. El operador puede mover el segundo proceso a un servidor separado, idealmente en una jurisdicción distinta, siguiendo el mismo procedimiento que el despliegue alojado. La renovación de fragmentos y el monitor de latidos se activan una vez que los dos fragmentos están en máquinas separadas. [[#trust-boundary #server-holds #keys]]
- Quien opera una instancia autoalojada aporta su propia cuenta de proveedor de telefonía. El despliegue alojado ofrece telefonía administrada y autogestionada. [Conexión con el proveedor](#admin-comms/provider) trata los modos. [[#telephony]]
- El despliegue alojado activa la verificación de versión por defecto. Las instancias autoalojadas la activan mediante una variable de configuración y pueden replicar el archivo de versiones. El operador del despliegue alojado puede publicar un canario de orden judicial firmado. [[#privacy #server-holds]]
**¿Qué aplica a ambos?** Cada versión lleva un manifiesto de hashes de archivos firmado con una clave Ed25519 fuera de línea. El service worker del navegador verifica el manifiesto durante la instalación, y una discrepancia conserva la versión anterior y muestra una advertencia que no se puede descartar. Una organización puede habilitar una dirección onion de Tor que alcance el mismo backend. [[#privacy #server-holds]]
**¿Qué se sopesa al elegir entre ellos?** Una sola clave de inicio de sesión sirve a todas las organizaciones del despliegue alojado. Incautar ambos fragmentos dentro de un periodo de veinticuatro horas permitiría a un atacante intentar adivinar contraseñas fuera de línea contra todas las organizaciones a la vez. Cada contraseña sigue estirada a través de una función deliberadamente lenta y exigente en memoria que encarece cada intento. Un despliegue autoalojado contiene el material de clave de una sola organización, así que una incautación en el lado alojado no lo alcanza, y una incautación de la instancia autoalojada no alcanza a nadie más. Se espera que las organizaciones que enfrentan a los adversarios más fuertes opten por el autoalojamiento. La contrapartida es la carga operativa de mantener y actualizar la instancia. [[#deep-dive #encryption #keys]]
[Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata la división, la renovación y la combinación de Lagrange. [La frontera de confianza](#deep-dive/the-trust-boundary) trata lo que cualquier servidor puede leer independientemente del tipo de despliegue. [Qué es CARE-Y](#deep-dive/what-is-care-y) trata el aislamiento de esquemas y el mapa de paquetes para contribuidores. [[#deep-dive]]
**Los procesos OPRF y la configuración de sockets.** [[#keys #server-holds]]
- \`packages/server/src/crypto/oprf-process.ts\` ejecuta la evaluación y se alcanza a través de \`oprf-ipc.ts\`. \`dead-man-switch.ts\` implementa el monitor de latidos y la destrucción de fragmentos. [[#keys #server-holds]]
- \`packages/server/src/env.ts\` define los dos ajustes de socket de los servidores de fragmentos OPRF, con sockets Unix en una máquina por defecto. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_deepdive_deployment_body = /** @type {(inputs: Demo_Narrative_Deepdive_Deployment_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦CÀRÈ-Y shìps às ònè còdèbàsè ànd ònè Dòckèr ìmàgè thàt rùns ìn twò dèplòymènt typès. À hòstèd mùltì-tènànt dèplòymènt àt càrè-y.àpp sèrvès màny òrgànìzàtìòns. À sèlf-hòstèd sìnglè-tènànt dèplòymènt sèrvès ònè òrgànìzàtìòn òn ìts òwn ìnfràstrùctùrè. Ìnstàncès dò nòt còmmùnìcàtè wìth èàch òthèr. [[#dèèp-dìvè #èncryptìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dìffèrs bètwèèn thè twò? •••••••••** [[#dèèp-dìvè #trùst-bòùndàry]]
- Òn thè hòstèd dèplòymènt, èàch òrgànìzàtìòn gèts ìts òwn PòstgrèSQL schèmà. Thè àpplìcàtìòn sèrvèr rùns òn à Hètznèr VPS ìn Gèrmàny wìth fùll-dìsk èncryptìòn bèhìnd à Càddy rèvèrsè pròxy. Thè kèy ùsèd dùrìng sìgn-ìn ìs splìt ìntò twò shàrès hèld by twò sèpàràtè sèrvèrs jòìnèd by mùtùàlly àùthèntìcàtèd TLS. Ònè sèrvèr ìs ìn thè ÈÙ ànd ònè ìs ìn Ìcèlànd. Còmpèllìng bòth rèqùìrès sèpàràtè lègàl pròcèssès ìn sèpàràtè jùrìsdìctìòns. Bòth shàrès àrè rè-ràndòmìzèd èvèry twènty-fòùr hòùrs, ànd à shàrè tàkèn fròm ònè èpòch ìs ùsèlèss àgàìnst thè òthèr sèrvèr's shàrè fròm à dìffèrènt èpòch. Whèn èìthèr sèrvèr mìssès thrèè cònsècùtìvè hèàrtbèàts fròm thè òthèr (fòrty-fìvè mìnùtès), thè sùrvìvìng sèrvèr dèstròys ìts òwn shàrè ànd rèfùsès àll sìgn-ìn kèy èvàlùàtìòns ùntìl thè òpèràtòr rèstòrès fròm òfflìnè èscròw. [[#trùst-bòùndàry #sèrvèr-hòlds #kèys]]
- Òn à sèlf-hòstèd dèplòymènt, ònè òrgànìzàtìòn rùns ònè schèmà ìn thè sàmè schèmà-pèr-òrgànìzàtìòn dèsìgn. Thè sìgn-ìn kèy ìs splìt ìntò thè sàmè twò shàrès, hèld by twò sèpàràtè pròcèssès. By dèfàùlt bòth pròcèssès rùn òn thè òpèràtòr's màchìnè. Thè òpèràtòr càn mòvè thè sècònd pròcèss tò à sèpàràtè sèrvèr, ìdèàlly ìn à dìffèrènt jùrìsdìctìòn, fòllòwìng thè sàmè pròcèdùrè às thè hòstèd dèplòymènt. Shàrè rèfrèsh ànd thè hèàrtbèàt mònìtòr àctìvàtè òncè thè twò shàrès àrè òn sèpàràtè màchìnès. [[#trùst-bòùndàry #sèrvèr-hòlds #kèys]]
- À sèlf-hòstèd òpèràtòr brìngs ìts òwn tèlèphòny pròvìdèr àccòùnt. Thè hòstèd dèplòymènt òffèrs bòth mànàgèd ànd sèlf-mànàgèd tèlèphòny. [Pròvìdèr cònnèctìòn](#àdmìn-còmms/pròvìdèr) còvèrs thè mòdès. [[#tèlèphòny]]
- Thè hòstèd dèplòymènt ènàblès thè vèrsìòn chèck by dèfàùlt. Sèlf-hòstèd ìnstàncès ènàblè ìt thròùgh à cònfìgùràtìòn vàrìàblè ànd càn mìrròr thè vèrsìòn fìlè. Thè òpèràtòr òf thè hòstèd dèplòymènt mày pùblìsh à sìgnèd wàrrànt cànàry. [[#prìvàcy #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt àpplìès tò bòth? •••••••** Èàch rèlèàsè càrrìès à mànìfèst òf fìlè hàshès sìgnèd wìth àn òfflìnè Èd25519 kèy. Thè bròwsèr's sèrvìcè wòrkèr chècks thè mànìfèst òn ìnstàll, ànd à mìsmàtch kèèps thè òld vèrsìòn ànd shòws à wàrnìng thàt cànnòt bè dìsmìssèd. Àn òrgànìzàtìòn càn ènàblè à Tòr ònìòn àddrèss thàt rèàchès thè sàmè bàckènd. [[#prìvàcy #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès chòòsìng bètwèèn thèm wèìgh? ••••••••••••** Ònè sìgn-ìn kèy sèrvès èvèry òrgànìzàtìòn òn thè hòstèd dèplòymènt. Sèìzìng bòth shàrès wìthìn ònè twènty-fòùr-hòùr pèrìòd wòùld lèt àn àttàckèr àttèmpt òfflìnè pàsswòrd gùèssès àgàìnst èvèry òrgànìzàtìòn òn ìt àt òncè. Èàch pàsswòrd ìs stìll strètchèd thròùgh à dèlìbèràtèly slòw, mèmòry-ìntènsìvè fùnctìòn thàt màkès èàch gùèss èxpènsìvè. À sèlf-hòstèd dèplòymènt hòlds ònè òrgànìzàtìòn's kèy màtèrìàl ònly, sò à sèìzùrè òn thè hòstèd sìdè cànnòt rèàch ìt, ànd à sèìzùrè òf thè sèlf-hòstèd ìnstàncè cànnòt rèàch ànyònè èlsè. Òrgànìzàtìòns fàcìng thè stròngèst àdvèrsàrìès àrè èxpèctèd tò sèlf-hòst. Thè tràdèòff ìs thè òpèràtìònàl bùrdèn òf rùnnìng ànd pàtchìng thè ìnstàncè. [[#dèèp-dìvè #èncryptìòn #kèys]]
[Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs thè splìt, thè rèfrèsh, ànd thè Làgràngè còmbìnàtìòn. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whàt àny sèrvèr càn rèàd règàrdlèss òf dèplòymènt typè. [Whàt CÀRÈ-Y ìs](#dèèp-dìvè/whàt-ìs-càrè-y) còvèrs thè schèmà ìsòlàtìòn ànd thè còntrìbùtòr pàckàgè màp. [[#dèèp-dìvè]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè ÒPRF pròcèssès ànd sòckèt cònfìgùràtìòn. ••••••••••••••** [[#kèys #sèrvèr-hòlds]]
- \`pàckàgès/sèrvèr/src/cryptò/òprf-pròcèss.ts\` rùns èvàlùàtìòn, rèàchèd thròùgh \`òprf-ìpc.ts\`. \`dèàd-màn-swìtch.ts\` ìmplèmènts thè hèàrtbèàt mònìtòr ànd shàrè dèstrùctìòn. [[#kèys #sèrvèr-hòlds]]
- \`pàckàgès/sèrvèr/src/ènv.ts\` dèfìnès thè twò ÒPRF shàrè-sèrvèr sòckèt sèttìngs, dèfàùltìng tò Ùnìx sòckèts òn ònè màchìnè. [[#kèys #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "CARE-Y ships as one codebase and one Docker image that runs in two deployment types. A hosted multi-tenant deployment at care-y.app serves many organizations..." |
*
* @param {Demo_Narrative_Deepdive_Deployment_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_deployment_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Deployment_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Deployment_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_deployment_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_deployment_body(inputs)
	return en_demo_narrative_deepdive_deployment_body(inputs)
});