/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Privacy_Notice_BodyInputs */

const en_demo_narrative_client_privacy_notice_body = /** @type {(inputs: Demo_Narrative_Client_Privacy_Notice_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The privacy notice sets out who collects a submission, what is collected, who can open it, how long it is kept and what the visitor can ask for afterward, across the ten disclosure sections a European data protection regime expects. It is reachable from every client page rather than only from the form, so the answer is available before the decision to type and afterward. [[#privacy #client-data]]
**What it says about who can read a submission.** The notice states that the people helping decrypt on their own devices, that the organization's key can open a submission until someone first takes the case, and that access narrows to the people working it from then on. That is the same two-state claim the form makes where the visitor is deciding what to type, in the same words, so the two surfaces cannot be read as two different promises. [How the visitor is protected](#client-intake/how-protected) covers the wraps behind it. [[#keys #privacy]]
**What the phone provider keeps.** A call or a text reaches the organization through a telephony provider, and the notice names it, names the country it operates in and states that it holds the phone number for up to 150 days and message content for up to 60. That retention sits outside the encryption boundary, the organization cannot shorten it, and the notice says so rather than leaving a visitor to assume the encryption covers the carrier. The cross-border transfer is disclosed with the contractual basis it rests on. [The telephony relay](#deep-dive/the-telephony-relay) covers what leaves the boundary on a call. [[#telephony #trust-boundary]]
**How long the organization keeps it.** Encrypted case data is kept while the case is open and for whatever period the organization set afterward, and a daily purge deletes closed cases past that cutoff along with the client record when its last case goes. An organization that sets no period keeps case data until it deletes it by hand. [Data retention](#deep-dive/data-retention) covers the deletion order, and [Retention](#admin-org/retention) covers where the period is set. [[#retention #server-holds]]
**What a visitor can ask for, and what they need to ask with.** The notice offers access, correction, deletion, restriction of use and a copy of what was provided, and it tells the visitor to quote the reference code the submission returned. The code is the practical part of the right, because the organization holds a generated alias rather than a name it can search on, so a request without the code describes a person the organization has no way to find. [Submission](#client-intake/submit) covers where that code comes from. [[#client-data #metadata]]
**Cookies, and what the page itself writes.** The notice states that the site sets only the cookies the form needs to work and that none of them track the visitor. The form writes nothing of its own, and the two controls that do write persistent state are the language picker, which sets a preference cookie, and the colour-scheme toggle, which writes to local storage. [The intake page](#client-intake/form) covers the traces a visit leaves on the device. [[#privacy #client-data]]
**The page and the one value that varies.** The notice is \`packages/client/src/routes/(client)/intake/privacy/+page.svelte\`, which renders the \`intake_privacy_*\` messages from the shared catalog and embeds \`intake_retention_disclosure\` verbatim under the retention heading. The organization's name is the only value substituted per deployment, read from the public branding response or from the name injected into the page, and it is plaintext rather than ciphertext because branding is not secret. The page holds no key material, and it re-renders on a language change so a visitor who switches language mid-read gets the whole notice again in the new one. [[#server-holds #privacy]]`)
};

const es_demo_narrative_client_privacy_notice_body = /** @type {(inputs: Demo_Narrative_Client_Privacy_Notice_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El aviso de privacidad expone quién recoge un envío, qué se recoge, quién puede abrirlo, cuánto tiempo se conserva y qué puede pedir el visitante después, a lo largo de las diez secciones de divulgación que espera un régimen europeo de protección de datos. Es accesible desde todas las páginas del cliente y no solo desde el formulario, de modo que la respuesta está disponible antes de decidir escribir y también después. [[#privacy #client-data]]
**Lo que dice sobre quién puede leer un envío.** El aviso indica que las personas que atienden descifran en sus propios dispositivos, que la clave de la organización puede abrir un envío hasta que alguien toma el caso por primera vez y que a partir de entonces el acceso se restringe a quienes lo trabajan. Esa es la misma afirmación de dos estados que hace el formulario allí donde el visitante decide qué escribir, con las mismas palabras, así que las dos superficies no pueden leerse como dos promesas distintas. [Cómo se protege al visitante](#client-intake/how-protected) trata las envolturas que hay detrás. [[#keys #privacy]]
**Lo que conserva el proveedor telefónico.** Una llamada o un mensaje de texto llega a la organización a través de un proveedor de telefonía, y el aviso lo nombra, nombra el país en el que opera e indica que guarda el número de teléfono hasta 150 días y el contenido de los mensajes hasta 60. Esa conservación queda fuera de la frontera de cifrado, la organización no puede acortarla, y el aviso lo dice en lugar de dejar que el visitante suponga que el cifrado cubre a la operadora. La transferencia internacional se divulga junto con la base contractual en la que se apoya. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que sale de la frontera en una llamada. [[#telephony #trust-boundary]]
**Cuánto tiempo lo conserva la organización.** Los datos cifrados del caso se conservan mientras el caso está abierto y durante el periodo que la organización haya fijado después, y una purga diaria elimina los casos cerrados que han pasado ese límite junto con el registro de cliente cuando se elimina su último caso. Una organización que no fija ningún periodo conserva los datos del caso hasta que los borra a mano. [Conservación de datos](#deep-dive/data-retention) trata el orden de borrado, y [Conservación](#admin-org/retention) trata dónde se fija el periodo. [[#retention #server-holds]]
**Lo que puede pedir un visitante y lo que necesita para pedirlo.** El aviso ofrece acceso, rectificación, supresión, limitación del uso y una copia de lo aportado, e indica al visitante que cite el código de referencia que devolvió el envío. El código es la parte práctica del derecho, porque la organización guarda un alias generado y no un nombre por el que pueda buscar, así que una petición sin el código describe a una persona que la organización no tiene forma de localizar. [Envío](#client-intake/submit) trata de dónde sale ese código. [[#client-data #metadata]]
**Las cookies y lo que escribe la propia página.** El aviso indica que el sitio establece solo las cookies que el formulario necesita para funcionar y que ninguna de ellas rastrea al visitante. El formulario no escribe nada propio, y los dos controles que sí escriben estado persistente son el selector de idioma, que fija una cookie de preferencia, y el conmutador de esquema de color, que escribe en el almacenamiento local. [La página de admisión](#client-intake/form) trata los rastros que deja una visita en el dispositivo. [[#privacy #client-data]]
**La página y el único valor que varía.** El aviso es \`packages/client/src/routes/(client)/intake/privacy/+page.svelte\`, que muestra los mensajes \`intake_privacy_*\` del catálogo compartido e inserta \`intake_retention_disclosure\` tal cual bajo el encabezado de conservación. El nombre de la organización es el único valor que se sustituye por despliegue, leído de la respuesta de identidad pública o del nombre inyectado en la página, y va en texto plano y no cifrado porque la identidad visual no es secreta. La página no contiene material de claves, y se vuelve a representar al cambiar de idioma, de modo que quien cambie de idioma a media lectura recibe el aviso entero en el nuevo. [[#server-holds #privacy]]`)
};

const en_xa2_demo_narrative_client_privacy_notice_body = /** @type {(inputs: Demo_Narrative_Client_Privacy_Notice_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè prìvàcy nòtìcè sèts òùt whò còllècts à sùbmìssìòn, whàt ìs còllèctèd, whò càn òpèn ìt, hòw lòng ìt ìs kèpt ànd whàt thè vìsìtòr càn àsk fòr àftèrwàrd, àcròss thè tèn dìsclòsùrè sèctìòns à Èùròpèàn dàtà pròtèctìòn règìmè èxpècts. Ìt ìs rèàchàblè fròm èvèry clìènt pàgè ràthèr thàn ònly fròm thè fòrm, sò thè ànswèr ìs àvàìlàblè bèfòrè thè dècìsìòn tò typè ànd àftèrwàrd. [[#prìvàcy #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt ìt sàys àbòùt whò càn rèàd à sùbmìssìòn. ••••••••••••••** Thè nòtìcè stàtès thàt thè pèòplè hèlpìng dècrypt òn thèìr òwn dèvìcès, thàt thè òrgànìzàtìòn's kèy càn òpèn à sùbmìssìòn ùntìl sòmèònè fìrst tàkès thè càsè, ànd thàt àccèss nàrròws tò thè pèòplè wòrkìng ìt fròm thèn òn. Thàt ìs thè sàmè twò-stàtè clàìm thè fòrm màkès whèrè thè vìsìtòr ìs dècìdìng whàt tò typè, ìn thè sàmè wòrds, sò thè twò sùrfàcès cànnòt bè rèàd às twò dìffèrènt pròmìsès. [Hòw thè vìsìtòr ìs pròtèctèd](#clìènt-ìntàkè/hòw-pròtèctèd) còvèrs thè wràps bèhìnd ìt. [[#kèys #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè phònè pròvìdèr kèèps. •••••••••** À càll òr à tèxt rèàchès thè òrgànìzàtìòn thròùgh à tèlèphòny pròvìdèr, ànd thè nòtìcè nàmès ìt, nàmès thè còùntry ìt òpèràtès ìn ànd stàtès thàt ìt hòlds thè phònè nùmbèr fòr ùp tò 150 dàys ànd mèssàgè còntènt fòr ùp tò 60. Thàt rètèntìòn sìts òùtsìdè thè èncryptìòn bòùndàry, thè òrgànìzàtìòn cànnòt shòrtèn ìt, ànd thè nòtìcè sàys sò ràthèr thàn lèàvìng à vìsìtòr tò àssùmè thè èncryptìòn còvèrs thè càrrìèr. Thè cròss-bòrdèr trànsfèr ìs dìsclòsèd wìth thè còntràctùàl bàsìs ìt rèsts òn. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt lèàvès thè bòùndàry òn à càll. [[#tèlèphòny #trùst-bòùndàry]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw lòng thè òrgànìzàtìòn kèèps ìt. •••••••••••** Èncryptèd càsè dàtà ìs kèpt whìlè thè càsè ìs òpèn ànd fòr whàtèvèr pèrìòd thè òrgànìzàtìòn sèt àftèrwàrd, ànd à dàìly pùrgè dèlètès clòsèd càsès pàst thàt cùtòff àlòng wìth thè clìènt rècòrd whèn ìts làst càsè gòès. Àn òrgànìzàtìòn thàt sèts nò pèrìòd kèèps càsè dàtà ùntìl ìt dèlètès ìt by hànd. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thè dèlètìòn òrdèr, ànd [Rètèntìòn](#àdmìn-òrg/rètèntìòn) còvèrs whèrè thè pèrìòd ìs sèt. [[#rètèntìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt à vìsìtòr càn àsk fòr, ànd whàt thèy nèèd tò àsk wìth. ••••••••••••••••••** Thè nòtìcè òffèrs àccèss, còrrèctìòn, dèlètìòn, rèstrìctìòn òf ùsè ànd à còpy òf whàt wàs pròvìdèd, ànd ìt tèlls thè vìsìtòr tò qùòtè thè rèfèrèncè còdè thè sùbmìssìòn rètùrnèd. Thè còdè ìs thè pràctìcàl pàrt òf thè rìght, bècàùsè thè òrgànìzàtìòn hòlds à gènèràtèd àlìàs ràthèr thàn à nàmè ìt càn sèàrch òn, sò à rèqùèst wìthòùt thè còdè dèscrìbès à pèrsòn thè òrgànìzàtìòn hàs nò wày tò fìnd. [Sùbmìssìòn](#clìènt-ìntàkè/sùbmìt) còvèrs whèrè thàt còdè còmès fròm. [[#clìènt-dàtà #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Còòkìès, ànd whàt thè pàgè ìtsèlf wrìtès. •••••••••••••** Thè nòtìcè stàtès thàt thè sìtè sèts ònly thè còòkìès thè fòrm nèèds tò wòrk ànd thàt nònè òf thèm tràck thè vìsìtòr. Thè fòrm wrìtès nòthìng òf ìts òwn, ànd thè twò còntròls thàt dò wrìtè pèrsìstènt stàtè àrè thè làngùàgè pìckèr, whìch sèts à prèfèrèncè còòkìè, ànd thè còlòùr-schèmè tògglè, whìch wrìtès tò lòcàl stòràgè. [Thè ìntàkè pàgè](#clìènt-ìntàkè/fòrm) còvèrs thè tràcès à vìsìt lèàvès òn thè dèvìcè. [[#prìvàcy #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pàgè ànd thè ònè vàlùè thàt vàrìès. ••••••••••••** Thè nòtìcè ìs \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/prìvàcy/+pàgè.svèltè\`, whìch rèndèrs thè \`ìntàkè_prìvàcy_*\` mèssàgès fròm thè shàrèd càtàlòg ànd èmbèds \`ìntàkè_rètèntìòn_dìsclòsùrè\` vèrbàtìm ùndèr thè rètèntìòn hèàdìng. Thè òrgànìzàtìòn's nàmè ìs thè ònly vàlùè sùbstìtùtèd pèr dèplòymènt, rèàd fròm thè pùblìc bràndìng rèspònsè òr fròm thè nàmè ìnjèctèd ìntò thè pàgè, ànd ìt ìs plàìntèxt ràthèr thàn cìphèrtèxt bècàùsè bràndìng ìs nòt sècrèt. Thè pàgè hòlds nò kèy màtèrìàl, ànd ìt rè-rèndèrs òn à làngùàgè chàngè sò à vìsìtòr whò swìtchès làngùàgè mìd-rèàd gèts thè whòlè nòtìcè àgàìn ìn thè nèw ònè. [[#sèrvèr-hòlds #prìvàcy]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The privacy notice sets out who collects a submission, what is collected, who can open it, how long it is kept and what the visitor can ask for afterward, ac..." |
*
* @param {Demo_Narrative_Client_Privacy_Notice_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_privacy_notice_body = /** @type {((inputs?: Demo_Narrative_Client_Privacy_Notice_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Privacy_Notice_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_privacy_notice_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_privacy_notice_body(inputs)
	return en_demo_narrative_client_privacy_notice_body(inputs)
});