/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Account_Sign_In_BodyInputs */

const en_demo_narrative_client_account_sign_in_body = /** @type {(inputs: Demo_Narrative_Client_Account_Sign_In_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The account page opens on a sign-in form whenever the tab holds no keys, which covers a first visit, a reload and a return after a timeout, because the keys that open the conversation come from the password and are stored nowhere. [[#portal #keys]]
**What the password produces.** The browser stretches the password, folds the result into a blinded value that an evaluation answers, and derives from the answer both the keypair that opens the client's messages and the bearer token that proves the account to the server. The password, and everything derived from it, stays inside a worker on the device. [How keys are derived](#deep-dive/how-keys-are-derived) covers the evaluation and the two holders that answer it, which are the same ones a member of staff signs in through. [[#keys #encryption]]
**What an unknown username gets back.** A request for the salt of a username is answered with a real salt or with a deterministic fake one, both computed on every request rather than the fake one only on a miss, and the sign-in that follows compares against a fixed dummy value when no account exists so the work is the same either way. A wrong password, a wrong username and an account that was never created produce one failure with nothing to tell them apart. [[#server-holds #privacy]]
**Where a username can still be probed.** Account creation has to tell a client that a name is already taken, so that path answers a probe where sign-in does not. It sits behind a rate limit and a proof-of-work puzzle and returns nothing else about the account it refused. [Security upgrades](#client-portal/account-upgrade) covers where accounts are created. [[#failure-states #metadata]]
**The session and the keys, which end separately.** A sign-in writes a session cookie marked HttpOnly, SameSite=Strict and Path=/, with no domain attribute and the Secure flag behind TLS, valid for twenty-four hours, and the server keeps a hash of the token rather than the token. The keys live in the tab instead: fifteen minutes without human input returns the page to this form, and closing the tab discards them, while the cookie is untouched by either. [Quick exit](#client-portal/quick-exit) covers the one path that ends the server-side session early. [[#server-holds #keys #failure-states]]
**How often a sign-in can be attempted.** Salt requests and sign-in attempts are capped per address per hour, at ten of each in production, and expired session rows are cleared on each successful sign-in. [[#failure-states #server-holds]]
**The sign-in path and the account row.** The form is \`AccountLoginForm.svelte\` in \`packages/client/src/lib/portal/\`, the derivation runs in the portal worker through \`account-crypto.ts\` beside it and \`packages/crypto/src/client-account.ts\`, and the server side is \`getSaltForUsername\` and \`login\` in \`packages/server/src/portal/account-service.ts\` against the tables from \`092_client_accounts.ts\`. [[#keys #server-holds]]`)
};

const es_demo_narrative_client_account_sign_in_body = /** @type {(inputs: Demo_Narrative_Client_Account_Sign_In_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La página de la cuenta se abre en un formulario de inicio de sesión siempre que la pestaña no tiene claves, lo que incluye una primera visita, una recarga y un regreso tras un cierre por inactividad, porque las claves que abren la conversación salen de la contraseña y no se guardan en ninguna parte. [[#portal #keys]]
**Lo que produce la contraseña.** El navegador estira la contraseña, integra el resultado en un valor cegado que una evaluación responde y deriva de esa respuesta tanto el par de claves que abre los mensajes del cliente como el testigo de acceso que acredita la cuenta ante el servidor. La contraseña, y todo lo derivado de ella, se queda dentro de un worker en el dispositivo. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata la evaluación y los dos titulares que la responden, que son los mismos por los que inicia sesión el personal. [[#keys #encryption]]
**Lo que devuelve un nombre de usuario desconocido.** Una petición de la sal de un nombre de usuario se responde con una sal real o con una falsa determinista, ambas calculadas en cada petición y no solo la falsa cuando no hay coincidencia, y el inicio de sesión posterior compara contra un valor ficticio fijo cuando no existe ninguna cuenta, de modo que el trabajo es el mismo en los dos casos. Una contraseña equivocada, un nombre de usuario equivocado y una cuenta que nunca se creó producen un único fallo sin nada que los distinga. [[#server-holds #privacy]]
**Dónde se puede sondear todavía un nombre de usuario.** La creación de cuentas tiene que avisar al cliente de que un nombre ya está ocupado, así que esa vía responde a un sondeo donde el inicio de sesión no lo hace. Está detrás de un límite de frecuencia y de un problema de prueba de trabajo, y no devuelve nada más sobre la cuenta que rechazó. [Mejoras de seguridad](#client-portal/account-upgrade) trata dónde se crean las cuentas. [[#failure-states #metadata]]
**La sesión y las claves, que terminan por separado.** Un inicio de sesión escribe una cookie de sesión marcada HttpOnly, SameSite=Strict y Path=/, sin atributo de dominio y con la marca Secure detrás de TLS, válida durante veinticuatro horas, y el servidor guarda un hash del testigo y no el testigo. Las claves viven en la pestaña: quince minutos sin actividad humana devuelven la página a este formulario, y cerrar la pestaña las descarta, mientras que la cookie no se ve afectada por ninguna de las dos cosas. [Salida rápida](#client-portal/quick-exit) trata la única vía que termina antes la sesión del servidor. [[#server-holds #keys #failure-states]]
**Con qué frecuencia se puede intentar un inicio de sesión.** Las peticiones de sal y los intentos de inicio de sesión están limitados por dirección y por hora, a diez de cada uno en producción, y las filas de sesión caducadas se borran en cada inicio de sesión correcto. [[#failure-states #server-holds]]
**La ruta de inicio de sesión y la fila de la cuenta.** El formulario es \`AccountLoginForm.svelte\`, en \`packages/client/src/lib/portal/\`; la derivación corre en el worker del portal mediante \`account-crypto.ts\`, junto a él, y \`packages/crypto/src/client-account.ts\`; y el lado del servidor son \`getSaltForUsername\` y \`login\`, en \`packages/server/src/portal/account-service.ts\`, contra las tablas de \`092_client_accounts.ts\`. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_client_account_sign_in_body = /** @type {(inputs: Demo_Narrative_Client_Account_Sign_In_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè àccòùnt pàgè òpèns tò à sìgn ìn fòrm whèn thèrè ìs nò àctìvè sèssìòn.
 •••••••••••••••••••••••**Hòw ìt wòrks. ••••** Thè pàsswòrd nèvèr lèàvès thè dèvìcè. Sìgnìng ìn dèrìvès èncryptìòn kèys fròm ìt thròùgh à dèlìbèràtèly slòw lòcàl còmpùtàtìòn còmbìnèd wìth à sèrvèr ròùnd trìp.
 •••••••••••••••••••••••••••••••••••••••••••••••••**Sèssìòn. •••** À sùccèssfùl sìgn ìn wrìtès à sèssìòn còòkìè wìth à 24 hòùr èxpìry ànd lòàds thè clìènt's cònvèrsàtìòn thrèàd. Dècryptìòn kèys lìvè ìn pàgè mèmòry, ànd à 15 mìnùtè ìdlè tìmèr thàt wàrns àt thè tèn mìnùtè màrk zèròs thèm ànd rètùrns tò thè sìgn ìn fòrm, sò rèlòàdìng òr rètùrnìng àftèr ìnàctìvìty mèàns rètypìng thè pàsswòrd.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ùnknòwn ùsèrnàmès. ••••••** Thè sèrvèr ànswèrs ùnknòwn ùsèrnàmès wìth à dètèrmìnìstìc fàkè sàlt ànd rùns thè sàmè còmpàrìsòn pàth ìt ùsès fòr rèàl àccòùnts, sò à wròng pàsswòrd, à wròng ùsèrnàmè, ànd à nònèxìstènt àccòùnt àll pròdùcè thè sàmè gènèrìc fàìlùrè. Thè lògìn sìdè òf àccòùnt ènùmèràtìòn ìs fùlly dèfèndèd. Thè crèàtìòn sìdè mùst tèll thè lègìtìmàtè clìènt whèn à ùsèrnàmè ìs tàkèn, whìch mèàns àn àttàckèr càn pròbè ùsèrnàmès tòò, bùt thè ànònymòùs crèàtìòn pàth sìts bèhìnd thè ìntàkè ràtè lìmìt ànd pròòf òf wòrk, thè ìn-pòrtàl pàth rèqùìrès sècùrè lìnk chànnèl àùthèntìcàtìòn, ànd nèìthèr rètùrns àny òthèr àccòùnt dàtà. •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The account page opens on a sign-in form whenever the tab holds no keys, which covers a first visit, a reload and a return after a timeout, because the keys ..." |
*
* @param {Demo_Narrative_Client_Account_Sign_In_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_account_sign_in_body = /** @type {((inputs?: Demo_Narrative_Client_Account_Sign_In_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Account_Sign_In_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_account_sign_in_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_account_sign_in_body(inputs)
	return en_demo_narrative_client_account_sign_in_body(inputs)
});