/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Submit_BodyInputs */

const en_demo_narrative_client_intake_submit_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Submit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Submitting encrypts every answer in the browser, composes the case title and body from them there as well, and sends ciphertext the server has no key for. The server creates the case, routes it and tells the destination queue's members that something arrived, without any of it passing through in the clear. [[#encryption #server-holds]]
**Working through a form in pages.** A form split into pages checks the current page before moving on and lists what is outstanding with the question each problem belongs to, and the visitor can move on anyway, which keeps a question someone cannot answer from being a dead end. On the last page the check runs across every page, the outstanding items are listed with the page each one sits on, and sending stays blocked until they are resolved. Pages whose questions depend on an earlier answer are skipped when that answer does not call for them, and the progress count counts only the pages that apply. [[#failure-states #client-data]]
**How often a form can be submitted.** Three submissions per address per hour is the default, and the limit is configured per deployment. An organization that expects abuse can additionally require the browser to solve a puzzle before each submission, which is off unless a difficulty is configured and is priced to cost a visitor a moment and an automated flood considerably more. [[#failure-states #portal]]
**Where a submission goes.** The queue is chosen by the routing answer when the form has one and the resolved queue is on that form's allow-list, by the form's own destination queue when it does not, and by the organization's intake queue when neither applies. A submission with no queue anywhere in that chain is refused rather than parked, so a form with no destination configured fails at the first submission rather than collecting cases nobody is told about. [Queues](#admin-people/queues) covers how membership decides who is told. [[#permissions #metadata]]
**What comes back.** A successful submission returns a reference code, which is the alias generated for the new client record, and the organization's own confirmation message when it wrote one. The code is what the visitor quotes to be found again, since the organization holds no name it can search on. [[#client-data #privacy]]
**The submit path and its limits.** The browser assembles and encrypts in \`handleSubmit\` in \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\` through \`encryptIntake\` and \`resolveSubmitMetadata\` in \`intake-crypto.ts\`. The route is \`submitIntake\` in \`packages/server/src/routes/client-portal.ts\`, which applies the rate limiter and the puzzle gate before decoding anything, and the writes are one transaction in \`createIntakeTicket\` in \`packages/server/src/portal/intake-service.ts\`, with the notification intent enqueued inside it so a rolled-back case cannot notify anyone. [[#server-holds #failure-states]]`)
};

const es_demo_narrative_client_intake_submit_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Submit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Enviar cifra cada respuesta en el navegador, compone allí mismo el título y el cuerpo del caso a partir de ellas y manda texto cifrado para el que el servidor no tiene ninguna clave. El servidor crea el caso, lo encamina y avisa a los miembros de la cola de destino de que ha llegado algo, sin que nada de ello pase por él en claro. [[#encryption #server-holds]]
**Recorrer un formulario por páginas.** Un formulario repartido en páginas comprueba la página actual antes de seguir y enumera lo que queda pendiente junto con la pregunta a la que corresponde cada problema, y el visitante puede seguir de todos modos, lo que evita que una pregunta que alguien no puede responder sea un callejón sin salida. En la última página la comprobación abarca todas las páginas, los puntos pendientes se enumeran con la página en la que está cada uno, y el envío sigue bloqueado hasta resolverlos. Las páginas cuyas preguntas dependen de una respuesta anterior se omiten cuando esa respuesta no las requiere, y el recuento de avance cuenta solo las páginas que corresponden. [[#failure-states #client-data]]
**Con qué frecuencia se puede enviar un formulario.** Tres envíos por dirección y por hora es el valor predeterminado, y el límite se configura en cada despliegue. Una organización que espere abusos puede además exigir que el navegador resuelva un rompecabezas antes de cada envío, algo que está desactivado salvo que se configure una dificultad y que está calibrado para costarle un instante a un visitante y bastante más a una avalancha automatizada. [[#failure-states #portal]]
**Adónde va un envío.** La cola la elige la respuesta de enrutamiento cuando el formulario tiene una y la cola resuelta figura en la lista de permitidos de ese formulario; si no, la cola de destino del propio formulario; y si tampoco, la cola de admisión de la organización. Un envío que no encuentra cola en ninguno de esos pasos se rechaza en lugar de quedar aparcado, así que un formulario sin destino configurado falla en el primer envío y no acumula casos de los que nadie se entera. [Colas](#admin-people/queues) trata cómo la pertenencia decide a quién se avisa. [[#permissions #metadata]]
**Lo que se recibe de vuelta.** Un envío correcto devuelve un código de referencia, que es el alias generado para el nuevo registro de cliente, y el mensaje de confirmación de la organización cuando ha redactado uno. El código es lo que el visitante cita para que vuelvan a localizarlo, ya que la organización no guarda ningún nombre por el que pueda buscar. [[#client-data #privacy]]
**La ruta de envío y sus límites.** El navegador ensambla y cifra en \`handleSubmit\`, en \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\`, mediante \`encryptIntake\` y \`resolveSubmitMetadata\`, en \`intake-crypto.ts\`. La ruta es \`submitIntake\`, en \`packages/server/src/routes/client-portal.ts\`, que aplica el limitador de frecuencia y la barrera del rompecabezas antes de decodificar nada, y las escrituras son una sola transacción en \`createIntakeTicket\`, en \`packages/server/src/portal/intake-service.ts\`, con la intención de notificación encolada dentro de ella para que un caso revertido no pueda avisar a nadie. [[#server-holds #failure-states]]`)
};

const en_xa2_demo_narrative_client_intake_submit_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Submit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè sèrvèr cànnòt rèàd àny òf thè sùbmìttèd ànswèrs, bècàùsè thè ìntàkè fòrm èncrypts àll fìèld vàlùès ìn thè bròwsèr ànd còmpòsès à tìckèt tìtlè ànd dèscrìptìòn fròm thèm bèfòrè ànythìng lèàvès thè dèvìcè, àftèr whìch thè sèrvèr crèàtès thè tìckèt ànd nòtìfìès thè dèstìnàtìòn qùèùè's mèmbèrs.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àbùsè còntròls. •••••** Òn à rùnnìng CÀRÈ-Y sèrvèr, ìntàkè sùbmìssìòns àrè càppèd àt à dèfàùlt òf thrèè pèr àddrèss pèr hòùr, ànd thè sèrvèr càn rèqùìrè à pròòf-òf-wòrk pùzzlè thè bròwsèr sòlvès bèfòrè thè sùbmìssìòn ìs àccèptèd. Thìs hàndbòòk rùns wìth pròòf òf wòrk dìsàblèd ànd thè ràtè lìmìtèr àccèptìng èvèrythìng, sò nòthìng ìn ìt ìs èvèr thròttlèd.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè sèrvèr hòlds. •••••••** Thè ìntàkè sùbmìssìòn lànds òn thè sèrvèr às à sèàlèd còntènt kèy ànd èncryptèd fìèld vàlùès thè sèrvèr cànnòt rèàd. Whèn à fìèld càrrìès à ròùtìng ròlè thè rèsòlvèd qùèùè, prìòrìty, òr èscàlàtìòn vàlùè àrrìvès ìn thè clèàr àlòngsìdè thè cìphèrtèxt, ànd thè sèrvèr ùsès ìt fòr ròùtìng wìthòùt èvèr sèèìng thè ànswèr thàt pròdùcèd ìt. •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Submitting encrypts every answer in the browser, composes the case title and body from them there as well, and sends ciphertext the server has no key for. Th..." |
*
* @param {Demo_Narrative_Client_Intake_Submit_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_submit_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Submit_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Submit_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_submit_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_submit_body(inputs)
	return en_demo_narrative_client_intake_submit_body(inputs)
});