/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Dashboard_Merge_Candidates_BodyInputs */

const en_demo_narrative_dashboard_merge_candidates_body = /** @type {(inputs: Demo_Narrative_Dashboard_Merge_Candidates_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`This section pairs client records that share a phone number or email address and lists each pair for review or dismissal. It appears only for users with the View clients permission and only when at least one undismissed pair exists. [[#client-data #permissions]]
**Candidate coverage.** The scan compares intake-derived contacts only for tickets the four lanes have loaded, so lane filters and caps change which tickets are scanned. It waits for every lane to finish loading before it runs. Hash-based matches draw from the non-merged clients the user can decrypt. A client record that has already been merged into another is excluded from both. Two users with different queue membership see different pairs of both kinds. A notice below the heading states that coverage. [[#permissions #privacy]]
**How does the comparison run?** The server returns encrypted intake responses for tickets the account holds key wraps for, field-to-role mappings, and the blind index hashes stored against those clients' phone numbers and email addresses. The crypto worker decrypts the intake responses, extracts contacts, hashes them, and compares all clients pairwise. Neither a contact value nor a search term ever reaches the server. [[#encryption #server-holds]]
**What does the server store?** Blind index hashes beside ciphertext. The server can test whether two hashes are equal. It cannot read the phone numbers, email addresses, or aliases the hashes were computed from, because those decrypt only in the browser. [The trust boundary](#deep-dive/the-trust-boundary) covers the plaintext columns across the schema. [[#server-holds #trust-boundary]]
**Match type.** Each pair carries a chip reading "Same phone number" or "Same email address," reflecting whether the match came from a phone hash or an email hash. [[#client-data]]
**Filtering.** The section filters by match type. Choosing "Same phone number" or "Same email address" narrows the list to that kind. When the filter matches nothing the section reads "No results found." The heading count reflects the filter. [[#client-data]]
**Shared lines.** A phone match offers a "Shared line" action. Marking a number as a shared line sets the flag on every phone row carrying that hash, not only the pair it was raised from. The server then excludes those hashes from the scan data, and the worker suppresses them as well. A shelter or clinic switchboard is the intended use. [[#client-data]]
**Dismissals.** One org-key-sealed blob for the whole organization, read, extended, and written back. A pair dismissed by one user stays hidden for everyone. Two dismissals written at the same time can lose one of them until the next write, because the blob follows a last-write-wins pattern. The server stores and returns that blob without being able to read it. [[#encryption #server-holds]]
**Display and worker limits.** The worker stops comparing after two hundred pairs and reports that it stopped, which is what the truncation notice reflects. The section shows the first five candidate pairs, with no paging. The heading counts all candidates matching the filter. [[#failure-states]]
**Scan trigger and source paths.** \`createMergeScan\` in \`packages/client/src/lib/composables/create-merge-scan.svelte.ts\` waits for idle time after every dashboard lane has settled, caches the result for the session, and re-runs on a dismissal or a merge. The server side is \`packages/server/src/clients/merge-scan-service.ts\` for the scan inputs and \`packages/server/src/clients/dismissal-service.ts\` for the blob. The pairwise comparison runs in \`packages/client/src/lib/workers/crypto-core.ts\`. [Merging clients](#admin-people/client-merge) covers what a merge does to the two records. [[#client-data]]`)
};

const es_demo_narrative_dashboard_merge_candidates_body = /** @type {(inputs: Demo_Narrative_Dashboard_Merge_Candidates_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Esta sección empareja los registros de clientes que comparten un número de teléfono o una dirección de correo y muestra cada par para revisarlo o descartarlo. Solo aparece para personas usuarias con el permiso Ver clientes y solo cuando existe al menos un par no descartado. [[#client-data #permissions]]
**Cobertura de candidatos.** El análisis compara los contactos derivados de la admisión solo para los tickets que los cuatro carriles tienen cargados, de modo que los filtros y los topes de cada carril cambian qué tickets se analizan. Espera a que todos los carriles terminen de cargar antes de ejecutarse. Las coincidencias basadas en hash abarcan los clientes no fusionados que la persona usuaria puede descifrar. Un registro de cliente que ya se fusionó con otro queda excluido de ambas fuentes. Dos personas usuarias con distinta pertenencia a colas ven pares distintos en ambos tipos. Un aviso debajo del encabezado indica esa cobertura. [[#permissions #privacy]]
**¿Cómo se ejecuta la comparación?** El servidor devuelve respuestas de admisión cifradas de los tickets para los que la cuenta tiene envoltorios de clave, los mapas de campo a rol y los hashes de índice ciego almacenados para los números de teléfono y direcciones de correo de esos clientes. El worker criptográfico descifra las respuestas de admisión, extrae los contactos, los convierte en hashes y los compara por pares. Ni un valor de contacto ni un término de búsqueda llegan nunca al servidor. [[#encryption #server-holds]]
**¿Qué almacena el servidor?** Hashes de índice ciego junto al texto cifrado. El servidor puede comprobar si dos hashes son iguales. No puede leer los números de teléfono, las direcciones de correo ni los alias a partir de los cuales se calcularon esos hashes, porque solo se descifran en el navegador. [La frontera de confianza](#deep-dive/the-trust-boundary) detalla las columnas en texto plano del esquema. [[#server-holds #trust-boundary]]
**Tipo de coincidencia.** Cada par lleva una etiqueta que dice "Mismo número de teléfono" o "Misma dirección de correo," según si la coincidencia provino de un hash de teléfono o de correo. [[#client-data]]
**Filtrado.** La sección filtra por tipo de coincidencia. Elegir "Mismo número de teléfono" o "Misma dirección de correo" reduce la lista a ese tipo. Cuando el filtro no coincide con nada, la sección muestra "No se encontraron resultados." El recuento del encabezado refleja el filtro. [[#client-data]]
**Líneas compartidas.** Una coincidencia de teléfono ofrece la acción "Línea compartida". Marcar un número como línea compartida activa la marca en cada fila de teléfono que lleve ese hash, no solo en el par desde el que se marcó. El servidor excluye después esos hashes de los datos del análisis, y el worker los suprime también. La centralita de un refugio o una clínica es el uso previsto. [[#client-data]]
**Descartes.** Un único blob sellado con la clave de la organización para toda la organización, que se lee, se amplía y se vuelve a escribir. Un par descartado por una persona usuaria queda oculto para todas. Dos descartes escritos al mismo tiempo pueden perder uno de ellos hasta la siguiente escritura, porque el blob sigue un patrón de última escritura gana. El servidor guarda y devuelve ese blob sin poder leerlo. [[#encryption #server-holds]]
**Límites de visualización y del worker.** El worker deja de comparar tras doscientos pares e informa de que se detuvo, que es lo que refleja el aviso de truncamiento. La sección muestra los primeros cinco pares candidatos, sin paginación. El recuento del encabezado cuenta todos los candidatos que coinciden con el filtro. [[#failure-states]]
**Inicio del análisis y rutas de código.** \`createMergeScan\`, en \`packages/client/src/lib/composables/create-merge-scan.svelte.ts\`, espera a un momento de inactividad tras asentarse todos los carriles, guarda el resultado durante la sesión y vuelve a ejecutarse ante un descarte o una fusión. El lado del servidor es \`packages/server/src/clients/merge-scan-service.ts\` para las entradas del análisis y \`packages/server/src/clients/dismissal-service.ts\` para el blob. La comparación por pares se ejecuta en \`packages/client/src/lib/workers/crypto-core.ts\`. [Fusionar clientes](#admin-people/client-merge) trata lo que una fusión hace con los dos registros. [[#client-data]]`)
};

const en_xa2_demo_narrative_dashboard_merge_candidates_body = /** @type {(inputs: Demo_Narrative_Dashboard_Merge_Candidates_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thìs sèctìòn pàìrs clìènt rècòrds thàt shàrè à phònè nùmbèr òr èmàìl àddrèss ànd lìsts èàch pàìr fòr rèvìèw òr dìsmìssàl. Ìt àppèàrs ònly fòr ùsèrs wìth thè Vìèw clìènts pèrmìssìòn ànd ònly whèn àt lèàst ònè ùndìsmìssèd pàìr èxìsts. [[#clìènt-dàtà #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Càndìdàtè còvèràgè. ••••••** Thè scàn còmpàrès ìntàkè-dèrìvèd còntàcts ònly fòr tìckèts thè fòùr lànès hàvè lòàdèd, sò lànè fìltèrs ànd càps chàngè whìch tìckèts àrè scànnèd. Ìt wàìts fòr èvèry lànè tò fìnìsh lòàdìng bèfòrè ìt rùns. Hàsh-bàsèd màtchès dràw fròm thè nòn-mèrgèd clìènts thè ùsèr càn dècrypt. À clìènt rècòrd thàt hàs àlrèàdy bèèn mèrgèd ìntò ànòthèr ìs èxclùdèd fròm bòth. Twò ùsèrs wìth dìffèrènt qùèùè mèmbèrshìp sèè dìffèrènt pàìrs òf bòth kìnds. À nòtìcè bèlòw thè hèàdìng stàtès thàt còvèràgè. [[#pèrmìssìòns #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè còmpàrìsòn rùn? •••••••••** Thè sèrvèr rètùrns èncryptèd ìntàkè rèspònsès fòr tìckèts thè àccòùnt hòlds kèy wràps fòr, fìèld-tò-ròlè màppìngs, ànd thè blìnd ìndèx hàshès stòrèd àgàìnst thòsè clìènts' phònè nùmbèrs ànd èmàìl àddrèssès. Thè cryptò wòrkèr dècrypts thè ìntàkè rèspònsès, èxtràcts còntàcts, hàshès thèm, ànd còmpàrès àll clìènts pàìrwìsè. Nèìthèr à còntàct vàlùè nòr à sèàrch tèrm èvèr rèàchès thè sèrvèr. [[#èncryptìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè? •••••••••** Blìnd ìndèx hàshès bèsìdè cìphèrtèxt. Thè sèrvèr càn tèst whèthèr twò hàshès àrè èqùàl. Ìt cànnòt rèàd thè phònè nùmbèrs, èmàìl àddrèssès, òr àlìàsès thè hàshès wèrè còmpùtèd fròm, bècàùsè thòsè dècrypt ònly ìn thè bròwsèr. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè plàìntèxt còlùmns àcròss thè schèmà. [[#sèrvèr-hòlds #trùst-bòùndàry]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Màtch typè. ••••** Èàch pàìr càrrìès à chìp rèàdìng "Sàmè phònè nùmbèr" òr "Sàmè èmàìl àddrèss," rèflèctìng whèthèr thè màtch càmè fròm à phònè hàsh òr àn èmàìl hàsh. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••**Fìltèrìng. •••** Thè sèctìòn fìltèrs by màtch typè. Chòòsìng "Sàmè phònè nùmbèr" òr "Sàmè èmàìl àddrèss" nàrròws thè lìst tò thàt kìnd. Whèn thè fìltèr màtchès nòthìng thè sèctìòn rèàds "Nò rèsùlts fòùnd." Thè hèàdìng còùnt rèflècts thè fìltèr. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Shàrèd lìnès. ••••** À phònè màtch òffèrs à "Shàrèd lìnè" àctìòn. Màrkìng à nùmbèr às à shàrèd lìnè sèts thè flàg òn èvèry phònè ròw càrryìng thàt hàsh, nòt ònly thè pàìr ìt wàs ràìsèd fròm. Thè sèrvèr thèn èxclùdès thòsè hàshès fròm thè scàn dàtà, ànd thè wòrkèr sùpprèssès thèm às wèll. À shèltèr òr clìnìc swìtchbòàrd ìs thè ìntèndèd ùsè. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dìsmìssàls. ••••** Ònè òrg-kèy-sèàlèd blòb fòr thè whòlè òrgànìzàtìòn, rèàd, èxtèndèd, ànd wrìttèn bàck. À pàìr dìsmìssèd by ònè ùsèr stàys hìddèn fòr èvèryònè. Twò dìsmìssàls wrìttèn àt thè sàmè tìmè càn lòsè ònè òf thèm ùntìl thè nèxt wrìtè, bècàùsè thè blòb fòllòws à làst-wrìtè-wìns pàttèrn. Thè sèrvèr stòrès ànd rètùrns thàt blòb wìthòùt bèìng àblè tò rèàd ìt. [[#èncryptìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dìsplày ànd wòrkèr lìmìts. ••••••••** Thè wòrkèr stòps còmpàrìng àftèr twò hùndrèd pàìrs ànd rèpòrts thàt ìt stòppèd, whìch ìs whàt thè trùncàtìòn nòtìcè rèflècts. Thè sèctìòn shòws thè fìrst fìvè càndìdàtè pàìrs, wìth nò pàgìng. Thè hèàdìng còùnts àll càndìdàtès màtchìng thè fìltèr. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Scàn trìggèr ànd sòùrcè pàths. •••••••••** \`crèàtèMèrgèScàn\` ìn \`pàckàgès/clìènt/src/lìb/còmpòsàblès/crèàtè-mèrgè-scàn.svèltè.ts\` wàìts fòr ìdlè tìmè àftèr èvèry dàshbòàrd lànè hàs sèttlèd, càchès thè rèsùlt fòr thè sèssìòn, ànd rè-rùns òn à dìsmìssàl òr à mèrgè. Thè sèrvèr sìdè ìs \`pàckàgès/sèrvèr/src/clìènts/mèrgè-scàn-sèrvìcè.ts\` fòr thè scàn ìnpùts ànd \`pàckàgès/sèrvèr/src/clìènts/dìsmìssàl-sèrvìcè.ts\` fòr thè blòb. Thè pàìrwìsè còmpàrìsòn rùns ìn \`pàckàgès/clìènt/src/lìb/wòrkèrs/cryptò-còrè.ts\`. [Mèrgìng clìènts](#àdmìn-pèòplè/clìènt-mèrgè) còvèrs whàt à mèrgè dòès tò thè twò rècòrds. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "This section pairs client records that share a phone number or email address and lists each pair for review or dismissal. It appears only for users with the ..." |
*
* @param {Demo_Narrative_Dashboard_Merge_Candidates_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_dashboard_merge_candidates_body = /** @type {((inputs?: Demo_Narrative_Dashboard_Merge_Candidates_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Dashboard_Merge_Candidates_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_dashboard_merge_candidates_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_dashboard_merge_candidates_body(inputs)
	return en_demo_narrative_dashboard_merge_candidates_body(inputs)
});