/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_People_BodyInputs */

const en_demo_narrative_admin_people_body = /** @type {(inputs: Demo_Narrative_Admin_People_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The roster shows every account belonging to the organization, whether active or deactivated. Each account shows its role, key status and queue memberships. [[#permissions #privacy]]
**Who can do what on the roster?** Viewing the roster, deactivating an account and managing invitations all require the Manage users permission. Role assignment requires the Manage roles permission. An account cannot change its own role, and the server refuses to demote the last active administrator. Direct account creation requires the Manage users permission; picking a non-default role during that creation requires the Manage roles permission as well. Sending an invitation at any role requires only the Manage users permission, with no additional role check. [The permission system](#deep-dive/the-permission-system) covers where those grants come from. [[#permissions]]
**Invitation path.** The invite link contains a random token that expires after seventy-two hours. The link names the role the future account will hold, and the invited person picks their own password. Keys are derived on that person's device; the administrator never touches key material for the new account. [How keys are derived](#deep-dive/how-keys-are-derived) covers what a password produces. [[#keys #privacy]]
**Direct creation path.** The administrator provides an identifier and a temporary password at least sixteen characters long. The administrator's browser derives keys for that account and wraps the organization key on its behalf. Both people know the temporary password until the new account replaces it; no forced change happens at first sign-in. [[#keys #privacy]]
**What does the server store for an invitation?** The token is kept as a SHA-256 hash paired with a sealed copy encrypted to the organization key. Any account that holds the organization key and can query the row can recover a pending link from the sealed copy. Role, inviting account, creation timestamp and expiry sit in plaintext columns. Revoking stamps the row with a revocation time instead of removing it, and accepting stamps it as consumed while keeping the row intact. [[#server-holds #metadata]]
**What does deactivation destroy?** The operation removes the account's ticket key wraps, its wrapped organization key and its stored key record in a single transaction. From that moment the account cannot decrypt anything. The server blocks the request when the account is the sole key holder for one or more cases and reports how many are affected. Overriding the guard makes those cases permanently unreadable. Reactivation brings the account back without restoring any deleted key material. \`revokeVolunteerKeys\` in \`packages/server/src/crypto/offboarding.ts\` handles the deletion. [[#keys #failure-states]]`)
};

const es_demo_narrative_admin_people_body = /** @type {(inputs: Demo_Narrative_Admin_People_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El directorio muestra todas las cuentas de la organización, estén activas o desactivadas. Cada cuenta muestra su rol, el estado de sus claves y las colas a las que pertenece. [[#permissions #privacy]]
**¿Quién puede hacer qué en el directorio?** Ver el directorio, desactivar una cuenta y gestionar invitaciones requieren el permiso Gestionar usuarios. La asignación de roles requiere el permiso Gestionar roles. Una cuenta no puede cambiar su propio rol, y el servidor rechaza degradar a la última persona administradora activa. Crear una cuenta directamente requiere el permiso Gestionar usuarios; elegir un rol distinto al predeterminado durante esa creación requiere además el permiso Gestionar roles. Enviar una invitación con cualquier rol requiere solo el permiso Gestionar usuarios, sin verificación adicional de rol. [El sistema de permisos](#deep-dive/the-permission-system) trata de dónde salen esas concesiones. [[#permissions]]
**Ruta de invitación.** El enlace de invitación contiene un token aleatorio que vence tras setenta y dos horas. El enlace fija el rol que tendrá la futura cuenta, y la persona invitada elige su propia contraseña. Las claves se derivan en el dispositivo de esa persona; la persona administradora nunca maneja material de claves de la cuenta nueva. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) explica qué produce una contraseña. [[#keys #privacy]]
**Ruta de creación directa.** La persona administradora proporciona un identificador y una contraseña temporal de al menos dieciséis caracteres. El navegador de la persona administradora deriva las claves de esa cuenta y envuelve en su nombre la clave de la organización. Ambas personas conocen la contraseña temporal hasta que la cuenta nueva la reemplace; no se fuerza un cambio en el primer inicio de sesión. [[#keys #privacy]]
**¿Qué guarda el servidor de una invitación?** El token se conserva como un hash SHA-256 emparejado con una copia sellada cifrada con la clave de la organización. Cualquier cuenta que tenga la clave de la organización y pueda consultar la fila puede recuperar un enlace pendiente a partir de la copia sellada. El rol, la cuenta que invitó, la marca de tiempo de creación y la de vencimiento están en columnas en texto plano. Revocar marca la fila con una fecha de revocación en lugar de borrarla, y aceptar la marca como consumida conservando la fila intacta. [[#server-holds #metadata]]
**¿Qué destruye la desactivación?** La operación elimina los envoltorios de clave de ticket de la cuenta, su clave de organización envuelta y su registro de claves almacenado en una sola transacción. A partir de ese momento la cuenta no puede descifrar nada. El servidor bloquea la solicitud cuando la cuenta es la única titular de claves de uno o más casos e indica cuántos están afectados. Forzar la operación deja esos casos permanentemente ilegibles. La reactivación restaura la cuenta sin restaurar el material de claves eliminado. \`revokeVolunteerKeys\`, en \`packages/server/src/crypto/offboarding.ts\`, se encarga de la eliminación. [[#keys #failure-states]]`)
};

const en_xa2_demo_narrative_admin_people_body = /** @type {(inputs: Demo_Narrative_Admin_People_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ròstèr shòws èvèry àccòùnt bèlòngìng tò thè òrgànìzàtìòn, whèthèr àctìvè òr dèàctìvàtèd. Èàch àccòùnt shòws ìts ròlè, kèy stàtùs ànd qùèùè mèmbèrshìps. [[#pèrmìssìòns #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn dò whàt òn thè ròstèr? •••••••••** Vìèwìng thè ròstèr, dèàctìvàtìng àn àccòùnt ànd mànàgìng ìnvìtàtìòns àll rèqùìrè thè Mànàgè ùsèrs pèrmìssìòn. Ròlè àssìgnmènt rèqùìrès thè Mànàgè ròlès pèrmìssìòn. Àn àccòùnt cànnòt chàngè ìts òwn ròlè, ànd thè sèrvèr rèfùsès tò dèmòtè thè làst àctìvè àdmìnìstràtòr. Dìrèct àccòùnt crèàtìòn rèqùìrès thè Mànàgè ùsèrs pèrmìssìòn; pìckìng à nòn-dèfàùlt ròlè dùrìng thàt crèàtìòn rèqùìrès thè Mànàgè ròlès pèrmìssìòn às wèll. Sèndìng àn ìnvìtàtìòn àt àny ròlè rèqùìrès ònly thè Mànàgè ùsèrs pèrmìssìòn, wìth nò àddìtìònàl ròlè chèck. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs whèrè thòsè grànts còmè fròm. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ìnvìtàtìòn pàth. •••••** Thè ìnvìtè lìnk còntàìns à ràndòm tòkèn thàt èxpìrès àftèr sèvènty-twò hòùrs. Thè lìnk nàmès thè ròlè thè fùtùrè àccòùnt wìll hòld, ànd thè ìnvìtèd pèrsòn pìcks thèìr òwn pàsswòrd. Kèys àrè dèrìvèd òn thàt pèrsòn's dèvìcè; thè àdmìnìstràtòr nèvèr tòùchès kèy màtèrìàl fòr thè nèw àccòùnt. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs whàt à pàsswòrd pròdùcès. [[#kèys #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dìrèct crèàtìòn pàth. •••••••** Thè àdmìnìstràtòr pròvìdès àn ìdèntìfìèr ànd à tèmpòràry pàsswòrd àt lèàst sìxtèèn chàràctèrs lòng. Thè àdmìnìstràtòr's bròwsèr dèrìvès kèys fòr thàt àccòùnt ànd wràps thè òrgànìzàtìòn kèy òn ìts bèhàlf. Bòth pèòplè knòw thè tèmpòràry pàsswòrd ùntìl thè nèw àccòùnt rèplàcès ìt; nò fòrcèd chàngè hàppèns àt fìrst sìgn-ìn. [[#kèys #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè fòr àn ìnvìtàtìòn? ••••••••••••••** Thè tòkèn ìs kèpt às à SHÀ-256 hàsh pàìrèd wìth à sèàlèd còpy èncryptèd tò thè òrgànìzàtìòn kèy. Àny àccòùnt thàt hòlds thè òrgànìzàtìòn kèy ànd càn qùèry thè ròw càn rècòvèr à pèndìng lìnk fròm thè sèàlèd còpy. Ròlè, ìnvìtìng àccòùnt, crèàtìòn tìmèstàmp ànd èxpìry sìt ìn plàìntèxt còlùmns. Rèvòkìng stàmps thè ròw wìth à rèvòcàtìòn tìmè ìnstèàd òf rèmòvìng ìt, ànd àccèptìng stàmps ìt às cònsùmèd whìlè kèèpìng thè ròw ìntàct. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès dèàctìvàtìòn dèstròy? ••••••••••** Thè òpèràtìòn rèmòvès thè àccòùnt's tìckèt kèy wràps, ìts wràppèd òrgànìzàtìòn kèy ànd ìts stòrèd kèy rècòrd ìn à sìnglè trànsàctìòn. Fròm thàt mòmènt thè àccòùnt cànnòt dècrypt ànythìng. Thè sèrvèr blòcks thè rèqùèst whèn thè àccòùnt ìs thè sòlè kèy hòldèr fòr ònè òr mòrè càsès ànd rèpòrts hòw màny àrè àffèctèd. Òvèrrìdìng thè gùàrd màkès thòsè càsès pèrmànèntly ùnrèàdàblè. Rèàctìvàtìòn brìngs thè àccòùnt bàck wìthòùt rèstòrìng àny dèlètèd kèy màtèrìàl. \`rèvòkèVòlùntèèrKèys\` ìn \`pàckàgès/sèrvèr/src/cryptò/òffbòàrdìng.ts\` hàndlès thè dèlètìòn. [[#kèys #fàìlùrè-stàtès]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The roster shows every account belonging to the organization, whether active or deactivated. Each account shows its role, key status and queue memberships. [..." |
*
* @param {Demo_Narrative_Admin_People_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_people_body = /** @type {((inputs?: Demo_Narrative_Admin_People_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_People_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_people_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_people_body(inputs)
	return en_demo_narrative_admin_people_body(inputs)
});