/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Disbursement_BodyInputs */

const en_demo_narrative_topic_disbursement_body = /** @type {(inputs: Demo_Narrative_Topic_Disbursement_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Recording a disbursement is a compose action alongside the internal note, offered when the case's queue carries a fund and the user holds the Record disbursements permission. The action opens a sheet where the user enters an amount and an optional note, confirms the fund, and saves. The result appears in the case thread as an internal note that shows the amount, the fund name, and the note text. [[#client-data #permissions]]
**What does one save write?** One server transaction writes the fund's ledger entry, the fund's next sealed balance, and an internal note on the case. The ledger entry names no case. The note's encrypted content carries a structured envelope that links the entry to the fund and amount, encrypted under the ticket key the same way an ordinary internal note is encrypted. If any part fails, the transaction rolls back and nothing is written. [[#encryption #server-holds]]
**Editing a recorded disbursement.** The timeline entry's context menu offers an edit action in place of the plain note edit. Editing opens the same sheet with the amount and note prefilled. Saving writes a reversal of the original ledger entry, a replacement entry with the new amount, the rewritten note, and the new sealed balance in one transaction. The reversal and replacement pair is the audit record of the correction. [Fund ledger](#admin-funds/ledger) covers what the auditor sees. [[#failure-states #metadata]]
**Who can edit?** The user who recorded the disbursement can edit it. A user with the Manage funds permission can edit anyone's disbursement. The server enforces both rules. [[#permissions]]
**The envelope inside the note.** A disbursement note's content starts with a control character that a textarea cannot produce, followed by a JSON envelope carrying the ledger entry id, fund id, amount, currency, and the volunteer's note text. The renderer checks the first character after decryption and shows the readable form when the marker is present. Surfaces without fund access show the raw note text, which is the envelope JSON. [[#encryption #client-data]]
**The sheet, the mutation, and the retry.** \`DisbursementSheet.svelte\` in \`packages/client/src/lib/components/tickets/\` owns the encryption, the mutation, and the dismiss lifecycle. It seals the ledger payload with the organization key and the note content with the ticket key. When the server returns a stale balance error, the sheet refetches the fund list, recomputes the next balance from the fresh one, and retries once before surfacing the error. [[#failure-states #client-data]]`)
};

const es_demo_narrative_topic_disbursement_body = /** @type {(inputs: Demo_Narrative_Topic_Disbursement_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Registrar un desembolso es una acción de composición junto a la nota interna, ofrecida cuando la cola del caso lleva un fondo y la persona usuaria tiene el permiso Registrar desembolsos. La acción abre una hoja donde se ingresa un monto y una nota opcional, se confirma el fondo y se guarda. El resultado aparece en el hilo del caso como una nota interna que muestra el monto, el nombre del fondo y el texto de la nota. [[#client-data #permissions]]
**¿Qué escribe un guardado?** Una única transacción del servidor escribe la entrada del libro mayor del fondo, el siguiente saldo sellado del fondo y una nota interna en el caso. La entrada del libro mayor no nombra caso alguno. El contenido cifrado de la nota lleva un sobre estructurado que vincula la entrada con el fondo y el monto, cifrado bajo la clave del ticket de la misma forma en que se cifra una nota interna ordinaria. Si alguna parte falla, la transacción se revierte y no se escribe nada. [[#encryption #server-holds]]
**Edición de un desembolso registrado.** El menú contextual de la entrada en la línea de tiempo ofrece una acción de edición en lugar de la edición de nota ordinaria. Editar abre la misma hoja con el monto y la nota precargados. Guardar escribe una reversión de la entrada original del libro mayor, una entrada de reemplazo con el nuevo monto, la nota reescrita y el nuevo saldo sellado en una sola transacción. El par de reversión y reemplazo es el registro de auditoría de la corrección. [Libro mayor de fondos](#admin-funds/ledger) trata lo que ve la persona auditora. [[#failure-states #metadata]]
**¿Quién puede editar?** La persona que registró el desembolso puede editarlo. Una persona con el permiso Gestionar fondos puede editar el desembolso de cualquier otra persona. El servidor aplica ambas reglas. [[#permissions]]
**El sobre dentro de la nota.** El contenido de una nota de desembolso comienza con un carácter de control que un área de texto no puede producir, seguido de un sobre JSON que lleva el id de la entrada del libro mayor, el id del fondo, el monto, la moneda y el texto de la nota de la persona voluntaria. El renderizador comprueba el primer carácter tras el descifrado y muestra la forma legible cuando el marcador está presente. Las superficies sin acceso al fondo muestran el texto bruto de la nota, que es el JSON del sobre. [[#encryption #client-data]]
**La hoja, la mutación y el reintento.** \`DisbursementSheet.svelte\` en \`packages/client/src/lib/components/tickets/\` es responsable del cifrado, la mutación y el ciclo de cierre. Sella la carga del libro mayor con la clave de la organización y el contenido de la nota con la clave del ticket. Cuando el servidor devuelve un error de saldo obsoleto, la hoja vuelve a obtener la lista de fondos, recalcula el siguiente saldo a partir del saldo actual y reintenta una vez antes de mostrar el error. [[#failure-states #client-data]]`)
};

const en_xa2_demo_narrative_topic_disbursement_body = /** @type {(inputs: Demo_Narrative_Topic_Disbursement_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Rècòrdìng à dìsbùrsèmènt ìs à còmpòsè àctìòn àlòngsìdè thè ìntèrnàl nòtè, òffèrèd whèn thè càsè's qùèùè càrrìès à fùnd ànd thè ùsèr hòlds thè Rècòrd dìsbùrsèmènts pèrmìssìòn. Thè àctìòn òpèns à shèèt whèrè thè ùsèr èntèrs àn àmòùnt ànd àn òptìònàl nòtè, cònfìrms thè fùnd, ànd sàvès. Thè rèsùlt àppèàrs ìn thè càsè thrèàd às àn ìntèrnàl nòtè thàt shòws thè àmòùnt, thè fùnd nàmè, ànd thè nòtè tèxt. [[#clìènt-dàtà #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès ònè sàvè wrìtè? ••••••••** Ònè sèrvèr trànsàctìòn wrìtès thè fùnd's lèdgèr èntry, thè fùnd's nèxt sèàlèd bàlàncè, ànd àn ìntèrnàl nòtè òn thè càsè. Thè lèdgèr èntry nàmès nò càsè. Thè nòtè's èncryptèd còntènt càrrìès à strùctùrèd ènvèlòpè thàt lìnks thè èntry tò thè fùnd ànd àmòùnt, èncryptèd ùndèr thè tìckèt kèy thè sàmè wày àn òrdìnàry ìntèrnàl nòtè ìs èncryptèd. Ìf àny pàrt fàìls, thè trànsàctìòn ròlls bàck ànd nòthìng ìs wrìttèn. [[#èncryptìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èdìtìng à rècòrdèd dìsbùrsèmènt. ••••••••••** Thè tìmèlìnè èntry's còntèxt mènù òffèrs àn èdìt àctìòn ìn plàcè òf thè plàìn nòtè èdìt. Èdìtìng òpèns thè sàmè shèèt wìth thè àmòùnt ànd nòtè prèfìllèd. Sàvìng wrìtès à rèvèrsàl òf thè òrìgìnàl lèdgèr èntry, à rèplàcèmènt èntry wìth thè nèw àmòùnt, thè rèwrìttèn nòtè, ànd thè nèw sèàlèd bàlàncè ìn ònè trànsàctìòn. Thè rèvèrsàl ànd rèplàcèmènt pàìr ìs thè àùdìt rècòrd òf thè còrrèctìòn. [Fùnd lèdgèr](#àdmìn-fùnds/lèdgèr) còvèrs whàt thè àùdìtòr sèès. [[#fàìlùrè-stàtès #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn èdìt? ••••** Thè ùsèr whò rècòrdèd thè dìsbùrsèmènt càn èdìt ìt. À ùsèr wìth thè Mànàgè fùnds pèrmìssìòn càn èdìt ànyònè's dìsbùrsèmènt. Thè sèrvèr ènfòrcès bòth rùlès. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè ènvèlòpè ìnsìdè thè nòtè. •••••••••** À dìsbùrsèmènt nòtè's còntènt stàrts wìth à còntròl chàràctèr thàt à tèxtàrèà cànnòt pròdùcè, fòllòwèd by à JSÒN ènvèlòpè càrryìng thè lèdgèr èntry ìd, fùnd ìd, àmòùnt, cùrrèncy, ànd thè vòlùntèèr's nòtè tèxt. Thè rèndèrèr chècks thè fìrst chàràctèr àftèr dècryptìòn ànd shòws thè rèàdàblè fòrm whèn thè màrkèr ìs prèsènt. Sùrfàcès wìthòùt fùnd àccèss shòw thè ràw nòtè tèxt, whìch ìs thè ènvèlòpè JSÒN. [[#èncryptìòn #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè shèèt, thè mùtàtìòn, ànd thè rètry. ••••••••••••** \`DìsbùrsèmèntShèèt.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/tìckèts/\` òwns thè èncryptìòn, thè mùtàtìòn, ànd thè dìsmìss lìfècyclè. Ìt sèàls thè lèdgèr pàylòàd wìth thè òrgànìzàtìòn kèy ànd thè nòtè còntènt wìth thè tìckèt kèy. Whèn thè sèrvèr rètùrns à stàlè bàlàncè èrròr, thè shèèt rèfètchès thè fùnd lìst, rècòmpùtès thè nèxt bàlàncè fròm thè frèsh ònè, ànd rètrìès òncè bèfòrè sùrfàcìng thè èrròr. [[#fàìlùrè-stàtès #clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Recording a disbursement is a compose action alongside the internal note, offered when the case's queue carries a fund and the user holds the Record disburse..." |
*
* @param {Demo_Narrative_Topic_Disbursement_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_disbursement_body = /** @type {((inputs?: Demo_Narrative_Topic_Disbursement_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Disbursement_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_disbursement_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_disbursement_body(inputs)
	return en_demo_narrative_topic_disbursement_body(inputs)
});