/* eslint-disable */
import * as registry from '../registry.js'
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Search_How_BodyInputs */

const en_demo_narrative_search_how_body = /** @type {(inputs: Demo_Narrative_Search_How_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`No search term ever leaves the device. The browser matches the query against text it has already decrypted, which is why a query about case content can run at all when the server cannot read any of it. [[#privacy #server-holds #search]]
**The initial search.** The query runs against whatever the current session has already loaded and decrypted. Cases match from the existing cache with no server request. Articles and accounts each fetch their full set once, the first time the group is needed, and then search that set in memory on every later query. Each group reports how many records it searched against how many exist, so the account can see when the answer covers only part of the set. [[#client-data #metadata]]
**The deeper search and when it starts.** The deeper search pages in every record of that kind the account has access to, decrypts each one in the browser, and matches there. It also starts on its own when the initial search finds no result at all, as long as at least some records were available to search. The account can start it manually at any time. Changing the query abandons a running deeper search and discards its results. [[#failure-states #client-data]]
**What does the server receive during a deeper search?** Two kinds of request, neither carrying a word of the query. A paging request fetches records by cursor and page size. A content request carries the identifiers of the cases whose titles did not match, a page number, and a page size. The server answers both with ciphertext it cannot read. [[#trust-boundary #server-holds]]
**What can the server infer?** That a deeper search happened, when it happened, and how many records were paged in. The content request names the cases whose titles did not match, so the server can derive which cases did match by subtraction. The server does not receive what was typed, which records ultimately matched, or whether anything matched at all. [The trust boundary](#deep-dive/the-trust-boundary) covers what else the server can infer from traffic. [[#metadata #trust-boundary]]
**What does the server restrict?** Both requests return only records in the queues the account has access to. A deeper search cannot widen what an account can see. When the account has access to no queue, the result is empty rather than an error. [The permission system](#deep-dive/the-permission-system) covers that boundary. [[#permissions #server-holds]]
**Why does client-side search work at this scale?** Paging an organization's full case set into the browser is practical at 200 to 2,000 cases and is the cost of the server not being able to index encrypted text. [[#failure-states #encryption]]
**The full-search functions and the registry.** Each provider's \`fullSearch\` function lives under \`packages/client/src/lib/search/providers/\`. The registry in \`registry.svelte.ts\` coordinates each run with a generation counter and an abort signal so an abandoned run cannot report over a live one. The server side is \`contentSearch\` in \`packages/server/src/tickets/search.ts\`. [[#client-data #server-holds]]`)
};

const es_demo_narrative_search_how_body = /** @type {(inputs: Demo_Narrative_Search_How_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Ningún término de búsqueda sale del dispositivo. El navegador compara la consulta con texto que ya ha descifrado, lo que permite buscar en el contenido de los casos cuando el servidor no puede leer nada de él. [[#privacy #server-holds #search]]
**La búsqueda inicial.** La consulta se ejecuta contra lo que la sesión actual ya ha cargado y descifrado. Los casos coinciden desde la caché existente sin petición al servidor. Los artículos y las cuentas recuperan su conjunto completo una sola vez, la primera vez que se necesita el grupo, y luego buscan en esa copia en memoria en cada consulta posterior. Cada grupo informa cuántos registros se buscaron contra cuántos existen, para que la cuenta vea cuándo la respuesta cubre solo parte del conjunto. [[#client-data #metadata]]
**La búsqueda profunda y cuándo se inicia.** La búsqueda profunda carga todos los registros de ese tipo a los que la cuenta tiene acceso, descifra cada uno en el navegador y compara allí. También se inicia por su cuenta cuando la búsqueda inicial no encuentra ningún resultado, siempre que haya al menos algunos registros disponibles para buscar. La cuenta puede iniciarla manualmente en cualquier momento. Cambiar la consulta abandona una búsqueda profunda en curso y descarta sus resultados. [[#failure-states #client-data]]
**¿Qué recibe el servidor durante una búsqueda profunda?** Dos tipos de petición, ninguna con una palabra de la consulta. Una petición de paginación recupera registros por cursor y tamaño de página. Una petición de contenido lleva los identificadores de los casos cuyos títulos no coincidieron, un número de página y un tamaño de página. El servidor responde a ambas con texto cifrado que no puede leer. [[#trust-boundary #server-holds]]
**¿Qué puede inferir el servidor?** Que ocurrió una búsqueda profunda, cuándo ocurrió y cuántos registros se paginaron. La petición de contenido nombra los casos cuyos títulos no coincidieron, así que el servidor puede derivar cuáles sí coincidieron por sustracción. El servidor no recibe qué se escribió, qué registros coincidieron finalmente ni si algo coincidió. [La frontera de confianza](#deep-dive/the-trust-boundary) trata lo que el servidor puede inferir del tráfico en general. [[#metadata #trust-boundary]]
**¿Qué restringe el servidor?** Ambas peticiones devuelven solo registros en las colas a las que la cuenta tiene acceso. Una búsqueda profunda no puede ampliar lo que una cuenta puede ver. Cuando la cuenta no tiene acceso a ninguna cola, el resultado es vacío en lugar de un error. [El sistema de permisos](#deep-dive/the-permission-system) trata ese límite. [[#permissions #server-holds]]
**¿Por qué funciona la búsqueda del lado del cliente a esta escala?** Cargar el conjunto completo de casos de una organización en el navegador es práctico con 200 a 2.000 casos y es el costo de que el servidor no pueda indexar texto cifrado. [[#failure-states #encryption]]
**Las funciones de búsqueda completa y el registro.** La función \`fullSearch\` de cada proveedor está en \`packages/client/src/lib/search/providers/\`. El registro en \`registry.svelte.ts\` coordina cada ejecución con un contador de generación y una señal de cancelación para que una ejecución abandonada no pueda informar sobre una activa. El lado del servidor es \`contentSearch\` en \`packages/server/src/tickets/search.ts\`. [[#client-data #server-holds]]`)
};

const en_xa2_demo_narrative_search_how_body = /** @type {(inputs: Demo_Narrative_Search_How_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Nò sèàrch tèrm èvèr lèàvès thè dèvìcè. Thè bròwsèr màtchès thè qùèry àgàìnst tèxt ìt hàs àlrèàdy dècryptèd, whìch ìs why à qùèry àbòùt càsè còntènt càn rùn àt àll whèn thè sèrvèr cànnòt rèàd àny òf ìt. [[#prìvàcy #sèrvèr-hòlds #sèàrch]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè ìnìtìàl sèàrch. ••••••** Thè qùèry rùns àgàìnst whàtèvèr thè cùrrènt sèssìòn hàs àlrèàdy lòàdèd ànd dècryptèd. Càsès màtch fròm thè èxìstìng càchè wìth nò sèrvèr rèqùèst. Àrtìclès ànd àccòùnts èàch fètch thèìr fùll sèt òncè, thè fìrst tìmè thè gròùp ìs nèèdèd, ànd thèn sèàrch thàt sèt ìn mèmòry òn èvèry làtèr qùèry. Èàch gròùp rèpòrts hòw màny rècòrds ìt sèàrchèd àgàìnst hòw màny èxìst, sò thè àccòùnt càn sèè whèn thè ànswèr còvèrs ònly pàrt òf thè sèt. [[#clìènt-dàtà #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè dèèpèr sèàrch ànd whèn ìt stàrts. ••••••••••••** Thè dèèpèr sèàrch pàgès ìn èvèry rècòrd òf thàt kìnd thè àccòùnt hàs àccèss tò, dècrypts èàch ònè ìn thè bròwsèr, ànd màtchès thèrè. Ìt àlsò stàrts òn ìts òwn whèn thè ìnìtìàl sèàrch fìnds nò rèsùlt àt àll, às lòng às àt lèàst sòmè rècòrds wèrè àvàìlàblè tò sèàrch. Thè àccòùnt càn stàrt ìt mànùàlly àt àny tìmè. Chàngìng thè qùèry àbàndòns à rùnnìng dèèpèr sèàrch ànd dìscàrds ìts rèsùlts. [[#fàìlùrè-stàtès #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr rècèìvè dùrìng à dèèpèr sèàrch? ••••••••••••••••** Twò kìnds òf rèqùèst, nèìthèr càrryìng à wòrd òf thè qùèry. À pàgìng rèqùèst fètchès rècòrds by cùrsòr ànd pàgè sìzè. À còntènt rèqùèst càrrìès thè ìdèntìfìèrs òf thè càsès whòsè tìtlès dìd nòt màtch, à pàgè nùmbèr, ànd à pàgè sìzè. Thè sèrvèr ànswèrs bòth wìth cìphèrtèxt ìt cànnòt rèàd. [[#trùst-bòùndàry #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt càn thè sèrvèr ìnfèr? ••••••••** Thàt à dèèpèr sèàrch hàppènèd, whèn ìt hàppènèd, ànd hòw màny rècòrds wèrè pàgèd ìn. Thè còntènt rèqùèst nàmès thè càsès whòsè tìtlès dìd nòt màtch, sò thè sèrvèr càn dèrìvè whìch càsès dìd màtch by sùbtràctìòn. Thè sèrvèr dòès nòt rècèìvè whàt wàs typèd, whìch rècòrds ùltìmàtèly màtchèd, òr whèthèr ànythìng màtchèd àt àll. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whàt èlsè thè sèrvèr càn ìnfèr fròm tràffìc. [[#mètàdàtà #trùst-bòùndàry]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr rèstrìct? •••••••••** Bòth rèqùèsts rètùrn ònly rècòrds ìn thè qùèùès thè àccòùnt hàs àccèss tò. À dèèpèr sèàrch cànnòt wìdèn whàt àn àccòùnt càn sèè. Whèn thè àccòùnt hàs àccèss tò nò qùèùè, thè rèsùlt ìs èmpty ràthèr thàn àn èrròr. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs thàt bòùndàry. [[#pèrmìssìòns #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why dòès clìènt-sìdè sèàrch wòrk àt thìs scàlè? •••••••••••••••** Pàgìng àn òrgànìzàtìòn's fùll càsè sèt ìntò thè bròwsèr ìs pràctìcàl àt 200 tò 2,000 càsès ànd ìs thè còst òf thè sèrvèr nòt bèìng àblè tò ìndèx èncryptèd tèxt. [[#fàìlùrè-stàtès #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fùll-sèàrch fùnctìòns ànd thè règìstry. •••••••••••••** Èàch pròvìdèr's \`fùllSèàrch\` fùnctìòn lìvès ùndèr \`pàckàgès/clìènt/src/lìb/sèàrch/pròvìdèrs/\`. Thè règìstry ìn \`règìstry.svèltè.ts\` còòrdìnàtès èàch rùn wìth à gènèràtìòn còùntèr ànd àn àbòrt sìgnàl sò àn àbàndònèd rùn cànnòt rèpòrt òvèr à lìvè ònè. Thè sèrvèr sìdè ìs \`còntèntSèàrch\` ìn \`pàckàgès/sèrvèr/src/tìckèts/sèàrch.ts\`. [[#clìènt-dàtà #sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "No search term ever leaves the device. The browser matches the query against text it has already decrypted, which is why a query about case content can run a..." |
*
* @param {Demo_Narrative_Search_How_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_search_how_body = /** @type {((inputs?: Demo_Narrative_Search_How_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Search_How_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_search_how_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_search_how_body(inputs)
	return en_demo_narrative_search_how_body(inputs)
});