/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Portal_Passphrase_BodyInputs */

const en_demo_narrative_client_portal_passphrase_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Passphrase_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A link created with a passphrase asks for the five spoken words before any message is decrypted, and the organization holds no copy of them to lose or hand over. [[#portal #keys]]
**Why a guess costs a round trip.** The browser stretches the normalized passphrase with Argon2id, folds the result together with the credential from the link, and sends a blinded value to be evaluated under a tag naming that organization and that channel. Only the evaluated answer derives the channel keypair, so a guess cannot be tested on the device holding the link, and each attempt is a rate-limited request that can be refused. Revoking the channel retires the tag, after which no evaluation for it is answered at all. [How keys are derived](#deep-dive/how-keys-are-derived) covers the evaluation and the two holders that answer it. [[#keys #encryption]]
**How a wrong passphrase is recognized.** The channel row carries a small ciphertext sealed to the correct public key, and the browser tells a right passphrase from a wrong one by opening it locally. The server is told nothing about the outcome, so it cannot learn which guesses were close or which link someone is working on. [[#server-holds #privacy]]
**Typing the words back differently.** Capitalization, spacing and unicode form are normalized before the stretch, so words heard on a call and typed back with capitals, double spaces or an accented keyboard derive the same key. Word identity and word order are the only things that have to match. [[#failure-states #keys]]
**What the wait during entry is.** Argon2id is deliberately expensive, and the evaluation is a network round trip that may also carry a proof-of-work puzzle the browser solves first, so entry takes seconds by design rather than by accident. [[#keys #failure-states]]
**Where the gate runs.** The gate is \`PortalPassphraseGate.svelte\` in \`packages/client/src/lib/portal/\`, the stretch and the fold are \`stretchPassphrase\` and \`portalOprfInput\` in \`packages/crypto/src/portal.ts\`, and the key check comes back on the bootstrap response from \`packages/server/src/portal/portal-message-service.ts\`. The words themselves are drawn on the organization's side, which [Setting up a secure link](#ticket-detail/secure-link) covers. [[#keys #portal]]`)
};

const es_demo_narrative_client_portal_passphrase_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Passphrase_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un enlace creado con frase de paso pide las cinco palabras habladas antes de descifrar ningún mensaje, y la organización no guarda ninguna copia de ellas que pueda perder o entregar. [[#portal #keys]]
**Por qué cada intento cuesta una ida y vuelta.** El navegador estira con Argon2id la frase de paso normalizada, une el resultado con la credencial del enlace y envía un valor cegado para que se evalúe bajo una etiqueta que nombra a esa organización y a ese canal. Solo la respuesta evaluada deriva el par de claves del canal, así que un intento no se puede probar en el dispositivo que tiene el enlace, y cada uno es una solicitud limitada que se puede rechazar. Revocar el canal retira la etiqueta, y a partir de ahí no se responde ninguna evaluación para ella. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata la evaluación y los dos titulares que la responden. [[#keys #encryption]]
**Cómo se reconoce una frase de paso incorrecta.** La fila del canal lleva un pequeño texto cifrado sellado con la clave pública correcta, y el navegador distingue una frase de paso correcta de una incorrecta abriéndolo de forma local. Al servidor no se le comunica el resultado, así que no puede saber qué intentos estuvieron cerca ni sobre qué enlace está trabajando alguien. [[#server-holds #privacy]]
**Escribir las palabras de otra manera.** Las mayúsculas, los espacios y la forma unicode se normalizan antes del estirado, de modo que unas palabras oídas en una llamada y escritas con mayúsculas, espacios dobles o un teclado con acentos derivan la misma clave. La identidad y el orden de las palabras son lo único que tiene que coincidir. [[#failure-states #keys]]
**Qué es la espera durante la entrada.** Argon2id es costoso a propósito, y la evaluación es una ida y vuelta por red que además puede traer un problema de prueba de trabajo que el navegador resuelve antes, así que la entrada tarda varios segundos por diseño y no por accidente. [[#keys #failure-states]]
**Dónde se ejecuta la puerta de entrada.** La puerta es \`PortalPassphraseGate.svelte\`, en \`packages/client/src/lib/portal/\`; el estirado y la unión son \`stretchPassphrase\` y \`portalOprfInput\`, en \`packages/crypto/src/portal.ts\`; y la comprobación de clave llega en la respuesta de arranque desde \`packages/server/src/portal/portal-message-service.ts\`. Las palabras se sortean en el lado de la organización, que trata [Crear un enlace seguro](#ticket-detail/secure-link). [[#keys #portal]]`)
};

const en_xa2_demo_narrative_client_portal_passphrase_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Passphrase_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À lìnk crèàtèd wìth à pàssphràsè àsks fòr thè fìvè spòkèn wòrds bèfòrè àny mèssàgè ìs dècryptèd, ànd thè òrgànìzàtìòn hòlds nò còpy òf thèm tò lòsè òr hànd òvèr. [[#pòrtàl #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why à gùèss còsts à ròùnd trìp. ••••••••••** Thè bròwsèr strètchès thè nòrmàlìzèd pàssphràsè wìth Àrgòn2ìd, fòlds thè rèsùlt tògèthèr wìth thè crèdèntìàl fròm thè lìnk, ànd sènds à blìndèd vàlùè tò bè èvàlùàtèd ùndèr à tàg nàmìng thàt òrgànìzàtìòn ànd thàt chànnèl. Ònly thè èvàlùàtèd ànswèr dèrìvès thè chànnèl kèypàìr, sò à gùèss cànnòt bè tèstèd òn thè dèvìcè hòldìng thè lìnk, ànd èàch àttèmpt ìs à ràtè-lìmìtèd rèqùèst thàt càn bè rèfùsèd. Rèvòkìng thè chànnèl rètìrès thè tàg, àftèr whìch nò èvàlùàtìòn fòr ìt ìs ànswèrèd àt àll. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs thè èvàlùàtìòn ànd thè twò hòldèrs thàt ànswèr ìt. [[#kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw à wròng pàssphràsè ìs rècògnìzèd. ••••••••••••** Thè chànnèl ròw càrrìès à smàll cìphèrtèxt sèàlèd tò thè còrrèct pùblìc kèy, ànd thè bròwsèr tèlls à rìght pàssphràsè fròm à wròng ònè by òpènìng ìt lòcàlly. Thè sèrvèr ìs tòld nòthìng àbòùt thè òùtcòmè, sò ìt cànnòt lèàrn whìch gùèssès wèrè clòsè òr whìch lìnk sòmèònè ìs wòrkìng òn. [[#sèrvèr-hòlds #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Typìng thè wòrds bàck dìffèrèntly. •••••••••••** Càpìtàlìzàtìòn, spàcìng ànd ùnìcòdè fòrm àrè nòrmàlìzèd bèfòrè thè strètch, sò wòrds hèàrd òn à càll ànd typèd bàck wìth càpìtàls, dòùblè spàcès òr àn àccèntèd kèybòàrd dèrìvè thè sàmè kèy. Wòrd ìdèntìty ànd wòrd òrdèr àrè thè ònly thìngs thàt hàvè tò màtch. [[#fàìlùrè-stàtès #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè wàìt dùrìng èntry ìs. •••••••••** Àrgòn2ìd ìs dèlìbèràtèly èxpènsìvè, ànd thè èvàlùàtìòn ìs à nètwòrk ròùnd trìp thàt mày àlsò càrry à pròòf-òf-wòrk pùzzlè thè bròwsèr sòlvès fìrst, sò èntry tàkès sècònds by dèsìgn ràthèr thàn by àccìdènt. [[#kèys #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèrè thè gàtè rùns. ••••••** Thè gàtè ìs \`PòrtàlPàssphràsèGàtè.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/pòrtàl/\`, thè strètch ànd thè fòld àrè \`strètchPàssphràsè\` ànd \`pòrtàlÒprfÌnpùt\` ìn \`pàckàgès/cryptò/src/pòrtàl.ts\`, ànd thè kèy chèck còmès bàck òn thè bòòtstràp rèspònsè fròm \`pàckàgès/sèrvèr/src/pòrtàl/pòrtàl-mèssàgè-sèrvìcè.ts\`. Thè wòrds thèmsèlvès àrè dràwn òn thè òrgànìzàtìòn's sìdè, whìch [Sèttìng ùp à sècùrè lìnk](#tìckèt-dètàìl/sècùrè-lìnk) còvèrs. [[#kèys #pòrtàl]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A link created with a passphrase asks for the five spoken words before any message is decrypted, and the organization holds no copy of them to lose or hand o..." |
*
* @param {Demo_Narrative_Client_Portal_Passphrase_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_portal_passphrase_body = /** @type {((inputs?: Demo_Narrative_Client_Portal_Passphrase_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Portal_Passphrase_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_portal_passphrase_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_portal_passphrase_body(inputs)
	return en_demo_narrative_client_portal_passphrase_body(inputs)
});