/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Queues_BodyInputs */

const en_demo_narrative_admin_queues_body = /** @type {(inputs: Demo_Narrative_Admin_Queues_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Queues are governed by three independent permissions. The Manage queues permission controls creation, reordering and deletion. The Manage queue membership permission controls who belongs to each queue. The Manage queue notifications permission controls who receives alerts when a queue's tickets change. [[#permissions]]
**What does creating a queue encrypt?** The browser encrypts the queue's name, color, icon, and fund reference under the organization key before sending the request. The server stores only the ciphertext, appends a sort position after the current highest, and records the organization key generation in force at the time. [Queue overview](#dashboard/queues) covers the plaintext columns each queue keeps. [[#encryption]]
**Fund mapping.** The queue editor lets a user with Manage queues and View funds set which fund a queue draws on. The sealed fund reference follows the same org-key ciphertext pattern as the queue's encrypted color and icon. Cases in that queue inherit the mapped fund for disbursements and balance display. [Fund balances](#ticket-detail/fund-balance) covers what the case panel and the dashboard card show. [[#encryption #server-holds]]
**Reordering and deletion.** Reordering renumbers every queue's position inside one transaction, in two passes, because no two queues may share a position. Deleting a queue is refused while it is the last one remaining. Deleting a queue that holds tickets is refused until another queue is named to receive them. Once a destination is named, the tickets move, and the membership and watcher rows for the deleted queue are removed with it. [[#metadata #failure-states]]
**Membership and access.** Adding an account to a queue grants it access to every ticket in that queue. Removing the account deletes its assignment row and revokes access on the next request. [The permission system](#deep-dive/the-permission-system) covers how access is checked. [[#permissions #keys]]
**How does a new member receive keys?** Membership grants access but issues no keys. A browser that already holds ticket keys detects members in its queues who are missing wraps, mints one wrap per ticket against that member's public key, and submits them. The sweep runs after sign-in. Until a teammate's browser completes it, the new member can reach each ticket's plaintext fields but cannot decrypt its title or content. [[#keys #encryption]]
**Intake form routing.** A submitted intake form goes to the queue the form names. When the form names none, the ticket goes to the organization's fallback intake queue. Setting that fallback requires the Manage channel routing permission. The fallback queue identifier is stored as plaintext on the organization's configuration row. [Intake forms list](#admin-org/intake-forms) covers per-form destination settings. [[#metadata #permissions]]`)
};

const es_demo_narrative_admin_queues_body = /** @type {(inputs: Demo_Narrative_Admin_Queues_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Las colas se rigen por tres permisos independientes. El permiso Gestionar colas controla la creación, el reordenamiento y la eliminación. El permiso Gestionar membresía de colas controla quién pertenece a cada cola. El permiso Gestionar notificaciones de colas controla quién recibe alertas cuando cambian los tickets de una cola. [[#permissions]]
**¿Qué cifra la creación de una cola?** El navegador cifra el nombre, el color, el icono y la referencia de fondo de la cola con la clave de la organización antes de enviar la petición. El servidor almacena solo el texto cifrado, añade una posición de orden después de la más alta y registra la generación de la clave de la organización vigente en ese momento. [Vista general de colas](#dashboard/queues) trata las columnas en texto plano que conserva cada cola. [[#encryption]]
**Asignación de fondo.** El editor de colas permite a quien tenga Gestionar colas y Ver fondos establecer qué fondo usa la cola. La referencia sellada del fondo sigue el mismo patrón de texto cifrado con clave de organización que el color y el icono cifrados de la cola. Los casos de esa cola heredan el fondo asignado para desembolsos y visualización del saldo. [Saldo de fondos](#ticket-detail/fund-balance) trata lo que muestran el panel del caso y la tarjeta del panel de inicio. [[#encryption #server-holds]]
**Reordenar y eliminar.** Reordenar renumera la posición de cada cola dentro de una transacción, en dos pasadas, porque dos colas no pueden compartir posición. La eliminación se rechaza mientras sea la última cola restante. La eliminación de una cola que tiene tickets se rechaza hasta que se nombra otra cola que los reciba. Una vez nombrado el destino, los tickets se trasladan y las filas de membresía y de observador de la cola eliminada se borran con ella. [[#metadata #failure-states]]
**Membresía y acceso.** Agregar una cuenta a una cola le concede acceso a todos los tickets de esa cola. Eliminar la cuenta borra su fila de asignación y revoca el acceso en la siguiente petición. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se comprueba el acceso. [[#permissions #keys]]
**¿Cómo recibe claves un miembro nuevo?** La membresía concede acceso pero no entrega claves. Un navegador que ya tiene las claves de los tickets detecta miembros de sus colas a los que les faltan envoltorios, crea un envoltorio por ticket con la clave pública de ese miembro y los envía. El barrido se ejecuta después de iniciar sesión. Hasta que el navegador de otro miembro lo completa, el miembro nuevo puede acceder a los campos en texto plano de cada ticket pero no puede descifrar su título ni su contenido. [[#keys #encryption]]
**Enrutamiento de formularios de admisión.** Un formulario de admisión enviado va a la cola que indica el formulario. Cuando el formulario no indica ninguna, el ticket va a la cola de admisión de respaldo de la organización. Fijar ese respaldo requiere el permiso Gestionar enrutamiento de canales. El identificador de la cola de respaldo se almacena como texto plano en la fila de configuración de la organización. [Lista de formularios de admisión](#admin-org/intake-forms) trata la configuración de destino por formulario. [[#metadata #permissions]]`)
};

const en_xa2_demo_narrative_admin_queues_body = /** @type {(inputs: Demo_Narrative_Admin_Queues_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Qùèùès àrè gòvèrnèd by thrèè ìndèpèndènt pèrmìssìòns. Thè Mànàgè qùèùès pèrmìssìòn còntròls crèàtìòn, rèòrdèrìng ànd dèlètìòn. Thè Mànàgè qùèùè mèmbèrshìp pèrmìssìòn còntròls whò bèlòngs tò èàch qùèùè. Thè Mànàgè qùèùè nòtìfìcàtìòns pèrmìssìòn còntròls whò rècèìvès àlèrts whèn à qùèùè's tìckèts chàngè. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès crèàtìng à qùèùè èncrypt? •••••••••••** Thè bròwsèr èncrypts thè qùèùè's nàmè, còlòr, ìcòn, ànd fùnd rèfèrèncè ùndèr thè òrgànìzàtìòn kèy bèfòrè sèndìng thè rèqùèst. Thè sèrvèr stòrès ònly thè cìphèrtèxt, àppènds à sòrt pòsìtìòn àftèr thè cùrrènt hìghèst, ànd rècòrds thè òrgànìzàtìòn kèy gènèràtìòn ìn fòrcè àt thè tìmè. [Qùèùè òvèrvìèw](#dàshbòàrd/qùèùès) còvèrs thè plàìntèxt còlùmns èàch qùèùè kèèps. [[#èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Fùnd màppìng. ••••** Thè qùèùè èdìtòr lèts à ùsèr wìth Mànàgè qùèùès ànd Vìèw fùnds sèt whìch fùnd à qùèùè dràws òn. Thè sèàlèd fùnd rèfèrèncè fòllòws thè sàmè òrg-kèy cìphèrtèxt pàttèrn às thè qùèùè's èncryptèd còlòr ànd ìcòn. Càsès ìn thàt qùèùè ìnhèrìt thè màppèd fùnd fòr dìsbùrsèmènts ànd bàlàncè dìsplày. [Fùnd bàlàncès](#tìckèt-dètàìl/fùnd-bàlàncè) còvèrs whàt thè càsè pànèl ànd thè dàshbòàrd càrd shòw. [[#èncryptìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rèòrdèrìng ànd dèlètìòn. ••••••••** Rèòrdèrìng rènùmbèrs èvèry qùèùè's pòsìtìòn ìnsìdè ònè trànsàctìòn, ìn twò pàssès, bècàùsè nò twò qùèùès mày shàrè à pòsìtìòn. Dèlètìng à qùèùè ìs rèfùsèd whìlè ìt ìs thè làst ònè rèmàìnìng. Dèlètìng à qùèùè thàt hòlds tìckèts ìs rèfùsèd ùntìl ànòthèr qùèùè ìs nàmèd tò rècèìvè thèm. Òncè à dèstìnàtìòn ìs nàmèd, thè tìckèts mòvè, ànd thè mèmbèrshìp ànd wàtchèr ròws fòr thè dèlètèd qùèùè àrè rèmòvèd wìth ìt. [[#mètàdàtà #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Mèmbèrshìp ànd àccèss. •••••••** Àddìng àn àccòùnt tò à qùèùè grànts ìt àccèss tò èvèry tìckèt ìn thàt qùèùè. Rèmòvìng thè àccòùnt dèlètès ìts àssìgnmènt ròw ànd rèvòkès àccèss òn thè nèxt rèqùèst. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw àccèss ìs chèckèd. [[#pèrmìssìòns #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès à nèw mèmbèr rècèìvè kèys? •••••••••••** Mèmbèrshìp grànts àccèss bùt ìssùès nò kèys. À bròwsèr thàt àlrèàdy hòlds tìckèt kèys dètècts mèmbèrs ìn ìts qùèùès whò àrè mìssìng wràps, mìnts ònè wràp pèr tìckèt àgàìnst thàt mèmbèr's pùblìc kèy, ànd sùbmìts thèm. Thè swèèp rùns àftèr sìgn-ìn. Ùntìl à tèàmmàtè's bròwsèr còmplètès ìt, thè nèw mèmbèr càn rèàch èàch tìckèt's plàìntèxt fìèlds bùt cànnòt dècrypt ìts tìtlè òr còntènt. [[#kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ìntàkè fòrm ròùtìng. ••••••** À sùbmìttèd ìntàkè fòrm gòès tò thè qùèùè thè fòrm nàmès. Whèn thè fòrm nàmès nònè, thè tìckèt gòès tò thè òrgànìzàtìòn's fàllbàck ìntàkè qùèùè. Sèttìng thàt fàllbàck rèqùìrès thè Mànàgè chànnèl ròùtìng pèrmìssìòn. Thè fàllbàck qùèùè ìdèntìfìèr ìs stòrèd às plàìntèxt òn thè òrgànìzàtìòn's cònfìgùràtìòn ròw. [Ìntàkè fòrms lìst](#àdmìn-òrg/ìntàkè-fòrms) còvèrs pèr-fòrm dèstìnàtìòn sèttìngs. [[#mètàdàtà #pèrmìssìòns]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Queues are governed by three independent permissions. The Manage queues permission controls creation, reordering and deletion. The Manage queue membership pe..." |
*
* @param {Demo_Narrative_Admin_Queues_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_queues_body = /** @type {((inputs?: Demo_Narrative_Admin_Queues_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Queues_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_queues_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_queues_body(inputs)
	return en_demo_narrative_admin_queues_body(inputs)
});