/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Client_Merge_BodyInputs */

const en_demo_narrative_admin_client_merge_body = /** @type {(inputs: Demo_Narrative_Admin_Client_Merge_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Merging two client records sets one as the survivor and writes a pointer from the other into it. Neither record is rewritten. The merged-away record keeps its own cases and its own row, so the survivor's case count stays separate and both histories remain distinct. [[#client-data]]
**What does the merge close and revoke?** The merge closes the merged-away record's open case and writes a system note on it. A case whose ticket depends on an open ticket elsewhere blocks the merge rather than closing with unresolved work. When both records have an active portal channel, one channel is kept and the other is revoked. The revoked channel's content is kept until the merge is locked. When only the merged-away record has a channel, that channel is moved to the survivor. [[#client-data #portal]]
**What does undo restore?** The browser seals a snapshot of the merged-away record with the organization key before sending the merge request. Undo removes the pointer and flags the event as reversed. Before the merge is locked, undo reopens the closed case, reinstates a revoked channel and its content, and points a moved channel back to its original record. The user can lock a merge against undo once its result is settled. After locking, undo is no longer available. [[#encryption #failure-states]]
**What does the server hold in plaintext?** The merge event row stores both clients' identifiers, the timestamp, whether the event is reversed, and whether undo is locked. The snapshot sits beside them as organization-key ciphertext. The audit log gains a row for the merge, for an undo, and for a lock change; each row carries the clients' identifiers and no names. [Audit log](#admin-logs/audit) covers what an audit row holds. [[#server-holds #metadata]]
**What does the Merge clients permission cover?** Merging, undoing, and locking all require the Merge clients permission, which is separate from View clients. The user can read the client list without being able to consolidate it. [Possible duplicates](#dashboard/merge-candidates) covers the scan that proposes pairs. [[#permissions]]
**The merge transaction and channel helpers.** \`createMergeService\` in \`packages/server/src/tickets/merge-service.ts\` runs the merge, the undo, and the lock toggle. Channel collisions are resolved by \`reconcileChannels\` in the same file, which delegates to \`purgeAndRevokeChannel\` in \`packages/server/src/portal/channel-service.ts\` for the destructive path and to \`repointChannel\` for the move path. The dependency check is \`allResolved\` in \`packages/server/src/tickets/dependency-service.ts\`. [[#client-data]]`)
};

const es_demo_narrative_admin_client_merge_body = /** @type {(inputs: Demo_Narrative_Admin_Client_Merge_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Fusionar dos registros de cliente establece uno como superviviente y escribe un puntero del otro hacia él. Ninguno de los dos registros se reescribe. El registro fusionado conserva sus propios casos y su propia fila, de modo que el recuento de casos del superviviente se mantiene aparte y ambos historiales quedan diferenciados. [[#client-data]]
**¿Qué cierra y revoca la fusión?** La fusión cierra el caso abierto del registro fusionado y escribe una nota del sistema en él. Un caso cuyo ticket depende de un ticket abierto en otro lugar bloquea la fusión en lugar de cerrarse con trabajo pendiente. Cuando ambos registros tienen un canal del portal activo, se conserva uno y se revoca el otro. El contenido del canal revocado se conserva hasta que la fusión se bloquea. Cuando solo el registro fusionado tiene un canal, ese canal se traslada al superviviente. [[#client-data #portal]]
**¿Qué restaura deshacer?** El navegador sella una instantánea del registro fusionado con la clave de la organización antes de enviar la petición de fusión. Deshacer elimina el puntero y marca el evento como revertido. Antes de bloquear la fusión, deshacer reabre el caso cerrado, restablece el canal revocado junto con su contenido y devuelve un canal trasladado a su registro original. La persona usuaria puede bloquear una fusión contra deshacer cuando su resultado ya está asentado. Tras el bloqueo, deshacer deja de estar disponible. [[#encryption #failure-states]]
**¿Qué guarda el servidor en texto plano?** La fila del evento de fusión almacena los identificadores de ambos clientes, la marca de tiempo, si el evento está revertido y si deshacer está bloqueado. La instantánea está junto a ellos como texto cifrado con la clave de la organización. El registro de auditoría suma una fila por la fusión, otra por deshacer y otra por un cambio de bloqueo; cada fila lleva los identificadores de los clientes y ningún nombre. [Registro de auditoría](#admin-logs/audit) trata lo que guarda una fila de auditoría. [[#server-holds #metadata]]
**¿Qué cubre el permiso Fusionar clientes?** Fusionar, deshacer y bloquear requieren el permiso Fusionar clientes, que es distinto de Ver clientes. La persona usuaria puede leer la lista de clientes sin poder consolidarla. [Posibles duplicados](#dashboard/merge-candidates) trata el análisis que propone parejas. [[#permissions]]
**La transacción de fusión y los auxiliares de canal.** \`createMergeService\`, en \`packages/server/src/tickets/merge-service.ts\`, ejecuta la fusión, la reversión y el cambio de bloqueo. Las colisiones de canal se resuelven en \`reconcileChannels\` del mismo archivo, que delega en \`purgeAndRevokeChannel\` de \`packages/server/src/portal/channel-service.ts\` para la ruta destructiva y en \`repointChannel\` para la ruta de traslado. La comprobación de dependencias es \`allResolved\` en \`packages/server/src/tickets/dependency-service.ts\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_admin_client_merge_body = /** @type {(inputs: Demo_Narrative_Admin_Client_Merge_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Mèrgìng twò clìènt rècòrds sèts ònè às thè sùrvìvòr ànd wrìtès à pòìntèr fròm thè òthèr ìntò ìt. Nèìthèr rècòrd ìs rèwrìttèn. Thè mèrgèd-àwày rècòrd kèèps ìts òwn càsès ànd ìts òwn ròw, sò thè sùrvìvòr's càsè còùnt stàys sèpàràtè ànd bòth hìstòrìès rèmàìn dìstìnct. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè mèrgè clòsè ànd rèvòkè? ••••••••••••** Thè mèrgè clòsès thè mèrgèd-àwày rècòrd's òpèn càsè ànd wrìtès à systèm nòtè òn ìt. À càsè whòsè tìckèt dèpènds òn àn òpèn tìckèt èlsèwhèrè blòcks thè mèrgè ràthèr thàn clòsìng wìth ùnrèsòlvèd wòrk. Whèn bòth rècòrds hàvè àn àctìvè pòrtàl chànnèl, ònè chànnèl ìs kèpt ànd thè òthèr ìs rèvòkèd. Thè rèvòkèd chànnèl's còntènt ìs kèpt ùntìl thè mèrgè ìs lòckèd. Whèn ònly thè mèrgèd-àwày rècòrd hàs à chànnèl, thàt chànnèl ìs mòvèd tò thè sùrvìvòr. [[#clìènt-dàtà #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès ùndò rèstòrè? •••••••** Thè bròwsèr sèàls à snàpshòt òf thè mèrgèd-àwày rècòrd wìth thè òrgànìzàtìòn kèy bèfòrè sèndìng thè mèrgè rèqùèst. Ùndò rèmòvès thè pòìntèr ànd flàgs thè èvènt às rèvèrsèd. Bèfòrè thè mèrgè ìs lòckèd, ùndò rèòpèns thè clòsèd càsè, rèìnstàtès à rèvòkèd chànnèl ànd ìts còntènt, ànd pòìnts à mòvèd chànnèl bàck tò ìts òrìgìnàl rècòrd. Thè ùsèr càn lòck à mèrgè àgàìnst ùndò òncè ìts rèsùlt ìs sèttlèd. Àftèr lòckìng, ùndò ìs nò lòngèr àvàìlàblè. [[#èncryptìòn #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr hòld ìn plàìntèxt? ••••••••••••** Thè mèrgè èvènt ròw stòrès bòth clìènts' ìdèntìfìèrs, thè tìmèstàmp, whèthèr thè èvènt ìs rèvèrsèd, ànd whèthèr ùndò ìs lòckèd. Thè snàpshòt sìts bèsìdè thèm às òrgànìzàtìòn-kèy cìphèrtèxt. Thè àùdìt lòg gàìns à ròw fòr thè mèrgè, fòr àn ùndò, ànd fòr à lòck chàngè; èàch ròw càrrìès thè clìènts' ìdèntìfìèrs ànd nò nàmès. [Àùdìt lòg](#àdmìn-lògs/àùdìt) còvèrs whàt àn àùdìt ròw hòlds. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè Mèrgè clìènts pèrmìssìòn còvèr? ••••••••••••••** Mèrgìng, ùndòìng, ànd lòckìng àll rèqùìrè thè Mèrgè clìènts pèrmìssìòn, whìch ìs sèpàràtè fròm Vìèw clìènts. Thè ùsèr càn rèàd thè clìènt lìst wìthòùt bèìng àblè tò cònsòlìdàtè ìt. [Pòssìblè dùplìcàtès](#dàshbòàrd/mèrgè-càndìdàtès) còvèrs thè scàn thàt pròpòsès pàìrs. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè mèrgè trànsàctìòn ànd chànnèl hèlpèrs. •••••••••••••** \`crèàtèMèrgèSèrvìcè\` ìn \`pàckàgès/sèrvèr/src/tìckèts/mèrgè-sèrvìcè.ts\` rùns thè mèrgè, thè ùndò, ànd thè lòck tògglè. Chànnèl còllìsìòns àrè rèsòlvèd by \`rècòncìlèChànnèls\` ìn thè sàmè fìlè, whìch dèlègàtès tò \`pùrgèÀndRèvòkèChànnèl\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/chànnèl-sèrvìcè.ts\` fòr thè dèstrùctìvè pàth ànd tò \`rèpòìntChànnèl\` fòr thè mòvè pàth. Thè dèpèndèncy chèck ìs \`àllRèsòlvèd\` ìn \`pàckàgès/sèrvèr/src/tìckèts/dèpèndèncy-sèrvìcè.ts\`. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Merging two client records sets one as the survivor and writes a pointer from the other into it. Neither record is rewritten. The merged-away record keeps it..." |
*
* @param {Demo_Narrative_Admin_Client_Merge_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_client_merge_body = /** @type {((inputs?: Demo_Narrative_Admin_Client_Merge_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Client_Merge_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_client_merge_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_client_merge_body(inputs)
	return en_demo_narrative_admin_client_merge_body(inputs)
});