/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Portal_Passphrase_BodyInputs */

const en_demo_narrative_client_portal_passphrase_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Passphrase_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`When a secure link carries a passphrase, the client enters it before any message is decrypted. The passphrase exists only in the browser of the user who created the link, for the duration of that setup step, and is spoken aloud on the call. No copy is written to the server, to the ticket thread, or to any audit record. [[#portal #keys]]
**Why can a guess not be checked locally?** Each guess is a request to the server, not a computation the device can run on its own. The server rate-limits these requests and can refuse them. A proof-of-work puzzle may be required before a request is answered. The combined cost is deliberate. Revoking the channel stops all further guesses from being answered. [[#keys #encryption]]
**What does the server see during entry?** The server sees each attempt against a named channel, the timing of each attempt, and the network address it came from. It does not learn whether any attempt was correct. The browser checks the result locally against a small ciphertext sealed to the correct public key, and reports nothing back. [[#server-holds #privacy]]
**Normalization.** Capitalization, spacing, and accented characters typed different ways are all normalized before derivation. A passphrase spoken on a call and retyped with different casing or extra spaces still derives the same key. Only the words themselves and their order need to match. [[#failure-states #keys]]
**The derivation path and its components.** The browser stretches the normalized passphrase with Argon2id, concatenates the result with the seed from the link, and sends a blinded value for evaluation under a tag naming that organization and channel. Only the evaluated answer derives the channel keypair. The gate is \`PortalPassphraseGate.svelte\` in \`packages/client/src/lib/portal/\`. The concatenation and blinding input are built by \`portalOprfInput\` in \`packages/crypto/src/portal.ts\`, which calls a private \`stretchPassphrase\` function internally. The key-check ciphertext is returned in the bootstrap response from \`packages/server/src/portal/portal-message-service.ts\`. [How keys are derived](#deep-dive/how-keys-are-derived) covers the evaluation and the two holders that answer it. The passphrase words are drawn on the organization side, in the setup step of \`SecureLinkSheet.svelte\`. [Secure link setup](#ticket-detail/secure-link) covers how a user creates the link and the passphrase. [[#keys #portal]]`)
};

const es_demo_narrative_client_portal_passphrase_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Passphrase_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cuando un enlace seguro lleva frase de paso, el cliente la introduce antes de que se descifre ningún mensaje. La frase de paso existe solo en el navegador de la persona usuaria que creó el enlace, durante ese paso de configuración, y se dice en voz alta en la llamada. No se escribe ninguna copia en el servidor, en el hilo del ticket ni en ningún registro de auditoría. [[#portal #keys]]
**¿Por qué no se puede comprobar un intento en el dispositivo?** Cada intento es una solicitud al servidor, no un cálculo que el dispositivo pueda ejecutar por su cuenta. El servidor limita la frecuencia de estas solicitudes y puede rechazarlas. Puede exigirse un problema de prueba de trabajo antes de responder. El coste combinado es deliberado. Revocar el canal impide que se responda ningún intento posterior. [[#keys #encryption]]
**¿Qué ve el servidor durante la entrada?** El servidor ve cada intento contra un canal identificado, la hora de cada intento y la dirección de red de donde proviene. No sabe si algún intento fue correcto. El navegador comprueba el resultado localmente contra un pequeño texto cifrado sellado con la clave pública correcta, y no comunica nada al servidor. [[#server-holds #privacy]]
**Normalización.** Las mayúsculas, los espacios y los caracteres acentuados escritos de distintas formas se normalizan antes de la derivación. Una frase de paso dicha en una llamada y reescrita con mayúsculas distintas o espacios de más aún deriva la misma clave. Solo las palabras en sí y su orden necesitan coincidir. [[#failure-states #keys]]
**La ruta de derivación y sus componentes.** El navegador estira la frase de paso normalizada con Argon2id, concatena el resultado con la semilla del enlace y envía un valor cegado para evaluación bajo una etiqueta que nombra esa organización y ese canal. Solo la respuesta evaluada deriva el par de claves del canal. La puerta es \`PortalPassphraseGate.svelte\` en \`packages/client/src/lib/portal/\`. La concatenación y la entrada de cegado se construyen con \`portalOprfInput\` en \`packages/crypto/src/portal.ts\`, que internamente llama a una función privada \`stretchPassphrase\`. El texto cifrado de comprobación de clave se devuelve en la respuesta de arranque desde \`packages/server/src/portal/portal-message-service.ts\`. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata la evaluación y los dos titulares que la responden. Las palabras de la frase de paso se sortean en el lado de la organización, en el paso de configuración de \`SecureLinkSheet.svelte\`. [Configuración de enlace seguro](#ticket-detail/secure-link) trata cómo se crea el enlace y la frase de paso. [[#keys #portal]]`)
};

const en_xa2_demo_narrative_client_portal_passphrase_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Passphrase_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Whèn à sècùrè lìnk càrrìès à pàssphràsè, thè clìènt èntèrs ìt bèfòrè àny mèssàgè ìs dècryptèd. Thè pàssphràsè èxìsts ònly ìn thè bròwsèr òf thè ùsèr whò crèàtèd thè lìnk, fòr thè dùràtìòn òf thàt sètùp stèp, ànd ìs spòkèn àlòùd òn thè càll. Nò còpy ìs wrìttèn tò thè sèrvèr, tò thè tìckèt thrèàd, òr tò àny àùdìt rècòrd. [[#pòrtàl #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why càn à gùèss nòt bè chèckèd lòcàlly? ••••••••••••** Èàch gùèss ìs à rèqùèst tò thè sèrvèr, nòt à còmpùtàtìòn thè dèvìcè càn rùn òn ìts òwn. Thè sèrvèr ràtè-lìmìts thèsè rèqùèsts ànd càn rèfùsè thèm. À pròòf-òf-wòrk pùzzlè mày bè rèqùìrèd bèfòrè à rèqùèst ìs ànswèrèd. Thè còmbìnèd còst ìs dèlìbèràtè. Rèvòkìng thè chànnèl stòps àll fùrthèr gùèssès fròm bèìng ànswèrèd. [[#kèys #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr sèè dùrìng èntry? ••••••••••••** Thè sèrvèr sèès èàch àttèmpt àgàìnst à nàmèd chànnèl, thè tìmìng òf èàch àttèmpt, ànd thè nètwòrk àddrèss ìt càmè fròm. Ìt dòès nòt lèàrn whèthèr àny àttèmpt wàs còrrèct. Thè bròwsèr chècks thè rèsùlt lòcàlly àgàìnst à smàll cìphèrtèxt sèàlèd tò thè còrrèct pùblìc kèy, ànd rèpòrts nòthìng bàck. [[#sèrvèr-hòlds #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Nòrmàlìzàtìòn. •••••** Càpìtàlìzàtìòn, spàcìng, ànd àccèntèd chàràctèrs typèd dìffèrènt wàys àrè àll nòrmàlìzèd bèfòrè dèrìvàtìòn. À pàssphràsè spòkèn òn à càll ànd rètypèd wìth dìffèrènt càsìng òr èxtrà spàcès stìll dèrìvès thè sàmè kèy. Ònly thè wòrds thèmsèlvès ànd thèìr òrdèr nèèd tò màtch. [[#fàìlùrè-stàtès #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè dèrìvàtìòn pàth ànd ìts còmpònènts. ••••••••••••** Thè bròwsèr strètchès thè nòrmàlìzèd pàssphràsè wìth Àrgòn2ìd, còncàtènàtès thè rèsùlt wìth thè sèèd fròm thè lìnk, ànd sènds à blìndèd vàlùè fòr èvàlùàtìòn ùndèr à tàg nàmìng thàt òrgànìzàtìòn ànd chànnèl. Ònly thè èvàlùàtèd ànswèr dèrìvès thè chànnèl kèypàìr. Thè gàtè ìs \`PòrtàlPàssphràsèGàtè.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/pòrtàl/\`. Thè còncàtènàtìòn ànd blìndìng ìnpùt àrè bùìlt by \`pòrtàlÒprfÌnpùt\` ìn \`pàckàgès/cryptò/src/pòrtàl.ts\`, whìch càlls à prìvàtè \`strètchPàssphràsè\` fùnctìòn ìntèrnàlly. Thè kèy-chèck cìphèrtèxt ìs rètùrnèd ìn thè bòòtstràp rèspònsè fròm \`pàckàgès/sèrvèr/src/pòrtàl/pòrtàl-mèssàgè-sèrvìcè.ts\`. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs thè èvàlùàtìòn ànd thè twò hòldèrs thàt ànswèr ìt. Thè pàssphràsè wòrds àrè dràwn òn thè òrgànìzàtìòn sìdè, ìn thè sètùp stèp òf \`SècùrèLìnkShèèt.svèltè\`. [Sècùrè lìnk sètùp](#tìckèt-dètàìl/sècùrè-lìnk) còvèrs hòw à ùsèr crèàtès thè lìnk ànd thè pàssphràsè. [[#kèys #pòrtàl]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "When a secure link carries a passphrase, the client enters it before any message is decrypted. The passphrase exists only in the browser of the user who crea..." |
*
* @param {Demo_Narrative_Client_Portal_Passphrase_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_portal_passphrase_body = /** @type {((inputs?: Demo_Narrative_Client_Portal_Passphrase_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Portal_Passphrase_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_portal_passphrase_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_portal_passphrase_body(inputs)
	return en_demo_narrative_client_portal_passphrase_body(inputs)
});