/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Account_Sign_In_BodyInputs */

const en_demo_narrative_client_account_sign_in_body = /** @type {(inputs: Demo_Narrative_Client_Account_Sign_In_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The sign-in form asks for a username and a password. It appears on a first visit, after a reload, and after the idle timeout or a closed tab clears the keys, because the keys that open the client's messages come from the password and are not stored anywhere. [[#portal #keys]]
**What does the password produce?** The browser derives a keypair for reading the client's messages and a separate token for authenticating to the server. Both come from the password alone. The derived material stays on the device and is cleared when the page closes. [How keys are derived](#deep-dive/how-keys-are-derived) covers the derivation steps and the two servers that participate. [[#keys #encryption]]
**What does an unknown username get back?** An unknown username, a wrong password, and a nonexistent account all receive the same failure after the same amount of work. The server cannot be made to answer differently for a name that exists and one that does not. [[#server-holds #privacy]]
**How long does the session last?** The server-side session uses a short cookie with sliding renewal on human activity. The cookie that carries it cannot be read by scripts on the page. The server stores a fingerprint of the token, not the token itself. After fifteen minutes without input from the client, the idle timeout clears the keys in the browser and revokes the session. Closing the tab clears the keys but does not revoke the server session; that session lapses within twenty minutes of the last renewal. [Sign out](#client-account/sign-out) and [Quick exit](#client-portal/quick-exit) also end the session. [[#server-holds #keys #failure-states]]
**Rate limits.** Salt requests and sign-in attempts are each capped at ten per address per hour. [[#failure-states #server-holds]]
**The sign-in derivation and enumeration defense.** The browser runs Argon2id on the password, blinds the stretched result, sends the blinded value to two evaluation servers, and derives from their combined answer the keypair and authentication token. The password, the stretched output, and the derived keys stay inside a worker and are zeroed on page close. The server answers every salt request with both a real salt and a deterministic fake salt computed in parallel, and compares the presented token against a fixed dummy hash when no account row matches, so timing and work are constant regardless of whether the username exists. The session cookie is HttpOnly, SameSite=Strict, Path=/, carries no domain attribute, and is always Secure in production. The server stores a BLAKE2b hash of the session token rather than the token itself, and purges expired session rows on each successful sign-in. The form is \`AccountLoginForm.svelte\` in \`packages/client/src/lib/portal/\`. Key derivation runs in the portal worker through \`account-crypto.ts\` and \`packages/crypto/src/client-account.ts\`. The server side is \`getSaltForUsername\` and \`login\` in \`packages/server/src/portal/account-service.ts\`, against the \`client_accounts\` and \`client_account_sessions\` tables in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. [[#keys #server-holds]]`)
};

const es_demo_narrative_client_account_sign_in_body = /** @type {(inputs: Demo_Narrative_Client_Account_Sign_In_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El formulario de inicio de sesión pide un nombre de usuario y una contraseña. Aparece en la primera visita, tras recargar la página, y tras el cierre por inactividad o el cierre de la pestaña, porque las claves que abren los mensajes del cliente se derivan de la contraseña y no se almacenan en ningún lugar. [[#portal #keys]]
**¿Qué produce la contraseña?** El navegador deriva un par de claves para leer los mensajes del cliente y un token separado para autenticarse ante el servidor. Ambos provienen exclusivamente de la contraseña. El material derivado permanece en el dispositivo y se borra cuando la página se cierra. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata los pasos de derivación y los dos servidores que participan. [[#keys #encryption]]
**¿Qué recibe un nombre de usuario desconocido?** Un nombre de usuario desconocido, una contraseña incorrecta y una cuenta inexistente reciben el mismo fallo tras la misma cantidad de trabajo. No se puede hacer que el servidor responda de forma distinta para un nombre que existe y otro que no. [[#server-holds #privacy]]
**¿Cuánto dura la sesión?** La sesión en el servidor usa una cookie corta con renovación deslizante según la actividad humana. La cookie que la transporta no puede ser leída por scripts en la página. El servidor almacena una huella del token, no el token mismo. Tras quince minutos sin actividad del cliente, el cierre por inactividad borra las claves en el navegador y revoca la sesión. Cerrar la pestaña borra las claves pero no revoca la sesión del servidor; esa sesión caduca dentro de los veinte minutos posteriores a la última renovación. [Cerrar sesión](#client-account/sign-out) y [Salida rápida](#client-portal/quick-exit) también terminan la sesión. [[#server-holds #keys #failure-states]]
**Límites de tasa.** Las solicitudes de sal y los intentos de inicio de sesión están limitados a diez por dirección por hora. [[#failure-states #server-holds]]
**La derivación de inicio de sesión y la defensa contra enumeración.** El navegador ejecuta Argon2id sobre la contraseña, ciega el resultado estirado, envía el valor cegado a dos servidores de evaluación y deriva de su respuesta combinada el par de claves y el token de autenticación. La contraseña, el resultado estirado y las claves derivadas permanecen dentro de un worker y se borran al cerrar la página. El servidor responde a cada solicitud de sal con una sal real y una sal falsa determinista calculadas en paralelo, y compara el token presentado contra un hash fijo de relleno cuando no hay fila de cuenta correspondiente, de modo que el tiempo y el trabajo son constantes independientemente de si el nombre de usuario existe. La cookie de sesión es HttpOnly, SameSite=Strict, Path=/, sin atributo de dominio, y siempre Secure en producción. El servidor almacena un hash BLAKE2b del token de sesión en lugar del token mismo, y purga las filas de sesión expiradas en cada inicio de sesión exitoso. El formulario es \`AccountLoginForm.svelte\` en \`packages/client/src/lib/portal/\`. La derivación de claves se ejecuta en el worker del portal a través de \`account-crypto.ts\` y \`packages/crypto/src/client-account.ts\`. El lado del servidor es \`getSaltForUsername\` y \`login\` en \`packages/server/src/portal/account-service.ts\`, contra las tablas \`client_accounts\` y \`client_account_sessions\` de \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_client_account_sign_in_body = /** @type {(inputs: Demo_Narrative_Client_Account_Sign_In_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè sìgn-ìn fòrm àsks fòr à ùsèrnàmè ànd à pàsswòrd. Ìt àppèàrs òn à fìrst vìsìt, àftèr à rèlòàd, ànd àftèr thè ìdlè tìmèòùt òr à clòsèd tàb clèàrs thè kèys, bècàùsè thè kèys thàt òpèn thè clìènt's mèssàgès còmè fròm thè pàsswòrd ànd àrè nòt stòrèd ànywhèrè. [[#pòrtàl #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè pàsswòrd pròdùcè? ••••••••••** Thè bròwsèr dèrìvès à kèypàìr fòr rèàdìng thè clìènt's mèssàgès ànd à sèpàràtè tòkèn fòr àùthèntìcàtìng tò thè sèrvèr. Bòth còmè fròm thè pàsswòrd àlònè. Thè dèrìvèd màtèrìàl stàys òn thè dèvìcè ànd ìs clèàrèd whèn thè pàgè clòsès. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs thè dèrìvàtìòn stèps ànd thè twò sèrvèrs thàt pàrtìcìpàtè. [[#kèys #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès àn ùnknòwn ùsèrnàmè gèt bàck? ••••••••••••** Àn ùnknòwn ùsèrnàmè, à wròng pàsswòrd, ànd à nònèxìstènt àccòùnt àll rècèìvè thè sàmè fàìlùrè àftèr thè sàmè àmòùnt òf wòrk. Thè sèrvèr cànnòt bè màdè tò ànswèr dìffèrèntly fòr à nàmè thàt èxìsts ànd ònè thàt dòès nòt. [[#sèrvèr-hòlds #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw lòng dòès thè sèssìòn làst? ••••••••••** Thè sèrvèr-sìdè sèssìòn ùsès à shòrt còòkìè wìth slìdìng rènèwàl òn hùmàn àctìvìty. Thè còòkìè thàt càrrìès ìt cànnòt bè rèàd by scrìpts òn thè pàgè. Thè sèrvèr stòrès à fìngèrprìnt òf thè tòkèn, nòt thè tòkèn ìtsèlf. Àftèr fìftèèn mìnùtès wìthòùt ìnpùt fròm thè clìènt, thè ìdlè tìmèòùt clèàrs thè kèys ìn thè bròwsèr ànd rèvòkès thè sèssìòn. Clòsìng thè tàb clèàrs thè kèys bùt dòès nòt rèvòkè thè sèrvèr sèssìòn; thàt sèssìòn làpsès wìthìn twènty mìnùtès òf thè làst rènèwàl. [Sìgn òùt](#clìènt-àccòùnt/sìgn-òùt) ànd [Qùìck èxìt](#clìènt-pòrtàl/qùìck-èxìt) àlsò ènd thè sèssìòn. [[#sèrvèr-hòlds #kèys #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ràtè lìmìts. ••••** Sàlt rèqùèsts ànd sìgn-ìn àttèmpts àrè èàch càppèd àt tèn pèr àddrèss pèr hòùr. [[#fàìlùrè-stàtès #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••**Thè sìgn-ìn dèrìvàtìòn ànd ènùmèràtìòn dèfènsè. •••••••••••••••** Thè bròwsèr rùns Àrgòn2ìd òn thè pàsswòrd, blìnds thè strètchèd rèsùlt, sènds thè blìndèd vàlùè tò twò èvàlùàtìòn sèrvèrs, ànd dèrìvès fròm thèìr còmbìnèd ànswèr thè kèypàìr ànd àùthèntìcàtìòn tòkèn. Thè pàsswòrd, thè strètchèd òùtpùt, ànd thè dèrìvèd kèys stày ìnsìdè à wòrkèr ànd àrè zèròèd òn pàgè clòsè. Thè sèrvèr ànswèrs èvèry sàlt rèqùèst wìth bòth à rèàl sàlt ànd à dètèrmìnìstìc fàkè sàlt còmpùtèd ìn pàràllèl, ànd còmpàrès thè prèsèntèd tòkèn àgàìnst à fìxèd dùmmy hàsh whèn nò àccòùnt ròw màtchès, sò tìmìng ànd wòrk àrè cònstànt règàrdlèss òf whèthèr thè ùsèrnàmè èxìsts. Thè sèssìòn còòkìè ìs HttpÒnly, SàmèSìtè=Strìct, Pàth=/, càrrìès nò dòmàìn àttrìbùtè, ànd ìs àlwàys Sècùrè ìn pròdùctìòn. Thè sèrvèr stòrès à BLÀKÈ2b hàsh òf thè sèssìòn tòkèn ràthèr thàn thè tòkèn ìtsèlf, ànd pùrgès èxpìrèd sèssìòn ròws òn èàch sùccèssfùl sìgn-ìn. Thè fòrm ìs \`ÀccòùntLògìnFòrm.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/pòrtàl/\`. Kèy dèrìvàtìòn rùns ìn thè pòrtàl wòrkèr thròùgh \`àccòùnt-cryptò.ts\` ànd \`pàckàgès/cryptò/src/clìènt-àccòùnt.ts\`. Thè sèrvèr sìdè ìs \`gètSàltFòrÙsèrnàmè\` ànd \`lògìn\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/àccòùnt-sèrvìcè.ts\`, àgàìnst thè \`clìènt_àccòùnts\` ànd \`clìènt_àccòùnt_sèssìòns\` tàblès ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`. [[#kèys #sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The sign-in form asks for a username and a password. It appears on a first visit, after a reload, and after the idle timeout or a closed tab clears the keys,..." |
*
* @param {Demo_Narrative_Client_Account_Sign_In_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_account_sign_in_body = /** @type {((inputs?: Demo_Narrative_Client_Account_Sign_In_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Account_Sign_In_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_account_sign_in_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_account_sign_in_body(inputs)
	return en_demo_narrative_client_account_sign_in_body(inputs)
});