/* eslint-disable */
import * as registry from '../registry.js'
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Decryption_BodyInputs */

const en_demo_narrative_topic_decryption_body = /** @type {(inputs: Demo_Narrative_Topic_Decryption_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The title, the description, and the messages are encrypted in the browser before they reach the server. [[#encryption #keys]]
**What does each field hold?** The title is the ticket's short name, shown in the ticket list. The description is the case write-up. The messages are the entries in the ticket's [unified case thread](#ticket-detail/conversation), where volunteers and the client communicate and where internal notes are recorded. [[#client-data #privacy]]
**Where does the content come from?** When a volunteer creates a ticket, they type the title and description in the new-ticket form, and the browser encrypts both before they leave the device. When a web intake form is submitted, the submitter's browser composes the title as "Web intake" plus the client's name if the form has a name field. It generates the description from the form answers and encrypts both fields before anything leaves the device. When an inbound phone call creates a ticket, the server generates the title "Call from" plus the client's internal ID, which is not a name; real names live encrypted. When an inbound SMS creates a ticket, the server generates the title "Inbound SMS". For those telephony tickets, the server holds the generated text in memory briefly, encrypts it to a fresh ticket key, zeroes the buffer, and stores only ciphertext. This is the one path where plaintext exists server-side, and only in memory, never on disk. Messages accumulate as the client and volunteers communicate. [Creating a new ticket](#tickets/new-ticket) covers how each creation channel populates the form. [[#encryption]]
**Who holds a ticket's key?** Every ticket has its own encryption key. A user who holds a copy of that key can unlock and read the ticket in their browser. A sealed copy is stored for each permitted account, one row per ticket, account, and key generation. A ticket created from a web intake form starts with an interim copy sealed to the organization key, and the browser unseals via that copy until per-account copies are created. A telephony ticket starts with copies sealed directly to each intake-queue member who has a public key. If no queue member has a public key at the time the ticket is created, no copy exists and nobody can read the ticket. [How encryption works](#deep-dive/how-encryption-works) covers the key hierarchy that these copies derive from. [[#keys #encryption]]
**Waiting for key sharing.** After an account joins a queue, tickets that were created before that account joined show their plaintext fields.
- Queue
- Priority
- Status
- Assignee
- Timestamps
The title is not shown because no copy of those tickets' keys has been wrapped for that account yet. The server cannot share the keys because it holds only sealed copies it cannot open. Only a signed-in browser that already holds a ticket's key can make a copy for another account. A teammate who already holds those keys shares them automatically on their next sign-in. That teammate's browser wraps a copy of each missing key for the new member's account, paced against idle time so it does not interrupt their work. The sweep is resumable; closing the browser mid-way loses no progress, and the next sign-in picks up where it stopped. After the account receives a key for a ticket, the browser can decrypt and display its title. [[#failure-states #keys]]
**Message previews.** Some view modes show a preview of a ticket's latest messages on the card. The preview content arrives encrypted. The browser fetches it in batches as cards scroll into view. The browser decrypts previews with the same ticket key that unlocks the title. A message can carry its own sealed copy of a temporary key for content written before per-account copies existed. The crypto worker unseals that key and re-encrypts the message under the ticket's key in the background. Preview data registers in the same cache registry as the other decrypted content, so it is wiped with everything else. [[#encryption]]
**Session cache.** A decrypted title stays in a browser-side cache for the rest of the session, so re-rendering the list does not re-decrypt. Every cache holding decrypted content auto-registers in a single cache registry. All registered caches are wiped together when the idle timer zeroes keys and when the page closes, and nothing derived from a decrypt is ever sent back to the server. [[#client-data #privacy]]
**Decrypt cache and backfill sweep.** \`TicketDecryptCache\` in \`packages/client/src/lib/crypto/ticket-decrypt-cache.ts\` sends each decrypt to the crypto worker and caches the result, and the base class auto-registers with the cache registry in \`packages/client/src/lib/crypto/cache-registry.ts\`. Wrap rows: \`ticket_key_wraps\` in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. Intake title composition: \`packages/shared/src/schemas/intake-ticket-composition.ts\`. Telephony ticket creation: \`packages/server/src/tickets/server-ticket-create.ts\`. Re-wrap sweep: \`packages/client/src/lib/crypto/wrap-backfill-sweep.svelte.ts\` against \`packages/server/src/tickets/wrap-backfill-service.ts\`. Preview loader: \`packages/client/src/lib/tickets/preview-loader.svelte.ts\`. Preview decrypt: \`packages/client/src/lib/crypto/follow-up-decrypt-cache.ts\`. [Creating a new ticket](#tickets/new-ticket) covers which accounts receive a wrap when a ticket is first created. [[#encryption]]`)
};

const es_demo_narrative_topic_decryption_body = /** @type {(inputs: Demo_Narrative_Topic_Decryption_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El título, la descripción y los mensajes se cifran en el navegador antes de llegar al servidor. [[#encryption #keys]]
**¿Qué contiene cada campo?** El título es el nombre corto del ticket, visible en la lista de tickets. La descripción es el relato del caso. Los mensajes son las entradas del [hilo de caso unificado](#ticket-detail/conversation) del ticket, donde los voluntarios y el cliente se comunican y donde se registran las notas internas. [[#client-data #privacy]]
**¿De dónde sale el contenido?** Cuando un voluntario crea un ticket, escribe el título y la descripción en el formulario de nuevo ticket, y el navegador cifra ambos antes de que salgan del dispositivo. Cuando se envía un formulario de admisión web, el navegador del remitente compone el título como "Web intake" más el nombre del cliente si el formulario tiene un campo de nombre. Genera la descripción a partir de las respuestas del formulario y cifra ambos campos antes de que nada salga del dispositivo. Cuando una llamada entrante crea un ticket, el servidor genera el título "Call from" más el ID interno del cliente, que no es un nombre; los nombres reales viven cifrados. Cuando un SMS entrante crea un ticket, el servidor genera el título "Inbound SMS". Para esos tickets de telefonía, el servidor retiene el texto generado brevemente en memoria, lo cifra con una clave de ticket nueva, pone el búfer a cero y almacena solo texto cifrado. Esta es la única vía en la que existe texto plano en el servidor, y solo en memoria, nunca en disco. Los mensajes se acumulan a medida que el cliente y los voluntarios se comunican. [Creando un nuevo ticket](#tickets/new-ticket) explica cómo cada canal de creación rellena el formulario. [[#encryption]]
**¿Quién tiene la clave de un ticket?** Cada ticket tiene su propia clave de cifrado. Una persona que posee una copia de esa clave puede desbloquear y leer el ticket en su navegador. Se almacena una copia sellada para cada cuenta con permiso, una fila por ticket, cuenta y generación de clave. Un ticket creado desde un formulario de admisión web empieza con una copia provisional sellada con la clave de la organización, y el navegador la abre con esa copia hasta que se crean las copias por cuenta. Un ticket de telefonía empieza con copias selladas directamente para cada miembro de la cola de admisión que tenga clave pública. Si ningún miembro de la cola tiene clave pública en el momento de crear el ticket, no existe ninguna copia y nadie puede leer el ticket. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) explica la jerarquía de claves de la que derivan estas copias. [[#keys #encryption]]
**En espera de compartición de claves.** Después de que una cuenta se une a una cola, los tickets creados antes de esa incorporación muestran sus campos en texto plano.
- Cola
- Prioridad
- Estado
- Persona asignada
- Marcas de tiempo
El título no se muestra porque todavía no existe una copia de las claves de esos tickets envuelta para esa cuenta. El servidor no puede compartir las claves porque solo guarda copias selladas que no puede abrir. Solo un navegador con sesión iniciada que ya posea la clave de un ticket puede crear una copia para otra cuenta. Una persona del equipo que ya tenga esas claves las comparte automáticamente en su siguiente inicio de sesión. El navegador de esa persona envuelve una copia de cada clave faltante para la cuenta del nuevo miembro, a ritmo de los momentos de inactividad para no interrumpir su trabajo. El barrido es reanudable; cerrar el navegador a mitad no pierde progreso, y el siguiente inicio de sesión continúa donde se detuvo. Cuando la cuenta recibe la clave de un ticket, el navegador puede descifrar y mostrar su título. [[#failure-states #keys]]
**Previsualizaciones de mensajes.** Algunos modos de vista muestran una previsualización de los últimos mensajes de un ticket en la tarjeta. El contenido de la previsualización llega cifrado. El navegador lo obtiene en lotes a medida que las tarjetas aparecen en pantalla. El navegador descifra las previsualizaciones con la misma clave del ticket que desbloquea el título. Un mensaje puede llevar su propia copia sellada de una clave temporal para contenido escrito antes de que existieran las copias por cuenta. El worker criptográfico abre esa clave y vuelve a cifrar el mensaje con la clave del ticket en segundo plano. Los datos de previsualización se registran en el mismo registro de cachés que el resto del contenido descifrado, así que se borran con todo lo demás. [[#encryption]]
**Caché de sesión.** Un título descifrado permanece en una caché del navegador durante el resto de la sesión, así que volver a dibujar la lista no repite el descifrado. Toda caché que contenga contenido descifrado se registra automáticamente en un registro único de cachés. Todas las cachés registradas se borran a la vez cuando el temporizador de inactividad pone las claves a cero y cuando se cierra la página, y nada derivado de un descifrado se devuelve al servidor. [[#client-data #privacy]]
**Caché de descifrado y barrido de reenvoltura.** \`TicketDecryptCache\`, en \`packages/client/src/lib/crypto/ticket-decrypt-cache.ts\`, envía cada descifrado al worker criptográfico y almacena el resultado, y la clase base se registra automáticamente en el registro de cachés de \`packages/client/src/lib/crypto/cache-registry.ts\`. Filas de envoltorio: \`ticket_key_wraps\`, en \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. Composición del título de admisión: \`packages/shared/src/schemas/intake-ticket-composition.ts\`. Creación de tickets de telefonía: \`packages/server/src/tickets/server-ticket-create.ts\`. Barrido de reenvoltura: \`packages/client/src/lib/crypto/wrap-backfill-sweep.svelte.ts\` contra \`packages/server/src/tickets/wrap-backfill-service.ts\`. Cargador de previsualizaciones: \`packages/client/src/lib/tickets/preview-loader.svelte.ts\`. Descifrado de previsualizaciones: \`packages/client/src/lib/crypto/follow-up-decrypt-cache.ts\`. [Creando un nuevo ticket](#tickets/new-ticket) explica qué cuentas reciben un envoltorio cuando el ticket se crea por primera vez. [[#encryption]]`)
};

const en_xa2_demo_narrative_topic_decryption_body = /** @type {(inputs: Demo_Narrative_Topic_Decryption_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè tìtlè, thè dèscrìptìòn, ànd thè mèssàgès àrè èncryptèd ìn thè bròwsèr bèfòrè thèy rèàch thè sèrvèr. [[#èncryptìòn #kèys]]
 ••••••••••••••••••••••••••••••••••••••**Whàt dòès èàch fìèld hòld? ••••••••** Thè tìtlè ìs thè tìckèt's shòrt nàmè, shòwn ìn thè tìckèt lìst. Thè dèscrìptìòn ìs thè càsè wrìtè-ùp. Thè mèssàgès àrè thè èntrìès ìn thè tìckèt's [ùnìfìèd càsè thrèàd](#tìckèt-dètàìl/cònvèrsàtìòn), whèrè vòlùntèèrs ànd thè clìènt còmmùnìcàtè ànd whèrè ìntèrnàl nòtès àrè rècòrdèd. [[#clìènt-dàtà #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèrè dòès thè còntènt còmè fròm? ••••••••••** Whèn à vòlùntèèr crèàtès à tìckèt, thèy typè thè tìtlè ànd dèscrìptìòn ìn thè nèw-tìckèt fòrm, ànd thè bròwsèr èncrypts bòth bèfòrè thèy lèàvè thè dèvìcè. Whèn à wèb ìntàkè fòrm ìs sùbmìttèd, thè sùbmìttèr's bròwsèr còmpòsès thè tìtlè às "Wèb ìntàkè" plùs thè clìènt's nàmè ìf thè fòrm hàs à nàmè fìèld. Ìt gènèràtès thè dèscrìptìòn fròm thè fòrm ànswèrs ànd èncrypts bòth fìèlds bèfòrè ànythìng lèàvès thè dèvìcè. Whèn àn ìnbòùnd phònè càll crèàtès à tìckèt, thè sèrvèr gènèràtès thè tìtlè "Càll fròm" plùs thè clìènt's ìntèrnàl ÌD, whìch ìs nòt à nàmè; rèàl nàmès lìvè èncryptèd. Whèn àn ìnbòùnd SMS crèàtès à tìckèt, thè sèrvèr gènèràtès thè tìtlè "Ìnbòùnd SMS". Fòr thòsè tèlèphòny tìckèts, thè sèrvèr hòlds thè gènèràtèd tèxt ìn mèmòry brìèfly, èncrypts ìt tò à frèsh tìckèt kèy, zèròès thè bùffèr, ànd stòrès ònly cìphèrtèxt. Thìs ìs thè ònè pàth whèrè plàìntèxt èxìsts sèrvèr-sìdè, ànd ònly ìn mèmòry, nèvèr òn dìsk. Mèssàgès àccùmùlàtè às thè clìènt ànd vòlùntèèrs còmmùnìcàtè. [Crèàtìng à nèw tìckèt](#tìckèts/nèw-tìckèt) còvèrs hòw èàch crèàtìòn chànnèl pòpùlàtès thè fòrm. [[#èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò hòlds à tìckèt's kèy? ••••••••** Èvèry tìckèt hàs ìts òwn èncryptìòn kèy. À ùsèr whò hòlds à còpy òf thàt kèy càn ùnlòck ànd rèàd thè tìckèt ìn thèìr bròwsèr. À sèàlèd còpy ìs stòrèd fòr èàch pèrmìttèd àccòùnt, ònè ròw pèr tìckèt, àccòùnt, ànd kèy gènèràtìòn. À tìckèt crèàtèd fròm à wèb ìntàkè fòrm stàrts wìth àn ìntèrìm còpy sèàlèd tò thè òrgànìzàtìòn kèy, ànd thè bròwsèr ùnsèàls vìà thàt còpy ùntìl pèr-àccòùnt còpìès àrè crèàtèd. À tèlèphòny tìckèt stàrts wìth còpìès sèàlèd dìrèctly tò èàch ìntàkè-qùèùè mèmbèr whò hàs à pùblìc kèy. Ìf nò qùèùè mèmbèr hàs à pùblìc kèy àt thè tìmè thè tìckèt ìs crèàtèd, nò còpy èxìsts ànd nòbòdy càn rèàd thè tìckèt. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè kèy hìèràrchy thàt thèsè còpìès dèrìvè fròm. [[#kèys #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Wàìtìng fòr kèy shàrìng. ••••••••** Àftèr àn àccòùnt jòìns à qùèùè, tìckèts thàt wèrè crèàtèd bèfòrè thàt àccòùnt jòìnèd shòw thèìr plàìntèxt fìèlds.
- Qùèùè
- Prìòrìty
- Stàtùs
- Àssìgnèè
- Tìmèstàmps
Thè tìtlè ìs nòt shòwn bècàùsè nò còpy òf thòsè tìckèts' kèys hàs bèèn wràppèd fòr thàt àccòùnt yèt. Thè sèrvèr cànnòt shàrè thè kèys bècàùsè ìt hòlds ònly sèàlèd còpìès ìt cànnòt òpèn. Ònly à sìgnèd-ìn bròwsèr thàt àlrèàdy hòlds à tìckèt's kèy càn màkè à còpy fòr ànòthèr àccòùnt. À tèàmmàtè whò àlrèàdy hòlds thòsè kèys shàrès thèm àùtòmàtìcàlly òn thèìr nèxt sìgn-ìn. Thàt tèàmmàtè's bròwsèr wràps à còpy òf èàch mìssìng kèy fòr thè nèw mèmbèr's àccòùnt, pàcèd àgàìnst ìdlè tìmè sò ìt dòès nòt ìntèrrùpt thèìr wòrk. Thè swèèp ìs rèsùmàblè; clòsìng thè bròwsèr mìd-wày lòsès nò prògrèss, ànd thè nèxt sìgn-ìn pìcks ùp whèrè ìt stòppèd. Àftèr thè àccòùnt rècèìvès à kèy fòr à tìckèt, thè bròwsèr càn dècrypt ànd dìsplày ìts tìtlè. [[#fàìlùrè-stàtès #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Mèssàgè prèvìèws. ••••••** Sòmè vìèw mòdès shòw à prèvìèw òf à tìckèt's làtèst mèssàgès òn thè càrd. Thè prèvìèw còntènt àrrìvès èncryptèd. Thè bròwsèr fètchès ìt ìn bàtchès às càrds scròll ìntò vìèw. Thè bròwsèr dècrypts prèvìèws wìth thè sàmè tìckèt kèy thàt ùnlòcks thè tìtlè. À mèssàgè càn càrry ìts òwn sèàlèd còpy òf à tèmpòràry kèy fòr còntènt wrìttèn bèfòrè pèr-àccòùnt còpìès èxìstèd. Thè cryptò wòrkèr ùnsèàls thàt kèy ànd rè-èncrypts thè mèssàgè ùndèr thè tìckèt's kèy ìn thè bàckgròùnd. Prèvìèw dàtà règìstèrs ìn thè sàmè càchè règìstry às thè òthèr dècryptèd còntènt, sò ìt ìs wìpèd wìth èvèrythìng èlsè. [[#èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèssìòn càchè. •••••** À dècryptèd tìtlè stàys ìn à bròwsèr-sìdè càchè fòr thè rèst òf thè sèssìòn, sò rè-rèndèrìng thè lìst dòès nòt rè-dècrypt. Èvèry càchè hòldìng dècryptèd còntènt àùtò-règìstèrs ìn à sìnglè càchè règìstry. Àll règìstèrèd càchès àrè wìpèd tògèthèr whèn thè ìdlè tìmèr zèròès kèys ànd whèn thè pàgè clòsès, ànd nòthìng dèrìvèd fròm à dècrypt ìs èvèr sènt bàck tò thè sèrvèr. [[#clìènt-dàtà #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dècrypt càchè ànd bàckfìll swèèp. ••••••••••** \`TìckètDècryptCàchè\` ìn \`pàckàgès/clìènt/src/lìb/cryptò/tìckèt-dècrypt-càchè.ts\` sènds èàch dècrypt tò thè cryptò wòrkèr ànd càchès thè rèsùlt, ànd thè bàsè clàss àùtò-règìstèrs wìth thè càchè règìstry ìn \`pàckàgès/clìènt/src/lìb/cryptò/càchè-règìstry.ts\`. Wràp ròws: \`tìckèt_kèy_wràps\` ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`. Ìntàkè tìtlè còmpòsìtìòn: \`pàckàgès/shàrèd/src/schèmàs/ìntàkè-tìckèt-còmpòsìtìòn.ts\`. Tèlèphòny tìckèt crèàtìòn: \`pàckàgès/sèrvèr/src/tìckèts/sèrvèr-tìckèt-crèàtè.ts\`. Rè-wràp swèèp: \`pàckàgès/clìènt/src/lìb/cryptò/wràp-bàckfìll-swèèp.svèltè.ts\` àgàìnst \`pàckàgès/sèrvèr/src/tìckèts/wràp-bàckfìll-sèrvìcè.ts\`. Prèvìèw lòàdèr: \`pàckàgès/clìènt/src/lìb/tìckèts/prèvìèw-lòàdèr.svèltè.ts\`. Prèvìèw dècrypt: \`pàckàgès/clìènt/src/lìb/cryptò/fòllòw-ùp-dècrypt-càchè.ts\`. [Crèàtìng à nèw tìckèt](#tìckèts/nèw-tìckèt) còvèrs whìch àccòùnts rècèìvè à wràp whèn à tìckèt ìs fìrst crèàtèd. [[#èncryptìòn]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The title, the description, and the messages are encrypted in the browser before they reach the server. [[#encryption #keys]] **What does each field hold?** ..." |
*
* @param {Demo_Narrative_Topic_Decryption_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_decryption_body = /** @type {((inputs?: Demo_Narrative_Topic_Decryption_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Decryption_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_decryption_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_decryption_body(inputs)
	return en_demo_narrative_topic_decryption_body(inputs)
});