/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Audit_Log_BodyInputs */

const en_demo_narrative_admin_audit_log_body = /** @type {(inputs: Demo_Narrative_Admin_Audit_Log_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The audit log is the organization's record of who did what. It covers ticket lifecycle, client records, queues, roles and permissions, intake forms, portal channels, key operations and the voicemail quarantine. Entries are only ever added. Nothing in the log can be edited or deleted, and the service has no update path, no delete path and no route that exposes one. [[#permissions #server-holds]]
**Which permission opens what.** The logs page is available to accounts holding either the view reports permission or the view audit log permission. [The permission system](#deep-dive/the-permission-system) covers how each is granted. [[#permissions]]
**What a row holds.** A row holds the event type, the account that acted, the ticket it acted on, a metadata object and a timestamp. All five are plaintext. The service writes no names, numbers or message content into any of them. The actor's name beside a row is organization-key ciphertext the browser opens. An action taken by the system itself is recorded against a fixed system actor rather than a person. [Recent activity](#dashboard/activity) covers the same row as the dashboard feed reads it. [[#privacy #encryption]]
**What the whole log gives away.** Read together, the rows are a timeline of the organization's operations. They show when accounts were active, how often cases are opened and closed, when permissions changed and when keys were rotated. Nothing in a row identifies a client or repeats what was said. [The trust boundary](#deep-dive/the-trust-boundary) covers the plaintext columns elsewhere in the schema. [[#metadata #server-holds]]
**Why the log outlives the cases.** The retention purge deletes tickets, their threads and their call records. It leaves the audit log alone, so the record of an action survives the case it was taken on. An audit row about a purged ticket still stores that ticket's ID. The ticket that ID names no longer exists, so there is nothing left to open from the row. [Data retention](#deep-dive/data-retention) covers what the purge takes. [[#retention]]
**The query and its filters.** \`query\` in \`packages/server/src/tickets/audit.ts\` pages fifty rows at a time, newest first. Filters for event type, actor, ticket and date range are applied in SQL. The same predicates are built onto the count. Audit writes are best-effort. A failed audit insert is swallowed so that it never blocks the operation that triggered it. An audit gap is possible where a database write failed. [[#failure-states]]`)
};

const es_demo_narrative_admin_audit_log_body = /** @type {(inputs: Demo_Narrative_Admin_Audit_Log_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El registro de auditoría es la constancia que tiene la organización de quién hizo qué. Abarca el ciclo de vida de los tickets, los registros de clientes, las colas, los roles y permisos, los formularios de admisión, los canales del portal, las operaciones con claves y la cuarentena de mensajes de voz. Las entradas solo se añaden. Nada del registro se puede editar ni borrar, y el servicio no tiene ninguna ruta de actualización, ninguna de borrado ni ninguna que las exponga. [[#permissions #server-holds]]
**Qué abre cada permiso.** La página de registros está disponible para las cuentas que tienen el permiso para ver reportes o el permiso para leer el registro de auditoría. [El sistema de permisos](#deep-dive/the-permission-system) explica cómo se concede cada uno. [[#permissions]]
**Qué guarda una fila.** Una fila guarda el tipo de evento, la cuenta que actuó, el ticket sobre el que actuó, un objeto de metadatos y una marca de tiempo. Los cinco están en texto plano. El servicio no escribe en ninguno de ellos nombres, números ni contenido de mensajes. El nombre de quien actuó que acompaña a la fila es texto cifrado con la clave de la organización que abre el navegador. Una acción del propio sistema queda registrada a nombre de un actor de sistema fijo y no de una persona. [Actividad reciente](#dashboard/activity) trata esa misma fila tal como la lee el resumen. [[#privacy #encryption]]
**Lo que revela el registro completo.** Leídas en conjunto, las filas son una cronología de la operación de la organización. Muestran cuándo estuvieron activas las cuentas, con qué frecuencia se abren y se cierran casos, cuándo cambiaron los permisos y cuándo se rotaron las claves. Nada de una fila identifica a un cliente ni repite lo que se dijo. [La frontera de confianza](#deep-dive/the-trust-boundary) trata las columnas en texto plano del resto del esquema. [[#metadata #server-holds]]
**Por qué el registro sobrevive a los casos.** La purga de retención elimina los tickets, sus hilos y sus registros de llamadas. Deja intacto el registro de auditoría, de modo que la constancia de una acción sobrevive al caso sobre el que se tomó. Una fila de auditoría sobre un ticket purgado sigue guardando el ID de ese ticket. El ticket que nombra ese ID ya no existe, así que ya no queda nada que abrir desde la fila. [Retención de datos](#deep-dive/data-retention) trata lo que se lleva la purga. [[#retention]]
**La consulta y sus filtros.** \`query\`, en \`packages/server/src/tickets/audit.ts\`, pagina cincuenta filas cada vez, de la más reciente a la más antigua. Los filtros de tipo de evento, actor, ticket y rango de fechas se aplican en SQL. Los mismos predicados se ponen sobre el recuento. Las escrituras de auditoría son de mejor esfuerzo. Una inserción de auditoría fallida se descarta para que nunca bloquee la operación que la provocó. Puede haber un hueco en el registro allí donde falló una escritura en la base de datos. [[#failure-states]]`)
};

const en_xa2_demo_narrative_admin_audit_log_body = /** @type {(inputs: Demo_Narrative_Admin_Audit_Log_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè àùdìt lòg ìs thè òrgànìzàtìòn's rècòrd òf whò dìd whàt. Ìt còvèrs tìckèt lìfècyclè, clìènt rècòrds, qùèùès, ròlès ànd pèrmìssìòns, ìntàkè fòrms, pòrtàl chànnèls, kèy òpèràtìòns ànd thè vòìcèmàìl qùàràntìnè. Èntrìès àrè ònly èvèr àddèd. Nòthìng ìn thè lòg càn bè èdìtèd òr dèlètèd, ànd thè sèrvìcè hàs nò ùpdàtè pàth, nò dèlètè pàth ànd nò ròùtè thàt èxpòsès ònè. [[#pèrmìssìòns #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whìch pèrmìssìòn òpèns whàt. •••••••••** Thè lògs pàgè ìs àvàìlàblè tò àccòùnts hòldìng èìthèr thè vìèw rèpòrts pèrmìssìòn òr thè vìèw àùdìt lòg pèrmìssìòn. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw èàch ìs gràntèd. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt à ròw hòlds. ••••••** À ròw hòlds thè èvènt typè, thè àccòùnt thàt àctèd, thè tìckèt ìt àctèd òn, à mètàdàtà òbjèct ànd à tìmèstàmp. Àll fìvè àrè plàìntèxt. Thè sèrvìcè wrìtès nò nàmès, nùmbèrs òr mèssàgè còntènt ìntò àny òf thèm. Thè àctòr's nàmè bèsìdè à ròw ìs òrgànìzàtìòn-kèy cìphèrtèxt thè bròwsèr òpèns. Àn àctìòn tàkèn by thè systèm ìtsèlf ìs rècòrdèd àgàìnst à fìxèd systèm àctòr ràthèr thàn à pèrsòn. [Rècènt àctìvìty](#dàshbòàrd/àctìvìty) còvèrs thè sàmè ròw às thè dàshbòàrd fèèd rèàds ìt. [[#prìvàcy #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè whòlè lòg gìvès àwày. •••••••••** Rèàd tògèthèr, thè ròws àrè à tìmèlìnè òf thè òrgànìzàtìòn's òpèràtìòns. Thèy shòw whèn àccòùnts wèrè àctìvè, hòw òftèn càsès àrè òpènèd ànd clòsèd, whèn pèrmìssìòns chàngèd ànd whèn kèys wèrè ròtàtèd. Nòthìng ìn à ròw ìdèntìfìès à clìènt òr rèpèàts whàt wàs sàìd. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè plàìntèxt còlùmns èlsèwhèrè ìn thè schèmà. [[#mètàdàtà #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why thè lòg òùtlìvès thè càsès. ••••••••••** Thè rètèntìòn pùrgè dèlètès tìckèts, thèìr thrèàds ànd thèìr càll rècòrds. Ìt lèàvès thè àùdìt lòg àlònè, sò thè rècòrd òf àn àctìòn sùrvìvès thè càsè ìt wàs tàkèn òn. Àn àùdìt ròw àbòùt à pùrgèd tìckèt stìll stòrès thàt tìckèt's ÌD. Thè tìckèt thàt ÌD nàmès nò lòngèr èxìsts, sò thèrè ìs nòthìng lèft tò òpèn fròm thè ròw. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs whàt thè pùrgè tàkès. [[#rètèntìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè qùèry ànd ìts fìltèrs. ••••••••** \`qùèry\` ìn \`pàckàgès/sèrvèr/src/tìckèts/àùdìt.ts\` pàgès fìfty ròws àt à tìmè, nèwèst fìrst. Fìltèrs fòr èvènt typè, àctòr, tìckèt ànd dàtè ràngè àrè àpplìèd ìn SQL. Thè sàmè prèdìcàtès àrè bùìlt òntò thè còùnt. Àùdìt wrìtès àrè bèst-èffòrt. À fàìlèd àùdìt ìnsèrt ìs swàllòwèd sò thàt ìt nèvèr blòcks thè òpèràtìòn thàt trìggèrèd ìt. Àn àùdìt gàp ìs pòssìblè whèrè à dàtàbàsè wrìtè fàìlèd. [[#fàìlùrè-stàtès]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The audit log is the organization's record of who did what. It covers ticket lifecycle, client records, queues, roles and permissions, intake forms, portal c..." |
*
* @param {Demo_Narrative_Admin_Audit_Log_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_audit_log_body = /** @type {((inputs?: Demo_Narrative_Admin_Audit_Log_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Audit_Log_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_audit_log_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_audit_log_body(inputs)
	return en_demo_narrative_admin_audit_log_body(inputs)
});