/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Fund_Records_BodyInputs */

const en_demo_narrative_deepdive_fund_records_body = /** @type {(inputs: Demo_Narrative_Deepdive_Fund_Records_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Every value that describes a fund or a ledger entry by name, amount, currency, type, or author is organization-key ciphertext. The server stores the sealed bytes and cannot read them. [How encryption works](#deep-dive/how-encryption-works) covers the organization key itself. [[#server-holds #encryption]]
**What plaintext does each fund row hold?** The fund table has two ciphertext columns (the fund payload and the sealed balance) alongside the row id, an active flag, a sort position, the balance version counter, a key generation marker, a creation timestamp, and a modification timestamp, all in plaintext. The balance version increments with each balance write, so it reveals how many entries a fund has received. The active flag shows whether the fund is in use. The creation timestamp records when the fund was created and never changes. The modification timestamp is stamped only by fund metadata edits (renaming, changing the currency, deactivating, or reactivating). Balance writes (disbursements, adjustments, revisions, and balance resets) do not touch the modification timestamp. The browser uses the modification timestamp to detect when a fund's payload has changed and must be decrypted again. [[#server-holds #metadata]]
**What plaintext does each ledger row hold?** Each row has one ciphertext column alongside a client-minted row id, the key generation, and a calendar date at day granularity, all in plaintext. The date is the day the entry was recorded. No fund reference, no user reference, no amount, and no entry type appear in any plaintext column. The fund, the amount, the entry type, the exact timestamp, and the person who recorded the entry are inside the encrypted payload. [[#server-holds #encryption #metadata]]
**What does the queue fund mapping reveal?** Each queue carries a nullable ciphertext column for its fund reference, sealed with the organization key. The server cannot read which fund a queue draws on. Whether the column is null or populated is visible, so the server can tell which queues have a fund mapped and which do not. [[#server-holds #encryption]]
**What can a database copy pair?** A copy reveals how many funds exist, how many ledger entries exist, and each entry's calendar date. It shows the fund notification toggle and per-fund metadata (active flag, sort position, creation timestamp, modification timestamp, balance version counter). The creation timestamp shows when each fund was created. The modification timestamp shows when each fund's metadata was last edited, but cannot pair a disbursement with the case note written in the same transaction, because balance writes do not stamp it. A copy cannot pair a ledger entry with the fund it belongs to, because the fund reference is inside the ciphertext. It cannot pair a ledger entry with a case, because the ledger row carries no ticket column. The only link between a disbursement and its case is inside the case note's encrypted content, sealed with the ticket key. A copy that has the followups table shows which cases carry internal notes and on which days. When a single note and a single ledger entry share the same calendar date, the two can be matched. When several notes or several entries fall on the same day, the date alone does not distinguish which note belongs to which entry. [[#server-holds #privacy #encryption]]
**What does the notification toggle reveal?** The toggle is a plaintext boolean on the organization's configuration row. It tells the server whether the organization has fund-entry notifications turned on. The notification itself is a ticketless event that names no case and carries no financial content. [[#server-holds #metadata]]
**What survives a case purge?** Purging a case through the retention policy or by hand deletes the case's rows, and any disbursement note in its thread. The ledger entry that recorded the disbursement is not deleted, because it carries no reference to the case. The fund's balance stays correct after the purge. An orphaned ledger entry reads as a disbursement whose case has been removed, which is the intended behavior. [Data retention](#deep-dive/data-retention) covers the purge policy. [[#retention #encryption #privacy]]
**What integrity does the server check?** The server enforces the balance version guard (a write is rejected when the version has moved since the browser last read it) and the permission gates on each procedure. The server cannot verify amounts, entry types, or fund references, because those values are inside sealed payloads the server cannot open. Accuracy depends on what the browser submits. The [fund ledger](#admin-org/fund-ledger) page's recompute action is the only check that the sealed balance matches the sum of the ledger. [[#encryption #server-holds #permissions]]
**The fund service transaction boundaries.** \`packages/server/src/funds/fund-service.ts\` runs every balance write and ledger insert inside one database transaction. A disbursement writes the ledger entry, the resealed balance, and the case note in a single commit. If any step fails, everything rolls back. The notification to fund managers fires after commit, outside the transaction, and is best-effort. [[#server-holds]]`)
};

const es_demo_narrative_deepdive_fund_records_body = /** @type {(inputs: Demo_Narrative_Deepdive_Fund_Records_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Todo valor que describe un fondo o una entrada del libro mayor por nombre, monto, moneda, tipo o autor es texto cifrado con la clave de organización. El servidor almacena los bytes sellados y no puede leerlos. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) explica la clave de organización. [[#server-holds #encryption]]
**¿Qué texto plano tiene cada fila de fondo?** La tabla de fondos tiene dos columnas cifradas (la carga del fondo y el saldo sellado) junto al id de fila, una bandera de activo, una posición de orden, el contador de versión del saldo, un marcador de generación de clave, una marca de tiempo de creación y una marca de tiempo de modificación, todo en texto plano. La versión del saldo se incrementa con cada escritura de saldo, así que revela cuántas entradas ha recibido un fondo. La bandera de activo muestra si el fondo está en uso. La marca de tiempo de creación registra cuándo se creó el fondo y no cambia. La marca de tiempo de modificación se actualiza solo con ediciones de metadatos del fondo (cambio de nombre, cambio de moneda, desactivación o reactivación). Las escrituras de saldo (desembolsos, ajustes, revisiones y restablecimientos de saldo) no modifican la marca de tiempo de modificación. El navegador usa la marca de tiempo de modificación para detectar cuándo la carga de un fondo ha cambiado y debe descifrarse de nuevo. [[#server-holds #metadata]]
**¿Qué texto plano tiene cada fila del libro mayor?** Cada fila tiene una columna cifrada junto a un id generado por el cliente, la generación de clave y una fecha calendario con granularidad de día, todo en texto plano. La fecha es el día en que se registró la entrada. Ninguna referencia a fondo, referencia a persona usuaria, monto ni tipo de entrada aparece en columna alguna de texto plano. El fondo, el monto, el tipo de entrada, la marca de tiempo exacta y la persona que registró la entrada están dentro de la carga cifrada. [[#server-holds #encryption #metadata]]
**¿Qué revela el mapeo de fondo en la cola?** Cada cola lleva una columna cifrada que puede ser nula para su referencia de fondo, sellada con la clave de organización. El servidor no puede leer qué fondo utiliza una cola. Si la columna es nula o tiene datos es visible, así que el servidor puede distinguir qué colas tienen un fondo asignado y cuáles no. [[#server-holds #encryption]]
**¿Qué puede emparejar una copia de la base de datos?** Una copia revela cuántos fondos existen, cuántas entradas del libro mayor existen y la fecha calendario de cada entrada. Muestra el interruptor de notificaciones de fondo y metadatos por fondo (bandera de activo, posición de orden, marca de tiempo de creación, marca de tiempo de modificación, contador de versión del saldo). La marca de tiempo de creación muestra cuándo se creó cada fondo. La marca de tiempo de modificación muestra cuándo se editaron por última vez los metadatos de cada fondo, pero no puede emparejar un desembolso con la nota de caso escrita en la misma transacción, porque las escrituras de saldo no la actualizan. Una copia no puede emparejar una entrada del libro mayor con el fondo al que pertenece, porque la referencia al fondo está dentro del texto cifrado. No puede emparejar una entrada del libro mayor con un caso, porque la fila del libro mayor no lleva columna de ticket. El único vínculo entre un desembolso y su caso está dentro del contenido cifrado de la nota de caso, sellado con la clave del ticket. Una copia que incluya la tabla de seguimientos muestra qué casos llevan notas internas y en qué días. Cuando una sola nota y una sola entrada del libro mayor comparten la misma fecha calendario, las dos pueden emparejarse. Cuando varias notas o varias entradas caen en el mismo día, la fecha por sí sola no distingue qué nota corresponde a qué entrada. [[#server-holds #privacy #encryption]]
**¿Qué revela el interruptor de notificaciones?** El interruptor es un booleano en texto plano en la fila de configuración de la organización. Indica al servidor si la organización tiene activadas las notificaciones de entradas de fondos. La notificación misma es un evento sin ticket que no nombra ningún caso y no lleva contenido financiero. [[#server-holds #metadata]]
**¿Qué sobrevive a la purga de un caso?** Purgar un caso mediante la política de retención o manualmente elimina las filas del caso, y cualquier nota de desembolso en su hilo. La entrada del libro mayor que registró el desembolso no se elimina, porque no lleva referencia al caso. El saldo del fondo permanece correcto después de la purga. Una entrada huérfana del libro mayor se lee como un desembolso cuyo caso fue eliminado, que es el comportamiento previsto. [Retención de datos](#deep-dive/data-retention) trata la política de purga. [[#retention #encryption #privacy]]
**¿Qué integridad verifica el servidor?** El servidor aplica la guarda de versión del saldo (una escritura se rechaza cuando la versión cambió desde la última lectura del navegador) y las puertas de permisos en cada procedimiento. El servidor no puede verificar montos, tipos de entrada ni referencias a fondos, porque esos valores están dentro de cargas selladas que el servidor no puede abrir. La exactitud depende de lo que el navegador envía. La acción de recálculo en la página del [libro mayor de fondos](#admin-org/fund-ledger) es la única verificación de que el saldo sellado coincide con la suma del libro mayor. [[#encryption #server-holds #permissions]]
**Los límites transaccionales del servicio de fondos.** \`packages/server/src/funds/fund-service.ts\` ejecuta cada escritura de saldo e inserción del libro mayor dentro de una única transacción de base de datos. Un desembolso escribe la entrada del libro mayor, el saldo resellado y la nota de caso en un solo commit. Si algún paso falla, todo se revierte. La notificación a administradores de fondos se envía después del commit, fuera de la transacción, con entrega de mejor esfuerzo. [[#server-holds]]`)
};

const en_xa2_demo_narrative_deepdive_fund_records_body = /** @type {(inputs: Demo_Narrative_Deepdive_Fund_Records_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èvèry vàlùè thàt dèscrìbès à fùnd òr à lèdgèr èntry by nàmè, àmòùnt, cùrrèncy, typè, òr àùthòr ìs òrgànìzàtìòn-kèy cìphèrtèxt. Thè sèrvèr stòrès thè sèàlèd bytès ànd cànnòt rèàd thèm. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè òrgànìzàtìòn kèy ìtsèlf. [[#sèrvèr-hòlds #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt plàìntèxt dòès èàch fùnd ròw hòld? ••••••••••••** Thè fùnd tàblè hàs twò cìphèrtèxt còlùmns (thè fùnd pàylòàd ànd thè sèàlèd bàlàncè) àlòngsìdè thè ròw ìd, àn àctìvè flàg, à sòrt pòsìtìòn, thè bàlàncè vèrsìòn còùntèr, à kèy gènèràtìòn màrkèr, à crèàtìòn tìmèstàmp, ànd à mòdìfìcàtìòn tìmèstàmp, àll ìn plàìntèxt. Thè bàlàncè vèrsìòn ìncrèmènts wìth èàch bàlàncè wrìtè, sò ìt rèvèàls hòw màny èntrìès à fùnd hàs rècèìvèd. Thè àctìvè flàg shòws whèthèr thè fùnd ìs ìn ùsè. Thè crèàtìòn tìmèstàmp rècòrds whèn thè fùnd wàs crèàtèd ànd nèvèr chàngès. Thè mòdìfìcàtìòn tìmèstàmp ìs stàmpèd ònly by fùnd mètàdàtà èdìts (rènàmìng, chàngìng thè cùrrèncy, dèàctìvàtìng, òr rèàctìvàtìng). Bàlàncè wrìtès (dìsbùrsèmènts, àdjùstmènts, rèvìsìòns, ànd bàlàncè rèsèts) dò nòt tòùch thè mòdìfìcàtìòn tìmèstàmp. Thè bròwsèr ùsès thè mòdìfìcàtìòn tìmèstàmp tò dètèct whèn à fùnd's pàylòàd hàs chàngèd ànd mùst bè dècryptèd àgàìn. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt plàìntèxt dòès èàch lèdgèr ròw hòld? •••••••••••••** Èàch ròw hàs ònè cìphèrtèxt còlùmn àlòngsìdè à clìènt-mìntèd ròw ìd, thè kèy gènèràtìòn, ànd à càlèndàr dàtè àt dày grànùlàrìty, àll ìn plàìntèxt. Thè dàtè ìs thè dày thè èntry wàs rècòrdèd. Nò fùnd rèfèrèncè, nò ùsèr rèfèrèncè, nò àmòùnt, ànd nò èntry typè àppèàr ìn àny plàìntèxt còlùmn. Thè fùnd, thè àmòùnt, thè èntry typè, thè èxàct tìmèstàmp, ànd thè pèrsòn whò rècòrdèd thè èntry àrè ìnsìdè thè èncryptèd pàylòàd. [[#sèrvèr-hòlds #èncryptìòn #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè qùèùè fùnd màppìng rèvèàl? ••••••••••••** Èàch qùèùè càrrìès à nùllàblè cìphèrtèxt còlùmn fòr ìts fùnd rèfèrèncè, sèàlèd wìth thè òrgànìzàtìòn kèy. Thè sèrvèr cànnòt rèàd whìch fùnd à qùèùè dràws òn. Whèthèr thè còlùmn ìs nùll òr pòpùlàtèd ìs vìsìblè, sò thè sèrvèr càn tèll whìch qùèùès hàvè à fùnd màppèd ànd whìch dò nòt. [[#sèrvèr-hòlds #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt càn à dàtàbàsè còpy pàìr? •••••••••** À còpy rèvèàls hòw màny fùnds èxìst, hòw màny lèdgèr èntrìès èxìst, ànd èàch èntry's càlèndàr dàtè. Ìt shòws thè fùnd nòtìfìcàtìòn tògglè ànd pèr-fùnd mètàdàtà (àctìvè flàg, sòrt pòsìtìòn, crèàtìòn tìmèstàmp, mòdìfìcàtìòn tìmèstàmp, bàlàncè vèrsìòn còùntèr). Thè crèàtìòn tìmèstàmp shòws whèn èàch fùnd wàs crèàtèd. Thè mòdìfìcàtìòn tìmèstàmp shòws whèn èàch fùnd's mètàdàtà wàs làst èdìtèd, bùt cànnòt pàìr à dìsbùrsèmènt wìth thè càsè nòtè wrìttèn ìn thè sàmè trànsàctìòn, bècàùsè bàlàncè wrìtès dò nòt stàmp ìt. À còpy cànnòt pàìr à lèdgèr èntry wìth thè fùnd ìt bèlòngs tò, bècàùsè thè fùnd rèfèrèncè ìs ìnsìdè thè cìphèrtèxt. Ìt cànnòt pàìr à lèdgèr èntry wìth à càsè, bècàùsè thè lèdgèr ròw càrrìès nò tìckèt còlùmn. Thè ònly lìnk bètwèèn à dìsbùrsèmènt ànd ìts càsè ìs ìnsìdè thè càsè nòtè's èncryptèd còntènt, sèàlèd wìth thè tìckèt kèy. À còpy thàt hàs thè fòllòwùps tàblè shòws whìch càsès càrry ìntèrnàl nòtès ànd òn whìch dàys. Whèn à sìnglè nòtè ànd à sìnglè lèdgèr èntry shàrè thè sàmè càlèndàr dàtè, thè twò càn bè màtchèd. Whèn sèvèràl nòtès òr sèvèràl èntrìès fàll òn thè sàmè dày, thè dàtè àlònè dòès nòt dìstìngùìsh whìch nòtè bèlòngs tò whìch èntry. [[#sèrvèr-hòlds #prìvàcy #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè nòtìfìcàtìòn tògglè rèvèàl? •••••••••••••** Thè tògglè ìs à plàìntèxt bòòlèàn òn thè òrgànìzàtìòn's cònfìgùràtìòn ròw. Ìt tèlls thè sèrvèr whèthèr thè òrgànìzàtìòn hàs fùnd-èntry nòtìfìcàtìòns tùrnèd òn. Thè nòtìfìcàtìòn ìtsèlf ìs à tìckètlèss èvènt thàt nàmès nò càsè ànd càrrìès nò fìnàncìàl còntènt. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt sùrvìvès à càsè pùrgè? •••••••••** Pùrgìng à càsè thròùgh thè rètèntìòn pòlìcy òr by hànd dèlètès thè càsè's ròws, ànd àny dìsbùrsèmènt nòtè ìn ìts thrèàd. Thè lèdgèr èntry thàt rècòrdèd thè dìsbùrsèmènt ìs nòt dèlètèd, bècàùsè ìt càrrìès nò rèfèrèncè tò thè càsè. Thè fùnd's bàlàncè stàys còrrèct àftèr thè pùrgè. Àn òrphànèd lèdgèr èntry rèàds às à dìsbùrsèmènt whòsè càsè hàs bèèn rèmòvèd, whìch ìs thè ìntèndèd bèhàvìòr. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thè pùrgè pòlìcy. [[#rètèntìòn #èncryptìòn #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt ìntègrìty dòès thè sèrvèr chèck? ••••••••••••** Thè sèrvèr ènfòrcès thè bàlàncè vèrsìòn gùàrd (à wrìtè ìs rèjèctèd whèn thè vèrsìòn hàs mòvèd sìncè thè bròwsèr làst rèàd ìt) ànd thè pèrmìssìòn gàtès òn èàch pròcèdùrè. Thè sèrvèr cànnòt vèrìfy àmòùnts, èntry typès, òr fùnd rèfèrèncès, bècàùsè thòsè vàlùès àrè ìnsìdè sèàlèd pàylòàds thè sèrvèr cànnòt òpèn. Àccùràcy dèpènds òn whàt thè bròwsèr sùbmìts. Thè [fùnd lèdgèr](#àdmìn-òrg/fùnd-lèdgèr) pàgè's rècòmpùtè àctìòn ìs thè ònly chèck thàt thè sèàlèd bàlàncè màtchès thè sùm òf thè lèdgèr. [[#èncryptìòn #sèrvèr-hòlds #pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fùnd sèrvìcè trànsàctìòn bòùndàrìès. ••••••••••••** \`pàckàgès/sèrvèr/src/fùnds/fùnd-sèrvìcè.ts\` rùns èvèry bàlàncè wrìtè ànd lèdgèr ìnsèrt ìnsìdè ònè dàtàbàsè trànsàctìòn. À dìsbùrsèmènt wrìtès thè lèdgèr èntry, thè rèsèàlèd bàlàncè, ànd thè càsè nòtè ìn à sìnglè còmmìt. Ìf àny stèp fàìls, èvèrythìng ròlls bàck. Thè nòtìfìcàtìòn tò fùnd mànàgèrs fìrès àftèr còmmìt, òùtsìdè thè trànsàctìòn, ànd ìs bèst-èffòrt. [[#sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Every value that describes a fund or a ledger entry by name, amount, currency, type, or author is organization-key ciphertext. The server stores the sealed b..." |
*
* @param {Demo_Narrative_Deepdive_Fund_Records_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_fund_records_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Fund_Records_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Fund_Records_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_fund_records_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_fund_records_body(inputs)
	return en_demo_narrative_deepdive_fund_records_body(inputs)
});