/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Language_BodyInputs */

const en_demo_narrative_topic_language_body = /** @type {(inputs: Demo_Narrative_Topic_Language_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The user can switch the interface language before signing in or at any time afterward. English and Spanish are compiled into the app, and a switch takes effect immediately without a server request. When no preference is stored, the app uses the language the browser requests, falling back to English when the browser requests neither. [[#privacy #client-data]]
**What does the server hold?** The stored preference is sealed to the organization key on the account. A database dump reveals that an account recorded a preference, not which language it chose. The server seals the preference itself during account creation, the one moment the choice passes through it as plaintext. Every later change is sealed in the browser and arrives at the server as ciphertext it writes without reading. The server holds no key that opens either value. [How encryption works](#deep-dive/how-encryption-works) covers the organization key. [[#server-holds #encryption]]
**When does the stored preference apply?** The sealed preference returns with the sign-in response. The browser opens it after key derivation finishes, so the stored language takes effect at the end of sign-in, not at the start. A language switch inside the app changes the running session on its own. The stored copy updates only when the user saves from settings or accepts the save offer. [[#encryption #keys]]
**The save offer.** After a language switch, the app asks once per session whether to keep the new language as the stored preference. The question is asked in the language being switched to, and it is not repeated in that session whether accepted or declined. The offer is skipped when the stored preference already matches. The save offer reappears in the next session if the stored preference still differs. [On the device](#deep-dive/on-the-device) covers what else survives after signing out. [[#privacy #client-data]]
**The locale resolution chain and the stored column.** Resolution order is the browser's preferred language, then the base locale. The stored column is \`users.encrypted_preferred_locale\`, sealed in \`packages/server/src/auth/service.ts\` and \`packages/server/src/onboarding/onboarding-service.ts\` on the creation paths and in \`packages/client/src/lib/settings/preferred-locale.ts\` for every change afterward, and opened in \`packages/client/src/routes/(auth)/login/+page.svelte\`. Interface locales and intake-form locales are separate lists. \`FORM_LOCALES\` in \`packages/shared/src/schemas/intake-forms.ts\` controls which languages an intake form can be written in. Adding a new interface language is catalog work in \`packages/shared/messages/\` and a locale entry in both \`packages/client/project.inlang/settings.json\` and \`packages/shared/project.inlang/settings.json\`. Paraglide compiles per package, so both must be compiled or one side serves stale strings. [[#client-data #server-holds]]`)
};

const es_demo_narrative_topic_language_body = /** @type {(inputs: Demo_Narrative_Topic_Language_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La persona usuaria puede cambiar el idioma de la interfaz antes de iniciar sesión o en cualquier momento posterior. El inglés y el español están compilados en la aplicación, y un cambio surte efecto de inmediato sin una solicitud al servidor. Cuando no hay preferencia almacenada, la aplicación usa el idioma que solicita el navegador y recurre al inglés cuando el navegador no solicita ninguno de los dos. [[#privacy #client-data]]
**¿Qué almacena el servidor?** La preferencia almacenada está sellada con la clave de la organización en la cuenta. Un volcado de la base de datos revela que una cuenta registró una preferencia, no qué idioma eligió. El servidor sella la preferencia él mismo durante la creación de la cuenta, el único momento en que la elección pasa por él como texto plano. Cada cambio posterior se sella en el navegador y llega al servidor como texto cifrado que escribe sin leer. El servidor no posee ninguna clave que abra ninguno de los dos valores. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la clave de la organización. [[#server-holds #encryption]]
**¿Cuándo se aplica la preferencia almacenada?** La preferencia sellada regresa con la respuesta de inicio de sesión. El navegador la abre cuando la derivación de claves termina, de modo que el idioma almacenado surte efecto al final del inicio de sesión, no al principio. Un cambio de idioma dentro de la aplicación modifica la sesión activa por sí solo. La copia almacenada se actualiza solo cuando la persona usuaria guarda desde ajustes o acepta la oferta de guardar. [[#encryption #keys]]
**La oferta de guardar.** Tras un cambio de idioma, la aplicación pregunta una vez por sesión si se desea conservar el nuevo idioma como preferencia almacenada. La pregunta se formula en el idioma al que se cambia, y no se repite en esa sesión tanto si se acepta como si se rechaza. Se omite cuando la preferencia almacenada ya coincide. La oferta de guardar reaparece en la siguiente sesión si la preferencia almacenada aún difiere. [En el dispositivo](#deep-dive/on-the-device) trata lo demás que sobrevive tras cerrar sesión. [[#privacy #client-data]]
**La cadena de resolución de idioma y la columna almacenada.** El orden de resolución es el idioma preferido del navegador, luego el idioma base. La columna almacenada es \`users.encrypted_preferred_locale\`, sellada en \`packages/server/src/auth/service.ts\` y \`packages/server/src/onboarding/onboarding-service.ts\` en las rutas de creación, y en \`packages/client/src/lib/settings/preferred-locale.ts\` para cada cambio posterior, y abierta en \`packages/client/src/routes/(auth)/login/+page.svelte\`. Los idiomas de interfaz y los idiomas de formularios de admisión son listas separadas. \`FORM_LOCALES\` en \`packages/shared/src/schemas/intake-forms.ts\` controla en qué idiomas se puede redactar un formulario de admisión. Agregar un nuevo idioma de interfaz es trabajo de catálogo en \`packages/shared/messages/\` y una entrada de idioma en \`packages/client/project.inlang/settings.json\` y \`packages/shared/project.inlang/settings.json\`. Paraglide compila por paquete, así que ambos deben compilarse o un lado sirve cadenas desactualizadas. [[#client-data #server-holds]]`)
};

const en_xa2_demo_narrative_topic_language_body = /** @type {(inputs: Demo_Narrative_Topic_Language_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ùsèr càn swìtch thè ìntèrfàcè làngùàgè bèfòrè sìgnìng ìn òr àt àny tìmè àftèrwàrd. Ènglìsh ànd Spànìsh àrè còmpìlèd ìntò thè àpp, ànd à swìtch tàkès èffèct ìmmèdìàtèly wìthòùt à sèrvèr rèqùèst. Whèn nò prèfèrèncè ìs stòrèd, thè àpp ùsès thè làngùàgè thè bròwsèr rèqùèsts, fàllìng bàck tò Ènglìsh whèn thè bròwsèr rèqùèsts nèìthèr. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr hòld? ••••••••** Thè stòrèd prèfèrèncè ìs sèàlèd tò thè òrgànìzàtìòn kèy òn thè àccòùnt. À dàtàbàsè dùmp rèvèàls thàt àn àccòùnt rècòrdèd à prèfèrèncè, nòt whìch làngùàgè ìt chòsè. Thè sèrvèr sèàls thè prèfèrèncè ìtsèlf dùrìng àccòùnt crèàtìòn, thè ònè mòmènt thè chòìcè pàssès thròùgh ìt às plàìntèxt. Èvèry làtèr chàngè ìs sèàlèd ìn thè bròwsèr ànd àrrìvès àt thè sèrvèr às cìphèrtèxt ìt wrìtès wìthòùt rèàdìng. Thè sèrvèr hòlds nò kèy thàt òpèns èìthèr vàlùè. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè òrgànìzàtìòn kèy. [[#sèrvèr-hòlds #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn dòès thè stòrèd prèfèrèncè àpply? ••••••••••••** Thè sèàlèd prèfèrèncè rètùrns wìth thè sìgn-ìn rèspònsè. Thè bròwsèr òpèns ìt àftèr kèy dèrìvàtìòn fìnìshès, sò thè stòrèd làngùàgè tàkès èffèct àt thè ènd òf sìgn-ìn, nòt àt thè stàrt. À làngùàgè swìtch ìnsìdè thè àpp chàngès thè rùnnìng sèssìòn òn ìts òwn. Thè stòrèd còpy ùpdàtès ònly whèn thè ùsèr sàvès fròm sèttìngs òr àccèpts thè sàvè òffèr. [[#èncryptìòn #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè sàvè òffèr. •••••** Àftèr à làngùàgè swìtch, thè àpp àsks òncè pèr sèssìòn whèthèr tò kèèp thè nèw làngùàgè às thè stòrèd prèfèrèncè. Thè qùèstìòn ìs àskèd ìn thè làngùàgè bèìng swìtchèd tò, ànd ìt ìs nòt rèpèàtèd ìn thàt sèssìòn whèthèr àccèptèd òr dèclìnèd. Thè òffèr ìs skìppèd whèn thè stòrèd prèfèrèncè àlrèàdy màtchès. Thè sàvè òffèr rèàppèàrs ìn thè nèxt sèssìòn ìf thè stòrèd prèfèrèncè stìll dìffèrs. [Òn thè dèvìcè](#dèèp-dìvè/òn-thè-dèvìcè) còvèrs whàt èlsè sùrvìvès àftèr sìgnìng òùt. [[#prìvàcy #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè lòcàlè rèsòlùtìòn chàìn ànd thè stòrèd còlùmn. •••••••••••••••** Rèsòlùtìòn òrdèr ìs thè bròwsèr's prèfèrrèd làngùàgè, thèn thè bàsè lòcàlè. Thè stòrèd còlùmn ìs \`ùsèrs.èncryptèd_prèfèrrèd_lòcàlè\`, sèàlèd ìn \`pàckàgès/sèrvèr/src/àùth/sèrvìcè.ts\` ànd \`pàckàgès/sèrvèr/src/ònbòàrdìng/ònbòàrdìng-sèrvìcè.ts\` òn thè crèàtìòn pàths ànd ìn \`pàckàgès/clìènt/src/lìb/sèttìngs/prèfèrrèd-lòcàlè.ts\` fòr èvèry chàngè àftèrwàrd, ànd òpènèd ìn \`pàckàgès/clìènt/src/ròùtès/(àùth)/lògìn/+pàgè.svèltè\`. Ìntèrfàcè lòcàlès ànd ìntàkè-fòrm lòcàlès àrè sèpàràtè lìsts. \`FÒRM_LÒCÀLÈS\` ìn \`pàckàgès/shàrèd/src/schèmàs/ìntàkè-fòrms.ts\` còntròls whìch làngùàgès àn ìntàkè fòrm càn bè wrìttèn ìn. Àddìng à nèw ìntèrfàcè làngùàgè ìs càtàlòg wòrk ìn \`pàckàgès/shàrèd/mèssàgès/\` ànd à lòcàlè èntry ìn bòth \`pàckàgès/clìènt/pròjèct.ìnlàng/sèttìngs.jsòn\` ànd \`pàckàgès/shàrèd/pròjèct.ìnlàng/sèttìngs.jsòn\`. Pàràglìdè còmpìlès pèr pàckàgè, sò bòth mùst bè còmpìlèd òr ònè sìdè sèrvès stàlè strìngs. [[#clìènt-dàtà #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The user can switch the interface language before signing in or at any time afterward. English and Spanish are compiled into the app, and a switch takes effe..." |
*
* @param {Demo_Narrative_Topic_Language_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_language_body = /** @type {((inputs?: Demo_Narrative_Topic_Language_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Language_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_language_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_language_body(inputs)
	return en_demo_narrative_topic_language_body(inputs)
});