/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Greetings_BodyInputs */

const en_demo_narrative_admin_greetings_body = /** @type {(inputs: Demo_Narrative_Admin_Greetings_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Greetings are what a caller hears on the way through a phone line, five of them for five points in the call, one for the answer, one for the language prompt, one for a caller with no case yet, one for a caller who already has one, and one for the staff menu. Each one is stored for a number and a language, so a line answers in the caller's language where a recording exists for it. [[#telephony]]
**Text or recording.** A greeting is either text the provider reads aloud or an uploaded recording in WAV, MP3 or OGG, up to five megabytes, and an upload is checked against the format's own signature bytes before storage so a file that claims to be audio and is not never reaches the store. Uploads are rate limited per account. [[#failure-states]]
**Why a greeting is not encrypted.** Every caller hears it, so the text and the recording are stored as the organization wrote them, and the provider fetches the recording over a public address whose only protection is an unguessable key the server generates. A greeting is outward-facing content in the same sense as the organization's branding, and it must never carry anything about a client or a case, since anyone holding the address can play it. [[#server-holds #privacy]]
**What the greeting row reveals.** The organization's own phone number sits in plaintext beside each greeting, along with the language, the greeting type and both timestamps, so a database dump of this table gives the numbers an organization answers on, the languages it serves and what it says on each line. This is the one place the tenant database records an organization's numbers. [The trust boundary](#deep-dive/the-trust-boundary) covers the plaintext columns across the schema. [[#metadata #server-holds]]
**The greeting row and its two readers.** \`019_create_phone_greetings.ts\` with \`054_greeting_phone_number.ts\` keys a greeting on number, language and type, and \`packages/server/src/telephony/ivr.ts\` turns each one into a spoken line or a played file when a call arrives. The admin preview reads the same recording through an authenticated endpoint rather than the public address. Writing a greeting needs permission to write call greetings, and reaching the section needs permission to manage infrastructure. [[#permissions]]`)
};

const es_demo_narrative_admin_greetings_body = /** @type {(inputs: Demo_Narrative_Admin_Greetings_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los saludos son lo que escucha quien llama a medida que avanza por una línea telefónica, cinco para cinco momentos de la llamada, uno para la respuesta, uno para la selección de idioma, uno para quien todavía no tiene caso, uno para quien ya tiene uno y uno para el menú del personal. Cada uno se guarda para un número y un idioma, de modo que una línea responde en el idioma de quien llama cuando existe una grabación para él. [[#telephony]]
**Texto o grabación.** Un saludo es texto que el proveedor lee en voz alta o una grabación subida en WAV, MP3 u OGG, de hasta cinco megabytes, y cada subida se comprueba contra los bytes de firma del propio formato antes de guardarse, así que un archivo que dice ser audio sin serlo nunca llega al almacén. Las subidas tienen un límite de frecuencia por cuenta. [[#failure-states]]
**Por qué un saludo no se cifra.** Todas las personas que llaman lo escuchan, así que el texto y la grabación se guardan tal como los escribió la organización, y el proveedor descarga la grabación desde una dirección pública cuya única protección es una clave impredecible que genera el servidor. Un saludo es contenido dirigido al exterior en el mismo sentido que la imagen de la organización, y nunca debe llevar nada sobre un cliente ni sobre un caso, porque cualquiera que tenga la dirección puede reproducirlo. [[#server-holds #privacy]]
**Lo que revela la fila de un saludo.** El número de teléfono de la propia organización está en texto plano junto a cada saludo, con el idioma, el tipo de saludo y ambas marcas de tiempo, de modo que un volcado de esta tabla da los números en los que responde una organización, los idiomas que atiende y lo que dice en cada línea. Es el único lugar donde la base de datos del inquilino registra los números de una organización. [La frontera de confianza](#deep-dive/the-trust-boundary) trata las columnas en texto plano de todo el esquema. [[#metadata #server-holds]]
**La fila del saludo y sus dos lectores.** \`019_create_phone_greetings.ts\`, junto con \`054_greeting_phone_number.ts\`, guarda un saludo bajo el número, el idioma y el tipo, y \`packages/server/src/telephony/ivr.ts\` convierte cada uno en una línea hablada o en un archivo reproducido cuando entra una llamada. La vista previa de administración lee esa misma grabación por un endpoint autenticado y no por la dirección pública. Escribir un saludo requiere permiso para escribir saludos de llamada, y llegar a la sección requiere permiso para gestionar la infraestructura. [[#permissions]]`)
};

const en_xa2_demo_narrative_admin_greetings_body = /** @type {(inputs: Demo_Narrative_Admin_Greetings_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Grèètìngs àrè whàt à càllèr hèàrs òn thè wày thròùgh à phònè lìnè, fìvè òf thèm fòr fìvè pòìnts ìn thè càll, ònè fòr thè ànswèr, ònè fòr thè làngùàgè pròmpt, ònè fòr à càllèr wìth nò càsè yèt, ònè fòr à càllèr whò àlrèàdy hàs ònè, ànd ònè fòr thè stàff mènù. Èàch ònè ìs stòrèd fòr à nùmbèr ànd à làngùàgè, sò à lìnè ànswèrs ìn thè càllèr's làngùàgè whèrè à rècòrdìng èxìsts fòr ìt. [[#tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Tèxt òr rècòrdìng. ••••••** À grèètìng ìs èìthèr tèxt thè pròvìdèr rèàds àlòùd òr àn ùplòàdèd rècòrdìng ìn WÀV, MP3 òr ÒGG, ùp tò fìvè mègàbytès, ànd àn ùplòàd ìs chèckèd àgàìnst thè fòrmàt's òwn sìgnàtùrè bytès bèfòrè stòràgè sò à fìlè thàt clàìms tò bè àùdìò ànd ìs nòt nèvèr rèàchès thè stòrè. Ùplòàds àrè ràtè lìmìtèd pèr àccòùnt. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why à grèètìng ìs nòt èncryptèd. ••••••••••** Èvèry càllèr hèàrs ìt, sò thè tèxt ànd thè rècòrdìng àrè stòrèd às thè òrgànìzàtìòn wròtè thèm, ànd thè pròvìdèr fètchès thè rècòrdìng òvèr à pùblìc àddrèss whòsè ònly pròtèctìòn ìs àn ùngùèssàblè kèy thè sèrvèr gènèràtès. À grèètìng ìs òùtwàrd-fàcìng còntènt ìn thè sàmè sènsè às thè òrgànìzàtìòn's bràndìng, ànd ìt mùst nèvèr càrry ànythìng àbòùt à clìènt òr à càsè, sìncè ànyònè hòldìng thè àddrèss càn plày ìt. [[#sèrvèr-hòlds #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè grèètìng ròw rèvèàls. •••••••••** Thè òrgànìzàtìòn's òwn phònè nùmbèr sìts ìn plàìntèxt bèsìdè èàch grèètìng, àlòng wìth thè làngùàgè, thè grèètìng typè ànd bòth tìmèstàmps, sò à dàtàbàsè dùmp òf thìs tàblè gìvès thè nùmbèrs àn òrgànìzàtìòn ànswèrs òn, thè làngùàgès ìt sèrvès ànd whàt ìt sàys òn èàch lìnè. Thìs ìs thè ònè plàcè thè tènànt dàtàbàsè rècòrds àn òrgànìzàtìòn's nùmbèrs. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè plàìntèxt còlùmns àcròss thè schèmà. [[#mètàdàtà #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè grèètìng ròw ànd ìts twò rèàdèrs. ••••••••••••** \`019_crèàtè_phònè_grèètìngs.ts\` wìth \`054_grèètìng_phònè_nùmbèr.ts\` kèys à grèètìng òn nùmbèr, làngùàgè ànd typè, ànd \`pàckàgès/sèrvèr/src/tèlèphòny/ìvr.ts\` tùrns èàch ònè ìntò à spòkèn lìnè òr à plàyèd fìlè whèn à càll àrrìvès. Thè àdmìn prèvìèw rèàds thè sàmè rècòrdìng thròùgh àn àùthèntìcàtèd èndpòìnt ràthèr thàn thè pùblìc àddrèss. Wrìtìng à grèètìng nèèds pèrmìssìòn tò wrìtè càll grèètìngs, ànd rèàchìng thè sèctìòn nèèds pèrmìssìòn tò mànàgè ìnfràstrùctùrè. [[#pèrmìssìòns]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Greetings are what a caller hears on the way through a phone line, five of them for five points in the call, one for the answer, one for the language prompt,..." |
*
* @param {Demo_Narrative_Admin_Greetings_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_greetings_body = /** @type {((inputs?: Demo_Narrative_Admin_Greetings_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Greetings_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_greetings_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_greetings_body(inputs)
	return en_demo_narrative_admin_greetings_body(inputs)
});