/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Settings_Password_BodyInputs */

const en_demo_narrative_settings_password_body = /** @type {(inputs: Demo_Narrative_Settings_Password_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Changing a password re-runs the derivation a sign-in runs, because the password is where the account's encryption keys come from. The browser derives a second set of keys from the new password, wraps everything the old set could open for the new one, and only then asks the server to accept the change. [[#keys #encryption]]
**What is wrapped again and what is left alone.** The key of every case the account can read, and the account's copy of the organization key, are opened with the old private key and wrapped for the new one. No case is re-encrypted, because each case keeps its own key and only the wrapping around that key changes, so an account holding a thousand cases re-wraps a thousand small keys rather than a thousand cases of text. [How keys are derived](#deep-dive/how-keys-are-derived) covers where the new keys come from. [[#keys #encryption]]
**What the server is given.** One request carrying the current password, the new password, a new salt, the new public half and the re-wrapped keys. The server verifies the current password against its stored hash, stores a hash of the new one, replaces the salt and public half, and swaps in the new wrap rows. It receives no private key and nothing it could unwrap, which is the same position it is in during a sign-in. [Username and password](#login/credentials) covers what it holds of a password. [[#server-holds #keys]]
**What ends and what continues.** Every other session on the account is deleted in the same transaction that stores the new hash, so a session opened elsewhere stops working at the change rather than at its own expiry. The session that made the change re-derives its keys and carries on without a further sign-in. [[#failure-states #privacy]]
**When a change is refused.** Five attempts a minute per account and address, counted against the request rather than the password, and a wrong current password ends the attempt before anything is written. A change is also refused while an intake submission or a portal reply is waiting to be converted, because those are sealed to the organization key as it stands and rotating past them would leave them unopenable. [[#failure-states #keys]]
**The window the code documents.** The new hash and the key rotation are two transactions inside one handler, so a server that dies between them leaves an account whose password has changed and whose key wraps have not, which is a state the next sign-in cannot derive into. The comment on the handler states this and weighs it against the minutes-long client-side gap it replaced. [[#failure-states #trust-boundary]]
**The orchestrator and the rotation service.** The browser sequence is \`changePassword\` in \`packages/client/src/lib/settings/password-change.ts\`, which runs a second short-lived crypto worker for the new keys and re-wraps case keys in batches of forty. The server side is \`profile.changePassword\` in \`packages/server/src/routes/profile.ts\` over \`packages/server/src/crypto/key-rotation.ts\`, whose \`rotation_lock\` column keeps a new case from being wrapped for a public key the account is about to stop holding. [[#keys #server-holds]]`)
};

const es_demo_narrative_settings_password_body = /** @type {(inputs: Demo_Narrative_Settings_Password_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cambiar la contraseña vuelve a ejecutar la derivación de un inicio de sesión, porque la contraseña es el origen de las claves de cifrado de la cuenta. El navegador deriva un segundo juego de claves a partir de la contraseña nueva, envuelve para él todo lo que abría el juego anterior y solo después pide al servidor que acepte el cambio. [[#keys #encryption]]
**Qué se vuelve a envolver y qué se deja intacto.** La clave de cada caso que la cuenta puede leer, y la copia de la clave de la organización que tiene la cuenta, se abren con la clave privada anterior y se envuelven para la nueva. Ningún caso se vuelve a cifrar, porque cada caso conserva su propia clave y solo cambia la envoltura que la rodea, de modo que una cuenta con mil casos reenvuelve mil claves pequeñas y no mil casos de texto. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata de dónde salen las claves nuevas. [[#keys #encryption]]
**Lo que se le entrega al servidor.** Una sola petición con la contraseña actual, la contraseña nueva, una sal nueva, la nueva mitad pública y las claves reenvueltas. El servidor comprueba la contraseña actual contra el hash que guarda, guarda un hash de la nueva, sustituye la sal y la mitad pública e intercambia las filas de envoltura. No recibe ninguna clave privada ni nada que pudiera desenvolver, que es la misma posición en la que está durante un inicio de sesión. [Nombre de usuario y contraseña](#login/credentials) trata lo que guarda de una contraseña. [[#server-holds #keys]]
**Qué termina y qué continúa.** Todas las demás sesiones de la cuenta se eliminan en la misma transacción que guarda el hash nuevo, así que una sesión abierta en otro sitio deja de funcionar en el momento del cambio y no al caducar. La sesión que hizo el cambio vuelve a derivar sus claves y sigue adelante sin otro inicio de sesión. [[#failure-states #privacy]]
**Cuándo se rechaza un cambio.** Cinco intentos por minuto por cuenta y dirección, contados sobre la petición y no sobre la contraseña, y una contraseña actual incorrecta termina el intento antes de que se escriba nada. También se rechaza mientras una solicitud de admisión o una respuesta del portal estén pendientes de conversión, porque están selladas con la clave de la organización tal como está y rotar más allá de ellas las dejaría sin poder abrirse. [[#failure-states #keys]]
**La ventana que el código documenta.** El hash nuevo y la rotación de claves son dos transacciones dentro de un mismo manejador, así que un servidor que muera entre ellas deja una cuenta con la contraseña cambiada y las envolturas sin cambiar, un estado que el inicio de sesión siguiente no puede derivar. El comentario del manejador lo deja escrito y lo compara con el hueco de varios minutos en el cliente que vino a sustituir. [[#failure-states #trust-boundary]]
**El orquestador y el servicio de rotación.** La secuencia del navegador es \`changePassword\`, en \`packages/client/src/lib/settings/password-change.ts\`, que ejecuta un segundo worker criptográfico efímero para las claves nuevas y reenvuelve las claves de los casos en lotes de cuarenta. El lado del servidor es \`profile.changePassword\`, en \`packages/server/src/routes/profile.ts\`, sobre \`packages/server/src/crypto/key-rotation.ts\`, cuya columna \`rotation_lock\` impide que un caso nuevo se envuelva para una clave pública que la cuenta está a punto de dejar de tener. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_settings_password_body = /** @type {(inputs: Demo_Narrative_Settings_Password_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Chàngìng à pàsswòrd rùns thè fùll kèy dèrìvàtìòn pìpèlìnè. Thè bròwsèr pròcèssès thè pàsswòrd thròùgh Àrgòn2ìd, pèrfòrms thè ÒPRF èxchàngè wìth thè thrèshòld sèrvèrs, ànd rè-wràps thè cryptògràphìc kèys.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns dùrìng à pàsswòrd chàngè. ••••••••••••** Thè bròwsèr dèrìvès nèw èncryptìòn kèys fròm thè nèw pàsswòrd, thèn rè-wràps thè òrgànìzàtìòn kèy ànd èvèry tìckèt kèy thè vòlùntèèr hàs àccèss tò ùndèr thè nèw kèys. Thìs mèàns thè vòlùntèèr's èncryptèd dàtà rèmàìns àccèssìblè wìthòùt rè-èncryptìng thè dàtà ìtsèlf. Thè òld pàsswòrd ìs vèrìfìèd, thè nèw pàsswòrd ìs hàshèd, àll kèy wràps àrè ròtàtèd, ànd òthèr àctìvè sèssìòns àrè tèrmìnàtèd, àll ìn à sìnglè àtòmìc sèrvèr càll.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè sèrvèr sèès. •••••••** Thè sèrvèr nèvèr sèès thè plàìntèxt òf thè nèw prìvàtè kèy. Ìt rècèìvès ònly thè rè-wràppèd kèy màtèrìàl, whìch ìs èncryptèd ànd ònly dècryptàblè by thè vòlùntèèr. ••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Changing a password re-runs the derivation a sign-in runs, because the password is where the account's encryption keys come from. The browser derives a secon..." |
*
* @param {Demo_Narrative_Settings_Password_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_settings_password_body = /** @type {((inputs?: Demo_Narrative_Settings_Password_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Settings_Password_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_settings_password_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_settings_password_body(inputs)
	return en_demo_narrative_settings_password_body(inputs)
});