/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Disbursement_BodyInputs */

const en_demo_narrative_topic_disbursement_body = /** @type {(inputs: Demo_Narrative_Topic_Disbursement_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Recording a disbursement is a compose action gated on the Record disbursements and View funds permissions together, and available only when the case's queue maps to a fund. The action opens a sheet where the user picks a fund, enters an amount, and writes an optional note. The queue's mapped fund is preselected. The user can choose any other active fund. [[#client-data #permissions]]
**What does one save write?** A single server transaction writes a ledger entry for the fund, the fund's resealed balance, and a private internal note on the case. The ledger entry carries no ticket reference. The note's encrypted content holds a structured envelope tying the entry to its fund and amount. If any step fails, everything rolls back. [[#encryption #server-holds]]
**The case note.** The disbursement appears in the thread as a private internal note showing the amount and the fund name. It is sealed with the ticket key, the same way any other internal note is sealed. Recording it also triggers the same case notification that an ordinary note triggers. [[#client-data #encryption]]
**Correcting a disbursement.** The context menu on a disbursement note offers an edit action. Editing reopens the sheet with the amount and note prefilled and the fund locked. Saving writes a reversal, a replacement entry with the corrected amount, and the rewritten case note, all in one transaction. The reversal-and-replacement pair forms the audit trail. [Fund ledger](#admin-org/fund-ledger) covers what the auditor sees. [[#failure-states #metadata]]
**Who can correct one?** The author can correct their own. A holder of Manage funds can correct another user's disbursement, and no other kind of note. Both paths require Record disbursements. The server enforces the author check and the permission check. [[#permissions]]
**The envelope inside the note.** A disbursement note begins with a marker character that distinguishes it from free-text notes. After the marker, a JSON envelope holds the ledger entry id, the fund id, the amount in minor units, the currency, and the note text. The renderer checks the marker after decryption and presents the amount and fund name. Without View funds, the fund name is omitted. [[#encryption #client-data]]
**The sheet and the balance retry.** \`DisbursementSheet.svelte\` in \`packages/client/src/lib/components/tickets/\` encrypts the ledger payload under the organization key and the note under the ticket key. On a stale-balance error, \`writeWithBalance\` in \`packages/client/src/lib/funds/fund-store.svelte.ts\` refetches the fund list, rebuilds the next balance from the fresh figure, and retries once before showing an error. [Fund balances](#ticket-detail/fund-balance) covers the shared balance cache. [[#failure-states #client-data]]`)
};

const es_demo_narrative_topic_disbursement_body = /** @type {(inputs: Demo_Narrative_Topic_Disbursement_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Registrar un desembolso es una acción del menú de redacción, controlada por los permisos Registrar desembolsos y Ver fondos juntos, y disponible solo cuando la cola del caso tiene un fondo asignado. La acción abre una hoja donde se elige un fondo, se ingresa un monto y se escribe una nota opcional. El fondo asignado a la cola aparece preseleccionado. Se puede elegir cualquier otro fondo activo. [[#client-data #permissions]]
**¿Qué escribe un guardado?** Una sola transacción del servidor escribe una entrada en el libro mayor del fondo, el saldo resellado del fondo y una nota interna privada en el caso. La entrada del libro mayor no lleva referencia al ticket. El contenido cifrado de la nota contiene un sobre estructurado que vincula la entrada con su fondo y monto. Si cualquier paso falla, todo se revierte. [[#encryption #server-holds]]
**La nota del caso.** El desembolso aparece en el hilo como una nota interna privada que muestra el monto y el nombre del fondo. Está sellada con la clave del ticket, igual que cualquier otra nota interna. Registrarlo también dispara la misma notificación de caso que una nota ordinaria. [[#client-data #encryption]]
**Corrección de un desembolso.** El menú contextual de la nota de desembolso ofrece una acción de edición. Editar reabre la hoja con el monto y la nota precargados y el fondo bloqueado. Guardar escribe una reversión, una entrada de reemplazo con el monto corregido y la nota reescrita del caso, todo en una transacción. El par de reversión y reemplazo constituye el rastro de auditoría. [Libro mayor de fondos](#admin-org/fund-ledger) trata lo que ve el auditor. [[#failure-states #metadata]]
**¿Quién puede corregir uno?** El autor puede corregir el suyo. Un titular del permiso Gestionar fondos puede corregir el desembolso de otra persona, y ningún otro tipo de nota. Ambas vías requieren Registrar desembolsos. El servidor aplica la verificación de autoría y la verificación de permiso. [[#permissions]]
**El sobre dentro de la nota.** Una nota de desembolso comienza con un carácter marcador que la distingue de las notas de texto libre. Después del marcador, un sobre JSON contiene el id de la entrada del libro mayor, el id del fondo, el monto en unidades menores, la moneda y el texto de la nota. El renderizador comprueba el marcador tras descifrar y presenta el monto y el nombre del fondo. Sin Ver fondos, el nombre del fondo se omite. [[#encryption #client-data]]
**La hoja y el reintento de saldo.** \`DisbursementSheet.svelte\` en \`packages/client/src/lib/components/tickets/\` cifra la carga del libro mayor con la clave de organización y la nota con la clave del ticket. Ante un error de saldo obsoleto, \`writeWithBalance\` en \`packages/client/src/lib/funds/fund-store.svelte.ts\` vuelve a obtener la lista de fondos, reconstruye el siguiente saldo a partir del valor actualizado y reintenta una vez antes de mostrar un error. [Saldos de fondos](#ticket-detail/fund-balance) trata la caché de saldo compartida. [[#failure-states #client-data]]`)
};

const en_xa2_demo_narrative_topic_disbursement_body = /** @type {(inputs: Demo_Narrative_Topic_Disbursement_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Rècòrdìng à dìsbùrsèmènt ìs à còmpòsè àctìòn gàtèd òn thè Rècòrd dìsbùrsèmènts ànd Vìèw fùnds pèrmìssìòns tògèthèr, ànd àvàìlàblè ònly whèn thè càsè's qùèùè màps tò à fùnd. Thè àctìòn òpèns à shèèt whèrè thè ùsèr pìcks à fùnd, èntèrs àn àmòùnt, ànd wrìtès àn òptìònàl nòtè. Thè qùèùè's màppèd fùnd ìs prèsèlèctèd. Thè ùsèr càn chòòsè àny òthèr àctìvè fùnd. [[#clìènt-dàtà #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès ònè sàvè wrìtè? ••••••••** À sìnglè sèrvèr trànsàctìòn wrìtès à lèdgèr èntry fòr thè fùnd, thè fùnd's rèsèàlèd bàlàncè, ànd à prìvàtè ìntèrnàl nòtè òn thè càsè. Thè lèdgèr èntry càrrìès nò tìckèt rèfèrèncè. Thè nòtè's èncryptèd còntènt hòlds à strùctùrèd ènvèlòpè tyìng thè èntry tò ìts fùnd ànd àmòùnt. Ìf àny stèp fàìls, èvèrythìng ròlls bàck. [[#èncryptìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè càsè nòtè. •••••** Thè dìsbùrsèmènt àppèàrs ìn thè thrèàd às à prìvàtè ìntèrnàl nòtè shòwìng thè àmòùnt ànd thè fùnd nàmè. Ìt ìs sèàlèd wìth thè tìckèt kèy, thè sàmè wày àny òthèr ìntèrnàl nòtè ìs sèàlèd. Rècòrdìng ìt àlsò trìggèrs thè sàmè càsè nòtìfìcàtìòn thàt àn òrdìnàry nòtè trìggèrs. [[#clìènt-dàtà #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Còrrèctìng à dìsbùrsèmènt. ••••••••** Thè còntèxt mènù òn à dìsbùrsèmènt nòtè òffèrs àn èdìt àctìòn. Èdìtìng rèòpèns thè shèèt wìth thè àmòùnt ànd nòtè prèfìllèd ànd thè fùnd lòckèd. Sàvìng wrìtès à rèvèrsàl, à rèplàcèmènt èntry wìth thè còrrèctèd àmòùnt, ànd thè rèwrìttèn càsè nòtè, àll ìn ònè trànsàctìòn. Thè rèvèrsàl-ànd-rèplàcèmènt pàìr fòrms thè àùdìt tràìl. [Fùnd lèdgèr](#àdmìn-òrg/fùnd-lèdgèr) còvèrs whàt thè àùdìtòr sèès. [[#fàìlùrè-stàtès #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn còrrèct ònè? ••••••** Thè àùthòr càn còrrèct thèìr òwn. À hòldèr òf Mànàgè fùnds càn còrrèct ànòthèr ùsèr's dìsbùrsèmènt, ànd nò òthèr kìnd òf nòtè. Bòth pàths rèqùìrè Rècòrd dìsbùrsèmènts. Thè sèrvèr ènfòrcès thè àùthòr chèck ànd thè pèrmìssìòn chèck. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè ènvèlòpè ìnsìdè thè nòtè. •••••••••** À dìsbùrsèmènt nòtè bègìns wìth à màrkèr chàràctèr thàt dìstìngùìshès ìt fròm frèè-tèxt nòtès. Àftèr thè màrkèr, à JSÒN ènvèlòpè hòlds thè lèdgèr èntry ìd, thè fùnd ìd, thè àmòùnt ìn mìnòr ùnìts, thè cùrrèncy, ànd thè nòtè tèxt. Thè rèndèrèr chècks thè màrkèr àftèr dècryptìòn ànd prèsènts thè àmòùnt ànd fùnd nàmè. Wìthòùt Vìèw fùnds, thè fùnd nàmè ìs òmìttèd. [[#èncryptìòn #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè shèèt ànd thè bàlàncè rètry. ••••••••••** \`DìsbùrsèmèntShèèt.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/tìckèts/\` èncrypts thè lèdgèr pàylòàd ùndèr thè òrgànìzàtìòn kèy ànd thè nòtè ùndèr thè tìckèt kèy. Òn à stàlè-bàlàncè èrròr, \`wrìtèWìthBàlàncè\` ìn \`pàckàgès/clìènt/src/lìb/fùnds/fùnd-stòrè.svèltè.ts\` rèfètchès thè fùnd lìst, rèbùìlds thè nèxt bàlàncè fròm thè frèsh fìgùrè, ànd rètrìès òncè bèfòrè shòwìng àn èrròr. [Fùnd bàlàncès](#tìckèt-dètàìl/fùnd-bàlàncè) còvèrs thè shàrèd bàlàncè càchè. [[#fàìlùrè-stàtès #clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Recording a disbursement is a compose action gated on the Record disbursements and View funds permissions together, and available only when the case's queue ..." |
*
* @param {Demo_Narrative_Topic_Disbursement_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_disbursement_body = /** @type {((inputs?: Demo_Narrative_Topic_Disbursement_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Disbursement_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_disbursement_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_disbursement_body(inputs)
	return en_demo_narrative_topic_disbursement_body(inputs)
});