/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Org_Deletion_BodyInputs */

const en_demo_narrative_admin_org_deletion_body = /** @type {(inputs: Demo_Narrative_Admin_Org_Deletion_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A user with the Request org deletion permission can request that the organization and all of its data be permanently erased. The request requires typing the organization's address as confirmation. A 30-day waiting period begins at the time of the request, and any holder of the same permission can cancel it while that period is open. Every holder of the permission is notified when a request is submitted and when one is cancelled, so a request from a compromised account is visible to the others while it can still be stopped. The notification names the event, not the person who acted. [[#retention #permissions]]
**What happens after the waiting period?** A daily automated job on the host processes requests whose waiting period has ended. Before erasing anything, the job stores a per-organization backup snapshot. No request proceeds without a stored snapshot. [[#retention]]
**What does erasure remove?** Erasure deletes the organization's cases, messages, files, accounts, configuration and encryption keys from the running system. A backup snapshot taken before the erasure stays in the backup repository for the backup retention window. Under the default policy that window is six months, so the operator can restore a deleted organization within that period. After the window closes, the backup is pruned and the data is unrecoverable. [Data retention](#deep-dive/data-retention) covers the backup retention policy. [[#retention #server-holds]]
**Who performs the erasure?** The organization requests deletion through the application. The erasure itself runs as a host-level process under the database owner role, which the application's runtime role cannot use. Only the operator of the deployment can run, defer or override an erasure. [[#permissions #server-holds]]
**Audit trail.** Requesting and cancelling a deletion are recorded in the [audit log](#admin-logs/audit). The erasure job writes a platform-level audit row when it finishes. [[#permissions]]
**The request table and the erasure service.** \`packages/server/src/db/migrations/platform/011_create_deletion_requests.ts\` creates \`deletion_requests\` in the public schema, one row per request. The row carries the requesting user, the cooling-off deadline, step-level timestamps, and a status that moves from pending through processing to done. A partial unique index allows one live request per organization. \`packages/server/src/org/deletion-request-service.ts\` handles submit, cancel and status on the runtime pool. \`packages/server/src/org/erasure-service.ts\` runs the erasure on the owner-role pool. The sequence claims the row, waits for the snapshot, sweeps blobs, drops the schema, deletes platform rows, closes the managed telephony subaccount, and writes the audit row. An advisory lock prevents two runs from overlapping. Each step records a timestamp on the request row so a failed run resumes from the first incomplete step. \`deploy/db/org-erase.sh\` orchestrates the host side, calling \`backup-org.sh\` for the snapshot and the CLI for each step. [[#server-holds]]`)
};

const es_demo_narrative_admin_org_deletion_body = /** @type {(inputs: Demo_Narrative_Admin_Org_Deletion_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La persona usuaria con el permiso Request org deletion puede solicitar que la organización y todos sus datos se eliminen de forma permanente. La solicitud requiere escribir la dirección de la organización como confirmación. Un período de espera de 30 días comienza en el momento de la solicitud, y cualquier titular del mismo permiso puede cancelarla mientras ese período esté abierto. Cada titular del permiso recibe una notificación cuando se envía una solicitud y cuando se cancela, de modo que una solicitud desde una cuenta comprometida sea visible para los demás mientras aún pueda detenerse. La notificación nombra el evento, no a la persona que actuó. [[#retention #permissions]]
**¿Qué ocurre después del período de espera?** Un trabajo automatizado diario en el servidor procesa las solicitudes cuyo período de espera ha vencido. Antes de eliminar nada, el trabajo almacena una copia de seguridad específica de la organización. Ninguna solicitud avanza sin una copia almacenada. [[#retention]]
**¿Qué elimina el borrado?** El borrado elimina los casos, mensajes, archivos, cuentas, configuración y claves de cifrado de la organización del sistema en producción. Una copia de seguridad tomada antes del borrado permanece en el repositorio de copias durante la ventana de retención de copias. Con la política predeterminada esa ventana es de seis meses, por lo que el operador puede restaurar una organización eliminada dentro de ese período. Después de que la ventana se cierra, la copia se descarta y los datos son irrecuperables. [Retención de datos](#deep-dive/data-retention) trata la política de retención de copias de seguridad. [[#retention #server-holds]]
**¿Quién ejecuta el borrado?** La organización solicita la eliminación a través de la aplicación. El borrado en sí se ejecuta como un proceso a nivel de servidor bajo el rol propietario de la base de datos, que el rol de ejecución de la aplicación no puede usar. Solo el operador del despliegue puede ejecutar, aplazar o anular un borrado. [[#permissions #server-holds]]
**Registro de auditoría.** La solicitud y la cancelación de una eliminación se registran en el [registro de auditoría](#admin-logs/audit). El trabajo de eliminación escribe una entrada de auditoría a nivel de plataforma cuando finaliza. [[#permissions]]
**La tabla de solicitudes y el servicio de borrado.** \`packages/server/src/db/migrations/platform/011_create_deletion_requests.ts\` crea \`deletion_requests\` en el esquema público, una fila por solicitud. La fila contiene la persona solicitante, la fecha límite del período de espera, marcas de tiempo por paso y un estado que avanza de pendiente a en proceso y luego a completado. Un índice parcial único permite una sola solicitud activa por organización. \`packages/server/src/org/deletion-request-service.ts\` gestiona el envío, la cancelación y la consulta de estado en el pool de ejecución. \`packages/server/src/org/erasure-service.ts\` ejecuta el borrado en el pool del rol propietario. La secuencia reclama la fila, espera la copia de seguridad, elimina los blobs, descarta el esquema, borra las filas de plataforma, cierra la subcuenta de telefonía gestionada y escribe la entrada de auditoría. Un bloqueo consultivo impide que dos ejecuciones se superpongan. Cada paso registra una marca de tiempo en la fila de la solicitud para que una ejecución fallida se reanude desde el primer paso incompleto. \`deploy/db/org-erase.sh\` orquesta el lado del servidor, invocando \`backup-org.sh\` para la copia y el CLI para cada paso. [[#server-holds]]`)
};

const en_xa2_demo_narrative_admin_org_deletion_body = /** @type {(inputs: Demo_Narrative_Admin_Org_Deletion_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À ùsèr wìth thè Rèqùèst òrg dèlètìòn pèrmìssìòn càn rèqùèst thàt thè òrgànìzàtìòn ànd àll òf ìts dàtà bè pèrmànèntly èràsèd. Thè rèqùèst rèqùìrès typìng thè òrgànìzàtìòn's àddrèss às cònfìrmàtìòn. À 30-dày wàìtìng pèrìòd bègìns àt thè tìmè òf thè rèqùèst, ànd àny hòldèr òf thè sàmè pèrmìssìòn càn càncèl ìt whìlè thàt pèrìòd ìs òpèn. Èvèry hòldèr òf thè pèrmìssìòn ìs nòtìfìèd whèn à rèqùèst ìs sùbmìttèd ànd whèn ònè ìs càncèllèd, sò à rèqùèst fròm à còmpròmìsèd àccòùnt ìs vìsìblè tò thè òthèrs whìlè ìt càn stìll bè stòppèd. Thè nòtìfìcàtìòn nàmès thè èvènt, nòt thè pèrsòn whò àctèd. [[#rètèntìòn #pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns àftèr thè wàìtìng pèrìòd? ••••••••••••** À dàìly àùtòmàtèd jòb òn thè hòst pròcèssès rèqùèsts whòsè wàìtìng pèrìòd hàs èndèd. Bèfòrè èràsìng ànythìng, thè jòb stòrès à pèr-òrgànìzàtìòn bàckùp snàpshòt. Nò rèqùèst pròcèèds wìthòùt à stòrèd snàpshòt. [[#rètèntìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès èràsùrè rèmòvè? ••••••••** Èràsùrè dèlètès thè òrgànìzàtìòn's càsès, mèssàgès, fìlès, àccòùnts, cònfìgùràtìòn ànd èncryptìòn kèys fròm thè rùnnìng systèm. À bàckùp snàpshòt tàkèn bèfòrè thè èràsùrè stàys ìn thè bàckùp rèpòsìtòry fòr thè bàckùp rètèntìòn wìndòw. Ùndèr thè dèfàùlt pòlìcy thàt wìndòw ìs sìx mònths, sò thè òpèràtòr càn rèstòrè à dèlètèd òrgànìzàtìòn wìthìn thàt pèrìòd. Àftèr thè wìndòw clòsès, thè bàckùp ìs prùnèd ànd thè dàtà ìs ùnrècòvèràblè. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thè bàckùp rètèntìòn pòlìcy. [[#rètèntìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò pèrfòrms thè èràsùrè? ••••••••** Thè òrgànìzàtìòn rèqùèsts dèlètìòn thròùgh thè àpplìcàtìòn. Thè èràsùrè ìtsèlf rùns às à hòst-lèvèl pròcèss ùndèr thè dàtàbàsè òwnèr ròlè, whìch thè àpplìcàtìòn's rùntìmè ròlè cànnòt ùsè. Ònly thè òpèràtòr òf thè dèplòymènt càn rùn, dèfèr òr òvèrrìdè àn èràsùrè. [[#pèrmìssìòns #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àùdìt tràìl. ••••** Rèqùèstìng ànd càncèllìng à dèlètìòn àrè rècòrdèd ìn thè [àùdìt lòg](#àdmìn-lògs/àùdìt). Thè èràsùrè jòb wrìtès à plàtfòrm-lèvèl àùdìt ròw whèn ìt fìnìshès. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rèqùèst tàblè ànd thè èràsùrè sèrvìcè. •••••••••••••** \`pàckàgès/sèrvèr/src/db/mìgràtìòns/plàtfòrm/011_crèàtè_dèlètìòn_rèqùèsts.ts\` crèàtès \`dèlètìòn_rèqùèsts\` ìn thè pùblìc schèmà, ònè ròw pèr rèqùèst. Thè ròw càrrìès thè rèqùèstìng ùsèr, thè còòlìng-òff dèàdlìnè, stèp-lèvèl tìmèstàmps, ànd à stàtùs thàt mòvès fròm pèndìng thròùgh pròcèssìng tò dònè. À pàrtìàl ùnìqùè ìndèx àllòws ònè lìvè rèqùèst pèr òrgànìzàtìòn. \`pàckàgès/sèrvèr/src/òrg/dèlètìòn-rèqùèst-sèrvìcè.ts\` hàndlès sùbmìt, càncèl ànd stàtùs òn thè rùntìmè pòòl. \`pàckàgès/sèrvèr/src/òrg/èràsùrè-sèrvìcè.ts\` rùns thè èràsùrè òn thè òwnèr-ròlè pòòl. Thè sèqùèncè clàìms thè ròw, wàìts fòr thè snàpshòt, swèèps blòbs, dròps thè schèmà, dèlètès plàtfòrm ròws, clòsès thè mànàgèd tèlèphòny sùbàccòùnt, ànd wrìtès thè àùdìt ròw. Àn àdvìsòry lòck prèvènts twò rùns fròm òvèrlàppìng. Èàch stèp rècòrds à tìmèstàmp òn thè rèqùèst ròw sò à fàìlèd rùn rèsùmès fròm thè fìrst ìncòmplètè stèp. \`dèplòy/db/òrg-èràsè.sh\` òrchèstràtès thè hòst sìdè, càllìng \`bàckùp-òrg.sh\` fòr thè snàpshòt ànd thè CLÌ fòr èàch stèp. [[#sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A user with the Request org deletion permission can request that the organization and all of its data be permanently erased. The request requires typing the ..." |
*
* @param {Demo_Narrative_Admin_Org_Deletion_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_org_deletion_body = /** @type {((inputs?: Demo_Narrative_Admin_Org_Deletion_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Org_Deletion_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_org_deletion_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_org_deletion_body(inputs)
	return en_demo_narrative_admin_org_deletion_body(inputs)
});