/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Data_Retention_BodyInputs */

const en_demo_narrative_deepdive_data_retention_body = /** @type {(inputs: Demo_Narrative_Deepdive_Data_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Data an organization no longer needs can still be taken from it. For a population targeted by a state-level adversary, a case record from three years ago remains a live risk to a person who may have moved, changed names, or gone quiet. Encryption protects what is stored; retention decides whether it is stored at all. The two are different defenses and an organization needs both. [[#retention #privacy]]
Automatic deletion is off until an administrator turns it on, and turning it on means choosing a window between 1 and 3,650 days. A daily job hard-deletes every closed case whose last activity is older than that window, removing its stored files before its rows and asking the telephony provider to delete its own call and message logs for it. A client record, together with its contact, portal channel and account rows, goes only when the last case for that client goes, so a client with an open or a recent case is untouched, and an organization that has never set a window is skipped. Both enabling the policy and changing the number ask for confirmation, and the confirmation says plainly that deleted data cannot be recovered even from the escrow file, because escrow protects keys and not rows. With the policy off, everything is kept until someone deletes it by hand. [[#retention]]
The policy is one setting for the whole organization rather than a choice per queue or per case type, and the reasoning is that a per-queue window is a decision someone has to remember correctly on the day they create a queue. Audit entries are exempt, so the record that something happened outlives the content of what happened. Configuring the policy requires the Manage retention permission, which sits with Admin by default and can be moved. [The permission system](#deep-dive/the-permission-system) covers how that moves. [[#retention #permissions]]
Retention cannot delete what a third party holds. It also cannot delete a copy a client kept on their own phone, and for clients on a monitored device that copy is often the more dangerous one, which is why the client-facing surfaces carry a quick exit and why the encrypted channels avoid third parties in the first place. And deletion only runs one way; nothing the policy removes can be restored. [[#retention #failure-states]]
**Separate lifetimes already running.** Three other clocks delete data independently of the organization-wide window. [[#retention #portal #telephony]]
- Portal message copies on the client side are deleted after 30 days of channel inactivity, measured from the later of the last-seen and created timestamps, and that sweep removes portal messages, portal attachments and portal recordings while leaving the organization's own record intact. [[#retention #portal]]
- One-time share links expire 72 hours after creation or on first read, whichever comes first, and the ciphertext column is cleared at read time while the row survives as a tombstone until an expiry sweep removes it. [[#retention #portal]]
- Telephony logs are deleted at the provider, because CARE-Y asks the provider to delete each call, message or recording log after processing, with retries when the request fails. [[#retention #telephony]]
**What survives a deletion.** A deletion removes content while structural traces remain. [[#retention #metadata #server-holds]]
- Audit rows are outside the purge, because the case reference on an audit row is a soft reference with no foreign key, so the event type, actor id, case id and timestamp outlive the case they describe. [[#retention #metadata]]
- Foreign key relationships and row counts remain readable in the tables that are left. [[#retention #metadata]]
- A deleted case removes its own ciphertext and its key wraps, and a key wrap without its case is not recoverable. [[#retention #encryption]]
- A note deleted from a case thread is marked deleted rather than removed, and its ciphertext stays in the row until the whole case is purged. The sweep that hard-deletes soft-deleted rows covers recordings and attachments only. [[#retention #failure-states]]
- Escrow holds key material rather than data, so no escrow ceremony brings back a deleted row. [[#retention #keys]]
**Contributor pointers.** The setting and the sweeps live apart from each other. [[#retention]]
- The organization-wide window is \`org_config.pii_retention_days\`, an integer column from \`packages/server/src/db/migrations/tenant/003_create_org_config.ts\`, written through \`setPiiRetentionDays\` in \`packages/server/src/auth/service.ts\` behind a permission-gated tRPC procedure in \`packages/server/src/routes/auth.ts\`, and read back for display through the hub status query. [[#retention #permissions]]
- The purge itself is \`packages/server/src/jobs/pii-retention.ts\`, which exports \`purgeTicket\` and \`purgeClient\` so manual deletion runs the same cascade. [[#retention]]
- The independent sweeps live in \`packages/server/src/jobs/\`, where \`portal-message-expiry.ts\` handles the 30-day portal window across tenant schemas and \`log-deletion.ts\` dispatches provider log deletions with backoff. [[#retention #portal #telephony]]
- Share link expiry logic is in \`packages/server/src/portal/share-service.ts\`. [[#retention #portal]]`)
};

const es_demo_narrative_deepdive_data_retention_body = /** @type {(inputs: Demo_Narrative_Deepdive_Data_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los datos que una organización ya no necesita todavía se le pueden arrebatar. Para una población perseguida por un adversario con recursos de un estado, un expediente de caso de hace tres años sigue siendo un riesgo vivo para una persona que puede haberse mudado, haber cambiado de nombre o haber callado. El cifrado protege lo que está almacenado; la retención decide si se almacena en absoluto. Son dos defensas distintas y una organización necesita las dos. [[#retention #privacy]]
La eliminación automática está apagada hasta que una persona administradora la enciende, y encenderla implica elegir una ventana de entre 1 y 3.650 días. Un trabajo diario elimina de forma definitiva cada caso cerrado cuya última actividad sea más antigua que esa ventana, retirando sus archivos almacenados antes que sus filas y pidiendo al proveedor de telefonía que elimine sus propios registros de llamadas y mensajes de ese caso. El registro de un cliente, junto con sus filas de contacto, de canal del portal y de cuenta, se va solo cuando se va el último caso de ese cliente, así que un cliente con un caso abierto o reciente queda intacto, y una organización que nunca ha fijado una ventana se omite. Tanto activar la política como cambiar el número piden confirmación, y la confirmación dice con claridad que los datos eliminados no se pueden recuperar ni desde el archivo de custodia, porque la custodia protege claves y no filas. Con la política apagada, todo se conserva hasta que alguien lo elimina a mano. [[#retention]]
La política es un único ajuste para toda la organización y no una elección por cola o por tipo de caso, y el razonamiento es que una ventana por cola es una decisión que alguien tiene que recordar correctamente el día en que crea una cola. Las entradas de auditoría están exentas, así que el registro de que algo ocurrió sobrevive al contenido de lo que ocurrió. Configurar la política requiere el permiso Definir cuánto tiempo se conservan los datos, que está con Administrador de forma predeterminada y se puede mover. [El sistema de permisos](#deep-dive/the-permission-system) explica cómo se mueve. [[#retention #permissions]]
La retención no puede eliminar lo que tiene una tercera parte. Tampoco puede eliminar una copia que un cliente guardó en su propio teléfono, y para los clientes con un dispositivo vigilado esa copia es a menudo la más peligrosa, y por eso las superficies de cara al cliente llevan una salida rápida y por eso los canales cifrados evitan a las terceras partes desde el principio. Y la eliminación corre en un solo sentido; nada de lo que la política quita se puede restaurar. [[#retention #failure-states]]
**Vidas separadas que ya corren.** Otros tres relojes eliminan datos con independencia de la ventana de toda la organización. [[#retention #portal #telephony]]
- Las copias de mensajes del portal del lado del cliente se eliminan tras 30 días de inactividad del canal, medidos desde la más tardía de las marcas de última vista y de creación, y ese barrido retira los mensajes del portal, los adjuntos del portal y las grabaciones del portal mientras deja intacto el registro propio de la organización. [[#retention #portal]]
- Los enlaces de compartición de un solo uso caducan 72 horas después de su creación o en la primera lectura, lo que ocurra primero, y la columna de texto cifrado se vacía en el momento de la lectura mientras la fila sobrevive como lápida hasta que un barrido de caducidad la retira. [[#retention #portal]]
- Los registros de telefonía se eliminan en el proveedor, porque CARE-Y pide al proveedor que elimine cada registro de llamada, mensaje o grabación después de procesarlo, con reintentos cuando la solicitud falla. [[#retention #telephony]]
**Qué sobrevive a una eliminación.** Una eliminación retira el contenido mientras quedan rastros estructurales. [[#retention #metadata #server-holds]]
- Las filas de auditoría quedan fuera de la purga, porque la referencia al caso en una fila de auditoría es una referencia blanda sin clave externa, así que el tipo de evento, el identificador del actor, el identificador del caso y la marca de tiempo sobreviven al caso que describen. [[#retention #metadata]]
- Las relaciones de claves externas y el número de filas siguen siendo legibles en las tablas que quedan. [[#retention #metadata]]
- Un caso eliminado retira su propio texto cifrado y sus envolturas de clave, y una envoltura de clave sin su caso no es recuperable. [[#retention #encryption]]
- Una nota eliminada de un hilo de caso queda marcada como eliminada y no retirada, y su texto cifrado permanece en la fila hasta que se purga el caso entero. El barrido que elimina de forma definitiva las filas marcadas cubre solo las grabaciones y los adjuntos. [[#retention #failure-states]]
- La custodia guarda material de claves y no datos, así que ninguna ceremonia de custodia devuelve una fila eliminada. [[#retention #keys]]
**Indicaciones para quien contribuye.** El ajuste y los barridos viven separados entre sí. [[#retention]]
- La ventana de toda la organización es \`org_config.pii_retention_days\`, una columna entera de \`packages/server/src/db/migrations/tenant/003_create_org_config.ts\`, escrita mediante \`setPiiRetentionDays\` en \`packages/server/src/auth/service.ts\` detrás de un procedimiento tRPC protegido por permiso en \`packages/server/src/routes/auth.ts\`, y leída de vuelta para mostrarla mediante la consulta de estado del hub. [[#retention #permissions]]
- La purga en sí es \`packages/server/src/jobs/pii-retention.ts\`, que exporta \`purgeTicket\` y \`purgeClient\` para que la eliminación manual recorra la misma cascada. [[#retention]]
- Los barridos independientes viven en \`packages/server/src/jobs/\`, donde \`portal-message-expiry.ts\` se encarga de la ventana de 30 días del portal en todos los esquemas de inquilino y \`log-deletion.ts\` despacha las eliminaciones de registros del proveedor con reintentos escalonados. [[#retention #portal #telephony]]
- La lógica de caducidad de los enlaces de compartición está en \`packages/server/src/portal/share-service.ts\`. [[#retention #portal]]`)
};

const en_xa2_demo_narrative_deepdive_data_retention_body = /** @type {(inputs: Demo_Narrative_Deepdive_Data_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Dàtà àn òrgànìzàtìòn nò lòngèr nèèds càn stìll bè tàkèn fròm ìt. Fòr à pòpùlàtìòn tàrgètèd by à stàtè-lèvèl àdvèrsàry, à càsè rècòrd fròm thrèè yèàrs àgò rèmàìns à lìvè rìsk tò à pèrsòn whò mày hàvè mòvèd, chàngèd nàmès, òr gònè qùìèt. Èncryptìòn pròtècts whàt ìs stòrèd; rètèntìòn dècìdès whèthèr ìt ìs stòrèd àt àll. Thè twò àrè dìffèrènt dèfènsès ànd àn òrgànìzàtìòn nèèds bòth. [[#rètèntìòn #prìvàcy]]
Àùtòmàtìc dèlètìòn ìs òff ùntìl àn àdmìnìstràtòr tùrns ìt òn, ànd tùrnìng ìt òn mèàns chòòsìng à wìndòw bètwèèn 1 ànd 3,650 dàys. À dàìly jòb hàrd-dèlètès èvèry clòsèd càsè whòsè làst àctìvìty ìs òldèr thàn thàt wìndòw, rèmòvìng ìts stòrèd fìlès bèfòrè ìts ròws ànd àskìng thè tèlèphòny pròvìdèr tò dèlètè ìts òwn càll ànd mèssàgè lògs fòr ìt. À clìènt rècòrd, tògèthèr wìth ìts còntàct, pòrtàl chànnèl ànd àccòùnt ròws, gòès ònly whèn thè làst càsè fòr thàt clìènt gòès, sò à clìènt wìth àn òpèn òr à rècènt càsè ìs ùntòùchèd, ànd àn òrgànìzàtìòn thàt hàs nèvèr sèt à wìndòw ìs skìppèd. Bòth ènàblìng thè pòlìcy ànd chàngìng thè nùmbèr àsk fòr cònfìrmàtìòn, ànd thè cònfìrmàtìòn sàys plàìnly thàt dèlètèd dàtà cànnòt bè rècòvèrèd èvèn fròm thè èscròw fìlè, bècàùsè èscròw pròtècts kèys ànd nòt ròws. Wìth thè pòlìcy òff, èvèrythìng ìs kèpt ùntìl sòmèònè dèlètès ìt by hànd. [[#rètèntìòn]]
Thè pòlìcy ìs ònè sèttìng fòr thè whòlè òrgànìzàtìòn ràthèr thàn à chòìcè pèr qùèùè òr pèr càsè typè, ànd thè rèàsònìng ìs thàt à pèr-qùèùè wìndòw ìs à dècìsìòn sòmèònè hàs tò rèmèmbèr còrrèctly òn thè dày thèy crèàtè à qùèùè. Àùdìt èntrìès àrè èxèmpt, sò thè rècòrd thàt sòmèthìng hàppènèd òùtlìvès thè còntènt òf whàt hàppènèd. Cònfìgùrìng thè pòlìcy rèqùìrès thè Mànàgè rètèntìòn pèrmìssìòn, whìch sìts wìth Àdmìn by dèfàùlt ànd càn bè mòvèd. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw thàt mòvès. [[#rètèntìòn #pèrmìssìòns]]
Rètèntìòn cànnòt dèlètè whàt à thìrd pàrty hòlds. Ìt àlsò cànnòt dèlètè à còpy à clìènt kèpt òn thèìr òwn phònè, ànd fòr clìènts òn à mònìtòrèd dèvìcè thàt còpy ìs òftèn thè mòrè dàngèròùs ònè, whìch ìs why thè clìènt-fàcìng sùrfàcès càrry à qùìck èxìt ànd why thè èncryptèd chànnèls àvòìd thìrd pàrtìès ìn thè fìrst plàcè. Ànd dèlètìòn ònly rùns ònè wày; nòthìng thè pòlìcy rèmòvès càn bè rèstòrèd. [[#rètèntìòn #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèpàràtè lìfètìmès àlrèàdy rùnnìng. •••••••••••** Thrèè òthèr clòcks dèlètè dàtà ìndèpèndèntly òf thè òrgànìzàtìòn-wìdè wìndòw. [[#rètèntìòn #pòrtàl #tèlèphòny]]
- Pòrtàl mèssàgè còpìès òn thè clìènt sìdè àrè dèlètèd àftèr 30 dàys òf chànnèl ìnàctìvìty, mèàsùrèd fròm thè làtèr òf thè làst-sèèn ànd crèàtèd tìmèstàmps, ànd thàt swèèp rèmòvès pòrtàl mèssàgès, pòrtàl àttàchmènts ànd pòrtàl rècòrdìngs whìlè lèàvìng thè òrgànìzàtìòn's òwn rècòrd ìntàct. [[#rètèntìòn #pòrtàl]]
- Ònè-tìmè shàrè lìnks èxpìrè 72 hòùrs àftèr crèàtìòn òr òn fìrst rèàd, whìchèvèr còmès fìrst, ànd thè cìphèrtèxt còlùmn ìs clèàrèd àt rèàd tìmè whìlè thè ròw sùrvìvès às à tòmbstònè ùntìl àn èxpìry swèèp rèmòvès ìt. [[#rètèntìòn #pòrtàl]]
- Tèlèphòny lògs àrè dèlètèd àt thè pròvìdèr, bècàùsè CÀRÈ-Y àsks thè pròvìdèr tò dèlètè èàch càll, mèssàgè òr rècòrdìng lòg àftèr pròcèssìng, wìth rètrìès whèn thè rèqùèst fàìls. [[#rètèntìòn #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt sùrvìvès à dèlètìòn. ••••••••** À dèlètìòn rèmòvès còntènt whìlè strùctùràl tràcès rèmàìn. [[#rètèntìòn #mètàdàtà #sèrvèr-hòlds]]
- Àùdìt ròws àrè òùtsìdè thè pùrgè, bècàùsè thè càsè rèfèrèncè òn àn àùdìt ròw ìs à sòft rèfèrèncè wìth nò fòrèìgn kèy, sò thè èvènt typè, àctòr ìd, càsè ìd ànd tìmèstàmp òùtlìvè thè càsè thèy dèscrìbè. [[#rètèntìòn #mètàdàtà]]
- Fòrèìgn kèy rèlàtìònshìps ànd ròw còùnts rèmàìn rèàdàblè ìn thè tàblès thàt àrè lèft. [[#rètèntìòn #mètàdàtà]]
- À dèlètèd càsè rèmòvès ìts òwn cìphèrtèxt ànd ìts kèy wràps, ànd à kèy wràp wìthòùt ìts càsè ìs nòt rècòvèràblè. [[#rètèntìòn #èncryptìòn]]
- À nòtè dèlètèd fròm à càsè thrèàd ìs màrkèd dèlètèd ràthèr thàn rèmòvèd, ànd ìts cìphèrtèxt stàys ìn thè ròw ùntìl thè whòlè càsè ìs pùrgèd. Thè swèèp thàt hàrd-dèlètès sòft-dèlètèd ròws còvèrs rècòrdìngs ànd àttàchmènts ònly. [[#rètèntìòn #fàìlùrè-stàtès]]
- Èscròw hòlds kèy màtèrìàl ràthèr thàn dàtà, sò nò èscròw cèrèmòny brìngs bàck à dèlètèd ròw. [[#rètèntìòn #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Còntrìbùtòr pòìntèrs. •••••••** Thè sèttìng ànd thè swèèps lìvè àpàrt fròm èàch òthèr. [[#rètèntìòn]]
- Thè òrgànìzàtìòn-wìdè wìndòw ìs \`òrg_cònfìg.pìì_rètèntìòn_dàys\`, àn ìntègèr còlùmn fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/003_crèàtè_òrg_cònfìg.ts\`, wrìttèn thròùgh \`sètPììRètèntìònDàys\` ìn \`pàckàgès/sèrvèr/src/àùth/sèrvìcè.ts\` bèhìnd à pèrmìssìòn-gàtèd tRPC pròcèdùrè ìn \`pàckàgès/sèrvèr/src/ròùtès/àùth.ts\`, ànd rèàd bàck fòr dìsplày thròùgh thè hùb stàtùs qùèry. [[#rètèntìòn #pèrmìssìòns]]
- Thè pùrgè ìtsèlf ìs \`pàckàgès/sèrvèr/src/jòbs/pìì-rètèntìòn.ts\`, whìch èxpòrts \`pùrgèTìckèt\` ànd \`pùrgèClìènt\` sò mànùàl dèlètìòn rùns thè sàmè càscàdè. [[#rètèntìòn]]
- Thè ìndèpèndènt swèèps lìvè ìn \`pàckàgès/sèrvèr/src/jòbs/\`, whèrè \`pòrtàl-mèssàgè-èxpìry.ts\` hàndlès thè 30-dày pòrtàl wìndòw àcròss tènànt schèmàs ànd \`lòg-dèlètìòn.ts\` dìspàtchès pròvìdèr lòg dèlètìòns wìth bàckòff. [[#rètèntìòn #pòrtàl #tèlèphòny]]
- Shàrè lìnk èxpìry lògìc ìs ìn \`pàckàgès/sèrvèr/src/pòrtàl/shàrè-sèrvìcè.ts\`. [[#rètèntìòn #pòrtàl]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Data an organization no longer needs can still be taken from it. For a population targeted by a state-level adversary, a case record from three years ago rem..." |
*
* @param {Demo_Narrative_Deepdive_Data_Retention_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_data_retention_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Data_Retention_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Data_Retention_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_data_retention_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_data_retention_body(inputs)
	return en_demo_narrative_deepdive_data_retention_body(inputs)
});