/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Fund_Encryption_BodyInputs */

const en_demo_narrative_topic_fund_encryption_body = /** @type {(inputs: Demo_Narrative_Topic_Fund_Encryption_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Fund names, amounts, currency codes, entry types, and who recorded each entry are inside encrypted payloads that the server stores and cannot open. The server holds the number of funds, the number of ledger rows, each entry's calendar date at day granularity, the fund notification toggle, and the sealed balance version counter. [[#server-holds #encryption]]
**What links a disbursement to a case?** The link exists only inside the case note's encrypted content, which is sealed under the ticket key. The server sees the ticket id and the ledger entry id together for the length of the recording request and does not store the pairing. A database dump shows that a case has an internal note and that a ledger entry exists on the same day, but it cannot pair them. [[#encryption #server-holds #privacy]]
**What does the ledger row expose?** Each ledger row is one ciphertext column and a calendar date. The row carries no fund id, no user id, no amount, and no entry type in plaintext. The fund id, amount, entry type, recording time, and recording user live inside the encrypted payload. A database dump reveals the total number of entries and their dates, which shows how often the organization moves money but not how much or to whom. [[#server-holds #metadata]]
**How is the balance protected?** Each fund's running balance is a second sealed column on the fund row, encrypted with the organization key. The server applies a new sealed balance only when the version counter matches the one the browser read, preventing two concurrent writes from building on the same starting balance. The version counter is the only plaintext the balance write changes. [[#encryption #keys]]
**The queue fund link.** The column that maps a queue to a fund is sealed ciphertext, following the same pattern as the queue's encrypted color and encrypted icon. The server cannot read which fund a queue draws on. [[#server-holds #encryption]]
**Key rotation.** Fund payloads, sealed balances, and ledger payloads are registered with the organization key reseal service. A balance write carries the organization key generation it was sealed under, and when the fund row is behind the current generation, the browser reseals the fund payload in the same write and the server moves the row to that generation atomically. [Key management](#admin-org/keys) covers the rotation process. [[#keys #encryption]]
**The fund service and its transaction boundaries.** \`packages/server/src/funds/fund-service.ts\` runs the balance compare and set, the ledger insert, and the optional case note inside one database transaction. The transaction boundary is what makes a disbursement either fully written or fully absent. The notification to fund managers fires after commit, best effort, and names no case. [[#server-holds]]`)
};

const es_demo_narrative_topic_fund_encryption_body = /** @type {(inputs: Demo_Narrative_Topic_Fund_Encryption_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los nombres de fondos, los montos, los códigos de moneda, los tipos de entrada y quién registró cada entrada están dentro de cargas cifradas que el servidor almacena y no puede abrir. El servidor conserva el número de fondos, el número de filas del libro mayor, la fecha de calendario de cada entrada con granularidad diaria, el interruptor de notificaciones de fondos y el contador de versión del saldo sellado. [[#server-holds #encryption]]
**¿Qué vincula un desembolso con un caso?** El vínculo existe solo dentro del contenido cifrado de la nota del caso, sellado bajo la clave del ticket. El servidor ve el id del ticket y el id de la entrada del libro mayor juntos durante el tiempo de la solicitud de registro, y no almacena el emparejamiento. Un volcado de la base de datos muestra que un caso tiene una nota interna y que existe una entrada del libro mayor en el mismo día, pero no puede vincularlos. [[#encryption #server-holds #privacy]]
**¿Qué expone la fila del libro mayor?** Cada fila del libro mayor es una columna de texto cifrado y una fecha de calendario. La fila no lleva id de fondo, ni id de persona, ni monto, ni tipo de entrada en texto plano. El id del fondo, el monto, el tipo de entrada, la hora de registro y la persona que registró viven dentro de la carga cifrada. Un volcado de la base de datos revela el número total de entradas y sus fechas, lo que muestra con qué frecuencia la organización mueve dinero, pero no cuánto ni a quién. [[#server-holds #metadata]]
**¿Cómo se protege el saldo?** El saldo corriente de cada fondo es una segunda columna sellada en la fila del fondo, cifrada con la clave de la organización. El servidor aplica un nuevo saldo sellado solo cuando el contador de versión coincide con el que leyó el navegador, lo que impide que dos escrituras concurrentes se basen en el mismo saldo inicial. El contador de versión es el único texto plano que cambia la escritura del saldo. [[#encryption #keys]]
**El vínculo cola fondo.** La columna que asigna una cola a un fondo es texto cifrado sellado, siguiendo el mismo patrón que el color cifrado y el icono cifrado de la cola. El servidor no puede leer qué fondo usa una cola. [[#server-holds #encryption]]
**Rotación de claves.** Las cargas de fondos, los saldos sellados y las cargas del libro mayor están registrados en el servicio de resellado de la clave de organización. Una escritura de saldo lleva la generación de la clave de organización bajo la que fue sellada, y cuando la fila del fondo está detrás de la generación actual, el navegador resella la carga del fondo en la misma escritura y el servidor mueve la fila a esa generación de forma atómica. [Gestión de claves](#admin-org/keys) trata el proceso de rotación. [[#keys #encryption]]
**El servicio de fondos y sus fronteras transaccionales.** \`packages/server/src/funds/fund-service.ts\` ejecuta la comparación y escritura del saldo, la inserción en el libro mayor y la nota de caso opcional dentro de una única transacción de base de datos. La frontera transaccional es lo que hace que un desembolso quede completamente escrito o completamente ausente. La notificación a gestores de fondos se dispara tras el commit, con entrega de mejor esfuerzo, y no nombra caso alguno. [[#server-holds]]`)
};

const en_xa2_demo_narrative_topic_fund_encryption_body = /** @type {(inputs: Demo_Narrative_Topic_Fund_Encryption_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Fùnd nàmès, àmòùnts, cùrrèncy còdès, èntry typès, ànd whò rècòrdèd èàch èntry àrè ìnsìdè èncryptèd pàylòàds thàt thè sèrvèr stòrès ànd cànnòt òpèn. Thè sèrvèr hòlds thè nùmbèr òf fùnds, thè nùmbèr òf lèdgèr ròws, èàch èntry's càlèndàr dàtè àt dày grànùlàrìty, thè fùnd nòtìfìcàtìòn tògglè, ànd thè sèàlèd bàlàncè vèrsìòn còùntèr. [[#sèrvèr-hòlds #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt lìnks à dìsbùrsèmènt tò à càsè? •••••••••••** Thè lìnk èxìsts ònly ìnsìdè thè càsè nòtè's èncryptèd còntènt, whìch ìs sèàlèd ùndèr thè tìckèt kèy. Thè sèrvèr sèès thè tìckèt ìd ànd thè lèdgèr èntry ìd tògèthèr fòr thè lèngth òf thè rècòrdìng rèqùèst ànd dòès nòt stòrè thè pàìrìng. À dàtàbàsè dùmp shòws thàt à càsè hàs àn ìntèrnàl nòtè ànd thàt à lèdgèr èntry èxìsts òn thè sàmè dày, bùt ìt cànnòt pàìr thèm. [[#èncryptìòn #sèrvèr-hòlds #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè lèdgèr ròw èxpòsè? ••••••••••** Èàch lèdgèr ròw ìs ònè cìphèrtèxt còlùmn ànd à càlèndàr dàtè. Thè ròw càrrìès nò fùnd ìd, nò ùsèr ìd, nò àmòùnt, ànd nò èntry typè ìn plàìntèxt. Thè fùnd ìd, àmòùnt, èntry typè, rècòrdìng tìmè, ànd rècòrdìng ùsèr lìvè ìnsìdè thè èncryptèd pàylòàd. À dàtàbàsè dùmp rèvèàls thè tòtàl nùmbèr òf èntrìès ànd thèìr dàtès, whìch shòws hòw òftèn thè òrgànìzàtìòn mòvès mònèy bùt nòt hòw mùch òr tò whòm. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìs thè bàlàncè pròtèctèd? •••••••••** Èàch fùnd's rùnnìng bàlàncè ìs à sècònd sèàlèd còlùmn òn thè fùnd ròw, èncryptèd wìth thè òrgànìzàtìòn kèy. Thè sèrvèr àpplìès à nèw sèàlèd bàlàncè ònly whèn thè vèrsìòn còùntèr màtchès thè ònè thè bròwsèr rèàd, prèvèntìng twò còncùrrènt wrìtès fròm bùìldìng òn thè sàmè stàrtìng bàlàncè. Thè vèrsìòn còùntèr ìs thè ònly plàìntèxt thè bàlàncè wrìtè chàngès. [[#èncryptìòn #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè qùèùè fùnd lìnk. ••••••** Thè còlùmn thàt màps à qùèùè tò à fùnd ìs sèàlèd cìphèrtèxt, fòllòwìng thè sàmè pàttèrn às thè qùèùè's èncryptèd còlòr ànd èncryptèd ìcòn. Thè sèrvèr cànnòt rèàd whìch fùnd à qùèùè dràws òn. [[#sèrvèr-hòlds #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Kèy ròtàtìòn. ••••** Fùnd pàylòàds, sèàlèd bàlàncès, ànd lèdgèr pàylòàds àrè règìstèrèd wìth thè òrgànìzàtìòn kèy rèsèàl sèrvìcè. À bàlàncè wrìtè càrrìès thè òrgànìzàtìòn kèy gènèràtìòn ìt wàs sèàlèd ùndèr, ànd whèn thè fùnd ròw ìs bèhìnd thè cùrrènt gènèràtìòn, thè bròwsèr rèsèàls thè fùnd pàylòàd ìn thè sàmè wrìtè ànd thè sèrvèr mòvès thè ròw tò thàt gènèràtìòn àtòmìcàlly. [Kèy mànàgèmènt](#àdmìn-òrg/kèys) còvèrs thè ròtàtìòn pròcèss. [[#kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fùnd sèrvìcè ànd ìts trànsàctìòn bòùndàrìès. •••••••••••••••** \`pàckàgès/sèrvèr/src/fùnds/fùnd-sèrvìcè.ts\` rùns thè bàlàncè còmpàrè ànd sèt, thè lèdgèr ìnsèrt, ànd thè òptìònàl càsè nòtè ìnsìdè ònè dàtàbàsè trànsàctìòn. Thè trànsàctìòn bòùndàry ìs whàt màkès à dìsbùrsèmènt èìthèr fùlly wrìttèn òr fùlly àbsènt. Thè nòtìfìcàtìòn tò fùnd mànàgèrs fìrès àftèr còmmìt, bèst èffòrt, ànd nàmès nò càsè. [[#sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Fund names, amounts, currency codes, entry types, and who recorded each entry are inside encrypted payloads that the server stores and cannot open. The serve..." |
*
* @param {Demo_Narrative_Topic_Fund_Encryption_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_fund_encryption_body = /** @type {((inputs?: Demo_Narrative_Topic_Fund_Encryption_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Fund_Encryption_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_fund_encryption_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_fund_encryption_body(inputs)
	return en_demo_narrative_topic_fund_encryption_body(inputs)
});