/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Saved_Filters_BodyInputs */

const en_demo_narrative_topic_saved_filters_body = /** @type {(inputs: Demo_Narrative_Topic_Saved_Filters_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A saved filter keeps a combination of active filters under a name so the same combination can be applied again in one step. Every saved filter has a required name, a color, and an icon. The saved filters appear as chips, and selecting a chip applies that combination. A link can carry a saved filter's identifier so opening the link applies the filter. [Filters](#tickets/filters) covers what a filter combination can select. [[#client-data]]
**Private and shared.** A new saved filter is private. It lives only in the browser's storage on the device that created it, under the key \`care-y:saved-filters\`. No row exists for it and no request carries it. Sharing writes it to a row on the server. Every account with permission to view cases lists the organization's shared filters alongside the private ones as one list. A shared filter carries a share icon. Unsharing deletes the row and puts the filter back in the device's storage as a private filter with a new identifier. [[#privacy #server-holds]]
**What does the server hold?** The server stores the name and the filter state encrypted with the organization key. It stores the color, the icon, the account that owns it, the organization key generation it was sealed under, and the time it was created in plaintext. The server cannot open either encrypted field. A database dump shows how many shared filters an organization keeps and which account owns each one. It does not show what any filter is called or which queue, priority, assignee, or date window it selects. [How encryption works](#deep-dive/how-encryption-works) covers the organization key and its rotation. [[#encryption #server-holds #metadata]]
**Key rotation.** Both encrypted columns are enrolled in the organization key rotation. A shared filter the browser cannot decrypt during a rotation in flight is left out of the list rather than shown broken. A chip whose name has not decrypted yet shows a placeholder. Private filters' names are re-sealed in the browser when the organization key rotates. [[#encryption #keys]]
**Who can do what?** Listing the organization's shared filters requires the View cases permission, the same permission the ticket list requires. Sharing, unsharing, and deleting a shared filter are limited to the account that owns it. The server refuses all three from any other account. The list offers those three actions only on a filter the account owns. [The permission system](#deep-dive/the-permission-system) covers where permissions come from. [[#permissions]]
**What stays readable on the device?** A private filter's name and state are both sealed under the organization key. The device holds no readable filter data after the user signs out. A stored entry that does not match the expected shape is dropped when the list loads, and the rest still load. [[#privacy #client-data]]
**The filter store and the ownership check.** \`packages/client/src/lib/stores/saved-filters.svelte.ts\` keeps the private and shared sets and presents them as one list. The name re-seal on organization key rotation is \`packages/client/src/lib/stores/saved-filter-reseal.ts\`. The list and its actions are \`packages/client/src/lib/components/filters/SavedFilterList.svelte\`; the create sheet is \`packages/client/src/lib/components/filters/CreateSavedFilter.svelte\`. The server route is \`packages/server/src/routes/saved-filters.ts\` over \`packages/server/src/tickets/saved-filter-service.ts\`, where the ownership check lives. The table is tenant migration \`115_saved_filters.ts\`. [[#client-data]]`)
};

const es_demo_narrative_topic_saved_filters_body = /** @type {(inputs: Demo_Narrative_Topic_Saved_Filters_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un filtro guardado conserva una combinación de filtros activos con un nombre para poder volver a aplicar la misma combinación en un solo paso. Cada filtro guardado tiene un nombre obligatorio, un color y un icono. Los filtros guardados aparecen como chips, y seleccionar un chip aplica esa combinación. Un enlace puede llevar el identificador de un filtro guardado para que al abrirlo se aplique el filtro. [Filtros](#tickets/filters) trata lo que puede seleccionar una combinación de filtros. [[#client-data]]
**Privado y compartido.** Un filtro guardado nuevo es privado. Vive solo en el almacenamiento del navegador del dispositivo que lo creó, bajo la clave \`care-y:saved-filters\`. No existe ninguna fila para él y ninguna petición lo transporta. Compartirlo lo escribe en una fila del servidor. Todas las cuentas con permiso para ver casos enumeran los filtros compartidos de la organización junto con los privados como una sola lista. Un filtro compartido lleva un icono de compartir. Dejar de compartirlo borra la fila y devuelve el filtro al almacenamiento del dispositivo como filtro privado con un identificador nuevo. [[#privacy #server-holds]]
**¿Qué guarda el servidor?** El servidor almacena el nombre y el estado del filtro cifrados con la clave de la organización. Almacena el color, el icono, la cuenta propietaria, la generación de clave de la organización bajo la que se selló y la fecha de creación en texto plano. El servidor no puede abrir ninguno de los dos campos cifrados. Un volcado de la base de datos muestra cuántos filtros compartidos conserva una organización y qué cuenta posee cada uno. No muestra cómo se llama ningún filtro ni qué cola, prioridad, persona asignada o ventana de fechas selecciona. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la clave de la organización y su rotación. [[#encryption #server-holds #metadata]]
**Rotación de claves.** Las dos columnas cifradas están inscritas en la rotación de la clave de la organización. Un filtro compartido que el navegador no pueda descifrar durante una rotación en curso queda fuera de la lista en lugar de mostrarse roto. Un chip cuyo nombre aún no se ha descifrado muestra un marcador de posición. Los nombres de los filtros privados se vuelven a sellar en el navegador cuando rota la clave de la organización. [[#encryption #keys]]
**¿Quién puede hacer qué?** Enumerar los filtros compartidos de la organización requiere el permiso Ver casos, el mismo permiso que requiere la lista de tickets. Compartir, dejar de compartir y borrar un filtro compartido están limitados a la cuenta propietaria. El servidor rechaza las tres acciones de cualquier otra cuenta. La lista ofrece esas tres acciones solo sobre un filtro que la cuenta posee. [El sistema de permisos](#deep-dive/the-permission-system) trata de dónde salen los permisos. [[#permissions]]
**¿Qué sigue legible en el dispositivo?** El nombre y el estado de un filtro privado están sellados con la clave de la organización. El dispositivo no conserva datos de filtro legibles después de que la persona usuaria cierra sesión. Una entrada almacenada que no coincida con la forma esperada se descarta al cargar la lista, y las demás se cargan igual. [[#privacy #client-data]]
**El almacén de filtros y la comprobación de propiedad.** \`packages/client/src/lib/stores/saved-filters.svelte.ts\` mantiene los conjuntos privado y compartido y los presenta como una sola lista. El resellado del nombre en la rotación de la clave de la organización es \`packages/client/src/lib/stores/saved-filter-reseal.ts\`. La lista y sus acciones son \`packages/client/src/lib/components/filters/SavedFilterList.svelte\`; la hoja de creación es \`packages/client/src/lib/components/filters/CreateSavedFilter.svelte\`. La ruta del servidor es \`packages/server/src/routes/saved-filters.ts\` sobre \`packages/server/src/tickets/saved-filter-service.ts\`, donde vive la comprobación de propiedad. La tabla es la migración de inquilino \`115_saved_filters.ts\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_saved_filters_body = /** @type {(inputs: Demo_Narrative_Topic_Saved_Filters_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À sàvèd fìltèr kèèps à còmbìnàtìòn òf àctìvè fìltèrs ùndèr à nàmè sò thè sàmè còmbìnàtìòn càn bè àpplìèd àgàìn ìn ònè stèp. Èvèry sàvèd fìltèr hàs à rèqùìrèd nàmè, à còlòr, ànd àn ìcòn. Thè sàvèd fìltèrs àppèàr às chìps, ànd sèlèctìng à chìp àpplìès thàt còmbìnàtìòn. À lìnk càn càrry à sàvèd fìltèr's ìdèntìfìèr sò òpènìng thè lìnk àpplìès thè fìltèr. [Fìltèrs](#tìckèts/fìltèrs) còvèrs whàt à fìltèr còmbìnàtìòn càn sèlèct. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Prìvàtè ànd shàrèd. ••••••** À nèw sàvèd fìltèr ìs prìvàtè. Ìt lìvès ònly ìn thè bròwsèr's stòràgè òn thè dèvìcè thàt crèàtèd ìt, ùndèr thè kèy \`càrè-y:sàvèd-fìltèrs\`. Nò ròw èxìsts fòr ìt ànd nò rèqùèst càrrìès ìt. Shàrìng wrìtès ìt tò à ròw òn thè sèrvèr. Èvèry àccòùnt wìth pèrmìssìòn tò vìèw càsès lìsts thè òrgànìzàtìòn's shàrèd fìltèrs àlòngsìdè thè prìvàtè ònès às ònè lìst. À shàrèd fìltèr càrrìès à shàrè ìcòn. Ùnshàrìng dèlètès thè ròw ànd pùts thè fìltèr bàck ìn thè dèvìcè's stòràgè às à prìvàtè fìltèr wìth à nèw ìdèntìfìèr. [[#prìvàcy #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr hòld? ••••••••** Thè sèrvèr stòrès thè nàmè ànd thè fìltèr stàtè èncryptèd wìth thè òrgànìzàtìòn kèy. Ìt stòrès thè còlòr, thè ìcòn, thè àccòùnt thàt òwns ìt, thè òrgànìzàtìòn kèy gènèràtìòn ìt wàs sèàlèd ùndèr, ànd thè tìmè ìt wàs crèàtèd ìn plàìntèxt. Thè sèrvèr cànnòt òpèn èìthèr èncryptèd fìèld. À dàtàbàsè dùmp shòws hòw màny shàrèd fìltèrs àn òrgànìzàtìòn kèèps ànd whìch àccòùnt òwns èàch ònè. Ìt dòès nòt shòw whàt àny fìltèr ìs càllèd òr whìch qùèùè, prìòrìty, àssìgnèè, òr dàtè wìndòw ìt sèlècts. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè òrgànìzàtìòn kèy ànd ìts ròtàtìòn. [[#èncryptìòn #sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Kèy ròtàtìòn. ••••** Bòth èncryptèd còlùmns àrè ènròllèd ìn thè òrgànìzàtìòn kèy ròtàtìòn. À shàrèd fìltèr thè bròwsèr cànnòt dècrypt dùrìng à ròtàtìòn ìn flìght ìs lèft òùt òf thè lìst ràthèr thàn shòwn bròkèn. À chìp whòsè nàmè hàs nòt dècryptèd yèt shòws à plàcèhòldèr. Prìvàtè fìltèrs' nàmès àrè rè-sèàlèd ìn thè bròwsèr whèn thè òrgànìzàtìòn kèy ròtàtès. [[#èncryptìòn #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn dò whàt? •••••** Lìstìng thè òrgànìzàtìòn's shàrèd fìltèrs rèqùìrès thè Vìèw càsès pèrmìssìòn, thè sàmè pèrmìssìòn thè tìckèt lìst rèqùìrès. Shàrìng, ùnshàrìng, ànd dèlètìng à shàrèd fìltèr àrè lìmìtèd tò thè àccòùnt thàt òwns ìt. Thè sèrvèr rèfùsès àll thrèè fròm àny òthèr àccòùnt. Thè lìst òffèrs thòsè thrèè àctìòns ònly òn à fìltèr thè àccòùnt òwns. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs whèrè pèrmìssìòns còmè fròm. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt stàys rèàdàblè òn thè dèvìcè? •••••••••••** À prìvàtè fìltèr's nàmè ànd stàtè àrè bòth sèàlèd ùndèr thè òrgànìzàtìòn kèy. Thè dèvìcè hòlds nò rèàdàblè fìltèr dàtà àftèr thè ùsèr sìgns òùt. À stòrèd èntry thàt dòès nòt màtch thè èxpèctèd shàpè ìs dròppèd whèn thè lìst lòàds, ànd thè rèst stìll lòàd. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fìltèr stòrè ànd thè òwnèrshìp chèck. •••••••••••••** \`pàckàgès/clìènt/src/lìb/stòrès/sàvèd-fìltèrs.svèltè.ts\` kèèps thè prìvàtè ànd shàrèd sèts ànd prèsènts thèm às ònè lìst. Thè nàmè rè-sèàl òn òrgànìzàtìòn kèy ròtàtìòn ìs \`pàckàgès/clìènt/src/lìb/stòrès/sàvèd-fìltèr-rèsèàl.ts\`. Thè lìst ànd ìts àctìòns àrè \`pàckàgès/clìènt/src/lìb/còmpònènts/fìltèrs/SàvèdFìltèrLìst.svèltè\`; thè crèàtè shèèt ìs \`pàckàgès/clìènt/src/lìb/còmpònènts/fìltèrs/CrèàtèSàvèdFìltèr.svèltè\`. Thè sèrvèr ròùtè ìs \`pàckàgès/sèrvèr/src/ròùtès/sàvèd-fìltèrs.ts\` òvèr \`pàckàgès/sèrvèr/src/tìckèts/sàvèd-fìltèr-sèrvìcè.ts\`, whèrè thè òwnèrshìp chèck lìvès. Thè tàblè ìs tènànt mìgràtìòn \`115_sàvèd_fìltèrs.ts\`. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A saved filter keeps a combination of active filters under a name so the same combination can be applied again in one step. Every saved filter has a required..." |
*
* @param {Demo_Narrative_Topic_Saved_Filters_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_saved_filters_body = /** @type {((inputs?: Demo_Narrative_Topic_Saved_Filters_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Saved_Filters_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_saved_filters_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_saved_filters_body(inputs)
	return en_demo_narrative_topic_saved_filters_body(inputs)
});