/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Telephony_Provider_BodyInputs */

const en_demo_narrative_admin_telephony_provider_body = /** @type {(inputs: Demo_Narrative_Admin_Telephony_Provider_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The provider connection gives an organization a path to the phone network under one of two arrangements. Self-managed telephony means the organization owns a provider account and gives CARE-Y the credentials for it. Managed telephony means the platform operator provisions numbers on the organization's behalf. [Deployment](#deep-dive/deployment) covers which deployment types offer each arrangement. Saving or changing either arrangement requires the Manage infrastructure permission. [[#telephony #permissions]]
**Why can the server read these credentials?** Provider credentials are encrypted under the server's operational key, not the organization's end-to-end key. The server holds that key, so the running server can read the credentials at any time. That is what allows it to place calls and send texts through the provider. The encryption protects the credentials in a database dump or backup taken without the key. It does not protect them from the server itself. [The telephony relay](#deep-dive/the-telephony-relay) covers what the provider learns during a call. [[#keys #trust-boundary]]
**What does the credential row hold?** One row per organization on the platform database. The provider name, the key version and the two timestamps are plaintext. The sealed configuration holds the account identifier, the authentication token and the provisioned phone numbers. A dump taken without the operational key gives the provider name and when the credentials last changed. [Encryption keys and escrow](#admin-org/keys) covers the key the rest of the product uses. [[#server-holds #metadata]]
**What does a save validate?** A save checks the credentials against the provider's expected format and makes an authenticated read-only request to the provider before storing them. Wrong credentials are refused at save time. A test action is available for later checks, and a provider failure surfaces in the admin hub. After saving, the read-back masks the account identifier and replaces the token with a fixed run of dots. The stored token is not sent back. [[#failure-states #encryption]]
**What does switching to managed do?** Switching to managed telephony deletes the credential row rather than leaving it unused. Any cached provider instance built from those credentials is invalidated on the same request. A call already in progress with the provider is unaffected, because the provider accepted the session before the row was deleted. [[#failure-states]]
**The config service and the provider factory.** \`packages/server/src/telephony/config-service.ts\` holds the encrypt, decrypt and upsert path. \`packages/server/src/telephony/factory.ts\` builds one provider instance per organization from the decrypted credentials and caches it. A save or a mode change invalidates the cached entry. A provider the server has no implementation for is refused at the factory before any call reaches the provider. [[#failure-states]]`)
};

const es_demo_narrative_admin_telephony_provider_body = /** @type {(inputs: Demo_Narrative_Admin_Telephony_Provider_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La conexión con el proveedor da a una organización un camino a la red telefónica bajo uno de dos arreglos. La telefonía autogestionada significa que la organización posee una cuenta de proveedor y le entrega a CARE-Y las credenciales. La telefonía gestionada significa que quien opera la plataforma aprovisiona los números en nombre de la organización. [Despliegue](#deep-dive/deployment) trata qué tipos de despliegue ofrecen cada arreglo. Guardar o cambiar cualquiera de los dos arreglos requiere el permiso Gestionar infraestructura. [[#telephony #permissions]]
**¿Por qué puede el servidor leer estas credenciales?** Las credenciales del proveedor se cifran con la clave operativa del servidor, no con la clave de cifrado de extremo a extremo de la organización. El servidor posee esa clave, de modo que puede leer las credenciales en cualquier momento. Eso es lo que le permite realizar llamadas y enviar mensajes de texto a través del proveedor. El cifrado protege las credenciales en un volcado de base de datos o una copia de seguridad tomada sin la clave. No las protege del propio servidor. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que el proveedor llega a saber durante una llamada. [[#keys #trust-boundary]]
**¿Qué guarda la fila de credenciales?** Una fila por organización en la base de datos de plataforma. El nombre del proveedor, la versión de clave y las dos marcas de tiempo son texto plano. La configuración sellada contiene el identificador de cuenta, el token de autenticación y los números aprovisionados. Un volcado tomado sin la clave operativa da el nombre del proveedor y cuándo cambiaron las credenciales por última vez. [Claves de cifrado y custodia](#admin-org/keys) trata la clave que usa el resto del producto. [[#server-holds #metadata]]
**¿Qué valida un guardado?** Un guardado verifica las credenciales contra el formato esperado del proveedor y realiza una solicitud autenticada de solo lectura al proveedor antes de almacenarlas. Las credenciales incorrectas se rechazan en el momento de guardar. Una acción de prueba está disponible para comprobaciones posteriores, y un fallo del proveedor se muestra en el panel de administración. Tras el guardado, la lectura devuelve el identificador de cuenta enmascarado y una serie fija de puntos en lugar del token. El token almacenado no se devuelve. [[#failure-states #encryption]]
**¿Qué hace el cambio a telefonía gestionada?** Cambiar a telefonía gestionada elimina la fila de credenciales en lugar de dejarla sin uso. Toda instancia de proveedor en caché construida a partir de esas credenciales se invalida en la misma solicitud. Una llamada ya en curso con el proveedor no se ve afectada, porque el proveedor aceptó la sesión antes de que la fila se eliminara. [[#failure-states]]
**El servicio de configuración y la fábrica de proveedores.** \`packages/server/src/telephony/config-service.ts\` contiene la ruta de cifrado, descifrado y escritura. \`packages/server/src/telephony/factory.ts\` construye una instancia de proveedor por organización a partir de las credenciales descifradas y la guarda en caché. Un guardado o un cambio de arreglo invalida la entrada en caché. Un proveedor sin implementación en el servidor se rechaza en la fábrica antes de que ninguna llamada llegue al proveedor. [[#failure-states]]`)
};

const en_xa2_demo_narrative_admin_telephony_provider_body = /** @type {(inputs: Demo_Narrative_Admin_Telephony_Provider_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè pròvìdèr cònnèctìòn gìvès àn òrgànìzàtìòn à pàth tò thè phònè nètwòrk ùndèr ònè òf twò àrràngèmènts. Sèlf-mànàgèd tèlèphòny mèàns thè òrgànìzàtìòn òwns à pròvìdèr àccòùnt ànd gìvès CÀRÈ-Y thè crèdèntìàls fòr ìt. Mànàgèd tèlèphòny mèàns thè plàtfòrm òpèràtòr pròvìsìòns nùmbèrs òn thè òrgànìzàtìòn's bèhàlf. [Dèplòymènt](#dèèp-dìvè/dèplòymènt) còvèrs whìch dèplòymènt typès òffèr èàch àrràngèmènt. Sàvìng òr chàngìng èìthèr àrràngèmènt rèqùìrès thè Mànàgè ìnfràstrùctùrè pèrmìssìòn. [[#tèlèphòny #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why càn thè sèrvèr rèàd thèsè crèdèntìàls? •••••••••••••** Pròvìdèr crèdèntìàls àrè èncryptèd ùndèr thè sèrvèr's òpèràtìònàl kèy, nòt thè òrgànìzàtìòn's ènd-tò-ènd kèy. Thè sèrvèr hòlds thàt kèy, sò thè rùnnìng sèrvèr càn rèàd thè crèdèntìàls àt àny tìmè. Thàt ìs whàt àllòws ìt tò plàcè càlls ànd sènd tèxts thròùgh thè pròvìdèr. Thè èncryptìòn pròtècts thè crèdèntìàls ìn à dàtàbàsè dùmp òr bàckùp tàkèn wìthòùt thè kèy. Ìt dòès nòt pròtèct thèm fròm thè sèrvèr ìtsèlf. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt thè pròvìdèr lèàrns dùrìng à càll. [[#kèys #trùst-bòùndàry]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè crèdèntìàl ròw hòld? •••••••••••** Ònè ròw pèr òrgànìzàtìòn òn thè plàtfòrm dàtàbàsè. Thè pròvìdèr nàmè, thè kèy vèrsìòn ànd thè twò tìmèstàmps àrè plàìntèxt. Thè sèàlèd cònfìgùràtìòn hòlds thè àccòùnt ìdèntìfìèr, thè àùthèntìcàtìòn tòkèn ànd thè pròvìsìònèd phònè nùmbèrs. À dùmp tàkèn wìthòùt thè òpèràtìònàl kèy gìvès thè pròvìdèr nàmè ànd whèn thè crèdèntìàls làst chàngèd. [Èncryptìòn kèys ànd èscròw](#àdmìn-òrg/kèys) còvèrs thè kèy thè rèst òf thè pròdùct ùsès. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à sàvè vàlìdàtè? ••••••••** À sàvè chècks thè crèdèntìàls àgàìnst thè pròvìdèr's èxpèctèd fòrmàt ànd màkès àn àùthèntìcàtèd rèàd-ònly rèqùèst tò thè pròvìdèr bèfòrè stòrìng thèm. Wròng crèdèntìàls àrè rèfùsèd àt sàvè tìmè. À tèst àctìòn ìs àvàìlàblè fòr làtèr chècks, ànd à pròvìdèr fàìlùrè sùrfàcès ìn thè àdmìn hùb. Àftèr sàvìng, thè rèàd-bàck màsks thè àccòùnt ìdèntìfìèr ànd rèplàcès thè tòkèn wìth à fìxèd rùn òf dòts. Thè stòrèd tòkèn ìs nòt sènt bàck. [[#fàìlùrè-stàtès #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès swìtchìng tò mànàgèd dò? •••••••••••** Swìtchìng tò mànàgèd tèlèphòny dèlètès thè crèdèntìàl ròw ràthèr thàn lèàvìng ìt ùnùsèd. Àny càchèd pròvìdèr ìnstàncè bùìlt fròm thòsè crèdèntìàls ìs ìnvàlìdàtèd òn thè sàmè rèqùèst. À càll àlrèàdy ìn prògrèss wìth thè pròvìdèr ìs ùnàffèctèd, bècàùsè thè pròvìdèr àccèptèd thè sèssìòn bèfòrè thè ròw wàs dèlètèd. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè cònfìg sèrvìcè ànd thè pròvìdèr fàctòry. ••••••••••••••** \`pàckàgès/sèrvèr/src/tèlèphòny/cònfìg-sèrvìcè.ts\` hòlds thè èncrypt, dècrypt ànd ùpsèrt pàth. \`pàckàgès/sèrvèr/src/tèlèphòny/fàctòry.ts\` bùìlds ònè pròvìdèr ìnstàncè pèr òrgànìzàtìòn fròm thè dècryptèd crèdèntìàls ànd càchès ìt. À sàvè òr à mòdè chàngè ìnvàlìdàtès thè càchèd èntry. À pròvìdèr thè sèrvèr hàs nò ìmplèmèntàtìòn fòr ìs rèfùsèd àt thè fàctòry bèfòrè àny càll rèàchès thè pròvìdèr. [[#fàìlùrè-stàtès]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The provider connection gives an organization a path to the phone network under one of two arrangements. Self-managed telephony means the organization owns a..." |
*
* @param {Demo_Narrative_Admin_Telephony_Provider_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_telephony_provider_body = /** @type {((inputs?: Demo_Narrative_Admin_Telephony_Provider_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Telephony_Provider_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_telephony_provider_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_telephony_provider_body(inputs)
	return en_demo_narrative_admin_telephony_provider_body(inputs)
});