/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Share_One_Time_BodyInputs */

const en_demo_narrative_client_share_one_time_body = /** @type {(inputs: Demo_Narrative_Client_Share_One_Time_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Each share link can be opened once. The first open gets the message and the server deletes it at that moment, so a second open gets an already-opened state instead of content. The link stops working seventy-two hours after it was made, and expired links are cleared daily. [Data retention](#deep-dive/data-retention) covers the sweep schedule and what clearing removes. [[#portal #encryption #retention]]
**What does the reader see when the content is gone?** A consumed link reports already opened, and the reader sees that the link was used. An expired link reports that the window closed. A link whose identifier matches no record reports not found, whether the record was cleared or the identifier never existed, so probing tells an observer nothing about which identifiers were real. [Shared content](#client-share/view) covers the incomplete-link state for a truncated or broken address. [[#failure-states #server-holds]]
**Who can spend the single read?** The page's own script spends the read after it loads. A fetcher that does not run scripts, such as a link preview bot or a messaging provider's URL scanner, loads the page without spending it. A scanner that opens pages in a full browser and runs scripts would spend it, and the reader who opens the link afterward sees the already-opened state. [[#trust-boundary #privacy]]
**What does interception before the first read mean?** A share link usually travels by text message, so it crosses the carrier and the messaging provider. An attacker who intercepts the full address before the reader opens it can spend the single read. The link is kept short-lived for that reason. [How the reader is protected](#client-share/exposure-hint) covers what the reader is told about that boundary. [[#trust-boundary #telephony]]
**What stays on the server after the read?** The record keeps the ticket, the times it was created, set to expire, and read. The message is gone, and the record stores no author. Authorship lives in a follow-up on the case thread, encrypted under the ticket key, where any member whose account holds the key can read it. A seized database reveals when a share was created and opened, and nothing of what it contained. [[#server-holds #metadata]]
**The conditional update and the cleanup job.** \`openShare\` in \`packages/server/src/portal/share-service.ts\` runs a conditional update (\`UPDATE ... WHERE read_at IS NULL AND expires_at > now()\`) that gates the race: the first caller to match sets \`read_at\`, gets the ciphertext from the RETURNING clause, and a second statement nulls the ciphertext column inside the same transaction. Subsequent callers fail the \`IS NULL\` predicate and fall through to classification (opened, expired, not_found). \`registerShareCleanupHandler\` in the same file handles the daily expired-row delete across all tenant schemas. The row is defined in \`packages/server/src/db/migrations/tenant/091_share_links.ts\`, which carries no \`created_by\` column. The expiry is written as \`now() + make_interval(secs => ...)\` so both the write and the enforcement use the database clock. [[#server-holds #retention]]`)
};

const es_demo_narrative_client_share_one_time_body = /** @type {(inputs: Demo_Narrative_Client_Share_One_Time_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cada enlace compartido se puede abrir una sola vez. La primera apertura obtiene el mensaje y el servidor lo elimina en ese momento, de modo que una segunda apertura recibe un estado de ya abierto en lugar de contenido. El enlace deja de funcionar setenta y dos horas después de su creación, y los enlaces caducados se eliminan a diario. [Retención de datos](#deep-dive/data-retention) trata el calendario de limpieza y lo que elimina. [[#portal #encryption #retention]]
**¿Qué ve quien lee cuando el contenido ya no está?** Un enlace consumido informa ya abierto, y quien lee ve que el enlace fue utilizado. Un enlace caducado informa que la ventana se cerró. Un enlace cuyo identificador no coincide con ningún registro informa no encontrado, tanto si el registro fue eliminado como si el identificador nunca existió, de modo que sondear no revela a un observador qué identificadores fueron reales. [Contenido compartido](#client-share/view) trata el estado de enlace incompleto para una dirección cortada o dañada. [[#failure-states #server-holds]]
**¿Quién puede gastar la única lectura?** El propio script de la página gasta la lectura después de cargar. Un rastreador que no ejecuta scripts, como un bot de vista previa de enlace o un escáner de URL del proveedor de mensajería, carga la página sin gastarla. Un escáner que abre páginas en un navegador completo y ejecuta scripts la gastaría, y quien lee y abre el enlace después ve el estado de ya abierto. [[#trust-boundary #privacy]]
**¿Qué significa una interceptación antes de la primera lectura?** Un enlace compartido suele viajar por mensaje de texto, por lo que cruza el operador y el proveedor de mensajería. Un atacante que intercepte la dirección completa antes de que quien debe leerlo lo abra puede gastar la única lectura. El enlace se mantiene de vida corta por esa razón. [Cómo se protege al lector](#client-share/exposure-hint) trata lo que se le comunica sobre esa frontera. [[#trust-boundary #telephony]]
**¿Qué conserva el servidor tras la lectura?** El registro conserva el ticket, y los momentos en que se creó, se fijó su caducidad y se leyó. El mensaje ya no está, y el registro no almacena autoría. La autoría vive en un seguimiento en el hilo del caso, cifrado bajo la clave del ticket, donde cualquier miembro cuya cuenta posea la clave puede leerlo. Una base de datos incautada revela cuándo se creó y se abrió un recurso compartido, y nada de lo que contenía. [[#server-holds #metadata]]
**La actualización condicional y la tarea de limpieza.** \`openShare\`, en \`packages/server/src/portal/share-service.ts\`, ejecuta una actualización condicional (\`UPDATE ... WHERE read_at IS NULL AND expires_at > now()\`) que arbitra la carrera: quien llega primero establece \`read_at\`, obtiene el texto cifrado de la cláusula RETURNING, y una segunda sentencia anula la columna de texto cifrado dentro de la misma transacción. Las llamadas posteriores fallan el predicado \`IS NULL\` y caen en la clasificación (opened, expired, not_found). \`registerShareCleanupHandler\`, en el mismo archivo, gestiona la eliminación diaria de filas caducadas en todos los esquemas de organización. La fila se define en \`packages/server/src/db/migrations/tenant/091_share_links.ts\`, que no tiene columna \`created_by\`. La caducidad se escribe como \`now() + make_interval(secs => ...)\` para que tanto la escritura como la verificación usen el reloj de la base de datos. [[#server-holds #retention]]`)
};

const en_xa2_demo_narrative_client_share_one_time_body = /** @type {(inputs: Demo_Narrative_Client_Share_One_Time_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èàch shàrè lìnk càn bè òpènèd òncè. Thè fìrst òpèn gèts thè mèssàgè ànd thè sèrvèr dèlètès ìt àt thàt mòmènt, sò à sècònd òpèn gèts àn àlrèàdy-òpènèd stàtè ìnstèàd òf còntènt. Thè lìnk stòps wòrkìng sèvènty-twò hòùrs àftèr ìt wàs màdè, ànd èxpìrèd lìnks àrè clèàrèd dàìly. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thè swèèp schèdùlè ànd whàt clèàrìng rèmòvès. [[#pòrtàl #èncryptìòn #rètèntìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè rèàdèr sèè whèn thè còntènt ìs gònè? •••••••••••••••** À cònsùmèd lìnk rèpòrts àlrèàdy òpènèd, ànd thè rèàdèr sèès thàt thè lìnk wàs ùsèd. Àn èxpìrèd lìnk rèpòrts thàt thè wìndòw clòsèd. À lìnk whòsè ìdèntìfìèr màtchès nò rècòrd rèpòrts nòt fòùnd, whèthèr thè rècòrd wàs clèàrèd òr thè ìdèntìfìèr nèvèr èxìstèd, sò pròbìng tèlls àn òbsèrvèr nòthìng àbòùt whìch ìdèntìfìèrs wèrè rèàl. [Shàrèd còntènt](#clìènt-shàrè/vìèw) còvèrs thè ìncòmplètè-lìnk stàtè fòr à trùncàtèd òr bròkèn àddrèss. [[#fàìlùrè-stàtès #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn spènd thè sìnglè rèàd? •••••••••** Thè pàgè's òwn scrìpt spènds thè rèàd àftèr ìt lòàds. À fètchèr thàt dòès nòt rùn scrìpts, sùch às à lìnk prèvìèw bòt òr à mèssàgìng pròvìdèr's ÙRL scànnèr, lòàds thè pàgè wìthòùt spèndìng ìt. À scànnèr thàt òpèns pàgès ìn à fùll bròwsèr ànd rùns scrìpts wòùld spènd ìt, ànd thè rèàdèr whò òpèns thè lìnk àftèrwàrd sèès thè àlrèàdy-òpènèd stàtè. [[#trùst-bòùndàry #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès ìntèrcèptìòn bèfòrè thè fìrst rèàd mèàn? •••••••••••••••** À shàrè lìnk ùsùàlly tràvèls by tèxt mèssàgè, sò ìt cròssès thè càrrìèr ànd thè mèssàgìng pròvìdèr. Àn àttàckèr whò ìntèrcèpts thè fùll àddrèss bèfòrè thè rèàdèr òpèns ìt càn spènd thè sìnglè rèàd. Thè lìnk ìs kèpt shòrt-lìvèd fòr thàt rèàsòn. [Hòw thè rèàdèr ìs pròtèctèd](#clìènt-shàrè/èxpòsùrè-hìnt) còvèrs whàt thè rèàdèr ìs tòld àbòùt thàt bòùndàry. [[#trùst-bòùndàry #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt stàys òn thè sèrvèr àftèr thè rèàd? ••••••••••••** Thè rècòrd kèèps thè tìckèt, thè tìmès ìt wàs crèàtèd, sèt tò èxpìrè, ànd rèàd. Thè mèssàgè ìs gònè, ànd thè rècòrd stòrès nò àùthòr. Àùthòrshìp lìvès ìn à fòllòw-ùp òn thè càsè thrèàd, èncryptèd ùndèr thè tìckèt kèy, whèrè àny mèmbèr whòsè àccòùnt hòlds thè kèy càn rèàd ìt. À sèìzèd dàtàbàsè rèvèàls whèn à shàrè wàs crèàtèd ànd òpènèd, ànd nòthìng òf whàt ìt còntàìnèd. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còndìtìònàl ùpdàtè ànd thè clèànùp jòb. •••••••••••••** \`òpènShàrè\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/shàrè-sèrvìcè.ts\` rùns à còndìtìònàl ùpdàtè (\`ÙPDÀTÈ ... WHÈRÈ rèàd_àt ÌS NÙLL ÀND èxpìrès_àt > nòw()\`) thàt gàtès thè ràcè: thè fìrst càllèr tò màtch sèts \`rèàd_àt\`, gèts thè cìphèrtèxt fròm thè RÈTÙRNÌNG clàùsè, ànd à sècònd stàtèmènt nùlls thè cìphèrtèxt còlùmn ìnsìdè thè sàmè trànsàctìòn. Sùbsèqùènt càllèrs fàìl thè \`ÌS NÙLL\` prèdìcàtè ànd fàll thròùgh tò clàssìfìcàtìòn (òpènèd, èxpìrèd, nòt_fòùnd). \`règìstèrShàrèClèànùpHàndlèr\` ìn thè sàmè fìlè hàndlès thè dàìly èxpìrèd-ròw dèlètè àcròss àll tènànt schèmàs. Thè ròw ìs dèfìnèd ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/091_shàrè_lìnks.ts\`, whìch càrrìès nò \`crèàtèd_by\` còlùmn. Thè èxpìry ìs wrìttèn às \`nòw() + màkè_ìntèrvàl(sècs => ...)\` sò bòth thè wrìtè ànd thè ènfòrcèmènt ùsè thè dàtàbàsè clòck. [[#sèrvèr-hòlds #rètèntìòn]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Each share link can be opened once. The first open gets the message and the server deletes it at that moment, so a second open gets an already-opened state i..." |
*
* @param {Demo_Narrative_Client_Share_One_Time_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_share_one_time_body = /** @type {((inputs?: Demo_Narrative_Client_Share_One_Time_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Share_One_Time_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_share_one_time_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_share_one_time_body(inputs)
	return en_demo_narrative_client_share_one_time_body(inputs)
});