/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Portal_Thread_BodyInputs */

const en_demo_narrative_client_portal_thread_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The portal thread gathers the client's own messages, the organization's replies, voicemails, call entries, files and contact corrections into one timeline ordered by date, which the client can narrow by type, by author and by date range. [[#portal #client-data]]
**What opens a message and where the key sits.** Each message on the channel is encrypted to the channel's public key, and the matching private key is derived inside a dedicated worker from the credential carried in the link, so the page never holds it. A file carries a random key of its own sealed to the same channel key, and voicemail recordings open by the same route. Call entries are plaintext metadata the server stores unencrypted, so a database dump shows that a call happened, when it happened, how long it lasted and how it ended, and not a word of what was said. [Portal and channel lifecycle](#deep-dive/portal-channel-lifecycle) covers the channel key. [[#encryption #keys #server-holds]]
**The credential and the address bar.** The credential rides in the part of the address after the \`#\`, which browsers never send in a request. The page reads it once and then removes it from the address bar, so it is absent from the history entry and from an address the client copies out. [Quick exit](#client-portal/quick-exit) covers what the page discards on the way out. [[#privacy #keys]]
**Narrowing and searching without the server.** Filters and in-thread search run against text the tab has already decrypted, so a search term and a filter choice never leave the device. The thread holds fifty messages and asks for the page before them when the client reaches the oldest one loaded, which keeps a long conversation from being decrypted in full on every visit. [[#privacy #client-data]]
**How long the client's copies last.** Every read stamps the channel as seen, and a channel that has gone thirty days without one drops the client's copies of its messages, files and recordings in a single transaction on the next read. The organization's record of the case is stored separately under the case key and follows its own schedule. [Data retention](#deep-dive/data-retention) covers that schedule. [[#retention #portal]]
**When a read is refused.** Portal reads are capped per address per hour, at sixty by default, and a refusal carries the time to wait. The page waits that out and retries rather than reporting a dead link, because a client who reads a transient refusal as expiry may throw away a link that still works. [[#failure-states]]
**The thread components and the paging path.** \`PortalThread.svelte\` in \`packages/client/src/lib/portal/\` renders the bubble, date separator, image, voicemail, call entry and correction components from \`packages/client/src/lib/components/tickets/\`, which are the same components the organization's own thread renders. Pages come from \`portalMessagePage\` in \`packages/server/src/routes/client-portal.ts\`, and the seen stamp and the expiry sweep are in \`packages/server/src/portal/portal-message-service.ts\`. [Conversation thread](#ticket-detail/conversation) covers the other end. [[#portal #client-data]]`)
};

const es_demo_narrative_client_portal_thread_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El hilo del portal reúne los mensajes del propio cliente, las respuestas de la organización, los mensajes de voz, las entradas de llamada, los archivos y las correcciones de contacto en una sola línea temporal ordenada por fecha, que el cliente puede acotar por tipo, por autoría y por intervalo de fechas. [[#portal #client-data]]
**Qué abre un mensaje y dónde está la clave.** Cada mensaje del canal va cifrado con la clave pública del canal, y la clave privada correspondiente se deriva dentro de un worker dedicado a partir de la credencial que lleva el enlace, así que la página nunca la tiene. Cada archivo lleva una clave aleatoria propia sellada con esa misma clave del canal, y las grabaciones de voz se abren por la misma vía. Las entradas de llamada son metadatos en texto plano que el servidor guarda sin cifrar, de modo que un volcado de la base de datos muestra que hubo una llamada, cuándo fue, cuánto duró y cómo terminó, y ni una palabra de lo que se dijo. [El ciclo de vida del portal y los canales](#deep-dive/portal-channel-lifecycle) trata la clave del canal. [[#encryption #keys #server-holds]]
**La credencial y la barra de direcciones.** La credencial viaja en la parte de la dirección posterior al \`#\`, que los navegadores nunca envían en una solicitud. La página la lee una vez y después la retira de la barra de direcciones, de modo que no está en la entrada del historial ni en una dirección que el cliente copie. [Salida rápida](#client-portal/quick-exit) trata lo que la página descarta al salir. [[#privacy #keys]]
**Acotar y buscar sin el servidor.** Los filtros y la búsqueda dentro del hilo funcionan sobre texto que la pestaña ya ha descifrado, así que un término de búsqueda y una elección de filtro nunca salen del dispositivo. El hilo mantiene cincuenta mensajes y pide la página anterior cuando el cliente llega al más antiguo que tiene cargado, lo que evita descifrar entera una conversación larga en cada visita. [[#privacy #client-data]]
**Cuánto duran las copias del cliente.** Cada lectura marca el canal como visto, y un canal que lleva treinta días sin ninguna elimina en una sola transacción, en la lectura siguiente, las copias de sus mensajes, archivos y grabaciones que tiene el cliente. El registro del caso que guarda la organización se almacena aparte bajo la clave del caso y sigue su propio calendario. [Retención de datos](#deep-dive/data-retention) trata ese calendario. [[#retention #portal]]
**Cuándo se rechaza una lectura.** Las lecturas del portal están limitadas por dirección y por hora, a sesenta de forma predeterminada, y el rechazo indica cuánto hay que esperar. La página espera ese tiempo y reintenta en lugar de informar de un enlace muerto, porque un cliente que lea un rechazo pasajero como una caducidad puede tirar un enlace que todavía funciona. [[#failure-states]]
**Los componentes del hilo y la ruta de paginación.** \`PortalThread.svelte\`, en \`packages/client/src/lib/portal/\`, presenta los componentes de burbuja, separador de fecha, imagen, mensaje de voz, entrada de llamada y corrección de \`packages/client/src/lib/components/tickets/\`, que son los mismos que presenta el hilo de la propia organización. Las páginas vienen de \`portalMessagePage\`, en \`packages/server/src/routes/client-portal.ts\`, y la marca de visto y el barrido de caducidad están en \`packages/server/src/portal/portal-message-service.ts\`. [Hilo de conversación](#ticket-detail/conversation) trata el otro extremo. [[#portal #client-data]]`)
};

const en_xa2_demo_narrative_client_portal_thread_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè pòrtàl thrèàd gàthèrs thè clìènt's òwn mèssàgès, thè òrgànìzàtìòn's rèplìès, vòìcèmàìls, càll èntrìès, fìlès ànd còntàct còrrèctìòns ìntò ònè tìmèlìnè òrdèrèd by dàtè, whìch thè clìènt càn nàrròw by typè, by àùthòr ànd by dàtè ràngè. [[#pòrtàl #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt òpèns à mèssàgè ànd whèrè thè kèy sìts. ••••••••••••••** Èàch mèssàgè òn thè chànnèl ìs èncryptèd tò thè chànnèl's pùblìc kèy, ànd thè màtchìng prìvàtè kèy ìs dèrìvèd ìnsìdè à dèdìcàtèd wòrkèr fròm thè crèdèntìàl càrrìèd ìn thè lìnk, sò thè pàgè nèvèr hòlds ìt. À fìlè càrrìès à ràndòm kèy òf ìts òwn sèàlèd tò thè sàmè chànnèl kèy, ànd vòìcèmàìl rècòrdìngs òpèn by thè sàmè ròùtè. Càll èntrìès àrè plàìntèxt mètàdàtà thè sèrvèr stòrès ùnèncryptèd, sò à dàtàbàsè dùmp shòws thàt à càll hàppènèd, whèn ìt hàppènèd, hòw lòng ìt làstèd ànd hòw ìt èndèd, ànd nòt à wòrd òf whàt wàs sàìd. [Pòrtàl ànd chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thè chànnèl kèy. [[#èncryptìòn #kèys #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè crèdèntìàl ànd thè àddrèss bàr. •••••••••••** Thè crèdèntìàl rìdès ìn thè pàrt òf thè àddrèss àftèr thè \`#\`, whìch bròwsèrs nèvèr sènd ìn à rèqùèst. Thè pàgè rèàds ìt òncè ànd thèn rèmòvès ìt fròm thè àddrèss bàr, sò ìt ìs àbsènt fròm thè hìstòry èntry ànd fròm àn àddrèss thè clìènt còpìès òùt. [Qùìck èxìt](#clìènt-pòrtàl/qùìck-èxìt) còvèrs whàt thè pàgè dìscàrds òn thè wày òùt. [[#prìvàcy #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Nàrròwìng ànd sèàrchìng wìthòùt thè sèrvèr. •••••••••••••** Fìltèrs ànd ìn-thrèàd sèàrch rùn àgàìnst tèxt thè tàb hàs àlrèàdy dècryptèd, sò à sèàrch tèrm ànd à fìltèr chòìcè nèvèr lèàvè thè dèvìcè. Thè thrèàd hòlds fìfty mèssàgès ànd àsks fòr thè pàgè bèfòrè thèm whèn thè clìènt rèàchès thè òldèst ònè lòàdèd, whìch kèèps à lòng cònvèrsàtìòn fròm bèìng dècryptèd ìn fùll òn èvèry vìsìt. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw lòng thè clìènt's còpìès làst. •••••••••••** Èvèry rèàd stàmps thè chànnèl às sèèn, ànd à chànnèl thàt hàs gònè thìrty dàys wìthòùt ònè dròps thè clìènt's còpìès òf ìts mèssàgès, fìlès ànd rècòrdìngs ìn à sìnglè trànsàctìòn òn thè nèxt rèàd. Thè òrgànìzàtìòn's rècòrd òf thè càsè ìs stòrèd sèpàràtèly ùndèr thè càsè kèy ànd fòllòws ìts òwn schèdùlè. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thàt schèdùlè. [[#rètèntìòn #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn à rèàd ìs rèfùsèd. •••••••** Pòrtàl rèàds àrè càppèd pèr àddrèss pèr hòùr, àt sìxty by dèfàùlt, ànd à rèfùsàl càrrìès thè tìmè tò wàìt. Thè pàgè wàìts thàt òùt ànd rètrìès ràthèr thàn rèpòrtìng à dèàd lìnk, bècàùsè à clìènt whò rèàds à trànsìènt rèfùsàl às èxpìry mày thròw àwày à lìnk thàt stìll wòrks. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè thrèàd còmpònènts ànd thè pàgìng pàth. •••••••••••••** \`PòrtàlThrèàd.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/pòrtàl/\` rèndèrs thè bùbblè, dàtè sèpàràtòr, ìmàgè, vòìcèmàìl, càll èntry ànd còrrèctìòn còmpònènts fròm \`pàckàgès/clìènt/src/lìb/còmpònènts/tìckèts/\`, whìch àrè thè sàmè còmpònènts thè òrgànìzàtìòn's òwn thrèàd rèndèrs. Pàgès còmè fròm \`pòrtàlMèssàgèPàgè\` ìn \`pàckàgès/sèrvèr/src/ròùtès/clìènt-pòrtàl.ts\`, ànd thè sèèn stàmp ànd thè èxpìry swèèp àrè ìn \`pàckàgès/sèrvèr/src/pòrtàl/pòrtàl-mèssàgè-sèrvìcè.ts\`. [Cònvèrsàtìòn thrèàd](#tìckèt-dètàìl/cònvèrsàtìòn) còvèrs thè òthèr ènd. [[#pòrtàl #clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The portal thread gathers the client's own messages, the organization's replies, voicemails, call entries, files and contact corrections into one timeline or..." |
*
* @param {Demo_Narrative_Client_Portal_Thread_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_portal_thread_body = /** @type {((inputs?: Demo_Narrative_Client_Portal_Thread_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Portal_Thread_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_portal_thread_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_portal_thread_body(inputs)
	return en_demo_narrative_client_portal_thread_body(inputs)
});