/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Settings_Security_BodyInputs */

const en_demo_narrative_settings_security_body = /** @type {(inputs: Demo_Narrative_Settings_Security_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The security briefing is part of onboarding and can be reopened from settings at any time. Reopening it does not write the seen flag. The flag is set only on the onboarding path, so the server cannot tell whether a user has revisited it. [[#privacy #server-holds]]
**What does the briefing cover?** The briefing explains how encryption works and includes a diagram of the key hierarchy. It names each category of data the system holds, the access rules that govern it, and what a seizure of that store would expose. It then walks through threat scenarios and answers each one with the specific data the adversary obtains and the data that remains encrypted or inaccessible. It closes with operational choices that carry lasting tradeoffs, such as telephony provider selection and two-factor authentication policy. [The trust boundary](#deep-dive/the-trust-boundary) covers each data category in more detail. [[#trust-boundary #server-holds]]
**What do the threat scenarios address?** The scenarios cover server seizure, compromise of one of the two key-derivation servers, a compromised device, an insider with administrative access, a compromised or subpoenaed telephony provider, and network surveillance. [Deployment](#deep-dive/deployment) covers where those servers run and who operates them. [[#trust-boundary #failure-states]]
**Lasting tradeoffs.** No mechanism exists to reset a forgotten password. Text messages travel outside the encrypted channel. An organization that has removed every user who held the organization key loses all data that key protected. [The organization key lifecycle](#deep-dive/organization-key-lifecycle) covers that last scenario. [[#keys #failure-states]]
**The briefing component and the seen flag.** The content is \`SecurityBriefing.svelte\` in \`packages/client/src/lib/components/onboarding/\`. Settings reopens it through \`SecurityBriefingPopup.svelte\` in \`packages/client/src/lib/components/settings/\`. The seen flag is \`users.has_seen_briefing\` from \`packages/server/src/db/migrations/tenant/001_baseline.ts\`, written by \`profile.markBriefingSeen\`. [[#server-holds]]`)
};

const es_demo_narrative_settings_security_body = /** @type {(inputs: Demo_Narrative_Settings_Security_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El resumen de seguridad forma parte del proceso de incorporación y se puede reabrir desde los ajustes en cualquier momento. Reabrirlo no escribe la marca de lectura. La marca solo se establece durante la incorporación, por lo que el servidor no puede saber si la persona usuaria lo ha revisitado. [[#privacy #server-holds]]
**¿Qué trata el resumen?** El resumen explica cómo funciona el cifrado e incluye un diagrama de la jerarquía de claves. Nombra cada categoría de datos que el sistema almacena, las reglas de acceso que la rigen y lo que una incautación de ese almacén expondría. Después recorre escenarios de amenaza y responde a cada uno con los datos concretos que el adversario obtiene y los que permanecen cifrados o inaccesibles. Cierra con decisiones operativas que conllevan compromisos duraderos, como la selección del proveedor de telefonía y la política de autenticación de dos factores. [La frontera de confianza](#deep-dive/the-trust-boundary) trata cada categoría de datos en más detalle. [[#trust-boundary #server-holds]]
**¿Qué escenarios de amenaza se abordan?** Los escenarios tratan la incautación del servidor, el compromiso de uno de los dos servidores de derivación de claves, un dispositivo comprometido, una persona con acceso administrativo actuando de forma malintencionada, un proveedor de telefonía comprometido o citado judicialmente, y la vigilancia de red. [Despliegue](#deep-dive/deployment) trata dónde se ejecutan esos servidores y quién los opera. [[#trust-boundary #failure-states]]
**Compromisos duraderos.** No existe un mecanismo para restablecer una contraseña olvidada. Los mensajes de texto viajan fuera del canal cifrado. Una organización de la que se ha eliminado a toda persona usuaria que tenía la clave de la organización pierde todos los datos que esa clave protegía. [El ciclo de vida de la clave de la organización](#deep-dive/organization-key-lifecycle) trata ese último escenario. [[#keys #failure-states]]
**El componente del resumen y la marca de lectura.** El contenido está en \`SecurityBriefing.svelte\` dentro de \`packages/client/src/lib/components/onboarding/\`. Ajustes lo reabre a través de \`SecurityBriefingPopup.svelte\` en \`packages/client/src/lib/components/settings/\`. La marca de lectura es \`users.has_seen_briefing\` de \`packages/server/src/db/migrations/tenant/001_baseline.ts\`, escrita por \`profile.markBriefingSeen\`. [[#server-holds]]`)
};

const en_xa2_demo_narrative_settings_security_body = /** @type {(inputs: Demo_Narrative_Settings_Security_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè sècùrìty brìèfìng ìs pàrt òf ònbòàrdìng ànd càn bè rèòpènèd fròm sèttìngs àt àny tìmè. Rèòpènìng ìt dòès nòt wrìtè thè sèèn flàg. Thè flàg ìs sèt ònly òn thè ònbòàrdìng pàth, sò thè sèrvèr cànnòt tèll whèthèr à ùsèr hàs rèvìsìtèd ìt. [[#prìvàcy #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè brìèfìng còvèr? •••••••••** Thè brìèfìng èxplàìns hòw èncryptìòn wòrks ànd ìnclùdès à dìàgràm òf thè kèy hìèràrchy. Ìt nàmès èàch càtègòry òf dàtà thè systèm hòlds, thè àccèss rùlès thàt gòvèrn ìt, ànd whàt à sèìzùrè òf thàt stòrè wòùld èxpòsè. Ìt thèn wàlks thròùgh thrèàt scènàrìòs ànd ànswèrs èàch ònè wìth thè spècìfìc dàtà thè àdvèrsàry òbtàìns ànd thè dàtà thàt rèmàìns èncryptèd òr ìnàccèssìblè. Ìt clòsès wìth òpèràtìònàl chòìcès thàt càrry làstìng tràdèòffs, sùch às tèlèphòny pròvìdèr sèlèctìòn ànd twò-fàctòr àùthèntìcàtìòn pòlìcy. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs èàch dàtà càtègòry ìn mòrè dètàìl. [[#trùst-bòùndàry #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dò thè thrèàt scènàrìòs àddrèss? ••••••••••••** Thè scènàrìòs còvèr sèrvèr sèìzùrè, còmpròmìsè òf ònè òf thè twò kèy-dèrìvàtìòn sèrvèrs, à còmpròmìsèd dèvìcè, àn ìnsìdèr wìth àdmìnìstràtìvè àccèss, à còmpròmìsèd òr sùbpòènàèd tèlèphòny pròvìdèr, ànd nètwòrk sùrvèìllàncè. [Dèplòymènt](#dèèp-dìvè/dèplòymènt) còvèrs whèrè thòsè sèrvèrs rùn ànd whò òpèràtès thèm. [[#trùst-bòùndàry #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Làstìng tràdèòffs. ••••••** Nò mèchànìsm èxìsts tò rèsèt à fòrgòttèn pàsswòrd. Tèxt mèssàgès tràvèl òùtsìdè thè èncryptèd chànnèl. Àn òrgànìzàtìòn thàt hàs rèmòvèd èvèry ùsèr whò hèld thè òrgànìzàtìòn kèy lòsès àll dàtà thàt kèy pròtèctèd. [Thè òrgànìzàtìòn kèy lìfècyclè](#dèèp-dìvè/òrgànìzàtìòn-kèy-lìfècyclè) còvèrs thàt làst scènàrìò. [[#kèys #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè brìèfìng còmpònènt ànd thè sèèn flàg. •••••••••••••** Thè còntènt ìs \`SècùrìtyBrìèfìng.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/ònbòàrdìng/\`. Sèttìngs rèòpèns ìt thròùgh \`SècùrìtyBrìèfìngPòpùp.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/sèttìngs/\`. Thè sèèn flàg ìs \`ùsèrs.hàs_sèèn_brìèfìng\` fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`, wrìttèn by \`pròfìlè.màrkBrìèfìngSèèn\`. [[#sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The security briefing is part of onboarding and can be reopened from settings at any time. Reopening it does not write the seen flag. The flag is set only on..." |
*
* @param {Demo_Narrative_Settings_Security_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_settings_security_body = /** @type {((inputs?: Demo_Narrative_Settings_Security_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Settings_Security_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_settings_security_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_settings_security_body(inputs)
	return en_demo_narrative_settings_security_body(inputs)
});