/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Quick_Exit_BodyInputs */

const en_demo_narrative_client_quick_exit_body = /** @type {(inputs: Demo_Narrative_Client_Quick_Exit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Every client-facing page has a quick exit control, from the intake form and the portal through the account page, the privacy notice, and a share link. The control is unlabeled, because the word "exit" visible on a shared device is itself a signal. Pressing the control or pressing Escape blanks the tab title, zeroes the key material the page holds, and sends the browser to an ordinary site the organization has chosen in its settings. When no safe URL is configured, a weather service is used. The replacement overwrites the current history entry, so the back button does not lead back to the page. On the account page the control also revokes the server-side session before navigating. Escape leaves the page even when a sheet or panel is open. [[#privacy #portal]]
**What does the control not clear?** Earlier browser history entries survive. Cache, stored form data, and the language cookie remain on the device. [On the device](#deep-dive/on-the-device) covers the full inventory of what each page leaves behind. A screenshot, a printout, or a saved copy of a message stays wherever the client put it. Monitoring software on the device records whatever the person sees well before the control fires. A client whose device is controlled by someone else is better served by a channel the organization can close from its side, which [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers, and by retention limits, which [Data retention](#deep-dive/data-retention) covers. [[#privacy #failure-states]]
**What does the server learn?** On the intake form, the portal, and a share link, no request reaches the server. An activation leaves no record on the organization's side. On the account page one request tells the server that a session ended and nothing about why. [[#server-holds #metadata #privacy]]
**What happens when the page closes without the control?** Closing the tab or navigating away zeroes the same key material and revokes the server session. The account page also runs a 15-minute idle timer that counts human input alone. At the 10-minute mark it announces a warning to assistive technology. When the timer fires it revokes the session and returns the page to the sign-in form. Background refreshes and network requests do not extend it. [[#keys #failure-states]]
**The component and the safe URL.** \`QuickExit.svelte\` is mounted once by \`ClientShell.svelte\` in the navbar, so it stays present through every state a client page passes through. Each page supplies its own key-zeroing callback through the client shell context. The control delegates to that callback and zeroes no keys itself. The Escape keydown listener runs on the capture phase and cancels the event, so it fires ahead of the overlay stack that would otherwise close an open sheet. A \`pagehide\` listener zeroes the same key material as a fallback when the tab closes or the browser navigates away. On the account page the session revocation is sent as a \`sendBeacon\` call because the navigation that follows would cancel an ordinary request. The safe URL is resolved from the page value, the organization's branding configuration, a server-injected copy, or the default, in that priority. [[#client-data #keys]]`)
};

const es_demo_narrative_client_quick_exit_body = /** @type {(inputs: Demo_Narrative_Client_Quick_Exit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Todas las páginas orientadas al cliente tienen un control de salida rápida, desde el formulario de admisión y el portal hasta la página de cuenta, el aviso de privacidad y un enlace compartido. El control no tiene etiqueta visible, porque la palabra "salir" en una pantalla que otra persona puede ver es en sí misma una señal. Al presionar el control o presionar Escape, se borra el título de la pestaña, se eliminan las claves que la página mantiene y el navegador se dirige a un sitio común que la organización ha configurado en sus ajustes. Cuando no se ha configurado una URL segura, se usa un servicio meteorológico. La navegación reemplaza la entrada actual del historial, de modo que el botón de retroceso no conduce de vuelta a la página. En la página de cuenta, el control también revoca la sesión del servidor antes de navegar. Escape abandona la página incluso cuando una hoja o panel está abierto. [[#privacy #portal]]
**¿Qué no borra el control?** Las entradas anteriores del historial del navegador sobreviven. La caché, los datos de formulario almacenados y la cookie de idioma permanecen en el dispositivo. [En el dispositivo](#deep-dive/on-the-device) trata el inventario completo de lo que cada página deja atrás. Una captura de pantalla, una impresión o una copia guardada de un mensaje permanece donde el cliente la dejó. El software de monitoreo en el dispositivo registra todo lo que la persona ve mucho antes de que el control se active. Un cliente cuyo dispositivo está controlado por otra persona se beneficia más de un canal que la organización puede cerrar desde su lado, lo que trata [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle), y de los límites de retención, lo que trata [Retención de datos](#deep-dive/data-retention). [[#privacy #failure-states]]
**¿Qué aprende el servidor?** En el formulario de admisión, el portal y un enlace compartido, ninguna solicitud llega al servidor. Una activación no deja registro en el lado de la organización. En la página de cuenta, una solicitud le indica al servidor que una sesión terminó y nada sobre la razón. [[#server-holds #metadata #privacy]]
**¿Qué ocurre cuando la página se cierra sin el control?** Cerrar la pestaña o navegar a otro lugar elimina las mismas claves y revoca la sesión del servidor. La página de cuenta también ejecuta un temporizador de inactividad de 15 minutos que cuenta solo la actividad humana. En la marca de 10 minutos anuncia una advertencia a la tecnología de asistencia. Cuando el temporizador se activa, revoca la sesión y devuelve la página al formulario de inicio de sesión. Las actualizaciones en segundo plano y las solicitudes de red no lo extienden. [[#keys #failure-states]]
**El componente y la URL segura.** \`QuickExit.svelte\` se monta una sola vez por \`ClientShell.svelte\` en la barra de navegación, de modo que permanece presente en cada estado por el que pasa una página de cliente. Cada página proporciona su propio callback de eliminación de claves a través del contexto del shell de cliente. El control delega en ese callback y no elimina claves por sí mismo. El listener de keydown de Escape se ejecuta en la fase de captura y cancela el evento, de modo que se activa antes de la pila de overlays que de otro modo cerraría una hoja abierta. Un listener de \`pagehide\` elimina las mismas claves como respaldo cuando se cierra la pestaña o el navegador navega a otro lugar. En la página de cuenta, la revocación de sesión se envía como una llamada \`sendBeacon\` porque la navegación que sigue cancelaría una solicitud ordinaria. La URL segura se resuelve desde el valor de la página, la configuración de marca de la organización, una copia inyectada por el servidor o el valor predeterminado, en ese orden de prioridad. [[#client-data #keys]]`)
};

const en_xa2_demo_narrative_client_quick_exit_body = /** @type {(inputs: Demo_Narrative_Client_Quick_Exit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èvèry clìènt-fàcìng pàgè hàs à qùìck èxìt còntròl, fròm thè ìntàkè fòrm ànd thè pòrtàl thròùgh thè àccòùnt pàgè, thè prìvàcy nòtìcè, ànd à shàrè lìnk. Thè còntròl ìs ùnlàbèlèd, bècàùsè thè wòrd "èxìt" vìsìblè òn à shàrèd dèvìcè ìs ìtsèlf à sìgnàl. Prèssìng thè còntròl òr prèssìng Èscàpè blànks thè tàb tìtlè, zèròès thè kèy màtèrìàl thè pàgè hòlds, ànd sènds thè bròwsèr tò àn òrdìnàry sìtè thè òrgànìzàtìòn hàs chòsèn ìn ìts sèttìngs. Whèn nò sàfè ÙRL ìs cònfìgùrèd, à wèàthèr sèrvìcè ìs ùsèd. Thè rèplàcèmènt òvèrwrìtès thè cùrrènt hìstòry èntry, sò thè bàck bùttòn dòès nòt lèàd bàck tò thè pàgè. Òn thè àccòùnt pàgè thè còntròl àlsò rèvòkès thè sèrvèr-sìdè sèssìòn bèfòrè nàvìgàtìng. Èscàpè lèàvès thè pàgè èvèn whèn à shèèt òr pànèl ìs òpèn. [[#prìvàcy #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè còntròl nòt clèàr? ••••••••••** Èàrlìèr bròwsèr hìstòry èntrìès sùrvìvè. Càchè, stòrèd fòrm dàtà, ànd thè làngùàgè còòkìè rèmàìn òn thè dèvìcè. [Òn thè dèvìcè](#dèèp-dìvè/òn-thè-dèvìcè) còvèrs thè fùll ìnvèntòry òf whàt èàch pàgè lèàvès bèhìnd. À scrèènshòt, à prìntòùt, òr à sàvèd còpy òf à mèssàgè stàys whèrèvèr thè clìènt pùt ìt. Mònìtòrìng sòftwàrè òn thè dèvìcè rècòrds whàtèvèr thè pèrsòn sèès wèll bèfòrè thè còntròl fìrès. À clìènt whòsè dèvìcè ìs còntròllèd by sòmèònè èlsè ìs bèttèr sèrvèd by à chànnèl thè òrgànìzàtìòn càn clòsè fròm ìts sìdè, whìch [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs, ànd by rètèntìòn lìmìts, whìch [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs. [[#prìvàcy #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr lèàrn? •••••••••** Òn thè ìntàkè fòrm, thè pòrtàl, ànd à shàrè lìnk, nò rèqùèst rèàchès thè sèrvèr. Àn àctìvàtìòn lèàvès nò rècòrd òn thè òrgànìzàtìòn's sìdè. Òn thè àccòùnt pàgè ònè rèqùèst tèlls thè sèrvèr thàt à sèssìòn èndèd ànd nòthìng àbòùt why. [[#sèrvèr-hòlds #mètàdàtà #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn thè pàgè clòsès wìthòùt thè còntròl? •••••••••••••••••** Clòsìng thè tàb òr nàvìgàtìng àwày zèròès thè sàmè kèy màtèrìàl ànd rèvòkès thè sèrvèr sèssìòn. Thè àccòùnt pàgè àlsò rùns à 15-mìnùtè ìdlè tìmèr thàt còùnts hùmàn ìnpùt àlònè. Àt thè 10-mìnùtè màrk ìt ànnòùncès à wàrnìng tò àssìstìvè tèchnòlògy. Whèn thè tìmèr fìrès ìt rèvòkès thè sèssìòn ànd rètùrns thè pàgè tò thè sìgn-ìn fòrm. Bàckgròùnd rèfrèshès ànd nètwòrk rèqùèsts dò nòt èxtènd ìt. [[#kèys #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còmpònènt ànd thè sàfè ÙRL. ••••••••••** \`QùìckÈxìt.svèltè\` ìs mòùntèd òncè by \`ClìèntShèll.svèltè\` ìn thè nàvbàr, sò ìt stàys prèsènt thròùgh èvèry stàtè à clìènt pàgè pàssès thròùgh. Èàch pàgè sùpplìès ìts òwn kèy-zèròìng càllbàck thròùgh thè clìènt shèll còntèxt. Thè còntròl dèlègàtès tò thàt càllbàck ànd zèròès nò kèys ìtsèlf. Thè Èscàpè kèydòwn lìstènèr rùns òn thè càptùrè phàsè ànd càncèls thè èvènt, sò ìt fìrès àhèàd òf thè òvèrlày stàck thàt wòùld òthèrwìsè clòsè àn òpèn shèèt. À \`pàgèhìdè\` lìstènèr zèròès thè sàmè kèy màtèrìàl às à fàllbàck whèn thè tàb clòsès òr thè bròwsèr nàvìgàtès àwày. Òn thè àccòùnt pàgè thè sèssìòn rèvòcàtìòn ìs sènt às à \`sèndBèàcòn\` càll bècàùsè thè nàvìgàtìòn thàt fòllòws wòùld càncèl àn òrdìnàry rèqùèst. Thè sàfè ÙRL ìs rèsòlvèd fròm thè pàgè vàlùè, thè òrgànìzàtìòn's bràndìng cònfìgùràtìòn, à sèrvèr-ìnjèctèd còpy, òr thè dèfàùlt, ìn thàt prìòrìty. [[#clìènt-dàtà #kèys]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Every client-facing page has a quick exit control, from the intake form and the portal through the account page, the privacy notice, and a share link. The co..." |
*
* @param {Demo_Narrative_Client_Quick_Exit_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_quick_exit_body = /** @type {((inputs?: Demo_Narrative_Client_Quick_Exit_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Quick_Exit_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_quick_exit_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_quick_exit_body(inputs)
	return en_demo_narrative_client_quick_exit_body(inputs)
});