/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Email_Thread_BodyInputs */

const en_demo_narrative_topic_email_thread_body = /** @type {(inputs: Demo_Narrative_Topic_Email_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Email sent and received on a ticket appears in the same thread as texts, portal replies, and notes. Email is the only channel whose content every mail server along the route can read. [[#client-data #encryption #telephony]]
**How does an outbound email reach the thread?** The browser sends the relay the ticket, a subject, and a body. The server looks up and decrypts the client's address on its own rather than accepting one from the request. A copy of the message is sealed with the ticket key and written to the thread as a follow-up. When the client has an active channel key, a second copy is sealed to that key so the follow-up record survives a mailbox nobody reads. An organization can switch its email channel off. When the channel is off, the relay refuses the request before decrypting an address. [Channel policy](#admin-comms/channel-policy) covers that setting. [Sending a reply](#ticket-detail/reply) covers the copies a message produces, and [The telephony relay](#deep-dive/the-telephony-relay) covers the buffer handling this endpoint shares with the text path. [[#encryption #server-holds #telephony]]
**Reply address and token.** Each ticket gets a reply address carrying a 128-bit random token. The server stores only a keyed hash of that token. The address exists in the outbound header and in the client's mailbox and in no location the database can reveal. Revoking the token stops emailed replies from routing to that thread. Earlier reply addresses stay routable until the user revokes them. [[#keys #server-holds #privacy]]
**What is an inbound email trusted for?** The reply token decides which ticket a message lands on. The From address is stored and shown as claimed, never used for routing. Anyone can write any address into it, and each inbound follow-up marks that caution.
- Attachments are counted and dropped rather than imported.
- A subject or body that exceeds the length limit is shortened rather than refused.
- A message arriving on a closed ticket reopens it.
When the newest follow-up from the client is an email, composing a text or a portal reply reports that the client may be waiting on email. The caution can be dismissed per ticket for the rest of the session. It does not appear when the organization has its email channel switched off. [Channel warnings](#ticket-detail/exposure-hints) covers the full set of channel cautions. [[#failure-states #privacy]]
**The relay handlers and the token row.** The outbound path is \`/relay/email\` in \`packages/server/src/routes/relay.ts\`, with reply address and footer assembly in \`packages/server/src/email/email-relay-service.ts\` and the token row from \`email_reply_tokens\` in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. Inbound mail is accepted by \`inbound-receiver.ts\` and written by \`inbound-email.ts\`. The bubbles are \`EmailBubbleContent.svelte\` and \`EmailInboundBubbleContent.svelte\`. [[#client-data]]`)
};

const es_demo_narrative_topic_email_thread_body = /** @type {(inputs: Demo_Narrative_Topic_Email_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El correo electrónico enviado y recibido en un ticket aparece en el mismo hilo que los mensajes de texto, las respuestas del portal y las notas. El correo es el único canal cuyo contenido puede leer cada servidor de correo en la ruta. [[#client-data #encryption #telephony]]
**¿Cómo llega un correo saliente al hilo?** El navegador envía al relay el ticket, un asunto y un cuerpo. El servidor busca y descifra la dirección del cliente por su cuenta en lugar de aceptar una de la solicitud. Una copia del mensaje se sella con la clave del ticket y se escribe en el hilo como seguimiento. Cuando el cliente tiene una clave de canal activa, una segunda copia se sella con esa clave para que el registro de seguimiento sobreviva a un buzón que nadie lee. Una organización puede desactivar su canal de correo electrónico. Cuando el canal está desactivado, el relay rechaza la solicitud antes de descifrar una dirección. [Política de canales](#admin-comms/channel-policy) trata esa configuración. [Enviando una respuesta](#ticket-detail/reply) trata las copias que produce un mensaje, y [El relay de telefonía](#deep-dive/the-telephony-relay) trata el manejo de búfer que este endpoint comparte con la ruta de texto. [[#encryption #server-holds #telephony]]
**Dirección de respuesta y token.** Cada ticket recibe una dirección de respuesta con un token aleatorio de 128 bits. El servidor almacena solo un hash con clave de ese token. La dirección existe en la cabecera del mensaje saliente y en el buzón del cliente y en ningún lugar que la base de datos pueda revelar. Revocar el token impide que las respuestas por correo se enruten a ese hilo. Las direcciones de respuesta anteriores siguen funcionando hasta que la persona usuaria las revoque. [[#keys #server-holds #privacy]]
**¿Para qué se confía en un correo entrante?** El token de respuesta decide a qué ticket se asigna un mensaje. La dirección del remitente se almacena y se muestra como declarada, nunca se usa para enrutamiento. Cualquiera puede escribir cualquier dirección en ella, y cada seguimiento entrante marca esa advertencia.
- Los archivos adjuntos se cuentan y se descartan en lugar de importarse.
- Un asunto o cuerpo que excede el límite de longitud se acorta en lugar de rechazarse.
- Un mensaje que llega a un ticket cerrado lo reabre.
Cuando el seguimiento más reciente del cliente es un correo electrónico, redactar un texto o una respuesta del portal informa que el cliente podría estar esperando una respuesta por correo. La advertencia se puede descartar por ticket durante el resto de la sesión. No aparece cuando la organización tiene su canal de correo desactivado. [Avisos de canal](#ticket-detail/exposure-hints) trata el conjunto completo de advertencias de canal. [[#failure-states #privacy]]
**Los handlers del relay y la fila del token.** La ruta de salida es \`/relay/email\` en \`packages/server/src/routes/relay.ts\`, con el ensamblaje de dirección de respuesta y pie de mensaje en \`packages/server/src/email/email-relay-service.ts\` y la fila del token en la tabla \`email_reply_tokens\` de \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. El correo entrante lo acepta \`inbound-receiver.ts\` y lo escribe \`inbound-email.ts\`. Las burbujas son \`EmailBubbleContent.svelte\` y \`EmailInboundBubbleContent.svelte\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_email_thread_body = /** @type {(inputs: Demo_Narrative_Topic_Email_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èmàìl sènt ànd rècèìvèd òn à tìckèt àppèàrs ìn thè sàmè thrèàd às tèxts, pòrtàl rèplìès, ànd nòtès. Èmàìl ìs thè ònly chànnèl whòsè còntènt èvèry màìl sèrvèr àlòng thè ròùtè càn rèàd. [[#clìènt-dàtà #èncryptìòn #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès àn òùtbòùnd èmàìl rèàch thè thrèàd? ••••••••••••••** Thè bròwsèr sènds thè rèlày thè tìckèt, à sùbjèct, ànd à bòdy. Thè sèrvèr lòòks ùp ànd dècrypts thè clìènt's àddrèss òn ìts òwn ràthèr thàn àccèptìng ònè fròm thè rèqùèst. À còpy òf thè mèssàgè ìs sèàlèd wìth thè tìckèt kèy ànd wrìttèn tò thè thrèàd às à fòllòw-ùp. Whèn thè clìènt hàs àn àctìvè chànnèl kèy, à sècònd còpy ìs sèàlèd tò thàt kèy sò thè fòllòw-ùp rècòrd sùrvìvès à màìlbòx nòbòdy rèàds. Àn òrgànìzàtìòn càn swìtch ìts èmàìl chànnèl òff. Whèn thè chànnèl ìs òff, thè rèlày rèfùsès thè rèqùèst bèfòrè dècryptìng àn àddrèss. [Chànnèl pòlìcy](#àdmìn-còmms/chànnèl-pòlìcy) còvèrs thàt sèttìng. [Sèndìng à rèply](#tìckèt-dètàìl/rèply) còvèrs thè còpìès à mèssàgè pròdùcès, ànd [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs thè bùffèr hàndlìng thìs èndpòìnt shàrès wìth thè tèxt pàth. [[#èncryptìòn #sèrvèr-hòlds #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rèply àddrèss ànd tòkèn. ••••••••** Èàch tìckèt gèts à rèply àddrèss càrryìng à 128-bìt ràndòm tòkèn. Thè sèrvèr stòrès ònly à kèyèd hàsh òf thàt tòkèn. Thè àddrèss èxìsts ìn thè òùtbòùnd hèàdèr ànd ìn thè clìènt's màìlbòx ànd ìn nò lòcàtìòn thè dàtàbàsè càn rèvèàl. Rèvòkìng thè tòkèn stòps èmàìlèd rèplìès fròm ròùtìng tò thàt thrèàd. Èàrlìèr rèply àddrèssès stày ròùtàblè ùntìl thè ùsèr rèvòkès thèm. [[#kèys #sèrvèr-hòlds #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt ìs àn ìnbòùnd èmàìl trùstèd fòr? ••••••••••••** Thè rèply tòkèn dècìdès whìch tìckèt à mèssàgè lànds òn. Thè Fròm àddrèss ìs stòrèd ànd shòwn às clàìmèd, nèvèr ùsèd fòr ròùtìng. Ànyònè càn wrìtè àny àddrèss ìntò ìt, ànd èàch ìnbòùnd fòllòw-ùp màrks thàt càùtìòn.
- Àttàchmènts àrè còùntèd ànd dròppèd ràthèr thàn ìmpòrtèd.
- À sùbjèct òr bòdy thàt èxcèèds thè lèngth lìmìt ìs shòrtènèd ràthèr thàn rèfùsèd.
- À mèssàgè àrrìvìng òn à clòsèd tìckèt rèòpèns ìt.
Whèn thè nèwèst fòllòw-ùp fròm thè clìènt ìs àn èmàìl, còmpòsìng à tèxt òr à pòrtàl rèply rèpòrts thàt thè clìènt mày bè wàìtìng òn èmàìl. Thè càùtìòn càn bè dìsmìssèd pèr tìckèt fòr thè rèst òf thè sèssìòn. Ìt dòès nòt àppèàr whèn thè òrgànìzàtìòn hàs ìts èmàìl chànnèl swìtchèd òff. [Chànnèl wàrnìngs](#tìckèt-dètàìl/èxpòsùrè-hìnts) còvèrs thè fùll sèt òf chànnèl càùtìòns. [[#fàìlùrè-stàtès #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rèlày hàndlèrs ànd thè tòkèn ròw. ••••••••••••** Thè òùtbòùnd pàth ìs \`/rèlày/èmàìl\` ìn \`pàckàgès/sèrvèr/src/ròùtès/rèlày.ts\`, wìth rèply àddrèss ànd fòòtèr àssèmbly ìn \`pàckàgès/sèrvèr/src/èmàìl/èmàìl-rèlày-sèrvìcè.ts\` ànd thè tòkèn ròw fròm \`èmàìl_rèply_tòkèns\` ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`. Ìnbòùnd màìl ìs àccèptèd by \`ìnbòùnd-rècèìvèr.ts\` ànd wrìttèn by \`ìnbòùnd-èmàìl.ts\`. Thè bùbblès àrè \`ÈmàìlBùbblèCòntènt.svèltè\` ànd \`ÈmàìlÌnbòùndBùbblèCòntènt.svèltè\`. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Email sent and received on a ticket appears in the same thread as texts, portal replies, and notes. Email is the only channel whose content every mail server..." |
*
* @param {Demo_Narrative_Topic_Email_Thread_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_email_thread_body = /** @type {((inputs?: Demo_Narrative_Topic_Email_Thread_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Email_Thread_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_email_thread_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_email_thread_body(inputs)
	return en_demo_narrative_topic_email_thread_body(inputs)
});