/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Library_Tools_BodyInputs */

const en_demo_narrative_topic_library_tools_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Tools_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Four view modes are available, with sorting by creation date, last edit, or rating, and filters for category, author, a creation date range, and two rating bands. The server evaluates the sort, the rating band, the author, and the date range inside its paged query. Regardless of sort order, the date filter applies to when an article was created. [Browsing articles](#library/browse) covers how the category filter splits between server and browser. [[#client-data]]
**What do the two rating bands mean?** The stored rating is a ranking score, not a tally of votes. The Positive band takes articles scoring above a near-zero floor. The Highly rated band takes articles scoring at or above half. [Helpfulness voting](#library/vote) covers how that score is computed. [[#metadata]]
**What stays on the device?** The selected view mode and saved filter combinations are kept in localStorage under their own keys, with no copy on the server. A saved combination whose state does not match the expected shape is discarded when the list loads. The filter name and state are sealed under the organization key. [Saved filters](#tickets/saved-filters) covers the same storage pattern and its privacy consequences on the ticket list. [[#privacy #server-holds]]
**What does select mode act on?** A category move applies to each selected article and reports per-article outcomes. Bulk delete works the same way. Deleting requires the Delete knowledge base articles permission and a confirmation. Each delete removes the article's attachment blobs and its votes along with the row. [File attachments](#library/attachments) covers what a blob holds. [[#permissions #failure-states]]
**The stores and the delete path.** \`kbFilterStore\` in \`packages/client/src/lib/stores/kb-filters.svelte.ts\` maps the filter state onto \`kbItemListInputSchema\`. The view mode is \`care-y-kb-view-mode\` in \`kb-view-mode.svelte.ts\`, validated against four accepted values on load. Saved combinations use the key \`care-y:kb-saved-filters\` in \`kb-saved-filters.svelte.ts\` and are checked against \`kbSavedFilterStateSchema\` at load time. The article row is deleted first, and attachment blobs are swept afterward. [View modes](#tickets/view-modes) covers the same four presentations on the ticket list. [[#client-data]]`)
};

const es_demo_narrative_topic_library_tools_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Tools_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Hay cuatro modos de vista disponibles, con ordenamiento por fecha de creación, última edición o valoración, y filtros por categoría, autor, un rango de fechas de creación y dos bandas de valoración. El servidor evalúa el ordenamiento, la banda de valoración, el autor y el rango de fechas dentro de su consulta paginada. Independientemente del orden elegido, el filtro de fechas se aplica a la fecha de creación del artículo. [Navegar artículos](#library/browse) trata cómo se divide el filtro de categoría entre servidor y navegador. [[#client-data]]
**¿Qué significan las dos bandas de valoración?** La puntuación almacenada es una puntuación de clasificación, no un conteo de votos. La banda Positiva toma artículos con una puntuación por encima de un umbral cercano a cero. La banda Muy valorado toma artículos con una puntuación igual o superior a la mitad. [Votación de utilidad](#library/vote) trata cómo se calcula esa puntuación. [[#metadata]]
**¿Qué queda en el dispositivo?** El modo de vista seleccionado y las combinaciones de filtros guardadas se mantienen en localStorage bajo claves propias, sin copia en el servidor. Una combinación guardada cuyo estado no coincide con la forma esperada se descarta cuando la lista se carga. El nombre y el estado del filtro están sellados con la clave de la organización. [Filtros guardados](#tickets/saved-filters) trata el mismo patrón de almacenamiento y sus consecuencias de privacidad en la lista de tickets. [[#privacy #server-holds]]
**¿Sobre qué actúa el modo de selección?** Un cambio de categoría se aplica a cada artículo seleccionado y reporta resultados por artículo. La eliminación masiva funciona del mismo modo. Eliminar requiere el permiso Eliminar artículos de la base de conocimiento y una confirmación. Cada eliminación borra los blobs de adjuntos del artículo y sus votos junto con la fila. [Archivos adjuntos](#library/attachments) trata lo que contiene un blob. [[#permissions #failure-states]]
**Los stores y la ruta de eliminación.** \`kbFilterStore\` en \`packages/client/src/lib/stores/kb-filters.svelte.ts\` mapea el estado de los filtros a \`kbItemListInputSchema\`. El modo de vista es \`care-y-kb-view-mode\` en \`kb-view-mode.svelte.ts\`, validado contra cuatro valores aceptados al cargar. Las combinaciones guardadas usan la clave \`care-y:kb-saved-filters\` en \`kb-saved-filters.svelte.ts\` y se verifican contra \`kbSavedFilterStateSchema\` al cargar. La fila del artículo se elimina primero, y los blobs de adjuntos se barren después. [Modos de vista](#tickets/view-modes) trata las mismas cuatro presentaciones en la lista de tickets. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_library_tools_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Tools_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Fòùr vìèw mòdès àrè àvàìlàblè, wìth sòrtìng by crèàtìòn dàtè, làst èdìt, òr ràtìng, ànd fìltèrs fòr càtègòry, àùthòr, à crèàtìòn dàtè ràngè, ànd twò ràtìng bànds. Thè sèrvèr èvàlùàtès thè sòrt, thè ràtìng bànd, thè àùthòr, ànd thè dàtè ràngè ìnsìdè ìts pàgèd qùèry. Règàrdlèss òf sòrt òrdèr, thè dàtè fìltèr àpplìès tò whèn àn àrtìclè wàs crèàtèd. [Bròwsìng àrtìclès](#lìbràry/bròwsè) còvèrs hòw thè càtègòry fìltèr splìts bètwèèn sèrvèr ànd bròwsèr. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dò thè twò ràtìng bànds mèàn? •••••••••••** Thè stòrèd ràtìng ìs à rànkìng scòrè, nòt à tàlly òf vòtès. Thè Pòsìtìvè bànd tàkès àrtìclès scòrìng àbòvè à nèàr-zèrò flòòr. Thè Hìghly ràtèd bànd tàkès àrtìclès scòrìng àt òr àbòvè hàlf. [Hèlpfùlnèss vòtìng](#lìbràry/vòtè) còvèrs hòw thàt scòrè ìs còmpùtèd. [[#mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt stàys òn thè dèvìcè? ••••••••** Thè sèlèctèd vìèw mòdè ànd sàvèd fìltèr còmbìnàtìòns àrè kèpt ìn lòcàlStòràgè ùndèr thèìr òwn kèys, wìth nò còpy òn thè sèrvèr. À sàvèd còmbìnàtìòn whòsè stàtè dòès nòt màtch thè èxpèctèd shàpè ìs dìscàrdèd whèn thè lìst lòàds. Thè fìltèr nàmè ànd stàtè àrè sèàlèd ùndèr thè òrgànìzàtìòn kèy. [Sàvèd fìltèrs](#tìckèts/sàvèd-fìltèrs) còvèrs thè sàmè stòràgè pàttèrn ànd ìts prìvàcy cònsèqùèncès òn thè tìckèt lìst. [[#prìvàcy #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès sèlèct mòdè àct òn? •••••••••** À càtègòry mòvè àpplìès tò èàch sèlèctèd àrtìclè ànd rèpòrts pèr-àrtìclè òùtcòmès. Bùlk dèlètè wòrks thè sàmè wày. Dèlètìng rèqùìrès thè Dèlètè knòwlèdgè bàsè àrtìclès pèrmìssìòn ànd à cònfìrmàtìòn. Èàch dèlètè rèmòvès thè àrtìclè's àttàchmènt blòbs ànd ìts vòtès àlòng wìth thè ròw. [Fìlè àttàchmènts](#lìbràry/àttàchmènts) còvèrs whàt à blòb hòlds. [[#pèrmìssìòns #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè stòrès ànd thè dèlètè pàth. ••••••••••** \`kbFìltèrStòrè\` ìn \`pàckàgès/clìènt/src/lìb/stòrès/kb-fìltèrs.svèltè.ts\` màps thè fìltèr stàtè òntò \`kbÌtèmLìstÌnpùtSchèmà\`. Thè vìèw mòdè ìs \`càrè-y-kb-vìèw-mòdè\` ìn \`kb-vìèw-mòdè.svèltè.ts\`, vàlìdàtèd àgàìnst fòùr àccèptèd vàlùès òn lòàd. Sàvèd còmbìnàtìòns ùsè thè kèy \`càrè-y:kb-sàvèd-fìltèrs\` ìn \`kb-sàvèd-fìltèrs.svèltè.ts\` ànd àrè chèckèd àgàìnst \`kbSàvèdFìltèrStàtèSchèmà\` àt lòàd tìmè. Thè àrtìclè ròw ìs dèlètèd fìrst, ànd àttàchmènt blòbs àrè swèpt àftèrwàrd. [Vìèw mòdès](#tìckèts/vìèw-mòdès) còvèrs thè sàmè fòùr prèsèntàtìòns òn thè tìckèt lìst. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Four view modes are available, with sorting by creation date, last edit, or rating, and filters for category, author, a creation date range, and two rating b..." |
*
* @param {Demo_Narrative_Topic_Library_Tools_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_library_tools_body = /** @type {((inputs?: Demo_Narrative_Topic_Library_Tools_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Library_Tools_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_library_tools_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_library_tools_body(inputs)
	return en_demo_narrative_topic_library_tools_body(inputs)
});