/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Close_Reopen_BodyInputs */

const en_demo_narrative_topic_close_reopen_body = /** @type {(inputs: Demo_Narrative_Topic_Close_Reopen_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Closing a ticket records that the work on it is finished. Reopening puts the ticket back in the working lists. Both require the Change case status permission. A ticket can be reopened at any time after it was closed. [[#tickets #permissions]]
**What does closing check first?** A ticket with unresolved linked tickets cannot be closed. The organization can mark note types as required at close, and the close sequence prompts for each one in turn. Each prompt can be skipped, so the requirement is a reminder, not a gate. A note written at a prompt is sealed in the browser under the ticket key. If a note fails to save, the prompt stays and the close does not proceed. If notes succeed but the close itself fails, the notes already written remain on the ticket. [Internal notes](#ticket-detail/notes) covers the types. [[#failure-states #encryption]]
**What does a close change on the server?** The server sets the status to closed and writes a system event into the thread. The server also deletes every account's read cursor for the ticket. [Date separators](#ticket-detail/date-separators) covers the read cursor. The status is a plaintext column. A database dump shows which tickets are closed and when each one closed. [[#server-holds #metadata #retention]]
**What does a reopen change?** A manual reopen sets the status back to open and writes its own system event. A text or email arriving from the client on a closed ticket reopens it before the message is written, so a client who makes contact again does not land in a ticket no user is watching. One shared path handles the automatic reopen for both channels. [Email in the conversation](#ticket-detail/email-thread) covers the inbound email route. [The permission system](#deep-dive/the-permission-system) covers the grant. [[#permissions #telephony]]
**The close composable and the reopen service.** The prompts are \`create-close-resolution.svelte.ts\` in \`packages/client/src/lib/composables/ticket-detail/\`, the close and reopen mutations are in \`packages/server/src/tickets/ticket-service.ts\`, and the automatic reopen is \`packages/server/src/tickets/ticket-reopen.ts\`. [[#client-data]]`)
};

const es_demo_narrative_topic_close_reopen_body = /** @type {(inputs: Demo_Narrative_Topic_Close_Reopen_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cerrar un ticket registra que el trabajo en él ha terminado. Reabrir devuelve el ticket a las listas activas. Ambas acciones requieren el permiso Cambiar estado del caso. Un ticket se puede reabrir en cualquier momento tras su cierre. [[#tickets #permissions]]
**¿Qué comprueba el cierre primero?** Un ticket con tickets vinculados sin resolver no se puede cerrar. La organización puede marcar tipos de nota como obligatorios al cierre, y la secuencia de cierre solicita cada uno por turno. Cada solicitud se puede omitir, así que el requisito es un recordatorio, no una restricción. Una nota escrita en ese momento se sella en el navegador con la clave del ticket. Si una nota falla al guardarse, la solicitud permanece y el cierre no avanza. Si las notas se guardan pero el propio cierre falla, las notas ya escritas permanecen en el ticket. [Notas internas](#ticket-detail/notes) trata los tipos. [[#failure-states #encryption]]
**¿Qué cambia un cierre en el servidor?** El servidor establece el estado a cerrado y escribe un evento de sistema en el hilo. El servidor también elimina el cursor de lectura de cada cuenta para el ticket. [Separadores de fecha](#ticket-detail/date-separators) trata el cursor de lectura. El estado es una columna en texto plano. Un volcado de la base de datos muestra qué tickets están cerrados y cuándo se cerró cada uno. [[#server-holds #metadata #retention]]
**¿Qué cambia una reapertura?** Una reapertura manual restablece el estado a abierto y escribe su propio evento de sistema. Un mensaje de texto o correo electrónico del cliente en un ticket cerrado lo reabre antes de que el mensaje se escriba, para que un cliente que vuelve a comunicarse no quede en un ticket que nadie vigila. Una sola ruta compartida gestiona la reapertura automática en ambos canales. [Correo electrónico en la conversación](#ticket-detail/email-thread) trata la ruta de correo entrante. [El sistema de permisos](#deep-dive/the-permission-system) trata el permiso. [[#permissions #telephony]]
**El composable de cierre y el servicio de reapertura.** Las solicitudes son \`create-close-resolution.svelte.ts\` en \`packages/client/src/lib/composables/ticket-detail/\`, las mutaciones de cierre y reapertura están en \`packages/server/src/tickets/ticket-service.ts\`, y la reapertura automática está en \`packages/server/src/tickets/ticket-reopen.ts\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_close_reopen_body = /** @type {(inputs: Demo_Narrative_Topic_Close_Reopen_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Clòsìng à tìckèt rècòrds thàt thè wòrk òn ìt ìs fìnìshèd. Rèòpènìng pùts thè tìckèt bàck ìn thè wòrkìng lìsts. Bòth rèqùìrè thè Chàngè càsè stàtùs pèrmìssìòn. À tìckèt càn bè rèòpènèd àt àny tìmè àftèr ìt wàs clòsèd. [[#tìckèts #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès clòsìng chèck fìrst? •••••••••** À tìckèt wìth ùnrèsòlvèd lìnkèd tìckèts cànnòt bè clòsèd. Thè òrgànìzàtìòn càn màrk nòtè typès às rèqùìrèd àt clòsè, ànd thè clòsè sèqùèncè pròmpts fòr èàch ònè ìn tùrn. Èàch pròmpt càn bè skìppèd, sò thè rèqùìrèmènt ìs à rèmìndèr, nòt à gàtè. À nòtè wrìttèn àt à pròmpt ìs sèàlèd ìn thè bròwsèr ùndèr thè tìckèt kèy. Ìf à nòtè fàìls tò sàvè, thè pròmpt stàys ànd thè clòsè dòès nòt pròcèèd. Ìf nòtès sùccèèd bùt thè clòsè ìtsèlf fàìls, thè nòtès àlrèàdy wrìttèn rèmàìn òn thè tìckèt. [Ìntèrnàl nòtès](#tìckèt-dètàìl/nòtès) còvèrs thè typès. [[#fàìlùrè-stàtès #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à clòsè chàngè òn thè sèrvèr? ••••••••••••** Thè sèrvèr sèts thè stàtùs tò clòsèd ànd wrìtès à systèm èvènt ìntò thè thrèàd. Thè sèrvèr àlsò dèlètès èvèry àccòùnt's rèàd cùrsòr fòr thè tìckèt. [Dàtè sèpàràtòrs](#tìckèt-dètàìl/dàtè-sèpàràtòrs) còvèrs thè rèàd cùrsòr. Thè stàtùs ìs à plàìntèxt còlùmn. À dàtàbàsè dùmp shòws whìch tìckèts àrè clòsèd ànd whèn èàch ònè clòsèd. [[#sèrvèr-hòlds #mètàdàtà #rètèntìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à rèòpèn chàngè? ••••••••** À mànùàl rèòpèn sèts thè stàtùs bàck tò òpèn ànd wrìtès ìts òwn systèm èvènt. À tèxt òr èmàìl àrrìvìng fròm thè clìènt òn à clòsèd tìckèt rèòpèns ìt bèfòrè thè mèssàgè ìs wrìttèn, sò à clìènt whò màkès còntàct àgàìn dòès nòt lànd ìn à tìckèt nò ùsèr ìs wàtchìng. Ònè shàrèd pàth hàndlès thè àùtòmàtìc rèòpèn fòr bòth chànnèls. [Èmàìl ìn thè cònvèrsàtìòn](#tìckèt-dètàìl/èmàìl-thrèàd) còvèrs thè ìnbòùnd èmàìl ròùtè. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs thè grànt. [[#pèrmìssìòns #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè clòsè còmpòsàblè ànd thè rèòpèn sèrvìcè. ••••••••••••••** Thè pròmpts àrè \`crèàtè-clòsè-rèsòlùtìòn.svèltè.ts\` ìn \`pàckàgès/clìènt/src/lìb/còmpòsàblès/tìckèt-dètàìl/\`, thè clòsè ànd rèòpèn mùtàtìòns àrè ìn \`pàckàgès/sèrvèr/src/tìckèts/tìckèt-sèrvìcè.ts\`, ànd thè àùtòmàtìc rèòpèn ìs \`pàckàgès/sèrvèr/src/tìckèts/tìckèt-rèòpèn.ts\`. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Closing a ticket records that the work on it is finished. Reopening puts the ticket back in the working lists. Both require the Change case status permission..." |
*
* @param {Demo_Narrative_Topic_Close_Reopen_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_close_reopen_body = /** @type {((inputs?: Demo_Narrative_Topic_Close_Reopen_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Close_Reopen_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_close_reopen_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_close_reopen_body(inputs)
	return en_demo_narrative_topic_close_reopen_body(inputs)
});