/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Library_Search_BodyInputs */

const en_demo_narrative_topic_library_search_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Search_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Searching the library matches the term against the titles and excerpts already decrypted in the browser, orders the list by match quality, and sends no part of the term to the server. The library page and the global search overlay both use the same matching function. [[#privacy #client-data #search]]
**The deeper search and when it starts.** The deeper search loads all remaining article pages, then requests the encrypted bodies of every article whose title and excerpt produced no match. Each body is decrypted in the browser and matched there. The deeper search starts on its own when the title and excerpt matches produce no result, the term is at least two characters, and the initial page has finished loading. The user can start it manually when no deeper search is running or finished for the current term and the term is at least two characters. A counter reports how many articles have been searched against the total. [[#encryption #client-data]]
**What does the server learn from a deeper search?** The server does not receive the term or learn which articles matched, because both stay in the browser. The request is a plain fetch by identifier and no record of it is written to the database. [[#server-holds #metadata]]
**When does the deeper search stop?** The body request accepts at most two hundred identifiers. An organization with more non-matching articles sends them in batches of two hundred. A network failure during any batch marks the run as incomplete and offers a retry. [[#failure-states]]
**The KB provider and the body endpoint.** The in-page matching and the global search overlay share \`fuzzySearch\` in \`packages/client/src/lib/search/fuzzy.ts\`. The deeper search run is \`createDeepSearch\` in \`packages/client/src/lib/search/deep-search.svelte.ts\`, driven by the \`kb\` provider's \`fullSearch\` in \`packages/client/src/lib/search/providers/kb.ts\`. The body endpoint is \`listBodies\` in \`packages/server/src/routes/kb.ts\`, whose input cap is \`listKbBodiesInputSchema\` in \`packages/shared/src/schemas/kb.ts\`. [How global search works](#search/how-it-works) covers the overlay that searches every surface at once. [[#client-data]]`)
};

const es_demo_narrative_topic_library_search_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Search_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La búsqueda en la biblioteca compara el término con los títulos y extractos ya descifrados en el navegador, ordena la lista por calidad de coincidencia y no envía ninguna parte del término al servidor. La página de la biblioteca y la superposición de búsqueda global usan la misma función de comparación. [[#privacy #client-data #search]]
**La búsqueda profunda y cuándo se inicia.** La búsqueda profunda carga todas las páginas de artículos restantes y luego solicita los cuerpos cifrados de cada artículo cuyo título y extracto no produjeron coincidencia. Cada cuerpo se descifra en el navegador y se compara allí. La búsqueda profunda se inicia por su cuenta cuando las coincidencias de título y extracto no producen ningún resultado, el término tiene al menos dos caracteres y la página inicial ha terminado de cargar. La persona usuaria puede iniciarla manualmente cuando no hay una búsqueda profunda en curso ni finalizada para el término actual y el término tiene al menos dos caracteres. Un contador informa cuántos artículos se han buscado del total. [[#encryption #client-data]]
**¿Qué aprende el servidor de una búsqueda profunda?** El servidor no recibe el término ni sabe qué artículos coincidieron, porque ambos permanecen en el navegador. La petición es una consulta simple por identificador y no se escribe ningún registro de ella en la base de datos. [[#server-holds #metadata]]
**¿Cuándo se detiene la búsqueda profunda?** La petición de cuerpos acepta como máximo doscientos identificadores. Una organización con más artículos sin coincidencia los envía en lotes de doscientos. Un fallo de red durante cualquier lote marca la ejecución como incompleta y ofrece un reintento. [[#failure-states]]
**El proveedor KB y el endpoint de cuerpos.** La comparación en la página y la superposición de búsqueda global comparten \`fuzzySearch\` en \`packages/client/src/lib/search/fuzzy.ts\`. La ejecución de la búsqueda profunda es \`createDeepSearch\` en \`packages/client/src/lib/search/deep-search.svelte.ts\`, impulsada por el \`fullSearch\` del proveedor \`kb\` en \`packages/client/src/lib/search/providers/kb.ts\`. El endpoint de cuerpos es \`listBodies\` en \`packages/server/src/routes/kb.ts\`, cuyo límite de entrada es \`listKbBodiesInputSchema\` en \`packages/shared/src/schemas/kb.ts\`. [Cómo funciona la búsqueda global](#search/how-it-works) trata la superposición que busca en todas las superficies a la vez. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_library_search_body = /** @type {(inputs: Demo_Narrative_Topic_Library_Search_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Sèàrchìng thè lìbràry màtchès thè tèrm àgàìnst thè tìtlès ànd èxcèrpts àlrèàdy dècryptèd ìn thè bròwsèr, òrdèrs thè lìst by màtch qùàlìty, ànd sènds nò pàrt òf thè tèrm tò thè sèrvèr. Thè lìbràry pàgè ànd thè glòbàl sèàrch òvèrlày bòth ùsè thè sàmè màtchìng fùnctìòn. [[#prìvàcy #clìènt-dàtà #sèàrch]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè dèèpèr sèàrch ànd whèn ìt stàrts. ••••••••••••** Thè dèèpèr sèàrch lòàds àll rèmàìnìng àrtìclè pàgès, thèn rèqùèsts thè èncryptèd bòdìès òf èvèry àrtìclè whòsè tìtlè ànd èxcèrpt pròdùcèd nò màtch. Èàch bòdy ìs dècryptèd ìn thè bròwsèr ànd màtchèd thèrè. Thè dèèpèr sèàrch stàrts òn ìts òwn whèn thè tìtlè ànd èxcèrpt màtchès pròdùcè nò rèsùlt, thè tèrm ìs àt lèàst twò chàràctèrs, ànd thè ìnìtìàl pàgè hàs fìnìshèd lòàdìng. Thè ùsèr càn stàrt ìt mànùàlly whèn nò dèèpèr sèàrch ìs rùnnìng òr fìnìshèd fòr thè cùrrènt tèrm ànd thè tèrm ìs àt lèàst twò chàràctèrs. À còùntèr rèpòrts hòw màny àrtìclès hàvè bèèn sèàrchèd àgàìnst thè tòtàl. [[#èncryptìòn #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr lèàrn fròm à dèèpèr sèàrch? •••••••••••••••** Thè sèrvèr dòès nòt rècèìvè thè tèrm òr lèàrn whìch àrtìclès màtchèd, bècàùsè bòth stày ìn thè bròwsèr. Thè rèqùèst ìs à plàìn fètch by ìdèntìfìèr ànd nò rècòrd òf ìt ìs wrìttèn tò thè dàtàbàsè. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn dòès thè dèèpèr sèàrch stòp? ••••••••••** Thè bòdy rèqùèst àccèpts àt mòst twò hùndrèd ìdèntìfìèrs. Àn òrgànìzàtìòn wìth mòrè nòn-màtchìng àrtìclès sènds thèm ìn bàtchès òf twò hùndrèd. À nètwòrk fàìlùrè dùrìng àny bàtch màrks thè rùn às ìncòmplètè ànd òffèrs à rètry. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè KB pròvìdèr ànd thè bòdy èndpòìnt. ••••••••••••** Thè ìn-pàgè màtchìng ànd thè glòbàl sèàrch òvèrlày shàrè \`fùzzySèàrch\` ìn \`pàckàgès/clìènt/src/lìb/sèàrch/fùzzy.ts\`. Thè dèèpèr sèàrch rùn ìs \`crèàtèDèèpSèàrch\` ìn \`pàckàgès/clìènt/src/lìb/sèàrch/dèèp-sèàrch.svèltè.ts\`, drìvèn by thè \`kb\` pròvìdèr's \`fùllSèàrch\` ìn \`pàckàgès/clìènt/src/lìb/sèàrch/pròvìdèrs/kb.ts\`. Thè bòdy èndpòìnt ìs \`lìstBòdìès\` ìn \`pàckàgès/sèrvèr/src/ròùtès/kb.ts\`, whòsè ìnpùt càp ìs \`lìstKbBòdìèsÌnpùtSchèmà\` ìn \`pàckàgès/shàrèd/src/schèmàs/kb.ts\`. [Hòw glòbàl sèàrch wòrks](#sèàrch/hòw-ìt-wòrks) còvèrs thè òvèrlày thàt sèàrchès èvèry sùrfàcè àt òncè. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Searching the library matches the term against the titles and excerpts already decrypted in the browser, orders the list by match quality, and sends no part ..." |
*
* @param {Demo_Narrative_Topic_Library_Search_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_library_search_body = /** @type {((inputs?: Demo_Narrative_Topic_Library_Search_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Library_Search_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_library_search_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_library_search_body(inputs)
	return en_demo_narrative_topic_library_search_body(inputs)
});