/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Portal_Upgrade_BodyInputs */

const en_demo_narrative_client_portal_upgrade_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Upgrade_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A client on a secure link can raise their own protection without asking anyone in the organization, by adding a spoken passphrase to the link or by moving to an account with a username and a password. [[#portal #privacy]]
**What each path is offered to.** A bare link is offered both. A link that already has a passphrase is offered the account, and gains access to the contact details the organization holds on file, which a bare link is refused because sealing them to a key derived from the link alone would hand them to anyone holding it. A client already on an account is offered nothing further, because there is nothing stronger to move to. [Portal and channel lifecycle](#deep-dive/portal-channel-lifecycle) covers the three tiers. [[#portal #permissions]]
**Adding a passphrase.** The browser draws five random words from a standard word list, which the client can replace with their own. Submitting derives a new channel key from the words, re-encrypts every message the client's device can still open under that key, and declares the rest as left behind. The server checks inside one transaction that the two lists exactly cover the channel's messages, so a message that arrived mid-upgrade aborts the write rather than being orphaned. Afterward the address still resolves and no longer opens the conversation on its own. [[#keys #encryption #failure-states]]
**Creating an account.** The client chooses a username and a password of at least eight characters, and the password runs the same derivation a member of staff signs in through. In one transaction the old channel is revoked, the account and its channel are created, the re-encrypted messages move across, and anything the device could not open is deleted, since it was already unreadable there. The secure link stops working at that moment. [Account sign in](#client-account/sign-in) covers what the account does afterward. [[#keys #portal]]
**What the server learns from either.** Neither the passphrase nor the password reaches the server. Both are stretched in the browser and folded into a blinded value that an evaluation answers without seeing the input or the output, and what the server ends up storing is a public key, a hash of a bearer token and a key check. A username is stored as a keyed hash rather than as text, and creating one reports that a name is taken, which is the one place a name can be probed. [How keys are derived](#deep-dive/how-keys-are-derived) covers the evaluation. [[#server-holds #keys #metadata]]
**The upgrade flows and their guards.** The chooser is \`UpgradeChooser.svelte\`, the two forms are \`AddPassphraseForm.svelte\` and \`AccountCreateForm.svelte\` in \`packages/client/src/lib/portal/\`, and the re-encryption helpers are \`add-passphrase-crypto.ts\` and \`account-crypto.ts\` beside them. The coverage guard is \`hasExactMessageCoverage\` in \`packages/server/src/portal/message-coverage.ts\`, called by \`addPassphrase\` in \`channel-service.ts\` and by \`upgradeFromSecureLink\` in \`account-service.ts\`. [[#portal #encryption]]`)
};

const es_demo_narrative_client_portal_upgrade_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Upgrade_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un cliente con un enlace seguro puede reforzar su propia protección sin pedírselo a nadie de la organización, añadiendo al enlace una frase de paso hablada o pasando a una cuenta con nombre de usuario y contraseña. [[#portal #privacy]]
**A quién se ofrece cada vía.** A un enlace simple se le ofrecen las dos. A un enlace que ya tiene frase de paso se le ofrece la cuenta, y obtiene acceso a los datos de contacto que la organización tiene registrados, que a un enlace simple se le niegan porque sellarlos con una clave derivada solo del enlace se los entregaría a cualquiera que lo tuviera. A un cliente que ya está en una cuenta no se le ofrece nada más, porque no hay nada más fuerte a lo que pasar. [El ciclo de vida del portal y los canales](#deep-dive/portal-channel-lifecycle) trata los tres niveles. [[#portal #permissions]]
**Añadir una frase de paso.** El navegador sortea cinco palabras al azar de una lista estándar, que el cliente puede sustituir por las suyas. Al enviarlas se deriva una nueva clave del canal, se vuelve a cifrar con ella cada mensaje que el dispositivo del cliente todavía puede abrir y se declaran los demás como dejados atrás. El servidor comprueba dentro de una sola transacción que las dos listas cubren exactamente los mensajes del canal, de modo que un mensaje llegado a mitad de la operación la aborta en lugar de quedar huérfano. Después, la dirección sigue resolviendo y ya no abre por sí sola la conversación. [[#keys #encryption #failure-states]]
**Crear una cuenta.** El cliente elige un nombre de usuario y una contraseña de al menos ocho caracteres, y la contraseña recorre la misma derivación con la que inicia sesión el personal. En una sola transacción se revoca el canal anterior, se crean la cuenta y su canal, los mensajes vueltos a cifrar pasan al nuevo y se elimina lo que el dispositivo no pudo abrir, ya que allí era ilegible de todos modos. El enlace seguro deja de funcionar en ese momento. [Inicio de sesión de la cuenta](#client-account/sign-in) trata lo que hace la cuenta a partir de entonces. [[#keys #portal]]
**Lo que el servidor averigua con cualquiera de las dos.** Ni la frase de paso ni la contraseña de la cuenta llegan al servidor. Las dos se estiran en el navegador y se integran en un valor cegado que una evaluación responde sin ver la entrada ni la salida, y lo que el servidor acaba guardando es una clave pública, un hash de un testigo de acceso y una comprobación de clave. Un nombre de usuario se guarda como hash con clave y no como texto, y al crear uno se informa de que un nombre está ocupado, que es el único punto donde se puede sondear un nombre. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata la evaluación. [[#server-holds #keys #metadata]]
**Los flujos de mejora y sus guardas.** El selector es \`UpgradeChooser.svelte\`, los dos formularios son \`AddPassphraseForm.svelte\` y \`AccountCreateForm.svelte\`, en \`packages/client/src/lib/portal/\`, y los auxiliares de recifrado son \`add-passphrase-crypto.ts\` y \`account-crypto.ts\`, junto a ellos. La guarda de cobertura es \`hasExactMessageCoverage\`, en \`packages/server/src/portal/message-coverage.ts\`, invocada por \`addPassphrase\`, en \`channel-service.ts\`, y por \`upgradeFromSecureLink\`, en \`account-service.ts\`. [[#portal #encryption]]`)
};

const en_xa2_demo_narrative_client_portal_upgrade_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Upgrade_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À clìènt òn à sècùrè lìnk càn ràìsè thèìr òwn pròtèctìòn wìthòùt àskìng ànyònè ìn thè òrgànìzàtìòn, by àddìng à spòkèn pàssphràsè tò thè lìnk òr by mòvìng tò àn àccòùnt wìth à ùsèrnàmè ànd à pàsswòrd. [[#pòrtàl #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt èàch pàth ìs òffèrèd tò. •••••••••** À bàrè lìnk ìs òffèrèd bòth. À lìnk thàt àlrèàdy hàs à pàssphràsè ìs òffèrèd thè àccòùnt, ànd gàìns àccèss tò thè còntàct dètàìls thè òrgànìzàtìòn hòlds òn fìlè, whìch à bàrè lìnk ìs rèfùsèd bècàùsè sèàlìng thèm tò à kèy dèrìvèd fròm thè lìnk àlònè wòùld hànd thèm tò ànyònè hòldìng ìt. À clìènt àlrèàdy òn àn àccòùnt ìs òffèrèd nòthìng fùrthèr, bècàùsè thèrè ìs nòthìng stròngèr tò mòvè tò. [Pòrtàl ànd chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thè thrèè tìèrs. [[#pòrtàl #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àddìng à pàssphràsè. ••••••** Thè bròwsèr dràws fìvè ràndòm wòrds fròm à stàndàrd wòrd lìst, whìch thè clìènt càn rèplàcè wìth thèìr òwn. Sùbmìttìng dèrìvès à nèw chànnèl kèy fròm thè wòrds, rè-èncrypts èvèry mèssàgè thè clìènt's dèvìcè càn stìll òpèn ùndèr thàt kèy, ànd dèclàrès thè rèst às lèft bèhìnd. Thè sèrvèr chècks ìnsìdè ònè trànsàctìòn thàt thè twò lìsts èxàctly còvèr thè chànnèl's mèssàgès, sò à mèssàgè thàt àrrìvèd mìd-ùpgràdè àbòrts thè wrìtè ràthèr thàn bèìng òrphànèd. Àftèrwàrd thè àddrèss stìll rèsòlvès ànd nò lòngèr òpèns thè cònvèrsàtìòn òn ìts òwn. [[#kèys #èncryptìòn #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Crèàtìng àn àccòùnt. ••••••** Thè clìènt chòòsès à ùsèrnàmè ànd à pàsswòrd òf àt lèàst èìght chàràctèrs, ànd thè pàsswòrd rùns thè sàmè dèrìvàtìòn à mèmbèr òf stàff sìgns ìn thròùgh. Ìn ònè trànsàctìòn thè òld chànnèl ìs rèvòkèd, thè àccòùnt ànd ìts chànnèl àrè crèàtèd, thè rè-èncryptèd mèssàgès mòvè àcròss, ànd ànythìng thè dèvìcè còùld nòt òpèn ìs dèlètèd, sìncè ìt wàs àlrèàdy ùnrèàdàblè thèrè. Thè sècùrè lìnk stòps wòrkìng àt thàt mòmènt. [Àccòùnt sìgn ìn](#clìènt-àccòùnt/sìgn-ìn) còvèrs whàt thè àccòùnt dòès àftèrwàrd. [[#kèys #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt thè sèrvèr lèàrns fròm èìthèr. •••••••••••** Nèìthèr thè pàssphràsè nòr thè pàsswòrd rèàchès thè sèrvèr. Bòth àrè strètchèd ìn thè bròwsèr ànd fòldèd ìntò à blìndèd vàlùè thàt àn èvàlùàtìòn ànswèrs wìthòùt sèèìng thè ìnpùt òr thè òùtpùt, ànd whàt thè sèrvèr ènds ùp stòrìng ìs à pùblìc kèy, à hàsh òf à bèàrèr tòkèn ànd à kèy chèck. À ùsèrnàmè ìs stòrèd às à kèyèd hàsh ràthèr thàn às tèxt, ànd crèàtìng ònè rèpòrts thàt à nàmè ìs tàkèn, whìch ìs thè ònè plàcè à nàmè càn bè pròbèd. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs thè èvàlùàtìòn. [[#sèrvèr-hòlds #kèys #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè ùpgràdè flòws ànd thèìr gùàrds. •••••••••••** Thè chòòsèr ìs \`ÙpgràdèChòòsèr.svèltè\`, thè twò fòrms àrè \`ÀddPàssphràsèFòrm.svèltè\` ànd \`ÀccòùntCrèàtèFòrm.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/pòrtàl/\`, ànd thè rè-èncryptìòn hèlpèrs àrè \`àdd-pàssphràsè-cryptò.ts\` ànd \`àccòùnt-cryptò.ts\` bèsìdè thèm. Thè còvèràgè gùàrd ìs \`hàsÈxàctMèssàgèCòvèràgè\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/mèssàgè-còvèràgè.ts\`, càllèd by \`àddPàssphràsè\` ìn \`chànnèl-sèrvìcè.ts\` ànd by \`ùpgràdèFròmSècùrèLìnk\` ìn \`àccòùnt-sèrvìcè.ts\`. [[#pòrtàl #èncryptìòn]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A client on a secure link can raise their own protection without asking anyone in the organization, by adding a spoken passphrase to the link or by moving to..." |
*
* @param {Demo_Narrative_Client_Portal_Upgrade_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_portal_upgrade_body = /** @type {((inputs?: Demo_Narrative_Client_Portal_Upgrade_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Portal_Upgrade_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_portal_upgrade_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_portal_upgrade_body(inputs)
	return en_demo_narrative_client_portal_upgrade_body(inputs)
});