/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Privacy_Notice_BodyInputs */

const en_demo_narrative_client_privacy_notice_body = /** @type {(inputs: Demo_Narrative_Client_Privacy_Notice_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The privacy notice is a fixed page linked from the drawer on every client page. It states who collects a submission, what data is gathered, who can read it, how long it is kept, what rights the visitor holds, and what cookies the site uses. The organization's name and its own retention setting change between deployments. [[#privacy #client-data]]
**What does the notice promise about reading a submission?** The notice says that volunteers open submissions on their own devices, that the organization key gives access until someone first takes the case, and that afterward only the people working on it can read it. Before that first open, any member holding the organization key can unseal the submission, and the server restricts it to members of the destination queue. The intake form states the same claim. [How the visitor is protected](#client-intake/how-protected) covers the encryption behind that claim. [[#keys #privacy]]
**What does the notice say about retention?** Encrypted data is described as kept while the case is open plus any retention period the organization chooses. Automatic deletion is off until an administrator enables it, so closed cases are kept indefinitely by default. The notice states that default. [Data retention](#deep-dive/data-retention) covers the deletion order, and [Retention policy](#admin-org/retention) covers where the window is configured. [[#retention #server-holds]]
**What rights does the notice offer?** The notice lists the rights the organization can fulfil. The visitor is told to quote the reference code returned after submission. The organization stores a generated alias, not a searchable name, and without the code it has no way to locate the record. [Submission](#client-intake/submit) covers where the code originates. [[#client-data #metadata]]
**What does the notice say about cookies?** Only session and security cookies required for the form are set, and the notice confirms none of them track the visitor. Outside the form itself, the language picker stores a preference cookie and the color-scheme toggle persists its choice in local storage. [The intake page](#client-intake/form) covers what traces a visit leaves on the device. [[#privacy #client-data]]
**The page component and its substitutions.** The page is \`packages/client/src/routes/(client)/intake/privacy/+page.svelte\`, rendering the \`intake_privacy_*\` messages and embedding \`intake_retention_disclosure\` within the retention section. The server substitutes the organization's name into the page for each organization when it serves it, or the page reads it from the public branding response. Branding is stored as plaintext because it is not a secret. No key material is present on the page. A language switch re-renders the entire notice in the new language without reloading. [[#server-holds #privacy]]`)
};

const es_demo_narrative_client_privacy_notice_body = /** @type {(inputs: Demo_Narrative_Client_Privacy_Notice_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El aviso de privacidad es una página fija enlazada desde el panel lateral en todas las páginas del cliente. Indica quién recoge un envío, qué datos se recopilan, quién puede leerlos, cuánto tiempo se conservan, qué derechos tiene el visitante y qué cookies usa el sitio. El nombre de la organización y su propia configuración de retención cambian entre despliegues. [[#privacy #client-data]]
**¿Qué promete el aviso sobre la lectura de un envío?** El aviso dice que las personas voluntarias abren los envíos en sus propios dispositivos, que la clave de la organización da acceso hasta que alguien toma el caso por primera vez y que a partir de ese momento solo quienes lo trabajan pueden leerlo. Antes de esa primera apertura, cualquier miembro que tenga la clave de la organización puede abrir el envío, y el servidor lo restringe a los miembros de la cola de destino. El formulario de admisión enuncia la misma afirmación. [Cómo se protege al visitante](#client-intake/how-protected) trata el cifrado detrás de esa afirmación. [[#keys #privacy]]
**¿Qué dice el aviso sobre la retención?** Los datos cifrados se describen como conservados mientras el caso esté abierto más cualquier periodo de retención que la organización elija. La eliminación automática está desactivada hasta que la persona administradora la active, así que por defecto los casos cerrados se conservan indefinidamente. El aviso indica ese valor predeterminado. [Retención de datos](#deep-dive/data-retention) trata el orden de eliminación, y [Política de retención](#admin-org/retention) trata dónde se configura la ventana. [[#retention #server-holds]]
**¿Qué derechos ofrece el aviso?** El aviso enumera los derechos que la organización puede cumplir. Se indica al visitante que cite el código de referencia devuelto tras el envío. La organización almacena un alias generado, no un nombre buscable, y sin el código no tiene forma de localizar el registro. [Envío](#client-intake/submit) trata de dónde proviene el código. [[#client-data #metadata]]
**¿Qué dice el aviso sobre las cookies?** Solo se establecen cookies de sesión y seguridad necesarias para el formulario, y el aviso confirma que ninguna rastrea al visitante. Fuera del formulario, el selector de idioma almacena una cookie de preferencia y el conmutador de esquema de color guarda su elección en el almacenamiento local. [La página de admisión](#client-intake/form) trata los rastros que deja una visita en el dispositivo. [[#privacy #client-data]]
**El componente de página y sus sustituciones.** La página es \`packages/client/src/routes/(client)/intake/privacy/+page.svelte\`, que muestra los mensajes \`intake_privacy_*\` e inserta \`intake_retention_disclosure\` dentro de la sección de retención. El servidor sustituye el nombre de la organización en la página para cada organización cuando la sirve, o la página lo lee de la respuesta de identidad pública. La identidad visual se almacena como texto plano porque no es secreta. No hay material de claves en la página. Un cambio de idioma vuelve a representar el aviso completo en el nuevo idioma sin recargar. [[#server-holds #privacy]]`)
};

const en_xa2_demo_narrative_client_privacy_notice_body = /** @type {(inputs: Demo_Narrative_Client_Privacy_Notice_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè prìvàcy nòtìcè ìs à fìxèd pàgè lìnkèd fròm thè dràwèr òn èvèry clìènt pàgè. Ìt stàtès whò còllècts à sùbmìssìòn, whàt dàtà ìs gàthèrèd, whò càn rèàd ìt, hòw lòng ìt ìs kèpt, whàt rìghts thè vìsìtòr hòlds, ànd whàt còòkìès thè sìtè ùsès. Thè òrgànìzàtìòn's nàmè ànd ìts òwn rètèntìòn sèttìng chàngè bètwèèn dèplòymènts. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè nòtìcè pròmìsè àbòùt rèàdìng à sùbmìssìòn? •••••••••••••••••** Thè nòtìcè sàys thàt vòlùntèèrs òpèn sùbmìssìòns òn thèìr òwn dèvìcès, thàt thè òrgànìzàtìòn kèy gìvès àccèss ùntìl sòmèònè fìrst tàkès thè càsè, ànd thàt àftèrwàrd ònly thè pèòplè wòrkìng òn ìt càn rèàd ìt. Bèfòrè thàt fìrst òpèn, àny mèmbèr hòldìng thè òrgànìzàtìòn kèy càn ùnsèàl thè sùbmìssìòn, ànd thè sèrvèr rèstrìcts ìt tò mèmbèrs òf thè dèstìnàtìòn qùèùè. Thè ìntàkè fòrm stàtès thè sàmè clàìm. [Hòw thè vìsìtòr ìs pròtèctèd](#clìènt-ìntàkè/hòw-pròtèctèd) còvèrs thè èncryptìòn bèhìnd thàt clàìm. [[#kèys #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè nòtìcè sày àbòùt rètèntìòn? •••••••••••••** Èncryptèd dàtà ìs dèscrìbèd às kèpt whìlè thè càsè ìs òpèn plùs àny rètèntìòn pèrìòd thè òrgànìzàtìòn chòòsès. Àùtòmàtìc dèlètìòn ìs òff ùntìl àn àdmìnìstràtòr ènàblès ìt, sò clòsèd càsès àrè kèpt ìndèfìnìtèly by dèfàùlt. Thè nòtìcè stàtès thàt dèfàùlt. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thè dèlètìòn òrdèr, ànd [Rètèntìòn pòlìcy](#àdmìn-òrg/rètèntìòn) còvèrs whèrè thè wìndòw ìs cònfìgùrèd. [[#rètèntìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt rìghts dòès thè nòtìcè òffèr? •••••••••••** Thè nòtìcè lìsts thè rìghts thè òrgànìzàtìòn càn fùlfìl. Thè vìsìtòr ìs tòld tò qùòtè thè rèfèrèncè còdè rètùrnèd àftèr sùbmìssìòn. Thè òrgànìzàtìòn stòrès à gènèràtèd àlìàs, nòt à sèàrchàblè nàmè, ànd wìthòùt thè còdè ìt hàs nò wày tò lòcàtè thè rècòrd. [Sùbmìssìòn](#clìènt-ìntàkè/sùbmìt) còvèrs whèrè thè còdè òrìgìnàtès. [[#clìènt-dàtà #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè nòtìcè sày àbòùt còòkìès? ••••••••••••** Ònly sèssìòn ànd sècùrìty còòkìès rèqùìrèd fòr thè fòrm àrè sèt, ànd thè nòtìcè cònfìrms nònè òf thèm tràck thè vìsìtòr. Òùtsìdè thè fòrm ìtsèlf, thè làngùàgè pìckèr stòrès à prèfèrèncè còòkìè ànd thè còlòr-schèmè tògglè pèrsìsts ìts chòìcè ìn lòcàl stòràgè. [Thè ìntàkè pàgè](#clìènt-ìntàkè/fòrm) còvèrs whàt tràcès à vìsìt lèàvès òn thè dèvìcè. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pàgè còmpònènt ànd ìts sùbstìtùtìòns. •••••••••••••** Thè pàgè ìs \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/prìvàcy/+pàgè.svèltè\`, rèndèrìng thè \`ìntàkè_prìvàcy_*\` mèssàgès ànd èmbèddìng \`ìntàkè_rètèntìòn_dìsclòsùrè\` wìthìn thè rètèntìòn sèctìòn. Thè sèrvèr sùbstìtùtès thè òrgànìzàtìòn's nàmè ìntò thè pàgè fòr èàch òrgànìzàtìòn whèn ìt sèrvès ìt, òr thè pàgè rèàds ìt fròm thè pùblìc bràndìng rèspònsè. Bràndìng ìs stòrèd às plàìntèxt bècàùsè ìt ìs nòt à sècrèt. Nò kèy màtèrìàl ìs prèsènt òn thè pàgè. À làngùàgè swìtch rè-rèndèrs thè èntìrè nòtìcè ìn thè nèw làngùàgè wìthòùt rèlòàdìng. [[#sèrvèr-hòlds #prìvàcy]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The privacy notice is a fixed page linked from the drawer on every client page. It states who collects a submission, what data is gathered, who can read it, ..." |
*
* @param {Demo_Narrative_Client_Privacy_Notice_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_privacy_notice_body = /** @type {((inputs?: Demo_Narrative_Client_Privacy_Notice_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Privacy_Notice_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_privacy_notice_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_privacy_notice_body(inputs)
	return en_demo_narrative_client_privacy_notice_body(inputs)
});