/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Response_Export_BodyInputs */

const en_demo_narrative_admin_response_export_body = /** @type {(inputs: Demo_Narrative_Admin_Response_Export_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The browser assembles the CSV from responses it has already decrypted. The server sends nothing new for the export, and no plaintext leaves the device until the user saves the file. The export button is disabled while any row is still decrypting. [[#encryption #client-data]]
**What goes into the file?** The first column is the submission timestamp, followed by one column per field in the submission's own label snapshot, in the form's field order. Rows the user could not decrypt are excluded, not exported blank. A confirmation dialog reports how many responses will be exported and how many will be skipped. Only pages already loaded in the viewer are in scope. Responses from unloaded pages do not appear in the file and are not reflected in the skip count. [Response cards](#admin-responses/responses) covers how pages load. [[#failure-states]]
**Answers to removed or relabeled fields.** The viewer and the export both read labels from the snapshot stored with each submission, not from the form's current definition. A relabeled field keeps its original wording and a removed field keeps its original label. The export covers every submitted answer. [Field list](#admin-forms/builder) covers what changing a field does. [[#client-data]]
**The file is plaintext.** The confirmation dialog states that the file contains unencrypted client data before the download starts. The encryption that protects answers inside CARE-Y covers the path up to this point, not the file afterwards. Where the file goes after download is a decision made outside the system. Cells that would otherwise trigger formula interpretation in a spreadsheet are prefixed so they are treated as text. [The trust boundary](#deep-dive/the-trust-boundary) covers where encryption applies and where it stops. [[#privacy #encryption]]
**The assembler and the audit record.** \`assembleIntakeCsv\` in \`packages/client/src/lib/export/intake-csv.ts\` handles quoting and formula prefixing, following RFC 4180 and the OWASP CSV injection guidance cited in the module. \`logExport\` in \`packages/server/src/routes/intake-forms.ts\` records the form ID and both counts before the file is offered. The server refuses the export when the audit write fails, so every plaintext download has an audit trace. [Audit log](#admin-logs/audit) covers the log itself. [[#metadata]]`)
};

const es_demo_narrative_admin_response_export_body = /** @type {(inputs: Demo_Narrative_Admin_Response_Export_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El navegador arma el CSV a partir de las respuestas que ya descifró. El servidor no envía nada nuevo para la exportación, y ningún texto en claro sale del dispositivo hasta que la persona usuaria guarda el archivo. El botón de exportación se deshabilita mientras alguna fila sigue descifrándose. [[#encryption #client-data]]
**¿Qué entra en el archivo?** La primera columna es la marca de tiempo del envío, seguida de una columna por cada campo en la instantánea de etiquetas del propio envío, en el orden del formulario. Las filas que la persona usuaria no pudo descifrar se excluyen en lugar de exportarse en blanco. Un diálogo de confirmación informa cuántas respuestas se exportarán y cuántas se omitirán. Solo entran las páginas ya cargadas en el visor. Las respuestas de páginas no cargadas no aparecen en el archivo ni se reflejan en el recuento de omitidas. [Tarjetas de respuesta](#admin-responses/responses) trata cómo se cargan las páginas. [[#failure-states]]
**Respuestas a campos eliminados o renombrados.** El visor y la exportación leen las etiquetas de la instantánea almacenada con cada envío, no de la definición actual del formulario. Un campo renombrado conserva su redacción original y un campo eliminado conserva su etiqueta original. La exportación incluye cada respuesta enviada. [Lista de campos](#admin-forms/builder) trata qué ocurre al modificar un campo. [[#client-data]]
**El archivo es texto plano.** El diálogo de confirmación indica que el archivo contiene datos de clientes sin cifrar antes de que comience la descarga. El cifrado que protege las respuestas dentro de CARE-Y cubre el camino hasta este punto, no el archivo posterior. Adónde va el archivo tras la descarga es una decisión que se toma fuera del sistema. Las celdas que de otro modo activarían la interpretación de fórmulas en una hoja de cálculo llevan un prefijo para que se traten como texto. [La frontera de confianza](#deep-dive/the-trust-boundary) trata dónde se aplica el cifrado y dónde termina. [[#privacy #encryption]]
**El ensamblador y el registro de auditoría.** \`assembleIntakeCsv\`, en \`packages/client/src/lib/export/intake-csv.ts\`, se encarga del entrecomillado y del prefijo de fórmulas, siguiendo la RFC 4180 y la guía de OWASP sobre inyección CSV citada en el módulo. \`logExport\`, en \`packages/server/src/routes/intake-forms.ts\`, registra el ID del formulario y ambos recuentos antes de ofrecer el archivo. El servidor rechaza la exportación cuando la escritura de auditoría falla, de modo que cada descarga en texto plano tiene traza de auditoría. [Registro de auditoría](#admin-logs/audit) trata el registro en sí. [[#metadata]]`)
};

const en_xa2_demo_narrative_admin_response_export_body = /** @type {(inputs: Demo_Narrative_Admin_Response_Export_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè bròwsèr àssèmblès thè CSV fròm rèspònsès ìt hàs àlrèàdy dècryptèd. Thè sèrvèr sènds nòthìng nèw fòr thè èxpòrt, ànd nò plàìntèxt lèàvès thè dèvìcè ùntìl thè ùsèr sàvès thè fìlè. Thè èxpòrt bùttòn ìs dìsàblèd whìlè àny ròw ìs stìll dècryptìng. [[#èncryptìòn #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt gòès ìntò thè fìlè? ••••••••** Thè fìrst còlùmn ìs thè sùbmìssìòn tìmèstàmp, fòllòwèd by ònè còlùmn pèr fìèld ìn thè sùbmìssìòn's òwn làbèl snàpshòt, ìn thè fòrm's fìèld òrdèr. Ròws thè ùsèr còùld nòt dècrypt àrè èxclùdèd, nòt èxpòrtèd blànk. À cònfìrmàtìòn dìàlòg rèpòrts hòw màny rèspònsès wìll bè èxpòrtèd ànd hòw màny wìll bè skìppèd. Ònly pàgès àlrèàdy lòàdèd ìn thè vìèwèr àrè ìn scòpè. Rèspònsès fròm ùnlòàdèd pàgès dò nòt àppèàr ìn thè fìlè ànd àrè nòt rèflèctèd ìn thè skìp còùnt. [Rèspònsè càrds](#àdmìn-rèspònsès/rèspònsès) còvèrs hòw pàgès lòàd. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ànswèrs tò rèmòvèd òr rèlàbèlèd fìèlds. ••••••••••••** Thè vìèwèr ànd thè èxpòrt bòth rèàd làbèls fròm thè snàpshòt stòrèd wìth èàch sùbmìssìòn, nòt fròm thè fòrm's cùrrènt dèfìnìtìòn. À rèlàbèlèd fìèld kèèps ìts òrìgìnàl wòrdìng ànd à rèmòvèd fìèld kèèps ìts òrìgìnàl làbèl. Thè èxpòrt còvèrs èvèry sùbmìttèd ànswèr. [Fìèld lìst](#àdmìn-fòrms/bùìldèr) còvèrs whàt chàngìng à fìèld dòès. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fìlè ìs plàìntèxt. •••••••** Thè cònfìrmàtìòn dìàlòg stàtès thàt thè fìlè còntàìns ùnèncryptèd clìènt dàtà bèfòrè thè dòwnlòàd stàrts. Thè èncryptìòn thàt pròtècts ànswèrs ìnsìdè CÀRÈ-Y còvèrs thè pàth ùp tò thìs pòìnt, nòt thè fìlè àftèrwàrds. Whèrè thè fìlè gòès àftèr dòwnlòàd ìs à dècìsìòn màdè òùtsìdè thè systèm. Cèlls thàt wòùld òthèrwìsè trìggèr fòrmùlà ìntèrprètàtìòn ìn à sprèàdshèèt àrè prèfìxèd sò thèy àrè trèàtèd às tèxt. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whèrè èncryptìòn àpplìès ànd whèrè ìt stòps. [[#prìvàcy #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè àssèmblèr ànd thè àùdìt rècòrd. •••••••••••** \`àssèmblèÌntàkèCsv\` ìn \`pàckàgès/clìènt/src/lìb/èxpòrt/ìntàkè-csv.ts\` hàndlès qùòtìng ànd fòrmùlà prèfìxìng, fòllòwìng RFC 4180 ànd thè ÒWÀSP CSV ìnjèctìòn gùìdàncè cìtèd ìn thè mòdùlè. \`lògÈxpòrt\` ìn \`pàckàgès/sèrvèr/src/ròùtès/ìntàkè-fòrms.ts\` rècòrds thè fòrm ÌD ànd bòth còùnts bèfòrè thè fìlè ìs òffèrèd. Thè sèrvèr rèfùsès thè èxpòrt whèn thè àùdìt wrìtè fàìls, sò èvèry plàìntèxt dòwnlòàd hàs àn àùdìt tràcè. [Àùdìt lòg](#àdmìn-lògs/àùdìt) còvèrs thè lòg ìtsèlf. [[#mètàdàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The browser assembles the CSV from responses it has already decrypted. The server sends nothing new for the export, and no plaintext leaves the device until ..." |
*
* @param {Demo_Narrative_Admin_Response_Export_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_response_export_body = /** @type {((inputs?: Demo_Narrative_Admin_Response_Export_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Response_Export_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_response_export_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_response_export_body(inputs)
	return en_demo_narrative_admin_response_export_body(inputs)
});