/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_General_BodyInputs */

const en_demo_narrative_admin_general_body = /** @type {(inputs: Demo_Narrative_Admin_General_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`General information holds the organization's name, its country code, its default language and the address the client-facing quick exit navigates to, and all are stored without encryption. [[#server-holds]]
**What does each field control?** The name is visible before anyone signs in, which is why it stays in the clear. The country code fills in the international prefix when a phone number is entered without one during sign-in code enrollment. The default language sets the language the server uses when it composes text on its own, such as the footer on a reply-by-email message and the notice a client receives through the portal. The exit address is the destination a client-facing page navigates to when the quick exit fires. [Quick exit](#client-portal/quick-exit) covers what leaving does to the session. [[#portal #telephony]]
**Why is the exit address validated twice?** A stored address must be an absolute https URL with a real hostname. A looser check would allow schemes that execute script rather than load a page, and the exit URL is the navigation a person triggers when leaving fast. The same validation runs again at read time, so a value saved before the rule existed or written through a path that bypassed it resolves to the built-in default instead of being served as stored. [[#failure-states #portal]]
**What does a database dump reveal?** A dump shows the organization's name, its country code, its default language and its exit address. The name already appears on unauthenticated pages, so the country, the language and the exit address are what the dump adds. [The trust boundary](#deep-dive/the-trust-boundary) covers what else the server holds in the clear. [[#server-holds #metadata]]
**Who can edit general information?** Editing requires the Manage org identity permission, which belongs to the Admin role by default. An organization can move it to another role. [The permission system](#deep-dive/the-permission-system) covers how grants move between roles. [[#permissions]]
**The name column and branding.** The organization name on this page and the display name under branding are the same column, \`org_config.name\`. A change here is the change branding shows. [Branding](#admin-org/branding) covers the rest of that row. [[#server-holds]]
**The config service and exit URL validation.** \`getOrgGeneral\` and \`updateOrgGeneral\` in \`packages/server/src/org/org-config-service.ts\` read and write the four columns behind permission-gated procedures in \`packages/server/src/routes/org.ts\`. The exit URL rule is \`safeExitUrlSchema\` in \`packages/shared/src/schemas/org.ts\`, and the read-back check is \`readSafeExitUrl\` in \`packages/server/src/branding/branding-service.ts\`. [[#server-holds]]`)
};

const es_demo_narrative_admin_general_body = /** @type {(inputs: Demo_Narrative_Admin_General_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La información general guarda el nombre de la organización, su código de país, su idioma predeterminado y la dirección a la que navega la salida rápida en las páginas para clientes, y se almacenan sin cifrar. [[#server-holds]]
**¿Qué controla cada campo?** El nombre es visible antes de que nadie inicie sesión, y por eso se guarda en claro. El código de país rellena el prefijo internacional cuando se introduce un número de teléfono sin él durante la inscripción de códigos de acceso. El idioma predeterminado fija el idioma que usa el servidor cuando redacta texto por su cuenta, como el pie de un mensaje de respuesta por correo y el aviso que recibe un cliente a través del portal. La dirección de salida es el destino al que navega una página para clientes cuando se activa la salida rápida. [Salida rápida](#client-portal/quick-exit) trata lo que la salida le hace a la sesión. [[#portal #telephony]]
**¿Por qué se valida dos veces la dirección de salida?** Una dirección almacenada tiene que ser una URL https absoluta con un nombre de host real. Una comprobación menos estricta permitiría esquemas que ejecutan código en lugar de cargar una página, y la URL de salida es la navegación que activa una persona cuando necesita salir deprisa. La misma validación se repite en el momento de la lectura, de modo que un valor guardado antes de que existiera la regla, o escrito por una vía que la omitió, se resuelve al destino integrado en lugar de servirse tal como está almacenado. [[#failure-states #portal]]
**¿Qué revela un volcado de la base de datos?** Un volcado muestra el nombre de la organización, su código de país, su idioma predeterminado y su dirección de salida. El nombre ya es visible en páginas no autenticadas, de modo que el país, el idioma y la dirección de salida son lo que el volcado añade. [La frontera de confianza](#deep-dive/the-trust-boundary) trata lo demás que el servidor guarda en claro. [[#server-holds #metadata]]
**¿Quién puede editar la información general?** Editar requiere el permiso Gestionar identidad de la organización, que pertenece al rol Admin de forma predeterminada. Una organización puede trasladarlo a otro rol. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se trasladan las concesiones entre roles. [[#permissions]]
**La columna de nombre y la marca.** El nombre de la organización en esta página y el nombre visible en la marca son la misma columna, \`org_config.name\`. Un cambio aquí es el cambio que muestra la marca. [Marca](#admin-org/branding) trata el resto de esa fila. [[#server-holds]]
**El servicio de configuración y la validación de la URL de salida.** \`getOrgGeneral\` y \`updateOrgGeneral\`, en \`packages/server/src/org/org-config-service.ts\`, leen y escriben las cuatro columnas detrás de procedimientos protegidos por permiso en \`packages/server/src/routes/org.ts\`. La regla de la URL de salida es \`safeExitUrlSchema\`, en \`packages/shared/src/schemas/org.ts\`, y la comprobación de lectura es \`readSafeExitUrl\`, en \`packages/server/src/branding/branding-service.ts\`. [[#server-holds]]`)
};

const en_xa2_demo_narrative_admin_general_body = /** @type {(inputs: Demo_Narrative_Admin_General_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Gènèràl ìnfòrmàtìòn hòlds thè òrgànìzàtìòn's nàmè, ìts còùntry còdè, ìts dèfàùlt làngùàgè ànd thè àddrèss thè clìènt-fàcìng qùìck èxìt nàvìgàtès tò, ànd àll àrè stòrèd wìthòùt èncryptìòn. [[#sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès èàch fìèld còntròl? •••••••••** Thè nàmè ìs vìsìblè bèfòrè ànyònè sìgns ìn, whìch ìs why ìt stàys ìn thè clèàr. Thè còùntry còdè fìlls ìn thè ìntèrnàtìònàl prèfìx whèn à phònè nùmbèr ìs èntèrèd wìthòùt ònè dùrìng sìgn-ìn còdè ènròllmènt. Thè dèfàùlt làngùàgè sèts thè làngùàgè thè sèrvèr ùsès whèn ìt còmpòsès tèxt òn ìts òwn, sùch às thè fòòtèr òn à rèply-by-èmàìl mèssàgè ànd thè nòtìcè à clìènt rècèìvès thròùgh thè pòrtàl. Thè èxìt àddrèss ìs thè dèstìnàtìòn à clìènt-fàcìng pàgè nàvìgàtès tò whèn thè qùìck èxìt fìrès. [Qùìck èxìt](#clìènt-pòrtàl/qùìck-èxìt) còvèrs whàt lèàvìng dòès tò thè sèssìòn. [[#pòrtàl #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why ìs thè èxìt àddrèss vàlìdàtèd twìcè? ••••••••••••** À stòrèd àddrèss mùst bè àn àbsòlùtè https ÙRL wìth à rèàl hòstnàmè. À lòòsèr chèck wòùld àllòw schèmès thàt èxècùtè scrìpt ràthèr thàn lòàd à pàgè, ànd thè èxìt ÙRL ìs thè nàvìgàtìòn à pèrsòn trìggèrs whèn lèàvìng fàst. Thè sàmè vàlìdàtìòn rùns àgàìn àt rèàd tìmè, sò à vàlùè sàvèd bèfòrè thè rùlè èxìstèd òr wrìttèn thròùgh à pàth thàt bypàssèd ìt rèsòlvès tò thè bùìlt-ìn dèfàùlt ìnstèàd òf bèìng sèrvèd às stòrèd. [[#fàìlùrè-stàtès #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à dàtàbàsè dùmp rèvèàl? ••••••••••** À dùmp shòws thè òrgànìzàtìòn's nàmè, ìts còùntry còdè, ìts dèfàùlt làngùàgè ànd ìts èxìt àddrèss. Thè nàmè àlrèàdy àppèàrs òn ùnàùthèntìcàtèd pàgès, sò thè còùntry, thè làngùàgè ànd thè èxìt àddrèss àrè whàt thè dùmp àdds. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whàt èlsè thè sèrvèr hòlds ìn thè clèàr. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn èdìt gènèràl ìnfòrmàtìòn? ••••••••••** Èdìtìng rèqùìrès thè Mànàgè òrg ìdèntìty pèrmìssìòn, whìch bèlòngs tò thè Àdmìn ròlè by dèfàùlt. Àn òrgànìzàtìòn càn mòvè ìt tò ànòthèr ròlè. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw grànts mòvè bètwèèn ròlès. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè nàmè còlùmn ànd bràndìng. •••••••••** Thè òrgànìzàtìòn nàmè òn thìs pàgè ànd thè dìsplày nàmè ùndèr bràndìng àrè thè sàmè còlùmn, \`òrg_cònfìg.nàmè\`. À chàngè hèrè ìs thè chàngè bràndìng shòws. [Bràndìng](#àdmìn-òrg/bràndìng) còvèrs thè rèst òf thàt ròw. [[#sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè cònfìg sèrvìcè ànd èxìt ÙRL vàlìdàtìòn. •••••••••••••** \`gètÒrgGènèràl\` ànd \`ùpdàtèÒrgGènèràl\` ìn \`pàckàgès/sèrvèr/src/òrg/òrg-cònfìg-sèrvìcè.ts\` rèàd ànd wrìtè thè fòùr còlùmns bèhìnd pèrmìssìòn-gàtèd pròcèdùrès ìn \`pàckàgès/sèrvèr/src/ròùtès/òrg.ts\`. Thè èxìt ÙRL rùlè ìs \`sàfèÈxìtÙrlSchèmà\` ìn \`pàckàgès/shàrèd/src/schèmàs/òrg.ts\`, ànd thè rèàd-bàck chèck ìs \`rèàdSàfèÈxìtÙrl\` ìn \`pàckàgès/sèrvèr/src/bràndìng/bràndìng-sèrvìcè.ts\`. [[#sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "General information holds the organization's name, its country code, its default language and the address the client-facing quick exit navigates to, and all ..." |
*
* @param {Demo_Narrative_Admin_General_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_general_body = /** @type {((inputs?: Demo_Narrative_Admin_General_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_General_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_general_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_general_body(inputs)
	return en_demo_narrative_admin_general_body(inputs)
});