/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs */

const en_demo_narrative_deepdive_how_encryption_works_body = /** @type {(inputs: Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A client's messages and the notes written about them are encrypted in the user's browser before they leave the device, and the server holds only the result. The server has no key that opens it, which is a different and stronger statement than a promise not to look. [[#encryption #client-data]]
Three separate keys carry three separate kinds of data, and a fourth kind is published on purpose. [[#encryption #keys #server-holds]]
- The case record, its messages, its notes and the client's contact details are readable only by the users authorized on that case. [[#encryption #client-data]]
- Shared organization material such as library articles, queue names, note types and settings is readable by any signed-in user in the organization. [[#encryption #keys]]
- Operational configuration such as telephony credentials and mail server settings is readable by the server itself, because the server is what places a call at three in the morning with nobody watching. [[#encryption #server-holds]]
- The intake page logo and colors are public so a client recognizes the organization they are contacting. [[#encryption #privacy]]
An attacker who seizes the server and takes the whole database gets ciphertext for all three encrypted classes, plus the telephony credentials from the operational tier, which grant phone system access and nothing about any client. Opening the case tier requires a user's password run through the key derivation protocol, and opening the organization tier requires the same password first. [How keys are derived](#deep-dive/how-keys-are-derived) explains why a password guess is expensive and why a single seized machine is not enough. [[#encryption #server-holds]]
Without breaking anything, an attacker does get the shape of the work. Case rows carry a plaintext status, priority, queue reference, creation timestamp and assignment. So a database dump shows that cases exist, how many, when each arrived, which queue took it, how urgent someone judged it, and that a particular account was assigned to it. It does not show the client, the phone number, the summary or a single message. The design does not hide overall activity levels or when they occur. [The trust boundary](#deep-dive/the-trust-boundary) lists this exposure field by field. [[#metadata #trust-boundary #server-holds]]
Encryption also stops at the edges of the device. A user whose laptop is compromised, or whose browser runs a malicious extension, is showing decrypted case content to whatever is watching, and no server-side property can prevent that. A message that arrived as an ordinary text message was readable by the carrier and the telephony provider before CARE-Y ever encrypted it, which is why the case thread marks where a message came from. [[#failure-states #telephony]]
**Per-case keys and wrapping.** Each case gets its own 32-byte symmetric key, and case content is sealed with XChaCha20-Poly1305 using additional authenticated data built from the case id and the storage slot, which is the title, the description, a follow-up id or a blob row id. A ciphertext moved to a different slot or a different case fails authentication rather than decrypting into the wrong place. The case key itself is never stored in the clear. For each authorized user it is wrapped to that user's ristretto255 public key using ECIES, so the server can wrap a key for a user it cannot impersonate and cannot unwrap. On open, the browser worker computes the shared secret from the user's private scalar and the stored ephemeral point, unwraps the case key, and decrypts, with no server round trip in the decryption path. [[#encryption #keys]]
**The organization tier and the public tier.** Shared material uses one organization keypair. The private half is wrapped per user under a key derived from that user's master key, so every signed-in user can open library articles and queue names while the server, holding only the public half, can seal new values without reading any. User display names and login identifiers are stored as sealed boxes under the same organization public key, which is why an administrator's browser can list users by name and the server cannot. Intake branding is the exception, because its key derives from the organization public key by hash and is therefore readable by anyone, which is the intent for a page a client must recognize before trusting it. [[#encryption #keys #privacy]]
**What the password does not unlock.** Revoking a user deletes their per-case wrapped keys, so the user's derived private key has nothing left to unwrap even if they still know their password. Changing a password changes the derived private key, which is why a password change re-wraps every case key the user can reach, an operation proportional to the number of cases they have access to. [[#keys #failure-states]]
**Contributor boundaries.** The primitives live in \`packages/crypto/src\`, split by job. [[#encryption #client-data]]
- \`content.ts\` does slot-bound content encryption. [[#encryption]]
- \`ecies.ts\` and \`keywrap.ts\` do key wrapping. [[#encryption #keys]]
- \`derive.ts\` and \`hkdf.ts\` do derivation. [[#keys]]
- \`mem.ts\` zeroes buffers. [[#encryption]]
Column shape is the design decision that outlives the code. The \`tickets\` table holds \`encrypted_title\` and \`encrypted_description\` as bytea beside plaintext \`status\`, \`priority\`, \`queue_id\`, \`assigned_to\` and \`created_at\`, and \`ticket_key_wraps\` holds one row per user per case with the ephemeral point, nonce and wrapped key. Adding a field to a case means choosing between the encrypted payload and the plaintext metadata, and a field chosen as plaintext stays visible in every future database dump. [[#encryption #client-data #server-holds]]`)
};

const es_demo_narrative_deepdive_how_encryption_works_body = /** @type {(inputs: Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los mensajes de un cliente y las notas escritas sobre él se cifran en el navegador de la persona usuaria antes de salir del dispositivo, y el servidor conserva solo el resultado. El servidor no tiene ninguna clave que lo abra, que es una afirmación distinta y más fuerte que la promesa de no mirar. [[#encryption #client-data]]
Tres claves separadas llevan tres tipos separados de datos, y un cuarto tipo se publica a propósito. [[#encryption #keys #server-holds]]
- El expediente del caso, sus mensajes, sus notas y los datos de contacto del cliente solo son legibles por las personas usuarias autorizadas en ese caso. [[#encryption #client-data]]
- El material compartido de la organización, como artículos de la biblioteca, nombres de cola, tipos de nota y ajustes, es legible por cualquier persona usuaria de la organización con la sesión iniciada. [[#encryption #keys]]
- La configuración operativa, como las credenciales de telefonía y los ajustes del servidor de correo, es legible por el servidor mismo, porque el servidor es lo que realiza una llamada a las tres de la mañana sin nadie mirando. [[#encryption #server-holds]]
- El logotipo y los colores de la página de ingreso son públicos para que un cliente reconozca a la organización con la que está contactando. [[#encryption #privacy]]
Un atacante que incauta el servidor y se lleva toda la base de datos obtiene texto cifrado de las tres clases cifradas, más las credenciales de telefonía del nivel operativo, que dan acceso al sistema telefónico y nada sobre ningún cliente. Abrir el nivel del caso requiere la contraseña de una persona usuaria pasada por el protocolo de derivación de claves, y abrir el nivel de la organización requiere antes esa misma contraseña. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) explica por qué adivinar una contraseña es costoso y por qué una sola máquina incautada no basta. [[#encryption #server-holds]]
Sin romper nada, un atacante sí obtiene la forma del trabajo. Las filas de caso llevan en texto plano el estado, la prioridad, la referencia de cola, la marca de tiempo de creación y la asignación. Así que un volcado de la base de datos muestra que existen casos, cuántos, cuándo llegó cada uno, qué cola lo tomó, con cuánta urgencia lo juzgó alguien y que una cuenta concreta quedó asignada a él. No muestra el cliente, el número de teléfono, el resumen ni un solo mensaje. El diseño no oculta los niveles generales de actividad ni cuándo ocurren. [La frontera de confianza](#deep-dive/the-trust-boundary) enumera esta exposición campo por campo. [[#metadata #trust-boundary #server-holds]]
El cifrado también se detiene en los bordes del dispositivo. Una persona usuaria cuyo portátil está comprometido, o cuyo navegador ejecuta una extensión maliciosa, está mostrando contenido descifrado del caso a lo que sea que esté observando, y ninguna propiedad del lado del servidor puede impedirlo. Un mensaje que llegó como mensaje de texto ordinario era legible por la compañía telefónica y por el proveedor de telefonía antes de que CARE-Y lo cifrara, y por eso el hilo del caso marca de dónde vino cada mensaje. [[#failure-states #telephony]]
**Claves por caso y envoltura.** Cada caso recibe su propia clave simétrica de 32 bytes, y el contenido del caso se sella con XChaCha20-Poly1305 usando datos autenticados adicionales construidos a partir del identificador del caso y de la ranura de almacenamiento, que es el título, la descripción, un identificador de seguimiento o el identificador de una fila de blob. Un texto cifrado movido a otra ranura o a otro caso falla la autenticación en lugar de descifrarse en el lugar equivocado. La clave del caso nunca se almacena en claro. Para cada persona usuaria autorizada se envuelve con su clave pública ristretto255 mediante ECIES, de modo que el servidor puede envolver una clave para una persona usuaria a la que no puede suplantar y cuya envoltura no puede abrir. Al abrir, el worker del navegador calcula el secreto compartido a partir del escalar privado de la persona usuaria y del punto efímero almacenado, desenvuelve la clave del caso y descifra, sin ninguna ida y vuelta al servidor en la ruta de descifrado. [[#encryption #keys]]
**El nivel de la organización y el nivel público.** El material compartido usa un único par de claves de la organización. La mitad privada se envuelve por persona usuaria bajo una clave derivada de su clave maestra, de modo que toda persona usuaria con la sesión iniciada puede abrir los artículos de la biblioteca y los nombres de cola mientras el servidor, que solo tiene la mitad pública, puede sellar valores nuevos sin leer ninguno. Los nombres visibles y los identificadores de inicio de sesión de las personas usuarias se almacenan como cajas selladas bajo esa misma clave pública de la organización, y por eso el navegador de una persona administradora puede listar a las personas usuarias por nombre y el servidor no. La identidad visual de ingreso es la excepción, porque su clave se deriva por hash de la clave pública de la organización y por tanto es legible por cualquiera, que es la intención para una página que un cliente debe reconocer antes de confiar en ella. [[#encryption #keys #privacy]]
**Qué no desbloquea la contraseña.** Revocar a una persona usuaria elimina sus claves envueltas por caso, así que su clave privada derivada no tiene nada que desenvolver aunque siga conociendo su contraseña. Cambiar una contraseña cambia la clave privada derivada, y por eso un cambio de contraseña vuelve a envolver cada clave de caso a la que la persona usuaria llega, una operación proporcional al número de casos a los que tiene acceso. [[#keys #failure-states]]
**Fronteras para quien contribuye.** Las primitivas viven en \`packages/crypto/src\`, divididas por tarea. [[#encryption #client-data]]
- \`content.ts\` hace el cifrado de contenido ligado a la ranura. [[#encryption]]
- \`ecies.ts\` y \`keywrap.ts\` hacen la envoltura de claves. [[#encryption #keys]]
- \`derive.ts\` y \`hkdf.ts\` hacen la derivación. [[#keys]]
- \`mem.ts\` pone los búferes a cero. [[#encryption]]
La forma de las columnas es la decisión de diseño que sobrevive al código. La tabla \`tickets\` guarda \`encrypted_title\` y \`encrypted_description\` como bytea junto a \`status\`, \`priority\`, \`queue_id\`, \`assigned_to\` y \`created_at\` en texto plano, y \`ticket_key_wraps\` guarda una fila por persona usuaria y por caso con el punto efímero, el nonce y la clave envuelta. Añadir un campo a un caso significa elegir entre la carga cifrada y los metadatos en texto plano, y un campo elegido como texto plano sigue visible en todos los volcados futuros de la base de datos. [[#encryption #client-data #server-holds]]`)
};

/**
* | output |
* | --- |
* | "A client's messages and the notes written about them are encrypted in the user's browser before they leave the device, and the server holds only the result. ..." |
*
* @param {Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs} inputs
* @param {{ locale?: "en" | "es" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_how_encryption_works_body = /** @type {((inputs?: Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs, options?: { locale?: "en" | "es" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs, { locale?: "en" | "es" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_how_encryption_works_body(inputs)
	return en_demo_narrative_deepdive_how_encryption_works_body(inputs)
});