/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_List_Search_BodyInputs */

const en_demo_narrative_topic_list_search_body = /** @type {(inputs: Demo_Narrative_Topic_List_Search_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A search control in the ticket list header opens a search bar below the filters. The search bar matches a term against the decrypted fields of each loaded ticket and steps through the matches one at a time. The term is never sent to the server. [[#client-data #privacy #search]]
**What does the search match?** A term is matched against the title, the description, the client alias, the queue name, and the assignee name of each loaded row. Matching ignores accents and letter case. One inserted character, one substituted character, one transposed pair, or one deleted character per term is tolerated. Results are ordered by match quality, best first. A row whose title has not finished decrypting is left out until it has. The queue name and assignee name are decrypted once per queue and once per account, not once per ticket. [[#encryption #client-data]]
**Narrowed list and match stepping.** The list shows only the matches, best first, in place of whatever sort was active, once the term reaches two characters. A term under two characters does not reduce the list. Matching runs over the tickets the active filters have already selected and skips any ticket the filters exclude. [Filters](#tickets/filters) covers what each filter selects. The unread filter and the unread sort apply after the matching and narrow the matches further. The previous and next buttons scroll each match to the center of the list. Scrolling the list by hand moves the position readout to the nearest match. The view mode can be changed during a search, and the current match is scrolled back into view. [[#client-data]]
**The deeper search.** The deeper search loads the rest of the list, 100 tickets per request, and matches the same fields over all of them. For tickets that still do not match, it requests their encrypted message content in batches of 50. Each batch is decrypted in the browser and matched the same way. Tickets matched on message content are added alongside the field matches. The deeper search starts on its own when the loaded rows produce no match, the term is at least two characters, and the first page has finished loading. The button in the search bar starts it at any time. [[#encryption #client-data]]
**When does the deeper search stop?** The search bar reports progress while the deeper search runs and shows a completed marker when it finishes. If a request for a page of tickets or a batch of message content fails, the run stops there rather than continuing over a partial set. Changing the term or closing the search bar resets the run and discards the decrypted message content it gathered. A stopped run does not restart on its own. [[#failure-states]]
**Arriving from global search.** The global search's "Show all" link loads the tickets page with the term already in the search bar and starts the deeper search without the user pressing anything. The term is carried without entering the URL or browser history. [Search](#search/how-it-works) covers the shared search surface. [[#search]]
**What does the server see?** The server never receives the term and never receives the matches. Serving the list is the paging it would serve anyway. During the deeper search the server additionally serves encrypted message content requested by ticket ID. The deeper search carries the active filter parameters, so the server returns only tickets matching both the filters and the queues the account has access to. The request for message content requires the View cases permission, and the server restricts it to the queues the account can access, ticket by ticket, independently of which IDs were asked for. A database dump or request log shows that one account read much of its accessible queues at one moment, not which words it was looking for. Encryption is the reason the search works this way. The server cannot match encrypted content, so matching happens in the browser after decryption. [The trust boundary](#deep-dive/the-trust-boundary) covers the general model. [[#server-holds #metadata #trust-boundary]]
**Search bar state, deeper search run, and shared matching.** The search bar's state and match stepping are in \`packages/client/src/lib/search/search-overlay.svelte.ts\`. The deeper search run is \`packages/client/src/lib/search/deep-search.svelte.ts\`. The matching and message-content fetching shared with the global search are in \`packages/client/src/lib/search/providers/tickets.ts\`. The typo-tolerant matcher is \`packages/client/src/lib/search/fuzzy.ts\`. The functions \`matchTitles\`, \`mergeSearchMatches\`, and \`applySearchOrder\` in \`packages/client/src/lib/tickets/ticket-list-utils.ts\` match the fields, merge message-content matches, and reduce the list to matches. The server side is \`contentSearch\` in \`packages/server/src/tickets/search.ts\`. [[#client-data]]`)
};

const es_demo_narrative_topic_list_search_body = /** @type {(inputs: Demo_Narrative_Topic_List_Search_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un control de búsqueda en la cabecera de la lista de tickets abre una barra de búsqueda debajo de los filtros. La barra compara un término con los campos descifrados de cada ticket cargado y recorre las coincidencias de una en una. El término no se envía nunca al servidor. [[#client-data #privacy #search]]
**¿Con qué compara la búsqueda?** El término se compara con el título, la descripción, el alias del cliente, el nombre de la cola y el nombre de la persona asignada de cada fila cargada. La comparación ignora acentos y diferencias entre mayúsculas y minúsculas. Se tolera un carácter insertado, uno sustituido, una pareja traspuesta o uno eliminado por término. Los resultados se ordenan por calidad de coincidencia, los mejores primero. Una fila cuyo título no ha terminado de descifrarse queda fuera hasta que lo haga. El nombre de la cola y el de la persona asignada se descifran una vez por cola y una vez por cuenta, no una vez por ticket. [[#encryption #client-data]]
**Lista reducida y recorrido de coincidencias.** La lista muestra solo las coincidencias, las mejores primero, en lugar del orden que estuviera activo, una vez que el término alcanza dos caracteres. Un término de menos de dos caracteres no reduce la lista. La comparación recorre los tickets que los filtros activos ya han seleccionado y omite cualquier ticket que los filtros excluyan. [Filtros](#tickets/filters) trata lo que selecciona cada filtro. El filtro de no leídos y la ordenación de no leídos se aplican después de la comparación y reducen las coincidencias aún más. Los botones anterior y siguiente desplazan cada coincidencia al centro de la lista. Desplazar la lista a mano mueve el indicador de posición a la coincidencia más cercana. El modo de vista se puede cambiar durante una búsqueda, y la coincidencia activa se vuelve a desplazar a la vista. [[#client-data]]
**La búsqueda profunda.** La búsqueda profunda carga el resto de la lista, 100 tickets por petición, y compara los mismos campos en todos ellos. Para los tickets que siguen sin coincidir, solicita su contenido de mensajes cifrado en lotes de 50. Cada lote se descifra en el navegador y se compara del mismo modo. Los tickets que coinciden por contenido de mensajes se añaden junto a las coincidencias de campo. La búsqueda profunda se inicia por su cuenta cuando las filas cargadas no producen ninguna coincidencia, el término tiene al menos dos caracteres y la primera página ha terminado de cargar. El botón en la barra de búsqueda la inicia en cualquier momento. [[#encryption #client-data]]
**¿Cuándo se detiene la búsqueda profunda?** La barra de búsqueda informa del progreso mientras la búsqueda profunda está en marcha y muestra un indicador de completado cuando termina. Si una petición de una página de tickets o un lote de contenido de mensajes falla, la ejecución se detiene ahí en lugar de continuar sobre un conjunto parcial. Cambiar el término o cerrar la barra de búsqueda reinicia la ejecución y descarta el contenido de mensajes descifrado que había reunido. Una ejecución detenida no se reinicia por su cuenta. [[#failure-states]]
**Llegada desde la búsqueda global.** El enlace "Mostrar todos" de la búsqueda global carga la página de tickets con el término ya en la barra de búsqueda e inicia la búsqueda profunda sin que la persona usuaria pulse nada. El término se transmite sin entrar en la URL ni en el historial del navegador. [Búsqueda](#search/how-it-works) trata la superficie de búsqueda compartida. [[#search]]
**¿Qué ve el servidor?** El servidor no recibe nunca el término ni las coincidencias. Lo que sirve es la paginación que serviría de todos modos. Durante la búsqueda profunda el servidor sirve además contenido de mensajes cifrado solicitado por identificador de ticket. La búsqueda profunda lleva los parámetros de los filtros activos, de modo que el servidor devuelve solo tickets que coinciden tanto con los filtros como con las colas a las que la cuenta tiene acceso. La petición de contenido de mensajes requiere el permiso Ver casos, y el servidor la restringe a las colas a las que la cuenta tiene acceso, ticket a ticket, con independencia de qué identificadores se pidieron. Un volcado de la base de datos o un registro de peticiones muestra que una cuenta leyó gran parte de sus colas en un momento dado, sin qué palabras buscaba. El cifrado es la razón por la que la búsqueda funciona así. El servidor no puede comparar contenido cifrado, así que la comparación ocurre en el navegador tras el descifrado. [La frontera de confianza](#deep-dive/the-trust-boundary) trata el modelo general. [[#server-holds #metadata #trust-boundary]]
**Estado de la barra, ejecución profunda y comparación compartida.** El estado de la barra de búsqueda y el avance entre coincidencias están en \`packages/client/src/lib/search/search-overlay.svelte.ts\`. La ejecución de la búsqueda profunda es \`packages/client/src/lib/search/deep-search.svelte.ts\`. La comparación y la recuperación de contenido de mensajes compartidas con la búsqueda global están en \`packages/client/src/lib/search/providers/tickets.ts\`. El comparador tolerante a errores tipográficos es \`packages/client/src/lib/search/fuzzy.ts\`. Las funciones \`matchTitles\`, \`mergeSearchMatches\` y \`applySearchOrder\` en \`packages/client/src/lib/tickets/ticket-list-utils.ts\` comparan los campos, fusionan las coincidencias de contenido de mensajes y reducen la lista a coincidencias. El lado del servidor es \`contentSearch\` en \`packages/server/src/tickets/search.ts\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_list_search_body = /** @type {(inputs: Demo_Narrative_Topic_List_Search_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À sèàrch còntròl ìn thè tìckèt lìst hèàdèr òpèns à sèàrch bàr bèlòw thè fìltèrs. Thè sèàrch bàr màtchès à tèrm àgàìnst thè dècryptèd fìèlds òf èàch lòàdèd tìckèt ànd stèps thròùgh thè màtchès ònè àt à tìmè. Thè tèrm ìs nèvèr sènt tò thè sèrvèr. [[#clìènt-dàtà #prìvàcy #sèàrch]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèàrch màtch? •••••••••** À tèrm ìs màtchèd àgàìnst thè tìtlè, thè dèscrìptìòn, thè clìènt àlìàs, thè qùèùè nàmè, ànd thè àssìgnèè nàmè òf èàch lòàdèd ròw. Màtchìng ìgnòrès àccènts ànd lèttèr càsè. Ònè ìnsèrtèd chàràctèr, ònè sùbstìtùtèd chàràctèr, ònè trànspòsèd pàìr, òr ònè dèlètèd chàràctèr pèr tèrm ìs tòlèràtèd. Rèsùlts àrè òrdèrèd by màtch qùàlìty, bèst fìrst. À ròw whòsè tìtlè hàs nòt fìnìshèd dècryptìng ìs lèft òùt ùntìl ìt hàs. Thè qùèùè nàmè ànd àssìgnèè nàmè àrè dècryptèd òncè pèr qùèùè ànd òncè pèr àccòùnt, nòt òncè pèr tìckèt. [[#èncryptìòn #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Nàrròwèd lìst ànd màtch stèppìng. ••••••••••** Thè lìst shòws ònly thè màtchès, bèst fìrst, ìn plàcè òf whàtèvèr sòrt wàs àctìvè, òncè thè tèrm rèàchès twò chàràctèrs. À tèrm ùndèr twò chàràctèrs dòès nòt rèdùcè thè lìst. Màtchìng rùns òvèr thè tìckèts thè àctìvè fìltèrs hàvè àlrèàdy sèlèctèd ànd skìps àny tìckèt thè fìltèrs èxclùdè. [Fìltèrs](#tìckèts/fìltèrs) còvèrs whàt èàch fìltèr sèlècts. Thè ùnrèàd fìltèr ànd thè ùnrèàd sòrt àpply àftèr thè màtchìng ànd nàrròw thè màtchès fùrthèr. Thè prèvìòùs ànd nèxt bùttòns scròll èàch màtch tò thè cèntèr òf thè lìst. Scròllìng thè lìst by hànd mòvès thè pòsìtìòn rèàdòùt tò thè nèàrèst màtch. Thè vìèw mòdè càn bè chàngèd dùrìng à sèàrch, ànd thè cùrrènt màtch ìs scròllèd bàck ìntò vìèw. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè dèèpèr sèàrch. ••••••** Thè dèèpèr sèàrch lòàds thè rèst òf thè lìst, 100 tìckèts pèr rèqùèst, ànd màtchès thè sàmè fìèlds òvèr àll òf thèm. Fòr tìckèts thàt stìll dò nòt màtch, ìt rèqùèsts thèìr èncryptèd mèssàgè còntènt ìn bàtchès òf 50. Èàch bàtch ìs dècryptèd ìn thè bròwsèr ànd màtchèd thè sàmè wày. Tìckèts màtchèd òn mèssàgè còntènt àrè àddèd àlòngsìdè thè fìèld màtchès. Thè dèèpèr sèàrch stàrts òn ìts òwn whèn thè lòàdèd ròws pròdùcè nò màtch, thè tèrm ìs àt lèàst twò chàràctèrs, ànd thè fìrst pàgè hàs fìnìshèd lòàdìng. Thè bùttòn ìn thè sèàrch bàr stàrts ìt àt àny tìmè. [[#èncryptìòn #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn dòès thè dèèpèr sèàrch stòp? ••••••••••** Thè sèàrch bàr rèpòrts prògrèss whìlè thè dèèpèr sèàrch rùns ànd shòws à còmplètèd màrkèr whèn ìt fìnìshès. Ìf à rèqùèst fòr à pàgè òf tìckèts òr à bàtch òf mèssàgè còntènt fàìls, thè rùn stòps thèrè ràthèr thàn còntìnùìng òvèr à pàrtìàl sèt. Chàngìng thè tèrm òr clòsìng thè sèàrch bàr rèsèts thè rùn ànd dìscàrds thè dècryptèd mèssàgè còntènt ìt gàthèrèd. À stòppèd rùn dòès nòt rèstàrt òn ìts òwn. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àrrìvìng fròm glòbàl sèàrch. •••••••••** Thè glòbàl sèàrch's "Shòw àll" lìnk lòàds thè tìckèts pàgè wìth thè tèrm àlrèàdy ìn thè sèàrch bàr ànd stàrts thè dèèpèr sèàrch wìthòùt thè ùsèr prèssìng ànythìng. Thè tèrm ìs càrrìèd wìthòùt èntèrìng thè ÙRL òr bròwsèr hìstòry. [Sèàrch](#sèàrch/hòw-ìt-wòrks) còvèrs thè shàrèd sèàrch sùrfàcè. [[#sèàrch]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr sèè? ••••••••** Thè sèrvèr nèvèr rècèìvès thè tèrm ànd nèvèr rècèìvès thè màtchès. Sèrvìng thè lìst ìs thè pàgìng ìt wòùld sèrvè ànywày. Dùrìng thè dèèpèr sèàrch thè sèrvèr àddìtìònàlly sèrvès èncryptèd mèssàgè còntènt rèqùèstèd by tìckèt ÌD. Thè dèèpèr sèàrch càrrìès thè àctìvè fìltèr pàràmètèrs, sò thè sèrvèr rètùrns ònly tìckèts màtchìng bòth thè fìltèrs ànd thè qùèùès thè àccòùnt hàs àccèss tò. Thè rèqùèst fòr mèssàgè còntènt rèqùìrès thè Vìèw càsès pèrmìssìòn, ànd thè sèrvèr rèstrìcts ìt tò thè qùèùès thè àccòùnt càn àccèss, tìckèt by tìckèt, ìndèpèndèntly òf whìch ÌDs wèrè àskèd fòr. À dàtàbàsè dùmp òr rèqùèst lòg shòws thàt ònè àccòùnt rèàd mùch òf ìts àccèssìblè qùèùès àt ònè mòmènt, nòt whìch wòrds ìt wàs lòòkìng fòr. Èncryptìòn ìs thè rèàsòn thè sèàrch wòrks thìs wày. Thè sèrvèr cànnòt màtch èncryptèd còntènt, sò màtchìng hàppèns ìn thè bròwsèr àftèr dècryptìòn. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè gènèràl mòdèl. [[#sèrvèr-hòlds #mètàdàtà #trùst-bòùndàry]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèàrch bàr stàtè, dèèpèr sèàrch rùn, ànd shàrèd màtchìng. ••••••••••••••••••** Thè sèàrch bàr's stàtè ànd màtch stèppìng àrè ìn \`pàckàgès/clìènt/src/lìb/sèàrch/sèàrch-òvèrlày.svèltè.ts\`. Thè dèèpèr sèàrch rùn ìs \`pàckàgès/clìènt/src/lìb/sèàrch/dèèp-sèàrch.svèltè.ts\`. Thè màtchìng ànd mèssàgè-còntènt fètchìng shàrèd wìth thè glòbàl sèàrch àrè ìn \`pàckàgès/clìènt/src/lìb/sèàrch/pròvìdèrs/tìckèts.ts\`. Thè typò-tòlèrànt màtchèr ìs \`pàckàgès/clìènt/src/lìb/sèàrch/fùzzy.ts\`. Thè fùnctìòns \`màtchTìtlès\`, \`mèrgèSèàrchMàtchès\`, ànd \`àpplySèàrchÒrdèr\` ìn \`pàckàgès/clìènt/src/lìb/tìckèts/tìckèt-lìst-ùtìls.ts\` màtch thè fìèlds, mèrgè mèssàgè-còntènt màtchès, ànd rèdùcè thè lìst tò màtchès. Thè sèrvèr sìdè ìs \`còntèntSèàrch\` ìn \`pàckàgès/sèrvèr/src/tìckèts/sèàrch.ts\`. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A search control in the ticket list header opens a search bar below the filters. The search bar matches a term against the decrypted fields of each loaded ti..." |
*
* @param {Demo_Narrative_Topic_List_Search_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_list_search_body = /** @type {((inputs?: Demo_Narrative_Topic_List_Search_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_List_Search_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_list_search_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_list_search_body(inputs)
	return en_demo_narrative_topic_list_search_body(inputs)
});