/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Settings_Consultant_Phone_BodyInputs */

const en_demo_narrative_settings_consultant_phone_body = /** @type {(inputs: Demo_Narrative_Settings_Consultant_Phone_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The user registers a personal phone number for receiving forwarded calls. A verification code sent to that number must be confirmed before the server will connect any call to it. [[#telephony #privacy]]
**How does the number reach the server?** The number passes through the server once, during verification. From that single pass the server stores a sealed copy encrypted to the organization's public key, a keyed hash for later comparison, and a copy encrypted under the server's own key only when the user opted into SMS notification pings. Any browser holding the organization key can open the sealed copy, but the API returns it only to the user who registered the number. The server-key copy exists so the server can send SMS pings without a browser present. [The telephony relay](#deep-dive/the-telephony-relay) covers how the server handles the number while it holds it. [[#trust-boundary #telephony]]
**Verification code and rate limits.** The code is six digits and expires after fifteen minutes. A third wrong attempt clears the code and requires a fresh send. A fresh send is refused within sixty seconds of the previous one and after five sends in an hour. Submitting a different number resets the verified state. An unproved number cannot inherit standing from a proved one. [[#failure-states]]
**What is each stored form for?** The keyed hash lets the server confirm that the number submitted with a call request matches the number that was verified, without the server holding the number in readable form. A compromised session that submits a different number fails the hash check and cannot redirect a client's call. Without pings, the server holds a number it cannot read and a hash it can only compare. [[#server-holds #telephony]]
**What changes when pings are switched off?** Switching pings off deletes the server-key copy along with the opt-in flag. Switching pings on afterward is refused because the server no longer has the number to re-encrypt, and the number must be verified again. Removing the registration deletes the sealed copy, the hash, the server-key copy, and the verified state together. [[#failure-states #server-holds]]
**What does the telephony provider learn?** Bridged calls and SMS pings both hand the number to the telephony provider, which sits outside the encryption boundary. The provider and the carrier learn which numbers spoke and when. [[#telephony #trust-boundary]]
**The verification handler and the columns.** The single phone write path is \`/relay/consultant-verify\` in \`packages/server/src/routes/relay.ts\`, calling \`prepareVerification\` in \`packages/server/src/telephony/consultant-service.ts\`. The handler reads the number as a \`Buffer\`, derives all three stored forms, sends the verification SMS, and zeroes every buffer that touched the number in a \`finally\` block. The columns \`encrypted_phone\`, \`ops_phone_hash\`, \`ops_encrypted_phone\`, and the rate-limit counters are on \`consultants\` in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. The hash uses the \`consultant-phone-index\` HKDF label, separate from the client phone label. [[#server-holds #telephony]]`)
};

const es_demo_narrative_settings_consultant_phone_body = /** @type {(inputs: Demo_Narrative_Settings_Consultant_Phone_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La persona usuaria registra un número de teléfono personal para recibir llamadas reenviadas. Se debe confirmar un código de verificación enviado a ese número antes de que el servidor conecte cualquier llamada. [[#telephony #privacy]]
**¿Cómo llega el número al servidor?** El número pasa por el servidor una vez, durante la verificación. De esa única pasada el servidor conserva una copia sellada cifrada con la clave pública de la organización, un hash con clave para comparación posterior, y una copia cifrada bajo la propia clave del servidor solo si la persona usuaria activó los avisos SMS. Cualquier navegador que posea la clave de la organización puede abrir la copia sellada, pero la API la devuelve solo a quien registró el número. La copia cifrada bajo la clave del servidor existe para que el servidor pueda enviar avisos SMS sin un navegador presente. [El relay de telefonía](#deep-dive/the-telephony-relay) trata cómo maneja el servidor el número mientras lo tiene. [[#trust-boundary #telephony]]
**Código de verificación y límites de envío.** Se genera un código de seis dígitos que caduca a los quince minutos. Tres intentos fallidos borran el código y obligan a solicitar uno nuevo. No se acepta otra solicitud en los sesenta segundos siguientes ni después de cinco solicitudes en una hora. Presentar un número diferente restablece el estado verificado. Un número sin comprobar no hereda la validez de uno comprobado. [[#failure-states]]
**¿Para qué se conserva cada forma?** El hash con clave permite al servidor confirmar que el número presentado en una solicitud de llamada coincide con el que se comprobó, sin conservar el número en forma legible. Si una sesión comprometida presenta un número distinto, la verificación del hash falla y la llamada del cliente no se redirige. Cuando los avisos están desactivados, el servidor retiene un número ilegible y un hash que solo puede cotejar. [[#server-holds #telephony]]
**¿Qué cambia al desactivar los avisos?** Desactivar los avisos elimina la copia cifrada bajo la clave del servidor junto con la marca de activación. Reactivarlos se rechaza porque el servidor ya no tiene el número para volver a cifrarlo, y se requiere verificar el número otra vez. Dar de baja el registro elimina la copia sellada, el hash, la copia cifrada y el estado verificado en una sola operación. [[#failure-states #server-holds]]
**¿Qué conoce el proveedor de telefonía?** Las llamadas puenteadas y los avisos SMS pasan el número al proveedor de telefonía. El proveedor opera fuera del alcance del cifrado y, junto con el operador, conoce qué números se comunicaron y en qué momento. [[#telephony #trust-boundary]]
**El controlador de verificación y las columnas.** La única vía de escritura del número es \`/relay/consultant-verify\` en \`packages/server/src/routes/relay.ts\`, que invoca \`prepareVerification\` en \`packages/server/src/telephony/consultant-service.ts\`. El controlador lee el número como \`Buffer\`, deriva las tres formas almacenadas, envía el SMS de verificación y pone a cero todos los buffers que tocaron el número en un bloque \`finally\`. Las columnas \`encrypted_phone\`, \`ops_phone_hash\`, \`ops_encrypted_phone\` y los contadores de frecuencia están en \`consultants\`, en \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. El hash se calcula bajo la etiqueta HKDF \`consultant-phone-index\`, separada de la etiqueta de teléfono de clientes. [[#server-holds #telephony]]`)
};

const en_xa2_demo_narrative_settings_consultant_phone_body = /** @type {(inputs: Demo_Narrative_Settings_Consultant_Phone_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ùsèr règìstèrs à pèrsònàl phònè nùmbèr fòr rècèìvìng fòrwàrdèd càlls. À vèrìfìcàtìòn còdè sènt tò thàt nùmbèr mùst bè cònfìrmèd bèfòrè thè sèrvèr wìll cònnèct àny càll tò ìt. [[#tèlèphòny #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè nùmbèr rèàch thè sèrvèr? ••••••••••••** Thè nùmbèr pàssès thròùgh thè sèrvèr òncè, dùrìng vèrìfìcàtìòn. Fròm thàt sìnglè pàss thè sèrvèr stòrès à sèàlèd còpy èncryptèd tò thè òrgànìzàtìòn's pùblìc kèy, à kèyèd hàsh fòr làtèr còmpàrìsòn, ànd à còpy èncryptèd ùndèr thè sèrvèr's òwn kèy ònly whèn thè ùsèr òptèd ìntò SMS nòtìfìcàtìòn pìngs. Àny bròwsèr hòldìng thè òrgànìzàtìòn kèy càn òpèn thè sèàlèd còpy, bùt thè ÀPÌ rètùrns ìt ònly tò thè ùsèr whò règìstèrèd thè nùmbèr. Thè sèrvèr-kèy còpy èxìsts sò thè sèrvèr càn sènd SMS pìngs wìthòùt à bròwsèr prèsènt. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs hòw thè sèrvèr hàndlès thè nùmbèr whìlè ìt hòlds ìt. [[#trùst-bòùndàry #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Vèrìfìcàtìòn còdè ànd ràtè lìmìts. •••••••••••** Thè còdè ìs sìx dìgìts ànd èxpìrès àftèr fìftèèn mìnùtès. À thìrd wròng àttèmpt clèàrs thè còdè ànd rèqùìrès à frèsh sènd. À frèsh sènd ìs rèfùsèd wìthìn sìxty sècònds òf thè prèvìòùs ònè ànd àftèr fìvè sènds ìn àn hòùr. Sùbmìttìng à dìffèrènt nùmbèr rèsèts thè vèrìfìèd stàtè. Àn ùnpròvèd nùmbèr cànnòt ìnhèrìt stàndìng fròm à pròvèd ònè. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt ìs èàch stòrèd fòrm fòr? •••••••••** Thè kèyèd hàsh lèts thè sèrvèr cònfìrm thàt thè nùmbèr sùbmìttèd wìth à càll rèqùèst màtchès thè nùmbèr thàt wàs vèrìfìèd, wìthòùt thè sèrvèr hòldìng thè nùmbèr ìn rèàdàblè fòrm. À còmpròmìsèd sèssìòn thàt sùbmìts à dìffèrènt nùmbèr fàìls thè hàsh chèck ànd cànnòt rèdìrèct à clìènt's càll. Wìthòùt pìngs, thè sèrvèr hòlds à nùmbèr ìt cànnòt rèàd ànd à hàsh ìt càn ònly còmpàrè. [[#sèrvèr-hòlds #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt chàngès whèn pìngs àrè swìtchèd òff? •••••••••••••** Swìtchìng pìngs òff dèlètès thè sèrvèr-kèy còpy àlòng wìth thè òpt-ìn flàg. Swìtchìng pìngs òn àftèrwàrd ìs rèfùsèd bècàùsè thè sèrvèr nò lòngèr hàs thè nùmbèr tò rè-èncrypt, ànd thè nùmbèr mùst bè vèrìfìèd àgàìn. Rèmòvìng thè règìstràtìòn dèlètès thè sèàlèd còpy, thè hàsh, thè sèrvèr-kèy còpy, ànd thè vèrìfìèd stàtè tògèthèr. [[#fàìlùrè-stàtès #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè tèlèphòny pròvìdèr lèàrn? ••••••••••••** Brìdgèd càlls ànd SMS pìngs bòth hànd thè nùmbèr tò thè tèlèphòny pròvìdèr, whìch sìts òùtsìdè thè èncryptìòn bòùndàry. Thè pròvìdèr ànd thè càrrìèr lèàrn whìch nùmbèrs spòkè ànd whèn. [[#tèlèphòny #trùst-bòùndàry]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè vèrìfìcàtìòn hàndlèr ànd thè còlùmns. •••••••••••••** Thè sìnglè phònè wrìtè pàth ìs \`/rèlày/cònsùltànt-vèrìfy\` ìn \`pàckàgès/sèrvèr/src/ròùtès/rèlày.ts\`, càllìng \`prèpàrèVèrìfìcàtìòn\` ìn \`pàckàgès/sèrvèr/src/tèlèphòny/cònsùltànt-sèrvìcè.ts\`. Thè hàndlèr rèàds thè nùmbèr às à \`Bùffèr\`, dèrìvès àll thrèè stòrèd fòrms, sènds thè vèrìfìcàtìòn SMS, ànd zèròès èvèry bùffèr thàt tòùchèd thè nùmbèr ìn à \`fìnàlly\` blòck. Thè còlùmns \`èncryptèd_phònè\`, \`òps_phònè_hàsh\`, \`òps_èncryptèd_phònè\`, ànd thè ràtè-lìmìt còùntèrs àrè òn \`cònsùltànts\` ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`. Thè hàsh ùsès thè \`cònsùltànt-phònè-ìndèx\` HKDF làbèl, sèpàràtè fròm thè clìènt phònè làbèl. [[#sèrvèr-hòlds #tèlèphòny]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The user registers a personal phone number for receiving forwarded calls. A verification code sent to that number must be confirmed before the server will co..." |
*
* @param {Demo_Narrative_Settings_Consultant_Phone_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_settings_consultant_phone_body = /** @type {((inputs?: Demo_Narrative_Settings_Consultant_Phone_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Settings_Consultant_Phone_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_settings_consultant_phone_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_settings_consultant_phone_body(inputs)
	return en_demo_narrative_settings_consultant_phone_body(inputs)
});