/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Keys_BodyInputs */

const en_demo_narrative_admin_keys_body = /** @type {(inputs: Demo_Narrative_Admin_Keys_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Every account in an organization holds its own wrapped copy of one organization key, and this section reports whether the signed-in account has that copy and offers the two operations on the key itself. [[#keys]]
**When an account has no copy.** An account that has enrolled its own keys but holds no wrapped copy cannot open anything sealed to the organization, which is the queue names, the note type names, the organization's own words for things and the display names on the roster, while the case content wrapped to that account personally is unaffected. The copy arrives without anyone requesting it, because a signed-in account holding the Manage keys permission checks every five minutes for accounts that are enrolled and unwrapped and wraps the key for each one, and a second copy of the same wrap is discarded rather than treated as an error. Until such a session runs, the account stays in that state. [Roster tools](#admin-people/roster-tools) covers the filter that finds those accounts. [[#keys #failure-states]]
**What the escrow file is and what it costs.** Export writes one JSON file that names its own format, its key derivation, the cost parameters it used and the salt and nonce beside the ciphertext, so the key can be recovered on an air-gapped machine with no CARE-Y code on it. The passphrase has to be at least 20 characters and a known common one is refused, the derivation is Argon2id at 256 MB and four passes because it runs on a workstation rather than during a sign-in. The file's SHA-256 is shown in groups of four characters so two copies can be compared by eye, and the passphrase bytes and the organization secret key are both zeroed afterwards whether the export finished or failed. Holding the file is holding the organization's data, and it restores keys rather than rows: anything deleted under [the retention policy](#admin-org/retention) is gone from an escrow recovery too. [[#keys #encryption]]
**Rotation and the chain behind it.** Rotation generates a new keypair in the browser, seals the outgoing secret key under the new one and stores that as a generation record, then wraps the new secret once for each active account that holds a public key and submits every wrap in a single request. The sealed chain is what keeps data written before the rotation readable, because each row carries the generation it was sealed under and a reader walks back along the chain to reach it. Accounts that are inactive or have never signed in receive no wrapped copy. The rows that identify people are re-sealed to the new key while the dialog is still open, covering client records, account rows, sessions, invitations, the blocklist, consultants and the two tables of wrapped case keys, and the remaining organization configuration converges afterwards under a sweep that any later sign-in holding Manage keys resumes where it stopped. The browser then fetches and unwraps its own copy through the ordinary sign-in path rather than trusting the key it just generated, and the dialog stays open while the operation is in flight. [How keys are derived](#deep-dive/how-keys-are-derived) covers where the organization key sits among the others. [[#keys #encryption #failure-states]]
**Who can do either.** Escrow export and key rotation both require the Manage keys permission, which is one of three grants that stay with Admin whatever a role configuration says, so a hand-written database row granting it elsewhere has no effect. [The permission system](#deep-dive/the-permission-system) covers the other two. [[#permissions]]
**The generation table and the reseal endpoint.** \`packages/server/src/db/migrations/tenant/113_org_key_generations.ts\` creates \`org_key_generations\`, one row per generation carrying the public key and the previous secret sealed under it, and stamps every table holding organization-sealed ciphertext with the generation its rows were written under. Re-encryption runs through \`packages/server/src/crypto/org-reseal-service.ts\`, which cannot check the plaintext it is handed because the server holds no organization key, so its guarantee is structural: a row is writable only while its stamp is below the current generation, the stamp bumps inside the same update, and the browser declares the rows it could not decrypt instead of passing over them silently. [[#keys #server-holds]]`)
};

const es_demo_narrative_admin_keys_body = /** @type {(inputs: Demo_Narrative_Admin_Keys_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cada cuenta de una organización guarda su propia copia envuelta de una sola clave de la organización, y esta sección informa de si la cuenta que ha iniciado sesión tiene esa copia y ofrece las dos operaciones sobre la clave en sí. [[#keys]]
**Cuando una cuenta no tiene copia.** Una cuenta que ha inscrito sus propias claves pero no tiene copia envuelta no puede abrir nada sellado para la organización, es decir los nombres de las colas, los nombres de los tipos de nota, las palabras propias de la organización y los nombres visibles del directorio, mientras que el contenido de los casos envuelto para esa cuenta en particular no se ve afectado. La copia llega sin que nadie la pida, porque una cuenta con sesión iniciada que tiene el permiso de gestionar claves comprueba cada cinco minutos si hay cuentas inscritas y sin envolver y envuelve la clave para cada una, y una segunda copia del mismo envoltorio se descarta en lugar de tratarse como error. Hasta que ocurra una sesión así, la cuenta se queda en ese estado. [Herramientas del directorio](#admin-people/roster-tools) trata el filtro que localiza esas cuentas. [[#keys #failure-states]]
**Qué es el archivo de custodia y qué cuesta.** La exportación escribe un único archivo JSON que declara su propio formato, su derivación de clave, los parámetros de coste que usó y la sal y el nonce junto al texto cifrado, de modo que la clave se puede recuperar en una máquina aislada sin nada de código de CARE-Y. La frase de contraseña tiene que tener al menos 20 caracteres y se rechaza si es una frase común conocida, la derivación es Argon2id con 256 MB y cuatro pasadas porque se ejecuta en una estación de trabajo y no durante un inicio de sesión. El SHA-256 del archivo se muestra en grupos de cuatro caracteres para poder comparar dos copias a simple vista, y tanto los bytes de la frase de contraseña como la clave secreta de la organización se ponen a cero después, haya terminado la exportación o haya fallado. Tener el archivo es tener los datos de la organización, y lo que restaura son claves y no filas: lo que se haya borrado por [la política de retención](#admin-org/retention) tampoco vuelve con una recuperación de custodia. [[#keys #encryption]]
**La rotación y la cadena que la sostiene.** La rotación genera un par de claves nuevo en el navegador, sella la clave secreta saliente con la nueva y guarda eso como un registro de generación, y después envuelve la clave secreta nueva una vez por cada cuenta activa que tenga clave pública y envía todos los envoltorios en una sola petición. La cadena sellada es lo que mantiene legibles los datos escritos antes de la rotación, porque cada fila lleva la generación con la que se selló y quien lee recorre la cadena hacia atrás hasta alcanzarla. Las cuentas inactivas o que nunca han iniciado sesión no reciben copia envuelta. Las filas que identifican a personas se vuelven a sellar con la clave nueva mientras el diálogo sigue abierto, y eso abarca los registros de clientes, las filas de cuentas, las sesiones, las invitaciones, la lista de bloqueo, las personas consultoras y las dos tablas de claves de caso envueltas; el resto de la configuración de la organización converge después mediante un barrido que cualquier inicio de sesión posterior con el permiso de gestionar claves retoma donde se quedó. Luego el navegador obtiene y desenvuelve su propia copia por la vía normal de inicio de sesión en lugar de fiarse de la clave que acaba de generar, y el diálogo permanece abierto mientras la operación está en curso. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) explica dónde encaja la clave de la organización entre las demás. [[#keys #encryption #failure-states]]
**Quién puede hacer cualquiera de las dos.** La exportación de custodia y la rotación de claves requieren ambas el permiso de gestionar claves, que es una de las tres concesiones que se quedan con Admin diga lo que diga una configuración de roles, así que una fila escrita a mano en la base de datos que lo conceda a otro rol no tiene efecto. [El sistema de permisos](#deep-dive/the-permission-system) trata las otras dos. [[#permissions]]
**La tabla de generaciones y el punto de resellado.** \`packages/server/src/db/migrations/tenant/113_org_key_generations.ts\` crea \`org_key_generations\`, una fila por generación con la clave pública y la secreta anterior sellada con ella, y marca con su generación cada tabla que guarda texto cifrado sellado para la organización. El recifrado pasa por \`packages/server/src/crypto/org-reseal-service.ts\`, que no puede comprobar el texto claro que recibe porque el servidor no tiene la clave de la organización, así que su garantía es estructural: una fila solo se puede escribir mientras su marca esté por debajo de la generación actual, la marca sube dentro de la misma actualización, y el navegador declara las filas que no pudo descifrar en vez de pasarlas por alto en silencio. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_admin_keys_body = /** @type {(inputs: Demo_Narrative_Admin_Keys_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè kèys sèctìòn rèpòrts thè òrgànìzàtìòn kèy stàtùs ànd pròvìdès twò òpèràtìòns òn ìt.
 •••••••••••••••••••••••••••**Èscròw. •••** Thè èscròw fìlè càrrìès ìts òwn KDF pàràmètèrs, sàlt, nòncè, ànd cìphèrtèxt ìn bàsè64, sò ìt càn bè rèàd òn àny màchìnè wìthòùt CÀRÈ-Y ìnstàllèd. Thè pàssphràsè mùst bè àt lèàst 20 chàràctèrs, ànd thè kèy dèrìvàtìòn ìs Àrgòn2ìd. Thè fìlè's SHÀ-256 ìs shòwn ìn gròùps òf fòùr chàràctèrs fòr vìsùàl còmpàrìsòn, ànd bòth thè pàssphràsè bytès ànd thè òrgànìzàtìòn's sècrèt kèy àrè zèròèd àftèr thè èxpòrt whèthèr òr nòt ìt sùccèèdèd.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Kèy ròtàtìòn. ••••** Ròtàtìòn gènèràtès à nèw kèypàìr ìn thè bròwsèr, wràps thè nèw sècrèt kèy òncè pèr àctìvè ùsèr whò hòlds à pùblìc kèy, ànd sùbmìts àll wràps ìn ònè rèqùèst. Ùsèrs whò àrè ìnàctìvè òr hàvè nèvèr sìgnèd ìn rècèìvè nò wràppèd còpy. Òn còmplètìòn thè bròwsèr fètchès ànd ùnwràps thè kèy thròùgh thè nòrmàl sìgn ìn pàth ràthèr thàn trùstìng thè kèy ìt jùst gènèràtèd, ànd thè ròtàtìòn dìàlòg cànnòt bè dìsmìssèd whìlè thè òpèràtìòn ìs ìn flìght.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pèrmìssìòns. ••••** Bòth èscròw èxpòrt ànd kèy ròtàtìòn rèqùìrè thè Mànàgè kèys pèrmìssìòn. ••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Every account in an organization holds its own wrapped copy of one organization key, and this section reports whether the signed-in account has that copy and..." |
*
* @param {Demo_Narrative_Admin_Keys_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_keys_body = /** @type {((inputs?: Demo_Narrative_Admin_Keys_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Keys_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_keys_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_keys_body(inputs)
	return en_demo_narrative_admin_keys_body(inputs)
});