/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs */

const en_demo_narrative_deepdive_how_encryption_works_body = /** @type {(inputs: Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A client's messages and the notes written about them are encrypted in the browser before they leave the device, and the server holds only the result. The server has no key that opens it, which is a different and stronger statement than a promise not to look. [Verifying the code](#deep-dive/verifying-the-code) covers how the browser confirms the code performing that encryption has not been tampered with. [[#encryption #client-data]]
Each kind of data has its own key and its own audience, and one kind is public on purpose. [[#encryption #keys #server-holds]]
- The case record, its messages, its notes and the client's alias are readable only by the users authorized on that case. A fresh intake submission or portal reply is sealed to the organization key until someone opens the case, so any signed-in user can unseal it during that window. [How the visitor is protected](#client-intake/how-protected) covers that conversion. [[#encryption #client-data]]
- Shared organization material such as library articles, queue names, note types and settings is readable by any signed-in user in the organization. [[#encryption #keys]]
- Operational configuration such as telephony credentials and mail server settings is readable by the server itself, along with the phone number and email address it needs to reach a client, because the server is what places a call at three in the morning with nobody watching. [[#encryption #server-holds]]
- The intake page logo and colors are public so a client recognizes the organization they are contacting. [[#encryption #privacy]]
An attacker who seizes the server and takes the whole database gets ciphertext for all three encrypted tiers, plus the telephony credentials from the operational tier, which grant phone system access and nothing about any client. Opening the case tier requires a user's password run through the key derivation protocol, and opening the organization tier requires the same password first. [How keys are derived](#deep-dive/how-keys-are-derived) covers why a password guess is expensive and why a single seized machine is not enough. [[#encryption #server-holds]]
Without breaking the encryption, an attacker does learn the shape of the work. Case rows carry a plaintext status, priority, queue reference, creation timestamp and assignment. A database dump shows that cases exist, how many, when each arrived, which queue took it, how urgent someone judged it, and that a particular account was assigned to it. It does not show the client's alias, the case summary or a single message. The client's phone number and email address sit in the operational tier, so a dump taken together with the server's secrets file yields those two. The design does not hide overall activity levels or when they occur. [The trust boundary](#deep-dive/the-trust-boundary) lists this exposure field by field. [[#metadata #trust-boundary #server-holds]]
Encryption also stops at the edges of the device. A user whose laptop is compromised, or whose browser runs a malicious extension, is showing decrypted case content to whatever is watching, and no server-side property can prevent that. A message that arrived as an ordinary text message was readable by the carrier and the telephony provider before CARE-Y ever encrypted it, which is why the case thread marks where a message came from. [[#failure-states #telephony]]
**Per-case keys and wrapping.** Each case gets its own 32-byte symmetric key, and case content is sealed with XChaCha20-Poly1305. The additional authenticated data binds each ciphertext to the case and to the storage slot it was encrypted for, so a ciphertext moved to a different slot or a different case fails authentication rather than decrypting into the wrong place. No copy of the case key exists in the clear. For each authorized user it is wrapped to that user's ristretto255 public key using ECIES, so the server can wrap a key for a user it cannot impersonate and cannot unwrap. A new case is wrapped for the creator and for each queue member whose public key is on file, and an empty wrap set is refused. Joining a queue backfills the wraps for that queue's existing cases through a resumable sweep, and deactivating the only account holding a case's wrap is refused unless an administrator forces it past a confirmation stating how many cases would become unreadable. Removing a user from a queue deletes the wraps issued while they were a member. On open, the browser worker computes the shared secret from the user's private scalar and the stored ephemeral point, unwraps the case key, and decrypts, with no server round trip in the decryption step. [[#encryption #keys]]
**The organization tier and the public tier.** Shared material uses one organization keypair. The private half is wrapped per user under a key derived from that user's master key, so every signed-in user can open library articles and queue names while the server, holding only the public half, can seal new values without reading any. User display names and login identifiers are stored as sealed boxes under the same organization public key, which is why an administrator's browser can list users by name and the server cannot. Intake branding is the exception, because its key derives from the organization public key by hash and is therefore readable by anyone, which is the intent for a page a client must recognize before trusting it. [The organization key lifecycle](#deep-dive/organization-key-lifecycle) covers creation, rotation, and what happens when no account holds a copy. [[#encryption #keys #privacy]]
**What does the password not unlock?** Deactivating a user deletes their per-case wrapped keys, so the user's derived private key has nothing left to unwrap even if they still know their password. Changing a password changes the derived private key, which is why a password change re-wraps every case key the user can read. That re-wrap is proportional to the number of cases they have access to. [Password and key re-wrap](#settings/password) covers the full sequence. [[#keys #failure-states]]
**Contributor boundaries.** The primitives live in \`packages/crypto/src\`, split by job. [[#encryption #client-data]]
- \`content.ts\` does slot-bound content encryption. [[#encryption]]
- \`ecies.ts\` and \`keywrap.ts\` do key wrapping. [[#encryption #keys]]
- \`derive.ts\` and \`hkdf.ts\` do derivation. [[#keys]]
- \`mem.ts\` zeroes buffers. [[#encryption]]
Column shape is the design decision that outlives the code. The \`tickets\` table holds \`encrypted_title\` and \`encrypted_description\` as bytea beside plaintext \`status\`, \`priority\`, \`queue_id\`, \`assigned_to\` and \`created_at\`, and \`ticket_key_wraps\` holds one row per user per case with the ephemeral point, nonce and wrapped key. Adding a field to a case means choosing between the encrypted payload and the plaintext metadata, and a field chosen as plaintext stays visible in every future database dump. [[#encryption #client-data #server-holds]]`)
};

const es_demo_narrative_deepdive_how_encryption_works_body = /** @type {(inputs: Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los mensajes de un cliente y las notas escritas sobre él se cifran en el navegador de la persona usuaria antes de salir del dispositivo, y el servidor conserva solo el resultado. El servidor no tiene ninguna clave que lo abra, que es una afirmación distinta y más fuerte que la promesa de no mirar. [Verificar el código](#deep-dive/verifying-the-code) trata cómo el navegador confirma que el código que realiza ese cifrado no ha sido alterado. [[#encryption #client-data]]
Cada tipo de dato tiene su propia clave y su propia audiencia, y uno de ellos es público a propósito. [[#encryption #keys #server-holds]]
- El expediente del caso, sus mensajes, sus notas y el alias del cliente solo son legibles por las personas usuarias autorizadas en ese caso. Un envío de admisión o una respuesta del portal recién llegados se sellan con la clave de la organización hasta que alguien abre el caso, de modo que cualquier persona usuaria con la sesión iniciada puede abrirlos durante esa ventana. [Cómo se protege al visitante](#client-intake/how-protected) trata esa conversión. [[#encryption #client-data]]
- El material compartido de la organización, como artículos de la biblioteca, nombres de cola, tipos de nota y ajustes, es legible por cualquier persona usuaria de la organización con la sesión iniciada. [[#encryption #keys]]
- La configuración operativa, como las credenciales de telefonía y los ajustes del servidor de correo, es legible por el servidor mismo, junto con el número de teléfono y la dirección de correo que necesita para contactar a un cliente, porque el servidor es lo que realiza una llamada a las tres de la mañana sin nadie mirando. [[#encryption #server-holds]]
- El logotipo y los colores de la página de admisión son públicos para que un cliente reconozca a la organización con la que está contactando. [[#encryption #privacy]]
Un atacante que incauta el servidor y se lleva toda la base de datos obtiene texto cifrado de los tres niveles cifrados, más las credenciales de telefonía del nivel operativo, que dan acceso al sistema telefónico y nada sobre ningún cliente. Abrir el nivel del caso requiere la contraseña de una persona usuaria pasada por el protocolo de derivación de claves, y abrir el nivel de la organización requiere antes esa misma contraseña. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) explica por qué adivinar una contraseña es costoso y por qué una sola máquina incautada no basta. [[#encryption #server-holds]]
Sin romper el cifrado, un atacante sí aprende la forma del trabajo. Las filas de caso llevan en texto plano el estado, la prioridad, la referencia de cola, la marca de tiempo de creación y la asignación. Un volcado de la base de datos muestra que existen casos, cuántos, cuándo llegó cada uno, qué cola lo tomó, con cuánta urgencia lo juzgó alguien y que una cuenta concreta quedó asignada a él. No muestra el alias del cliente, el resumen del caso ni un solo mensaje. El número de teléfono y la dirección de correo del cliente están en el nivel operativo, así que un volcado tomado junto con el archivo de secretos del servidor sí entrega esos dos. El diseño no oculta los niveles generales de actividad ni cuándo ocurren. [La frontera de confianza](#deep-dive/the-trust-boundary) enumera esta exposición campo por campo. [[#metadata #trust-boundary #server-holds]]
El cifrado también se detiene en los bordes del dispositivo. Una persona usuaria cuyo portátil está comprometido, o cuyo navegador ejecuta una extensión maliciosa, está mostrando contenido descifrado del caso a lo que sea que esté observando, y ninguna propiedad del lado del servidor puede impedirlo. Un mensaje que llegó como mensaje de texto ordinario era legible por la compañía telefónica y por el proveedor de telefonía antes de que CARE-Y lo cifrara, y por eso el hilo del caso marca de dónde vino cada mensaje. [[#failure-states #telephony]]
**Claves por caso y envoltura.** Cada caso recibe su propia clave simétrica de 32 bytes, y el contenido del caso se sella con XChaCha20-Poly1305. Los datos autenticados adicionales ligan cada texto cifrado al caso y a la ranura de almacenamiento para la que se cifró, de modo que un texto cifrado movido a otra ranura o a otro caso falla la autenticación en lugar de descifrarse en el lugar equivocado. No existe ninguna copia de la clave del caso en claro. Para cada persona usuaria autorizada se envuelve con su clave pública ristretto255 mediante ECIES, de modo que el servidor puede envolver una clave para una persona usuaria a la que no puede suplantar y cuya envoltura no puede abrir. Un caso nuevo se envuelve para la persona creadora y para cada miembro de la cola cuya clave pública conste en el archivo, y un conjunto de envolturas vacío se rechaza. Unirse a una cola rellena las envolturas de los casos que esa cola ya tenía mediante un barrido reanudable, y desactivar a la única cuenta que sostiene la envoltura de un caso se rechaza salvo que una persona administradora lo fuerce pasando por una confirmación que indica cuántos casos quedarían ilegibles. Retirar a una persona usuaria de una cola elimina las envolturas emitidas mientras formaba parte de ella. Al abrir, el worker del navegador calcula el secreto compartido a partir del escalar privado de la persona usuaria y del punto efímero almacenado, desenvuelve la clave del caso y descifra, sin ninguna ida y vuelta al servidor en el paso de descifrado. [[#encryption #keys]]
**El nivel de la organización y el nivel público.** El material compartido usa un único par de claves de la organización. La mitad privada se envuelve por persona usuaria bajo una clave derivada de su clave maestra, de modo que toda persona usuaria con la sesión iniciada puede abrir los artículos de la biblioteca y los nombres de cola mientras el servidor, que solo tiene la mitad pública, puede sellar valores nuevos sin leer ninguno. Los nombres visibles y los identificadores de inicio de sesión de las personas usuarias se almacenan como cajas selladas bajo esa misma clave pública de la organización, y por eso el navegador de una persona administradora puede listar a las personas usuarias por nombre y el servidor no. La identidad visual de admisión es la excepción, porque su clave se deriva por hash de la clave pública de la organización y por tanto es legible por cualquiera, que es la intención para una página que un cliente debe reconocer antes de confiar en ella. [El ciclo de vida de la clave de la organización](#deep-dive/organization-key-lifecycle) trata la creación, la rotación y lo que ocurre cuando ninguna cuenta tiene una copia. [[#encryption #keys #privacy]]
**¿Qué no desbloquea la contraseña?** Desactivar a una persona usuaria elimina sus claves envueltas por caso, así que su clave privada derivada no tiene nada que desenvolver aunque siga conociendo su contraseña. Cambiar una contraseña cambia la clave privada derivada, y por eso un cambio de contraseña vuelve a envolver cada clave de caso que la persona usuaria puede leer. Esa re-envoltura es proporcional al número de casos a los que tiene acceso. [Contraseña y re-envolvimiento de claves](#settings/password) trata la secuencia completa. [[#keys #failure-states]]
**Fronteras para quien contribuye.** Las primitivas viven en \`packages/crypto/src\`, divididas por tarea. [[#encryption #client-data]]
- \`content.ts\` hace el cifrado de contenido ligado a la ranura. [[#encryption]]
- \`ecies.ts\` y \`keywrap.ts\` hacen la envoltura de claves. [[#encryption #keys]]
- \`derive.ts\` y \`hkdf.ts\` hacen la derivación. [[#keys]]
- \`mem.ts\` pone los búferes a cero. [[#encryption]]
La forma de las columnas es la decisión de diseño que sobrevive al código. La tabla \`tickets\` guarda \`encrypted_title\` y \`encrypted_description\` como bytea junto a \`status\`, \`priority\`, \`queue_id\`, \`assigned_to\` y \`created_at\` en texto plano, y \`ticket_key_wraps\` guarda una fila por persona usuaria y por caso con el punto efímero, el nonce y la clave envuelta. Añadir un campo a un caso significa elegir entre la carga cifrada y los metadatos en texto plano, y un campo elegido como texto plano sigue visible en todos los volcados futuros de la base de datos. [[#encryption #client-data #server-holds]]`)
};

const en_xa2_demo_narrative_deepdive_how_encryption_works_body = /** @type {(inputs: Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À clìènt's mèssàgès ànd thè nòtès wrìttèn àbòùt thèm àrè èncryptèd ìn thè bròwsèr bèfòrè thèy lèàvè thè dèvìcè, ànd thè sèrvèr hòlds ònly thè rèsùlt. Thè sèrvèr hàs nò kèy thàt òpèns ìt, whìch ìs à dìffèrènt ànd stròngèr stàtèmènt thàn à pròmìsè nòt tò lòòk. [Vèrìfyìng thè còdè](#dèèp-dìvè/vèrìfyìng-thè-còdè) còvèrs hòw thè bròwsèr cònfìrms thè còdè pèrfòrmìng thàt èncryptìòn hàs nòt bèèn tàmpèrèd wìth. [[#èncryptìòn #clìènt-dàtà]]
Èàch kìnd òf dàtà hàs ìts òwn kèy ànd ìts òwn àùdìèncè, ànd ònè kìnd ìs pùblìc òn pùrpòsè. [[#èncryptìòn #kèys #sèrvèr-hòlds]]
- Thè càsè rècòrd, ìts mèssàgès, ìts nòtès ànd thè clìènt's àlìàs àrè rèàdàblè ònly by thè ùsèrs àùthòrìzèd òn thàt càsè. À frèsh ìntàkè sùbmìssìòn òr pòrtàl rèply ìs sèàlèd tò thè òrgànìzàtìòn kèy ùntìl sòmèònè òpèns thè càsè, sò àny sìgnèd-ìn ùsèr càn ùnsèàl ìt dùrìng thàt wìndòw. [Hòw thè vìsìtòr ìs pròtèctèd](#clìènt-ìntàkè/hòw-pròtèctèd) còvèrs thàt cònvèrsìòn. [[#èncryptìòn #clìènt-dàtà]]
- Shàrèd òrgànìzàtìòn màtèrìàl sùch às lìbràry àrtìclès, qùèùè nàmès, nòtè typès ànd sèttìngs ìs rèàdàblè by àny sìgnèd-ìn ùsèr ìn thè òrgànìzàtìòn. [[#èncryptìòn #kèys]]
- Òpèràtìònàl cònfìgùràtìòn sùch às tèlèphòny crèdèntìàls ànd màìl sèrvèr sèttìngs ìs rèàdàblè by thè sèrvèr ìtsèlf, àlòng wìth thè phònè nùmbèr ànd èmàìl àddrèss ìt nèèds tò rèàch à clìènt, bècàùsè thè sèrvèr ìs whàt plàcès à càll àt thrèè ìn thè mòrnìng wìth nòbòdy wàtchìng. [[#èncryptìòn #sèrvèr-hòlds]]
- Thè ìntàkè pàgè lògò ànd còlòrs àrè pùblìc sò à clìènt rècògnìzès thè òrgànìzàtìòn thèy àrè còntàctìng. [[#èncryptìòn #prìvàcy]]
Àn àttàckèr whò sèìzès thè sèrvèr ànd tàkès thè whòlè dàtàbàsè gèts cìphèrtèxt fòr àll thrèè èncryptèd tìèrs, plùs thè tèlèphòny crèdèntìàls fròm thè òpèràtìònàl tìèr, whìch grànt phònè systèm àccèss ànd nòthìng àbòùt àny clìènt. Òpènìng thè càsè tìèr rèqùìrès à ùsèr's pàsswòrd rùn thròùgh thè kèy dèrìvàtìòn pròtòcòl, ànd òpènìng thè òrgànìzàtìòn tìèr rèqùìrès thè sàmè pàsswòrd fìrst. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs why à pàsswòrd gùèss ìs èxpènsìvè ànd why à sìnglè sèìzèd màchìnè ìs nòt ènòùgh. [[#èncryptìòn #sèrvèr-hòlds]]
Wìthòùt brèàkìng thè èncryptìòn, àn àttàckèr dòès lèàrn thè shàpè òf thè wòrk. Càsè ròws càrry à plàìntèxt stàtùs, prìòrìty, qùèùè rèfèrèncè, crèàtìòn tìmèstàmp ànd àssìgnmènt. À dàtàbàsè dùmp shòws thàt càsès èxìst, hòw màny, whèn èàch àrrìvèd, whìch qùèùè tòòk ìt, hòw ùrgènt sòmèònè jùdgèd ìt, ànd thàt à pàrtìcùlàr àccòùnt wàs àssìgnèd tò ìt. Ìt dòès nòt shòw thè clìènt's àlìàs, thè càsè sùmmàry òr à sìnglè mèssàgè. Thè clìènt's phònè nùmbèr ànd èmàìl àddrèss sìt ìn thè òpèràtìònàl tìèr, sò à dùmp tàkèn tògèthèr wìth thè sèrvèr's sècrèts fìlè yìèlds thòsè twò. Thè dèsìgn dòès nòt hìdè òvèràll àctìvìty lèvèls òr whèn thèy òccùr. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) lìsts thìs èxpòsùrè fìèld by fìèld. [[#mètàdàtà #trùst-bòùndàry #sèrvèr-hòlds]]
Èncryptìòn àlsò stòps àt thè èdgès òf thè dèvìcè. À ùsèr whòsè làptòp ìs còmpròmìsèd, òr whòsè bròwsèr rùns à màlìcìòùs èxtènsìòn, ìs shòwìng dècryptèd càsè còntènt tò whàtèvèr ìs wàtchìng, ànd nò sèrvèr-sìdè pròpèrty càn prèvènt thàt. À mèssàgè thàt àrrìvèd às àn òrdìnàry tèxt mèssàgè wàs rèàdàblè by thè càrrìèr ànd thè tèlèphòny pròvìdèr bèfòrè CÀRÈ-Y èvèr èncryptèd ìt, whìch ìs why thè càsè thrèàd màrks whèrè à mèssàgè càmè fròm. [[#fàìlùrè-stàtès #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pèr-càsè kèys ànd wràppìng. •••••••••** Èàch càsè gèts ìts òwn 32-bytè symmètrìc kèy, ànd càsè còntènt ìs sèàlèd wìth XChàChà20-Pòly1305. Thè àddìtìònàl àùthèntìcàtèd dàtà bìnds èàch cìphèrtèxt tò thè càsè ànd tò thè stòràgè slòt ìt wàs èncryptèd fòr, sò à cìphèrtèxt mòvèd tò à dìffèrènt slòt òr à dìffèrènt càsè fàìls àùthèntìcàtìòn ràthèr thàn dècryptìng ìntò thè wròng plàcè. Nò còpy òf thè càsè kèy èxìsts ìn thè clèàr. Fòr èàch àùthòrìzèd ùsèr ìt ìs wràppèd tò thàt ùsèr's rìstrèttò255 pùblìc kèy ùsìng ÈCÌÈS, sò thè sèrvèr càn wràp à kèy fòr à ùsèr ìt cànnòt ìmpèrsònàtè ànd cànnòt ùnwràp. À nèw càsè ìs wràppèd fòr thè crèàtòr ànd fòr èàch qùèùè mèmbèr whòsè pùblìc kèy ìs òn fìlè, ànd àn èmpty wràp sèt ìs rèfùsèd. Jòìnìng à qùèùè bàckfìlls thè wràps fòr thàt qùèùè's èxìstìng càsès thròùgh à rèsùmàblè swèèp, ànd dèàctìvàtìng thè ònly àccòùnt hòldìng à càsè's wràp ìs rèfùsèd ùnlèss àn àdmìnìstràtòr fòrcès ìt pàst à cònfìrmàtìòn stàtìng hòw màny càsès wòùld bècòmè ùnrèàdàblè. Rèmòvìng à ùsèr fròm à qùèùè dèlètès thè wràps ìssùèd whìlè thèy wèrè à mèmbèr. Òn òpèn, thè bròwsèr wòrkèr còmpùtès thè shàrèd sècrèt fròm thè ùsèr's prìvàtè scàlàr ànd thè stòrèd èphèmèràl pòìnt, ùnwràps thè càsè kèy, ànd dècrypts, wìth nò sèrvèr ròùnd trìp ìn thè dècryptìòn stèp. [[#èncryptìòn #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè òrgànìzàtìòn tìèr ànd thè pùblìc tìèr. •••••••••••••** Shàrèd màtèrìàl ùsès ònè òrgànìzàtìòn kèypàìr. Thè prìvàtè hàlf ìs wràppèd pèr ùsèr ùndèr à kèy dèrìvèd fròm thàt ùsèr's màstèr kèy, sò èvèry sìgnèd-ìn ùsèr càn òpèn lìbràry àrtìclès ànd qùèùè nàmès whìlè thè sèrvèr, hòldìng ònly thè pùblìc hàlf, càn sèàl nèw vàlùès wìthòùt rèàdìng àny. Ùsèr dìsplày nàmès ànd lògìn ìdèntìfìèrs àrè stòrèd às sèàlèd bòxès ùndèr thè sàmè òrgànìzàtìòn pùblìc kèy, whìch ìs why àn àdmìnìstràtòr's bròwsèr càn lìst ùsèrs by nàmè ànd thè sèrvèr cànnòt. Ìntàkè bràndìng ìs thè èxcèptìòn, bècàùsè ìts kèy dèrìvès fròm thè òrgànìzàtìòn pùblìc kèy by hàsh ànd ìs thèrèfòrè rèàdàblè by ànyònè, whìch ìs thè ìntènt fòr à pàgè à clìènt mùst rècògnìzè bèfòrè trùstìng ìt. [Thè òrgànìzàtìòn kèy lìfècyclè](#dèèp-dìvè/òrgànìzàtìòn-kèy-lìfècyclè) còvèrs crèàtìòn, ròtàtìòn, ànd whàt hàppèns whèn nò àccòùnt hòlds à còpy. [[#èncryptìòn #kèys #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè pàsswòrd nòt ùnlòck? •••••••••••** Dèàctìvàtìng à ùsèr dèlètès thèìr pèr-càsè wràppèd kèys, sò thè ùsèr's dèrìvèd prìvàtè kèy hàs nòthìng lèft tò ùnwràp èvèn ìf thèy stìll knòw thèìr pàsswòrd. Chàngìng à pàsswòrd chàngès thè dèrìvèd prìvàtè kèy, whìch ìs why à pàsswòrd chàngè rè-wràps èvèry càsè kèy thè ùsèr càn rèàd. Thàt rè-wràp ìs pròpòrtìònàl tò thè nùmbèr òf càsès thèy hàvè àccèss tò. [Pàsswòrd ànd kèy rè-wràp](#sèttìngs/pàsswòrd) còvèrs thè fùll sèqùèncè. [[#kèys #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Còntrìbùtòr bòùndàrìès. •••••••** Thè prìmìtìvès lìvè ìn \`pàckàgès/cryptò/src\`, splìt by jòb. [[#èncryptìòn #clìènt-dàtà]]
- \`còntènt.ts\` dòès slòt-bòùnd còntènt èncryptìòn. [[#èncryptìòn]]
- \`ècìès.ts\` ànd \`kèywràp.ts\` dò kèy wràppìng. [[#èncryptìòn #kèys]]
- \`dèrìvè.ts\` ànd \`hkdf.ts\` dò dèrìvàtìòn. [[#kèys]]
- \`mèm.ts\` zèròès bùffèrs. [[#èncryptìòn]]
Còlùmn shàpè ìs thè dèsìgn dècìsìòn thàt òùtlìvès thè còdè. Thè \`tìckèts\` tàblè hòlds \`èncryptèd_tìtlè\` ànd \`èncryptèd_dèscrìptìòn\` às bytèà bèsìdè plàìntèxt \`stàtùs\`, \`prìòrìty\`, \`qùèùè_ìd\`, \`àssìgnèd_tò\` ànd \`crèàtèd_àt\`, ànd \`tìckèt_kèy_wràps\` hòlds ònè ròw pèr ùsèr pèr càsè wìth thè èphèmèràl pòìnt, nòncè ànd wràppèd kèy. Àddìng à fìèld tò à càsè mèàns chòòsìng bètwèèn thè èncryptèd pàylòàd ànd thè plàìntèxt mètàdàtà, ànd à fìèld chòsèn às plàìntèxt stàys vìsìblè ìn èvèry fùtùrè dàtàbàsè dùmp. [[#èncryptìòn #clìènt-dàtà #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A client's messages and the notes written about them are encrypted in the browser before they leave the device, and the server holds only the result. The ser..." |
*
* @param {Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_how_encryption_works_body = /** @type {((inputs?: Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_How_Encryption_Works_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_how_encryption_works_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_how_encryption_works_body(inputs)
	return en_demo_narrative_deepdive_how_encryption_works_body(inputs)
});