/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Reply_BodyInputs */

const en_demo_narrative_topic_reply_body = /** @type {(inputs: Demo_Narrative_Topic_Reply_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A reply is encrypted in the browser under the ticket key before it leaves the device, and the server stores the result without holding a key that can open it. How much of the path stays encrypted depends on the channel: a reply to an encrypted portal channel is sealed for the client's own browser, while a text message leaves the encrypted path when it reaches the telephony provider. [[#encryption #telephony]]
**What two copies does a reply produce?** Sending writes the message twice, under different keys. [[#encryption #portal]]
- The organization's copy is encrypted under the ticket's symmetric key and stored as a follow-up on the ticket, readable by every account the ticket key is wrapped for. [[#encryption #client-data]]
- The client's copy is sealed to the public key of their active portal channel and stored beside that channel, readable only in the client's browser. [[#portal #encryption]]
When the client has no encrypted channel open, the second copy is not written and the reply reaches them over the channel they came in on. [How encryption works](#deep-dive/how-encryption-works) covers the key hierarchy behind both copies. [[#encryption #portal]]
**Sending a text.** The browser posts the ticket identifier and the message to a relay endpoint. The server resolves and decrypts the client's phone number itself rather than accepting one from the browser, which keeps the number out of the request. The server hands both to the telephony provider and then zeroes every buffer that touched plaintext in a \`finally\` block: the raw request body, the ticket identifier, the message, and the phone number. [[#telephony #server-holds #encryption]]
- The endpoint logs no request body and returns no content in an error response.
- The message is capped at 1600 characters, and both the browser and the server count the same unit.
- The provider interface accepts strings rather than buffers, so two immutable copies of the number and the message exist for the length of one outbound HTTP call and persist until garbage collection. This residual risk is recorded in the code beside the line that creates it.
- A text is refused when the organization has switched the SMS channel off.
[The telephony relay](#deep-dive/the-telephony-relay) covers what the carrier and the provider see after the message leaves. [[#telephony #server-holds #encryption]]
**What happens when the relay succeeds but the thread write fails?** The relay runs before the follow-up write. A message can reach the client and then fail to be recorded. The composer keeps the encrypted copy it already built and retries the follow-up write without re-posting the relay. [[#failure-states #telephony]]
**What does the server store from a reply?** The follow-up row's content is ciphertext. Its ticket identifier, its source, its type, its private flag, the user who wrote it, the users mentioned in it, and its creation time are plaintext columns. A database dump shows that a particular user sent a text on a particular ticket at a particular time, and shows neither the text nor whom the ticket concerns. The content is sealed with an authenticated stream cipher, so ciphertext length follows message length and separates a one-word reply from a long one. [The trust boundary](#deep-dive/the-trust-boundary) lists the plaintext columns elsewhere in the schema. [[#metadata #server-holds #client-data]]
**Drafts.** Unsent compose text is held in memory and cleared on sign-out and on idle timeout. Closing the tab also discards it. [[#client-data #privacy]]
**What gates each channel?** Each relay endpoint requires its own permission, so an organization can staff text, email, and calls separately. The text relay requires the Send client SMS permission, the email relay requires the Send client email permission, and the call relay requires the Call clients permission. The server checks the permission on every request rather than relying on the compose bar that hides the option. [The permission system](#deep-dive/the-permission-system) covers moving those between roles. [[#permissions #telephony]]
**The send composables and relay handlers.** The compose surfaces are \`ReplySheet.svelte\` and \`TicketCompose.svelte\` under \`packages/client/src/lib/components/tickets/\`. The send paths are \`create-send-message.svelte.ts\`, \`create-sms-send.svelte.ts\`, and the shared \`relay-then-record.ts\` under \`packages/client/src/lib/composables/ticket-detail/\`. The relay handlers are in \`packages/server/src/routes/relay.ts\` with shared body parsing and authentication in \`relay-utils.ts\`. The follow-up row is written through \`packages/server/src/tickets/followup-service.ts\`, and its schema comes from \`packages/server/src/db/migrations/tenant/026_create_followups.ts\` with \`047_add_followup_authoring.ts\`. [[#client-data #server-holds]]`)
};

const es_demo_narrative_topic_reply_body = /** @type {(inputs: Demo_Narrative_Topic_Reply_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Una respuesta se cifra en el navegador con la clave del ticket antes de salir del dispositivo, y el servidor almacena el resultado sin poseer una clave que pueda abrirlo. Cuánto del recorrido permanece cifrado depende del canal: una respuesta a un canal cifrado del portal se sella para el propio navegador del cliente, mientras que un mensaje de texto abandona la ruta cifrada al llegar al proveedor de telefonía. [[#encryption #telephony]]
**¿Qué dos copias produce una respuesta?** El envío escribe el mensaje dos veces, con claves distintas. [[#encryption #portal]]
- La copia de la organización se cifra con la clave simétrica del ticket y se almacena como un seguimiento en el ticket, legible para cada cuenta para la que se ha envuelto la clave del ticket. [[#encryption #client-data]]
- La copia del cliente se sella con la clave pública de su canal activo del portal y se almacena junto a ese canal, legible solo en el navegador del cliente. [[#portal #encryption]]
Cuando el cliente no tiene ningún canal cifrado abierto, la segunda copia no se escribe y la respuesta le llega por el canal por el que entró. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la jerarquía de claves detrás de ambas copias. [[#encryption #portal]]
**Enviar un mensaje de texto.** El navegador envía el identificador del ticket y el mensaje a un endpoint de relevo. El servidor resuelve y descifra por su cuenta el número de teléfono del cliente en lugar de aceptar uno del navegador, lo que mantiene el número fuera de la solicitud. El servidor entrega ambos al proveedor de telefonía y después pone a cero cada búfer que tocó texto plano en un bloque \`finally\`: el cuerpo crudo de la solicitud, el identificador del ticket, el mensaje y el número de teléfono. [[#telephony #server-holds #encryption]]
- El endpoint no registra ningún cuerpo de solicitud y no devuelve contenido en una respuesta de error.
- El mensaje tiene un tope de 1600 caracteres, y tanto el navegador como el servidor cuentan la misma unidad.
- La interfaz del proveedor acepta cadenas en lugar de búferes, por lo que existen dos copias inmutables del número y del mensaje durante una sola llamada HTTP saliente y persisten hasta la recolección de basura. Este riesgo residual está anotado en el código junto a la línea que lo crea.
- Un mensaje de texto se rechaza cuando la organización ha desactivado el canal SMS.
[El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que ven la operadora y el proveedor una vez que el mensaje sale. [[#telephony #server-holds #encryption]]
**¿Qué pasa cuando el relevo funciona pero la escritura en el hilo falla?** El relevo se ejecuta antes de la escritura del seguimiento. Un mensaje puede llegar al cliente y luego fallar al registrarse. El compositor conserva la copia cifrada que ya había construido y reintenta solo la escritura del seguimiento sin reenviar el relevo. [[#failure-states #telephony]]
**¿Qué almacena el servidor de una respuesta?** El contenido de la fila de seguimiento es texto cifrado. El identificador del ticket, su origen, su tipo, su marca de privacidad, la persona que lo escribió, las personas mencionadas en él y su hora de creación son columnas en texto plano. Un volcado de la base de datos muestra que una persona concreta envió un mensaje de texto en un ticket concreto en un momento concreto, y no muestra ni el texto ni a quién concierne el ticket. El contenido se sella con un cifrado de flujo autenticado, por lo que la longitud del texto cifrado sigue a la del mensaje y separa una respuesta de una palabra de una larga. [La frontera de confianza](#deep-dive/the-trust-boundary) enumera las columnas en texto plano del resto del esquema. [[#metadata #server-holds #client-data]]
**Borradores.** El texto sin enviar del compositor se guarda en memoria y se borra al cerrar sesión y cuando se agota el tiempo de inactividad. Cerrar la pestaña también lo descarta. [[#client-data #privacy]]
**¿Qué controla el acceso a cada canal?** Cada endpoint de relevo requiere su propio permiso, de modo que una organización puede asignar personal distinto a texto, correo y llamadas. El relevo de texto requiere el permiso Enviar SMS al cliente, el relevo de correo requiere el permiso Enviar correo al cliente y el relevo de llamadas requiere el permiso Llamar a clientes. El servidor comprueba el permiso en cada solicitud en lugar de depender de la barra de composición que oculta la opción. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se trasladan esos permisos entre roles. [[#permissions #telephony]]
**Los composables de envío y los manejadores de relevo.** Las superficies de composición son \`ReplySheet.svelte\` y \`TicketCompose.svelte\` en \`packages/client/src/lib/components/tickets/\`. Las rutas de envío son \`create-send-message.svelte.ts\`, \`create-sms-send.svelte.ts\` y el compartido \`relay-then-record.ts\` en \`packages/client/src/lib/composables/ticket-detail/\`. Los manejadores de relevo están en \`packages/server/src/routes/relay.ts\` con el análisis del cuerpo y la autenticación compartidos en \`relay-utils.ts\`. La fila de seguimiento se escribe mediante \`packages/server/src/tickets/followup-service.ts\`, y su esquema viene de \`packages/server/src/db/migrations/tenant/026_create_followups.ts\` con \`047_add_followup_authoring.ts\`. [[#client-data #server-holds]]`)
};

const en_xa2_demo_narrative_topic_reply_body = /** @type {(inputs: Demo_Narrative_Topic_Reply_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À rèply ìs èncryptèd ìn thè bròwsèr ùndèr thè tìckèt kèy bèfòrè ìt lèàvès thè dèvìcè, ànd thè sèrvèr stòrès thè rèsùlt wìthòùt hòldìng à kèy thàt càn òpèn ìt. Hòw mùch òf thè pàth stàys èncryptèd dèpènds òn thè chànnèl: à rèply tò àn èncryptèd pòrtàl chànnèl ìs sèàlèd fòr thè clìènt's òwn bròwsèr, whìlè à tèxt mèssàgè lèàvès thè èncryptèd pàth whèn ìt rèàchès thè tèlèphòny pròvìdèr. [[#èncryptìòn #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt twò còpìès dòès à rèply pròdùcè? ••••••••••••** Sèndìng wrìtès thè mèssàgè twìcè, ùndèr dìffèrènt kèys. [[#èncryptìòn #pòrtàl]]
- Thè òrgànìzàtìòn's còpy ìs èncryptèd ùndèr thè tìckèt's symmètrìc kèy ànd stòrèd às à fòllòw-ùp òn thè tìckèt, rèàdàblè by èvèry àccòùnt thè tìckèt kèy ìs wràppèd fòr. [[#èncryptìòn #clìènt-dàtà]]
- Thè clìènt's còpy ìs sèàlèd tò thè pùblìc kèy òf thèìr àctìvè pòrtàl chànnèl ànd stòrèd bèsìdè thàt chànnèl, rèàdàblè ònly ìn thè clìènt's bròwsèr. [[#pòrtàl #èncryptìòn]]
Whèn thè clìènt hàs nò èncryptèd chànnèl òpèn, thè sècònd còpy ìs nòt wrìttèn ànd thè rèply rèàchès thèm òvèr thè chànnèl thèy càmè ìn òn. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè kèy hìèràrchy bèhìnd bòth còpìès. [[#èncryptìòn #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèndìng à tèxt. •••••** Thè bròwsèr pòsts thè tìckèt ìdèntìfìèr ànd thè mèssàgè tò à rèlày èndpòìnt. Thè sèrvèr rèsòlvès ànd dècrypts thè clìènt's phònè nùmbèr ìtsèlf ràthèr thàn àccèptìng ònè fròm thè bròwsèr, whìch kèèps thè nùmbèr òùt òf thè rèqùèst. Thè sèrvèr hànds bòth tò thè tèlèphòny pròvìdèr ànd thèn zèròès èvèry bùffèr thàt tòùchèd plàìntèxt ìn à \`fìnàlly\` blòck: thè ràw rèqùèst bòdy, thè tìckèt ìdèntìfìèr, thè mèssàgè, ànd thè phònè nùmbèr. [[#tèlèphòny #sèrvèr-hòlds #èncryptìòn]]
- Thè èndpòìnt lògs nò rèqùèst bòdy ànd rètùrns nò còntènt ìn àn èrròr rèspònsè.
- Thè mèssàgè ìs càppèd àt 1600 chàràctèrs, ànd bòth thè bròwsèr ànd thè sèrvèr còùnt thè sàmè ùnìt.
- Thè pròvìdèr ìntèrfàcè àccèpts strìngs ràthèr thàn bùffèrs, sò twò ìmmùtàblè còpìès òf thè nùmbèr ànd thè mèssàgè èxìst fòr thè lèngth òf ònè òùtbòùnd HTTP càll ànd pèrsìst ùntìl gàrbàgè còllèctìòn. Thìs rèsìdùàl rìsk ìs rècòrdèd ìn thè còdè bèsìdè thè lìnè thàt crèàtès ìt.
- À tèxt ìs rèfùsèd whèn thè òrgànìzàtìòn hàs swìtchèd thè SMS chànnèl òff.
[Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt thè càrrìèr ànd thè pròvìdèr sèè àftèr thè mèssàgè lèàvès. [[#tèlèphòny #sèrvèr-hòlds #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn thè rèlày sùccèèds bùt thè thrèàd wrìtè fàìls? ••••••••••••••••••••** Thè rèlày rùns bèfòrè thè fòllòw-ùp wrìtè. À mèssàgè càn rèàch thè clìènt ànd thèn fàìl tò bè rècòrdèd. Thè còmpòsèr kèèps thè èncryptèd còpy ìt àlrèàdy bùìlt ànd rètrìès thè fòllòw-ùp wrìtè wìthòùt rè-pòstìng thè rèlày. [[#fàìlùrè-stàtès #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè fròm à rèply? ••••••••••••** Thè fòllòw-ùp ròw's còntènt ìs cìphèrtèxt. Ìts tìckèt ìdèntìfìèr, ìts sòùrcè, ìts typè, ìts prìvàtè flàg, thè ùsèr whò wròtè ìt, thè ùsèrs mèntìònèd ìn ìt, ànd ìts crèàtìòn tìmè àrè plàìntèxt còlùmns. À dàtàbàsè dùmp shòws thàt à pàrtìcùlàr ùsèr sènt à tèxt òn à pàrtìcùlàr tìckèt àt à pàrtìcùlàr tìmè, ànd shòws nèìthèr thè tèxt nòr whòm thè tìckèt còncèrns. Thè còntènt ìs sèàlèd wìth àn àùthèntìcàtèd strèàm cìphèr, sò cìphèrtèxt lèngth fòllòws mèssàgè lèngth ànd sèpàràtès à ònè-wòrd rèply fròm à lòng ònè. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) lìsts thè plàìntèxt còlùmns èlsèwhèrè ìn thè schèmà. [[#mètàdàtà #sèrvèr-hòlds #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dràfts. •••** Ùnsènt còmpòsè tèxt ìs hèld ìn mèmòry ànd clèàrèd òn sìgn-òùt ànd òn ìdlè tìmèòùt. Clòsìng thè tàb àlsò dìscàrds ìt. [[#clìènt-dàtà #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••**Whàt gàtès èàch chànnèl? ••••••••** Èàch rèlày èndpòìnt rèqùìrès ìts òwn pèrmìssìòn, sò àn òrgànìzàtìòn càn stàff tèxt, èmàìl, ànd càlls sèpàràtèly. Thè tèxt rèlày rèqùìrès thè Sènd clìènt SMS pèrmìssìòn, thè èmàìl rèlày rèqùìrès thè Sènd clìènt èmàìl pèrmìssìòn, ànd thè càll rèlày rèqùìrès thè Càll clìènts pèrmìssìòn. Thè sèrvèr chècks thè pèrmìssìòn òn èvèry rèqùèst ràthèr thàn rèlyìng òn thè còmpòsè bàr thàt hìdès thè òptìòn. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs mòvìng thòsè bètwèèn ròlès. [[#pèrmìssìòns #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè sènd còmpòsàblès ànd rèlày hàndlèrs. ••••••••••••** Thè còmpòsè sùrfàcès àrè \`RèplyShèèt.svèltè\` ànd \`TìckètCòmpòsè.svèltè\` ùndèr \`pàckàgès/clìènt/src/lìb/còmpònènts/tìckèts/\`. Thè sènd pàths àrè \`crèàtè-sènd-mèssàgè.svèltè.ts\`, \`crèàtè-sms-sènd.svèltè.ts\`, ànd thè shàrèd \`rèlày-thèn-rècòrd.ts\` ùndèr \`pàckàgès/clìènt/src/lìb/còmpòsàblès/tìckèt-dètàìl/\`. Thè rèlày hàndlèrs àrè ìn \`pàckàgès/sèrvèr/src/ròùtès/rèlày.ts\` wìth shàrèd bòdy pàrsìng ànd àùthèntìcàtìòn ìn \`rèlày-ùtìls.ts\`. Thè fòllòw-ùp ròw ìs wrìttèn thròùgh \`pàckàgès/sèrvèr/src/tìckèts/fòllòwùp-sèrvìcè.ts\`, ànd ìts schèmà còmès fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/026_crèàtè_fòllòwùps.ts\` wìth \`047_àdd_fòllòwùp_àùthòrìng.ts\`. [[#clìènt-dàtà #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A reply is encrypted in the browser under the ticket key before it leaves the device, and the server stores the result without holding a key that can open it..." |
*
* @param {Demo_Narrative_Topic_Reply_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_reply_body = /** @type {((inputs?: Demo_Narrative_Topic_Reply_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Reply_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_reply_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_reply_body(inputs)
	return en_demo_narrative_topic_reply_body(inputs)
});