/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Share_View_BodyInputs */

const en_demo_narrative_client_share_view_body = /** @type {(inputs: Demo_Narrative_Client_Share_View_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A share link delivers one encrypted message to a reader who has no account, no sign-in and nothing installed. The server hands over the scrambled message without being able to read it, and the reader's own device performs the decryption. [[#portal #encryption]]
**What does the server see of the address?** The share's identifier travels in the URL path. The key that decrypts the content sits after the \`#\` fragment mark, which browsers never include in a request. The page replaces the address bar entry with the path alone as soon as it loads, before fetching and decrypting, so the key is absent from the browser's history and from any address the reader copies or forwards even when opening fails. [How encryption works](#deep-dive/how-encryption-works) covers the sealing. [[#keys #server-holds]]
**Why does the key open only this message?** Each link gets its own key, generated fresh for that share alone. The key is unrelated to any credential the reader may hold for a portal or an account, and opening the link ties the request to no other conversation. [[#encryption #privacy]]
**What does a broken link report?** A link that arrives truncated or missing its fragment tells the reader to check that the complete link was opened. Text messages are the delivery channel for these links, and a message split across segments is the likeliest cause. [Single use access](#client-share/one-time) covers the remaining end states. [[#failure-states #telephony]]
**What survives after decryption?** The decrypted message sits in the page and cannot be wiped the way the key can. Quick exit leaves the page. A screenshot, a copy, or a printout remains wherever the reader placed it. [On the device](#deep-dive/on-the-device) covers what a share link leaves in the browser's history and storage. [Quick exit](#client-portal/quick-exit) covers what that control clears and what it does not. [[#failure-states #privacy]]
**Rate limit.** The server allows ten opens per address per minute, which blocks guessing link identifiers without getting in a reader's way. [[#failure-states]]
**The view page and the sealing pair.** The page is \`packages/client/src/routes/(client)/share/[id]/+page.svelte\`. \`encryptShare\` and \`decryptShare\` in \`packages/client/src/lib/portal/share-crypto.ts\` seal and unseal on the main thread, because no session or worker exists on this page. The share key is bound to the share's identifier in the authenticated data, which prevents replaying the ciphertext under a different identifier. The key is zeroed immediately after use. \`openShare\` in \`packages/server/src/portal/share-service.ts\` performs the server-side consume against the row from \`091_share_links.ts\`. [Share link](#ticket-detail/share-link) covers the sending end. [[#encryption #server-holds]]`)
};

const es_demo_narrative_client_share_view_body = /** @type {(inputs: Demo_Narrative_Client_Share_View_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un enlace compartido entrega un único mensaje cifrado a quien lee, sin necesidad de cuenta, de inicio de sesión ni de instalación. El servidor entrega el mensaje cifrado sin poder leerlo, y el propio dispositivo de quien lee realiza el descifrado. [[#portal #encryption]]
**¿Qué ve el servidor de la dirección?** El identificador del recurso compartido viaja en la ruta de la URL. La clave que descifra el contenido va después de la marca de fragmento \`#\`, que los navegadores nunca incluyen en una solicitud. La página reemplaza la entrada de la barra de direcciones con la ruta sola en cuanto carga, antes de solicitar y descifrar, de modo que la clave no queda en el historial del navegador ni en ninguna dirección que quien lee copie o reenvíe aunque la apertura falle. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata el sellado. [[#keys #server-holds]]
**¿Por qué solo abre este mensaje?** Cada enlace recibe su propia clave, generada exclusivamente para ese recurso compartido. La clave no guarda vínculo con ninguna credencial que quien lee pueda tener en el portal o en una cuenta, y abrir el enlace no vincula la solicitud con ninguna otra conversación. [[#encryption #privacy]]
**¿Qué informa un enlace dañado?** Un enlace que llega cortado o sin su fragmento indica a quien lee que compruebe que se abrió el enlace completo. Los mensajes de texto son el canal de entrega de estos enlaces, y un mensaje partido entre segmentos es la causa más probable. [Acceso de un solo uso](#client-share/one-time) trata los estados finales restantes. [[#failure-states #telephony]]
**¿Qué sobrevive tras el descifrado?** El mensaje descifrado permanece en la página y no se puede borrar como sí se borra la clave. La salida rápida abandona la página. Una captura, una copia impresa o un archivo guardado permanece donde quien lee lo dejó. [En el dispositivo](#deep-dive/on-the-device) trata lo que un enlace compartido deja en el historial y almacenamiento del navegador. [Salida rápida](#client-portal/quick-exit) trata lo que ese control borra y lo que no. [[#failure-states #privacy]]
**Límite de frecuencia.** El servidor permite diez aperturas por dirección por minuto, lo que bloquea el sondeo de identificadores de enlaces sin estorbar a quien lee. [[#failure-states]]
**La página de lectura y el par de sellado.** La página es \`packages/client/src/routes/(client)/share/[id]/+page.svelte\`. \`encryptShare\` y \`decryptShare\`, en \`packages/client/src/lib/portal/share-crypto.ts\`, sellan y abren en el hilo principal porque no existe sesión ni worker en esta página. La clave del recurso está ligada a su identificador en los datos autenticados, lo que impide reutilizar el texto cifrado bajo un identificador distinto. La clave se pone a cero inmediatamente tras su uso. \`openShare\`, en \`packages/server/src/portal/share-service.ts\`, ejecuta el consumo en el servidor contra la fila de \`091_share_links.ts\`. [Enlace compartido](#ticket-detail/share-link) trata el extremo de envío. [[#encryption #server-holds]]`)
};

const en_xa2_demo_narrative_client_share_view_body = /** @type {(inputs: Demo_Narrative_Client_Share_View_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À shàrè lìnk dèlìvèrs ònè èncryptèd mèssàgè tò à rèàdèr whò hàs nò àccòùnt, nò sìgn-ìn ànd nòthìng ìnstàllèd. Thè sèrvèr hànds òvèr thè scràmblèd mèssàgè wìthòùt bèìng àblè tò rèàd ìt, ànd thè rèàdèr's òwn dèvìcè pèrfòrms thè dècryptìòn. [[#pòrtàl #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr sèè òf thè àddrèss? ••••••••••••** Thè shàrè's ìdèntìfìèr tràvèls ìn thè ÙRL pàth. Thè kèy thàt dècrypts thè còntènt sìts àftèr thè \`#\` fràgmènt màrk, whìch bròwsèrs nèvèr ìnclùdè ìn à rèqùèst. Thè pàgè rèplàcès thè àddrèss bàr èntry wìth thè pàth àlònè às sòòn às ìt lòàds, bèfòrè fètchìng ànd dècryptìng, sò thè kèy ìs àbsènt fròm thè bròwsèr's hìstòry ànd fròm àny àddrèss thè rèàdèr còpìès òr fòrwàrds èvèn whèn òpènìng fàìls. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè sèàlìng. [[#kèys #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why dòès thè kèy òpèn ònly thìs mèssàgè? ••••••••••••** Èàch lìnk gèts ìts òwn kèy, gènèràtèd frèsh fòr thàt shàrè àlònè. Thè kèy ìs ùnrèlàtèd tò àny crèdèntìàl thè rèàdèr mày hòld fòr à pòrtàl òr àn àccòùnt, ànd òpènìng thè lìnk tìès thè rèqùèst tò nò òthèr cònvèrsàtìòn. [[#èncryptìòn #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à bròkèn lìnk rèpòrt? ••••••••••** À lìnk thàt àrrìvès trùncàtèd òr mìssìng ìts fràgmènt tèlls thè rèàdèr tò chèck thàt thè còmplètè lìnk wàs òpènèd. Tèxt mèssàgès àrè thè dèlìvèry chànnèl fòr thèsè lìnks, ànd à mèssàgè splìt àcròss sègmènts ìs thè lìkèlìèst càùsè. [Sìnglè ùsè àccèss](#clìènt-shàrè/ònè-tìmè) còvèrs thè rèmàìnìng ènd stàtès. [[#fàìlùrè-stàtès #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt sùrvìvès àftèr dècryptìòn? ••••••••••** Thè dècryptèd mèssàgè sìts ìn thè pàgè ànd cànnòt bè wìpèd thè wày thè kèy càn. Qùìck èxìt lèàvès thè pàgè. À scrèènshòt, à còpy, òr à prìntòùt rèmàìns whèrèvèr thè rèàdèr plàcèd ìt. [Òn thè dèvìcè](#dèèp-dìvè/òn-thè-dèvìcè) còvèrs whàt à shàrè lìnk lèàvès ìn thè bròwsèr's hìstòry ànd stòràgè. [Qùìck èxìt](#clìènt-pòrtàl/qùìck-èxìt) còvèrs whàt thàt còntròl clèàrs ànd whàt ìt dòès nòt. [[#fàìlùrè-stàtès #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ràtè lìmìt. ••••** Thè sèrvèr àllòws tèn òpèns pèr àddrèss pèr mìnùtè, whìch blòcks gùèssìng lìnk ìdèntìfìèrs wìthòùt gèttìng ìn à rèàdèr's wày. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••**Thè vìèw pàgè ànd thè sèàlìng pàìr. •••••••••••** Thè pàgè ìs \`pàckàgès/clìènt/src/ròùtès/(clìènt)/shàrè/[ìd]/+pàgè.svèltè\`. \`èncryptShàrè\` ànd \`dècryptShàrè\` ìn \`pàckàgès/clìènt/src/lìb/pòrtàl/shàrè-cryptò.ts\` sèàl ànd ùnsèàl òn thè màìn thrèàd, bècàùsè nò sèssìòn òr wòrkèr èxìsts òn thìs pàgè. Thè shàrè kèy ìs bòùnd tò thè shàrè's ìdèntìfìèr ìn thè àùthèntìcàtèd dàtà, whìch prèvènts rèplàyìng thè cìphèrtèxt ùndèr à dìffèrènt ìdèntìfìèr. Thè kèy ìs zèròèd ìmmèdìàtèly àftèr ùsè. \`òpènShàrè\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/shàrè-sèrvìcè.ts\` pèrfòrms thè sèrvèr-sìdè cònsùmè àgàìnst thè ròw fròm \`091_shàrè_lìnks.ts\`. [Shàrè lìnk](#tìckèt-dètàìl/shàrè-lìnk) còvèrs thè sèndìng ènd. [[#èncryptìòn #sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A share link delivers one encrypted message to a reader who has no account, no sign-in and nothing installed. The server hands over the scrambled message wit..." |
*
* @param {Demo_Narrative_Client_Share_View_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_share_view_body = /** @type {((inputs?: Demo_Narrative_Client_Share_View_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Share_View_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_share_view_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_share_view_body(inputs)
	return en_demo_narrative_client_share_view_body(inputs)
});