/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Language_BodyInputs */

const en_demo_narrative_topic_language_body = /** @type {(inputs: Demo_Narrative_Topic_Language_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The interface language can be changed before signing in and at any time afterward, and the change takes effect without a request to the server, because English and Spanish are both compiled into the app. With no choice recorded, the app follows the language the browser asks for and uses English when the browser asks for neither. [[#privacy #client-data]]
**What the server holds of a language choice.** The stored preference sits in a sealed box on the account row that only the organization key opens, so a database dump shows that an account recorded a language and not which one. The server seals that box itself while the account is being created, which is the one moment the choice passes through it in the clear; a later change is sealed in the browser and reaches the server as ciphertext it writes without reading. It holds no key that reopens either one. [How encryption works](#deep-dive/how-encryption-works) covers the organization key. [[#server-holds #encryption]]
**When the stored choice is applied.** The sealed preference comes back with the sign-in response and is opened in the browser once key derivation has finished, so the stored language takes effect at the end of a sign-in rather than at the start. Switching language from inside the app changes the session on its own, and the stored copy changes only when it is written from settings or when the offer that follows a switch is taken. [[#encryption #keys]]
**The offer that follows a switch.** Switching language asks once in a session whether to keep that language as the stored preference, in the language being switched to, and it is not asked again in that session whether it was taken or turned down. It is skipped when the stored preference already matches. Turning it down records nothing, which leaves the switch as a change to the session alone. [[#privacy #client-data]]
**The locale strategy, the stored column and adding a language.** Resolution order is configured in \`packages/client/vite.config.ts\` as cookie, then the browser's preferred language, then the base locale. The stored copy is \`users.encrypted_preferred_locale\` from \`packages/server/src/db/migrations/tenant/075_add_encrypted_preferred_locale.ts\`, sealed in \`packages/server/src/auth/service.ts\` and \`packages/server/src/onboarding/onboarding-service.ts\` on the creation paths and in \`packages/client/src/lib/settings/preferred-locale.ts\` for every change after them, and opened in \`packages/client/src/routes/(auth)/login/+page.svelte\`. Adding or updating an interface language is catalog work rather than code. The strings live in \`packages/shared/messages/en.json\` and \`es.json\`, and a new language code goes in the \`locales\` list of both \`packages/client/project.inlang/settings.json\` and \`packages/shared/project.inlang/settings.json\`, which are two projects pointed at that one pair of catalogs. Paraglide compiles per package, so both have to be compiled or one side keeps serving the old set. Content an organization writes for itself follows a separate path, since the locales available for intake form text come from \`FORM_LOCALES\` in \`packages/shared/src/schemas/intake-forms.ts\` rather than from the interface list. [[#client-data #server-holds]]`)
};

const es_demo_narrative_topic_language_body = /** @type {(inputs: Demo_Narrative_Topic_Language_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El idioma de la interfaz se puede cambiar antes de iniciar sesión y en cualquier momento después, y el cambio surte efecto sin ninguna solicitud al servidor, porque el inglés y el español van compilados dentro de la aplicación. Sin una elección registrada, la aplicación sigue el idioma que pide el navegador y usa el inglés cuando el navegador no pide ninguno de los dos. [[#privacy #client-data]]
**Lo que el servidor guarda de una elección de idioma.** La preferencia almacenada vive en una caja sellada en la fila de la cuenta que solo abre la clave de la organización, así que un volcado de la base de datos muestra que una cuenta registró un idioma y no cuál. El servidor sella esa caja mientras se crea la cuenta, que es el único momento en que la elección pasa por él en claro; un cambio posterior se sella en el navegador y le llega como texto cifrado que escribe sin leer. No conserva ninguna clave que reabra ninguna de las dos. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la clave de la organización. [[#server-holds #encryption]]
**Cuándo se aplica la elección almacenada.** La preferencia sellada vuelve con la respuesta del inicio de sesión y se abre en el navegador una vez terminada la derivación de claves, de modo que el idioma almacenado surte efecto al final del inicio de sesión y no al principio. Cambiar de idioma desde dentro de la aplicación afecta por sí solo a la sesión, y la copia almacenada cambia únicamente cuando se escribe desde los ajustes o cuando se acepta el ofrecimiento que sigue a un cambio. [[#encryption #keys]]
**El ofrecimiento que sigue a un cambio.** Cambiar de idioma pregunta una vez por sesión si conservar ese idioma como preferencia almacenada, en el idioma al que se está cambiando, y no vuelve a preguntarlo en esa sesión tanto si se acepta como si se rechaza. Se omite cuando la preferencia almacenada ya coincide. Rechazarlo no registra nada, lo que deja el cambio como un cambio solo de la sesión. [[#privacy #client-data]]
**La estrategia de idioma, la columna almacenada y cómo añadir un idioma.** El orden de resolución se configura en \`packages/client/vite.config.ts\` como cookie, luego el idioma preferido del navegador y luego el idioma base. La copia almacenada es \`users.encrypted_preferred_locale\`, de \`packages/server/src/db/migrations/tenant/075_add_encrypted_preferred_locale.ts\`, sellada en \`packages/server/src/auth/service.ts\` y \`packages/server/src/onboarding/onboarding-service.ts\` en las rutas de creación y en \`packages/client/src/lib/settings/preferred-locale.ts\` para cada cambio posterior, y abierta en \`packages/client/src/routes/(auth)/login/+page.svelte\`. Añadir o actualizar un idioma de la interfaz es trabajo de catálogo más que de código. Las cadenas viven en \`packages/shared/messages/en.json\` y \`es.json\`, y el código de un idioma nuevo va en la lista \`locales\` tanto de \`packages/client/project.inlang/settings.json\` como de \`packages/shared/project.inlang/settings.json\`, dos proyectos que apuntan a ese mismo par de catálogos. Paraglide compila por paquete, así que hay que compilar los dos o uno de los lados seguirá sirviendo el conjunto anterior. El contenido que cada organización redacta para sí misma sigue una ruta aparte, ya que los idiomas disponibles para el texto de los formularios de admisión salen de \`FORM_LOCALES\`, en \`packages/shared/src/schemas/intake-forms.ts\`, y no de la lista de la interfaz. [[#client-data #server-holds]]`)
};

const en_xa2_demo_narrative_topic_language_body = /** @type {(inputs: Demo_Narrative_Topic_Language_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ìntèrfàcè làngùàgè ìs chàngèàblè bèfòrè sìgn ìn ànd àt àny tìmè àftèr, ànd thè chàngè ìs ìmmèdìàtè bècàùsè bòth làngùàgès shìp ìnsìdè thè àpp wìth nòthìng fètchèd fròm thè sèrvèr àt swìtch tìmè. Wìth nò chòìcè màdè, thè àpp fòllòws thè bròwsèr's rèqùèstèd làngùàgè ànd fàlls bàck tò Ènglìsh whèn thè bròwsèr àsks fòr nèìthèr.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Prìvàcy. •••** Thè stòrèd làngùàgè prèfèrèncè ìs cìphèrtèxt thè sèrvèr cànnòt rèàd, sò ìt rèvèàls nòthìng àbòùt whò ìs sìgnìng ìn. Ìt ìs sènt ìn plàìntèxt èxàctly òncè, àt àccòùnt crèàtìòn, bècàùsè thè sèrvèr pèrfòrms thè ìnìtìàl sèàlìng àt thàt pòìnt, ànd thè sèàlèd còpy ìs rèàpplìèd àt èàch sìgn ìn àftèrwàrd. ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The interface language can be changed before signing in and at any time afterward, and the change takes effect without a request to the server, because Engli..." |
*
* @param {Demo_Narrative_Topic_Language_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_language_body = /** @type {((inputs?: Demo_Narrative_Topic_Language_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Language_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_language_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_language_body(inputs)
	return en_demo_narrative_topic_language_body(inputs)
});