/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Fund_Ledger_BodyInputs */

const en_demo_narrative_admin_fund_ledger_body = /** @type {(inputs: Demo_Narrative_Admin_Fund_Ledger_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The fund ledger page lists every fund the organization has created, active and deactivated, with a balance card for each and the full entry history below. Viewing requires the Audit funds permission, which includes View funds. The admin hub's Analytics group links to it. [[#permissions]]
**What does each balance card show?** The card displays the fund's running balance after decryption. The case panel and the dashboard queue cards read the same sealed figure. Two lines below the balance break the history into adjusted and disbursed totals, both computed in the browser from the decrypted entries. [[#encryption #client-data]]
**Deactivated funds.** A deactivated fund and its history stay on this page. The card is marked inactive. [Fund administration](#admin-org/funds) covers deactivation. [[#failure-states]]
**What does each entry hold?** An entry holds an amount, an entry type (disbursement, adjustment, or correction), the exact recording timestamp, and the name of the person who recorded it. The encrypted payload carries every one of these fields. [[#encryption #server-holds]]
**What does the server store per entry?** One ciphertext column, one calendar date at day granularity, a client-minted row id, and the organization key generation. The ciphertext holds the fund reference, the amount, the entry type, the full timestamp, and the recorder. None of those appear in any plaintext column. [[#server-holds #metadata]]
**The ledger and the case.** A ledger entry names no case. The only link between a disbursement and its case is inside the case note's encrypted content. [Recording a disbursement](#ticket-detail/disbursement) covers the case note and how corrections produce reversal-and-replacement pairs in this ledger. [[#privacy #encryption]]
**Currency.** A fund's currency is locked once it has entries in the ledger. Amounts follow the currency's own decimal convention. [[#client-data]]
**What happens when entries cannot be read?** The balance card warns that the displayed figures may be incomplete and withholds the recompute action. [[#failure-states #encryption]]
**Recomputing the balance.** When the decrypted ledger entries add up to a different figure than the stored balance, a holder of Manage funds can overwrite it. The browser totals every entry, seals the new figure with the organization key, and submits it with a version guard that rejects the write if another session changed the balance first. The sealed balance exists only to spare other surfaces from reading the full ledger. [[#encryption #keys]]
**The ledger query.** \`funds.listLedger\` fetches every row. The browser decrypts each payload through the organization key cache that the rest of the fund surfaces share. \`computeLedgerTotals\` and \`computeLedgerTotalsByFund\` in \`packages/client/src/lib/funds/balances.ts\` produce the per-fund and per-type breakdowns. \`FundBalanceCard.svelte\` and \`FundHistoryList.svelte\` in \`packages/client/src/lib/components/funds/\` present the results. [What the server holds about money](#deep-dive/fund-records) covers the storage model. [[#client-data]]`)
};

const es_demo_narrative_admin_fund_ledger_body = /** @type {(inputs: Demo_Narrative_Admin_Fund_Ledger_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La página del libro de fondos enumera todos los fondos que la organización ha creado, activos y desactivados, con una tarjeta de saldo para cada uno y el historial completo de entradas debajo. Para verla se requiere el permiso Auditar fondos, que incluye Ver fondos. El grupo Analíticas del panel de administración enlaza a esta página. [[#permissions]]
**¿Qué muestra cada tarjeta de saldo?** La tarjeta muestra el saldo del fondo tras descifrarlo. El panel del caso y las tarjetas de cola del panel principal leen la misma cifra sellada. Dos líneas debajo del saldo desglosan el historial en totales ajustados y desembolsados, ambos calculados en el navegador a partir de las entradas descifradas. [[#encryption #client-data]]
**Fondos desactivados.** Un fondo desactivado y su historial permanecen en esta página. La tarjeta aparece marcada como inactiva. [Administración de fondos](#admin-org/funds) trata la desactivación. [[#failure-states]]
**¿Qué contiene cada entrada?** Una entrada contiene un monto, un tipo (desembolso, ajuste o corrección), la marca de tiempo exacta del registro y el nombre de quien la registró. El contenido cifrado lleva todos estos campos. [[#encryption #server-holds]]
**¿Qué almacena el servidor por entrada?** Una columna de texto cifrado, una fecha calendario con granularidad diaria, un identificador de fila generado por el cliente y la generación de clave de la organización. Dentro del texto cifrado están la referencia al fondo, el monto, el tipo, la marca de tiempo completa y el registrador. Ninguno de esos datos aparece en columnas de texto plano. [[#server-holds #metadata]]
**El libro y el caso.** Una entrada del libro no nombra ningún caso. El único vínculo entre un desembolso y su caso está dentro del contenido cifrado de la nota del caso. [Registrar un desembolso](#ticket-detail/disbursement) trata la nota del caso y cómo las correcciones producen pares de reversión y reemplazo en este libro. [[#privacy #encryption]]
**Moneda.** La moneda de un fondo queda bloqueada una vez que el fondo tiene entradas en el libro. Los montos respetan la convención decimal de cada moneda. [[#client-data]]
**¿Qué ocurre cuando las entradas no se pueden leer?** La tarjeta de saldo advierte que las cifras mostradas pueden estar incompletas y retiene la acción de recalcular. [[#failure-states #encryption]]
**Recalcular el saldo.** Cuando la suma de las entradas descifradas difiere del saldo almacenado, un titular de Gestionar fondos puede sobrescribirlo. El navegador totaliza cada entrada, sella la nueva cifra con la clave de la organización y la envía con un control de versión que rechaza la escritura si otra sesión modificó el saldo primero. El saldo sellado existe solo para evitar que otras superficies lean el libro completo. [[#encryption #keys]]
**La consulta del libro.** \`funds.listLedger\` obtiene todas las filas. El navegador descifra cada contenido a través del caché de clave de organización que comparten las demás superficies de fondos. \`computeLedgerTotals\` y \`computeLedgerTotalsByFund\` en \`packages/client/src/lib/funds/balances.ts\` producen los desgloses por fondo y por tipo. \`FundBalanceCard.svelte\` y \`FundHistoryList.svelte\` en \`packages/client/src/lib/components/funds/\` presentan los resultados. [Lo que el servidor almacena sobre dinero](#deep-dive/fund-records) trata el modelo de almacenamiento. [[#client-data]]`)
};

const en_xa2_demo_narrative_admin_fund_ledger_body = /** @type {(inputs: Demo_Narrative_Admin_Fund_Ledger_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè fùnd lèdgèr pàgè lìsts èvèry fùnd thè òrgànìzàtìòn hàs crèàtèd, àctìvè ànd dèàctìvàtèd, wìth à bàlàncè càrd fòr èàch ànd thè fùll èntry hìstòry bèlòw. Vìèwìng rèqùìrès thè Àùdìt fùnds pèrmìssìòn, whìch ìnclùdès Vìèw fùnds. Thè àdmìn hùb's Ànàlytìcs gròùp lìnks tò ìt. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès èàch bàlàncè càrd shòw? ••••••••••** Thè càrd dìsplàys thè fùnd's rùnnìng bàlàncè àftèr dècryptìòn. Thè càsè pànèl ànd thè dàshbòàrd qùèùè càrds rèàd thè sàmè sèàlèd fìgùrè. Twò lìnès bèlòw thè bàlàncè brèàk thè hìstòry ìntò àdjùstèd ànd dìsbùrsèd tòtàls, bòth còmpùtèd ìn thè bròwsèr fròm thè dècryptèd èntrìès. [[#èncryptìòn #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dèàctìvàtèd fùnds. ••••••** À dèàctìvàtèd fùnd ànd ìts hìstòry stày òn thìs pàgè. Thè càrd ìs màrkèd ìnàctìvè. [Fùnd àdmìnìstràtìòn](#àdmìn-òrg/fùnds) còvèrs dèàctìvàtìòn. [[#fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès èàch èntry hòld? ••••••••** Àn èntry hòlds àn àmòùnt, àn èntry typè (dìsbùrsèmènt, àdjùstmènt, òr còrrèctìòn), thè èxàct rècòrdìng tìmèstàmp, ànd thè nàmè òf thè pèrsòn whò rècòrdèd ìt. Thè èncryptèd pàylòàd càrrìès èvèry ònè òf thèsè fìèlds. [[#èncryptìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè pèr èntry? ••••••••••••** Ònè cìphèrtèxt còlùmn, ònè càlèndàr dàtè àt dày grànùlàrìty, à clìènt-mìntèd ròw ìd, ànd thè òrgànìzàtìòn kèy gènèràtìòn. Thè cìphèrtèxt hòlds thè fùnd rèfèrèncè, thè àmòùnt, thè èntry typè, thè fùll tìmèstàmp, ànd thè rècòrdèr. Nònè òf thòsè àppèàr ìn àny plàìntèxt còlùmn. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè lèdgèr ànd thè càsè. ••••••••** À lèdgèr èntry nàmès nò càsè. Thè ònly lìnk bètwèèn à dìsbùrsèmènt ànd ìts càsè ìs ìnsìdè thè càsè nòtè's èncryptèd còntènt. [Rècòrdìng à dìsbùrsèmènt](#tìckèt-dètàìl/dìsbùrsèmènt) còvèrs thè càsè nòtè ànd hòw còrrèctìòns pròdùcè rèvèrsàl-ànd-rèplàcèmènt pàìrs ìn thìs lèdgèr. [[#prìvàcy #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Cùrrèncy. •••** À fùnd's cùrrèncy ìs lòckèd òncè ìt hàs èntrìès ìn thè lèdgèr. Àmòùnts fòllòw thè cùrrèncy's òwn dècìmàl cònvèntìòn. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn èntrìès cànnòt bè rèàd? •••••••••••••** Thè bàlàncè càrd wàrns thàt thè dìsplàyèd fìgùrès mày bè ìncòmplètè ànd wìthhòlds thè rècòmpùtè àctìòn. [[#fàìlùrè-stàtès #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••**Rècòmpùtìng thè bàlàncè. ••••••••** Whèn thè dècryptèd lèdgèr èntrìès àdd ùp tò à dìffèrènt fìgùrè thàn thè stòrèd bàlàncè, à hòldèr òf Mànàgè fùnds càn òvèrwrìtè ìt. Thè bròwsèr tòtàls èvèry èntry, sèàls thè nèw fìgùrè wìth thè òrgànìzàtìòn kèy, ànd sùbmìts ìt wìth à vèrsìòn gùàrd thàt rèjècts thè wrìtè ìf ànòthèr sèssìòn chàngèd thè bàlàncè fìrst. Thè sèàlèd bàlàncè èxìsts ònly tò spàrè òthèr sùrfàcès fròm rèàdìng thè fùll lèdgèr. [[#èncryptìòn #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè lèdgèr qùèry. ••••••** \`fùnds.lìstLèdgèr\` fètchès èvèry ròw. Thè bròwsèr dècrypts èàch pàylòàd thròùgh thè òrgànìzàtìòn kèy càchè thàt thè rèst òf thè fùnd sùrfàcès shàrè. \`còmpùtèLèdgèrTòtàls\` ànd \`còmpùtèLèdgèrTòtàlsByFùnd\` ìn \`pàckàgès/clìènt/src/lìb/fùnds/bàlàncès.ts\` pròdùcè thè pèr-fùnd ànd pèr-typè brèàkdòwns. \`FùndBàlàncèCàrd.svèltè\` ànd \`FùndHìstòryLìst.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/fùnds/\` prèsènt thè rèsùlts. [Whàt thè sèrvèr hòlds àbòùt mònèy](#dèèp-dìvè/fùnd-rècòrds) còvèrs thè stòràgè mòdèl. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The fund ledger page lists every fund the organization has created, active and deactivated, with a balance card for each and the full entry history below. Vi..." |
*
* @param {Demo_Narrative_Admin_Fund_Ledger_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_fund_ledger_body = /** @type {((inputs?: Demo_Narrative_Admin_Fund_Ledger_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Fund_Ledger_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_fund_ledger_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_fund_ledger_body(inputs)
	return en_demo_narrative_admin_fund_ledger_body(inputs)
});