/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Unread_Badges_BodyInputs */

const en_demo_narrative_topic_unread_badges_body = /** @type {(inputs: Demo_Narrative_Topic_Unread_Badges_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Each ticket row shows how many replies the signed-in account has not read. [[#client-data #encryption]]
**Where does the count come from?** Each account keeps one encrypted read cursor per ticket, recording the last position read. The server returns that ciphertext with recent reply times for the current page. Reply times exclude system events and the account's own replies. The browser decrypts the cursor and counts the times after it. The server sends at most twenty reply times per ticket, so a ticket with more unread replies than that shows twenty. [Filters](#tickets/filters) covers the unread rule and the sweep beyond the loaded page. [[#client-data #encryption #privacy #server-holds]]
**What does the cursor row reveal?** The row is created the first time an account opens a ticket, filled with 85 random bytes. That size matches a real encrypted cursor: 24 bytes of nonce, roughly 45 bytes of payload, and a 16-byte authentication tag. A row of random bytes is indistinguishable from one holding a real position, by content or by size. The server can tell which tickets an account has opened. It cannot tell which the account has read. Closing a ticket deletes its cursor rows. [The trust boundary](#deep-dive/the-trust-boundary) covers that row beside the others. [[#server-holds #privacy #metadata #trust-boundary]]
**When is the count absent?** The count needs the cursor decrypted, so no count appears while decrypts are in flight, after the idle timer zeroes the keys, or on a ticket whose key the account never received. None of those three means the ticket is read. An absent badge is not a zero. [Ticket decryption](#tickets/decryption) covers the missing-key case. [[#failure-states #keys]]
**The cursor lifecycle and read-state sources.** Both sources (window query for loaded rows and sweep for the rest) are in \`packages/client/src/lib/tickets/create-list-read-state.svelte.ts\`. The cap is \`READ_STATE_TIMESTAMPS_PER_TICKET\` in \`packages/server/src/tickets/ticket-service.ts\`. Random-byte fill and deletion on close are in \`packages/server/src/tickets/read-cursor-service.ts\`. The table is migration \`048_create_ticket_read_cursors.ts\`. [Needs attention](#dashboard/needs-attention) covers the overview bucket reading this state. [[#client-data]]`)
};

const es_demo_narrative_topic_unread_badges_body = /** @type {(inputs: Demo_Narrative_Topic_Unread_Badges_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cada fila de ticket muestra cuántas respuestas no ha leído la cuenta que tiene la sesión abierta. [[#client-data #encryption]]
**¿De dónde sale el conteo?** Cada cuenta mantiene un cursor de lectura cifrado por ticket, que registra la última posición leída. El servidor devuelve ese texto cifrado junto con marcas de tiempo de respuestas recientes de la página actual. Las marcas de tiempo excluyen eventos del sistema y las propias respuestas de la cuenta. El navegador descifra el cursor y cuenta las marcas de tiempo posteriores a él. El servidor envía como máximo veinte marcas de tiempo por ticket, así que un ticket con más respuestas no leídas muestra veinte. [Filtros](#tickets/filters) trata la regla de no leído y el barrido más allá de la página cargada. [[#client-data #encryption #privacy #server-holds]]
**¿Qué revela la fila del cursor?** La fila se crea la primera vez que una cuenta abre un ticket, rellenada con 85 bytes aleatorios. Ese tamaño coincide con un cursor cifrado real: 24 bytes de nonce, aproximadamente 45 bytes de contenido y una etiqueta de autenticación de 16 bytes. Una fila de bytes aleatorios es indistinguible de una con una posición real, tanto por contenido como por tamaño. El servidor puede saber qué tickets ha abierto una cuenta. No puede saber cuáles ha leído. Cerrar un ticket elimina sus filas de cursor. [La frontera de confianza](#deep-dive/the-trust-boundary) trata esa fila junto a las demás. [[#server-holds #privacy #metadata #trust-boundary]]
**¿Cuándo está ausente el conteo?** El conteo necesita que el cursor se descifre, así que no aparece mientras los descifrados están en curso, después de que el temporizador de inactividad ponga las claves a cero, o en un ticket cuya clave la cuenta nunca recibió. Ninguno de esos tres casos significa que el ticket esté leído. Una insignia ausente no es un cero. [Descifrado de tickets](#tickets/decryption) trata el caso de la clave faltante. [[#failure-states #keys]]
**El ciclo de vida del cursor y las fuentes de estado de lectura.** Ambas fuentes (consulta de ventana para las filas cargadas y barrido para el resto) están en \`packages/client/src/lib/tickets/create-list-read-state.svelte.ts\`. El límite es \`READ_STATE_TIMESTAMPS_PER_TICKET\` en \`packages/server/src/tickets/ticket-service.ts\`. El relleno con bytes aleatorios y la eliminación al cerrar están en \`packages/server/src/tickets/read-cursor-service.ts\`. La tabla es la migración \`048_create_ticket_read_cursors.ts\`. [Necesita atención](#dashboard/needs-attention) trata el panel del resumen que lee este estado. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_unread_badges_body = /** @type {(inputs: Demo_Narrative_Topic_Unread_Badges_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èàch tìckèt ròw shòws hòw màny rèplìès thè sìgnèd-ìn àccòùnt hàs nòt rèàd. [[#clìènt-dàtà #èncryptìòn]]
 ••••••••••••••••••••••••••••••••**Whèrè dòès thè còùnt còmè fròm? ••••••••••** Èàch àccòùnt kèèps ònè èncryptèd rèàd cùrsòr pèr tìckèt, rècòrdìng thè làst pòsìtìòn rèàd. Thè sèrvèr rètùrns thàt cìphèrtèxt wìth rècènt rèply tìmès fòr thè cùrrènt pàgè. Rèply tìmès èxclùdè systèm èvènts ànd thè àccòùnt's òwn rèplìès. Thè bròwsèr dècrypts thè cùrsòr ànd còùnts thè tìmès àftèr ìt. Thè sèrvèr sènds àt mòst twènty rèply tìmès pèr tìckèt, sò à tìckèt wìth mòrè ùnrèàd rèplìès thàn thàt shòws twènty. [Fìltèrs](#tìckèts/fìltèrs) còvèrs thè ùnrèàd rùlè ànd thè swèèp bèyònd thè lòàdèd pàgè. [[#clìènt-dàtà #èncryptìòn #prìvàcy #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè cùrsòr ròw rèvèàl? ••••••••••** Thè ròw ìs crèàtèd thè fìrst tìmè àn àccòùnt òpèns à tìckèt, fìllèd wìth 85 ràndòm bytès. Thàt sìzè màtchès à rèàl èncryptèd cùrsòr: 24 bytès òf nòncè, ròùghly 45 bytès òf pàylòàd, ànd à 16-bytè àùthèntìcàtìòn tàg. À ròw òf ràndòm bytès ìs ìndìstìngùìshàblè fròm ònè hòldìng à rèàl pòsìtìòn, by còntènt òr by sìzè. Thè sèrvèr càn tèll whìch tìckèts àn àccòùnt hàs òpènèd. Ìt cànnòt tèll whìch thè àccòùnt hàs rèàd. Clòsìng à tìckèt dèlètès ìts cùrsòr ròws. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thàt ròw bèsìdè thè òthèrs. [[#sèrvèr-hòlds #prìvàcy #mètàdàtà #trùst-bòùndàry]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn ìs thè còùnt àbsènt? ••••••••** Thè còùnt nèèds thè cùrsòr dècryptèd, sò nò còùnt àppèàrs whìlè dècrypts àrè ìn flìght, àftèr thè ìdlè tìmèr zèròès thè kèys, òr òn à tìckèt whòsè kèy thè àccòùnt nèvèr rècèìvèd. Nònè òf thòsè thrèè mèàns thè tìckèt ìs rèàd. Àn àbsènt bàdgè ìs nòt à zèrò. [Tìckèt dècryptìòn](#tìckèts/dècryptìòn) còvèrs thè mìssìng-kèy càsè. [[#fàìlùrè-stàtès #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè cùrsòr lìfècyclè ànd rèàd-stàtè sòùrcès. ••••••••••••••** Bòth sòùrcès (wìndòw qùèry fòr lòàdèd ròws ànd swèèp fòr thè rèst) àrè ìn \`pàckàgès/clìènt/src/lìb/tìckèts/crèàtè-lìst-rèàd-stàtè.svèltè.ts\`. Thè càp ìs \`RÈÀD_STÀTÈ_TÌMÈSTÀMPS_PÈR_TÌCKÈT\` ìn \`pàckàgès/sèrvèr/src/tìckèts/tìckèt-sèrvìcè.ts\`. Ràndòm-bytè fìll ànd dèlètìòn òn clòsè àrè ìn \`pàckàgès/sèrvèr/src/tìckèts/rèàd-cùrsòr-sèrvìcè.ts\`. Thè tàblè ìs mìgràtìòn \`048_crèàtè_tìckèt_rèàd_cùrsòrs.ts\`. [Nèèds àttèntìòn](#dàshbòàrd/nèèds-àttèntìòn) còvèrs thè òvèrvìèw bùckèt rèàdìng thìs stàtè. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Each ticket row shows how many replies the signed-in account has not read. [[#client-data #encryption]] **Where does the count come from?** Each account keep..." |
*
* @param {Demo_Narrative_Topic_Unread_Badges_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_unread_badges_body = /** @type {((inputs?: Demo_Narrative_Topic_Unread_Badges_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Unread_Badges_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_unread_badges_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_unread_badges_body(inputs)
	return en_demo_narrative_topic_unread_badges_body(inputs)
});