/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Protection_BodyInputs */

const en_demo_narrative_client_intake_protection_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Protection_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The browser encrypts the visitor's answers and contact details before anything leaves the device. The server receives ciphertext and holds no key that can open it. [Contact method and follow-up options](#client-intake/contact-method) covers how each contact detail is handled after submission. [[#privacy #encryption]]
**Who can open a fresh submission?** Each submission gets its own encryption key. The browser seals that key to the organization's public key. Until someone opens the case, any active member who has set up their keys can unseal the submission, because the organization key is available to all of them. The server restricts the sealed submission to members of the destination queue who hold the View cases permission. The first user to open the case replaces the organization-wide seal with one copy of the ticket key sealed for each authorized user. From that point, only users holding a copy can read it. [How encryption works](#deep-dive/how-encryption-works) covers the organization key. [[#keys #permissions]]
**Who receives a copy of the ticket key?** Queue members and users holding the View intake responses permission receive a copy, provided they have set up their keys. A user who joins the queue or receives the permission afterward can still gain a copy. When another user who already holds the key opens the response viewer, that user's browser seals the missing copies. [Unreadable response](#admin-responses/key-not-held) covers what happens when no copy exists yet. [[#keys #permissions]]
**What does a database dump reveal?** The stored row holds ciphertext for the visitor's answers, a sealed alias that identifies the new client record without naming anyone, the destination queue, the priority and the write timestamps. A dump confirms that a submission arrived, which queue received it and at what priority. It cannot recover what was written. [The trust boundary](#deep-dive/the-trust-boundary) covers the other plaintext columns across the schema. [[#server-holds #metadata]]
**The sealing and conversion modules.** \`encryptIntake\` in \`packages/client/src/routes/(client)/intake/intake-crypto.ts\` seals the per-submission key to the organization's public key. The server writes that sealed copy to \`intake_key_wraps\`, defined in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. \`packages/server/src/portal/intake-conversion-service.ts\` replaces the sealed copy with per-user wraps in a single transaction and removes the interim row. The backfill path for users added later is \`backfillWraps\` in \`packages/server/src/portal/intake-response-service.ts\`. [[#keys #server-holds]]`)
};

const es_demo_narrative_client_intake_protection_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Protection_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El navegador cifra las respuestas y los datos de contacto del visitante antes de que nada salga del dispositivo. El servidor recibe texto cifrado y no posee ninguna clave que pueda abrirlo. [Método de contacto y opciones de seguimiento](#client-intake/contact-method) trata cómo se gestiona cada dato de contacto tras el envío. [[#privacy #encryption]]
**¿Quién puede abrir un envío nuevo?** Cada envío recibe su propia clave de cifrado. El navegador sella esa clave con la clave pública de la organización. Hasta que alguien abre el caso, cualquier miembro activo que haya configurado sus claves puede abrir el envío, porque la clave de la organización está disponible para todos. El servidor restringe el envío sellado a los miembros de la cola de destino que tengan el permiso Ver casos. La primera persona que abre el caso reemplaza el sello organizativo con una copia de la clave del ticket sellada para cada persona autorizada. A partir de ese momento, solo quienes poseen una copia pueden leerlo. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la clave de la organización. [[#keys #permissions]]
**¿Quién recibe una copia de la clave del ticket?** Los miembros de la cola y quienes tienen el permiso Ver respuestas de ingreso reciben una copia, siempre que hayan configurado sus claves. Una persona que se una a la cola o reciba el permiso después todavía puede obtener una copia. Cuando otra persona que ya posea la clave abra el visor de respuestas, el navegador de esa persona sella las copias que faltan. [Respuesta ilegible](#admin-responses/key-not-held) trata lo que ocurre cuando aún no existe ninguna copia. [[#keys #permissions]]
**¿Qué revela un volcado de base de datos?** La fila almacenada contiene texto cifrado de las respuestas del visitante, un alias sellado que identifica el nuevo registro de cliente sin nombrar a nadie, la cola de destino, la prioridad y las marcas de tiempo de escritura. Un volcado confirma que llegó un envío, qué cola lo recibió y con qué prioridad. No puede recuperar lo que se escribió. [La frontera de confianza](#deep-dive/the-trust-boundary) trata las demás columnas en texto plano del esquema. [[#server-holds #metadata]]
**Los módulos de sellado y conversión.** \`encryptIntake\` en \`packages/client/src/routes/(client)/intake/intake-crypto.ts\` sella la clave del envío con la clave pública de la organización. El servidor escribe esa copia sellada en \`intake_key_wraps\`, definida en \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. \`packages/server/src/portal/intake-conversion-service.ts\` reemplaza la copia sellada con copias selladas por persona en una sola transacción y elimina la fila provisional. La ruta de relleno para personas añadidas después es \`backfillWraps\` en \`packages/server/src/portal/intake-response-service.ts\`. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_client_intake_protection_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Protection_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè bròwsèr èncrypts thè vìsìtòr's ànswèrs ànd còntàct dètàìls bèfòrè ànythìng lèàvès thè dèvìcè. Thè sèrvèr rècèìvès cìphèrtèxt ànd hòlds nò kèy thàt càn òpèn ìt. [Còntàct mèthòd ànd fòllòw-ùp òptìòns](#clìènt-ìntàkè/còntàct-mèthòd) còvèrs hòw èàch còntàct dètàìl ìs hàndlèd àftèr sùbmìssìòn. [[#prìvàcy #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn òpèn à frèsh sùbmìssìòn? ••••••••••** Èàch sùbmìssìòn gèts ìts òwn èncryptìòn kèy. Thè bròwsèr sèàls thàt kèy tò thè òrgànìzàtìòn's pùblìc kèy. Ùntìl sòmèònè òpèns thè càsè, àny àctìvè mèmbèr whò hàs sèt ùp thèìr kèys càn ùnsèàl thè sùbmìssìòn, bècàùsè thè òrgànìzàtìòn kèy ìs àvàìlàblè tò àll òf thèm. Thè sèrvèr rèstrìcts thè sèàlèd sùbmìssìòn tò mèmbèrs òf thè dèstìnàtìòn qùèùè whò hòld thè Vìèw càsès pèrmìssìòn. Thè fìrst ùsèr tò òpèn thè càsè rèplàcès thè òrgànìzàtìòn-wìdè sèàl wìth ònè còpy òf thè tìckèt kèy sèàlèd fòr èàch àùthòrìzèd ùsèr. Fròm thàt pòìnt, ònly ùsèrs hòldìng à còpy càn rèàd ìt. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè òrgànìzàtìòn kèy. [[#kèys #pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò rècèìvès à còpy òf thè tìckèt kèy? ••••••••••••** Qùèùè mèmbèrs ànd ùsèrs hòldìng thè Vìèw ìntàkè rèspònsès pèrmìssìòn rècèìvè à còpy, pròvìdèd thèy hàvè sèt ùp thèìr kèys. À ùsèr whò jòìns thè qùèùè òr rècèìvès thè pèrmìssìòn àftèrwàrd càn stìll gàìn à còpy. Whèn ànòthèr ùsèr whò àlrèàdy hòlds thè kèy òpèns thè rèspònsè vìèwèr, thàt ùsèr's bròwsèr sèàls thè mìssìng còpìès. [Ùnrèàdàblè rèspònsè](#àdmìn-rèspònsès/kèy-nòt-hèld) còvèrs whàt hàppèns whèn nò còpy èxìsts yèt. [[#kèys #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à dàtàbàsè dùmp rèvèàl? ••••••••••** Thè stòrèd ròw hòlds cìphèrtèxt fòr thè vìsìtòr's ànswèrs, à sèàlèd àlìàs thàt ìdèntìfìès thè nèw clìènt rècòrd wìthòùt nàmìng ànyònè, thè dèstìnàtìòn qùèùè, thè prìòrìty ànd thè wrìtè tìmèstàmps. À dùmp cònfìrms thàt à sùbmìssìòn àrrìvèd, whìch qùèùè rècèìvèd ìt ànd àt whàt prìòrìty. Ìt cànnòt rècòvèr whàt wàs wrìttèn. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè òthèr plàìntèxt còlùmns àcròss thè schèmà. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè sèàlìng ànd cònvèrsìòn mòdùlès. •••••••••••** \`èncryptÌntàkè\` ìn \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/ìntàkè-cryptò.ts\` sèàls thè pèr-sùbmìssìòn kèy tò thè òrgànìzàtìòn's pùblìc kèy. Thè sèrvèr wrìtès thàt sèàlèd còpy tò \`ìntàkè_kèy_wràps\`, dèfìnèd ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`. \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-cònvèrsìòn-sèrvìcè.ts\` rèplàcès thè sèàlèd còpy wìth pèr-ùsèr wràps ìn à sìnglè trànsàctìòn ànd rèmòvès thè ìntèrìm ròw. Thè bàckfìll pàth fòr ùsèrs àddèd làtèr ìs \`bàckfìllWràps\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-rèspònsè-sèrvìcè.ts\`. [[#kèys #sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The browser encrypts the visitor's answers and contact details before anything leaves the device. The server receives ciphertext and holds no key that can op..." |
*
* @param {Demo_Narrative_Client_Intake_Protection_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_protection_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Protection_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Protection_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_protection_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_protection_body(inputs)
	return en_demo_narrative_client_intake_protection_body(inputs)
});