/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Data_Retention_BodyInputs */

const en_demo_narrative_deepdive_data_retention_body = /** @type {(inputs: Demo_Narrative_Deepdive_Data_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Data an organization no longer needs can still be taken from it. For a population targeted by a state-level adversary, a case record from three years ago remains a live risk to a person who may have moved, changed names, or gone quiet. Encryption protects what is stored; retention decides whether it is stored at all. The two are different defenses and an organization needs both. [[#retention #privacy]]
The organization's retention policy is off until an administrator turns it on, and turning it on means choosing a window between 1 and 3,650 days. A daily job hard-deletes every closed case whose last activity is older than that window, removing its stored files before its rows and asking the telephony provider to delete its own call and recording logs for the case. A client record, together with its portal channel and account rows, goes only when the last case for that client goes; the client's phone and email rows go only when no other client references them. A client with an open or a recent case is untouched, and an organization that has never set a window is skipped. Enabling the policy and changing the window both ask for confirmation, and the confirmation states that deleted data leaves the live database at once and ages out of the encrypted backups within the backup retention window. With the policy off, everything is kept until someone deletes it by hand. [[#retention]]
The policy is one setting for the whole organization rather than a choice per queue or per case type. A per-queue window would be a decision someone has to get right on the day they create a queue. Configuring the policy requires the Manage retention permission, which sits with Admin by default and can be moved. [The permission system](#deep-dive/the-permission-system) covers how that moves. [[#retention #permissions]]
Retention cannot delete what a third party holds. It cannot delete a copy a client kept on their own phone either. For clients on a monitored device that copy is often the more dangerous one. [[#retention #failure-states]]
**Nightly encrypted backups.** A nightly job takes a full database dump into an encrypted restic repository on a separate host. Snapshots are kept for at least six months under a retention policy of fourteen daily, eight weekly, and six monthly snapshots. A row the retention job deletes remains in the backup repository until its oldest containing snapshot ages out. The restore scripts can bring back any snapshot within that window. The escrow file cannot, because it holds key material and not data rows. [[#retention #server-holds]]
**Separate lifetimes.** Portal message copies, one-time share links, telephony provider logs, and organization erasure each follow their own schedule independent of the organization-wide window. [[#retention #portal #telephony]]
- Portal message copies on the client side are deleted after 30 days of channel inactivity, measured from the later of the last-seen and created timestamps. That sweep removes portal messages, portal attachments and portal recordings while leaving the organization's own record intact. [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers the channel model. [[#retention #portal]]
- One-time share links expire 72 hours after creation or on first read, whichever comes first. The ciphertext column is cleared at read time while the row survives as a tombstone until an expiry sweep removes it. [[#retention #portal]]
- CARE-Y asks the telephony provider to delete each call and recording log after processing, with retries when the request fails. [[#retention #telephony]]
- An organization deletion request starts a 30-day cooling-off period. After it elapses, the operator CLI takes a pre-deletion per-organization snapshot into the same backup repository, then drops the schema, blobs, and platform rows. The pre-deletion snapshot follows the same backup retention window. [[#retention #server-holds]]
**What survives a deletion?** [[#retention #metadata #server-holds]]
- Foreign key relationships and row counts remain readable in the tables that are left. [[#retention #metadata]]
- A deleted case removes its own ciphertext and its key wraps. A key wrap without its case cannot be recovered. [[#retention #encryption]]
- Fund ledger entries carry no case reference, so a disbursement recorded against a case survives that case's purge as an organization-key-sealed record of the amount, date, and recorder. [[#retention #server-holds]]
- Escrow holds key material rather than data, so no escrow ceremony brings back a deleted row. Nightly backup snapshots within the retention window can. [[#retention #keys]]
**The retention column and the purge jobs.** [[#retention]]
- The organization-wide window is \`org_config.pii_retention_days\`, an integer column defined in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`, written through \`setPiiRetentionDays\` in \`packages/server/src/auth/service.ts\` behind a permission-gated tRPC procedure in \`packages/server/src/routes/auth.ts\`, and read back for display through the hub status query. [[#retention #permissions]]
- The purge itself is \`packages/server/src/jobs/pii-retention.ts\`, which exports \`purgeTicket\` and \`purgeClient\` so manual deletion runs the same cascade. [[#retention]]
- The independent sweeps live in \`packages/server/src/jobs/\`, where \`portal-message-expiry.ts\` handles the 30-day portal window across tenant schemas and \`log-deletion.ts\` dispatches provider log deletions with backoff. [[#retention #portal #telephony]]
- Share link expiry logic is in \`packages/server/src/portal/share-service.ts\`. [[#retention #portal]]
- Nightly backups are in \`deploy/backup/backup-full.sh\`, restore in \`deploy/backup/restore-full.sh\`, and organization-level backup in \`deploy/backup/backup-org.sh\`. The erasure pipeline is \`deploy/db/org-erase.sh\` started by \`deploy/db/care-y-org-erase.timer\`. [[#retention #server-holds]]`)
};

const es_demo_narrative_deepdive_data_retention_body = /** @type {(inputs: Demo_Narrative_Deepdive_Data_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los datos que una organización ya no necesita todavía se le pueden arrebatar. Para una población perseguida por un adversario con recursos de un estado, un expediente de caso de hace tres años sigue siendo un riesgo vivo para una persona que puede haberse mudado, haber cambiado de nombre o haber callado. El cifrado protege lo que está almacenado; la retención decide si se almacena en absoluto. Son dos defensas distintas y una organización necesita las dos. [[#retention #privacy]]
La política de retención de la organización está apagada hasta que una persona administradora la enciende, y encenderla implica elegir una ventana de entre 1 y 3.650 días. Un trabajo diario elimina de forma definitiva cada caso cerrado cuya última actividad sea más antigua que esa ventana, retirando sus archivos almacenados antes que sus filas y pidiendo al proveedor de telefonía que elimine sus propios registros de llamadas y grabaciones del caso. El registro de un cliente, junto con sus filas de canal del portal y de cuenta, se va solo cuando se va el último caso de ese cliente; las filas de teléfono y correo del cliente se van solo cuando ningún otro cliente las referencia. Un cliente con un caso abierto o reciente queda intacto, y una organización que nunca ha fijado una ventana se omite. Tanto activar la política como cambiar la ventana piden confirmación, y la confirmación indica que los datos eliminados abandonan la base de datos activa de inmediato y caducan de las copias de seguridad cifradas dentro de la ventana de retención de copias. Con la política apagada, todo se conserva hasta que alguien lo elimina a mano. [[#retention]]
La política es un único ajuste para toda la organización y no una elección por cola o por tipo de caso. Una ventana por cola sería una decisión que alguien tendría que acertar el día en que crea una cola. Configurar la política requiere el permiso Definir cuánto tiempo se conservan los datos, que está con Administrador de forma predeterminada y se puede mover. [El sistema de permisos](#deep-dive/the-permission-system) explica cómo se mueve. [[#retention #permissions]]
La retención no puede eliminar lo que tiene una tercera parte. Tampoco puede eliminar una copia que un cliente guardó en su propio teléfono. Para clientes con un dispositivo vigilado, esa copia es a menudo la más peligrosa. [[#retention #failure-states]]
**Copias de seguridad nocturnas cifradas.** Un trabajo nocturno toma un volcado completo de la base de datos en un repositorio restic cifrado en un servidor separado. Las instantáneas se conservan al menos seis meses bajo una política de retención de catorce diarias, ocho semanales y seis mensuales. Una fila que el trabajo de retención elimina permanece en el repositorio de copias hasta que su instantánea contenedora más antigua caduca. Los scripts de restauración pueden recuperar cualquier instantánea dentro de esa ventana. El archivo de custodia no puede, porque guarda material de claves y no filas de datos. [[#retention #server-holds]]
**Vidas separadas.** Las copias de mensajes del portal, los enlaces de compartición de un solo uso, los registros del proveedor de telefonía y la eliminación de una organización siguen cada uno su propio calendario con independencia de la ventana de toda la organización. [[#retention #portal #telephony]]
- Las copias de mensajes del portal del lado del cliente se eliminan tras 30 días de inactividad del canal, medidos desde la más tardía de las marcas de última vista y de creación. Ese barrido retira los mensajes del portal, los adjuntos del portal y las grabaciones del portal mientras deja intacto el registro propio de la organización. [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata el modelo de canal. [[#retention #portal]]
- Los enlaces de compartición de un solo uso caducan 72 horas después de su creación o en la primera lectura, lo que ocurra primero. La columna de texto cifrado se vacía en el momento de la lectura mientras la fila sobrevive como lápida hasta que un barrido de caducidad la retira. [[#retention #portal]]
- CARE-Y pide al proveedor de telefonía que elimine cada registro de llamada y grabación después de procesarlo, con reintentos cuando la solicitud falla. [[#retention #telephony]]
- Una solicitud de eliminación de la organización inicia un periodo de enfriamiento de 30 días. Transcurrido el plazo, la herramienta CLI del operador toma una instantánea previa a la eliminación por organización en el mismo repositorio de copias, y luego elimina el esquema, los blobs y las filas de la plataforma. La instantánea previa sigue la misma ventana de retención de copias. [[#retention #server-holds]]
**¿Qué sobrevive a una eliminación?** [[#retention #metadata #server-holds]]
- Las relaciones de claves externas y el número de filas siguen siendo legibles en las tablas que quedan. [[#retention #metadata]]
- Un caso eliminado retira su propio texto cifrado y sus envolturas de clave. Una envoltura de clave sin su caso no es recuperable. [[#retention #encryption]]
- Las entradas del libro mayor de fondos no llevan referencia al caso, por lo que un desembolso registrado contra un caso sobrevive a la purga de ese caso como un registro sellado con la clave de la organización del importe, la fecha y quien lo registró. [[#retention #server-holds]]
- La custodia guarda material de claves y no datos, así que ninguna ceremonia de custodia devuelve una fila eliminada. Las instantáneas de la copia de seguridad nocturna dentro de la ventana de retención sí pueden. [[#retention #keys]]
**La columna de retención y los trabajos de purga.** [[#retention]]
- La ventana de toda la organización es \`org_config.pii_retention_days\`, una columna entera definida en \`packages/server/src/db/migrations/tenant/001_baseline.ts\`, escrita mediante \`setPiiRetentionDays\` en \`packages/server/src/auth/service.ts\` detrás de un procedimiento tRPC protegido por permiso en \`packages/server/src/routes/auth.ts\`, y leída de vuelta para mostrarla mediante la consulta de estado del hub. [[#retention #permissions]]
- La purga en sí es \`packages/server/src/jobs/pii-retention.ts\`, que exporta \`purgeTicket\` y \`purgeClient\` para que la eliminación manual recorra la misma cascada. [[#retention]]
- Los barridos independientes viven en \`packages/server/src/jobs/\`, donde \`portal-message-expiry.ts\` se encarga de la ventana de 30 días del portal en todos los esquemas de inquilino y \`log-deletion.ts\` despacha las eliminaciones de registros del proveedor con reintentos escalonados. [[#retention #portal #telephony]]
- La lógica de caducidad de los enlaces de compartición está en \`packages/server/src/portal/share-service.ts\`. [[#retention #portal]]
- Las copias nocturnas están en \`deploy/backup/backup-full.sh\`, la restauración en \`deploy/backup/restore-full.sh\` y la copia por organización en \`deploy/backup/backup-org.sh\`. La cadena de eliminación es \`deploy/db/org-erase.sh\`, iniciada por \`deploy/db/care-y-org-erase.timer\`. [[#retention #server-holds]]`)
};

const en_xa2_demo_narrative_deepdive_data_retention_body = /** @type {(inputs: Demo_Narrative_Deepdive_Data_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Dàtà àn òrgànìzàtìòn nò lòngèr nèèds càn stìll bè tàkèn fròm ìt. Fòr à pòpùlàtìòn tàrgètèd by à stàtè-lèvèl àdvèrsàry, à càsè rècòrd fròm thrèè yèàrs àgò rèmàìns à lìvè rìsk tò à pèrsòn whò mày hàvè mòvèd, chàngèd nàmès, òr gònè qùìèt. Èncryptìòn pròtècts whàt ìs stòrèd; rètèntìòn dècìdès whèthèr ìt ìs stòrèd àt àll. Thè twò àrè dìffèrènt dèfènsès ànd àn òrgànìzàtìòn nèèds bòth. [[#rètèntìòn #prìvàcy]]
Thè òrgànìzàtìòn's rètèntìòn pòlìcy ìs òff ùntìl àn àdmìnìstràtòr tùrns ìt òn, ànd tùrnìng ìt òn mèàns chòòsìng à wìndòw bètwèèn 1 ànd 3,650 dàys. À dàìly jòb hàrd-dèlètès èvèry clòsèd càsè whòsè làst àctìvìty ìs òldèr thàn thàt wìndòw, rèmòvìng ìts stòrèd fìlès bèfòrè ìts ròws ànd àskìng thè tèlèphòny pròvìdèr tò dèlètè ìts òwn càll ànd rècòrdìng lògs fòr thè càsè. À clìènt rècòrd, tògèthèr wìth ìts pòrtàl chànnèl ànd àccòùnt ròws, gòès ònly whèn thè làst càsè fòr thàt clìènt gòès; thè clìènt's phònè ànd èmàìl ròws gò ònly whèn nò òthèr clìènt rèfèrèncès thèm. À clìènt wìth àn òpèn òr à rècènt càsè ìs ùntòùchèd, ànd àn òrgànìzàtìòn thàt hàs nèvèr sèt à wìndòw ìs skìppèd. Ènàblìng thè pòlìcy ànd chàngìng thè wìndòw bòth àsk fòr cònfìrmàtìòn, ànd thè cònfìrmàtìòn stàtès thàt dèlètèd dàtà lèàvès thè lìvè dàtàbàsè àt òncè ànd àgès òùt òf thè èncryptèd bàckùps wìthìn thè bàckùp rètèntìòn wìndòw. Wìth thè pòlìcy òff, èvèrythìng ìs kèpt ùntìl sòmèònè dèlètès ìt by hànd. [[#rètèntìòn]]
Thè pòlìcy ìs ònè sèttìng fòr thè whòlè òrgànìzàtìòn ràthèr thàn à chòìcè pèr qùèùè òr pèr càsè typè. À pèr-qùèùè wìndòw wòùld bè à dècìsìòn sòmèònè hàs tò gèt rìght òn thè dày thèy crèàtè à qùèùè. Cònfìgùrìng thè pòlìcy rèqùìrès thè Mànàgè rètèntìòn pèrmìssìòn, whìch sìts wìth Àdmìn by dèfàùlt ànd càn bè mòvèd. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw thàt mòvès. [[#rètèntìòn #pèrmìssìòns]]
Rètèntìòn cànnòt dèlètè whàt à thìrd pàrty hòlds. Ìt cànnòt dèlètè à còpy à clìènt kèpt òn thèìr òwn phònè èìthèr. Fòr clìènts òn à mònìtòrèd dèvìcè thàt còpy ìs òftèn thè mòrè dàngèròùs ònè. [[#rètèntìòn #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Nìghtly èncryptèd bàckùps. ••••••••** À nìghtly jòb tàkès à fùll dàtàbàsè dùmp ìntò àn èncryptèd rèstìc rèpòsìtòry òn à sèpàràtè hòst. Snàpshòts àrè kèpt fòr àt lèàst sìx mònths ùndèr à rètèntìòn pòlìcy òf fòùrtèèn dàìly, èìght wèèkly, ànd sìx mònthly snàpshòts. À ròw thè rètèntìòn jòb dèlètès rèmàìns ìn thè bàckùp rèpòsìtòry ùntìl ìts òldèst còntàìnìng snàpshòt àgès òùt. Thè rèstòrè scrìpts càn brìng bàck àny snàpshòt wìthìn thàt wìndòw. Thè èscròw fìlè cànnòt, bècàùsè ìt hòlds kèy màtèrìàl ànd nòt dàtà ròws. [[#rètèntìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sèpàràtè lìfètìmès. ••••••** Pòrtàl mèssàgè còpìès, ònè-tìmè shàrè lìnks, tèlèphòny pròvìdèr lògs, ànd òrgànìzàtìòn èràsùrè èàch fòllòw thèìr òwn schèdùlè ìndèpèndènt òf thè òrgànìzàtìòn-wìdè wìndòw. [[#rètèntìòn #pòrtàl #tèlèphòny]]
- Pòrtàl mèssàgè còpìès òn thè clìènt sìdè àrè dèlètèd àftèr 30 dàys òf chànnèl ìnàctìvìty, mèàsùrèd fròm thè làtèr òf thè làst-sèèn ànd crèàtèd tìmèstàmps. Thàt swèèp rèmòvès pòrtàl mèssàgès, pòrtàl àttàchmènts ànd pòrtàl rècòrdìngs whìlè lèàvìng thè òrgànìzàtìòn's òwn rècòrd ìntàct. [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thè chànnèl mòdèl. [[#rètèntìòn #pòrtàl]]
- Ònè-tìmè shàrè lìnks èxpìrè 72 hòùrs àftèr crèàtìòn òr òn fìrst rèàd, whìchèvèr còmès fìrst. Thè cìphèrtèxt còlùmn ìs clèàrèd àt rèàd tìmè whìlè thè ròw sùrvìvès às à tòmbstònè ùntìl àn èxpìry swèèp rèmòvès ìt. [[#rètèntìòn #pòrtàl]]
- CÀRÈ-Y àsks thè tèlèphòny pròvìdèr tò dèlètè èàch càll ànd rècòrdìng lòg àftèr pròcèssìng, wìth rètrìès whèn thè rèqùèst fàìls. [[#rètèntìòn #tèlèphòny]]
- Àn òrgànìzàtìòn dèlètìòn rèqùèst stàrts à 30-dày còòlìng-òff pèrìòd. Àftèr ìt èlàpsès, thè òpèràtòr CLÌ tàkès à prè-dèlètìòn pèr-òrgànìzàtìòn snàpshòt ìntò thè sàmè bàckùp rèpòsìtòry, thèn dròps thè schèmà, blòbs, ànd plàtfòrm ròws. Thè prè-dèlètìòn snàpshòt fòllòws thè sàmè bàckùp rètèntìòn wìndòw. [[#rètèntìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt sùrvìvès à dèlètìòn? ••••••••** [[#rètèntìòn #mètàdàtà #sèrvèr-hòlds]]
- Fòrèìgn kèy rèlàtìònshìps ànd ròw còùnts rèmàìn rèàdàblè ìn thè tàblès thàt àrè lèft. [[#rètèntìòn #mètàdàtà]]
- À dèlètèd càsè rèmòvès ìts òwn cìphèrtèxt ànd ìts kèy wràps. À kèy wràp wìthòùt ìts càsè cànnòt bè rècòvèrèd. [[#rètèntìòn #èncryptìòn]]
- Fùnd lèdgèr èntrìès càrry nò càsè rèfèrèncè, sò à dìsbùrsèmènt rècòrdèd àgàìnst à càsè sùrvìvès thàt càsè's pùrgè às àn òrgànìzàtìòn-kèy-sèàlèd rècòrd òf thè àmòùnt, dàtè, ànd rècòrdèr. [[#rètèntìòn #sèrvèr-hòlds]]
- Èscròw hòlds kèy màtèrìàl ràthèr thàn dàtà, sò nò èscròw cèrèmòny brìngs bàck à dèlètèd ròw. Nìghtly bàckùp snàpshòts wìthìn thè rètèntìòn wìndòw càn. [[#rètèntìòn #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rètèntìòn còlùmn ànd thè pùrgè jòbs. ••••••••••••** [[#rètèntìòn]]
- Thè òrgànìzàtìòn-wìdè wìndòw ìs \`òrg_cònfìg.pìì_rètèntìòn_dàys\`, àn ìntègèr còlùmn dèfìnèd ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`, wrìttèn thròùgh \`sètPììRètèntìònDàys\` ìn \`pàckàgès/sèrvèr/src/àùth/sèrvìcè.ts\` bèhìnd à pèrmìssìòn-gàtèd tRPC pròcèdùrè ìn \`pàckàgès/sèrvèr/src/ròùtès/àùth.ts\`, ànd rèàd bàck fòr dìsplày thròùgh thè hùb stàtùs qùèry. [[#rètèntìòn #pèrmìssìòns]]
- Thè pùrgè ìtsèlf ìs \`pàckàgès/sèrvèr/src/jòbs/pìì-rètèntìòn.ts\`, whìch èxpòrts \`pùrgèTìckèt\` ànd \`pùrgèClìènt\` sò mànùàl dèlètìòn rùns thè sàmè càscàdè. [[#rètèntìòn]]
- Thè ìndèpèndènt swèèps lìvè ìn \`pàckàgès/sèrvèr/src/jòbs/\`, whèrè \`pòrtàl-mèssàgè-èxpìry.ts\` hàndlès thè 30-dày pòrtàl wìndòw àcròss tènànt schèmàs ànd \`lòg-dèlètìòn.ts\` dìspàtchès pròvìdèr lòg dèlètìòns wìth bàckòff. [[#rètèntìòn #pòrtàl #tèlèphòny]]
- Shàrè lìnk èxpìry lògìc ìs ìn \`pàckàgès/sèrvèr/src/pòrtàl/shàrè-sèrvìcè.ts\`. [[#rètèntìòn #pòrtàl]]
- Nìghtly bàckùps àrè ìn \`dèplòy/bàckùp/bàckùp-fùll.sh\`, rèstòrè ìn \`dèplòy/bàckùp/rèstòrè-fùll.sh\`, ànd òrgànìzàtìòn-lèvèl bàckùp ìn \`dèplòy/bàckùp/bàckùp-òrg.sh\`. Thè èràsùrè pìpèlìnè ìs \`dèplòy/db/òrg-èràsè.sh\` stàrtèd by \`dèplòy/db/càrè-y-òrg-èràsè.tìmèr\`. [[#rètèntìòn #sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Data an organization no longer needs can still be taken from it. For a population targeted by a state-level adversary, a case record from three years ago rem..." |
*
* @param {Demo_Narrative_Deepdive_Data_Retention_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_data_retention_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Data_Retention_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Data_Retention_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_data_retention_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_data_retention_body(inputs)
	return en_demo_narrative_deepdive_data_retention_body(inputs)
});