/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Settings_Identity_BodyInputs */

const en_demo_narrative_settings_identity_body = /** @type {(inputs: Demo_Narrative_Settings_Identity_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The user has a display name visible on their work and a username used to sign in. The display name is encrypted in the browser before it reaches the server. The username passes through the server in plaintext at account creation and again at a username change. A username change requires the current password, and a display name change does not. [[#privacy #server-holds]]
**How is the display name protected?** The browser seals the display name to the organization's public key. The server stores the resulting ciphertext and cannot read it. Every surface that shows a display name decrypts it in the browser. A user with the Manage users permission can update another account's display name through the same seal, from their own browser. [How encryption works](#deep-dive/how-encryption-works) covers the organization key. [[#encryption #server-holds]]
**Why does the username reach the server in plaintext?** Sign-in requires the server to match a username against a keyed hash it computed earlier. The server computes that hash, stores it for future lookups, and seals a separate copy with the organization key so browsers can decrypt it. No plaintext column is kept. The hash is salted with the organization's identifier, so one username shared by two organizations yields two distinct hashes. [Username and password](#login/credentials) covers the sign-in side and the fake-salt defense. [[#server-holds #metadata]]
**What can someone learn from the stored hash?** The hash uses HMAC-SHA256 keyed with a value derived from the server's operational key. Someone holding both the database and that key can test a guessed username and confirm whether it belongs to an account. The hash cannot be reversed into a username. Without the operational key, a database dump alone is not enough to test guesses. A username based on a legal name or email address is confirmable with the key; one unrelated to any person is not. [[#metadata #privacy]]
**What does a failed username change say?** The self-service path reports a conflict with the same generic wording it uses for any other failure, so an attempt does not reveal whether a username is taken. The administrator path (Manage users) names the conflict for the administrator. An administrator cannot change their own username through the administrator path and must use the self-service path, which requires the current password. [[#failure-states #permissions]]
**The profile mutations and their columns.** Both changes are mutations in \`packages/server/src/routes/profile.ts\` over \`updateDisplayName\` and \`updateUsername\` in \`packages/server/src/auth/service.ts\`. The columns are \`users.encrypted_display_name\`, \`users.encrypted_identifier\` and \`users.identifier_hash\` from \`packages/server/src/db/migrations/tenant/001_create_users.ts\`, and the keyed hash is \`hashIdentifier\` in \`packages/server/src/crypto/field-encryptor.ts\`. [[#server-holds]]`)
};

const es_demo_narrative_settings_identity_body = /** @type {(inputs: Demo_Narrative_Settings_Identity_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La persona usuaria tiene un nombre visible que aparece en su trabajo y un nombre de usuario con el que inicia sesión. El nombre visible se cifra en el navegador antes de llegar al servidor. El nombre de usuario pasa por el servidor en texto plano durante la creación de la cuenta y de nuevo durante un cambio de nombre de usuario. Un cambio de nombre de usuario requiere la contraseña actual, y un cambio de nombre visible no. [[#privacy #server-holds]]
**¿Cómo se protege el nombre visible?** El navegador sella el nombre visible con la clave pública de la organización. El servidor almacena el texto cifrado resultante y no puede leerlo. Cada superficie que muestra un nombre visible lo descifra en el navegador. Una persona con el permiso Gestionar usuarios puede actualizar el nombre visible de otra cuenta con el mismo sellado, desde su propio navegador. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la clave de la organización. [[#encryption #server-holds]]
**¿Por qué el nombre de usuario llega al servidor en texto plano?** El inicio de sesión requiere que el servidor compare un nombre de usuario contra un hash con clave que calculó anteriormente. El servidor calcula ese hash, lo almacena para futuras consultas, y sella una copia separada con la clave de la organización para que los navegadores la descifren. No se conserva ninguna columna en texto plano. El hash se sala con el identificador de la organización, de modo que un nombre de usuario compartido por dos organizaciones produce dos hashes distintos. [Nombre de usuario y contraseña](#login/credentials) trata el lado del inicio de sesión y la defensa de sal falsa. [[#server-holds #metadata]]
**¿Qué puede alguien aprender del hash almacenado?** El hash usa HMAC-SHA256 con una clave derivada de la clave operativa del servidor. Quien tenga la base de datos y esa clave puede probar un nombre de usuario adivinado y confirmar si corresponde a una cuenta. El hash no puede invertirse para obtener un nombre de usuario. Sin la clave operativa, un volcado de la base de datos no basta para probar conjeturas. Un nombre de usuario basado en un nombre legal o una dirección de correo se puede confirmar con la clave; uno que no esté ligado a ninguna persona, no. [[#metadata #privacy]]
**¿Qué dice un cambio de nombre de usuario fallido?** La ruta de autoservicio informa un conflicto con la misma redacción genérica que usa para cualquier otro fallo, así que un intento no revela si un nombre de usuario está ocupado. La ruta de administración (Gestionar usuarios) indica el conflicto a quien administra. Quien administra no puede cambiar su propio nombre de usuario por la ruta de administración y debe usar la ruta de autoservicio, que requiere la contraseña actual. [[#failure-states #permissions]]
**Las mutaciones de perfil y sus columnas.** Los dos cambios son mutaciones en \`packages/server/src/routes/profile.ts\` sobre \`updateDisplayName\` y \`updateUsername\` en \`packages/server/src/auth/service.ts\`. Las columnas son \`users.encrypted_display_name\`, \`users.encrypted_identifier\` y \`users.identifier_hash\` de \`packages/server/src/db/migrations/tenant/001_create_users.ts\`, y el hash con clave es \`hashIdentifier\` en \`packages/server/src/crypto/field-encryptor.ts\`. [[#server-holds]]`)
};

const en_xa2_demo_narrative_settings_identity_body = /** @type {(inputs: Demo_Narrative_Settings_Identity_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ùsèr hàs à dìsplày nàmè vìsìblè òn thèìr wòrk ànd à ùsèrnàmè ùsèd tò sìgn ìn. Thè dìsplày nàmè ìs èncryptèd ìn thè bròwsèr bèfòrè ìt rèàchès thè sèrvèr. Thè ùsèrnàmè pàssès thròùgh thè sèrvèr ìn plàìntèxt àt àccòùnt crèàtìòn ànd àgàìn àt à ùsèrnàmè chàngè. À ùsèrnàmè chàngè rèqùìrès thè cùrrènt pàsswòrd, ànd à dìsplày nàmè chàngè dòès nòt. [[#prìvàcy #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìs thè dìsplày nàmè pròtèctèd? •••••••••••** Thè bròwsèr sèàls thè dìsplày nàmè tò thè òrgànìzàtìòn's pùblìc kèy. Thè sèrvèr stòrès thè rèsùltìng cìphèrtèxt ànd cànnòt rèàd ìt. Èvèry sùrfàcè thàt shòws à dìsplày nàmè dècrypts ìt ìn thè bròwsèr. À ùsèr wìth thè Mànàgè ùsèrs pèrmìssìòn càn ùpdàtè ànòthèr àccòùnt's dìsplày nàmè thròùgh thè sàmè sèàl, fròm thèìr òwn bròwsèr. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè òrgànìzàtìòn kèy. [[#èncryptìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why dòès thè ùsèrnàmè rèàch thè sèrvèr ìn plàìntèxt? ••••••••••••••••** Sìgn-ìn rèqùìrès thè sèrvèr tò màtch à ùsèrnàmè àgàìnst à kèyèd hàsh ìt còmpùtèd èàrlìèr. Thè sèrvèr còmpùtès thàt hàsh, stòrès ìt fòr fùtùrè lòòkùps, ànd sèàls à sèpàràtè còpy wìth thè òrgànìzàtìòn kèy sò bròwsèrs càn dècrypt ìt. Nò plàìntèxt còlùmn ìs kèpt. Thè hàsh ìs sàltèd wìth thè òrgànìzàtìòn's ìdèntìfìèr, sò ònè ùsèrnàmè shàrèd by twò òrgànìzàtìòns yìèlds twò dìstìnct hàshès. [Ùsèrnàmè ànd pàsswòrd](#lògìn/crèdèntìàls) còvèrs thè sìgn-ìn sìdè ànd thè fàkè-sàlt dèfènsè. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt càn sòmèònè lèàrn fròm thè stòrèd hàsh? ••••••••••••••** Thè hàsh ùsès HMÀC-SHÀ256 kèyèd wìth à vàlùè dèrìvèd fròm thè sèrvèr's òpèràtìònàl kèy. Sòmèònè hòldìng bòth thè dàtàbàsè ànd thàt kèy càn tèst à gùèssèd ùsèrnàmè ànd cònfìrm whèthèr ìt bèlòngs tò àn àccòùnt. Thè hàsh cànnòt bè rèvèrsèd ìntò à ùsèrnàmè. Wìthòùt thè òpèràtìònàl kèy, à dàtàbàsè dùmp àlònè ìs nòt ènòùgh tò tèst gùèssès. À ùsèrnàmè bàsèd òn à lègàl nàmè òr èmàìl àddrèss ìs cònfìrmàblè wìth thè kèy; ònè ùnrèlàtèd tò àny pèrsòn ìs nòt. [[#mètàdàtà #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à fàìlèd ùsèrnàmè chàngè sày? ••••••••••••** Thè sèlf-sèrvìcè pàth rèpòrts à cònflìct wìth thè sàmè gènèrìc wòrdìng ìt ùsès fòr àny òthèr fàìlùrè, sò àn àttèmpt dòès nòt rèvèàl whèthèr à ùsèrnàmè ìs tàkèn. Thè àdmìnìstràtòr pàth (Mànàgè ùsèrs) nàmès thè cònflìct fòr thè àdmìnìstràtòr. Àn àdmìnìstràtòr cànnòt chàngè thèìr òwn ùsèrnàmè thròùgh thè àdmìnìstràtòr pàth ànd mùst ùsè thè sèlf-sèrvìcè pàth, whìch rèqùìrès thè cùrrènt pàsswòrd. [[#fàìlùrè-stàtès #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pròfìlè mùtàtìòns ànd thèìr còlùmns. ••••••••••••** Bòth chàngès àrè mùtàtìòns ìn \`pàckàgès/sèrvèr/src/ròùtès/pròfìlè.ts\` òvèr \`ùpdàtèDìsplàyNàmè\` ànd \`ùpdàtèÙsèrnàmè\` ìn \`pàckàgès/sèrvèr/src/àùth/sèrvìcè.ts\`. Thè còlùmns àrè \`ùsèrs.èncryptèd_dìsplày_nàmè\`, \`ùsèrs.èncryptèd_ìdèntìfìèr\` ànd \`ùsèrs.ìdèntìfìèr_hàsh\` fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_crèàtè_ùsèrs.ts\`, ànd thè kèyèd hàsh ìs \`hàshÌdèntìfìèr\` ìn \`pàckàgès/sèrvèr/src/cryptò/fìèld-èncryptòr.ts\`. [[#sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The user has a display name visible on their work and a username used to sign in. The display name is encrypted in the browser before it reaches the server. ..." |
*
* @param {Demo_Narrative_Settings_Identity_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_settings_identity_body = /** @type {((inputs?: Demo_Narrative_Settings_Identity_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Settings_Identity_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_settings_identity_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_settings_identity_body(inputs)
	return en_demo_narrative_settings_identity_body(inputs)
});