/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Submit_BodyInputs */

const en_demo_narrative_client_intake_submit_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Submit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Submitting encrypts every answer in the browser, composes the case title and body from them there as well, and sends ciphertext the server has no key for. The server creates the case, routes it and tells the destination queue's members that something arrived, without any of it passing through in the clear. [[#encryption #server-holds]]
**Working through a form in pages.** A form split into pages checks the current page before moving on and lists what is outstanding with the question each problem belongs to, and the visitor can move on anyway, which keeps a question someone cannot answer from being a dead end. On the last page the check runs across every page, the outstanding items are listed with the page each one sits on, and sending stays blocked until they are resolved. Pages whose questions depend on an earlier answer are skipped when that answer does not call for them, and the progress count counts only the pages that apply. [[#failure-states #client-data]]
**How often a form can be submitted.** Three submissions per address per hour is the default, and the limit is configured per deployment. An organization that expects abuse can additionally require the browser to solve a puzzle before each submission, which is off unless a difficulty is configured and is priced to cost a visitor a moment and an automated flood considerably more. [[#failure-states #portal]]
**Where a submission goes.** The queue is chosen by the routing answer when the form has one and the resolved queue is on that form's allow-list, by the form's own destination queue when it does not, and by the organization's intake queue when neither applies. A submission with no queue anywhere in that chain is refused rather than parked, so a form with no destination configured fails at the first submission rather than collecting cases nobody is told about. [Queues](#admin-people/queues) covers how membership decides who is told. [[#permissions #metadata]]
**What comes back.** A successful submission returns a reference code, which is the alias generated for the new client record, and the organization's own confirmation message when it wrote one. The code is what the visitor quotes to be found again, since the organization holds no name it can search on. [[#client-data #privacy]]
**The submit path and its limits.** The browser assembles and encrypts in \`handleSubmit\` in \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\` through \`encryptIntake\` and \`resolveSubmitMetadata\` in \`intake-crypto.ts\`. The route is \`submitIntake\` in \`packages/server/src/routes/client-portal.ts\`, which applies the rate limiter and the puzzle gate before decoding anything, and the writes are one transaction in \`createIntakeTicket\` in \`packages/server/src/portal/intake-service.ts\`, with the notification intent enqueued inside it so a rolled-back case cannot notify anyone. [[#server-holds #failure-states]]`)
};

const es_demo_narrative_client_intake_submit_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Submit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Enviar cifra cada respuesta en el navegador, compone allí mismo el título y el cuerpo del caso a partir de ellas y manda texto cifrado para el que el servidor no tiene ninguna clave. El servidor crea el caso, lo encamina y avisa a los miembros de la cola de destino de que ha llegado algo, sin que nada de ello pase por él en claro. [[#encryption #server-holds]]
**Recorrer un formulario por páginas.** Un formulario repartido en páginas comprueba la página actual antes de seguir y enumera lo que queda pendiente junto con la pregunta a la que corresponde cada problema, y el visitante puede seguir de todos modos, lo que evita que una pregunta que alguien no puede responder sea un callejón sin salida. En la última página la comprobación abarca todas las páginas, los puntos pendientes se enumeran con la página en la que está cada uno, y el envío sigue bloqueado hasta resolverlos. Las páginas cuyas preguntas dependen de una respuesta anterior se omiten cuando esa respuesta no las requiere, y el recuento de avance cuenta solo las páginas que corresponden. [[#failure-states #client-data]]
**Con qué frecuencia se puede enviar un formulario.** Tres envíos por dirección y por hora es el valor predeterminado, y el límite se configura en cada despliegue. Una organización que espere abusos puede además exigir que el navegador resuelva un rompecabezas antes de cada envío, algo que está desactivado salvo que se configure una dificultad y que está calibrado para costarle un instante a un visitante y bastante más a una avalancha automatizada. [[#failure-states #portal]]
**Adónde va un envío.** La cola la elige la respuesta de enrutamiento cuando el formulario tiene una y la cola resuelta figura en la lista de permitidos de ese formulario; si no, la cola de destino del propio formulario; y si tampoco, la cola de admisión de la organización. Un envío que no encuentra cola en ninguno de esos pasos se rechaza en lugar de quedar aparcado, así que un formulario sin destino configurado falla en el primer envío y no acumula casos de los que nadie se entera. [Colas](#admin-people/queues) trata cómo la pertenencia decide a quién se avisa. [[#permissions #metadata]]
**Lo que se recibe de vuelta.** Un envío correcto devuelve un código de referencia, que es el alias generado para el nuevo registro de cliente, y el mensaje de confirmación de la organización cuando ha redactado uno. El código es lo que el visitante cita para que vuelvan a localizarlo, ya que la organización no guarda ningún nombre por el que pueda buscar. [[#client-data #privacy]]
**La ruta de envío y sus límites.** El navegador ensambla y cifra en \`handleSubmit\`, en \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\`, mediante \`encryptIntake\` y \`resolveSubmitMetadata\`, en \`intake-crypto.ts\`. La ruta es \`submitIntake\`, en \`packages/server/src/routes/client-portal.ts\`, que aplica el limitador de frecuencia y la barrera del rompecabezas antes de decodificar nada, y las escrituras son una sola transacción en \`createIntakeTicket\`, en \`packages/server/src/portal/intake-service.ts\`, con la intención de notificación encolada dentro de ella para que un caso revertido no pueda avisar a nadie. [[#server-holds #failure-states]]`)
};

const en_xa2_demo_narrative_client_intake_submit_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Submit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Sùbmìttìng èncrypts èvèry ànswèr ìn thè bròwsèr, còmpòsès thè càsè tìtlè ànd bòdy fròm thèm thèrè às wèll, ànd sènds cìphèrtèxt thè sèrvèr hàs nò kèy fòr. Thè sèrvèr crèàtès thè càsè, ròùtès ìt ànd tèlls thè dèstìnàtìòn qùèùè's mèmbèrs thàt sòmèthìng àrrìvèd, wìthòùt àny òf ìt pàssìng thròùgh ìn thè clèàr. [[#èncryptìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Wòrkìng thròùgh à fòrm ìn pàgès. ••••••••••** À fòrm splìt ìntò pàgès chècks thè cùrrènt pàgè bèfòrè mòvìng òn ànd lìsts whàt ìs òùtstàndìng wìth thè qùèstìòn èàch pròblèm bèlòngs tò, ànd thè vìsìtòr càn mòvè òn ànywày, whìch kèèps à qùèstìòn sòmèònè cànnòt ànswèr fròm bèìng à dèàd ènd. Òn thè làst pàgè thè chèck rùns àcròss èvèry pàgè, thè òùtstàndìng ìtèms àrè lìstèd wìth thè pàgè èàch ònè sìts òn, ànd sèndìng stàys blòckèd ùntìl thèy àrè rèsòlvèd. Pàgès whòsè qùèstìòns dèpènd òn àn èàrlìèr ànswèr àrè skìppèd whèn thàt ànswèr dòès nòt càll fòr thèm, ànd thè prògrèss còùnt còùnts ònly thè pàgès thàt àpply. [[#fàìlùrè-stàtès #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw òftèn à fòrm càn bè sùbmìttèd. •••••••••••** Thrèè sùbmìssìòns pèr àddrèss pèr hòùr ìs thè dèfàùlt, ànd thè lìmìt ìs cònfìgùrèd pèr dèplòymènt. Àn òrgànìzàtìòn thàt èxpècts àbùsè càn àddìtìònàlly rèqùìrè thè bròwsèr tò sòlvè à pùzzlè bèfòrè èàch sùbmìssìòn, whìch ìs òff ùnlèss à dìffìcùlty ìs cònfìgùrèd ànd ìs prìcèd tò còst à vìsìtòr à mòmènt ànd àn àùtòmàtèd flòòd cònsìdèràbly mòrè. [[#fàìlùrè-stàtès #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèrè à sùbmìssìòn gòès. ••••••••** Thè qùèùè ìs chòsèn by thè ròùtìng ànswèr whèn thè fòrm hàs ònè ànd thè rèsòlvèd qùèùè ìs òn thàt fòrm's àllòw-lìst, by thè fòrm's òwn dèstìnàtìòn qùèùè whèn ìt dòès nòt, ànd by thè òrgànìzàtìòn's ìntàkè qùèùè whèn nèìthèr àpplìès. À sùbmìssìòn wìth nò qùèùè ànywhèrè ìn thàt chàìn ìs rèfùsèd ràthèr thàn pàrkèd, sò à fòrm wìth nò dèstìnàtìòn cònfìgùrèd fàìls àt thè fìrst sùbmìssìòn ràthèr thàn còllèctìng càsès nòbòdy ìs tòld àbòùt. [Qùèùès](#àdmìn-pèòplè/qùèùès) còvèrs hòw mèmbèrshìp dècìdès whò ìs tòld. [[#pèrmìssìòns #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt còmès bàck. •••••** À sùccèssfùl sùbmìssìòn rètùrns à rèfèrèncè còdè, whìch ìs thè àlìàs gènèràtèd fòr thè nèw clìènt rècòrd, ànd thè òrgànìzàtìòn's òwn cònfìrmàtìòn mèssàgè whèn ìt wròtè ònè. Thè còdè ìs whàt thè vìsìtòr qùòtès tò bè fòùnd àgàìn, sìncè thè òrgànìzàtìòn hòlds nò nàmè ìt càn sèàrch òn. [[#clìènt-dàtà #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè sùbmìt pàth ànd ìts lìmìts. ••••••••••** Thè bròwsèr àssèmblès ànd èncrypts ìn \`hàndlèSùbmìt\` ìn \`pàckàgès/clìènt/src/ròùtès/(clìènt)/ìntàkè/ÌntàkèFòrmBòdy.svèltè\` thròùgh \`èncryptÌntàkè\` ànd \`rèsòlvèSùbmìtMètàdàtà\` ìn \`ìntàkè-cryptò.ts\`. Thè ròùtè ìs \`sùbmìtÌntàkè\` ìn \`pàckàgès/sèrvèr/src/ròùtès/clìènt-pòrtàl.ts\`, whìch àpplìès thè ràtè lìmìtèr ànd thè pùzzlè gàtè bèfòrè dècòdìng ànythìng, ànd thè wrìtès àrè ònè trànsàctìòn ìn \`crèàtèÌntàkèTìckèt\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-sèrvìcè.ts\`, wìth thè nòtìfìcàtìòn ìntènt ènqùèùèd ìnsìdè ìt sò à ròllèd-bàck càsè cànnòt nòtìfy ànyònè. [[#sèrvèr-hòlds #fàìlùrè-stàtès]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Submitting encrypts every answer in the browser, composes the case title and body from them there as well, and sends ciphertext the server has no key for. Th..." |
*
* @param {Demo_Narrative_Client_Intake_Submit_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_submit_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Submit_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Submit_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_submit_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_submit_body(inputs)
	return en_demo_narrative_client_intake_submit_body(inputs)
});