/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Email_Thread_BodyInputs */

const en_demo_narrative_topic_email_thread_body = /** @type {(inputs: Demo_Narrative_Topic_Email_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Email sent and received on a ticket sits in the same thread as texts, portal replies, and notes. Email is the one channel whose content is readable by every mail server it passes through. [[#client-data #encryption #telephony]]
**How does an outbound email reach the thread?** The browser sends the relay the ticket, a subject, and a body. The server resolves and decrypts the client's address itself rather than accepting one from the request. A copy of the message is sealed with the ticket key and written to the thread as a follow-up. A second copy is sealed to the client's channel key when one is active, so the follow-up record survives a mailbox nobody reads. An organization can switch its email channel off, and the relay refuses before it decrypts an address. [Channel policy](#admin-comms/channel-policy) covers that setting. [Sending a reply](#ticket-detail/reply) covers the copies a message produces, and [The telephony relay](#deep-dive/the-telephony-relay) covers the buffer handling this endpoint shares with the text path. [[#encryption #server-holds #telephony]]
**Reply address and token.** Each ticket gets a reply address carrying a 128-bit random token. The server stores only a keyed hash of that token, so the address exists in the outbound header and in the client's mailbox and nowhere the database can give it up. Revoking the token stops emailed replies from routing to that thread. Sending a new reply address for a ticket retires the previous one. [[#keys #server-holds #privacy]]
**What is an inbound email trusted for?** The reply token decides which ticket a message lands on. The From address is stored and shown as claimed and never used for routing, because anyone can write any address into it; each inbound follow-up carries that caution.
- Attachments are counted and dropped rather than imported.
- An over-long subject or body is truncated rather than refused.
- A message arriving on a closed ticket reopens it.
When the newest client-sent follow-up is an email, composing a text or a portal reply reports that the client may be waiting on email. The caution is dismissable per ticket for the rest of the session and is not raised when the organization has its email channel switched off. [Channel warnings](#ticket-detail/exposure-hints) covers the full set of channel cautions. [[#failure-states #privacy]]
**The relay handlers and the token row.** The outbound path is \`/relay/email\` in \`packages/server/src/routes/relay.ts\`, with reply address and footer assembly in \`packages/server/src/email/email-relay-service.ts\` and the token row from \`110_email_reply_tokens.ts\`. Inbound mail is accepted by \`inbound-receiver.ts\` and written by \`inbound-email.ts\`. The bubbles are \`EmailBubbleContent.svelte\` and \`EmailInboundBubbleContent.svelte\`. [[#client-data]]`)
};

const es_demo_narrative_topic_email_thread_body = /** @type {(inputs: Demo_Narrative_Topic_Email_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El correo electrónico enviado y recibido en un ticket aparece en el mismo hilo que los mensajes de texto, las respuestas del portal y las notas. El correo es el único canal cuyo contenido es legible por cada servidor de correo por el que pasa. [[#client-data #encryption #telephony]]
**¿Cómo llega un correo saliente al hilo?** El navegador envía al relay el ticket, un asunto y un cuerpo. El servidor resuelve y descifra la dirección del cliente por sí mismo en lugar de aceptar una de la solicitud. Una copia del mensaje se sella con la clave del ticket y se escribe en el hilo como seguimiento. Una segunda copia se sella con la clave de canal del cliente cuando hay una activa, para que el registro de seguimiento sobreviva a un buzón que nadie lee. Una organización puede desactivar su canal de correo electrónico, y el relay rechaza la solicitud antes de descifrar una dirección. [Política de canales](#admin-comms/channel-policy) trata esa configuración. [Enviando una respuesta](#ticket-detail/reply) trata las copias que produce un mensaje, y [El relay de telefonía](#deep-dive/the-telephony-relay) trata el manejo de búfer que este endpoint comparte con la ruta de texto. [[#encryption #server-holds #telephony]]
**Dirección de respuesta y token.** Cada ticket recibe una dirección de respuesta con un token aleatorio de 128 bits. El servidor almacena solo un hash con clave de ese token, de modo que la dirección existe en la cabecera del mensaje saliente y en el buzón del cliente y en ningún lugar que la base de datos pueda revelar. Revocar el token impide que las respuestas por correo se enruten a ese hilo. Enviar una nueva dirección de respuesta para un ticket retira la anterior. [[#keys #server-holds #privacy]]
**¿Para qué se confía en un correo entrante?** El token de respuesta decide a qué ticket se asigna un mensaje. La dirección del remitente se almacena y se muestra como declarada y nunca se usa para enrutamiento, porque cualquiera puede escribir cualquier dirección en ella; cada seguimiento entrante lleva esa advertencia.
- Los archivos adjuntos se cuentan y se descartan en lugar de importarse.
- Un asunto o cuerpo demasiado largo se trunca en lugar de rechazarse.
- Un mensaje que llega a un ticket cerrado lo reabre.
Cuando el seguimiento más reciente enviado por el cliente es un correo electrónico, componer un mensaje de texto o una respuesta del portal informa que el cliente podría estar esperando una respuesta por correo. La advertencia se puede descartar por ticket durante el resto de la sesión y no se muestra cuando la organización tiene su canal de correo desactivado. [Avisos de canal](#ticket-detail/exposure-hints) trata el conjunto completo de advertencias de canal. [[#failure-states #privacy]]
**Los handlers del relay y la fila del token.** La ruta de salida es \`/relay/email\` en \`packages/server/src/routes/relay.ts\`, con el ensamblaje de dirección de respuesta y pie de mensaje en \`packages/server/src/email/email-relay-service.ts\` y la fila del token en \`110_email_reply_tokens.ts\`. El correo entrante lo acepta \`inbound-receiver.ts\` y lo escribe \`inbound-email.ts\`. Las burbujas son \`EmailBubbleContent.svelte\` y \`EmailInboundBubbleContent.svelte\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_email_thread_body = /** @type {(inputs: Demo_Narrative_Topic_Email_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èmàìl sènt ànd rècèìvèd òn à tìckèt sìts ìn thè sàmè thrèàd às tèxts, pòrtàl rèplìès, ànd nòtès. Èmàìl ìs thè ònè chànnèl whòsè còntènt ìs rèàdàblè by èvèry màìl sèrvèr ìt pàssès thròùgh. [[#clìènt-dàtà #èncryptìòn #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès àn òùtbòùnd èmàìl rèàch thè thrèàd? ••••••••••••••** Thè bròwsèr sènds thè rèlày thè tìckèt, à sùbjèct, ànd à bòdy. Thè sèrvèr rèsòlvès ànd dècrypts thè clìènt's àddrèss ìtsèlf ràthèr thàn àccèptìng ònè fròm thè rèqùèst. À còpy òf thè mèssàgè ìs sèàlèd wìth thè tìckèt kèy ànd wrìttèn tò thè thrèàd às à fòllòw-ùp. À sècònd còpy ìs sèàlèd tò thè clìènt's chànnèl kèy whèn ònè ìs àctìvè, sò thè fòllòw-ùp rècòrd sùrvìvès à màìlbòx nòbòdy rèàds. Àn òrgànìzàtìòn càn swìtch ìts èmàìl chànnèl òff, ànd thè rèlày rèfùsès bèfòrè ìt dècrypts àn àddrèss. [Chànnèl pòlìcy](#àdmìn-còmms/chànnèl-pòlìcy) còvèrs thàt sèttìng. [Sèndìng à rèply](#tìckèt-dètàìl/rèply) còvèrs thè còpìès à mèssàgè pròdùcès, ànd [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs thè bùffèr hàndlìng thìs èndpòìnt shàrès wìth thè tèxt pàth. [[#èncryptìòn #sèrvèr-hòlds #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rèply àddrèss ànd tòkèn. ••••••••** Èàch tìckèt gèts à rèply àddrèss càrryìng à 128-bìt ràndòm tòkèn. Thè sèrvèr stòrès ònly à kèyèd hàsh òf thàt tòkèn, sò thè àddrèss èxìsts ìn thè òùtbòùnd hèàdèr ànd ìn thè clìènt's màìlbòx ànd nòwhèrè thè dàtàbàsè càn gìvè ìt ùp. Rèvòkìng thè tòkèn stòps èmàìlèd rèplìès fròm ròùtìng tò thàt thrèàd. Sèndìng à nèw rèply àddrèss fòr à tìckèt rètìrès thè prèvìòùs ònè. [[#kèys #sèrvèr-hòlds #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt ìs àn ìnbòùnd èmàìl trùstèd fòr? ••••••••••••** Thè rèply tòkèn dècìdès whìch tìckèt à mèssàgè lànds òn. Thè Fròm àddrèss ìs stòrèd ànd shòwn às clàìmèd ànd nèvèr ùsèd fòr ròùtìng, bècàùsè ànyònè càn wrìtè àny àddrèss ìntò ìt; èàch ìnbòùnd fòllòw-ùp càrrìès thàt càùtìòn.
- Àttàchmènts àrè còùntèd ànd dròppèd ràthèr thàn ìmpòrtèd.
- Àn òvèr-lòng sùbjèct òr bòdy ìs trùncàtèd ràthèr thàn rèfùsèd.
- À mèssàgè àrrìvìng òn à clòsèd tìckèt rèòpèns ìt.
Whèn thè nèwèst clìènt-sènt fòllòw-ùp ìs àn èmàìl, còmpòsìng à tèxt òr à pòrtàl rèply rèpòrts thàt thè clìènt mày bè wàìtìng òn èmàìl. Thè càùtìòn ìs dìsmìssàblè pèr tìckèt fòr thè rèst òf thè sèssìòn ànd ìs nòt ràìsèd whèn thè òrgànìzàtìòn hàs ìts èmàìl chànnèl swìtchèd òff. [Chànnèl wàrnìngs](#tìckèt-dètàìl/èxpòsùrè-hìnts) còvèrs thè fùll sèt òf chànnèl càùtìòns. [[#fàìlùrè-stàtès #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rèlày hàndlèrs ànd thè tòkèn ròw. ••••••••••••** Thè òùtbòùnd pàth ìs \`/rèlày/èmàìl\` ìn \`pàckàgès/sèrvèr/src/ròùtès/rèlày.ts\`, wìth rèply àddrèss ànd fòòtèr àssèmbly ìn \`pàckàgès/sèrvèr/src/èmàìl/èmàìl-rèlày-sèrvìcè.ts\` ànd thè tòkèn ròw fròm \`110_èmàìl_rèply_tòkèns.ts\`. Ìnbòùnd màìl ìs àccèptèd by \`ìnbòùnd-rècèìvèr.ts\` ànd wrìttèn by \`ìnbòùnd-èmàìl.ts\`. Thè bùbblès àrè \`ÈmàìlBùbblèCòntènt.svèltè\` ànd \`ÈmàìlÌnbòùndBùbblèCòntènt.svèltè\`. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Email sent and received on a ticket sits in the same thread as texts, portal replies, and notes. Email is the one channel whose content is readable by every ..." |
*
* @param {Demo_Narrative_Topic_Email_Thread_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_email_thread_body = /** @type {((inputs?: Demo_Narrative_Topic_Email_Thread_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Email_Thread_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_email_thread_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_email_thread_body(inputs)
	return en_demo_narrative_topic_email_thread_body(inputs)
});