/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Quick_Exit_BodyInputs */

const en_demo_narrative_client_quick_exit_body = /** @type {(inputs: Demo_Narrative_Client_Quick_Exit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A quick exit control is on every client-facing page, from the intake form through the portal, the account and a one-time share link. The control has no visible label, because the word \\"exit\\" on a screen someone else can see is itself a signal. Pressing it, or pressing Escape anywhere on the page, blanks the browser tab's title, discards the keys the page was holding, and sends the browser to an ordinary site the organization chooses in its settings, with a weather service as the default when it has chosen none. That navigation replaces the current history entry, so the back button does not return to the conversation. [[#privacy #portal]]
The control clears what is on the screen and the keys the page holds. History entries from before the client opened the link survive, the browser's cache and stored form data are untouched, and a screenshot, a saved message or a printed page stays where it was put. Software installed on the device to watch the person using it sees what that person sees well before the control is ever pressed. A client on a device someone else controls is better served by a channel the organization can end from its own side, which [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers, and by the copies the organization declines to keep, which [Data retention](#deep-dive/data-retention) covers. [[#privacy #failure-states]]
**What the server learns.** On the intake form, the portal and a share link the control reaches no server at all, so an activation leaves no trace on the organization's side. On the account page it also sends one beacon to the account logout procedure, and that request tells the server that this account's session ended at this moment and nothing about why. [[#server-holds #metadata #privacy]]
**What the control does when it fires.** Four steps run in a fixed order, and the page is gone by the end of the fourth. [[#privacy #keys]]
1. The document title is replaced with a blank space, so the tab strip stops naming the organization. [[#privacy]]
2. On the account page a beacon revokes the server-side session, sent as a beacon rather than an ordinary request because the navigation that follows would cancel anything still in flight. [[#server-holds]]
3. The page's key material is zeroed, which on the portal is the channel seed, the bearer token and the channel private scalar held in the portal worker, and on the account page the session keys derived at sign-in. [[#keys #encryption]]
4. The browser navigates to the safe URL through a history replacement rather than a push. [[#privacy]]
Escape is handled on the capture phase and cancels the event, so it reaches the exit ahead of the overlay stack that would otherwise close an open sheet, and an open panel is never the reason a press fails to leave. [[#privacy]]
**Leaving without pressing it.** A page-hide listener zeroes the same key material when the tab closes or the browser navigates away on its own, so the keys do not outlive the page even when nobody reaches the control. The account page also runs a 15 minute idle timer that counts human input alone, announces a warning to assistive technology at the 10 minute mark, and returns the page to the sign-in form when it fires, and server traffic and background refreshes do not reset it. [[#keys #failure-states]]
**Where the session outlives the page.** An account session is valid for 24 hours from sign-in, and the quick exit path is the only one that tells the server to end it early. Closing the tab, the idle timeout and a navigation away all stop at the browser, so a session ended those ways stays valid on the server until its own expiry. [[#server-holds #failure-states]]
**The shell mount and the safe URL.** The control is \`packages/client/src/lib/components/portal/QuickExit.svelte\`, mounted once per client page by \`packages/client/src/lib/shell/ClientShell.svelte\` in the navbar trailing slot, which is why it stays mounted through each state a client page passes through instead of being re-rendered per page. The safe URL resolves in \`packages/client/src/lib/client-shell/context.ts\`, preferring the page's own value, then the organization's configured URL, then a copy injected into the document before the browser parsed it, then the default. Anyone adding a client-facing surface supplies the callback that zeroes whatever key material that surface holds, because the control zeroes nothing on its own. [[#client-data #keys]]`)
};

const es_demo_narrative_client_quick_exit_body = /** @type {(inputs: Demo_Narrative_Client_Quick_Exit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un control de salida rápida está en todas las páginas del cliente, desde el formulario de admisión hasta el portal, la cuenta y un enlace compartido de un solo uso. El control no tiene etiqueta visible, porque la palabra \\"salir\\" en una pantalla que otra persona puede ver ya es una señal. Pulsarlo, o pulsar Escape en cualquier parte de la página, borra el título de la pestaña del navegador, descarta las claves que la página tenía en memoria y lleva el navegador a un sitio corriente que la organización elige en sus ajustes, con un servicio meteorológico como valor predeterminado cuando no ha elegido ninguno. Esa navegación reemplaza la entrada actual del historial, así que el botón atrás no devuelve a la conversación. [[#privacy #portal]]
El control borra lo que hay en la pantalla y las claves que la página tiene en memoria. Las entradas del historial anteriores a la apertura del enlace sobreviven, la caché del navegador y los datos de formulario guardados quedan intactos, y una captura de pantalla, un mensaje guardado o una página impresa siguen donde se dejaron. Un programa instalado en el dispositivo para vigilar a quien lo usa ve lo mismo que esa persona mucho antes de que el control llegue a pulsarse. Un cliente que usa un dispositivo controlado por otra persona está mejor servido por un canal que la organización pueda cerrar desde su propio lado, descrito en [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle), y por las copias que la organización decide no conservar, tratadas en [Retención de datos](#deep-dive/data-retention). [[#privacy #failure-states]]
**Lo que aprende el servidor.** En el formulario de admisión, en el portal y en un enlace compartido el control no llega a ningún servidor, así que una activación no deja rastro del lado de la organización. En la página de cuenta además se envía una baliza al procedimiento de cierre de sesión de la cuenta, y esa solicitud le dice al servidor que la sesión de esta cuenta terminó en este momento y nada sobre el motivo. [[#server-holds #metadata #privacy]]
**Lo que hace el control al activarse.** Se ejecutan cuatro pasos en un orden fijo, y al terminar el cuarto la página ya no está. [[#privacy #keys]]
1. El título del documento se reemplaza por un espacio en blanco, de modo que la tira de pestañas deja de nombrar a la organización. [[#privacy]]
2. En la página de cuenta una baliza revoca la sesión del lado del servidor, enviada como baliza y no como solicitud corriente porque la navegación posterior cancelaría cualquier petición todavía en curso. [[#server-holds]]
3. Se pone a cero el material de claves de la página, que en el portal es la semilla del canal, el token portador y el escalar privado del canal que custodia el worker del portal, y en la página de cuenta las claves de sesión derivadas al iniciar sesión. [[#keys #encryption]]
4. El navegador va a la URL segura mediante un reemplazo del historial en lugar de una inserción. [[#privacy]]
Escape se atiende en la fase de captura y cancela el evento, así que llega a la salida antes que la pila de superposiciones que de otro modo cerraría una hoja abierta, y un panel abierto nunca es el motivo de que una pulsación no consiga salir. [[#privacy]]
**Salir sin pulsarlo.** Un escuchador de ocultación de página pone a cero el mismo material de claves cuando la pestaña se cierra o el navegador sale por su cuenta, así que las claves no sobreviven a la página aunque nadie alcance el control. La página de cuenta además ejecuta un temporizador de inactividad de 15 minutos que cuenta únicamente la entrada humana, anuncia un aviso a la tecnología de asistencia a los 10 minutos y devuelve la página al formulario de inicio de sesión cuando vence, y ni el tráfico al servidor ni las actualizaciones en segundo plano lo reinician. [[#keys #failure-states]]
**Cuando la sesión sobrevive a la página.** Una sesión de cuenta es válida durante 24 horas desde el inicio de sesión, y la ruta de salida rápida es la única que le pide al servidor terminarla antes. Cerrar la pestaña, el vencimiento por inactividad y una navegación a otra dirección se quedan en el navegador, así que una sesión terminada de esas formas sigue siendo válida en el servidor hasta que expire por sí sola. [[#server-holds #failure-states]]
**El montaje en el shell y la URL segura.** El control es \`packages/client/src/lib/components/portal/QuickExit.svelte\`, montado una sola vez por página de cliente desde \`packages/client/src/lib/shell/ClientShell.svelte\` en la ranura final de la barra de navegación, y por eso se mantiene montado en cada estado por el que pasa una página de cliente en lugar de volver a renderizarse. La URL segura se resuelve en \`packages/client/src/lib/client-shell/context.ts\`, que prefiere el valor de la propia página, luego la URL configurada por la organización, luego una copia inyectada en el documento antes de que el navegador lo analizara, y por último el valor predeterminado. Quien añada una superficie de cliente aporta la función que pone a cero el material de claves que esa superficie custodia, porque el control no pone nada a cero por su cuenta. [[#client-data #keys]]`)
};

const en_xa2_demo_narrative_client_quick_exit_body = /** @type {(inputs: Demo_Narrative_Client_Quick_Exit_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè qùìck èxìt còntròl àppèàrs òn èvèry clìènt pàgè, fròm thè ìntàkè fòrm thròùgh thè pòrtàl ànd àccòùnt tò shàrè lìnks. Ìt ìs àn ìcòn wìth nò vìsìblè tèxt làbèl, bècàùsè thè wòrd "èxìt" òn scrèèn còùld dràw àttèntìòn òn à shàrèd òr mònìtòrèd dèvìcè.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìt wòrks. ••••** Tàppìng thè còntròl òr prèssìng Èscàpè ànywhèrè òn thè pàgè rùns à fìxèd sèqùèncè. Thè bròwsèr tàb's tìtlè ìs blànkèd sò thè tàb strìp dòès nòt shòw thè òrgànìzàtìòn's nàmè, àll èncryptìòn kèys hèld ìn mèmòry àrè zèròèd, ànd thè bròwsèr nàvìgàtès tò à nèùtràl sìtè thè òrgànìzàtìòn cònfìgùrès ìn ìts sèttìngs. Thè nàvìgàtìòn rèplàcès thè cùrrènt hìstòry èntry sò thè clìènt pàgè dòès nòt àppèàr bèhìnd thè bàck bùttòn. Èscàpè tàkès prècèdèncè òvèr clòsìng àny òpèn pànèl òr shèèt, bècàùsè lèàvìng fàst ìs thè pùrpòsè òf thè còntròl ànd thè nàvìgàtìòn tèàrs thè pàgè dòwn èìthèr wày. Òn thè àccòùnt pàgè, qùìck èxìt àlsò ènds thè sèrvèr sìdè sèssìòn sò thè còòkìè cànnòt bè rèùsèd.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sàfèty nèt. ••••** Qùìck èxìt zèròès kèys àùtòmàtìcàlly whèn à tàb ìs clòsèd òr thè vìsìtòr nàvìgàtès àwày bèfòrè ùsìng thè còntròl. Òn thè àccòùnt pàgè à 15 mìnùtè ìdlè tìmèr thàt wàrns àt thè tèn mìnùtè màrk rètùrns tò thè sìgn ìn fòrm.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Sècùrìty tràdèòff. ••••••** Thè àccòùnt pàgè's sèssìòn còòkìè hàs à 24 hòùr èxpìry. Whèn qùìck èxìt fìrès ìt ènds thè sèrvèr sèssìòn, bùt thè òthèr wàys òf lèàvìng thè pàgè dò nòt rèàch thè sèrvèr, sò thè sèssìòn stàys àlìvè ùntìl ìt èxpìrès òn ìts òwn.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ìn thè dèmò. ••••** Òn à rùnnìng CÀRÈ-Y sèrvèr thè còntròl nàvìgàtès tò thè sàfè ÙRL ìmmèdìàtèly. Ìn thè dèmò thè nàvìgàtìòn ìs ìntèrcèptèd sò thè èmbèddèd phònè stàys òn thè pàgè, ànd thè dàtà flòw pànèl rècòrds thè àctìvàtìòn ìnstèàd. ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A quick exit control is on every client-facing page, from the intake form through the portal, the account and a one-time share link. The control has no visib..." |
*
* @param {Demo_Narrative_Client_Quick_Exit_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_quick_exit_body = /** @type {((inputs?: Demo_Narrative_Client_Quick_Exit_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Quick_Exit_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_quick_exit_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_quick_exit_body(inputs)
	return en_demo_narrative_client_quick_exit_body(inputs)
});