/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs */

const en_demo_narrative_deepdive_telephony_relay_body = /** @type {(inputs: Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Phone calls and text messages are the one part of CARE-Y where plaintext has to exist on the server, because a phone number and a message body have to be handed to a phone company in a form it can act on. The relay is where that happens, and it holds plaintext only long enough to forward it and then zeroes every buffer that carried it. [[#telephony #encryption]]
For an outbound text, the user's browser decrypts the reply and posts it with the ticket identifier to a single relay endpoint. The server looks up and decrypts the client's phone number from its own store, never from the request, then hands number and body to the telephony provider and wipes the memory it used. The relay writes nothing, logs no request body, and returns no content in an error response. The browser separately encrypts its own copy and stores that on the case thread, so the readable record of the conversation lives where only the ticket's members can open it. Outbound email follows the same shape through a relay endpoint of its own. An outbound call carries no message body, and the browser submits the user's own callback number, which the server refuses unless it hashes to the number the user verified, while the client's number is resolved server-side the same way. [[#telephony #server-holds]]
Inbound messages follow the same shape in reverse. A text arrives at the provider, the provider posts it to CARE-Y, and the server encrypts the body before writing anything to the database, then wipes the plaintext. CARE-Y then asks the provider to delete its own log of that message, and retries through a job queue if the request fails. [[#telephony #encryption]]
The message was already readable by other people before it arrived. The client's phone carrier saw it. The telephony provider saw it, and holds phone number and delivery metadata under its own retention rules and its own legal obligations regardless of what CARE-Y requests. A subpoena to the provider produces that metadata. It does not produce message content, because CARE-Y's stored copy is encrypted and CARE-Y asked the provider to delete its log. Clients who need the channel itself protected are better served by an encrypted channel in their browser, and [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers those. [What the network sees](#deep-dive/what-the-network-sees) covers the broader picture of what each observer along the path can read. [[#telephony #failure-states #privacy]]
**Why is the relay not part of the main API?** The relay endpoints are raw HTTP handlers rather than tRPC procedures, because the tRPC JSON parser produces JavaScript strings and a string cannot be zeroed. The handlers read the request body as a \`Buffer\`, use it, and call \`.fill(0)\` in \`finally\` blocks on every buffer that touched plaintext. That covers the raw body, the phone number buffer, the message buffer, and the ticket identifier buffer. Authentication uses the same session functions as the rest of the API, called directly, and the endpoints mount under a \`/relay/\` prefix with a maximum body size. [[#telephony #server-holds]]
**What does inbound handling do?** The webhook signature is validated before anything else, in development as well as in production, and a request with a missing or invalid signature is rejected. After validation, the request is deduplicated by provider message identifier. [[#telephony #encryption #failure-states]]
1. The client is resolved or created by blind index on the phone number. [[#telephony #client-data]]
2. The ticket is resolved or created. [[#telephony #client-data]]
3. The body is encrypted under a per-ticket key, and both plaintext and key are zeroed in \`finally\` blocks. [[#telephony #encryption]]
4. When the client has an active encrypted portal channel, a copy of the message is sealed to the channel's public key so that the client's view of the conversation matches the organization's. [[#telephony #portal]]
That portal copy is the one message class on the portal that the server rather than a browser seals. Voicemail audio is fetched from the provider, sealed to the ticket key, stored, and then deleted at the provider. A recording that cannot be routed to a ticket is sealed to the organization key and held in quarantine for an administrator to route by hand. [[#telephony #encryption #portal]]
**Provider boundary.** Provider-specific code sits behind one interface. The interface covers sending messages, placing calls, validating webhooks, and deleting call, message, and recording logs. Twilio is the implemented provider. SignalWire has a validated configuration shape and no provider module, so selecting it is not yet a working path. A mock provider stands in for development and for this handbook. Switching providers is configuration rather than code, and provider credentials live in the operational tier where the server can read them, which is the one tier the server has keys for. [[#telephony #server-holds]]
**The relay, webhook, and provider code.** Relay handlers are \`packages/server/src/routes/relay.ts\`, which mounts one endpoint each for a text, an email, a call, a WebRTC token, a phone lookup, and a consultant verification, with shared parsing and authentication in \`relay-utils.ts\`. [[#telephony #server-holds]]
- Webhook intake is \`packages/server/src/routes/webhooks.ts\`, dispatching to \`packages/server/src/telephony/inbound-sms.ts\`, \`inbound-mms.ts\`, \`inbound-call.ts\`, and \`recording-handler.ts\`. [[#telephony]]
- The provider interface is \`packages/server/src/telephony/provider.ts\` with \`twilio.ts\`, \`provider-http.ts\`, and \`mock-provider.ts\` behind it and \`factory.ts\` selecting one. [[#telephony]]
- Log deletion is \`packages/server/src/jobs/log-deletion.ts\` with helpers in \`telephony/log-deletion-helpers.ts\`. [[#telephony #retention]]
- The automatic reply is selected in \`packages/server/src/telephony/sms-auto-reply.ts\` and sent by \`inbound-sms.ts\` after the follow-up is written. [[#telephony]]
A new relay endpoint uses \`Buffer\` rather than string, logs no bodies, returns no plaintext in errors, and zeroes every buffer in a \`finally\` block. [[#telephony #server-holds]]`)
};

const es_demo_narrative_deepdive_telephony_relay_body = /** @type {(inputs: Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Las llamadas y los mensajes de texto son la única parte de CARE-Y donde el texto plano tiene que existir en el servidor, porque un número de teléfono y el cuerpo de un mensaje tienen que entregarse a una compañía telefónica en una forma sobre la que pueda actuar. El relay es donde eso ocurre, y retiene el texto plano solo el tiempo necesario para reenviarlo y después pone a cero cada búfer que lo transportó. [[#telephony #encryption]]
Para un mensaje de texto saliente, el navegador de la persona usuaria descifra la respuesta y la envía junto con el identificador del ticket a un único endpoint de relay. El servidor busca y descifra el número de teléfono del cliente desde su propio almacén, nunca desde la solicitud, y después entrega número y cuerpo al proveedor de telefonía y borra la memoria que usó. El relay no escribe nada, no registra el cuerpo de la solicitud y no devuelve contenido en una respuesta de error. El navegador cifra por separado su propia copia y la guarda en el hilo del caso, así que el registro legible de la conversación queda donde solo los integrantes del ticket pueden abrirlo. El correo saliente sigue la misma forma a través de un endpoint de relay propio. Una llamada saliente no lleva cuerpo de mensaje, y el navegador envía el número de devolución de llamada de la propia persona usuaria, que el servidor rechaza salvo que su hash coincida con el número que la persona usuaria verificó, mientras que el número del cliente se resuelve en el servidor de la misma manera. [[#telephony #server-holds]]
Los mensajes entrantes siguen la misma forma al revés. Un mensaje de texto llega al proveedor, el proveedor lo publica en CARE-Y, y el servidor cifra el cuerpo antes de escribir nada en la base de datos y después borra el texto plano. CARE-Y pide entonces al proveedor que elimine su propio registro de ese mensaje, y reintenta a través de una cola de tareas si la solicitud falla. [[#telephony #encryption]]
El mensaje ya era legible por otras personas antes de llegar. La compañía telefónica del cliente lo vio. El proveedor de telefonía lo vio, y conserva el número de teléfono y los metadatos de entrega bajo sus propias reglas de retención y sus propias obligaciones legales, independientemente de lo que CARE-Y solicite. Una orden judicial al proveedor produce esos metadatos. No produce el contenido de los mensajes, porque la copia que CARE-Y almacena está cifrada y CARE-Y pidió al proveedor que eliminara su registro. Los clientes que necesitan que el canal mismo esté protegido quedan mejor servidos por un canal cifrado en su navegador, y [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata esos canales. [Lo que ve la red](#deep-dive/what-the-network-sees) trata el panorama más amplio de lo que cada observador a lo largo de la ruta puede leer. [[#telephony #failure-states #privacy]]
**¿Por qué el relay no forma parte de la API principal?** Los endpoints de relay son manejadores HTTP crudos en lugar de procedimientos tRPC, porque el analizador JSON de tRPC produce cadenas JavaScript y una cadena no se puede poner a cero. Los manejadores leen el cuerpo de la solicitud como un \`Buffer\`, lo usan y llaman a \`.fill(0)\` en bloques \`finally\` sobre cada búfer que tocó texto plano. Eso cubre el cuerpo crudo, el búfer del número de teléfono, el búfer del mensaje y el búfer del identificador del ticket. La autenticación usa las mismas funciones de sesión que el resto de la API, llamadas directamente, y los endpoints se montan bajo un prefijo \`/relay/\` con un tamaño máximo de cuerpo. [[#telephony #server-holds]]
**¿Qué hace el manejo de lo entrante?** La firma del webhook se valida antes de cualquier otra cosa, tanto en desarrollo como en producción, y una solicitud con firma ausente o inválida se rechaza. Tras la validación, la solicitud se deduplica por identificador de mensaje del proveedor. [[#telephony #encryption #failure-states]]
1. Se resuelve o se crea el cliente mediante el índice ciego del número de teléfono. [[#telephony #client-data]]
2. Se resuelve o se crea el ticket. [[#telephony #client-data]]
3. El cuerpo se cifra con una clave por ticket, y tanto el texto plano como la clave se ponen a cero en bloques \`finally\`. [[#telephony #encryption]]
4. Cuando el cliente tiene un canal del portal cifrado activo, una copia del mensaje se sella con la clave pública del canal para que la vista de la conversación que tiene el cliente coincida con la de la organización. [[#telephony #portal]]
Esa copia del portal es la única clase de mensaje del portal que sella el servidor en lugar de un navegador. El audio de los correos de voz se obtiene del proveedor, se sella con la clave del ticket, se almacena y después se elimina en el proveedor. Una grabación que no se puede encaminar a un ticket se sella con la clave de la organización y se retiene en cuarentena para que la encamine una persona administradora. [[#telephony #encryption #portal]]
**Frontera con el proveedor.** El código específico del proveedor está detrás de una única interfaz. La interfaz cubre el envío de mensajes, la realización de llamadas, la validación de webhooks y la eliminación de registros de llamadas, mensajes y grabaciones. Twilio es el proveedor implementado. SignalWire tiene una forma de configuración validada y ningún módulo de proveedor, así que seleccionarlo aún no es un camino que funcione. Un proveedor simulado hace de sustituto para el desarrollo y para este manual. Cambiar de proveedor es configuración y no código, y las credenciales del proveedor viven en el nivel operativo donde el servidor puede leerlas, que es el único nivel para el que el servidor tiene claves. [[#telephony #server-holds]]
**El relay, los webhooks y el código del proveedor.** Los manejadores de relay son \`packages/server/src/routes/relay.ts\`, que monta un endpoint para cada cosa: un mensaje de texto, un correo, una llamada, un token de WebRTC, una consulta de número y una verificación de la persona consultora, con el análisis y la autenticación compartidos en \`relay-utils.ts\`. [[#telephony #server-holds]]
- La recepción de webhooks es \`packages/server/src/routes/webhooks.ts\`, que despacha a \`packages/server/src/telephony/inbound-sms.ts\`, \`inbound-mms.ts\`, \`inbound-call.ts\` y \`recording-handler.ts\`. [[#telephony]]
- La interfaz del proveedor es \`packages/server/src/telephony/provider.ts\` con \`twilio.ts\`, \`provider-http.ts\` y \`mock-provider.ts\` detrás de ella y \`factory.ts\` seleccionando uno. [[#telephony]]
- La eliminación de registros es \`packages/server/src/jobs/log-deletion.ts\` con ayudantes en \`telephony/log-deletion-helpers.ts\`. [[#telephony #retention]]
- La respuesta automática se selecciona en \`packages/server/src/telephony/sms-auto-reply.ts\` y se envía desde \`inbound-sms.ts\` tras escribir el follow-up. [[#telephony]]
Un nuevo endpoint de relay usa \`Buffer\` en lugar de cadena, no registra los cuerpos, no devuelve texto plano en los errores y pone a cero cada búfer en un bloque \`finally\`. [[#telephony #server-holds]]`)
};

const en_xa2_demo_narrative_deepdive_telephony_relay_body = /** @type {(inputs: Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Phònè càlls ànd tèxt mèssàgès àrè thè ònè pàrt òf CÀRÈ-Y whèrè plàìntèxt hàs tò èxìst òn thè sèrvèr, bècàùsè à phònè nùmbèr ànd à mèssàgè bòdy hàvè tò bè hàndèd tò à phònè còmpàny ìn à fòrm ìt càn àct òn. Thè rèlày ìs whèrè thàt hàppèns, ànd ìt hòlds plàìntèxt ònly lòng ènòùgh tò fòrwàrd ìt ànd thèn zèròès èvèry bùffèr thàt càrrìèd ìt. [[#tèlèphòny #èncryptìòn]]
Fòr àn òùtbòùnd tèxt, thè ùsèr's bròwsèr dècrypts thè rèply ànd pòsts ìt wìth thè tìckèt ìdèntìfìèr tò à sìnglè rèlày èndpòìnt. Thè sèrvèr lòòks ùp ànd dècrypts thè clìènt's phònè nùmbèr fròm ìts òwn stòrè, nèvèr fròm thè rèqùèst, thèn hànds nùmbèr ànd bòdy tò thè tèlèphòny pròvìdèr ànd wìpès thè mèmòry ìt ùsèd. Thè rèlày wrìtès nòthìng, lògs nò rèqùèst bòdy, ànd rètùrns nò còntènt ìn àn èrròr rèspònsè. Thè bròwsèr sèpàràtèly èncrypts ìts òwn còpy ànd stòrès thàt òn thè càsè thrèàd, sò thè rèàdàblè rècòrd òf thè cònvèrsàtìòn lìvès whèrè ònly thè tìckèt's mèmbèrs càn òpèn ìt. Òùtbòùnd èmàìl fòllòws thè sàmè shàpè thròùgh à rèlày èndpòìnt òf ìts òwn. Àn òùtbòùnd càll càrrìès nò mèssàgè bòdy, ànd thè bròwsèr sùbmìts thè ùsèr's òwn càllbàck nùmbèr, whìch thè sèrvèr rèfùsès ùnlèss ìt hàshès tò thè nùmbèr thè ùsèr vèrìfìèd, whìlè thè clìènt's nùmbèr ìs rèsòlvèd sèrvèr-sìdè thè sàmè wày. [[#tèlèphòny #sèrvèr-hòlds]]
Ìnbòùnd mèssàgès fòllòw thè sàmè shàpè ìn rèvèrsè. À tèxt àrrìvès àt thè pròvìdèr, thè pròvìdèr pòsts ìt tò CÀRÈ-Y, ànd thè sèrvèr èncrypts thè bòdy bèfòrè wrìtìng ànythìng tò thè dàtàbàsè, thèn wìpès thè plàìntèxt. CÀRÈ-Y thèn àsks thè pròvìdèr tò dèlètè ìts òwn lòg òf thàt mèssàgè, ànd rètrìès thròùgh à jòb qùèùè ìf thè rèqùèst fàìls. [[#tèlèphòny #èncryptìòn]]
Thè mèssàgè wàs àlrèàdy rèàdàblè by òthèr pèòplè bèfòrè ìt àrrìvèd. Thè clìènt's phònè càrrìèr sàw ìt. Thè tèlèphòny pròvìdèr sàw ìt, ànd hòlds phònè nùmbèr ànd dèlìvèry mètàdàtà ùndèr ìts òwn rètèntìòn rùlès ànd ìts òwn lègàl òblìgàtìòns règàrdlèss òf whàt CÀRÈ-Y rèqùèsts. À sùbpòènà tò thè pròvìdèr pròdùcès thàt mètàdàtà. Ìt dòès nòt pròdùcè mèssàgè còntènt, bècàùsè CÀRÈ-Y's stòrèd còpy ìs èncryptèd ànd CÀRÈ-Y àskèd thè pròvìdèr tò dèlètè ìts lòg. Clìènts whò nèèd thè chànnèl ìtsèlf pròtèctèd àrè bèttèr sèrvèd by àn èncryptèd chànnèl ìn thèìr bròwsèr, ànd [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thòsè. [Whàt thè nètwòrk sèès](#dèèp-dìvè/whàt-thè-nètwòrk-sèès) còvèrs thè bròàdèr pìctùrè òf whàt èàch òbsèrvèr àlòng thè pàth càn rèàd. [[#tèlèphòny #fàìlùrè-stàtès #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why ìs thè rèlày nòt pàrt òf thè màìn ÀPÌ? •••••••••••••** Thè rèlày èndpòìnts àrè ràw HTTP hàndlèrs ràthèr thàn tRPC pròcèdùrès, bècàùsè thè tRPC JSÒN pàrsèr pròdùcès JàvàScrìpt strìngs ànd à strìng cànnòt bè zèròèd. Thè hàndlèrs rèàd thè rèqùèst bòdy às à \`Bùffèr\`, ùsè ìt, ànd càll \`.fìll(0)\` ìn \`fìnàlly\` blòcks òn èvèry bùffèr thàt tòùchèd plàìntèxt. Thàt còvèrs thè ràw bòdy, thè phònè nùmbèr bùffèr, thè mèssàgè bùffèr, ànd thè tìckèt ìdèntìfìèr bùffèr. Àùthèntìcàtìòn ùsès thè sàmè sèssìòn fùnctìòns às thè rèst òf thè ÀPÌ, càllèd dìrèctly, ànd thè èndpòìnts mòùnt ùndèr à \`/rèlày/\` prèfìx wìth à màxìmùm bòdy sìzè. [[#tèlèphòny #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès ìnbòùnd hàndlìng dò? •••••••••** Thè wèbhòòk sìgnàtùrè ìs vàlìdàtèd bèfòrè ànythìng èlsè, ìn dèvèlòpmènt às wèll às ìn pròdùctìòn, ànd à rèqùèst wìth à mìssìng òr ìnvàlìd sìgnàtùrè ìs rèjèctèd. Àftèr vàlìdàtìòn, thè rèqùèst ìs dèdùplìcàtèd by pròvìdèr mèssàgè ìdèntìfìèr. [[#tèlèphòny #èncryptìòn #fàìlùrè-stàtès]]
1. Thè clìènt ìs rèsòlvèd òr crèàtèd by blìnd ìndèx òn thè phònè nùmbèr. [[#tèlèphòny #clìènt-dàtà]]
2. Thè tìckèt ìs rèsòlvèd òr crèàtèd. [[#tèlèphòny #clìènt-dàtà]]
3. Thè bòdy ìs èncryptèd ùndèr à pèr-tìckèt kèy, ànd bòth plàìntèxt ànd kèy àrè zèròèd ìn \`fìnàlly\` blòcks. [[#tèlèphòny #èncryptìòn]]
4. Whèn thè clìènt hàs àn àctìvè èncryptèd pòrtàl chànnèl, à còpy òf thè mèssàgè ìs sèàlèd tò thè chànnèl's pùblìc kèy sò thàt thè clìènt's vìèw òf thè cònvèrsàtìòn màtchès thè òrgànìzàtìòn's. [[#tèlèphòny #pòrtàl]]
Thàt pòrtàl còpy ìs thè ònè mèssàgè clàss òn thè pòrtàl thàt thè sèrvèr ràthèr thàn à bròwsèr sèàls. Vòìcèmàìl àùdìò ìs fètchèd fròm thè pròvìdèr, sèàlèd tò thè tìckèt kèy, stòrèd, ànd thèn dèlètèd àt thè pròvìdèr. À rècòrdìng thàt cànnòt bè ròùtèd tò à tìckèt ìs sèàlèd tò thè òrgànìzàtìòn kèy ànd hèld ìn qùàràntìnè fòr àn àdmìnìstràtòr tò ròùtè by hànd. [[#tèlèphòny #èncryptìòn #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pròvìdèr bòùndàry. ••••••** Pròvìdèr-spècìfìc còdè sìts bèhìnd ònè ìntèrfàcè. Thè ìntèrfàcè còvèrs sèndìng mèssàgès, plàcìng càlls, vàlìdàtìng wèbhòòks, ànd dèlètìng càll, mèssàgè, ànd rècòrdìng lògs. Twìlìò ìs thè ìmplèmèntèd pròvìdèr. SìgnàlWìrè hàs à vàlìdàtèd cònfìgùràtìòn shàpè ànd nò pròvìdèr mòdùlè, sò sèlèctìng ìt ìs nòt yèt à wòrkìng pàth. À mòck pròvìdèr stànds ìn fòr dèvèlòpmènt ànd fòr thìs hàndbòòk. Swìtchìng pròvìdèrs ìs cònfìgùràtìòn ràthèr thàn còdè, ànd pròvìdèr crèdèntìàls lìvè ìn thè òpèràtìònàl tìèr whèrè thè sèrvèr càn rèàd thèm, whìch ìs thè ònè tìèr thè sèrvèr hàs kèys fòr. [[#tèlèphòny #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rèlày, wèbhòòk, ànd pròvìdèr còdè. ••••••••••••** Rèlày hàndlèrs àrè \`pàckàgès/sèrvèr/src/ròùtès/rèlày.ts\`, whìch mòùnts ònè èndpòìnt èàch fòr à tèxt, àn èmàìl, à càll, à WèbRTC tòkèn, à phònè lòòkùp, ànd à cònsùltànt vèrìfìcàtìòn, wìth shàrèd pàrsìng ànd àùthèntìcàtìòn ìn \`rèlày-ùtìls.ts\`. [[#tèlèphòny #sèrvèr-hòlds]]
- Wèbhòòk ìntàkè ìs \`pàckàgès/sèrvèr/src/ròùtès/wèbhòòks.ts\`, dìspàtchìng tò \`pàckàgès/sèrvèr/src/tèlèphòny/ìnbòùnd-sms.ts\`, \`ìnbòùnd-mms.ts\`, \`ìnbòùnd-càll.ts\`, ànd \`rècòrdìng-hàndlèr.ts\`. [[#tèlèphòny]]
- Thè pròvìdèr ìntèrfàcè ìs \`pàckàgès/sèrvèr/src/tèlèphòny/pròvìdèr.ts\` wìth \`twìlìò.ts\`, \`pròvìdèr-http.ts\`, ànd \`mòck-pròvìdèr.ts\` bèhìnd ìt ànd \`fàctòry.ts\` sèlèctìng ònè. [[#tèlèphòny]]
- Lòg dèlètìòn ìs \`pàckàgès/sèrvèr/src/jòbs/lòg-dèlètìòn.ts\` wìth hèlpèrs ìn \`tèlèphòny/lòg-dèlètìòn-hèlpèrs.ts\`. [[#tèlèphòny #rètèntìòn]]
- Thè àùtòmàtìc rèply ìs sèlèctèd ìn \`pàckàgès/sèrvèr/src/tèlèphòny/sms-àùtò-rèply.ts\` ànd sènt by \`ìnbòùnd-sms.ts\` àftèr thè fòllòw-ùp ìs wrìttèn. [[#tèlèphòny]]
À nèw rèlày èndpòìnt ùsès \`Bùffèr\` ràthèr thàn strìng, lògs nò bòdìès, rètùrns nò plàìntèxt ìn èrròrs, ànd zèròès èvèry bùffèr ìn à \`fìnàlly\` blòck. [[#tèlèphòny #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Phone calls and text messages are the one part of CARE-Y where plaintext has to exist on the server, because a phone number and a message body have to be han..." |
*
* @param {Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_telephony_relay_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Telephony_Relay_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_telephony_relay_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_telephony_relay_body(inputs)
	return en_demo_narrative_deepdive_telephony_relay_body(inputs)
});