/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Fund_Balances_BodyInputs */

const en_demo_narrative_topic_fund_balances_body = /** @type {(inputs: Demo_Narrative_Topic_Fund_Balances_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The case panel shows the fund mapped to the case's queue, with the fund's name and its available balance. A case in a queue with no fund mapping shows no fund line and offers no disbursement action. The balance is what volunteers have recorded through disbursements and adjustments, not a bank account figure. Dashboard queue cards show the same balance for each queue that carries a fund. [[#client-data #encryption]]
**How does the balance reach the browser?** Each fund's running balance is stored on the server as organization-key ciphertext. The browser decrypts it after fetching the fund list and holds the result in a shared cache. A balance refreshes after any write in the current session and after any other session records a fund entry. [How encryption works](#deep-dive/how-encryption-works) covers the organization key. [[#encryption #keys]]
**How is the queue mapped to a fund?** Each queue's fund reference is an organization-key ciphertext column on the queue row. The server stores the bytes and cannot read which fund a queue draws on. Whether a queue has a fund mapped is visible to the server, because the column is null when unmapped. The mapping is set in the queue editor on the People page, and requires the Manage queues and View funds permissions together. [Queue management](#admin-people/queues) covers the editor. [[#encryption #server-holds #metadata]]
**Below-zero balances.** Disbursements are accepted even when the result would take a fund below zero. The disbursement sheet shows an inline warning for as long as the entered amount would produce a negative balance, but it does not block the write. [[#failure-states]]
**Who can see fund balances?** The View funds permission controls access to fund names and balances, and is held by Volunteer and above by default. Manage funds and Audit funds both include it. Without View funds the balance line on the case panel, the balance on each queue card, and the disbursement action are all hidden, and the server rejects the underlying request. [The permission system](#deep-dive/the-permission-system) covers how grants work. [[#permissions]]
**The fund store.** All fund surfaces read from a single TanStack Query cache built by \`createFundStore\` in \`packages/client/src/lib/funds/fund-store.svelte.ts\`, queried under \`fundKeys.list()\` and invalidated at the \`fundKeys.all\` scope after every write and after a server-sent fund-changed event. \`createCaseFund\` in the same module looks up the queue's decrypted fund reference in that cache and exposes the resolved fund to the case panel. [[#client-data]]`)
};

const es_demo_narrative_topic_fund_balances_body = /** @type {(inputs: Demo_Narrative_Topic_Fund_Balances_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El panel del caso muestra el fondo asignado a la cola del caso, con su nombre y el saldo disponible. Un caso en una cola sin fondo asignado no muestra línea de fondo ni ofrece la acción de desembolso. El saldo refleja lo que se ha registrado a través de desembolsos y ajustes, no el saldo de una cuenta bancaria. Las tarjetas de cola en el panel principal muestran el mismo saldo en cada cola que tiene un fondo. [[#client-data #encryption]]
**¿Cómo llega el saldo al navegador?** El saldo acumulado de cada fondo se almacena en el servidor como texto cifrado con la clave de la organización. El navegador lo descifra tras obtener la lista de fondos y conserva el resultado en una caché compartida. Un saldo se actualiza tras cualquier escritura en la sesión activa y cuando otra sesión registra una entrada de fondo. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) explica la clave de la organización. [[#encryption #keys]]
**¿Cómo se asigna un fondo a una cola?** La columna de fondo en cada fila de cola almacena texto cifrado con la clave de la organización. El servidor guarda los bytes y no puede leer qué fondo corresponde a cada cola. La existencia de una asignación sí es visible para el servidor, porque la columna es nula cuando no hay fondo. La asignación se configura en el editor de colas de la página Personas y requiere los permisos Manage queues y View funds a la vez. [Gestión de colas](#admin-people/queues) trata el editor. [[#encryption #server-holds #metadata]]
**Saldos negativos.** Los desembolsos se aceptan incluso cuando el resultado dejaría el fondo por debajo de cero. La hoja de desembolso muestra un aviso en línea mientras el monto ingresado produciría un saldo negativo, pero no impide la escritura. [[#failure-states]]
**¿Quién puede ver los saldos de fondos?** El permiso View funds controla el acceso a nombres y saldos de fondos, y lo tienen Volunteer y superiores de forma predeterminada. Manage funds y Audit funds lo incluyen. Sin View funds, la línea de saldo en el panel del caso, el saldo en la tarjeta de cola y el desembolso quedan ocultos, y el servidor rechaza la solicitud subyacente. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se otorgan. [[#permissions]]
**El almacén de fondos.** Todas las superficies de fondos leen de una sola caché TanStack Query construida por \`createFundStore\` en \`packages/client/src/lib/funds/fund-store.svelte.ts\`, consultada con \`fundKeys.list()\` e invalidada en el ámbito \`fundKeys.all\` tras cada escritura y tras un evento del servidor que señala un cambio en fondos. \`createCaseFund\` en el mismo módulo busca la referencia descifrada de la cola en esa caché y expone el fondo resultante al panel del caso. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_fund_balances_body = /** @type {(inputs: Demo_Narrative_Topic_Fund_Balances_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè càsè pànèl shòws thè fùnd màppèd tò thè càsè's qùèùè, wìth thè fùnd's nàmè ànd ìts àvàìlàblè bàlàncè. À càsè ìn à qùèùè wìth nò fùnd màppìng shòws nò fùnd lìnè ànd òffèrs nò dìsbùrsèmènt àctìòn. Thè bàlàncè ìs whàt vòlùntèèrs hàvè rècòrdèd thròùgh dìsbùrsèmènts ànd àdjùstmènts, nòt à bànk àccòùnt fìgùrè. Dàshbòàrd qùèùè càrds shòw thè sàmè bàlàncè fòr èàch qùèùè thàt càrrìès à fùnd. [[#clìènt-dàtà #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè bàlàncè rèàch thè bròwsèr? ••••••••••••** Èàch fùnd's rùnnìng bàlàncè ìs stòrèd òn thè sèrvèr às òrgànìzàtìòn-kèy cìphèrtèxt. Thè bròwsèr dècrypts ìt àftèr fètchìng thè fùnd lìst ànd hòlds thè rèsùlt ìn à shàrèd càchè. À bàlàncè rèfrèshès àftèr àny wrìtè ìn thè cùrrènt sèssìòn ànd àftèr àny òthèr sèssìòn rècòrds à fùnd èntry. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè òrgànìzàtìòn kèy. [[#èncryptìòn #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìs thè qùèùè màppèd tò à fùnd? •••••••••••** Èàch qùèùè's fùnd rèfèrèncè ìs àn òrgànìzàtìòn-kèy cìphèrtèxt còlùmn òn thè qùèùè ròw. Thè sèrvèr stòrès thè bytès ànd cànnòt rèàd whìch fùnd à qùèùè dràws òn. Whèthèr à qùèùè hàs à fùnd màppèd ìs vìsìblè tò thè sèrvèr, bècàùsè thè còlùmn ìs nùll whèn ùnmàppèd. Thè màppìng ìs sèt ìn thè qùèùè èdìtòr òn thè Pèòplè pàgè, ànd rèqùìrès thè Mànàgè qùèùès ànd Vìèw fùnds pèrmìssìòns tògèthèr. [Qùèùè mànàgèmènt](#àdmìn-pèòplè/qùèùès) còvèrs thè èdìtòr. [[#èncryptìòn #sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Bèlòw-zèrò bàlàncès. ••••••** Dìsbùrsèmènts àrè àccèptèd èvèn whèn thè rèsùlt wòùld tàkè à fùnd bèlòw zèrò. Thè dìsbùrsèmènt shèèt shòws àn ìnlìnè wàrnìng fòr às lòng às thè èntèrèd àmòùnt wòùld pròdùcè à nègàtìvè bàlàncè, bùt ìt dòès nòt blòck thè wrìtè. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn sèè fùnd bàlàncès? ••••••••** Thè Vìèw fùnds pèrmìssìòn còntròls àccèss tò fùnd nàmès ànd bàlàncès, ànd ìs hèld by Vòlùntèèr ànd àbòvè by dèfàùlt. Mànàgè fùnds ànd Àùdìt fùnds bòth ìnclùdè ìt. Wìthòùt Vìèw fùnds thè bàlàncè lìnè òn thè càsè pànèl, thè bàlàncè òn èàch qùèùè càrd, ànd thè dìsbùrsèmènt àctìòn àrè àll hìddèn, ànd thè sèrvèr rèjècts thè ùndèrlyìng rèqùèst. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw grànts wòrk. [[#pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè fùnd stòrè. •••••** Àll fùnd sùrfàcès rèàd fròm à sìnglè TànStàck Qùèry càchè bùìlt by \`crèàtèFùndStòrè\` ìn \`pàckàgès/clìènt/src/lìb/fùnds/fùnd-stòrè.svèltè.ts\`, qùèrìèd ùndèr \`fùndKèys.lìst()\` ànd ìnvàlìdàtèd àt thè \`fùndKèys.àll\` scòpè àftèr èvèry wrìtè ànd àftèr à sèrvèr-sènt fùnd-chàngèd èvènt. \`crèàtèCàsèFùnd\` ìn thè sàmè mòdùlè lòòks ùp thè qùèùè's dècryptèd fùnd rèfèrèncè ìn thàt càchè ànd èxpòsès thè rèsòlvèd fùnd tò thè càsè pànèl. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The case panel shows the fund mapped to the case's queue, with the fund's name and its available balance. A case in a queue with no fund mapping shows no fun..." |
*
* @param {Demo_Narrative_Topic_Fund_Balances_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_fund_balances_body = /** @type {((inputs?: Demo_Narrative_Topic_Fund_Balances_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Fund_Balances_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_fund_balances_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_fund_balances_body(inputs)
	return en_demo_narrative_topic_fund_balances_body(inputs)
});