/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Key_Derivation_BodyInputs */

const en_demo_narrative_topic_key_derivation_body = /** @type {(inputs: Demo_Narrative_Topic_Key_Derivation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The browser stretches the password with Argon2id over 64 MB of memory and four passes before any of it becomes key material. That cost is what the rest of the derivation consumes, and it is what makes each guess expensive for anyone running passwords offline against a stolen database. [[#keys #encryption]]
**Argon2id and the floor.** The cost parameters have a minimum compiled into the browser's own code, and a value the server suggests is taken only when it is higher. A server that has been taken over can make the derivation slower and cannot make it cheaper. The salt comes from the server per account, and a request for an account that does not exist is answered with a deterministic fake salt that a caller cannot tell from a real one. [Username and password](#login/credentials) covers the part of the password that does go to the server. [[#keys #server-holds]]
**The two shares.** The stretched material does not leave the browser. What leaves is a blinded value answered by two independent evaluators, neither of which learns the password, the stretched input, the final output or what the other contributed, and each of which holds one share of a key that exists in one piece nowhere. [How keys are derived](#deep-dive/how-keys-are-derived) covers the protocol and the key hierarchy its answer feeds. [[#keys #encryption]]
**Where the two shares actually run.** Each evaluator is a privilege-dropped process holding its share in locked, read-only memory, and the two sit on hosts in different legal jurisdictions, one in the EU and one in Iceland, joined by mutually authenticated TLS rather than a local socket. An order served in one country reaches at most one of them, and both shares are re-randomized every twenty-four hours, so a share copied in one period is incompatible with its counterpart in the next. [[#trust-boundary #keys]]
**What the browser ends up with.** The combined output is expanded into a personal keypair and into the key that unwraps the organization's shared key, each under its own label so that neither can be derived from the other. Until all of that has finished, the tab holds nothing that can decrypt a case. [[#encryption #keys]]
**What an attacker would need.** Both evaluator shares, the account's password, and the account's second factor, because the derivation starts only after the second factor has been accepted. A database dump on its own yields no key material, since nothing derived from the password is stored anywhere. [The trust boundary](#deep-dive/the-trust-boundary) covers what a dump does yield. [[#trust-boundary #server-holds]]
**The derivation path in code.** The browser pipeline is \`packages/client/src/lib/auth/login-crypto.ts\` running inside \`packages/client/src/lib/workers/crypto.worker.ts\`. The primitives are \`packages/crypto/src/derive.ts\` and \`packages/crypto/src/oprf.ts\`. The evaluator processes are \`packages/server/src/crypto/oprf-process.ts\` and \`oprf-server.ts\`, reached through \`oprf-ipc.ts\`, with rate limiting and proof-of-work gating in \`oprf-evaluate-service.ts\`. [[#keys #server-holds]]`)
};

const es_demo_narrative_topic_key_derivation_body = /** @type {(inputs: Demo_Narrative_Topic_Key_Derivation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El navegador estira la contraseña con Argon2id sobre 64 MB de memoria y cuatro pasadas antes de que nada de ella se convierta en material de claves. Ese resultado estirado es lo que consume el resto de la derivación, y su coste es lo que encarece cada intento para quien pruebe contraseñas sin conexión contra una base de datos robada. [[#keys #encryption]]
**Argon2id y el mínimo obligatorio.** Los parámetros de coste tienen un mínimo compilado en el código del propio navegador, y un valor propuesto por el servidor solo se toma cuando es mayor. Un servidor tomado por un atacante puede hacer la derivación más lenta y no puede abaratarla. La sal la entrega el servidor por cuenta, y una petición para una cuenta inexistente se responde con una sal falsa determinista que quien la pide no puede distinguir de una real. [Nombre de usuario y contraseña](#login/credentials) trata la parte de la contraseña que sí va al servidor. [[#keys #server-holds]]
**Las dos partes.** El material estirado no sale del navegador. Lo que sale es un valor cegado que responden dos evaluadores independientes, ninguno de los cuales llega a conocer la contraseña, la entrada estirada, la salida final ni lo que aportó el otro, y cada uno de los cuales guarda una parte de una clave que no existe entera en ningún sitio. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata el protocolo y la jerarquía de claves que alimenta su respuesta. [[#keys #encryption]]
**Dónde se ejecutan realmente las dos partes.** Cada evaluador es un proceso con privilegios rebajados que guarda su parte en memoria bloqueada y de solo lectura, y los dos están en equipos situados en jurisdicciones legales distintas, uno en la Unión Europea y otro en Islandia, unidos por TLS con autenticación mutua en lugar de un socket local. Una orden dictada en un solo país alcanza como mucho a uno de ellos, y ambas partes se vuelven a aleatorizar cada veinticuatro horas, de modo que una parte copiada en un periodo es incompatible con su homóloga en el siguiente. [[#trust-boundary #keys]]
**Con qué se queda el navegador.** La salida combinada se expande en un par de claves personal y en la clave que desenvuelve la clave compartida de la organización, cada una bajo su propia etiqueta para que ninguna pueda derivarse de la otra. Hasta que todo eso termina, la pestaña no contiene nada capaz de descifrar un caso. [[#encryption #keys]]
**Lo que necesitaría un atacante.** Las dos partes de los evaluadores, la contraseña de la cuenta y su segundo factor, porque la derivación solo empieza cuando el segundo factor se ha aceptado. Un volcado de la base de datos por sí solo no aporta material de claves, ya que nada derivado de la contraseña se almacena en ninguna parte. [La frontera de confianza](#deep-dive/the-trust-boundary) trata lo que sí aporta un volcado. [[#trust-boundary #server-holds]]
**La ruta de derivación en el código.** La secuencia del navegador es \`packages/client/src/lib/auth/login-crypto.ts\`, ejecutada dentro de \`packages/client/src/lib/workers/crypto.worker.ts\`. Las primitivas son \`packages/crypto/src/derive.ts\` y \`packages/crypto/src/oprf.ts\`. Los procesos evaluadores son \`packages/server/src/crypto/oprf-process.ts\` y \`oprf-server.ts\`, alcanzados a través de \`oprf-ipc.ts\`, con la limitación de tasa y la exigencia de prueba de trabajo en \`oprf-evaluate-service.ts\`. [[#keys #server-holds]]`)
};

const en_xa2_demo_narrative_topic_key_derivation_body = /** @type {(inputs: Demo_Narrative_Topic_Key_Derivation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè pàsswòrd ìs thè stàrtìng pòìnt, bùt ìt ìs nòt thè kèy. Thè bròwsèr rùns àn Àrgòn2ìd dèrìvàtìòn (tùnèd tò ùsè 64 MB òf mèmòry àcròss fòùr pàssès) tò trànsfòrm thè pàsswòrd ìntò ràw kèy màtèrìàl. Thìs dèrìvàtìòn hàppèns èntìrèly ìn thè bròwsèr, ànd thè sèrvèr nèvèr sèès ìts ìnpùt òr òùtpùt.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìt wòrks. ••••** Thè dèrìvèd màtèrìàl thèn pàssès thròùgh à thrèshòld pròtòcòl ìnvòlvìng twò sèrvèrs lòcàtèd ìn sèpàràtè lègàl jùrìsdìctìòns. Thè bròwsèr blìnds ìts ìnpùt bèfòrè sèndìng ìt, ànd ùnblìnds thè rèsùlt àftèr bòth sèrvèrs rèspònd. Nèìthèr sèrvèr sèès thè pàsswòrd, thè dèrìvèd kèy, òr whàt thè òthèr sèrvèr còntrìbùtèd. Èàch sèrvèr hòlds ònè shàrè, ànd à sìnglè shàrè ìs màthèmàtìcàlly ùsèlèss òn ìts òwn.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èncryptìòn. ••••** Thè còmbìnèd òùtpùt pròdùcès à pèrsònàl kèypàìr ànd thè kèy thàt ùnwràps thè òrgànìzàtìòn's shàrèd èncryptìòn kèy. Ònly àftèr thìs pròcèss còmplètès càn thè bròwsèr dècrypt càsè dàtà.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Prìvàcy. •••** Thìs dèsìgn mèàns thàt còmpròmìsìng ònè sèrvèr, òr còmpèllìng dìsclòsùrè ìn ònè jùrìsdìctìòn, yìèlds nòthìng. Àn àttàckèr wòùld nèèd bòth sèrvèrs, àccèss ìn bòth lègàl jùrìsdìctìòns, thè pàsswòrd, ànd thè sècònd fàctòr. Shàrès àrè rèfrèshèd dàìly, sò à càptùrèd shàrè èxpìrès èvèn ìf nèvèr dètèctèd. ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The browser stretches the password with Argon2id over 64 MB of memory and four passes before any of it becomes key material. That cost is what the rest of th..." |
*
* @param {Demo_Narrative_Topic_Key_Derivation_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_key_derivation_body = /** @type {((inputs?: Demo_Narrative_Topic_Key_Derivation_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Key_Derivation_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_key_derivation_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_key_derivation_body(inputs)
	return en_demo_narrative_topic_key_derivation_body(inputs)
});