/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Quarantine_BodyInputs */

const en_demo_narrative_admin_quarantine_body = /** @type {(inputs: Demo_Narrative_Admin_Quarantine_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A voicemail the system cannot attach to a ticket is sealed with the organization key and held in quarantine for manual routing. The system does not store the recording in the open and does not discard it. A voicemail enters quarantine when the call tracker has no record of the call, when no intake queue is configured, or when the caller cannot be resolved to a client. [[#telephony #failure-states]]
**How is the recording sealed?** The server downloads the audio from the provider and seals it with the organization key. It writes the ciphertext to blob storage and then asks the provider to delete both the recording and the call log. The caller's number and the number called are captured and sealed for voicemails quarantined because of a tracker miss or an unresolved client; a voicemail quarantined because no intake queue exists has neither number recorded. The audio exists in plaintext in server memory only during the sealing call, in a buffer the code zeroes. A provider deletion that fails on the first attempt is enqueued for retry. [The telephony relay](#deep-dive/the-telephony-relay) covers the same buffer handling during a normal call. [[#encryption #privacy]]
**Routing and dismissal.** The browser decrypts the sealed audio locally, so listening to a quarantined voicemail is the only way to learn who called when the number did not resolve. The browser re-seals the audio under the ticket's key for each recipient, and the server receives only ciphertext. The sealed original is deleted after the follow-up is created. When two users route the same voicemail, the first write settles it and the second receives a conflict error. Dismissing a voicemail deletes its audio permanently. [Voicemails](#ticket-detail/voicemails) covers the recording after it reaches a ticket. [[#keys]]
**What does a database dump reveal?** The reason, the status, the duration, and the timestamps are plaintext columns. The caller's number and the number called are ciphertext. A dump shows how many voicemails an organization failed to route and when each one arrived, but not who called. Arrivals, routing decisions, and dismissals are written to the audit log. [Audit log](#admin-logs/audit) covers that record. [[#server-holds #metadata]]
**The quarantine service and its notification.** \`packages/server/src/telephony/voicemail-quarantine.ts\` runs the seal, store, audit, and cleanup path. A duplicate webhook delivery is absorbed by the unique recording identifier rather than creating a second row. The arrival notification is sent to every user holding the Manage voicemail quarantine permission. Reviewing, routing, and dismissing all require the same permission. [The permission system](#deep-dive/the-permission-system) covers how permissions are granted. [[#permissions]]`)
};

const es_demo_narrative_admin_quarantine_body = /** @type {(inputs: Demo_Narrative_Admin_Quarantine_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un mensaje de voz que el sistema no puede vincular a un ticket se sella con la clave de la organización y se retiene en cuarentena para enrutamiento manual. El sistema no almacena la grabación sin cifrar y no la descarta. Un mensaje de voz entra en cuarentena cuando el rastreador de llamadas no tiene registro de la llamada, cuando no hay cola de admisión configurada, o cuando no se puede resolver al llamante como cliente. [[#telephony #failure-states]]
**¿Cómo se sella la grabación?** El servidor descarga el audio del proveedor y lo sella con la clave de la organización. Escribe el texto cifrado en almacenamiento de blobs y pide al proveedor que elimine tanto la grabación como el registro de llamada. El número del llamante y el número llamado se capturan y se sellan en los mensajes de voz en cuarentena por fallo del rastreador o por un cliente no resuelto; un mensaje de voz en cuarentena porque no existe cola de admisión no registra ninguno de los dos números. El audio existe en texto plano en la memoria del servidor solo durante la llamada de sellado, en un buffer que el código pone a cero. Una eliminación del proveedor que falla en el primer intento se encola para reintento. [El relay de telefonía](#deep-dive/the-telephony-relay) trata el mismo manejo de buffers durante una llamada normal. [[#encryption #privacy]]
**Enrutamiento y descarte.** El navegador descifra el audio sellado localmente, así que escuchar un mensaje de voz en cuarentena es la única forma de saber quién llamó cuando el número no pudo resolverse. El navegador resella el audio con la clave del ticket para cada destinatario, y el servidor recibe solo texto cifrado. El original sellado se elimina después de crear el seguimiento. Cuando dos personas usuarias enrutan el mismo mensaje de voz, la primera escritura lo resuelve y la segunda recibe un error de conflicto. Descartar un mensaje de voz elimina su audio permanentemente. [Mensajes de voz](#ticket-detail/voicemails) trata la grabación después de que llega a un ticket. [[#keys]]
**¿Qué revela un volcado de la base de datos?** La razón, el estado, la duración y las marcas de tiempo son columnas en texto plano. El número del llamante y el número llamado son texto cifrado. Un volcado muestra cuántos mensajes de voz una organización no pudo enrutar y cuándo llegó cada uno, pero no quién llamó. Las llegadas, las decisiones de enrutamiento y los descartes se escriben en el registro de auditoría. [Registro de auditoría](#admin-logs/audit) trata ese registro. [[#server-holds #metadata]]
**El servicio de cuarentena y su notificación.** \`packages/server/src/telephony/voicemail-quarantine.ts\` ejecuta la ruta de sellado, almacenamiento, auditoría y limpieza. Una entrega duplicada de webhook se absorbe por el identificador único de grabación en lugar de crear una segunda fila. La notificación de llegada se envía a cada persona usuaria que tenga el permiso Gestionar cuarentena de correo de voz. Revisar, enrutar y descartar requieren el mismo permiso. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se otorgan los permisos. [[#permissions]]`)
};

const en_xa2_demo_narrative_admin_quarantine_body = /** @type {(inputs: Demo_Narrative_Admin_Quarantine_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À vòìcèmàìl thè systèm cànnòt àttàch tò à tìckèt ìs sèàlèd wìth thè òrgànìzàtìòn kèy ànd hèld ìn qùàràntìnè fòr mànùàl ròùtìng. Thè systèm dòès nòt stòrè thè rècòrdìng ìn thè òpèn ànd dòès nòt dìscàrd ìt. À vòìcèmàìl èntèrs qùàràntìnè whèn thè càll tràckèr hàs nò rècòrd òf thè càll, whèn nò ìntàkè qùèùè ìs cònfìgùrèd, òr whèn thè càllèr cànnòt bè rèsòlvèd tò à clìènt. [[#tèlèphòny #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìs thè rècòrdìng sèàlèd? •••••••••** Thè sèrvèr dòwnlòàds thè àùdìò fròm thè pròvìdèr ànd sèàls ìt wìth thè òrgànìzàtìòn kèy. Ìt wrìtès thè cìphèrtèxt tò blòb stòràgè ànd thèn àsks thè pròvìdèr tò dèlètè bòth thè rècòrdìng ànd thè càll lòg. Thè càllèr's nùmbèr ànd thè nùmbèr càllèd àrè càptùrèd ànd sèàlèd fòr vòìcèmàìls qùàràntìnèd bècàùsè òf à tràckèr mìss òr àn ùnrèsòlvèd clìènt; à vòìcèmàìl qùàràntìnèd bècàùsè nò ìntàkè qùèùè èxìsts hàs nèìthèr nùmbèr rècòrdèd. Thè àùdìò èxìsts ìn plàìntèxt ìn sèrvèr mèmòry ònly dùrìng thè sèàlìng càll, ìn à bùffèr thè còdè zèròès. À pròvìdèr dèlètìòn thàt fàìls òn thè fìrst àttèmpt ìs ènqùèùèd fòr rètry. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs thè sàmè bùffèr hàndlìng dùrìng à nòrmàl càll. [[#èncryptìòn #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ròùtìng ànd dìsmìssàl. •••••••** Thè bròwsèr dècrypts thè sèàlèd àùdìò lòcàlly, sò lìstènìng tò à qùàràntìnèd vòìcèmàìl ìs thè ònly wày tò lèàrn whò càllèd whèn thè nùmbèr dìd nòt rèsòlvè. Thè bròwsèr rè-sèàls thè àùdìò ùndèr thè tìckèt's kèy fòr èàch rècìpìènt, ànd thè sèrvèr rècèìvès ònly cìphèrtèxt. Thè sèàlèd òrìgìnàl ìs dèlètèd àftèr thè fòllòw-ùp ìs crèàtèd. Whèn twò ùsèrs ròùtè thè sàmè vòìcèmàìl, thè fìrst wrìtè sèttlès ìt ànd thè sècònd rècèìvès à cònflìct èrròr. Dìsmìssìng à vòìcèmàìl dèlètès ìts àùdìò pèrmànèntly. [Vòìcèmàìls](#tìckèt-dètàìl/vòìcèmàìls) còvèrs thè rècòrdìng àftèr ìt rèàchès à tìckèt. [[#kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à dàtàbàsè dùmp rèvèàl? ••••••••••** Thè rèàsòn, thè stàtùs, thè dùràtìòn, ànd thè tìmèstàmps àrè plàìntèxt còlùmns. Thè càllèr's nùmbèr ànd thè nùmbèr càllèd àrè cìphèrtèxt. À dùmp shòws hòw màny vòìcèmàìls àn òrgànìzàtìòn fàìlèd tò ròùtè ànd whèn èàch ònè àrrìvèd, bùt nòt whò càllèd. Àrrìvàls, ròùtìng dècìsìòns, ànd dìsmìssàls àrè wrìttèn tò thè àùdìt lòg. [Àùdìt lòg](#àdmìn-lògs/àùdìt) còvèrs thàt rècòrd. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè qùàràntìnè sèrvìcè ànd ìts nòtìfìcàtìòn. ••••••••••••••** \`pàckàgès/sèrvèr/src/tèlèphòny/vòìcèmàìl-qùàràntìnè.ts\` rùns thè sèàl, stòrè, àùdìt, ànd clèànùp pàth. À dùplìcàtè wèbhòòk dèlìvèry ìs àbsòrbèd by thè ùnìqùè rècòrdìng ìdèntìfìèr ràthèr thàn crèàtìng à sècònd ròw. Thè àrrìvàl nòtìfìcàtìòn ìs sènt tò èvèry ùsèr hòldìng thè Mànàgè vòìcèmàìl qùàràntìnè pèrmìssìòn. Rèvìèwìng, ròùtìng, ànd dìsmìssìng àll rèqùìrè thè sàmè pèrmìssìòn. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw pèrmìssìòns àrè gràntèd. [[#pèrmìssìòns]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A voicemail the system cannot attach to a ticket is sealed with the organization key and held in quarantine for manual routing. The system does not store the..." |
*
* @param {Demo_Narrative_Admin_Quarantine_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_quarantine_body = /** @type {((inputs?: Demo_Narrative_Admin_Quarantine_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Quarantine_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_quarantine_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_quarantine_body(inputs)
	return en_demo_narrative_admin_quarantine_body(inputs)
});