/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Network_BodyInputs */

const en_demo_narrative_deepdive_network_body = /** @type {(inputs: Demo_Narrative_Deepdive_Network_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`All traffic between the browser and the server travels over TLS. Someone watching the connection cannot read the path, page content, request bodies, or API responses. What TLS does not hide is the hostname, and on the hosted deployment the hostname includes the organization's subdomain, so the DNS lookup and the TLS handshake both reveal which organization the user is connecting to. [Deployment](#deep-dive/deployment) covers the hosted and self-hosted models. [[#privacy #encryption]]
**What about portal and share links?** Portal links and share links carry their decryption key in the URL fragment. The fragment is the part after the # sign. Browsers never send the fragment to any server, so neither the network nor the CARE-Y server sees the key. [[#encryption #privacy]]
**What does the server store about a connection?** The server records the IP address and user agent of each staff session, sealed to the organization key, alongside keyed hashes used to detect a change. The server cannot read the sealed values during normal operation. A change of IP address clears the session's second-factor verification, and [Two factor authentication](#login/two-factor) covers what happens next. Rate limits count requests per IP address for sign-in, public intake, and portal reads. The key-evaluation service logs each requesting IP address only as a hash under a key that rotates daily, so cross-day correlation requires both days' keys. [[#server-holds #privacy]]
**What do notifications reveal?** Web push notifications carry no content. The server sends an empty body. Notification emails and text pings carry a fixed message with no content from the conversation. [[#privacy #metadata]]
**What about phone calls and texts?** The carrier and the telephony provider can read text messages and hear phone calls. [The telephony relay](#deep-dive/the-telephony-relay) covers what crosses that boundary and how the server handles plaintext. [[#telephony #privacy]]
**What does CARE-Y do about connection visibility?** Organizations can offer a Tor onion address alongside the regular hostname. When a user connects through Tor, the user's internet provider sees a connection to Tor but not to CARE-Y, and the CARE-Y server sees a Tor address instead of the user's real address. Sessions arriving over the onion address are not bound to an IP address, because Tor circuits change. The session token and user agent still bind the session. The server recognizes connections arriving through Tor exit nodes or the onion address and reports the connection type to the interface, so each user can see whether they are connected over Tor or the regular internet. [Security briefing](#settings/security) covers the onboarding walkthrough that explains what network surveillance can and cannot reveal. [[#privacy #trust-boundary]]
**Does the app contact any third party?** The content security policy restricts scripts, fonts, and connections to the application's own origin. Fonts are self-hosted. The client has no analytics service and no error-reporting service. In shipped code the browser contacts no third-party origin at runtime. The one exception is quick exit, which navigates to the organization's configured safe site on the user's action. API responses carry a no-store directive so the browser does not write them to its disk cache. [[#privacy #server-holds]]
**The response headers and the network-facing code.** Production responses carry HSTS with a two-year max-age, includeSubDomains, and preload. X-Frame-Options is DENY. Referrer-Policy is strict-origin-when-cross-origin. Cross-origin isolation headers are set. The CSP is defined in \`packages/client/svelte.config.js\`. Response headers are set in \`packages/client/src/hooks.server.ts\`. The no-store directive on API responses is in \`packages/server/src/index.ts\` and on blob downloads in \`packages/server/src/routes/blob-download.ts\`. The daily-rotating IP hash for key evaluations is derived in \`packages/server/src/crypto/oprf-audit.ts\`. Session IP and user-agent sealing is in \`packages/server/src/auth/session-repository.ts\`. The IP-change handler is in \`packages/server/src/auth/service.ts\`. Notification messages are in \`packages/server/src/notifications/i18n.ts\`, and the empty-body push sender is in \`packages/server/src/notifications/push.ts\`. [[#server-holds #privacy]]`)
};

const es_demo_narrative_deepdive_network_body = /** @type {(inputs: Demo_Narrative_Deepdive_Network_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Todo el tráfico entre el navegador y el servidor viaja sobre TLS. Alguien que observe la conexión no puede leer la ruta, el contenido de las páginas, los cuerpos de las solicitudes ni las respuestas de la API. Lo que TLS no oculta es el nombre de host, y en el despliegue alojado ese nombre incluye el subdominio de la organización, por lo que la consulta DNS y el saludo TLS revelan a qué organización se conecta la persona usuaria. [Despliegue](#deep-dive/deployment) trata los modelos alojado y autoalojado. [[#privacy #encryption]]
**¿Qué ocurre con los enlaces de portal y los enlaces compartidos?** Los enlaces de portal y los enlaces compartidos llevan su clave de descifrado en el fragmento de la URL. El fragmento es la parte después del signo #. Los navegadores nunca envían el fragmento a ningún servidor, así que ni la red ni el servidor de CARE-Y ven la clave. [[#encryption #privacy]]
**¿Qué almacena el servidor sobre una conexión?** El servidor registra la dirección IP y el agente de usuario de cada sesión del personal, sellados con la clave de la organización, junto con hashes con clave que se usan para detectar un cambio. El servidor no puede leer los valores sellados durante la operación normal. Un cambio de dirección IP borra la verificación de segundo factor de la sesión, y [Autenticación de dos factores](#login/two-factor) trata lo que sucede después. Los límites de frecuencia cuentan solicitudes por dirección IP para inicio de sesión, admisión pública y lecturas del portal. El servicio de evaluación de claves registra cada IP solicitante solo como un hash bajo una clave que rota diariamente, por lo que la correlación entre días requiere las claves de ambos días. [[#server-holds #privacy]]
**¿Qué revelan las notificaciones?** Las notificaciones push web no llevan contenido. El servidor envía un cuerpo vacío. Los correos de notificación y los mensajes de texto llevan un mensaje fijo sin contenido de la conversación. [[#privacy #metadata]]
**¿Qué ocurre con las llamadas y los mensajes de texto?** El operador telefónico y el proveedor de telefonía pueden leer los mensajes de texto y escuchar las llamadas. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que cruza esa frontera y cómo el servidor maneja el texto plano. [[#telephony #privacy]]
**¿Qué hace CARE-Y respecto a la visibilidad de la conexión?** Las organizaciones pueden ofrecer una dirección onion de Tor junto al nombre de host regular. Cuando una persona usuaria se conecta a través de Tor, su proveedor de internet ve una conexión a Tor pero no a CARE-Y, y el servidor de CARE-Y ve una dirección de Tor en lugar de la dirección real de la persona. Las sesiones que llegan por la dirección onion no se vinculan a una dirección IP, porque los circuitos de Tor cambian. El token de sesión y el agente de usuario aún vinculan la sesión. El servidor reconoce las conexiones que llegan a través de nodos de salida de Tor o la dirección onion e informa el tipo de conexión a la interfaz, para que cada persona pueda ver si está conectada a través de Tor o de la internet regular. [Resumen de seguridad](#settings/security) trata el recorrido de incorporación que explica qué puede y qué no puede revelar la vigilancia de red. [[#privacy #trust-boundary]]
**¿Contacta la aplicación a algún tercero?** La política de seguridad de contenido restringe scripts, fuentes y conexiones al propio origen de la aplicación. Las fuentes tipográficas se alojan localmente. El cliente no tiene servicio de analítica ni servicio de informes de errores. En el código en producción el navegador no contacta ningún origen de terceros en tiempo de ejecución. La única excepción es la salida rápida, que navega al sitio seguro configurado por la organización cuando la persona usuaria lo activa. Las respuestas de la API llevan una directiva no-store para que el navegador no las escriba en su caché de disco. [[#privacy #server-holds]]
**Las cabeceras de respuesta y el código de cara a la red.** Las respuestas de producción llevan HSTS con un max-age de dos años, includeSubDomains y preload. X-Frame-Options es DENY. Referrer-Policy es strict-origin-when-cross-origin. Las cabeceras de aislamiento de origen cruzado están configuradas. La CSP se define en \`packages/client/svelte.config.js\`. Las cabeceras de respuesta se configuran en \`packages/client/src/hooks.server.ts\`. La directiva no-store en las respuestas de la API está en \`packages/server/src/index.ts\` y en las descargas de blobs en \`packages/server/src/routes/blob-download.ts\`. El hash de IP con rotación diaria para evaluaciones de claves se deriva en \`packages/server/src/crypto/oprf-audit.ts\`. El sellado de IP y agente de usuario de sesión está en \`packages/server/src/auth/session-repository.ts\`. El manejador de cambio de IP está en \`packages/server/src/auth/service.ts\`. Los mensajes de notificación están en \`packages/server/src/notifications/i18n.ts\`, y el emisor push de cuerpo vacío está en \`packages/server/src/notifications/push.ts\`. [[#server-holds #privacy]]`)
};

const en_xa2_demo_narrative_deepdive_network_body = /** @type {(inputs: Demo_Narrative_Deepdive_Network_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Àll tràffìc bètwèèn thè bròwsèr ànd thè sèrvèr tràvèls òvèr TLS. Sòmèònè wàtchìng thè cònnèctìòn cànnòt rèàd thè pàth, pàgè còntènt, rèqùèst bòdìès, òr ÀPÌ rèspònsès. Whàt TLS dòès nòt hìdè ìs thè hòstnàmè, ànd òn thè hòstèd dèplòymènt thè hòstnàmè ìnclùdès thè òrgànìzàtìòn's sùbdòmàìn, sò thè DNS lòòkùp ànd thè TLS hàndshàkè bòth rèvèàl whìch òrgànìzàtìòn thè ùsèr ìs cònnèctìng tò. [Dèplòymènt](#dèèp-dìvè/dèplòymènt) còvèrs thè hòstèd ànd sèlf-hòstèd mòdèls. [[#prìvàcy #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt àbòùt pòrtàl ànd shàrè lìnks? •••••••••••** Pòrtàl lìnks ànd shàrè lìnks càrry thèìr dècryptìòn kèy ìn thè ÙRL fràgmènt. Thè fràgmènt ìs thè pàrt àftèr thè # sìgn. Bròwsèrs nèvèr sènd thè fràgmènt tò àny sèrvèr, sò nèìthèr thè nètwòrk nòr thè CÀRÈ-Y sèrvèr sèès thè kèy. [[#èncryptìòn #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè àbòùt à cònnèctìòn? ••••••••••••••** Thè sèrvèr rècòrds thè ÌP àddrèss ànd ùsèr àgènt òf èàch stàff sèssìòn, sèàlèd tò thè òrgànìzàtìòn kèy, àlòngsìdè kèyèd hàshès ùsèd tò dètèct à chàngè. Thè sèrvèr cànnòt rèàd thè sèàlèd vàlùès dùrìng nòrmàl òpèràtìòn. À chàngè òf ÌP àddrèss clèàrs thè sèssìòn's sècònd-fàctòr vèrìfìcàtìòn, ànd [Twò fàctòr àùthèntìcàtìòn](#lògìn/twò-fàctòr) còvèrs whàt hàppèns nèxt. Ràtè lìmìts còùnt rèqùèsts pèr ÌP àddrèss fòr sìgn-ìn, pùblìc ìntàkè, ànd pòrtàl rèàds. Thè kèy-èvàlùàtìòn sèrvìcè lògs èàch rèqùèstìng ÌP àddrèss ònly às à hàsh ùndèr à kèy thàt ròtàtès dàìly, sò cròss-dày còrrèlàtìòn rèqùìrès bòth dàys' kèys. [[#sèrvèr-hòlds #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dò nòtìfìcàtìòns rèvèàl? •••••••••** Wèb pùsh nòtìfìcàtìòns càrry nò còntènt. Thè sèrvèr sènds àn èmpty bòdy. Nòtìfìcàtìòn èmàìls ànd tèxt pìngs càrry à fìxèd mèssàgè wìth nò còntènt fròm thè cònvèrsàtìòn. [[#prìvàcy #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt àbòùt phònè càlls ànd tèxts? ••••••••••** Thè càrrìèr ànd thè tèlèphòny pròvìdèr càn rèàd tèxt mèssàgès ànd hèàr phònè càlls. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt cròssès thàt bòùndàry ànd hòw thè sèrvèr hàndlès plàìntèxt. [[#tèlèphòny #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès CÀRÈ-Y dò àbòùt cònnèctìòn vìsìbìlìty? •••••••••••••••** Òrgànìzàtìòns càn òffèr à Tòr ònìòn àddrèss àlòngsìdè thè règùlàr hòstnàmè. Whèn à ùsèr cònnècts thròùgh Tòr, thè ùsèr's ìntèrnèt pròvìdèr sèès à cònnèctìòn tò Tòr bùt nòt tò CÀRÈ-Y, ànd thè CÀRÈ-Y sèrvèr sèès à Tòr àddrèss ìnstèàd òf thè ùsèr's rèàl àddrèss. Sèssìòns àrrìvìng òvèr thè ònìòn àddrèss àrè nòt bòùnd tò àn ÌP àddrèss, bècàùsè Tòr cìrcùìts chàngè. Thè sèssìòn tòkèn ànd ùsèr àgènt stìll bìnd thè sèssìòn. Thè sèrvèr rècògnìzès cònnèctìòns àrrìvìng thròùgh Tòr èxìt nòdès òr thè ònìòn àddrèss ànd rèpòrts thè cònnèctìòn typè tò thè ìntèrfàcè, sò èàch ùsèr càn sèè whèthèr thèy àrè cònnèctèd òvèr Tòr òr thè règùlàr ìntèrnèt. [Sècùrìty brìèfìng](#sèttìngs/sècùrìty) còvèrs thè ònbòàrdìng wàlkthròùgh thàt èxplàìns whàt nètwòrk sùrvèìllàncè càn ànd cànnòt rèvèàl. [[#prìvàcy #trùst-bòùndàry]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dòès thè àpp còntàct àny thìrd pàrty? ••••••••••••** Thè còntènt sècùrìty pòlìcy rèstrìcts scrìpts, fònts, ànd cònnèctìòns tò thè àpplìcàtìòn's òwn òrìgìn. Fònts àrè sèlf-hòstèd. Thè clìènt hàs nò ànàlytìcs sèrvìcè ànd nò èrròr-rèpòrtìng sèrvìcè. Ìn shìppèd còdè thè bròwsèr còntàcts nò thìrd-pàrty òrìgìn àt rùntìmè. Thè ònè èxcèptìòn ìs qùìck èxìt, whìch nàvìgàtès tò thè òrgànìzàtìòn's cònfìgùrèd sàfè sìtè òn thè ùsèr's àctìòn. ÀPÌ rèspònsès càrry à nò-stòrè dìrèctìvè sò thè bròwsèr dòès nòt wrìtè thèm tò ìts dìsk càchè. [[#prìvàcy #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rèspònsè hèàdèrs ànd thè nètwòrk-fàcìng còdè. •••••••••••••••** Pròdùctìòn rèspònsès càrry HSTS wìth à twò-yèàr màx-àgè, ìnclùdèSùbDòmàìns, ànd prèlòàd. X-Fràmè-Òptìòns ìs DÈNY. Rèfèrrèr-Pòlìcy ìs strìct-òrìgìn-whèn-cròss-òrìgìn. Cròss-òrìgìn ìsòlàtìòn hèàdèrs àrè sèt. Thè CSP ìs dèfìnèd ìn \`pàckàgès/clìènt/svèltè.cònfìg.js\`. Rèspònsè hèàdèrs àrè sèt ìn \`pàckàgès/clìènt/src/hòòks.sèrvèr.ts\`. Thè nò-stòrè dìrèctìvè òn ÀPÌ rèspònsès ìs ìn \`pàckàgès/sèrvèr/src/ìndèx.ts\` ànd òn blòb dòwnlòàds ìn \`pàckàgès/sèrvèr/src/ròùtès/blòb-dòwnlòàd.ts\`. Thè dàìly-ròtàtìng ÌP hàsh fòr kèy èvàlùàtìòns ìs dèrìvèd ìn \`pàckàgès/sèrvèr/src/cryptò/òprf-àùdìt.ts\`. Sèssìòn ÌP ànd ùsèr-àgènt sèàlìng ìs ìn \`pàckàgès/sèrvèr/src/àùth/sèssìòn-rèpòsìtòry.ts\`. Thè ÌP-chàngè hàndlèr ìs ìn \`pàckàgès/sèrvèr/src/àùth/sèrvìcè.ts\`. Nòtìfìcàtìòn mèssàgès àrè ìn \`pàckàgès/sèrvèr/src/nòtìfìcàtìòns/ì18n.ts\`, ànd thè èmpty-bòdy pùsh sèndèr ìs ìn \`pàckàgès/sèrvèr/src/nòtìfìcàtìòns/pùsh.ts\`. [[#sèrvèr-hòlds #prìvàcy]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "All traffic between the browser and the server travels over TLS. Someone watching the connection cannot read the path, page content, request bodies, or API r..." |
*
* @param {Demo_Narrative_Deepdive_Network_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_network_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Network_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Network_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_network_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_network_body(inputs)
	return en_demo_narrative_deepdive_network_body(inputs)
});