/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Library_Detail_BodyInputs */

const en_demo_narrative_library_detail_body = /** @type {(inputs: Demo_Narrative_Library_Detail_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The browser fetches the article's encrypted body from the server, decrypts it with the organization key, and strips anything that could run as code before rendering the result. The title and metadata come from the list cache and are readable before the body arrives. [[#encryption #client-data]]
**How does the author name arrive?** The browser decrypts the author's display name from its own cache of organization-key names rather than receiving it with the article. When the browser does not hold the author's name, it fetches it from the server. An author that cannot be resolved produces a label identifying the author as unknown rather than a missing line. [Browsing articles](#library/browse) covers which fields on the row are plaintext and which are sealed. [[#encryption #failure-states]]
**How are images in the body fetched?** Each image reference in the document uses a custom URI scheme that maps to an attachment identifier. The browser downloads the ciphertext from the organization's blob storage and decrypts it as the article renders. An image that fails to decrypt is replaced with its alt text or a fallback message. All image data comes from the organization's own blob storage and no external source. [File attachments](#library/attachments) covers the blob route and the checks it runs. [[#server-holds #failure-states]]
**What does an open record?** Opening an article adds its identifier and a timestamp to the user's recently viewed list. [Opening global search](#search/overlay) covers how that list is stored, sealed, and cleared on a password change. [[#privacy]]
**What happens when the article cannot be read?** A body that fails to decrypt reports the failure in place of the article content. A deleted article returns a not-found error from the server, and the query surfaces that error instead of rendering an empty page. [[#failure-states]]
**The detail query and the render pipeline.** \`ArticleDetailView.svelte\` in \`packages/client/src/lib/components/library/\` calls \`getItem\` from \`packages/server/src/routes/kb.ts\`, which returns \`encrypted_body\`. The decrypted bytes are ProseMirror JSON serialized through \`DOMSerializer\`, then sanitized by DOMPurify with a strict tag and attribute allowlist in \`renderArticleBody\` in \`packages/client/src/lib/utils/render-article.ts\`. Legacy plain-text articles are wrapped in paragraphs and sanitized through the same allowlist. [[#client-data]]`)
};

const es_demo_narrative_library_detail_body = /** @type {(inputs: Demo_Narrative_Library_Detail_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El navegador descarga el cuerpo cifrado del artículo desde el servidor, lo descifra con la clave de la organización y elimina del resultado todo lo que podría ejecutarse como código antes de representarlo. El título y los metadatos vienen de la caché de la lista y se pueden leer antes de que llegue el cuerpo. [[#encryption #client-data]]
**¿Cómo llega el nombre de la autoría?** El navegador descifra el nombre visible de la autoría a partir de su propia caché de nombres cifrados con la clave de la organización, en lugar de recibirlo junto con el artículo. Cuando el navegador no tiene el nombre de la autoría, lo solicita al servidor. Si la autoría no se puede resolver, se muestra una etiqueta que la identifica como desconocida en lugar de omitir la línea. [Navegar artículos](#library/browse) trata qué campos de la fila son texto en claro y cuáles están sellados. [[#encryption #failure-states]]
**¿Cómo se descargan las imágenes del cuerpo?** Cada referencia a imagen en el documento usa un esquema URI propio que corresponde a un identificador de adjunto. El navegador descarga el texto cifrado del almacenamiento de blobs de la organización y lo descifra mientras el artículo se representa. Una imagen que no se puede descifrar se reemplaza con su texto alternativo o un mensaje de respaldo. Todos los datos de imagen provienen del almacenamiento de blobs propio de la organización, sin fuentes externas. [Archivos adjuntos](#library/attachments) trata la ruta de blobs y las verificaciones que ejecuta. [[#server-holds #failure-states]]
**¿Qué registra una apertura?** Abrir un artículo añade su identificador y una marca de tiempo a la lista de vistos recientemente de la persona usuaria. [Abrir la búsqueda global](#search/overlay) trata cómo se almacena, sella y borra esa lista tras un cambio de contraseña. [[#privacy]]
**¿Qué pasa cuando el artículo no se puede leer?** Un cuerpo que no se puede descifrar indica el fallo en lugar del contenido del artículo. Un artículo eliminado devuelve un error de no encontrado desde el servidor, y la consulta muestra ese error en vez de representar una página vacía. [[#failure-states]]
**La consulta de detalle y la cadena de representación.** \`ArticleDetailView.svelte\`, en \`packages/client/src/lib/components/library/\`, llama a \`getItem\` de \`packages/server/src/routes/kb.ts\`, que devuelve \`encrypted_body\`. Los bytes descifrados son JSON de ProseMirror serializado mediante \`DOMSerializer\` y saneado por DOMPurify con una lista estricta de etiquetas y atributos permitidos en \`renderArticleBody\` en \`packages/client/src/lib/utils/render-article.ts\`. Los artículos de texto simple heredados se envuelven en párrafos y se sanean con la misma lista de permitidos. [[#client-data]]`)
};

const en_xa2_demo_narrative_library_detail_body = /** @type {(inputs: Demo_Narrative_Library_Detail_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè bròwsèr fètchès thè àrtìclè's èncryptèd bòdy fròm thè sèrvèr, dècrypts ìt wìth thè òrgànìzàtìòn kèy, ànd strìps ànythìng thàt còùld rùn às còdè bèfòrè rèndèrìng thè rèsùlt. Thè tìtlè ànd mètàdàtà còmè fròm thè lìst càchè ànd àrè rèàdàblè bèfòrè thè bòdy àrrìvès. [[#èncryptìòn #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè àùthòr nàmè àrrìvè? ••••••••••** Thè bròwsèr dècrypts thè àùthòr's dìsplày nàmè fròm ìts òwn càchè òf òrgànìzàtìòn-kèy nàmès ràthèr thàn rècèìvìng ìt wìth thè àrtìclè. Whèn thè bròwsèr dòès nòt hòld thè àùthòr's nàmè, ìt fètchès ìt fròm thè sèrvèr. Àn àùthòr thàt cànnòt bè rèsòlvèd pròdùcès à làbèl ìdèntìfyìng thè àùthòr às ùnknòwn ràthèr thàn à mìssìng lìnè. [Bròwsìng àrtìclès](#lìbràry/bròwsè) còvèrs whìch fìèlds òn thè ròw àrè plàìntèxt ànd whìch àrè sèàlèd. [[#èncryptìòn #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw àrè ìmàgès ìn thè bòdy fètchèd? •••••••••••** Èàch ìmàgè rèfèrèncè ìn thè dòcùmènt ùsès à cùstòm ÙRÌ schèmè thàt màps tò àn àttàchmènt ìdèntìfìèr. Thè bròwsèr dòwnlòàds thè cìphèrtèxt fròm thè òrgànìzàtìòn's blòb stòràgè ànd dècrypts ìt às thè àrtìclè rèndèrs. Àn ìmàgè thàt fàìls tò dècrypt ìs rèplàcèd wìth ìts àlt tèxt òr à fàllbàck mèssàgè. Àll ìmàgè dàtà còmès fròm thè òrgànìzàtìòn's òwn blòb stòràgè ànd nò èxtèrnàl sòùrcè. [Fìlè àttàchmènts](#lìbràry/àttàchmènts) còvèrs thè blòb ròùtè ànd thè chècks ìt rùns. [[#sèrvèr-hòlds #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès àn òpèn rècòrd? ••••••••** Òpènìng àn àrtìclè àdds ìts ìdèntìfìèr ànd à tìmèstàmp tò thè ùsèr's rècèntly vìèwèd lìst. [Òpènìng glòbàl sèàrch](#sèàrch/òvèrlày) còvèrs hòw thàt lìst ìs stòrèd, sèàlèd, ànd clèàrèd òn à pàsswòrd chàngè. [[#prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn thè àrtìclè cànnòt bè rèàd? ••••••••••••••** À bòdy thàt fàìls tò dècrypt rèpòrts thè fàìlùrè ìn plàcè òf thè àrtìclè còntènt. À dèlètèd àrtìclè rètùrns à nòt-fòùnd èrròr fròm thè sèrvèr, ànd thè qùèry sùrfàcès thàt èrròr ìnstèàd òf rèndèrìng àn èmpty pàgè. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè dètàìl qùèry ànd thè rèndèr pìpèlìnè. •••••••••••••** \`ÀrtìclèDètàìlVìèw.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/còmpònènts/lìbràry/\` càlls \`gètÌtèm\` fròm \`pàckàgès/sèrvèr/src/ròùtès/kb.ts\`, whìch rètùrns \`èncryptèd_bòdy\`. Thè dècryptèd bytès àrè PròsèMìrròr JSÒN sèrìàlìzèd thròùgh \`DÒMSèrìàlìzèr\`, thèn sànìtìzèd by DÒMPùrìfy wìth à strìct tàg ànd àttrìbùtè àllòwlìst ìn \`rèndèrÀrtìclèBòdy\` ìn \`pàckàgès/clìènt/src/lìb/ùtìls/rèndèr-àrtìclè.ts\`. Lègàcy plàìn-tèxt àrtìclès àrè wràppèd ìn pàràgràphs ànd sànìtìzèd thròùgh thè sàmè àllòwlìst. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The browser fetches the article's encrypted body from the server, decrypts it with the organization key, and strips anything that could run as code before re..." |
*
* @param {Demo_Narrative_Library_Detail_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_library_detail_body = /** @type {((inputs?: Demo_Narrative_Library_Detail_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Library_Detail_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_library_detail_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_library_detail_body(inputs)
	return en_demo_narrative_library_detail_body(inputs)
});