/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Portal_Thread_BodyInputs */

const en_demo_narrative_client_portal_thread_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The portal thread merges the client's messages, the organization's replies, voicemails, call log entries, files and contact corrections into one sequence ordered by date. The client can filter by type, by author and by date range. [[#portal #client-data]]
**How are messages encrypted?** Each message is encrypted to the channel's public key, and the matching private key is derived in a dedicated worker from the credential the link carries. Files carry a random key of their own sealed to the same channel key, and voicemail recordings open by the same path. The server stores call entries as plaintext metadata, so a database dump reveals that a call happened, when and how long it lasted. [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers the channel key. [[#encryption #keys #server-holds]]
**How does the credential stay private?** The credential sits in the part of the URL after the \`#\`, which browsers never send to a server. The page reads it once and removes it from the address bar, so it is absent from the browser's history and from any address the client copies. [Quick exit](#client-portal/quick-exit) covers what the page discards on exit. [[#privacy #keys]]
**What stays on the device?** Filters and in-thread search operate on text already decrypted in the tab. No search term or filter choice leaves the device. The thread loads fifty messages at a time and fetches the older page when the client reaches the oldest one loaded. [[#privacy #client-data]]
**How long do the client's copies last?** Every read stamps the channel as seen. The client's copies of messages, files and recordings expire after a period. The organization's record of the ticket is stored separately under the ticket key and follows its own schedule. [Data retention](#deep-dive/data-retention) covers that schedule. [[#retention #portal]]
**What happens when a read is refused?** The server rate-limits portal reads to sixty per address per hour by default. A refusal carries the number of seconds to wait, and the page retries automatically after that interval. The automatic retry matters because a client who mistakes a transient refusal for a dead link may discard a link that still works. [[#failure-states]]
**The thread component and the paging path.** \`PortalThread.svelte\` in \`packages/client/src/lib/portal/\` renders messages, date separators, images, voicemails, call entries and corrections using components from \`packages/client/src/lib/components/tickets/\`, shared with the organization's own conversation thread. Pages come from \`portalMessagePage\` in \`packages/server/src/routes/client-portal.ts\`, and the seen stamp and the expiry sweep are in \`packages/server/src/portal/portal-message-service.ts\`. [Conversation thread](#ticket-detail/conversation) covers the organization's end. [[#portal #client-data]]`)
};

const es_demo_narrative_client_portal_thread_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El hilo del portal reúne los mensajes del cliente, las respuestas de la organización, los mensajes de voz, las entradas del registro de llamadas, los archivos y las correcciones de contacto en una sola secuencia ordenada por fecha. El cliente puede filtrar por tipo, por autoría y por intervalo de fechas. [[#portal #client-data]]
**¿Cómo se cifran los mensajes?** Cada mensaje se cifra con la clave pública del canal, y la clave privada correspondiente se deriva en un worker dedicado a partir de la credencial que lleva el enlace. Los archivos llevan una clave aleatoria propia sellada con esa misma clave del canal, y las grabaciones de voz se abren por la misma vía. El servidor almacena las entradas de llamada como metadatos en texto plano, de modo que un volcado de la base de datos revela que hubo una llamada, cuándo ocurrió y cuánto duró. [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata la clave del canal. [[#encryption #keys #server-holds]]
**¿Cómo se protege la credencial?** La credencial está en la parte de la URL posterior al \`#\`, que los navegadores nunca envían a un servidor. La página la lee una vez y la retira de la barra de direcciones, de modo que no aparece en el historial del navegador ni en ninguna dirección que el cliente copie. [Salida rápida](#client-portal/quick-exit) trata lo que la página descarta al salir. [[#privacy #keys]]
**¿Qué permanece en el dispositivo?** Los filtros y la búsqueda dentro del hilo operan sobre texto ya descifrado en la pestaña. Ningún término de búsqueda ni elección de filtro sale del dispositivo. El hilo carga cincuenta mensajes a la vez y pide la página anterior cuando el cliente llega al más antiguo que tiene cargado. [[#privacy #client-data]]
**¿Cuánto duran las copias del cliente?** Cada lectura marca el canal como visto. Las copias de mensajes, archivos y grabaciones del cliente expiran tras un periodo. El registro del ticket que guarda la organización se almacena aparte bajo la clave del ticket y sigue su propio calendario. [Retención de datos](#deep-dive/data-retention) trata ese calendario. [[#retention #portal]]
**¿Qué ocurre cuando se rechaza una lectura?** El servidor limita las lecturas del portal a sesenta por dirección por hora de forma predeterminada. El rechazo indica cuántos segundos hay que esperar, y la página reintenta automáticamente pasado ese intervalo. El reintento automático importa porque un cliente que confunda un rechazo pasajero con un enlace muerto puede descartar un enlace que todavía funciona. [[#failure-states]]
**El componente del hilo y la ruta de paginación.** \`PortalThread.svelte\`, en \`packages/client/src/lib/portal/\`, presenta mensajes, separadores de fecha, imágenes, mensajes de voz, entradas de llamada y correcciones usando componentes de \`packages/client/src/lib/components/tickets/\`, compartidos con el hilo de conversación de la propia organización. Las páginas vienen de \`portalMessagePage\` en \`packages/server/src/routes/client-portal.ts\`, y la marca de visto y el barrido de caducidad están en \`packages/server/src/portal/portal-message-service.ts\`. [Hilo de conversación](#ticket-detail/conversation) trata el extremo de la organización. [[#portal #client-data]]`)
};

const en_xa2_demo_narrative_client_portal_thread_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè pòrtàl thrèàd mèrgès thè clìènt's mèssàgès, thè òrgànìzàtìòn's rèplìès, vòìcèmàìls, càll lòg èntrìès, fìlès ànd còntàct còrrèctìòns ìntò ònè sèqùèncè òrdèrèd by dàtè. Thè clìènt càn fìltèr by typè, by àùthòr ànd by dàtè ràngè. [[#pòrtàl #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw àrè mèssàgès èncryptèd? •••••••••** Èàch mèssàgè ìs èncryptèd tò thè chànnèl's pùblìc kèy, ànd thè màtchìng prìvàtè kèy ìs dèrìvèd ìn à dèdìcàtèd wòrkèr fròm thè crèdèntìàl thè lìnk càrrìès. Fìlès càrry à ràndòm kèy òf thèìr òwn sèàlèd tò thè sàmè chànnèl kèy, ànd vòìcèmàìl rècòrdìngs òpèn by thè sàmè pàth. Thè sèrvèr stòrès càll èntrìès às plàìntèxt mètàdàtà, sò à dàtàbàsè dùmp rèvèàls thàt à càll hàppènèd, whèn ànd hòw lòng ìt làstèd. [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thè chànnèl kèy. [[#èncryptìòn #kèys #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès thè crèdèntìàl stày prìvàtè? ••••••••••••** Thè crèdèntìàl sìts ìn thè pàrt òf thè ÙRL àftèr thè \`#\`, whìch bròwsèrs nèvèr sènd tò à sèrvèr. Thè pàgè rèàds ìt òncè ànd rèmòvès ìt fròm thè àddrèss bàr, sò ìt ìs àbsènt fròm thè bròwsèr's hìstòry ànd fròm àny àddrèss thè clìènt còpìès. [Qùìck èxìt](#clìènt-pòrtàl/qùìck-èxìt) còvèrs whàt thè pàgè dìscàrds òn èxìt. [[#prìvàcy #kèys]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt stàys òn thè dèvìcè? ••••••••** Fìltèrs ànd ìn-thrèàd sèàrch òpèràtè òn tèxt àlrèàdy dècryptèd ìn thè tàb. Nò sèàrch tèrm òr fìltèr chòìcè lèàvès thè dèvìcè. Thè thrèàd lòàds fìfty mèssàgès àt à tìmè ànd fètchès thè òldèr pàgè whèn thè clìènt rèàchès thè òldèst ònè lòàdèd. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw lòng dò thè clìènt's còpìès làst? ••••••••••••** Èvèry rèàd stàmps thè chànnèl às sèèn. Thè clìènt's còpìès òf mèssàgès, fìlès ànd rècòrdìngs èxpìrè àftèr à pèrìòd. Thè òrgànìzàtìòn's rècòrd òf thè tìckèt ìs stòrèd sèpàràtèly ùndèr thè tìckèt kèy ànd fòllòws ìts òwn schèdùlè. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thàt schèdùlè. [[#rètèntìòn #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn à rèàd ìs rèfùsèd? •••••••••••** Thè sèrvèr ràtè-lìmìts pòrtàl rèàds tò sìxty pèr àddrèss pèr hòùr by dèfàùlt. À rèfùsàl càrrìès thè nùmbèr òf sècònds tò wàìt, ànd thè pàgè rètrìès àùtòmàtìcàlly àftèr thàt ìntèrvàl. Thè àùtòmàtìc rètry màttèrs bècàùsè à clìènt whò mìstàkès à trànsìènt rèfùsàl fòr à dèàd lìnk mày dìscàrd à lìnk thàt stìll wòrks. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè thrèàd còmpònènt ànd thè pàgìng pàth. •••••••••••••** \`PòrtàlThrèàd.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/pòrtàl/\` rèndèrs mèssàgès, dàtè sèpàràtòrs, ìmàgès, vòìcèmàìls, càll èntrìès ànd còrrèctìòns ùsìng còmpònènts fròm \`pàckàgès/clìènt/src/lìb/còmpònènts/tìckèts/\`, shàrèd wìth thè òrgànìzàtìòn's òwn cònvèrsàtìòn thrèàd. Pàgès còmè fròm \`pòrtàlMèssàgèPàgè\` ìn \`pàckàgès/sèrvèr/src/ròùtès/clìènt-pòrtàl.ts\`, ànd thè sèèn stàmp ànd thè èxpìry swèèp àrè ìn \`pàckàgès/sèrvèr/src/pòrtàl/pòrtàl-mèssàgè-sèrvìcè.ts\`. [Cònvèrsàtìòn thrèàd](#tìckèt-dètàìl/cònvèrsàtìòn) còvèrs thè òrgànìzàtìòn's ènd. [[#pòrtàl #clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The portal thread merges the client's messages, the organization's replies, voicemails, call log entries, files and contact corrections into one sequence ord..." |
*
* @param {Demo_Narrative_Client_Portal_Thread_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_portal_thread_body = /** @type {((inputs?: Demo_Narrative_Client_Portal_Thread_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Portal_Thread_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_portal_thread_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_portal_thread_body(inputs)
	return en_demo_narrative_client_portal_thread_body(inputs)
});