/* eslint-disable */
import * as registry from '../registry.js'
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_On_The_Device_BodyInputs */

const en_demo_narrative_deepdive_on_the_device_body = /** @type {(inputs: Demo_Narrative_Deepdive_On_The_Device_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Keys and decrypted case content live in the browser's memory. When the user signs out, closes the tab, or sits idle for fifteen minutes, the browser zeroes the keys and clears the decrypted caches. A small set of preferences and organization details stay in browser storage after the keys are gone. [[#privacy #keys #encryption]]
**What does memory hold?** Keys are held in a background process of the browser. Per-case ticket keys sit in a fifty-entry cache that zeroes each key it evicts. Decrypted text and organization material are held by the open page and registered together so they can be cleared in one step. The app writes nothing decrypted or key-bearing to the browser's database. [[#keys #encryption #client-data]]
**When are the keys zeroed?** Signing out clears the decrypted caches and zeroes the keys first, then asks the server to end the session. If the server does not confirm, the sign-in page shows a notice. The idle timeout after fifteen minutes does the same. Closing the tab clears the decrypted caches and zeroes the organization key, and the background process zeroes its own keys three seconds after the last tab disconnects. A thirty-minute backstop zeroes all keys if no request arrives, covering tabs that crash without sending a disconnect. [[#keys #privacy]]
**What stays after a staff user signs out?** The color scheme, the interface theme, and view-mode choices remain in local storage. The branding cache, the organization's terminology, saved-filter keys, and reply drafts are cleared on sign-out and on idle timeout. [Language selection](#settings/language) covers what the language preference stores. [[#client-data #privacy]]
**What stays on a client's device?** Client pages write no organization branding to the device's storage. The name and safe-exit address arrive in the page from the server. Portal and share links carry the decryption key in the URL fragment, which browsers do not include in requests. The page strips the fragment from the address bar once it has read it, but the path with the channel or share identifier stays in the browser history. The share view's decrypted text is a JavaScript string that cannot be zeroed; leaving the page drops the reference. Intake zeroes each key inside the call that created it, and its form fields turn browser autofill off. Client password fields discourage the browser from saving the password. A client's theme or language choice leaves the same local storage key as a staff user's. [Quick exit](#client-portal/quick-exit) covers what the exit control does and does not clear. The client account idle timeout revokes the server session and returns to the sign-in page. [Account sign in](#client-account/sign-in) covers that timeout. [[#client-data #portal #privacy]]
**The cleanup modules and the worker backstop.** Sign-out runs through \`packages/client/src/routes/(auth)/logout/+page.svelte\`. The idle timeout fires in \`packages/client/src/routes/(app)/+layout.svelte\`. Tab-close cleanup runs in \`packages/client/src/lib/auth/cleanup.ts\`. The cache registry that coordinates clearing is \`packages/client/src/lib/crypto/cache-registry.ts\`. The shared worker's idle self-zero backstop is \`IDLE_SELF_ZERO_MS\` in \`packages/client/src/lib/workers/crypto-core.ts\`. The per-case ticket key cache is \`packages/client/src/lib/workers/tk-cache.ts\`, with a fifty-entry cap and memzero on eviction. The service worker excludes all API paths from its cache in \`packages/client/src/service-worker.ts\`, and the server sets \`no-store\` on every tRPC response via \`packages/server/src/http/response-headers.ts\`. [[#keys #encryption]]`)
};

const es_demo_narrative_deepdive_on_the_device_body = /** @type {(inputs: Demo_Narrative_Deepdive_On_The_Device_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Las claves y el contenido descifrado de los casos viven en la memoria del navegador. Cuando la persona usuaria cierra sesión, cierra la pestaña o permanece inactiva quince minutos, el navegador pone las claves a cero y borra las cachés de contenido descifrado. Un conjunto reducido de preferencias y datos de la organización permanece en el almacenamiento del navegador después de que las claves desaparecen. [[#privacy #keys #encryption]]
**¿Qué contiene la memoria?** Las claves se mantienen en un proceso en segundo plano del navegador. Las claves de ticket por caso ocupan una caché de cincuenta entradas que pone a cero cada clave que desaloja. El texto descifrado y el material de la organización los retiene la página abierta y se registran juntos para poder borrarse en un solo paso. La app no escribe nada descifrado ni portador de claves en la base de datos del navegador. [[#keys #encryption #client-data]]
**¿Cuándo se ponen las claves a cero?** Al cerrar sesión se borran las cachés de descifrado y se ponen las claves a cero primero, y después se pide al servidor que termine la sesión. Si el servidor no confirma, la página de inicio de sesión muestra un aviso. El cierre por inactividad tras quince minutos hace lo mismo. Cerrar la pestaña borra las cachés de descifrado y pone a cero la clave de organización, y el proceso en segundo plano pone a cero sus propias claves tres segundos después de que se desconecta la última pestaña. Un respaldo de treinta minutos pone todas las claves a cero si no llega ninguna solicitud, cubriendo pestañas que fallan sin enviar una desconexión. [[#keys #privacy]]
**¿Qué permanece cuando una persona del equipo cierra sesión?** El esquema de color, el tema de interfaz y las opciones de modo de vista permanecen en almacenamiento local. La caché de marca, la terminología de la organización, las claves de filtros guardados y los borradores de respuesta se borran al cerrar sesión y cuando se agota el tiempo de inactividad. [Selección de idioma](#settings/language) trata lo que almacena la preferencia de idioma. [[#client-data #privacy]]
**¿Qué permanece en el dispositivo del cliente?** Las páginas de cliente no escriben marca de la organización en el almacenamiento del dispositivo. El nombre y la dirección de salida segura llegan a la página desde el servidor. Los enlaces de portal y de contenido compartido llevan la clave de descifrado en el fragmento de URL, que los navegadores no incluyen en las solicitudes. La página elimina el fragmento de la barra de direcciones una vez que lo ha leído, pero la ruta con el identificador de canal o de enlace compartido permanece en el historial del navegador. El texto descifrado de la vista compartida es una cadena JavaScript que no se puede poner a cero; salir de la página elimina la referencia. La admisión pone a cero cada clave dentro de la llamada que la creó, y sus campos de formulario desactivan el autocompletado del navegador. Los campos de contraseña del cliente disuaden al navegador de guardar la contraseña. La elección de tema o idioma del cliente deja la misma clave de almacenamiento local que la de una persona del equipo. [Salida rápida](#client-portal/quick-exit) trata lo que el control de salida borra y lo que no. El cierre por inactividad de cuenta de cliente revoca la sesión del servidor y vuelve a la página de inicio de sesión. [Inicio de sesión de cuenta](#client-account/sign-in) trata ese cierre por inactividad. [[#client-data #portal #privacy]]
**Los módulos de limpieza y el respaldo del worker.** El cierre de sesión se ejecuta en \`packages/client/src/routes/(auth)/logout/+page.svelte\`. El cierre por inactividad se dispara en \`packages/client/src/routes/(app)/+layout.svelte\`. La limpieza al cerrar pestaña se ejecuta en \`packages/client/src/lib/auth/cleanup.ts\`. El registro de cachés que coordina el borrado es \`packages/client/src/lib/crypto/cache-registry.ts\`. El respaldo de auto-borrado por inactividad del shared worker es \`IDLE_SELF_ZERO_MS\` en \`packages/client/src/lib/workers/crypto-core.ts\`. La caché de claves de ticket por caso es \`packages/client/src/lib/workers/tk-cache.ts\`, con un límite de cincuenta entradas y memzero al desalojar. El service worker excluye todas las rutas de API de su caché en \`packages/client/src/service-worker.ts\`, y el servidor establece \`no-store\` en cada respuesta tRPC a través de \`packages/server/src/http/response-headers.ts\`. [[#keys #encryption]]`)
};

const en_xa2_demo_narrative_deepdive_on_the_device_body = /** @type {(inputs: Demo_Narrative_Deepdive_On_The_Device_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Kèys ànd dècryptèd càsè còntènt lìvè ìn thè bròwsèr's mèmòry. Whèn thè ùsèr sìgns òùt, clòsès thè tàb, òr sìts ìdlè fòr fìftèèn mìnùtès, thè bròwsèr zèròès thè kèys ànd clèàrs thè dècryptèd càchès. À smàll sèt òf prèfèrèncès ànd òrgànìzàtìòn dètàìls stày ìn bròwsèr stòràgè àftèr thè kèys àrè gònè. [[#prìvàcy #kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès mèmòry hòld? •••••••** Kèys àrè hèld ìn à bàckgròùnd pròcèss òf thè bròwsèr. Pèr-càsè tìckèt kèys sìt ìn à fìfty-èntry càchè thàt zèròès èàch kèy ìt èvìcts. Dècryptèd tèxt ànd òrgànìzàtìòn màtèrìàl àrè hèld by thè òpèn pàgè ànd règìstèrèd tògèthèr sò thèy càn bè clèàrèd ìn ònè stèp. Thè àpp wrìtès nòthìng dècryptèd òr kèy-bèàrìng tò thè bròwsèr's dàtàbàsè. [[#kèys #èncryptìòn #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn àrè thè kèys zèròèd? ••••••••** Sìgnìng òùt clèàrs thè dècryptèd càchès ànd zèròès thè kèys fìrst, thèn àsks thè sèrvèr tò ènd thè sèssìòn. Ìf thè sèrvèr dòès nòt cònfìrm, thè sìgn-ìn pàgè shòws à nòtìcè. Thè ìdlè tìmèòùt àftèr fìftèèn mìnùtès dòès thè sàmè. Clòsìng thè tàb clèàrs thè dècryptèd càchès ànd zèròès thè òrgànìzàtìòn kèy, ànd thè bàckgròùnd pròcèss zèròès ìts òwn kèys thrèè sècònds àftèr thè làst tàb dìscònnècts. À thìrty-mìnùtè bàckstòp zèròès àll kèys ìf nò rèqùèst àrrìvès, còvèrìng tàbs thàt cràsh wìthòùt sèndìng à dìscònnèct. [[#kèys #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt stàys àftèr à stàff ùsèr sìgns òùt? ••••••••••••** Thè còlòr schèmè, thè ìntèrfàcè thèmè, ànd vìèw-mòdè chòìcès rèmàìn ìn lòcàl stòràgè. Thè bràndìng càchè, thè òrgànìzàtìòn's tèrmìnòlògy, sàvèd-fìltèr kèys, ànd rèply dràfts àrè clèàrèd òn sìgn-òùt ànd òn ìdlè tìmèòùt. [Làngùàgè sèlèctìòn](#sèttìngs/làngùàgè) còvèrs whàt thè làngùàgè prèfèrèncè stòrès. [[#clìènt-dàtà #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt stàys òn à clìènt's dèvìcè? ••••••••••** Clìènt pàgès wrìtè nò òrgànìzàtìòn bràndìng tò thè dèvìcè's stòràgè. Thè nàmè ànd sàfè-èxìt àddrèss àrrìvè ìn thè pàgè fròm thè sèrvèr. Pòrtàl ànd shàrè lìnks càrry thè dècryptìòn kèy ìn thè ÙRL fràgmènt, whìch bròwsèrs dò nòt ìnclùdè ìn rèqùèsts. Thè pàgè strìps thè fràgmènt fròm thè àddrèss bàr òncè ìt hàs rèàd ìt, bùt thè pàth wìth thè chànnèl òr shàrè ìdèntìfìèr stàys ìn thè bròwsèr hìstòry. Thè shàrè vìèw's dècryptèd tèxt ìs à JàvàScrìpt strìng thàt cànnòt bè zèròèd; lèàvìng thè pàgè dròps thè rèfèrèncè. Ìntàkè zèròès èàch kèy ìnsìdè thè càll thàt crèàtèd ìt, ànd ìts fòrm fìèlds tùrn bròwsèr àùtòfìll òff. Clìènt pàsswòrd fìèlds dìscòùràgè thè bròwsèr fròm sàvìng thè pàsswòrd. À clìènt's thèmè òr làngùàgè chòìcè lèàvès thè sàmè lòcàl stòràgè kèy às à stàff ùsèr's. [Qùìck èxìt](#clìènt-pòrtàl/qùìck-èxìt) còvèrs whàt thè èxìt còntròl dòès ànd dòès nòt clèàr. Thè clìènt àccòùnt ìdlè tìmèòùt rèvòkès thè sèrvèr sèssìòn ànd rètùrns tò thè sìgn-ìn pàgè. [Àccòùnt sìgn ìn](#clìènt-àccòùnt/sìgn-ìn) còvèrs thàt tìmèòùt. [[#clìènt-dàtà #pòrtàl #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè clèànùp mòdùlès ànd thè wòrkèr bàckstòp. ••••••••••••••** Sìgn-òùt rùns thròùgh \`pàckàgès/clìènt/src/ròùtès/(àùth)/lògòùt/+pàgè.svèltè\`. Thè ìdlè tìmèòùt fìrès ìn \`pàckàgès/clìènt/src/ròùtès/(àpp)/+làyòùt.svèltè\`. Tàb-clòsè clèànùp rùns ìn \`pàckàgès/clìènt/src/lìb/àùth/clèànùp.ts\`. Thè càchè règìstry thàt còòrdìnàtès clèàrìng ìs \`pàckàgès/clìènt/src/lìb/cryptò/càchè-règìstry.ts\`. Thè shàrèd wòrkèr's ìdlè sèlf-zèrò bàckstòp ìs \`ÌDLÈ_SÈLF_ZÈRÒ_MS\` ìn \`pàckàgès/clìènt/src/lìb/wòrkèrs/cryptò-còrè.ts\`. Thè pèr-càsè tìckèt kèy càchè ìs \`pàckàgès/clìènt/src/lìb/wòrkèrs/tk-càchè.ts\`, wìth à fìfty-èntry càp ànd mèmzèrò òn èvìctìòn. Thè sèrvìcè wòrkèr èxclùdès àll ÀPÌ pàths fròm ìts càchè ìn \`pàckàgès/clìènt/src/sèrvìcè-wòrkèr.ts\`, ànd thè sèrvèr sèts \`nò-stòrè\` òn èvèry tRPC rèspònsè vìà \`pàckàgès/sèrvèr/src/http/rèspònsè-hèàdèrs.ts\`. [[#kèys #èncryptìòn]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Keys and decrypted case content live in the browser's memory. When the user signs out, closes the tab, or sits idle for fifteen minutes, the browser zeroes t..." |
*
* @param {Demo_Narrative_Deepdive_On_The_Device_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_on_the_device_body = /** @type {((inputs?: Demo_Narrative_Deepdive_On_The_Device_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_On_The_Device_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_on_the_device_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_on_the_device_body(inputs)
	return en_demo_narrative_deepdive_on_the_device_body(inputs)
});