/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Settings_Twofa_BodyInputs */

const en_demo_narrative_settings_twofa_body = /** @type {(inputs: Demo_Narrative_Settings_Twofa_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The user enrolls and removes second-factor methods from settings. An account can hold several active methods at once, and each one works independently. [Two factor authentication](#login/two-factor) covers what a sign-in does with them and how the methods compare in strength. [[#privacy #permissions]]
**How is each method proved at enrollment?** [Passkeys and security keys](#login/passkey) and [Authenticator app codes](#login/totp) are verified on the spot, from the device or from a code the app generates. [Email codes](#login/email) and [Text message codes](#login/sms) deliver a verification code and keep the method inactive until the user confirms it. [Push approval](#login/push) sends a test notification to confirm the device can receive it. [[#failure-states]]
**Resend cooldowns.** The server enforces sixty seconds between email codes and ninety seconds between text message codes. The browser counts down from the same values, so the wait the user sees and the wait the server applies cannot drift apart. [[#failure-states #telephony]]
**Who can remove a method?** Removal requires the user to have already verified a second factor in the current session. The server refuses to remove the last active method. An administrator can reset another account's second-factor methods through an audited process that records who performed the reset. [[#permissions #failure-states]]
**Backup code lifecycle.** [Backup codes](#login/backup-codes) are generated as a set of eight after the first method is enrolled. Generating a new set deletes the previous one, so codes recorded earlier stop working at that moment. [[#failure-states]]
**What does a database copy show?** The method names on each account and whether each is active are stored without encryption. The count of unused backup codes is also unencrypted. A copy of the database reveals which types of second factor each account uses and how many backup codes remain. Method secrets (TOTP keys, passkey credentials) are stored in encrypted columns, and backup codes are stored only as hashes. [The trust boundary](#deep-dive/the-trust-boundary) covers the rest of the unencrypted schema. [[#server-holds #metadata]]
**Does removing email as a second factor change where notifications go?** The address used for email second-factor codes and the address used for notification delivery are managed separately. Removing the email method clears the second-factor address without affecting the notification address. [Notification preferences](#settings/notifications) covers where the notification address comes from. [[#server-holds #privacy]]
**The enrollment service and cooldown constants.** Enrollment, verification, and removal live in the \`enroll\` and \`methods\` routers in \`packages/server/src/routes/two-factor.ts\`, backed by \`packages/server/src/auth/two-factor-service.ts\`. The cooldown constants are in \`packages/shared/src/schemas/auth.ts\`. [Notification preferences](#settings/notifications) covers the notification address. [[#server-holds]]`)
};

const es_demo_narrative_settings_twofa_body = /** @type {(inputs: Demo_Narrative_Settings_Twofa_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La persona usuaria inscribe y elimina métodos de segundo factor desde los ajustes. Una cuenta puede tener varios métodos activos a la vez, y cada uno funciona de forma independiente. [Autenticación de dos factores](#login/two-factor) trata lo que hace un inicio de sesión con ellos y cómo se comparan en fortaleza los métodos. [[#privacy #permissions]]
**¿Cómo se demuestra cada método al inscribirse?** [Passkeys y llaves de seguridad](#login/passkey) y [Códigos de aplicación de autenticación](#login/totp) se verifican en el momento, desde el dispositivo o con un código que genera la aplicación. [Códigos por correo](#login/email) y [Códigos por mensaje de texto](#login/sms) envían un código de verificación y mantienen el método inactivo hasta que la persona usuaria lo confirma. [Aprobación push](#login/push) envía una notificación de prueba para confirmar que el dispositivo puede recibirla. [[#failure-states]]
**Tiempos de espera entre reenvíos.** El servidor aplica sesenta segundos entre códigos por correo y noventa segundos entre códigos por mensaje de texto. El navegador cuenta atrás desde los mismos valores, de modo que la espera que ve la persona usuaria y la que aplica el servidor no pueden separarse. [[#failure-states #telephony]]
**¿Quién puede eliminar un método?** La eliminación requiere que la persona usuaria ya haya verificado un segundo factor en la sesión en curso. El servidor rechaza eliminar el último método activo. Una persona administradora puede restablecer los métodos de segundo factor de otra cuenta mediante un proceso auditado que registra quién realizó el restablecimiento. [[#permissions #failure-states]]
**Ciclo de vida de los códigos de respaldo.** Los [códigos de respaldo](#login/backup-codes) se generan como un conjunto de ocho tras inscribir el primer método. Generar un conjunto nuevo elimina el anterior, de modo que los códigos anotados antes dejan de funcionar en ese momento. [[#failure-states]]
**¿Qué muestra una copia de la base de datos?** Los nombres de los métodos en cada cuenta y si cada uno está activo se almacenan sin cifrar. El recuento de códigos de respaldo sin usar tampoco está cifrado. Una copia de la base de datos revela qué tipos de segundo factor usa cada cuenta y cuántos códigos de respaldo le quedan. Los secretos de los métodos (claves TOTP, credenciales de passkey) se almacenan en columnas cifradas, y los códigos de respaldo se almacenan solo como hashes. [La frontera de confianza](#deep-dive/the-trust-boundary) trata el resto del esquema sin cifrar. [[#server-holds #metadata]]
**¿Eliminar el correo como segundo factor cambia adónde van las notificaciones?** La dirección usada para los códigos de segundo factor por correo y la dirección usada para las notificaciones se gestionan por separado. Eliminar el método de correo borra la dirección de segundo factor sin afectar la dirección de notificaciones. [Preferencias de notificaciones](#settings/notifications) trata de dónde viene la dirección de notificaciones. [[#server-holds #privacy]]
**El servicio de inscripción y las constantes de espera.** La inscripción, la verificación y la eliminación están en los enrutadores \`enroll\` y \`methods\` de \`packages/server/src/routes/two-factor.ts\`, respaldados por \`packages/server/src/auth/two-factor-service.ts\`. Las constantes de espera están en \`packages/shared/src/schemas/auth.ts\`. [Preferencias de notificaciones](#settings/notifications) trata la dirección de notificaciones. [[#server-holds]]`)
};

const en_xa2_demo_narrative_settings_twofa_body = /** @type {(inputs: Demo_Narrative_Settings_Twofa_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ùsèr ènròlls ànd rèmòvès sècònd-fàctòr mèthòds fròm sèttìngs. Àn àccòùnt càn hòld sèvèràl àctìvè mèthòds àt òncè, ànd èàch ònè wòrks ìndèpèndèntly. [Twò fàctòr àùthèntìcàtìòn](#lògìn/twò-fàctòr) còvèrs whàt à sìgn-ìn dòès wìth thèm ànd hòw thè mèthòds còmpàrè ìn strèngth. [[#prìvàcy #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìs èàch mèthòd pròvèd àt ènròllmènt? ••••••••••••** [Pàsskèys ànd sècùrìty kèys](#lògìn/pàsskèy) ànd [Àùthèntìcàtòr àpp còdès](#lògìn/tòtp) àrè vèrìfìèd òn thè spòt, fròm thè dèvìcè òr fròm à còdè thè àpp gènèràtès. [Èmàìl còdès](#lògìn/èmàìl) ànd [Tèxt mèssàgè còdès](#lògìn/sms) dèlìvèr à vèrìfìcàtìòn còdè ànd kèèp thè mèthòd ìnàctìvè ùntìl thè ùsèr cònfìrms ìt. [Pùsh àppròvàl](#lògìn/pùsh) sènds à tèst nòtìfìcàtìòn tò cònfìrm thè dèvìcè càn rècèìvè ìt. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rèsènd còòldòwns. ••••••** Thè sèrvèr ènfòrcès sìxty sècònds bètwèèn èmàìl còdès ànd nìnèty sècònds bètwèèn tèxt mèssàgè còdès. Thè bròwsèr còùnts dòwn fròm thè sàmè vàlùès, sò thè wàìt thè ùsèr sèès ànd thè wàìt thè sèrvèr àpplìès cànnòt drìft àpàrt. [[#fàìlùrè-stàtès #tèlèphòny]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn rèmòvè à mèthòd? ••••••••** Rèmòvàl rèqùìrès thè ùsèr tò hàvè àlrèàdy vèrìfìèd à sècònd fàctòr ìn thè cùrrènt sèssìòn. Thè sèrvèr rèfùsès tò rèmòvè thè làst àctìvè mèthòd. Àn àdmìnìstràtòr càn rèsèt ànòthèr àccòùnt's sècònd-fàctòr mèthòds thròùgh àn àùdìtèd pròcèss thàt rècòrds whò pèrfòrmèd thè rèsèt. [[#pèrmìssìòns #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Bàckùp còdè lìfècyclè. •••••••** [Bàckùp còdès](#lògìn/bàckùp-còdès) àrè gènèràtèd às à sèt òf èìght àftèr thè fìrst mèthòd ìs ènròllèd. Gènèràtìng à nèw sèt dèlètès thè prèvìòùs ònè, sò còdès rècòrdèd èàrlìèr stòp wòrkìng àt thàt mòmènt. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à dàtàbàsè còpy shòw? ••••••••••** Thè mèthòd nàmès òn èàch àccòùnt ànd whèthèr èàch ìs àctìvè àrè stòrèd wìthòùt èncryptìòn. Thè còùnt òf ùnùsèd bàckùp còdès ìs àlsò ùnèncryptèd. À còpy òf thè dàtàbàsè rèvèàls whìch typès òf sècònd fàctòr èàch àccòùnt ùsès ànd hòw màny bàckùp còdès rèmàìn. Mèthòd sècrèts (TÒTP kèys, pàsskèy crèdèntìàls) àrè stòrèd ìn èncryptèd còlùmns, ànd bàckùp còdès àrè stòrèd ònly às hàshès. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè rèst òf thè ùnèncryptèd schèmà. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dòès rèmòvìng èmàìl às à sècònd fàctòr chàngè whèrè nòtìfìcàtìòns gò? •••••••••••••••••••••** Thè àddrèss ùsèd fòr èmàìl sècònd-fàctòr còdès ànd thè àddrèss ùsèd fòr nòtìfìcàtìòn dèlìvèry àrè mànàgèd sèpàràtèly. Rèmòvìng thè èmàìl mèthòd clèàrs thè sècònd-fàctòr àddrèss wìthòùt àffèctìng thè nòtìfìcàtìòn àddrèss. [Nòtìfìcàtìòn prèfèrèncès](#sèttìngs/nòtìfìcàtìòns) còvèrs whèrè thè nòtìfìcàtìòn àddrèss còmès fròm. [[#sèrvèr-hòlds #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè ènròllmènt sèrvìcè ànd còòldòwn cònstànts. ••••••••••••••** Ènròllmènt, vèrìfìcàtìòn, ànd rèmòvàl lìvè ìn thè \`ènròll\` ànd \`mèthòds\` ròùtèrs ìn \`pàckàgès/sèrvèr/src/ròùtès/twò-fàctòr.ts\`, bàckèd by \`pàckàgès/sèrvèr/src/àùth/twò-fàctòr-sèrvìcè.ts\`. Thè còòldòwn cònstànts àrè ìn \`pàckàgès/shàrèd/src/schèmàs/àùth.ts\`. [Nòtìfìcàtìòn prèfèrèncès](#sèttìngs/nòtìfìcàtìòns) còvèrs thè nòtìfìcàtìòn àddrèss. [[#sèrvèr-hòlds]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The user enrolls and removes second-factor methods from settings. An account can hold several active methods at once, and each one works independently. [Two ..." |
*
* @param {Demo_Narrative_Settings_Twofa_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_settings_twofa_body = /** @type {((inputs?: Demo_Narrative_Settings_Twofa_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Settings_Twofa_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_settings_twofa_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_settings_twofa_body(inputs)
	return en_demo_narrative_settings_twofa_body(inputs)
});