/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Field_Config_BodyInputs */

const en_demo_narrative_admin_field_config_body = /** @type {(inputs: Demo_Narrative_Admin_Field_Config_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A field's settings hold everything about that one field, and what they offer changes with its type. Every field carries a label and optional help text in each language and a switch making it required; text fields add a placeholder and a maximum length, the two pick types add an editable option list, and the standalone checkbox adds a switch that makes ticking it a condition of submitting. [[#client-data]]
**What a role is for.** Ten roles tell the rest of the system what an answer means rather than leaving it an unlabeled string, so a phone number becomes the case's contact method and a chosen option becomes the queue the case lands in. Seven of them identify or reach a person, covering phone and email contact, real name, pronouns, contact safety, consent and language preference, and each may appear at most once in a form. A role and a widget are validated as a pair in the browser and again on the server, and when the chosen role cannot work with the current widget the sheet states the conflict, blocks the field from being finished and offers the widget that fits, carrying the options and the queue mapping across to it. [Fields on the public form](#client-intake/fields) covers what a visitor does with them. [[#client-data #metadata]]
**What a role leaves in the clear.** The role and the queues an option routes to are plaintext columns, because the submitting browser resolves them and the server routes on them, so a database dump shows that a form asks for a phone number and which queue a given option leads to without showing what the question said or what anyone answered. The list of people a field escalates to is encrypted under the server's operational key rather than left beside them. [Queues](#admin-people/queues) covers what a queue grants. [[#server-holds #metadata]]
**When a field appears.** A field can be set to appear only when answers to earlier fields match stated values, written as groups of conditions where a group passes when all of its rules hold and the field appears when any group passes. Only a single pick, a multiple pick, a checkbox, a text field, a long text field or a date can drive a rule, and only fields that come earlier in the form, so a form cannot build a loop out of two fields waiting on each other. [[#client-data]]
**Changing a field's type.** Switching type stashes the configuration of the type being left, so switching back restores it rather than starting over, and it clears only a role the new type cannot carry at all, keeping one that is merely in conflict so the sheet can explain it instead of dropping the routing work without a word. [[#failure-states]]
**The role tables and where they are enforced.** \`ROLE_WIDGET_COMPATIBILITY\` and \`UNIQUE_ROLES_PER_FORM\` in \`packages/shared/src/schemas/intake-forms.ts\` are the single definition of both rules, read by \`packages/client/src/lib/components/admin/IntakeFieldConfigSheet.svelte\` for the live conflict notice and applied again as refinements on the save schema, so a form assembled outside the editor is held to the same pairs. [[#client-data]]`)
};

const es_demo_narrative_admin_field_config_body = /** @type {(inputs: Demo_Narrative_Admin_Field_Config_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La configuración de un campo contiene todo lo relativo a ese campo, y lo que ofrece cambia según su tipo. Todo campo lleva una etiqueta y un texto de ayuda opcional en cada idioma y un interruptor que lo hace obligatorio; los campos de texto añaden un texto de ejemplo y una longitud máxima, los dos tipos de selección añaden una lista de opciones editable, y la casilla suelta añade un interruptor que convierte marcarla en condición para enviar. [[#client-data]]
**Para qué sirve un rol.** Diez roles le dicen al resto del sistema qué significa una respuesta en lugar de dejarla como una cadena sin etiquetar, de modo que un número de teléfono pasa a ser la vía de contacto del caso y una opción elegida pasa a ser la cola en la que aterriza. Siete de ellos identifican o alcanzan a una persona, y abarcan el contacto por teléfono y por correo, el nombre real, los pronombres, la seguridad del contacto, el consentimiento y la preferencia de idioma, y cada uno puede aparecer como mucho una vez en un formulario. Un rol y un widget se validan como pareja en el navegador y otra vez en el servidor, y cuando el rol elegido no puede funcionar con el widget actual la hoja expone el conflicto, impide dar por terminado el campo y ofrece el widget que sí encaja, arrastrando hasta él las opciones y la correspondencia de colas. [Los campos del formulario público](#client-intake/fields) trata lo que hace un visitante con ellos. [[#client-data #metadata]]
**Qué deja un rol en claro.** El rol y las colas a las que encamina una opción son columnas en texto plano, porque el navegador que envía los resuelve y el servidor encamina con ellos, así que un volcado de la base de datos muestra que un formulario pide un número de teléfono y a qué cola lleva una opción dada, sin mostrar qué decía la pregunta ni qué respondió nadie. La lista de personas a las que escala un campo se cifra con la clave operativa del servidor en vez de quedarse junto a ellos. [Colas](#admin-people/queues) trata lo que concede una cola. [[#server-holds #metadata]]
**Cuándo aparece un campo.** Un campo se puede configurar para aparecer solo cuando las respuestas a campos anteriores coinciden con valores indicados, escrito como grupos de condiciones en los que un grupo se cumple cuando se cumplen todas sus reglas y el campo aparece cuando se cumple algún grupo. Solo una selección simple, una selección múltiple, una casilla, un campo de texto, uno de texto largo o una fecha pueden gobernar una regla, y solo campos que vayan antes en el formulario, así que un formulario no puede formar un ciclo con dos campos esperándose el uno al otro. [[#client-data]]
**Cambiar el tipo de un campo.** Cambiar de tipo guarda la configuración del tipo que se abandona, de modo que volver a él la restaura en lugar de empezar de cero, y borra únicamente un rol que el tipo nuevo no pueda llevar en absoluto, conservando el que solo está en conflicto para que la hoja pueda explicarlo en vez de descartar el trabajo de encaminamiento sin decir nada. [[#failure-states]]
**Las tablas de roles y dónde se aplican.** \`ROLE_WIDGET_COMPATIBILITY\` y \`UNIQUE_ROLES_PER_FORM\`, en \`packages/shared/src/schemas/intake-forms.ts\`, son la única definición de ambas reglas, la lee \`packages/client/src/lib/components/admin/IntakeFieldConfigSheet.svelte\` para el aviso de conflicto en vivo y vuelve a aplicarse como refinamiento del esquema de guardado, así que un formulario ensamblado fuera del editor queda sujeto a las mismas parejas. [[#client-data]]`)
};

const en_xa2_demo_narrative_admin_field_config_body = /** @type {(inputs: Demo_Narrative_Admin_Field_Config_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè fìèld sèttìngs shèèt còntròls thè cònfìgùràtìòn fòr à sìnglè fìèld, ànd ìts còntènts chàngè wìth thè fìèld typè. Èvèry fìèld hàs à làbèl ànd òptìònàl hèlp tèxt fòr èàch lòcàlè ànd à rèqùìrèd tògglè. Tèxt fìèlds hàvè à plàcèhòldèr ànd màxìmùm lèngth, thè twò pìck typès hàvè èdìtàblè òptìòn lìsts, ànd thè stàndàlònè chèckbòx hàs à tògglè thàt rèqùìrès thè vìsìtòr tò chèck ìt bèfòrè sùbmìttìng.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ròlès. ••** Tèn ròlès tèll thè rèst òf thè systèm whàt à fìèld's ànswèr mèàns ràthèr thàn lèàvìng ìt àn ùnlàbèlèd strìng. Ròlès thàt ìdèntìfy à pèrsòn, sùch às phònè còntàct òr rèàl nàmè, mày àppèàr àt mòst òncè pèr fòrm. Thè ròlè ànd wìdgèt typè àrè vàlìdàtèd às à pàìr, ànd whèn à chòsèn ròlè dòès nòt fìt thè cùrrènt wìdgèt thè shèèt èxplàìns thè cònflìct ànd òffèrs thè còmpàtìblè wìdgèt às à còrrèctìòn.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn ìt àppèàrs. •••••** À fìèld càn bè sèt tò àppèàr ònly whèn ànswèrs òn èàrlìèr fìèlds màtch spècìfìèd vàlùès, èxprèssèd às gròùps òf còndìtìòns.
 ••••••••••••••••••••••••••••••••••••••**Pèrsìstèncè. ••••** Chàngìng thè fìèld typè prèsèrvès thè cònfìgùràtìòn òf thè typè bèìng lèft sò swìtchìng bàck dòès nòt lòsè wòrk, ànd clèàrs ònly à ròlè thè nèw typè cànnòt càrry. •••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A field's settings hold everything about that one field, and what they offer changes with its type. Every field carries a label and optional help text in eac..." |
*
* @param {Demo_Narrative_Admin_Field_Config_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_field_config_body = /** @type {((inputs?: Demo_Narrative_Admin_Field_Config_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Field_Config_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_field_config_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_field_config_body(inputs)
	return en_demo_narrative_admin_field_config_body(inputs)
});