/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Intake_Forms_BodyInputs */

const en_demo_narrative_admin_intake_forms_body = /** @type {(inputs: Demo_Narrative_Admin_Intake_Forms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The intake forms list holds every form the organization has built. A single switch on this page turns web intake off for the whole organization. [[#portal]]
**Saving and publishing.** A form is created inactive and cannot receive submissions until the user activates it. Activation is a separate operation from saving, so editing a live form cannot take it off the public address by accident. Deactivating a form stops new submissions and leaves both the form and every answer already collected in place. [Field list](#admin-forms/builder) covers what a save writes. [[#failure-states #portal]]
**What answers the public address when no form is active?** When web intake is on and no custom form carries the default flag, a built-in two-field form (a name and a message) takes its place, answering in the language the visitor's browser requests. That built-in form has its own toggle, separate from the organization-wide switch. [The intake page](#client-intake/form) covers what the visitor is asked. [[#portal #client-data]]
**What does the server store in the clear?** A form's internal name, its slug, its active and default flags, its destination queue and its field count are plaintext columns. The form's field labels, configuration, description, and messages are plaintext by design, because they are served to unauthenticated visitors on the public page. A database dump reveals the number of forms, their internal names, their public addresses, how many fields each carries, and the wording of those fields. [The trust boundary](#deep-dive/the-trust-boundary) covers the rest of that picture. [[#server-holds #metadata]]
**How are answers protected?** Answers carry a per-case key wrapped to individual accounts. A user who builds and publishes a form gains nothing toward reading the submissions it collects. [Response cards](#admin-responses/responses) covers reading the answers. [[#encryption #keys]]
**Duplicating and deleting.** Duplicating a form mints fresh field and option keys, appends a suffix to the name and clears the slug. The copy shares no key material with the original and cannot collide on a public address. Deleting a form is refused once any response exists, so removing the form cannot remove the answers it collected. [[#failure-states #encryption]]
**Who can manage forms and who can read answers?** Managing forms requires the Manage intake forms permission. Reading answers requires the View intake responses permission. Neither carries the other, so a user who publishes a form cannot read its submissions unless the organization also grants View intake responses. [The permission system](#deep-dive/the-permission-system) covers moving either permission. [[#permissions]]
**The service and the audit trail.** \`packages/server/src/portal/intake-form-service.ts\` holds the whole-form save, the slug uniqueness check, the atomic default swap and the single writer of the active flag. \`packages/server/src/routes/intake-forms.ts\` gates every procedure on one of the two permissions. Saving, deleting, activating, deactivating, and both the web-intake and built-in-default toggles write audit entries. [[#server-holds #failure-states]]`)
};

const es_demo_narrative_admin_intake_forms_body = /** @type {(inputs: Demo_Narrative_Admin_Intake_Forms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La lista de formularios de admisión contiene cada formulario que la organización ha creado. Un interruptor en esta página desactiva la admisión web de toda la organización. [[#portal]]
**Guardado y publicación.** Un formulario se crea inactivo y no puede recibir envíos hasta que la persona usuaria lo activa. La activación es una operación separada del guardado, de modo que editar un formulario en uso no puede retirarlo de la dirección pública por descuido. Desactivar un formulario detiene los envíos nuevos y deja en su sitio tanto el formulario como todas las respuestas recogidas. [Lista de campos](#admin-forms/builder) trata lo que escribe un guardado. [[#failure-states #portal]]
**¿Qué responde en la dirección pública cuando no hay formulario activo?** Con la admisión web encendida y sin formulario propio que lleve la marca de predeterminado, un formulario integrado de dos campos (un nombre y un mensaje) ocupa su lugar, respondiendo en el idioma que solicite el navegador del visitante. Ese formulario integrado tiene su propio interruptor, aparte del interruptor de la organización. [La página de admisión](#client-intake/form) trata lo que se le pide al visitante. [[#portal #client-data]]
**¿Qué almacena el servidor en claro?** El nombre interno de un formulario, su slug, sus marcas de activo y predeterminado, su cola de destino y su número de campos son columnas en texto plano. Las etiquetas de los campos, su configuración y la descripción y los mensajes del formulario son texto plano por diseño, porque se sirven a visitantes no autenticados en la página pública. Un volcado de base de datos revela cuántos formularios tiene la organización, sus nombres internos, sus direcciones públicas, cuántos campos lleva cada uno y la redacción de esos campos. [La frontera de confianza](#deep-dive/the-trust-boundary) trata el resto de ese panorama. [[#server-holds #metadata]]
**¿Cómo se protegen las respuestas?** Las respuestas llevan una clave por caso envuelta para cuentas concretas. La persona usuaria que construye y publica un formulario no gana acceso alguno a los envíos que este recoge. [Tarjetas de respuesta](#admin-responses/responses) trata la lectura de las respuestas. [[#encryption #keys]]
**Duplicar y borrar.** Duplicar un formulario acuña claves nuevas de campo y de opción, añade un sufijo al nombre y vacía el slug. La copia no comparte material de claves con el original y no puede coincidir en una dirección pública. Borrar un formulario se rechaza en cuanto existe una respuesta, de modo que eliminar el formulario no puede eliminar las respuestas que recogió. [[#failure-states #encryption]]
**¿Quién puede gestionar formularios y quién puede leer respuestas?** Gestionar formularios requiere el permiso Gestionar formularios de ingreso. Leer respuestas requiere el permiso Ver respuestas de ingreso. Ninguno arrastra al otro, así que la persona usuaria que publica un formulario no puede leer los envíos a menos que la organización también conceda Ver respuestas de ingreso. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo trasladar cualquiera de los dos. [[#permissions]]
**El servicio y el rastro de auditoría.** \`packages/server/src/portal/intake-form-service.ts\` contiene el guardado completo del formulario, la comprobación de unicidad del slug, el cambio atómico de predeterminado y el único escritor de la marca de activo. \`packages/server/src/routes/intake-forms.ts\` protege cada procedimiento con uno de los dos permisos. Guardar, borrar, activar, desactivar y los dos interruptores (admisión web y formulario integrado predeterminado) escriben entradas de auditoría. [[#server-holds #failure-states]]`)
};

const en_xa2_demo_narrative_admin_intake_forms_body = /** @type {(inputs: Demo_Narrative_Admin_Intake_Forms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ìntàkè fòrms lìst hòlds èvèry fòrm thè òrgànìzàtìòn hàs bùìlt. À sìnglè swìtch òn thìs pàgè tùrns wèb ìntàkè òff fòr thè whòlè òrgànìzàtìòn. [[#pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••**Sàvìng ànd pùblìshìng. •••••••** À fòrm ìs crèàtèd ìnàctìvè ànd cànnòt rècèìvè sùbmìssìòns ùntìl thè ùsèr àctìvàtès ìt. Àctìvàtìòn ìs à sèpàràtè òpèràtìòn fròm sàvìng, sò èdìtìng à lìvè fòrm cànnòt tàkè ìt òff thè pùblìc àddrèss by àccìdènt. Dèàctìvàtìng à fòrm stòps nèw sùbmìssìòns ànd lèàvès bòth thè fòrm ànd èvèry ànswèr àlrèàdy còllèctèd ìn plàcè. [Fìèld lìst](#àdmìn-fòrms/bùìldèr) còvèrs whàt à sàvè wrìtès. [[#fàìlùrè-stàtès #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt ànswèrs thè pùblìc àddrèss whèn nò fòrm ìs àctìvè? •••••••••••••••••** Whèn wèb ìntàkè ìs òn ànd nò cùstòm fòrm càrrìès thè dèfàùlt flàg, à bùìlt-ìn twò-fìèld fòrm (à nàmè ànd à mèssàgè) tàkès ìts plàcè, ànswèrìng ìn thè làngùàgè thè vìsìtòr's bròwsèr rèqùèsts. Thàt bùìlt-ìn fòrm hàs ìts òwn tògglè, sèpàràtè fròm thè òrgànìzàtìòn-wìdè swìtch. [Thè ìntàkè pàgè](#clìènt-ìntàkè/fòrm) còvèrs whàt thè vìsìtòr ìs àskèd. [[#pòrtàl #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè ìn thè clèàr? ••••••••••••** À fòrm's ìntèrnàl nàmè, ìts slùg, ìts àctìvè ànd dèfàùlt flàgs, ìts dèstìnàtìòn qùèùè ànd ìts fìèld còùnt àrè plàìntèxt còlùmns. Thè fòrm's fìèld làbèls, cònfìgùràtìòn, dèscrìptìòn, ànd mèssàgès àrè plàìntèxt by dèsìgn, bècàùsè thèy àrè sèrvèd tò ùnàùthèntìcàtèd vìsìtòrs òn thè pùblìc pàgè. À dàtàbàsè dùmp rèvèàls thè nùmbèr òf fòrms, thèìr ìntèrnàl nàmès, thèìr pùblìc àddrèssès, hòw màny fìèlds èàch càrrìès, ànd thè wòrdìng òf thòsè fìèlds. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè rèst òf thàt pìctùrè. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw àrè ànswèrs pròtèctèd? ••••••••** Ànswèrs càrry à pèr-càsè kèy wràppèd tò ìndìvìdùàl àccòùnts. À ùsèr whò bùìlds ànd pùblìshès à fòrm gàìns nòthìng tòwàrd rèàdìng thè sùbmìssìòns ìt còllècts. [Rèspònsè càrds](#àdmìn-rèspònsès/rèspònsès) còvèrs rèàdìng thè ànswèrs. [[#èncryptìòn #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dùplìcàtìng ànd dèlètìng. ••••••••** Dùplìcàtìng à fòrm mìnts frèsh fìèld ànd òptìòn kèys, àppènds à sùffìx tò thè nàmè ànd clèàrs thè slùg. Thè còpy shàrès nò kèy màtèrìàl wìth thè òrìgìnàl ànd cànnòt còllìdè òn à pùblìc àddrèss. Dèlètìng à fòrm ìs rèfùsèd òncè àny rèspònsè èxìsts, sò rèmòvìng thè fòrm cànnòt rèmòvè thè ànswèrs ìt còllèctèd. [[#fàìlùrè-stàtès #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn mànàgè fòrms ànd whò càn rèàd ànswèrs? ••••••••••••••** Mànàgìng fòrms rèqùìrès thè Mànàgè ìntàkè fòrms pèrmìssìòn. Rèàdìng ànswèrs rèqùìrès thè Vìèw ìntàkè rèspònsès pèrmìssìòn. Nèìthèr càrrìès thè òthèr, sò à ùsèr whò pùblìshès à fòrm cànnòt rèàd ìts sùbmìssìòns ùnlèss thè òrgànìzàtìòn àlsò grànts Vìèw ìntàkè rèspònsès. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs mòvìng èìthèr pèrmìssìòn. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè sèrvìcè ànd thè àùdìt tràìl. ••••••••••** \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-fòrm-sèrvìcè.ts\` hòlds thè whòlè-fòrm sàvè, thè slùg ùnìqùènèss chèck, thè àtòmìc dèfàùlt swàp ànd thè sìnglè wrìtèr òf thè àctìvè flàg. \`pàckàgès/sèrvèr/src/ròùtès/ìntàkè-fòrms.ts\` gàtès èvèry pròcèdùrè òn ònè òf thè twò pèrmìssìòns. Sàvìng, dèlètìng, àctìvàtìng, dèàctìvàtìng, ànd bòth thè wèb-ìntàkè ànd bùìlt-ìn-dèfàùlt tògglès wrìtè àùdìt èntrìès. [[#sèrvèr-hòlds #fàìlùrè-stàtès]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The intake forms list holds every form the organization has built. A single switch on this page turns web intake off for the whole organization. [[#portal]] ..." |
*
* @param {Demo_Narrative_Admin_Intake_Forms_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_intake_forms_body = /** @type {((inputs?: Demo_Narrative_Admin_Intake_Forms_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Intake_Forms_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_intake_forms_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_intake_forms_body(inputs)
	return en_demo_narrative_admin_intake_forms_body(inputs)
});