/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Voicemails_BodyInputs */

const en_demo_narrative_topic_voicemails_body = /** @type {(inputs: Demo_Narrative_Topic_Voicemails_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A voicemail on the organization's line becomes a follow-up on the client's ticket, with audio the browser opens and the server cannot. [[#telephony #encryption]]
**What happens to the audio before it is stored?** The server fetches the recording from the provider. It seals the recording with the ticket key, writes the ciphertext to blob storage, then asks the provider to delete both the recording and the call log it belongs to. The audio exists in plaintext only for that one handler call, in buffers the code zeroes. [Call log](#ticket-detail/call-log) covers the provider cleanup that follows, and [The telephony relay](#deep-dive/the-telephony-relay) covers the rules that endpoint works under. [[#server-holds #telephony #retention]]
**What happens when a recording cannot be matched?** A voicemail whose call cannot be matched to a client or a queue is sealed to the organization key and held in quarantine for an administrator to route by hand, rather than stored in the open or discarded. [Voicemail quarantine](#admin-comms/quarantine) covers what an administrator can do with one. [[#failure-states #encryption]]
**Playback and metadata.** Fetching the ciphertext requires the Download case media permission. The endpoint hands back ciphertext and decrypts nothing itself. The browser decodes the audio on the device, and the decrypted sound exists in one tab and is dropped when the follow-up is closed. The row beside the audio holds its size, its duration and its times in plaintext, so a database dump shows that a ticket received a ninety-second voicemail on a given evening. [[#permissions #privacy #metadata]]
**How is a recording bound to its ticket?** A recording is either sealed directly under the ticket key or sealed under a key of its own that the ticket key unwraps. Either way the audio is bound to its row identifier, so ciphertext moved to another row fails to open. A copy is sealed to the client's channel key when one is active, so the client can hear their own voicemail on their private page. [How encryption works](#deep-dive/how-encryption-works) covers the binding. [[#keys #encryption #portal]]
**The recording handler and the player.** \`packages/server/src/telephony/recording-handler.ts\` runs the store-then-delete sequence, \`voicemail-quarantine.ts\` holds the unroutable ones, and the row comes from \`027_create_recordings.ts\`. The player is \`VoicemailPlayer.svelte\`, which takes an injected decrypt callback built in \`packages/client/src/lib/tickets/recording-decrypt.ts\` so the ticket thread and the client's own thread share one player. [[#client-data]]`)
};

const es_demo_narrative_topic_voicemails_body = /** @type {(inputs: Demo_Narrative_Topic_Voicemails_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un mensaje de voz en la línea de la organización se convierte en un seguimiento en el ticket del cliente, con un audio que el navegador abre y el servidor no puede abrir. [[#telephony #encryption]]
**¿Qué ocurre con el audio antes de almacenarse?** El servidor obtiene la grabación del proveedor. La sella con la clave del ticket, escribe el texto cifrado en almacenamiento de blobs y pide al proveedor que elimine tanto la grabación como el registro de llamada al que pertenece. El audio existe en texto plano solo durante esa única llamada del handler, en buffers que el código pone a cero. [Registro de llamadas](#ticket-detail/call-log) trata la limpieza del proveedor que sigue, y [El relay de telefonía](#deep-dive/the-telephony-relay) trata las reglas bajo las que trabaja ese endpoint. [[#server-holds #telephony #retention]]
**¿Qué ocurre cuando una grabación no puede emparejarse?** Un mensaje de voz cuya llamada no puede emparejarse con un cliente o una cola se sella con la clave de la organización y se retiene en cuarentena para que una persona administradora lo enrute a mano, en lugar de almacenarse sin cifrar o descartarse. [Cuarentena de correo de voz](#admin-comms/quarantine) trata lo que una persona administradora puede hacer con uno. [[#failure-states #encryption]]
**Reproducción y metadatos.** Obtener el texto cifrado requiere el permiso Descargar archivos del caso. El endpoint devuelve texto cifrado y no descifra nada. El navegador decodifica el audio en el dispositivo, y el sonido descifrado existe en una pestaña y se descarta cuando se cierra el seguimiento. La fila junto al audio guarda su tamaño, su duración y sus marcas de tiempo en texto plano, así que un volcado de la base de datos muestra que un ticket recibió un mensaje de voz de noventa segundos en una tarde determinada. [[#permissions #privacy #metadata]]
**¿Cómo se vincula una grabación a su ticket?** Una grabación se sella directamente con la clave del ticket o se sella con una clave propia que la clave del ticket desenvuelve. En ambos casos el audio está vinculado al identificador de su fila, así que un texto cifrado movido a otra fila no se abre. Una copia se sella con la clave de canal del cliente cuando hay uno activo, para que el cliente pueda escuchar su propio mensaje de voz en su página privada. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la vinculación. [[#keys #encryption #portal]]
**El handler de grabación y el reproductor.** \`packages/server/src/telephony/recording-handler.ts\` ejecuta la secuencia de almacenar y eliminar, \`voicemail-quarantine.ts\` retiene los que no pueden enrutarse, y la fila proviene de \`027_create_recordings.ts\`. El reproductor es \`VoicemailPlayer.svelte\`, que recibe un callback de descifrado inyectado construido en \`packages/client/src/lib/tickets/recording-decrypt.ts\` para que el hilo del ticket y el hilo propio del cliente compartan un reproductor. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_voicemails_body = /** @type {(inputs: Demo_Narrative_Topic_Voicemails_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À vòìcèmàìl òn thè òrgànìzàtìòn's lìnè bècòmès à fòllòw-ùp òn thè clìènt's tìckèt, wìth àùdìò thè bròwsèr òpèns ànd thè sèrvèr cànnòt. [[#tèlèphòny #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns tò thè àùdìò bèfòrè ìt ìs stòrèd? ••••••••••••••** Thè sèrvèr fètchès thè rècòrdìng fròm thè pròvìdèr. Ìt sèàls thè rècòrdìng wìth thè tìckèt kèy, wrìtès thè cìphèrtèxt tò blòb stòràgè, thèn àsks thè pròvìdèr tò dèlètè bòth thè rècòrdìng ànd thè càll lòg ìt bèlòngs tò. Thè àùdìò èxìsts ìn plàìntèxt ònly fòr thàt ònè hàndlèr càll, ìn bùffèrs thè còdè zèròès. [Càll lòg](#tìckèt-dètàìl/càll-lòg) còvèrs thè pròvìdèr clèànùp thàt fòllòws, ànd [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs thè rùlès thàt èndpòìnt wòrks ùndèr. [[#sèrvèr-hòlds #tèlèphòny #rètèntìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn à rècòrdìng cànnòt bè màtchèd? •••••••••••••••** À vòìcèmàìl whòsè càll cànnòt bè màtchèd tò à clìènt òr à qùèùè ìs sèàlèd tò thè òrgànìzàtìòn kèy ànd hèld ìn qùàràntìnè fòr àn àdmìnìstràtòr tò ròùtè by hànd, ràthèr thàn stòrèd ìn thè òpèn òr dìscàrdèd. [Vòìcèmàìl qùàràntìnè](#àdmìn-còmms/qùàràntìnè) còvèrs whàt àn àdmìnìstràtòr càn dò wìth ònè. [[#fàìlùrè-stàtès #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Plàybàck ànd mètàdàtà. •••••••** Fètchìng thè cìphèrtèxt rèqùìrès thè Dòwnlòàd càsè mèdìà pèrmìssìòn. Thè èndpòìnt hànds bàck cìphèrtèxt ànd dècrypts nòthìng ìtsèlf. Thè bròwsèr dècòdès thè àùdìò òn thè dèvìcè, ànd thè dècryptèd sòùnd èxìsts ìn ònè tàb ànd ìs dròppèd whèn thè fòllòw-ùp ìs clòsèd. Thè ròw bèsìdè thè àùdìò hòlds ìts sìzè, ìts dùràtìòn ànd ìts tìmès ìn plàìntèxt, sò à dàtàbàsè dùmp shòws thàt à tìckèt rècèìvèd à nìnèty-sècònd vòìcèmàìl òn à gìvèn èvènìng. [[#pèrmìssìòns #prìvàcy #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìs à rècòrdìng bòùnd tò ìts tìckèt? ••••••••••••** À rècòrdìng ìs èìthèr sèàlèd dìrèctly ùndèr thè tìckèt kèy òr sèàlèd ùndèr à kèy òf ìts òwn thàt thè tìckèt kèy ùnwràps. Èìthèr wày thè àùdìò ìs bòùnd tò ìts ròw ìdèntìfìèr, sò cìphèrtèxt mòvèd tò ànòthèr ròw fàìls tò òpèn. À còpy ìs sèàlèd tò thè clìènt's chànnèl kèy whèn ònè ìs àctìvè, sò thè clìènt càn hèàr thèìr òwn vòìcèmàìl òn thèìr prìvàtè pàgè. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè bìndìng. [[#kèys #èncryptìòn #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rècòrdìng hàndlèr ànd thè plàyèr. ••••••••••••** \`pàckàgès/sèrvèr/src/tèlèphòny/rècòrdìng-hàndlèr.ts\` rùns thè stòrè-thèn-dèlètè sèqùèncè, \`vòìcèmàìl-qùàràntìnè.ts\` hòlds thè ùnròùtàblè ònès, ànd thè ròw còmès fròm \`027_crèàtè_rècòrdìngs.ts\`. Thè plàyèr ìs \`VòìcèmàìlPlàyèr.svèltè\`, whìch tàkès àn ìnjèctèd dècrypt càllbàck bùìlt ìn \`pàckàgès/clìènt/src/lìb/tìckèts/rècòrdìng-dècrypt.ts\` sò thè tìckèt thrèàd ànd thè clìènt's òwn thrèàd shàrè ònè plàyèr. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A voicemail on the organization's line becomes a follow-up on the client's ticket, with audio the browser opens and the server cannot. [[#telephony #encrypti..." |
*
* @param {Demo_Narrative_Topic_Voicemails_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_voicemails_body = /** @type {((inputs?: Demo_Narrative_Topic_Voicemails_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Voicemails_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_voicemails_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_voicemails_body(inputs)
	return en_demo_narrative_topic_voicemails_body(inputs)
});