/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Deep_Search_BodyInputs */

const en_demo_narrative_topic_deep_search_body = /** @type {(inputs: Demo_Narrative_Topic_Deep_Search_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Searching inside a ticket matches against the text already decrypted in the browser. No search term is sent to the server, no result is reported back, and the request that fetches older follow-ups carries a cursor and a page size with no words, so the server cannot tell a search from ordinary reading. [[#privacy #client-data]]
**What starts the sweep?** A term of at least two characters that matches nothing among the loaded follow-ups starts a sweep that pages the rest of the thread in, oldest first, and matches each page as it arrives. The count it reports is follow-ups loaded against the ticket's total, so it measures how much of the thread has been brought in rather than how many matches exist. Changing the term or closing the search stops the sweep. [[#failure-states]]
**What can a search not find?** A follow-up whose content the account holds no key for is skipped. A follow-up still being decrypted is also skipped at that instant, but the match list is reactive over the decrypt cache, so each result appears as its decrypt completes without the user re-running the search. In the timeline view the search runs over the timeline's own set, which carries notes and recorded events in full and withholds plain message bodies. A word spoken in a message is found in the [Conversation thread](#ticket-detail/conversation) and not in the timeline. [Timeline view](#ticket-detail/timeline) covers why those bodies are withheld. [[#keys #failure-states]]
**The matcher and the paging loop.** \`searchFollowUps\` in \`packages/client/src/lib/tickets/ticket-detail-utils.ts\` builds the haystack from the decrypt cache, skipping any follow-up whose plaintext is absent or is the decrypt error sentinel, and hands the rest to the shared fuzzy matcher, so a near miss and a different word order still match. The paging loop is \`createDeepSearch\` in \`packages/client/src/lib/composables/ticket-detail/create-deep-search.svelte.ts\`. [[#client-data]]`)
};

const es_demo_narrative_topic_deep_search_body = /** @type {(inputs: Demo_Narrative_Topic_Deep_Search_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Buscar dentro de un ticket compara contra el texto ya descifrado en el navegador. No se envía ningún término de búsqueda al servidor, no se reporta ningún resultado, y la solicitud que obtiene seguimientos anteriores lleva un cursor y un tamaño de página sin palabras, por lo que el servidor no puede distinguir una búsqueda de una lectura ordinaria. [[#privacy #client-data]]
**¿Qué inicia el barrido?** Un término de al menos dos caracteres que no coincide con nada entre los seguimientos cargados inicia un barrido que trae el resto del hilo, del más antiguo al más reciente, y compara cada página conforme llega. El conteo que reporta es seguimientos cargados contra el total del ticket, por lo que mide cuánto del hilo se ha traído en lugar de cuántas coincidencias existen. Cambiar el término o cerrar la búsqueda detiene el barrido. [[#failure-states]]
**¿Qué no puede encontrar una búsqueda?** Un seguimiento cuyo contenido la cuenta no tiene clave para abrir se omite. Un seguimiento que aún se está descifrando también se omite en ese instante, pero la lista de coincidencias es reactiva sobre la caché de descifrado, por lo que cada resultado aparece conforme su descifrado se completa sin que se deba repetir la búsqueda. En la vista de línea de tiempo la búsqueda se ejecuta sobre el conjunto propio de la línea de tiempo, que incluye notas y eventos registrados completos y omite los cuerpos de mensajes. Una palabra dicha en un mensaje se encuentra en el [Hilo de conversación](#ticket-detail/conversation) y no en la línea de tiempo. [Vista de línea de tiempo](#ticket-detail/timeline) explica por qué esos cuerpos se omiten. [[#keys #failure-states]]
**El comparador y el bucle de paginación.** \`searchFollowUps\` en \`packages/client/src/lib/tickets/ticket-detail-utils.ts\` construye el pajar desde la caché de descifrado, omitiendo todo seguimiento cuyo texto plano está ausente o es el centinela de error de descifrado, y pasa el resto al comparador difuso compartido, por lo que una coincidencia aproximada y un orden de palabras diferente aún coinciden. El bucle de paginación es \`createDeepSearch\` en \`packages/client/src/lib/composables/ticket-detail/create-deep-search.svelte.ts\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_deep_search_body = /** @type {(inputs: Demo_Narrative_Topic_Deep_Search_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Sèàrchìng ìnsìdè à tìckèt màtchès àgàìnst thè tèxt àlrèàdy dècryptèd ìn thè bròwsèr. Nò sèàrch tèrm ìs sènt tò thè sèrvèr, nò rèsùlt ìs rèpòrtèd bàck, ànd thè rèqùèst thàt fètchès òldèr fòllòw-ùps càrrìès à cùrsòr ànd à pàgè sìzè wìth nò wòrds, sò thè sèrvèr cànnòt tèll à sèàrch fròm òrdìnàry rèàdìng. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt stàrts thè swèèp? •••••••** À tèrm òf àt lèàst twò chàràctèrs thàt màtchès nòthìng àmòng thè lòàdèd fòllòw-ùps stàrts à swèèp thàt pàgès thè rèst òf thè thrèàd ìn, òldèst fìrst, ànd màtchès èàch pàgè às ìt àrrìvès. Thè còùnt ìt rèpòrts ìs fòllòw-ùps lòàdèd àgàìnst thè tìckèt's tòtàl, sò ìt mèàsùrès hòw mùch òf thè thrèàd hàs bèèn bròùght ìn ràthèr thàn hòw màny màtchès èxìst. Chàngìng thè tèrm òr clòsìng thè sèàrch stòps thè swèèp. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt càn à sèàrch nòt fìnd? •••••••••** À fòllòw-ùp whòsè còntènt thè àccòùnt hòlds nò kèy fòr ìs skìppèd. À fòllòw-ùp stìll bèìng dècryptèd ìs àlsò skìppèd àt thàt ìnstànt, bùt thè màtch lìst ìs rèàctìvè òvèr thè dècrypt càchè, sò èàch rèsùlt àppèàrs às ìts dècrypt còmplètès wìthòùt thè ùsèr rè-rùnnìng thè sèàrch. Ìn thè tìmèlìnè vìèw thè sèàrch rùns òvèr thè tìmèlìnè's òwn sèt, whìch càrrìès nòtès ànd rècòrdèd èvènts ìn fùll ànd wìthhòlds plàìn mèssàgè bòdìès. À wòrd spòkèn ìn à mèssàgè ìs fòùnd ìn thè [Cònvèrsàtìòn thrèàd](#tìckèt-dètàìl/cònvèrsàtìòn) ànd nòt ìn thè tìmèlìnè. [Tìmèlìnè vìèw](#tìckèt-dètàìl/tìmèlìnè) còvèrs why thòsè bòdìès àrè wìthhèld. [[#kèys #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè màtchèr ànd thè pàgìng lòòp. ••••••••••** \`sèàrchFòllòwÙps\` ìn \`pàckàgès/clìènt/src/lìb/tìckèts/tìckèt-dètàìl-ùtìls.ts\` bùìlds thè hàystàck fròm thè dècrypt càchè, skìppìng àny fòllòw-ùp whòsè plàìntèxt ìs àbsènt òr ìs thè dècrypt èrròr sèntìnèl, ànd hànds thè rèst tò thè shàrèd fùzzy màtchèr, sò à nèàr mìss ànd à dìffèrènt wòrd òrdèr stìll màtch. Thè pàgìng lòòp ìs \`crèàtèDèèpSèàrch\` ìn \`pàckàgès/clìènt/src/lìb/còmpòsàblès/tìckèt-dètàìl/crèàtè-dèèp-sèàrch.svèltè.ts\`. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Searching inside a ticket matches against the text already decrypted in the browser. No search term is sent to the server, no result is reported back, and th..." |
*
* @param {Demo_Narrative_Topic_Deep_Search_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_deep_search_body = /** @type {((inputs?: Demo_Narrative_Topic_Deep_Search_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Deep_Search_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_deep_search_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_deep_search_body(inputs)
	return en_demo_narrative_topic_deep_search_body(inputs)
});