/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Clients_BodyInputs */

const en_demo_narrative_admin_clients_body = /** @type {(inputs: Demo_Narrative_Admin_Clients_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The client list holds every client record the organization has created, paginated twenty-five at a time, with a ticket count beside each record. The alias is organization-key ciphertext that only a browser with that key can read. The phone number and the email address are encrypted with the server's operational key. The server holds that key, so the running server can read both values back at any time. That is what allows it to dial the number and send the mail. The encryption protects contact values in a database dump or backup taken without the key. It does not protect them from the server itself. [[#client-data #encryption]]
**What does the server return without View client PII?** The server decrypts each contact value, builds a masked form, and zeroes the buffer before the response leaves. A phone number becomes the last four digits behind three asterisks; an email address becomes its first character and domain. A user with the View client PII permission receives the full formatted value instead. The masked form is built server-side and the full value never reaches a browser that lacks the permission. [The trust boundary](#deep-dive/the-trust-boundary) covers why contact values sit on a different key from ticket content. [[#privacy #server-holds]]
**Who can change a client record?** Viewing the list requires the View clients permission. Renaming a record requires the Edit client alias permission. Changing a phone number or email address requires the Edit client contact permission, or the user must be assigned to a ticket belonging to that client. [Contact correction](#ticket-detail/correction-status) covers the flow that carries a correction from the client into the record. Deleting a client permanently removes the client row, its tickets, portal channels, and attached files, and writes an audit row carrying counts. Deletion requires the Delete clients permission. [Audit log](#admin-logs/audit) covers what an audit row holds. [[#permissions #client-data]]
**How does exact search work?** The browser hashes the search term with the organization key and sends the hash to the server, which matches it against a stored alias hash on each record. The server compares hashes without learning the term. Alias hashes are backfilled proactively so that every record is searchable. Anything shorter than an exact alias match filters the records already loaded in the browser. [[#privacy #metadata]]
**Merged records.** A client record merged into another drops out of the list. It keeps its own row and its own tickets. [Merging clients](#admin-people/client-merge) covers what a merge changes. [[#client-data]]
**The client route and its service.** \`packages/server/src/routes/clients.ts\` defines the tRPC router. \`packages/server/src/clients/client-service.ts\` holds listing, alias editing, phone replacement, and duplicate detection. Masking runs in \`phoneForViewer\` and \`emailForViewer\` in \`packages/server/src/utils/sql.ts\`. Deletion delegates to \`purgeClient\` in \`packages/server/src/jobs/pii-retention.ts\`, which cascades through tickets, merge events, portal channels, and orphaned phone and email rows inside a transaction. [[#client-data]]`)
};

const es_demo_narrative_admin_clients_body = /** @type {(inputs: Demo_Narrative_Admin_Clients_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La lista de clientes contiene todos los registros de clientes que la organización ha creado, paginados de veinticinco en veinticinco, con un conteo de tickets junto a cada registro. El alias es texto cifrado con la clave de la organización que solo un navegador con esa clave puede leer. El número de teléfono y la dirección de correo están cifrados con la clave operativa del servidor. El servidor posee esa clave, por lo que puede leer ambos valores en cualquier momento. Eso es lo que le permite marcar el número y enviar el correo. El cifrado protege los valores de contacto en un volcado de base de datos o una copia de seguridad tomada sin la clave, pero no los protege del propio servidor. [[#client-data #encryption]]
**¿Qué devuelve el servidor sin Ver datos personales del cliente?** El servidor descifra cada valor de contacto, construye una forma enmascarada y pone a cero el búfer antes de enviar la respuesta. Un número de teléfono queda como los últimos cuatro dígitos detrás de tres asteriscos; una dirección de correo queda como su primer carácter y el dominio. Con el permiso Ver datos personales del cliente se recibe el valor completo formateado. La forma enmascarada se construye en el servidor y el valor completo no llega a un navegador que no tiene el permiso. [La frontera de confianza](#deep-dive/the-trust-boundary) trata por qué los valores de contacto están en una clave distinta al contenido de los tickets. [[#privacy #server-holds]]
**¿Quién puede modificar un registro de cliente?** Ver la lista requiere el permiso Ver clientes. Renombrar un registro requiere el permiso Editar alias del cliente. Cambiar un número de teléfono o una dirección de correo requiere el permiso Editar contacto del cliente, o la persona usuaria debe estar asignada a un ticket que pertenezca a ese cliente. [Corrección de contacto](#ticket-detail/correction-status) trata el flujo que lleva una corrección del cliente al registro. Eliminar un cliente borra permanentemente la fila del cliente, sus tickets, canales del portal y archivos adjuntos, y escribe una fila de auditoría con conteos. La eliminación requiere el permiso Eliminar clientes. [Registro de auditoría](#admin-logs/audit) trata lo que contiene una fila de auditoría. [[#permissions #client-data]]
**¿Cómo funciona la búsqueda exacta?** El navegador convierte el término de búsqueda en un hash con la clave de la organización y envía el hash al servidor, que lo compara contra un hash de alias almacenado en cada registro. El servidor compara hashes sin conocer el término. Los hashes de alias se rellenan de forma proactiva para que todos los registros sean buscables. Cualquier búsqueda que no sea un alias exacto filtra los registros ya cargados en el navegador. [[#privacy #metadata]]
**Registros fusionados.** Un registro de cliente fusionado en otro desaparece de la lista. Conserva su propia fila y sus propios tickets. [Fusionar clientes](#admin-people/client-merge) trata qué cambia una fusión. [[#client-data]]
**La ruta de clientes y su servicio.** \`packages/server/src/routes/clients.ts\` define el router tRPC. \`packages/server/src/clients/client-service.ts\` contiene el listado, la edición de alias, el reemplazo de teléfono y la detección de duplicados. El enmascaramiento se ejecuta en \`phoneForViewer\` y \`emailForViewer\` en \`packages/server/src/utils/sql.ts\`. La eliminación delega en \`purgeClient\` en \`packages/server/src/jobs/pii-retention.ts\`, que recorre tickets, eventos de fusión, canales del portal y filas huérfanas de teléfono y correo dentro de una transacción. [[#client-data]]`)
};

const en_xa2_demo_narrative_admin_clients_body = /** @type {(inputs: Demo_Narrative_Admin_Clients_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè clìènt lìst hòlds èvèry clìènt rècòrd thè òrgànìzàtìòn hàs crèàtèd, pàgìnàtèd twènty-fìvè àt à tìmè, wìth à tìckèt còùnt bèsìdè èàch rècòrd. Thè àlìàs ìs òrgànìzàtìòn-kèy cìphèrtèxt thàt ònly à bròwsèr wìth thàt kèy càn rèàd. Thè phònè nùmbèr ànd thè èmàìl àddrèss àrè èncryptèd wìth thè sèrvèr's òpèràtìònàl kèy. Thè sèrvèr hòlds thàt kèy, sò thè rùnnìng sèrvèr càn rèàd bòth vàlùès bàck àt àny tìmè. Thàt ìs whàt àllòws ìt tò dìàl thè nùmbèr ànd sènd thè màìl. Thè èncryptìòn pròtècts còntàct vàlùès ìn à dàtàbàsè dùmp òr bàckùp tàkèn wìthòùt thè kèy. Ìt dòès nòt pròtèct thèm fròm thè sèrvèr ìtsèlf. [[#clìènt-dàtà #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr rètùrn wìthòùt Vìèw clìènt PÌÌ? ••••••••••••••••** Thè sèrvèr dècrypts èàch còntàct vàlùè, bùìlds à màskèd fòrm, ànd zèròès thè bùffèr bèfòrè thè rèspònsè lèàvès. À phònè nùmbèr bècòmès thè làst fòùr dìgìts bèhìnd thrèè àstèrìsks; àn èmàìl àddrèss bècòmès ìts fìrst chàràctèr ànd dòmàìn. À ùsèr wìth thè Vìèw clìènt PÌÌ pèrmìssìòn rècèìvès thè fùll fòrmàttèd vàlùè ìnstèàd. Thè màskèd fòrm ìs bùìlt sèrvèr-sìdè ànd thè fùll vàlùè nèvèr rèàchès à bròwsèr thàt làcks thè pèrmìssìòn. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs why còntàct vàlùès sìt òn à dìffèrènt kèy fròm tìckèt còntènt. [[#prìvàcy #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn chàngè à clìènt rècòrd? ••••••••••** Vìèwìng thè lìst rèqùìrès thè Vìèw clìènts pèrmìssìòn. Rènàmìng à rècòrd rèqùìrès thè Èdìt clìènt àlìàs pèrmìssìòn. Chàngìng à phònè nùmbèr òr èmàìl àddrèss rèqùìrès thè Èdìt clìènt còntàct pèrmìssìòn, òr thè ùsèr mùst bè àssìgnèd tò à tìckèt bèlòngìng tò thàt clìènt. [Còntàct còrrèctìòn](#tìckèt-dètàìl/còrrèctìòn-stàtùs) còvèrs thè flòw thàt càrrìès à còrrèctìòn fròm thè clìènt ìntò thè rècòrd. Dèlètìng à clìènt pèrmànèntly rèmòvès thè clìènt ròw, ìts tìckèts, pòrtàl chànnèls, ànd àttàchèd fìlès, ànd wrìtès àn àùdìt ròw càrryìng còùnts. Dèlètìòn rèqùìrès thè Dèlètè clìènts pèrmìssìòn. [Àùdìt lòg](#àdmìn-lògs/àùdìt) còvèrs whàt àn àùdìt ròw hòlds. [[#pèrmìssìòns #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw dòès èxàct sèàrch wòrk? •••••••••** Thè bròwsèr hàshès thè sèàrch tèrm wìth thè òrgànìzàtìòn kèy ànd sènds thè hàsh tò thè sèrvèr, whìch màtchès ìt àgàìnst à stòrèd àlìàs hàsh òn èàch rècòrd. Thè sèrvèr còmpàrès hàshès wìthòùt lèàrnìng thè tèrm. Àlìàs hàshès àrè bàckfìllèd pròàctìvèly sò thàt èvèry rècòrd ìs sèàrchàblè. Ànythìng shòrtèr thàn àn èxàct àlìàs màtch fìltèrs thè rècòrds àlrèàdy lòàdèd ìn thè bròwsèr. [[#prìvàcy #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Mèrgèd rècòrds. •••••** À clìènt rècòrd mèrgèd ìntò ànòthèr dròps òùt òf thè lìst. Ìt kèèps ìts òwn ròw ànd ìts òwn tìckèts. [Mèrgìng clìènts](#àdmìn-pèòplè/clìènt-mèrgè) còvèrs whàt à mèrgè chàngès. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè clìènt ròùtè ànd ìts sèrvìcè. ••••••••••** \`pàckàgès/sèrvèr/src/ròùtès/clìènts.ts\` dèfìnès thè tRPC ròùtèr. \`pàckàgès/sèrvèr/src/clìènts/clìènt-sèrvìcè.ts\` hòlds lìstìng, àlìàs èdìtìng, phònè rèplàcèmènt, ànd dùplìcàtè dètèctìòn. Màskìng rùns ìn \`phònèFòrVìèwèr\` ànd \`èmàìlFòrVìèwèr\` ìn \`pàckàgès/sèrvèr/src/ùtìls/sql.ts\`. Dèlètìòn dèlègàtès tò \`pùrgèClìènt\` ìn \`pàckàgès/sèrvèr/src/jòbs/pìì-rètèntìòn.ts\`, whìch càscàdès thròùgh tìckèts, mèrgè èvènts, pòrtàl chànnèls, ànd òrphànèd phònè ànd èmàìl ròws ìnsìdè à trànsàctìòn. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The client list holds every client record the organization has created, paginated twenty-five at a time, with a ticket count beside each record. The alias is..." |
*
* @param {Demo_Narrative_Admin_Clients_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_clients_body = /** @type {((inputs?: Demo_Narrative_Admin_Clients_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Clients_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_clients_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_clients_body(inputs)
	return en_demo_narrative_admin_clients_body(inputs)
});