/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Intake_Form_BodyInputs */

const en_demo_narrative_client_intake_form_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Form_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The intake page takes a request for help from someone who has no account and no prior relationship to the organization, which is why it asks for nothing before it starts. [[#portal #privacy]]
**The built-in form.** An organization that has published nothing gets a form asking for a name, a message and how it should reach the visitor, with the name optional and the message required. Its labels and placeholders carry English and Spanish text, so a visitor reading in Spanish reads Spanish field text rather than Spanish page furniture around English questions. [Contact method and follow-up options](#client-intake/contact-method) covers the reach-back step. [[#client-data]]
**Forms an organization publishes.** A published form replaces the built-in one with its own fields and carries its own link name, so several forms can be live at once and each one names its own destination queue. A link name matching no published form is answered with the same not-available notice that web intake being switched off produces, so a guessed address confirms nothing about what else exists. [Custom form fields](#client-intake/fields) covers what those fields can be, and [Intake forms](#admin-org/intake-forms) covers the organization-wide switches. [[#portal #metadata]]
**Content the organization writes.** A form can carry an introduction, a banner image, a message shown after a successful submission and a message shown once it closes. The three text pieces are stored encrypted under a key derived from the organization's public key, which anyone can derive, so they are protected in a database dump and not against a running server. The banner is stored encrypted too and decrypted by the server on request, because a browser cannot hand an ordinary image tag anything else. [The form builder](#admin-forms/builder) covers how that content is authored. [[#encryption #server-holds]]
**What the page leaves on the device.** The form writes nothing to local storage, session storage or cookies, and what the visitor typed stays in memory until the tab closes. The language picker sets a cookie and the colour-scheme toggle writes to local storage, so a visitor who touches either leaves a trace the form alone would not. The page is an ordinary navigation, so a browser history entry stays behind. [Quick exit](#client-portal/quick-exit) covers the control that leaves the page in a hurry. [[#privacy #client-data]]
**When the page has no form to show.** A not-available notice stands in when web intake is switched off for the organization, when the link name matches no published form, and when the built-in form has been turned off with no custom default in its place. A separate notice explains the requirement when scripting is disabled, because the encryption runs in the browser. A failure to load or to decrypt the form shows an error with a retry, and a missing organization public key says that the page cannot encrypt and suggests calling. [Closed form](#client-intake/closed-form) covers the state a closing date produces. [[#failure-states]]
**The resolver, the page body and the asset route.** \`resolvePublicForm\` in \`packages/server/src/portal/intake-form-service.ts\` answers the public read and passes field labels and configs through as ciphertext. The page is \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\`, whose built-in field set is \`DEFAULT_INTAKE_FORM\`. Banner images are served by \`packages/server/src/routes/form-assets.ts\`, which decrypts through \`decryptFormAssetBlob\` and restricts the response type to PNG, JPEG and WebP. [[#server-holds #portal]]`)
};

const es_demo_narrative_client_intake_form_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Form_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La página de admisión recoge una petición de ayuda de alguien que no tiene cuenta ni relación previa con la organización, y por eso no pide nada antes de empezar. [[#portal #privacy]]
**El formulario integrado.** Una organización que no ha publicado nada dispone de un formulario que pide un nombre, un mensaje y la forma de contactar con el visitante, con el nombre opcional y el mensaje obligatorio. Sus etiquetas y textos de ayuda llevan texto en inglés y en español, de modo que quien lea en español lee las preguntas en español y no un marco en español alrededor de preguntas en inglés. [Método de contacto y opciones de seguimiento](#client-intake/contact-method) trata el paso de contacto. [[#client-data]]
**Los formularios que publica una organización.** Un formulario publicado sustituye al integrado con sus propios campos y lleva su propio nombre de enlace, así que puede haber varios activos a la vez y cada uno nombra su propia cola de destino. Un nombre de enlace que no corresponde a ningún formulario publicado recibe el mismo aviso de no disponible que produce desactivar la admisión web, de modo que una dirección adivinada no confirma nada sobre lo que existe. [Campos de formularios personalizados](#client-intake/fields) trata qué pueden ser esos campos, y [Formularios de admisión](#admin-org/intake-forms) trata los interruptores de toda la organización. [[#portal #metadata]]
**El contenido que redacta la organización.** Un formulario puede llevar una introducción, una imagen de portada, un mensaje que se muestra tras un envío correcto y un mensaje que se muestra cuando ya está cerrado. Las tres piezas de texto se guardan cifradas con una clave derivada de la clave pública de la organización, que cualquiera puede derivar, así que están protegidas en un volcado de la base de datos y no frente a un servidor en funcionamiento. La portada también se guarda cifrada y la descifra el servidor cuando se pide, porque a una etiqueta de imagen corriente no se le puede entregar otra cosa. [El constructor de formularios](#admin-forms/builder) trata cómo se redacta ese contenido. [[#encryption #server-holds]]
**Lo que la página deja en el dispositivo.** El formulario no escribe nada en almacenamiento local, almacenamiento de sesión ni cookies, y lo que el visitante escribió permanece en memoria hasta que se cierra la pestaña. El selector de idioma fija una cookie y el conmutador de esquema de color escribe en el almacenamiento local, así que quien use cualquiera de los dos deja un rastro que el formulario por sí solo no dejaría. La página es una navegación corriente, de modo que queda una entrada en el historial del navegador. [Salida rápida](#client-portal/quick-exit) trata el control que abandona la página con prisa. [[#privacy #client-data]]
**Cuando la página no tiene ningún formulario que mostrar.** Un aviso de no disponible ocupa su lugar cuando la admisión web está desactivada para la organización, cuando el nombre de enlace no corresponde a ningún formulario publicado y cuando el formulario integrado se ha desactivado sin un formulario personalizado predeterminado que lo sustituya. Un aviso aparte explica el requisito cuando el scripting está desactivado, porque el cifrado se ejecuta en el navegador. Un fallo al cargar o al descifrar el formulario muestra un error con la opción de reintentar, y la ausencia de la clave pública de la organización indica que la página no puede cifrar y sugiere llamar. [Formulario cerrado](#client-intake/closed-form) trata el estado que produce una fecha de cierre. [[#failure-states]]
**El resolutor, el cuerpo de la página y la ruta de recursos.** \`resolvePublicForm\`, en \`packages/server/src/portal/intake-form-service.ts\`, responde a la lectura pública y devuelve las etiquetas y configuraciones de campo como texto cifrado sin abrirlas. La página es \`packages/client/src/routes/(client)/intake/IntakeFormBody.svelte\`, cuyo conjunto de campos integrado es \`DEFAULT_INTAKE_FORM\`. Las imágenes de portada las sirve \`packages/server/src/routes/form-assets.ts\`, que descifra mediante \`decryptFormAssetBlob\` y restringe el tipo de respuesta a PNG, JPEG y WebP. [[#server-holds #portal]]`)
};

const en_xa2_demo_narrative_client_intake_form_body = /** @type {(inputs: Demo_Narrative_Client_Intake_Form_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ìntàkè fòrm ìs thè fìrst thìng à pèrsòn sèèkìng hèlp sèès, ànd nò lògìn òr àccòùnt ìs nèèdèd tò ùsè ìt.
 •••••••••••••••••••••••••••••••••**Qùìck èxìt. ••••** Thè qùìck èxìt còntròl ìs rèndèrèd òncè by thè clìènt shèll ràthèr thàn by èàch pàgè, sò ìt ìs prèsènt òn èvèry clìènt pàgè ànd à nèw pàgè cànnòt fòrgèt ìt. Thè fùll sèqùèncè ànd ìts sàfèty nèt àrè dòcùmèntèd ìn thè qùìck èxìt èntry.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dèfàùlt fòrm. ••••** Èvèry òrgànìzàtìòn hàs à bùìlt-ìn ìntàkè fòrm wìth à nàmè fìèld ànd à còntàct mèthòd sèlèctòr. Àdmìnìstràtòrs càn pùblìsh cùstòm fòrms thàt rèplàcè ìt wìth thèìr òwn fìèlds, ànd èàch cùstòm fòrm gèts ìts òwn shàrèàblè lìnk.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Òrg-àùthòrèd còntènt. •••••••** Thè ìntàkè fòrm càn càrry à cùstòm ìntròdùctìòn wrìttèn by àn àdmìnìstràtòr ìn thè fòrm bùìldèr, à bànnèr ìmàgè, ànd à cùstòm sùbmìssìòn mèssàgè thàt rèplàcès thè dèfàùlt cònfìrmàtìòn còpy. Thè ìntròdùctìòn ànd thè sùbmìssìòn mèssàgè àrè èncryptèd àt rèst ànd dècryptèd by thè vìsìtòr's bròwsèr fòr dìsplày, whìlè thè bànnèr ìmàgè ìs dècryptèd by thè sèrvèr òn thè fly ànd sèrvèd às àn òrdìnàry ìmàgè.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dèvìcè tràcès. •••••** Thè ìntàkè fòrm ìtsèlf wrìtès nòthìng tò lòcàl stòràgè, sèssìòn stòràgè, òr còòkìès, ànd ànythìng thè vìsìtòr typèd stàys ìn mèmòry ònly ùntìl thè tàb clòsès. Thè làngùàgè pìckèr ànd thè còlòùr-schèmè tògglè ìn thè dràwèr dò wrìtè pèrsìstènt stàtè: thè làngùàgè pìckèr sèts à còòkìè ànd thè còlòùr-schèmè tògglè wrìtès tò lòcàl stòràgè, sò à vìsìtòr whò ùsès èìthèr ònè lèàvès à tràcè thè fòrm àlònè wòùld nòt. À bròwsèr hìstòry èntry àlsò rèmàìns bècàùsè thè pàgè ìs à nòrmàl nàvìgàtìòn.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ìf ìt fàìls. ••••** Thè ìntàkè fòrm shòws àn èrròr wìth à rètry òptìòn whèn à nètwòrk òr dècryptìòn fàìlùrè prèvènts lòàdìng, ànd ìf thè òrgànìzàtìòn's pùblìc kèy ìs nòt àvàìlàblè àt àll ìt tèlls thè vìsìtòr ìt cànnòt èncrypt ànd sùggèsts càllìng ìnstèàd.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèn ìt ìs èmpty. ••••••** Thè ìntàkè pàgè shòws à nòtìcè thàt thè fòrm ìs nòt àvàìlàblè whèn ìntàkè ìs dìsàblèd àt thè òrgànìzàtìòn lèvèl, whèn thè fòrm àddrèss dòès nòt màtch à pùblìshèd fòrm, òr whèn thè bùìlt-ìn dèfàùlt fòrm hàs bèèn tùrnèd òff, ànd whèn JàvàScrìpt ìs dìsàblèd à sèpàràtè nòtìcè èxplàìns thàt thè fòrm nèèds ìt tò èncrypt. ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The intake page takes a request for help from someone who has no account and no prior relationship to the organization, which is why it asks for nothing befo..." |
*
* @param {Demo_Narrative_Client_Intake_Form_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_intake_form_body = /** @type {((inputs?: Demo_Narrative_Client_Intake_Form_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Intake_Form_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_intake_form_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_intake_form_body(inputs)
	return en_demo_narrative_client_intake_form_body(inputs)
});