/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Client_Portal_Upgrade_BodyInputs */

const en_demo_narrative_client_portal_upgrade_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Upgrade_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A client on a secure link can strengthen protection without involving the organization, either by adding a passphrase or by creating an account. [[#portal #privacy]]
**Who is offered which path?** A bare link offers both options. A passphrase-protected link offers only account creation, and the client gains access to the contact details the organization has on file. Contact details are withheld from a bare link because a key derived from the URL alone would hand them to anyone who held the URL. A client already on an account has no further option. [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers the three tiers. [[#portal #permissions]]
**Adding a passphrase.** The browser suggests five random words from a published word list, and the client can replace them. On submission the browser derives a fresh channel key from the passphrase and re-seals every message the device can still open under that key. Messages the device cannot open, such as ones sealed to a previous key the session no longer holds, are left behind. Before submission, the form tells the client how many messages cannot be carried over, with a way to go back. After success, if any messages were left behind, a notice says so. The server accepts the change only when the re-sealed messages and the skipped messages together account for every message in the channel, so a message arriving mid-upgrade aborts the operation. The link address keeps working afterward but no longer opens the conversation without the passphrase. [[#keys #encryption #failure-states]]
**Creating an account.** The client picks a username (minimum three characters) and a password (minimum eight characters). The password goes through the same key derivation that staff sign-in uses. One operation revokes the previous channel, creates the account and a new channel, moves the re-sealed messages across, and deletes anything the device could not open, since those messages were already unreadable to the client. Before submission, the form tells the client how many messages will be deleted, with a way to go back. The secure link ceases to work at that point. [Account sign in](#client-account/sign-in) covers what the account provides afterward. [[#keys #portal]]
**What does the server store afterward?** The passphrase and the password both stay in the browser. The server records a public key, a login-token hash, and a key check value after either upgrade. Usernames are kept as keyed hashes, not as readable text. [How keys are derived](#deep-dive/how-keys-are-derived) covers the derivation protocol. [[#server-holds #keys #metadata]]
**The upgrade components and the coverage guard.** The chooser is \`UpgradeChooser.svelte\`, the two forms are \`AddPassphraseForm.svelte\` and \`AccountCreateForm.svelte\` in \`packages/client/src/lib/portal/\`, and the re-seal helpers are \`add-passphrase-crypto.ts\` and \`account-crypto.ts\` beside them. The word suggestion draws from the EFF large wordlist (7776 entries) using rejection sampling over a 13-bit range. The coverage guard is \`hasExactMessageCoverage\` in \`packages/server/src/portal/message-coverage.ts\`, called by \`addPassphrase\` in \`channel-service.ts\` and by \`upgradeFromSecureLink\` in \`account-service.ts\`. The skipped-message notice after either path is \`portal_reseal_skipped_note\`. [[#portal #encryption]]`)
};

const es_demo_narrative_client_portal_upgrade_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Upgrade_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un cliente con un enlace seguro puede reforzar la protección sin intervención de la organización, añadiendo una frase de paso o creando una cuenta. [[#portal #privacy]]
**¿A quién se ofrece cada vía?** Un enlace simple ofrece las dos opciones. Un enlace ya protegido con frase de paso ofrece solo la creación de cuenta, y el cliente obtiene acceso a los datos de contacto que la organización tiene registrados. A un enlace simple se le niegan esos datos porque una clave derivada solo de la URL se los entregaría a cualquiera que la tuviera. Un cliente que ya tiene cuenta no tiene más opciones. [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata los tres niveles. [[#portal #permissions]]
**Añadir una frase de paso.** El navegador sugiere cinco palabras al azar de una lista de palabras publicada, y el cliente puede reemplazarlas. Al enviar, el navegador deriva una nueva clave de canal a partir de la frase de paso y vuelve a sellar cada mensaje que el dispositivo aún puede abrir con esa clave. Los mensajes que el dispositivo no puede abrir, como los sellados con una clave anterior que la sesión ya no tiene, quedan atrás. Antes del envío, el formulario indica al cliente cuántos mensajes no se pueden trasladar, con la opción de volver atrás. Tras el resultado, si algún mensaje quedó atrás, un aviso lo indica. El servidor acepta el cambio solo cuando los mensajes resellados y los omitidos juntos cubren todos los mensajes del canal, de modo que un mensaje que llegue a mitad de la operación la aborta. La dirección del enlace sigue funcionando después, pero ya no abre la conversación sin la frase de paso. [[#keys #encryption #failure-states]]
**Crear una cuenta.** El cliente elige un nombre de usuario (mínimo tres caracteres) y una contraseña (mínimo ocho caracteres). La contraseña recorre la misma derivación de claves que usa el inicio de sesión del personal. Una operación revoca el canal anterior, crea la cuenta y un canal nuevo, traslada los mensajes resellados y elimina los que el dispositivo no pudo abrir, ya que esos mensajes eran ilegibles para el cliente. Antes del envío, el formulario indica al cliente cuántos mensajes se eliminarán, con la opción de volver atrás. El enlace seguro deja de funcionar en ese momento. [Inicio de sesión de cuenta](#client-account/sign-in) trata lo que ofrece la cuenta a partir de entonces. [[#keys #portal]]
**¿Qué guarda el servidor después?** Tanto la frase de paso como la contraseña permanecen en el navegador. El servidor registra una clave pública, un hash del token de inicio de sesión y un valor de comprobación de clave tras cualquiera de las dos mejoras. Los nombres de usuario se guardan como hashes con clave, no como texto legible. [Cómo se derivan las claves](#deep-dive/how-keys-are-derived) trata el protocolo de derivación. [[#server-holds #keys #metadata]]
**Los componentes de mejora y la guarda de cobertura.** El selector es \`UpgradeChooser.svelte\`, los dos formularios son \`AddPassphraseForm.svelte\` y \`AccountCreateForm.svelte\` en \`packages/client/src/lib/portal/\`, y los auxiliares de resellado son \`add-passphrase-crypto.ts\` y \`account-crypto.ts\` junto a ellos. La sugerencia de palabras toma de la lista grande EFF (7776 entradas) usando muestreo por rechazo en un rango de 13 bits. La guarda de cobertura es \`hasExactMessageCoverage\` en \`packages/server/src/portal/message-coverage.ts\`, invocada por \`addPassphrase\` en \`channel-service.ts\` y por \`upgradeFromSecureLink\` en \`account-service.ts\`. El aviso de mensajes omitidos tras cualquiera de las dos vías es \`portal_reseal_skipped_note\`. [[#portal #encryption]]`)
};

const en_xa2_demo_narrative_client_portal_upgrade_body = /** @type {(inputs: Demo_Narrative_Client_Portal_Upgrade_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À clìènt òn à sècùrè lìnk càn strèngthèn pròtèctìòn wìthòùt ìnvòlvìng thè òrgànìzàtìòn, èìthèr by àddìng à pàssphràsè òr by crèàtìng àn àccòùnt. [[#pòrtàl #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••**Whò ìs òffèrèd whìch pàth? ••••••••** À bàrè lìnk òffèrs bòth òptìòns. À pàssphràsè-pròtèctèd lìnk òffèrs ònly àccòùnt crèàtìòn, ànd thè clìènt gàìns àccèss tò thè còntàct dètàìls thè òrgànìzàtìòn hàs òn fìlè. Còntàct dètàìls àrè wìthhèld fròm à bàrè lìnk bècàùsè à kèy dèrìvèd fròm thè ÙRL àlònè wòùld hànd thèm tò ànyònè whò hèld thè ÙRL. À clìènt àlrèàdy òn àn àccòùnt hàs nò fùrthèr òptìòn. [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thè thrèè tìèrs. [[#pòrtàl #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àddìng à pàssphràsè. ••••••** Thè bròwsèr sùggèsts fìvè ràndòm wòrds fròm à pùblìshèd wòrd lìst, ànd thè clìènt càn rèplàcè thèm. Òn sùbmìssìòn thè bròwsèr dèrìvès à frèsh chànnèl kèy fròm thè pàssphràsè ànd rè-sèàls èvèry mèssàgè thè dèvìcè càn stìll òpèn ùndèr thàt kèy. Mèssàgès thè dèvìcè cànnòt òpèn, sùch às ònès sèàlèd tò à prèvìòùs kèy thè sèssìòn nò lòngèr hòlds, àrè lèft bèhìnd. Bèfòrè sùbmìssìòn, thè fòrm tèlls thè clìènt hòw màny mèssàgès cànnòt bè càrrìèd òvèr, wìth à wày tò gò bàck. Àftèr sùccèss, ìf àny mèssàgès wèrè lèft bèhìnd, à nòtìcè sàys sò. Thè sèrvèr àccèpts thè chàngè ònly whèn thè rè-sèàlèd mèssàgès ànd thè skìppèd mèssàgès tògèthèr àccòùnt fòr èvèry mèssàgè ìn thè chànnèl, sò à mèssàgè àrrìvìng mìd-ùpgràdè àbòrts thè òpèràtìòn. Thè lìnk àddrèss kèèps wòrkìng àftèrwàrd bùt nò lòngèr òpèns thè cònvèrsàtìòn wìthòùt thè pàssphràsè. [[#kèys #èncryptìòn #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Crèàtìng àn àccòùnt. ••••••** Thè clìènt pìcks à ùsèrnàmè (mìnìmùm thrèè chàràctèrs) ànd à pàsswòrd (mìnìmùm èìght chàràctèrs). Thè pàsswòrd gòès thròùgh thè sàmè kèy dèrìvàtìòn thàt stàff sìgn-ìn ùsès. Ònè òpèràtìòn rèvòkès thè prèvìòùs chànnèl, crèàtès thè àccòùnt ànd à nèw chànnèl, mòvès thè rè-sèàlèd mèssàgès àcròss, ànd dèlètès ànythìng thè dèvìcè còùld nòt òpèn, sìncè thòsè mèssàgès wèrè àlrèàdy ùnrèàdàblè tò thè clìènt. Bèfòrè sùbmìssìòn, thè fòrm tèlls thè clìènt hòw màny mèssàgès wìll bè dèlètèd, wìth à wày tò gò bàck. Thè sècùrè lìnk cèàsès tò wòrk àt thàt pòìnt. [Àccòùnt sìgn ìn](#clìènt-àccòùnt/sìgn-ìn) còvèrs whàt thè àccòùnt pròvìdès àftèrwàrd. [[#kèys #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè àftèrwàrd? ••••••••••••** Thè pàssphràsè ànd thè pàsswòrd bòth stày ìn thè bròwsèr. Thè sèrvèr rècòrds à pùblìc kèy, à lògìn-tòkèn hàsh, ànd à kèy chèck vàlùè àftèr èìthèr ùpgràdè. Ùsèrnàmès àrè kèpt às kèyèd hàshès, nòt às rèàdàblè tèxt. [Hòw kèys àrè dèrìvèd](#dèèp-dìvè/hòw-kèys-àrè-dèrìvèd) còvèrs thè dèrìvàtìòn pròtòcòl. [[#sèrvèr-hòlds #kèys #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè ùpgràdè còmpònènts ànd thè còvèràgè gùàrd. ••••••••••••••** Thè chòòsèr ìs \`ÙpgràdèChòòsèr.svèltè\`, thè twò fòrms àrè \`ÀddPàssphràsèFòrm.svèltè\` ànd \`ÀccòùntCrèàtèFòrm.svèltè\` ìn \`pàckàgès/clìènt/src/lìb/pòrtàl/\`, ànd thè rè-sèàl hèlpèrs àrè \`àdd-pàssphràsè-cryptò.ts\` ànd \`àccòùnt-cryptò.ts\` bèsìdè thèm. Thè wòrd sùggèstìòn dràws fròm thè ÈFF làrgè wòrdlìst (7776 èntrìès) ùsìng rèjèctìòn sàmplìng òvèr à 13-bìt ràngè. Thè còvèràgè gùàrd ìs \`hàsÈxàctMèssàgèCòvèràgè\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/mèssàgè-còvèràgè.ts\`, càllèd by \`àddPàssphràsè\` ìn \`chànnèl-sèrvìcè.ts\` ànd by \`ùpgràdèFròmSècùrèLìnk\` ìn \`àccòùnt-sèrvìcè.ts\`. Thè skìppèd-mèssàgè nòtìcè àftèr èìthèr pàth ìs \`pòrtàl_rèsèàl_skìppèd_nòtè\`. [[#pòrtàl #èncryptìòn]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A client on a secure link can strengthen protection without involving the organization, either by adding a passphrase or by creating an account. [[#portal #p..." |
*
* @param {Demo_Narrative_Client_Portal_Upgrade_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_client_portal_upgrade_body = /** @type {((inputs?: Demo_Narrative_Client_Portal_Upgrade_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Client_Portal_Upgrade_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_client_portal_upgrade_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_client_portal_upgrade_body(inputs)
	return en_demo_narrative_client_portal_upgrade_body(inputs)
});