/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Call_Log_BodyInputs */

const en_demo_narrative_admin_call_log_body = /** @type {(inputs: Demo_Narrative_Admin_Call_Log_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Every call and voicemail written to a ticket appears in the call history, sorted newest first and paged fifty at a time. The call history holds and shows no phone number. Each row identifies the client by an alias the browser decrypts with the organization key. The remaining columns are plaintext the server already holds. [[#telephony #privacy]]
**What does a row carry?** Each row carries the call's direction, outcome, duration, timestamp, and the ticket the call belongs to. The list draws from call and voicemail follow-ups on ticket threads, not from provider records. A follow-up that has been deleted from the thread does not appear. [[#metadata]]
**Who has access to the call history?** Viewing requires the View reports permission. The query applies no queue filter, so a user with that permission sees calls on tickets in queues the user does not belong to. The alias still requires the organization key to decrypt, and the ticket behind a row still requires the ticket key. A row can therefore name a call the user cannot open. [The permission system](#deep-dive/the-permission-system) covers how each permission is granted. [[#permissions #encryption]]
**What does the plaintext reveal?** The plaintext columns expose the direction, duration, outcome and timing of every call the organization placed or received, with aliases standing in for phone numbers. That pattern reveals when the organization is active, how long calls last and how often they fail. Call content and phone numbers are absent. [The trust boundary](#deep-dive/the-trust-boundary) covers what the other plaintext columns give away. [[#server-holds #metadata]]
**What happens when a ticket is purged?** Call and voicemail rows are follow-ups on the ticket, so the retention purge removes them together. A closed ticket that has aged past its retention window leaves no call history behind. [Data retention](#deep-dive/data-retention) covers the purge. [[#retention]]
**The call log query and its filters.** \`callLog\` in \`packages/server/src/tickets/reports-service.ts\` selects follow-ups of type \`phone_call\` and \`voicemail\` where \`deleted_at\` is null, maps direction onto the follow-up's \`source\` column, and derives both the count and the page from a single filtered base so they cannot drift. Direction, outcome and date-range filters are applied in SQL. [[#metadata]]`)
};

const es_demo_narrative_admin_call_log_body = /** @type {(inputs: Demo_Narrative_Admin_Call_Log_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Todas las llamadas y los mensajes de voz registrados en un ticket aparecen en el historial de llamadas, ordenados del más reciente al más antiguo y paginados de cincuenta en cincuenta. El historial no almacena ni muestra ningún número de teléfono. Cada fila identifica al cliente con un alias que el navegador descifra con la clave de la organización. Las columnas restantes son texto plano que el servidor ya tiene. [[#telephony #privacy]]
**¿Qué contiene una fila?** Cada fila lleva el sentido de la llamada, su resultado, su duración, su marca de tiempo y el ticket al que pertenece. La lista se construye a partir de los seguimientos de tipo llamada y mensaje de voz en los hilos de los tickets, no de los registros del proveedor. Un seguimiento eliminado del hilo no aparece. [[#metadata]]
**¿Quién tiene acceso al historial de llamadas?** Se necesita el permiso Ver reportes. La consulta no aplica ningún filtro de cola, así que la persona usuaria con ese permiso ve llamadas de tickets en colas a las que no pertenece. El alias sigue necesitando la clave de la organización para descifrarse, y el ticket detrás de una fila sigue necesitando la clave del ticket. Una fila puede, por tanto, nombrar una llamada que la persona usuaria no puede abrir. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se otorga cada permiso. [[#permissions #encryption]]
**¿Qué revela el texto plano?** Las columnas en texto plano exponen el sentido, la duración, el resultado y el momento de cada llamada que la organización hizo o recibió, con alias en lugar de números de teléfono. Ese patrón revela cuándo está activa la organización, cuánto duran las llamadas y con qué frecuencia fallan. El contenido de las llamadas y los números de teléfono están ausentes. [La frontera de confianza](#deep-dive/the-trust-boundary) trata qué revelan las demás columnas en texto plano. [[#server-holds #metadata]]
**¿Qué ocurre cuando se purga un ticket?** Las filas de llamada y mensaje de voz son seguimientos del ticket, así que la purga de retención las elimina junto con él. Un ticket cerrado que ha superado su plazo de retención no deja ningún historial de llamadas. [Retención de datos](#deep-dive/data-retention) trata la purga. [[#retention]]
**La consulta del historial y sus filtros.** \`callLog\`, en \`packages/server/src/tickets/reports-service.ts\`, selecciona los seguimientos de tipo \`phone_call\` y \`voicemail\` donde \`deleted_at\` es nulo, deriva el sentido de la columna \`source\` del seguimiento y construye tanto el recuento como la página sobre una misma base filtrada para que no puedan separarse. Los filtros de sentido, resultado y rango de fechas se aplican en SQL. [[#metadata]]`)
};

const en_xa2_demo_narrative_admin_call_log_body = /** @type {(inputs: Demo_Narrative_Admin_Call_Log_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èvèry càll ànd vòìcèmàìl wrìttèn tò à tìckèt àppèàrs ìn thè càll hìstòry, sòrtèd nèwèst fìrst ànd pàgèd fìfty àt à tìmè. Thè càll hìstòry hòlds ànd shòws nò phònè nùmbèr. Èàch ròw ìdèntìfìès thè clìènt by àn àlìàs thè bròwsèr dècrypts wìth thè òrgànìzàtìòn kèy. Thè rèmàìnìng còlùmns àrè plàìntèxt thè sèrvèr àlrèàdy hòlds. [[#tèlèphòny #prìvàcy]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à ròw càrry? •••••••** Èàch ròw càrrìès thè càll's dìrèctìòn, òùtcòmè, dùràtìòn, tìmèstàmp, ànd thè tìckèt thè càll bèlòngs tò. Thè lìst dràws fròm càll ànd vòìcèmàìl fòllòw-ùps òn tìckèt thrèàds, nòt fròm pròvìdèr rècòrds. À fòllòw-ùp thàt hàs bèèn dèlètèd fròm thè thrèàd dòès nòt àppèàr. [[#mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò hàs àccèss tò thè càll hìstòry? •••••••••••** Vìèwìng rèqùìrès thè Vìèw rèpòrts pèrmìssìòn. Thè qùèry àpplìès nò qùèùè fìltèr, sò à ùsèr wìth thàt pèrmìssìòn sèès càlls òn tìckèts ìn qùèùès thè ùsèr dòès nòt bèlòng tò. Thè àlìàs stìll rèqùìrès thè òrgànìzàtìòn kèy tò dècrypt, ànd thè tìckèt bèhìnd à ròw stìll rèqùìrès thè tìckèt kèy. À ròw càn thèrèfòrè nàmè à càll thè ùsèr cànnòt òpèn. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw èàch pèrmìssìòn ìs gràntèd. [[#pèrmìssìòns #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè plàìntèxt rèvèàl? ••••••••••** Thè plàìntèxt còlùmns èxpòsè thè dìrèctìòn, dùràtìòn, òùtcòmè ànd tìmìng òf èvèry càll thè òrgànìzàtìòn plàcèd òr rècèìvèd, wìth àlìàsès stàndìng ìn fòr phònè nùmbèrs. Thàt pàttèrn rèvèàls whèn thè òrgànìzàtìòn ìs àctìvè, hòw lòng càlls làst ànd hòw òftèn thèy fàìl. Càll còntènt ànd phònè nùmbèrs àrè àbsènt. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whàt thè òthèr plàìntèxt còlùmns gìvè àwày. [[#sèrvèr-hòlds #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn à tìckèt ìs pùrgèd? ••••••••••••** Càll ànd vòìcèmàìl ròws àrè fòllòw-ùps òn thè tìckèt, sò thè rètèntìòn pùrgè rèmòvès thèm tògèthèr. À clòsèd tìckèt thàt hàs àgèd pàst ìts rètèntìòn wìndòw lèàvès nò càll hìstòry bèhìnd. [Dàtà rètèntìòn](#dèèp-dìvè/dàtà-rètèntìòn) còvèrs thè pùrgè. [[#rètèntìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè càll lòg qùèry ànd ìts fìltèrs. •••••••••••** \`càllLòg\` ìn \`pàckàgès/sèrvèr/src/tìckèts/rèpòrts-sèrvìcè.ts\` sèlècts fòllòw-ùps òf typè \`phònè_càll\` ànd \`vòìcèmàìl\` whèrè \`dèlètèd_àt\` ìs nùll, màps dìrèctìòn òntò thè fòllòw-ùp's \`sòùrcè\` còlùmn, ànd dèrìvès bòth thè còùnt ànd thè pàgè fròm à sìnglè fìltèrèd bàsè sò thèy cànnòt drìft. Dìrèctìòn, òùtcòmè ànd dàtè-ràngè fìltèrs àrè àpplìèd ìn SQL. [[#mètàdàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Every call and voicemail written to a ticket appears in the call history, sorted newest first and paged fifty at a time. The call history holds and shows no ..." |
*
* @param {Demo_Narrative_Admin_Call_Log_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_call_log_body = /** @type {((inputs?: Demo_Narrative_Admin_Call_Log_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Call_Log_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_call_log_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_call_log_body(inputs)
	return en_demo_narrative_admin_call_log_body(inputs)
});