/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Email_Thread_BodyInputs */

const en_demo_narrative_topic_email_thread_body = /** @type {(inputs: Demo_Narrative_Topic_Email_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Email sent and received on a case sits in the same thread as texts, portal replies and notes, and is the one channel whose content is readable by every mail server it passes. [[#client-data #encryption]]
**What leaves and what is kept.** The browser hands the relay the case, a subject and a body, and the server resolves and decrypts the client's address itself rather than accepting one from the request. A copy of the message is sealed with the case key and written to the thread, and a second copy is sealed to the client's channel key when one is active, so the thread record survives a mailbox nobody reads. The organization can switch its email channel off, and the relay refuses before it decrypts an address. [A reply](#ticket-detail/reply) covers the copies a message produces, and [The telephony relay](#deep-dive/the-telephony-relay) covers the buffer handling this endpoint shares with the text path. [[#encryption #server-holds #telephony]]
**The address a client answers to.** Each case gets a reply address carrying a 128-bit random token, and the server stores only a keyed hash of it, so the address exists in the outbound header and in the client's mailbox and nowhere the database can give it up. Revoking the token from the case stops emailed replies routing to that thread, and the next outbound email mints a new one. A server restart mints a new token as well, because the old value cannot be recovered from the hash. [[#keys #server-holds #privacy]]
**What an inbound email is trusted for.** The reply token decides which case a message lands on. The From address is stored and shown as claimed and never used for routing, because anyone can write any address into it, and each inbound message carries that caution with it. Attachments are counted and dropped rather than imported, an over-long subject or body is truncated rather than refused, and a message arriving on a closed case reopens it. [[#failure-states #privacy]]
**Replying on the channel the client used.** With the newest client-sent entry being an email, composing a text or a portal reply reports that the client may be waiting on email. The caution is dismissable per case for the rest of the session and is not raised when the organization has its email channel switched off. [[#failure-states]]
**The relay handler and the token row.** The outbound path is \`/relay/email\` in \`packages/server/src/routes/relay.ts\` with the reply address and footer assembly in \`packages/server/src/email/email-relay-service.ts\`, and the token row comes from \`110_email_reply_tokens.ts\`. Inbound mail is accepted by \`inbound-receiver.ts\` and written by \`inbound-email.ts\`, and the bubbles are \`EmailBubbleContent.svelte\` and \`EmailInboundBubbleContent.svelte\`. [[#client-data]]`)
};

const es_demo_narrative_topic_email_thread_body = /** @type {(inputs: Demo_Narrative_Topic_Email_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El correo enviado y recibido en un caso queda en el mismo hilo que los mensajes de texto, las respuestas del portal y las notas, y es el único canal cuyo contenido pueden leer todos los servidores de correo por los que pasa. [[#client-data #encryption]]
**Lo que sale y lo que se guarda.** El navegador entrega al relé el caso, un asunto y un cuerpo, y el servidor resuelve y descifra por su cuenta la dirección del cliente en lugar de aceptar una que venga en la petición. Una copia del mensaje se sella con la clave del caso y se escribe en el hilo, y una segunda copia se sella con la clave del canal del cliente cuando hay uno activo, de modo que el registro del hilo sobrevive a un buzón que nadie lee. La organización puede desactivar su canal de correo, y el relé lo rechaza antes de descifrar ninguna dirección. [Una respuesta](#ticket-detail/reply) trata las copias que produce un mensaje, y [El relé de telefonía](#deep-dive/the-telephony-relay) trata el manejo de memoria que este extremo comparte con el camino de los mensajes de texto. [[#encryption #server-holds #telephony]]
**La dirección a la que responde un cliente.** Cada caso recibe una dirección de respuesta con un token aleatorio de 128 bits, y el servidor guarda solo un hash con clave de ese token, así que la dirección existe en la cabecera saliente y en el buzón del cliente y en ningún sitio que la base de datos pueda entregar. Revocar el token desde el caso detiene las respuestas por correo hacia ese hilo, y el siguiente correo saliente crea uno nuevo. Un reinicio del servidor también crea uno nuevo, porque el valor anterior no se puede recuperar del hash. [[#keys #server-holds #privacy]]
**Para qué se fía el sistema de un correo entrante.** El token de respuesta decide en qué caso aterriza un mensaje. La dirección del remitente se guarda y se muestra como declarada y nunca se usa para enrutar, porque cualquiera puede escribir cualquier dirección ahí, y cada mensaje entrante lleva consigo esa advertencia. Los adjuntos se cuentan y se descartan en lugar de importarse, un asunto o un cuerpo demasiado largos se recortan en lugar de rechazarse, y un mensaje que llega a un caso cerrado lo reabre. [[#failure-states #privacy]]
**Responder por el canal que usó el cliente.** Si la entrada más reciente escrita por el cliente es un correo, redactar un mensaje de texto o una respuesta del portal indica que el cliente puede estar esperando un correo. La advertencia se puede descartar por caso durante el resto de la sesión y no aparece cuando la organización tiene desactivado su canal de correo. [[#failure-states]]
**El extremo del relé y la fila del token.** El camino saliente es \`/relay/email\`, en \`packages/server/src/routes/relay.ts\`, con el montaje de la dirección de respuesta y el pie en \`packages/server/src/email/email-relay-service.ts\`, y la fila del token viene de \`110_email_reply_tokens.ts\`. El correo entrante lo acepta \`inbound-receiver.ts\` y lo escribe \`inbound-email.ts\`, y las burbujas son \`EmailBubbleContent.svelte\` y \`EmailInboundBubbleContent.svelte\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_email_thread_body = /** @type {(inputs: Demo_Narrative_Topic_Email_Thread_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èmàìls sènt ànd rècèìvèd òn à tìckèt àppèàr ìn thè sàmè cònvèrsàtìòn thrèàd às SMS mèssàgès, pòrtàl rèplìès, ànd ìntèrnàl nòtès.
 •••••••••••••••••••••••••••••••••••••••**Òùtbòùnd èmàìls. •••••** Whèn à vòlùntèèr sènds àn èmàìl fròm thè còmpòsè bàr, thè thrèàd shòws thè mèssàgè wìth à sùbjèct lìnè, thè fòrmàttèd bòdy, ànd àn Èmàìl chìp làbèlìng thè chànnèl. Thè còmpòsè shèèt whèrè thè vòlùntèèr wrìtès thè èmàìl shòws à plàìntèxt wàrnìng bànnèr bècàùsè thè mèssàgè lèàvès thè systèm ùnèncryptèd.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ìnbòùnd èmàìls. •••••** Whèn à clìènt rèplìès by èmàìl, thè thrèàd shòws thè clàìmèd Fròm àddrèss, thè sùbjèct, ànd thè plàìn tèxt bòdy. Thè Fròm àddrèss ìs màrkèd às ùnvèrìfìèd bècàùsè thè sèrvèr cànnòt cònfìrm thè sèndèr's ìdèntìty. Ìf thè ìnbòùnd èmàìl càrrìèd àttàchmènts, à nòtìcè bèlòw thè bòdy sàys hòw màny wèrè strìppèd, sìncè èmàìl àttàchmènts àrè nòt ìmpòrtèd ìntò thè èncryptèd stòrè.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ìnbòùnd càùtìòn. •••••** Àn ìnfò bùttòn òn èàch ìnbòùnd èmàìl òpèns àn èxpàndàblè pànèl wìth thè wàrnìng "Thìs mèssàgè àrrìvèd by èmàìl. Èmàìl ìs thè èàsìèst chànnèl tò fàkè. Chèck ànythìng ìmpòrtànt ìn ìt bèfòrè àctìng òn ìt."
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Còmpòsè bàr nòtìcè. ••••••** Whèn thè clìènt's mòst rècènt mèssàgè àrrìvèd by èmàìl, à càùtìòn àppèàrs àbòvè thè còmpòsè bàr wàrnìng thàt thè clìènt mày bè èxpèctìng àn èmàìl rèply ànd mìght nòt sèè àn SMS òr pòrtàl mèssàgè. Thè càùtìòn càn bè dìsmìssèd ànd stàys dìsmìssèd fòr thàt tìckèt fòr thè rèst òf thè sèssìòn.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rèvòkìng thè rèply tòkèn. ••••••••** Thè càsè pànèl shòws à Rèvòkè èmàìl rèply tòkèn àctìòn whèn thè clìènt hàs àn èmàìl àddrèss òn fìlè. Rèvòkìng thè tòkèn stòps èmàìlèd rèplìès fròm làndìng ìn thè thrèàd, ànd à nèw tòkèn ìs crèàtèd àùtòmàtìcàlly òn thè nèxt òùtbòùnd èmàìl fròm à vòlùntèèr. •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Email sent and received on a case sits in the same thread as texts, portal replies and notes, and is the one channel whose content is readable by every mail ..." |
*
* @param {Demo_Narrative_Topic_Email_Thread_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_email_thread_body = /** @type {((inputs?: Demo_Narrative_Topic_Email_Thread_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Email_Thread_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_email_thread_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_email_thread_body(inputs)
	return en_demo_narrative_topic_email_thread_body(inputs)
});