/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Conversation_BodyInputs */

const en_demo_narrative_topic_conversation_body = /** @type {(inputs: Demo_Narrative_Topic_Conversation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The unified case thread gathers everything said on a ticket into one sequence. It holds what the client sent, what the organization sent back, the notes written about it, and the events the ticket recorded. [[#client-data]]
**One sequence, several channels.** Text messages, replies typed into the application, emails, and voicemails are separate kinds of follow-up in the same thread. Whether the client or a user wrote a follow-up decides which side it sits on. The type is a plaintext column, so the server knows a ticket received four texts and sent one email at given times, but holds the words of none of them. [The telephony relay](#deep-dive/the-telephony-relay) covers what the carrier saw of a text before it arrived. [[#metadata #server-holds #telephony]]
**How are follow-ups sealed?** Each follow-up is sealed with the ticket key and bound to its own position in the sequence. A ciphertext moved to another follow-up or another ticket fails to open. Replies a client sends from their portal arrive under a one-off key that the ticket key absorbs on first reading. [How encryption works](#deep-dive/how-encryption-works) covers the slot binding. [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers the one-off key convergence. [[#encryption #keys]]
**Paging through a long thread.** The thread opens on the most recent fifty follow-ups. Older pages of fifty load as reading moves back, and the reading position stays steady as each page arrives. When unread follow-ups are older than the first page, pages load until the last read point is in view. A refresh of the newest page merges follow-ups individually rather than replacing the page, so an older page already loaded is not split at its boundary. [Date separators](#ticket-detail/date-separators) covers the day boundaries. [System events](#ticket-detail/system-events) covers the recorded events. [[#failure-states]]
**The paginator and the follow-up row.** \`packages/client/src/lib/tickets/chat-paginator.svelte.ts\` is the shared paging implementation behind both this thread and the client portal thread. Both call sites pass a page size of fifty. The row is \`packages/server/src/db/migrations/tenant/026_create_followups.ts\` with \`encrypted_content\` as \`bytea\` beside plaintext \`source\`, \`type\`, and \`created_at\`. [[#client-data #server-holds]]`)
};

const es_demo_narrative_topic_conversation_body = /** @type {(inputs: Demo_Narrative_Topic_Conversation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El hilo de caso unificado reúne todo lo dicho en un ticket en una sola secuencia. Contiene lo que envió el cliente, lo que respondió la organización, las notas escritas al respecto y los eventos que registró el ticket. [[#client-data]]
**Una secuencia, varios canales.** Mensajes de texto, respuestas escritas en la aplicación, correos electrónicos y buzones de voz son tipos distintos de seguimiento en el mismo hilo. Si lo escribió el cliente o la persona usuaria determina de qué lado aparece el seguimiento. El tipo es una columna en texto plano, así que el servidor sabe que un ticket recibió cuatro textos y envió un correo a ciertas horas, pero no conserva las palabras de ninguno. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que el operador vio de un texto antes de que llegara. [[#metadata #server-holds #telephony]]
**¿Cómo se sellan los seguimientos?** Cada seguimiento se sella con la clave del ticket y se vincula a su propia posición en la secuencia. Un texto cifrado movido a otro seguimiento o a otro ticket no se abre. Las respuestas que un cliente envía desde su portal llegan bajo una clave de un solo uso que la clave del ticket absorbe en la primera lectura. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la vinculación a la ranura. [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata la convergencia de la clave de un solo uso. [[#encryption #keys]]
**Paginación en un hilo largo.** El hilo abre con los cincuenta seguimientos más recientes. Páginas anteriores de cincuenta se cargan conforme la lectura retrocede, y la posición de lectura se mantiene estable mientras llega cada página. Cuando hay seguimientos no leídos más antiguos que la primera página, se cargan páginas hasta que el último punto de lectura queda visible. Una actualización de la página más reciente fusiona seguimientos individualmente en vez de reemplazar la página, así que una página anterior ya cargada no se corta en su límite. [Separadores de fecha](#ticket-detail/date-separators) trata los límites de día. [Eventos del sistema](#ticket-detail/system-events) trata los eventos registrados. [[#failure-states]]
**El paginador y la fila de seguimiento.** \`packages/client/src/lib/tickets/chat-paginator.svelte.ts\` es la implementación de paginación compartida detrás de este hilo y del hilo del portal del cliente. Ambos puntos de llamada pasan un tamaño de página de cincuenta. La fila es \`packages/server/src/db/migrations/tenant/026_create_followups.ts\` con \`encrypted_content\` como \`bytea\` junto a las columnas en texto plano \`source\`, \`type\` y \`created_at\`. [[#client-data #server-holds]]`)
};

const en_xa2_demo_narrative_topic_conversation_body = /** @type {(inputs: Demo_Narrative_Topic_Conversation_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ùnìfìèd càsè thrèàd gàthèrs èvèrythìng sàìd òn à tìckèt ìntò ònè sèqùèncè. Ìt hòlds whàt thè clìènt sènt, whàt thè òrgànìzàtìòn sènt bàck, thè nòtès wrìttèn àbòùt ìt, ànd thè èvènts thè tìckèt rècòrdèd. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ònè sèqùèncè, sèvèràl chànnèls. ••••••••••** Tèxt mèssàgès, rèplìès typèd ìntò thè àpplìcàtìòn, èmàìls, ànd vòìcèmàìls àrè sèpàràtè kìnds òf fòllòw-ùp ìn thè sàmè thrèàd. Whèthèr thè clìènt òr à ùsèr wròtè à fòllòw-ùp dècìdès whìch sìdè ìt sìts òn. Thè typè ìs à plàìntèxt còlùmn, sò thè sèrvèr knòws à tìckèt rècèìvèd fòùr tèxts ànd sènt ònè èmàìl àt gìvèn tìmès, bùt hòlds thè wòrds òf nònè òf thèm. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt thè càrrìèr sàw òf à tèxt bèfòrè ìt àrrìvèd. [[#mètàdàtà #sèrvèr-hòlds #tèlèphòny]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw àrè fòllòw-ùps sèàlèd? ••••••••** Èàch fòllòw-ùp ìs sèàlèd wìth thè tìckèt kèy ànd bòùnd tò ìts òwn pòsìtìòn ìn thè sèqùèncè. À cìphèrtèxt mòvèd tò ànòthèr fòllòw-ùp òr ànòthèr tìckèt fàìls tò òpèn. Rèplìès à clìènt sènds fròm thèìr pòrtàl àrrìvè ùndèr à ònè-òff kèy thàt thè tìckèt kèy àbsòrbs òn fìrst rèàdìng. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè slòt bìndìng. [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thè ònè-òff kèy cònvèrgèncè. [[#èncryptìòn #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pàgìng thròùgh à lòng thrèàd. •••••••••** Thè thrèàd òpèns òn thè mòst rècènt fìfty fòllòw-ùps. Òldèr pàgès òf fìfty lòàd às rèàdìng mòvès bàck, ànd thè rèàdìng pòsìtìòn stàys stèàdy às èàch pàgè àrrìvès. Whèn ùnrèàd fòllòw-ùps àrè òldèr thàn thè fìrst pàgè, pàgès lòàd ùntìl thè làst rèàd pòìnt ìs ìn vìèw. À rèfrèsh òf thè nèwèst pàgè mèrgès fòllòw-ùps ìndìvìdùàlly ràthèr thàn rèplàcìng thè pàgè, sò àn òldèr pàgè àlrèàdy lòàdèd ìs nòt splìt àt ìts bòùndàry. [Dàtè sèpàràtòrs](#tìckèt-dètàìl/dàtè-sèpàràtòrs) còvèrs thè dày bòùndàrìès. [Systèm èvènts](#tìckèt-dètàìl/systèm-èvènts) còvèrs thè rècòrdèd èvènts. [[#fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pàgìnàtòr ànd thè fòllòw-ùp ròw. •••••••••••** \`pàckàgès/clìènt/src/lìb/tìckèts/chàt-pàgìnàtòr.svèltè.ts\` ìs thè shàrèd pàgìng ìmplèmèntàtìòn bèhìnd bòth thìs thrèàd ànd thè clìènt pòrtàl thrèàd. Bòth càll sìtès pàss à pàgè sìzè òf fìfty. Thè ròw ìs \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/026_crèàtè_fòllòwùps.ts\` wìth \`èncryptèd_còntènt\` às \`bytèà\` bèsìdè plàìntèxt \`sòùrcè\`, \`typè\`, ànd \`crèàtèd_àt\`. [[#clìènt-dàtà #sèrvèr-hòlds]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The unified case thread gathers everything said on a ticket into one sequence. It holds what the client sent, what the organization sent back, the notes writ..." |
*
* @param {Demo_Narrative_Topic_Conversation_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_conversation_body = /** @type {((inputs?: Demo_Narrative_Topic_Conversation_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Conversation_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_conversation_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_conversation_body(inputs)
	return en_demo_narrative_topic_conversation_body(inputs)
});