/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs */

const en_demo_narrative_deepdive_portal_channel_lifecycle_body = /** @type {(inputs: Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A client's safest channel depends on their phone, their situation, and who else might see their screen. CARE-Y offers three tiers and lets the client move up without asking anyone's permission. The tiers differ in how much of the channel itself is protected. The help behind each tier is the same. [[#portal #privacy]]
Text and email is where every client starts. It works on any phone with no setup, and the organization's stored copy of the conversation is encrypted like everything else. The channel itself is not protected, because a text message is readable by the carrier and by the telephony provider on its way through. [The telephony relay](#deep-dive/the-telephony-relay) covers what that means in practice. [[#portal #telephony]]
A secure link is a private page for one client, reachable only by the exact link sent to them, with no account and no password to remember. Messages on that page are encrypted in the client's own browser, so neither the phone company nor the server can read them. The key material lives in the URL fragment, which browsers never send to a server. The server stores the conversation without ever being able to open it. The limitation follows directly from that design. Anyone who gets the whole link gets the conversation, which matters for a client whose phone might be looked through. A client can add a passphrase. The link alone then cannot open the conversation. The passphrase has an enforced minimum strength. [[#portal #encryption #failure-states]]
An encrypted account is the strongest of the three tiers. The client chooses a username and a password, and the password derives their keys through the same protocol a staff member's password uses. The credential is something the client knows rather than something in a message someone else could find. The client can add the account page to their home screen for repeat visits. A subpoena to the phone company or the mail provider produces a login page address and nothing else. Closing the tab clears the keys from the browser but does not revoke the server session; that session lapses within twenty minutes of the last renewal. [Account sign in](#client-account/sign-in) covers that session model. [[#portal #keys]]
Moving up a tier is the client's own decision, taken from inside their own session, and no member of staff has to enable it. The client is warned before submitting when messages on the device cannot be opened under the new key. [Security upgrades](#client-portal/account-upgrade) covers the upgrade paths and their limitations. [[#portal #privacy]]
- A client on a bare link is offered both the passphrase and the account. [[#portal]]
- A client on a passphrase link is offered the account. [[#portal]]
- A client already on an account is offered nothing further. [[#portal]]
Adding a passphrase or an account is the mitigation for a captured link, and gating a mitigation behind someone else's attention works against it, which is why the client controls the decision. [[#portal #privacy]]
One-time message links are a separate mechanism rather than a tier. A user sends a single encrypted message whose link stops working after its first read or after 72 hours, whichever comes first. That is how something sensitive travels over an insecure channel without living there. [[#portal #encryption]]
**Credential model per tier.** Each tier authenticates the client differently. [[#portal #keys #encryption]]
- Text and email has no portal credential, because the client's phone number is the address. [[#portal #telephony]]
- A secure link's credential is a 24-byte random seed carried in the URL fragment. From that seed the browser derives a 48-character channel id, a 32-byte auth token, and an Argon2id salt. The server stores only a BLAKE2b hash of the auth token for timing-safe comparison. [[#portal #keys]]
- An account's credential is a username and a password, which run the full staff pipeline and yield both a keypair and an independent auth token under separate HKDF labels. Neither reveals the other. [[#portal #keys]]
The channel keypair does not come from the seed directly. The seed, or the seed concatenated with the Argon2id stretch of a spoken passphrase, becomes the input to a key evaluation under a tag naming that organization and channel, and the evaluation's output is what derives the keypair. [[#portal #keys #encryption]]
**Why does the evaluation step matter?** Routing channel derivation through a tagged evaluation gives two properties a seed-only derivation cannot have. A passphrase guess costs a rate-limited round trip under that channel's tag rather than a local hash, which is what makes a short spoken phrase worth using. Revocation becomes cryptographic rather than procedural, because the evaluation path refuses tags whose channel is revoked or expired. No other credential is an oracle for that key, and a photographed link paired with a later database dump stops decrypting at revocation. An unknown channel id is allowed because a link is minted before its row exists. An active row requires the auth token. Revoked and expired rows are refused. [[#portal #keys #server-holds]]
**What does the server hold for a channel?** The portal_channels row is plaintext throughout. [[#server-holds #metadata #portal]]
- The channel id, the auth token hash, the client's public key and a passphrase flag. [[#server-holds #portal]]
- A key-check ciphertext with its ephemeral point and nonce. [[#server-holds #portal]]
- A status column, plus created, last-seen, last-notified and revoked timestamps. [[#server-holds #metadata]]
- Message rows for the channel carry direction, ephemeral point, nonce, ciphertext and timestamps. [[#server-holds #portal]]
A client has at most one active channel at a time, enforced by a partial unique index on client_id. The client row carries a plaintext tier column that the server updates when a channel is created or revoked. The server knows a channel exists, when it was opened, how often the client visited, and which tier the client moved to. It cannot read a word of the conversation. A wrong passphrase is detected in the client's browser against the stored key check. The server never learns whether a guess was right. [[#server-holds #metadata #portal]]
**Lifecycle and endings.** [[#portal #retention #failure-states]]
- It expires lazily after 30 days without the client reading it. The sweep runs on the next read request and deletes the client-side copies of messages, attachments and recordings. The organization's record of the case stays intact. Unseen replies from the organization are kept. [[#portal #retention]]
- Regenerating a link revokes the old channel and deletes the client's copies. The old link shows a dead-link state on the next open. [[#portal #failure-states]]
- A user revokes it outright. Revoked, unknown and badly authenticated channel ids all produce the same generic response, indistinguishable by design so a link cannot be probed. [[#portal #failure-states]]
- The organization disables the secure link channel at the policy level. New channel creation stops and replies are refused, but a client holding a working link can still open it and read, because a freeze can be lifted later while destroying a client's access to their own history cannot be undone. [[#portal #permissions]]
- Merging two clients revokes the losing client's channel. The revoked channel's content is kept until the merge is locked. [Merging clients](#admin-people/client-merge) covers that outcome. [[#portal #failure-states]]
**Client-side custody.** Portal crypto runs in a dedicated worker rather than on the page. The worker owns the seed after the main thread's one unavoidable touch of parsing the URL fragment, along with the passphrase stretch, the blind and finalize halves of the evaluation, the keypair, and message and attachment encryption. A zeroing operation fires on quick exit and page hide. A script injected mid-session can still read plaintext already rendered on the page, which nothing can prevent, but it cannot take the channel's private scalar out of the worker and decrypt the channel's future traffic offline. [[#portal #failure-states #encryption]]
**The derivation, worker, services and schema.** Channel derivation is \`packages/crypto/src/portal.ts\` and account derivation is \`packages/crypto/src/client-account.ts\`, both on the shared \`keypairFromOprfOutput\` helper. The portal worker and its bridge are under \`packages/client/src/lib/workers/portal*\`, and the client surfaces are under \`packages/client/src/lib/portal/\`. The server services are under \`packages/server/src/portal/\` with the tRPC surface in \`packages/server/src/routes/client-portal.ts\`. Schema is in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`, and the 30-day sweep is \`packages/server/src/portal/portal-message-service.ts\`. [[#portal #retention]]`)
};

const es_demo_narrative_deepdive_portal_channel_lifecycle_body = /** @type {(inputs: Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El canal más seguro para un cliente depende de su teléfono, su situación y de quién más pueda ver su pantalla. CARE-Y ofrece tres niveles y permite al cliente subir sin pedir permiso a nadie. Los niveles difieren en cuánto del canal mismo está protegido. La ayuda detrás de cada nivel es la misma. [[#portal #privacy]]
Texto y correo es donde comienza cada cliente. Funciona en cualquier teléfono sin configuración, y la copia almacenada de la conversación está cifrada como todo lo demás. El canal en sí no está protegido, porque un mensaje de texto es legible por el operador y por el proveedor de telefonía en su camino. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que eso significa en la práctica. [[#portal #telephony]]
Un enlace seguro es una página privada para un solo cliente, accesible únicamente mediante el enlace exacto que se le envió, sin cuenta ni contraseña que recordar. Los mensajes en esa página se cifran en el navegador del cliente, por lo que ni la compañía telefónica ni el servidor pueden leerlos. El material de claves vive en el fragmento de la URL, que los navegadores nunca envían al servidor. El servidor almacena la conversación sin poder abrirla. La limitación se deriva directamente de ese diseño. Cualquier persona que obtenga el enlace completo obtiene la conversación, lo cual importa para un cliente cuyo teléfono podría ser revisado. El cliente puede agregar una frase de paso. Solo el enlace entonces no basta para abrir la conversación. La frase de paso tiene una fortaleza mínima exigida. [[#portal #encryption #failure-states]]
Una cuenta cifrada es el más fuerte de los tres niveles. El cliente elige un nombre de usuario y una contraseña, y la contraseña deriva sus claves a través del mismo protocolo que usa la contraseña del personal. La credencial es algo que el cliente sabe, no algo en un mensaje que otra persona podría encontrar. El cliente puede añadir la página de la cuenta a su pantalla de inicio para visitas repetidas. Una orden judicial al operador telefónico o al proveedor de correo produce una dirección de página de inicio de sesión y nada más. Cerrar la pestaña borra las claves del navegador pero no revoca la sesión del servidor; esa sesión caduca dentro de los veinte minutos posteriores a la última renovación. [Inicio de sesión de cuenta](#client-account/sign-in) trata ese modelo de sesión. [[#portal #keys]]
Subir de nivel es decisión del cliente, tomada desde dentro de su propia sesión, y ningún miembro del personal necesita habilitarla. El cliente recibe aviso antes de enviar cuando los mensajes del dispositivo no se pueden abrir con la nueva clave. [Mejoras de seguridad](#client-portal/account-upgrade) trata las vías de mejora y sus limitaciones. [[#portal #privacy]]
- Un cliente en un enlace simple tiene acceso tanto a la frase de paso como a la cuenta. [[#portal]]
- Un cliente en un enlace con frase de paso tiene acceso a la cuenta. [[#portal]]
- Un cliente que ya tiene una cuenta no tiene opciones adicionales. [[#portal]]
Agregar una frase de paso o una cuenta es la mitigación ante un enlace capturado, y condicionar una mitigación a la atención de otra persona va en contra de su propósito, por lo que el cliente controla la decisión. [[#portal #privacy]]
Los enlaces de mensaje de un solo uso son un mecanismo separado, no un nivel. La persona usuaria envía un solo mensaje cifrado cuyo enlace deja de funcionar después de su primera lectura o después de 72 horas, lo que ocurra primero. Así es como algo sensible viaja por un canal inseguro sin permanecer allí. [[#portal #encryption]]
**Modelo de credencial por nivel.** Cada nivel autentica al cliente de forma diferente. [[#portal #keys #encryption]]
- Texto y correo no tiene credencial de portal, porque el número de teléfono del cliente es la dirección. [[#portal #telephony]]
- La credencial de un enlace seguro es una semilla aleatoria de 24 bytes transportada en el fragmento de la URL. De esa semilla el navegador deriva un identificador de canal de 48 caracteres, un token de autenticación de 32 bytes y una sal Argon2id. El servidor almacena solo un hash BLAKE2b del token de autenticación para comparación de tiempo constante. [[#portal #keys]]
- La credencial de una cuenta es un nombre de usuario y una contraseña, que ejecutan el pipeline completo del personal y producen tanto un par de claves como un token de autenticación independiente bajo etiquetas HKDF separadas. Ninguno revela al otro. [[#portal #keys]]
El par de claves del canal no proviene de la semilla directamente. La semilla, o la semilla concatenada con el estiramiento Argon2id de una frase de paso hablada, se convierte en la entrada de una evaluación de clave bajo una etiqueta que nombra esa organización y canal, y el resultado de la evaluación es lo que deriva el par de claves. [[#portal #keys #encryption]]
**¿Por qué importa el paso de evaluación?** Enrutar la derivación del canal a través de una evaluación con etiqueta da dos propiedades que una derivación solo desde la semilla no puede tener. Adivinar una frase de paso cuesta un viaje de ida y vuelta con límite de tasa bajo la etiqueta de ese canal en lugar de un hash local, que es lo que hace que una frase hablada corta valga la pena. La revocación se vuelve criptográfica en lugar de procedimental, porque la ruta de evaluación rechaza etiquetas cuyo canal está revocado o expirado. Ninguna otra credencial es un oráculo para esa clave, y un enlace fotografiado combinado con un volcado posterior de la base de datos deja de descifrar en la revocación. Un identificador de canal desconocido es permitido porque un enlace se crea antes de que exista su fila. Una fila activa requiere el token de autenticación. Las filas revocadas y expiradas son rechazadas. [[#portal #keys #server-holds]]
**¿Qué almacena el servidor para un canal?** La fila de portal_channels es texto plano en su totalidad. [[#server-holds #metadata #portal]]
- El identificador de canal, el hash del token de autenticación, la clave pública del cliente y una bandera de frase de paso. [[#server-holds #portal]]
- Un texto cifrado de verificación de clave con su punto efímero y nonce. [[#server-holds #portal]]
- Una columna de estado, más marcas de tiempo de creación, última vista, última notificación y revocación. [[#server-holds #metadata]]
- Las filas de mensajes del canal llevan dirección, punto efímero, nonce, texto cifrado y marcas de tiempo. [[#server-holds #portal]]
Un cliente tiene como máximo un canal activo a la vez, garantizado por un índice único parcial sobre client_id. La fila del cliente lleva una columna de nivel en texto plano que el servidor actualiza cuando se crea o se revoca un canal. El servidor sabe que un canal existe, cuándo se abrió, con qué frecuencia lo visitó el cliente y a qué nivel se movió. No puede leer una sola palabra de la conversación. Una frase de paso incorrecta se detecta en el navegador del cliente contra la verificación de clave almacenada. El servidor nunca se entera de si un intento fue correcto. [[#server-holds #metadata #portal]]
**Ciclo de vida y finales.** [[#portal #retention #failure-states]]
- Expira de forma diferida después de 30 días sin que el cliente lo lea. El barrido se ejecuta en la siguiente solicitud de lectura y elimina las copias del lado del cliente de mensajes, adjuntos y grabaciones. El registro del caso de la organización permanece intacto. Las respuestas no leídas de la organización se conservan. [[#portal #retention]]
- Regenerar un enlace revoca el canal anterior y elimina las copias del cliente. El enlace anterior muestra un estado de enlace inactivo en la siguiente apertura. [[#portal #failure-states]]
- La persona usuaria lo revoca directamente. Los identificadores de canal revocados, desconocidos y mal autenticados producen la misma respuesta genérica, indistinguible por diseño para que un enlace no pueda ser sondeado. [[#portal #failure-states]]
- La organización desactiva el canal de enlace seguro a nivel de política. La creación de nuevos canales se detiene y las respuestas se rechazan, pero un cliente que tenga un enlace funcional aún puede abrirlo y leer, porque una congelación puede levantarse más adelante mientras que destruir el acceso del cliente a su propio historial no puede deshacerse. [[#portal #permissions]]
- Fusionar dos clientes revoca el canal del cliente perdedor. El contenido del canal revocado se conserva hasta que la fusión se bloquea. [Fusionar clientes](#admin-people/client-merge) trata ese resultado. [[#portal #failure-states]]
**Custodia del lado del cliente.** La criptografía del portal se ejecuta en un worker dedicado en lugar de en la página. El worker posee la semilla después del único toque inevitable del hilo principal al analizar el fragmento de la URL, junto con el estiramiento de la frase de paso, las mitades de cegado y finalización de la evaluación, el par de claves, y el cifrado de mensajes y adjuntos. Una operación de borrado se dispara en la salida rápida y al ocultar la página. Un script inyectado durante la sesión aún puede leer el texto plano ya renderizado en la página, lo cual nada puede prevenir, pero no puede extraer el escalar privado del canal del worker y descifrar el tráfico futuro del canal fuera de línea. [[#portal #failure-states #encryption]]
**La derivación, el worker, los servicios y el esquema.** La derivación de canal está en \`packages/crypto/src/portal.ts\` y la derivación de cuenta está en \`packages/crypto/src/client-account.ts\`, ambas sobre el helper compartido \`keypairFromOprfOutput\`. El worker del portal y su puente están bajo \`packages/client/src/lib/workers/portal*\`, y las superficies del cliente están bajo \`packages/client/src/lib/portal/\`. Los servicios del servidor están bajo \`packages/server/src/portal/\` con la superficie tRPC en \`packages/server/src/routes/client-portal.ts\`. El esquema está en \`packages/server/src/db/migrations/tenant/001_baseline.ts\`, y el barrido de 30 días está en \`packages/server/src/portal/portal-message-service.ts\`. [[#portal #retention]]`)
};

const en_xa2_demo_narrative_deepdive_portal_channel_lifecycle_body = /** @type {(inputs: Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À clìènt's sàfèst chànnèl dèpènds òn thèìr phònè, thèìr sìtùàtìòn, ànd whò èlsè mìght sèè thèìr scrèèn. CÀRÈ-Y òffèrs thrèè tìèrs ànd lèts thè clìènt mòvè ùp wìthòùt àskìng ànyònè's pèrmìssìòn. Thè tìèrs dìffèr ìn hòw mùch òf thè chànnèl ìtsèlf ìs pròtèctèd. Thè hèlp bèhìnd èàch tìèr ìs thè sàmè. [[#pòrtàl #prìvàcy]]
Tèxt ànd èmàìl ìs whèrè èvèry clìènt stàrts. Ìt wòrks òn àny phònè wìth nò sètùp, ànd thè òrgànìzàtìòn's stòrèd còpy òf thè cònvèrsàtìòn ìs èncryptèd lìkè èvèrythìng èlsè. Thè chànnèl ìtsèlf ìs nòt pròtèctèd, bècàùsè à tèxt mèssàgè ìs rèàdàblè by thè càrrìèr ànd by thè tèlèphòny pròvìdèr òn ìts wày thròùgh. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt thàt mèàns ìn pràctìcè. [[#pòrtàl #tèlèphòny]]
À sècùrè lìnk ìs à prìvàtè pàgè fòr ònè clìènt, rèàchàblè ònly by thè èxàct lìnk sènt tò thèm, wìth nò àccòùnt ànd nò pàsswòrd tò rèmèmbèr. Mèssàgès òn thàt pàgè àrè èncryptèd ìn thè clìènt's òwn bròwsèr, sò nèìthèr thè phònè còmpàny nòr thè sèrvèr càn rèàd thèm. Thè kèy màtèrìàl lìvès ìn thè ÙRL fràgmènt, whìch bròwsèrs nèvèr sènd tò à sèrvèr. Thè sèrvèr stòrès thè cònvèrsàtìòn wìthòùt èvèr bèìng àblè tò òpèn ìt. Thè lìmìtàtìòn fòllòws dìrèctly fròm thàt dèsìgn. Ànyònè whò gèts thè whòlè lìnk gèts thè cònvèrsàtìòn, whìch màttèrs fòr à clìènt whòsè phònè mìght bè lòòkèd thròùgh. À clìènt càn àdd à pàssphràsè. Thè lìnk àlònè thèn cànnòt òpèn thè cònvèrsàtìòn. Thè pàssphràsè hàs àn ènfòrcèd mìnìmùm strèngth. [[#pòrtàl #èncryptìòn #fàìlùrè-stàtès]]
Àn èncryptèd àccòùnt ìs thè stròngèst òf thè thrèè tìèrs. Thè clìènt chòòsès à ùsèrnàmè ànd à pàsswòrd, ànd thè pàsswòrd dèrìvès thèìr kèys thròùgh thè sàmè pròtòcòl à stàff mèmbèr's pàsswòrd ùsès. Thè crèdèntìàl ìs sòmèthìng thè clìènt knòws ràthèr thàn sòmèthìng ìn à mèssàgè sòmèònè èlsè còùld fìnd. Thè clìènt càn àdd thè àccòùnt pàgè tò thèìr hòmè scrèèn fòr rèpèàt vìsìts. À sùbpòènà tò thè phònè còmpàny òr thè màìl pròvìdèr pròdùcès à lògìn pàgè àddrèss ànd nòthìng èlsè. Clòsìng thè tàb clèàrs thè kèys fròm thè bròwsèr bùt dòès nòt rèvòkè thè sèrvèr sèssìòn; thàt sèssìòn làpsès wìthìn twènty mìnùtès òf thè làst rènèwàl. [Àccòùnt sìgn ìn](#clìènt-àccòùnt/sìgn-ìn) còvèrs thàt sèssìòn mòdèl. [[#pòrtàl #kèys]]
Mòvìng ùp à tìèr ìs thè clìènt's òwn dècìsìòn, tàkèn fròm ìnsìdè thèìr òwn sèssìòn, ànd nò mèmbèr òf stàff hàs tò ènàblè ìt. Thè clìènt ìs wàrnèd bèfòrè sùbmìttìng whèn mèssàgès òn thè dèvìcè cànnòt bè òpènèd ùndèr thè nèw kèy. [Sècùrìty ùpgràdès](#clìènt-pòrtàl/àccòùnt-ùpgràdè) còvèrs thè ùpgràdè pàths ànd thèìr lìmìtàtìòns. [[#pòrtàl #prìvàcy]]
- À clìènt òn à bàrè lìnk ìs òffèrèd bòth thè pàssphràsè ànd thè àccòùnt. [[#pòrtàl]]
- À clìènt òn à pàssphràsè lìnk ìs òffèrèd thè àccòùnt. [[#pòrtàl]]
- À clìènt àlrèàdy òn àn àccòùnt ìs òffèrèd nòthìng fùrthèr. [[#pòrtàl]]
Àddìng à pàssphràsè òr àn àccòùnt ìs thè mìtìgàtìòn fòr à càptùrèd lìnk, ànd gàtìng à mìtìgàtìòn bèhìnd sòmèònè èlsè's àttèntìòn wòrks àgàìnst ìt, whìch ìs why thè clìènt còntròls thè dècìsìòn. [[#pòrtàl #prìvàcy]]
Ònè-tìmè mèssàgè lìnks àrè à sèpàràtè mèchànìsm ràthèr thàn à tìèr. À ùsèr sènds à sìnglè èncryptèd mèssàgè whòsè lìnk stòps wòrkìng àftèr ìts fìrst rèàd òr àftèr 72 hòùrs, whìchèvèr còmès fìrst. Thàt ìs hòw sòmèthìng sènsìtìvè tràvèls òvèr àn ìnsècùrè chànnèl wìthòùt lìvìng thèrè. [[#pòrtàl #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Crèdèntìàl mòdèl pèr tìèr. ••••••••** Èàch tìèr àùthèntìcàtès thè clìènt dìffèrèntly. [[#pòrtàl #kèys #èncryptìòn]]
- Tèxt ànd èmàìl hàs nò pòrtàl crèdèntìàl, bècàùsè thè clìènt's phònè nùmbèr ìs thè àddrèss. [[#pòrtàl #tèlèphòny]]
- À sècùrè lìnk's crèdèntìàl ìs à 24-bytè ràndòm sèèd càrrìèd ìn thè ÙRL fràgmènt. Fròm thàt sèèd thè bròwsèr dèrìvès à 48-chàràctèr chànnèl ìd, à 32-bytè àùth tòkèn, ànd àn Àrgòn2ìd sàlt. Thè sèrvèr stòrès ònly à BLÀKÈ2b hàsh òf thè àùth tòkèn fòr tìmìng-sàfè còmpàrìsòn. [[#pòrtàl #kèys]]
- Àn àccòùnt's crèdèntìàl ìs à ùsèrnàmè ànd à pàsswòrd, whìch rùn thè fùll stàff pìpèlìnè ànd yìèld bòth à kèypàìr ànd àn ìndèpèndènt àùth tòkèn ùndèr sèpàràtè HKDF làbèls. Nèìthèr rèvèàls thè òthèr. [[#pòrtàl #kèys]]
Thè chànnèl kèypàìr dòès nòt còmè fròm thè sèèd dìrèctly. Thè sèèd, òr thè sèèd còncàtènàtèd wìth thè Àrgòn2ìd strètch òf à spòkèn pàssphràsè, bècòmès thè ìnpùt tò à kèy èvàlùàtìòn ùndèr à tàg nàmìng thàt òrgànìzàtìòn ànd chànnèl, ànd thè èvàlùàtìòn's òùtpùt ìs whàt dèrìvès thè kèypàìr. [[#pòrtàl #kèys #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Why dòès thè èvàlùàtìòn stèp màttèr? •••••••••••** Ròùtìng chànnèl dèrìvàtìòn thròùgh à tàggèd èvàlùàtìòn gìvès twò pròpèrtìès à sèèd-ònly dèrìvàtìòn cànnòt hàvè. À pàssphràsè gùèss còsts à ràtè-lìmìtèd ròùnd trìp ùndèr thàt chànnèl's tàg ràthèr thàn à lòcàl hàsh, whìch ìs whàt màkès à shòrt spòkèn phràsè wòrth ùsìng. Rèvòcàtìòn bècòmès cryptògràphìc ràthèr thàn pròcèdùràl, bècàùsè thè èvàlùàtìòn pàth rèfùsès tàgs whòsè chànnèl ìs rèvòkèd òr èxpìrèd. Nò òthèr crèdèntìàl ìs àn òràclè fòr thàt kèy, ànd à phòtògràphèd lìnk pàìrèd wìth à làtèr dàtàbàsè dùmp stòps dècryptìng àt rèvòcàtìòn. Àn ùnknòwn chànnèl ìd ìs àllòwèd bècàùsè à lìnk ìs mìntèd bèfòrè ìts ròw èxìsts. Àn àctìvè ròw rèqùìrès thè àùth tòkèn. Rèvòkèd ànd èxpìrèd ròws àrè rèfùsèd. [[#pòrtàl #kèys #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr hòld fòr à chànnèl? ••••••••••••** Thè pòrtàl_chànnèls ròw ìs plàìntèxt thròùghòùt. [[#sèrvèr-hòlds #mètàdàtà #pòrtàl]]
- Thè chànnèl ìd, thè àùth tòkèn hàsh, thè clìènt's pùblìc kèy ànd à pàssphràsè flàg. [[#sèrvèr-hòlds #pòrtàl]]
- À kèy-chèck cìphèrtèxt wìth ìts èphèmèràl pòìnt ànd nòncè. [[#sèrvèr-hòlds #pòrtàl]]
- À stàtùs còlùmn, plùs crèàtèd, làst-sèèn, làst-nòtìfìèd ànd rèvòkèd tìmèstàmps. [[#sèrvèr-hòlds #mètàdàtà]]
- Mèssàgè ròws fòr thè chànnèl càrry dìrèctìòn, èphèmèràl pòìnt, nòncè, cìphèrtèxt ànd tìmèstàmps. [[#sèrvèr-hòlds #pòrtàl]]
À clìènt hàs àt mòst ònè àctìvè chànnèl àt à tìmè, ènfòrcèd by à pàrtìàl ùnìqùè ìndèx òn clìènt_ìd. Thè clìènt ròw càrrìès à plàìntèxt tìèr còlùmn thàt thè sèrvèr ùpdàtès whèn à chànnèl ìs crèàtèd òr rèvòkèd. Thè sèrvèr knòws à chànnèl èxìsts, whèn ìt wàs òpènèd, hòw òftèn thè clìènt vìsìtèd, ànd whìch tìèr thè clìènt mòvèd tò. Ìt cànnòt rèàd à wòrd òf thè cònvèrsàtìòn. À wròng pàssphràsè ìs dètèctèd ìn thè clìènt's bròwsèr àgàìnst thè stòrèd kèy chèck. Thè sèrvèr nèvèr lèàrns whèthèr à gùèss wàs rìght. [[#sèrvèr-hòlds #mètàdàtà #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Lìfècyclè ànd èndìngs. •••••••** [[#pòrtàl #rètèntìòn #fàìlùrè-stàtès]]
- Ìt èxpìrès làzìly àftèr 30 dàys wìthòùt thè clìènt rèàdìng ìt. Thè swèèp rùns òn thè nèxt rèàd rèqùèst ànd dèlètès thè clìènt-sìdè còpìès òf mèssàgès, àttàchmènts ànd rècòrdìngs. Thè òrgànìzàtìòn's rècòrd òf thè càsè stàys ìntàct. Ùnsèèn rèplìès fròm thè òrgànìzàtìòn àrè kèpt. [[#pòrtàl #rètèntìòn]]
- Règènèràtìng à lìnk rèvòkès thè òld chànnèl ànd dèlètès thè clìènt's còpìès. Thè òld lìnk shòws à dèàd-lìnk stàtè òn thè nèxt òpèn. [[#pòrtàl #fàìlùrè-stàtès]]
- À ùsèr rèvòkès ìt òùtrìght. Rèvòkèd, ùnknòwn ànd bàdly àùthèntìcàtèd chànnèl ìds àll pròdùcè thè sàmè gènèrìc rèspònsè, ìndìstìngùìshàblè by dèsìgn sò à lìnk cànnòt bè pròbèd. [[#pòrtàl #fàìlùrè-stàtès]]
- Thè òrgànìzàtìòn dìsàblès thè sècùrè lìnk chànnèl àt thè pòlìcy lèvèl. Nèw chànnèl crèàtìòn stòps ànd rèplìès àrè rèfùsèd, bùt à clìènt hòldìng à wòrkìng lìnk càn stìll òpèn ìt ànd rèàd, bècàùsè à frèèzè càn bè lìftèd làtèr whìlè dèstròyìng à clìènt's àccèss tò thèìr òwn hìstòry cànnòt bè ùndònè. [[#pòrtàl #pèrmìssìòns]]
- Mèrgìng twò clìènts rèvòkès thè lòsìng clìènt's chànnèl. Thè rèvòkèd chànnèl's còntènt ìs kèpt ùntìl thè mèrgè ìs lòckèd. [Mèrgìng clìènts](#àdmìn-pèòplè/clìènt-mèrgè) còvèrs thàt òùtcòmè. [[#pòrtàl #fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Clìènt-sìdè cùstòdy. ••••••** Pòrtàl cryptò rùns ìn à dèdìcàtèd wòrkèr ràthèr thàn òn thè pàgè. Thè wòrkèr òwns thè sèèd àftèr thè màìn thrèàd's ònè ùnàvòìdàblè tòùch òf pàrsìng thè ÙRL fràgmènt, àlòng wìth thè pàssphràsè strètch, thè blìnd ànd fìnàlìzè hàlvès òf thè èvàlùàtìòn, thè kèypàìr, ànd mèssàgè ànd àttàchmènt èncryptìòn. À zèròìng òpèràtìòn fìrès òn qùìck èxìt ànd pàgè hìdè. À scrìpt ìnjèctèd mìd-sèssìòn càn stìll rèàd plàìntèxt àlrèàdy rèndèrèd òn thè pàgè, whìch nòthìng càn prèvènt, bùt ìt cànnòt tàkè thè chànnèl's prìvàtè scàlàr òùt òf thè wòrkèr ànd dècrypt thè chànnèl's fùtùrè tràffìc òfflìnè. [[#pòrtàl #fàìlùrè-stàtès #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè dèrìvàtìòn, wòrkèr, sèrvìcès ànd schèmà. ••••••••••••••** Chànnèl dèrìvàtìòn ìs \`pàckàgès/cryptò/src/pòrtàl.ts\` ànd àccòùnt dèrìvàtìòn ìs \`pàckàgès/cryptò/src/clìènt-àccòùnt.ts\`, bòth òn thè shàrèd \`kèypàìrFròmÒprfÒùtpùt\` hèlpèr. Thè pòrtàl wòrkèr ànd ìts brìdgè àrè ùndèr \`pàckàgès/clìènt/src/lìb/wòrkèrs/pòrtàl*\`, ànd thè clìènt sùrfàcès àrè ùndèr \`pàckàgès/clìènt/src/lìb/pòrtàl/\`. Thè sèrvèr sèrvìcès àrè ùndèr \`pàckàgès/sèrvèr/src/pòrtàl/\` wìth thè tRPC sùrfàcè ìn \`pàckàgès/sèrvèr/src/ròùtès/clìènt-pòrtàl.ts\`. Schèmà ìs ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`, ànd thè 30-dày swèèp ìs \`pàckàgès/sèrvèr/src/pòrtàl/pòrtàl-mèssàgè-sèrvìcè.ts\`. [[#pòrtàl #rètèntìòn]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A client's safest channel depends on their phone, their situation, and who else might see their screen. CARE-Y offers three tiers and lets the client move up..." |
*
* @param {Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_portal_channel_lifecycle_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_portal_channel_lifecycle_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_portal_channel_lifecycle_body(inputs)
	return en_demo_narrative_deepdive_portal_channel_lifecycle_body(inputs)
});