/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Reply_BodyInputs */

const en_demo_narrative_topic_reply_body = /** @type {(inputs: Demo_Narrative_Topic_Reply_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A reply written on a case is encrypted in the browser under that case's own key before it goes anywhere, and the server stores the result without holding a key that opens it. How much of the trip is protected after that depends on the channel, because a message sent to an encrypted portal channel is sealed for the client's own browser while a text message has to be handed to a phone company in a form it can act on. The user picks the channel before composing, and picking one that leaves the encrypted path shows a note saying so once per session. [[#encryption #telephony]]
**The two copies a reply produces.** Sending writes the message twice, once for the organization and once for the client, and different keys open the two. [[#encryption #portal]]
- The organization's copy is encrypted under the case's symmetric key and stored as a follow-up row on the case, readable by the users that case's key is wrapped for. [[#encryption #client-data]]
- The client's copy is sealed to the public key of their active portal channel and stored beside that channel, readable in the client's own browser and nowhere else. [[#portal #encryption]]
When the client has no encrypted channel open, the second copy is not written and the reply reaches them over the channel they came in on. [How encryption works](#deep-dive/how-encryption-works) covers the key hierarchy behind both copies. [[#encryption #portal]]
**Sending a text.** The browser posts the case id and the message to a relay endpoint, and the server resolves and decrypts the client's phone number itself rather than accepting one from the browser, which keeps the number out of the request. It hands both to the telephony provider and then zeroes every buffer that touched plaintext in a \`finally\` block, covering the raw request body, the case id, the message and the phone number. The endpoint logs no request body, returns no content in an error response, and caps the message at 1600 bytes. One residual risk stays recorded in the code beside the line that creates it, which is that the provider interface accepts strings rather than buffers, so two immutable copies of the number and the message exist for the length of a single outbound HTTP call and persist until garbage collection. A text is refused outright when the organization has switched the SMS channel off. [The telephony relay](#deep-dive/the-telephony-relay) covers what the carrier and the provider see once it leaves. [[#telephony #server-holds #encryption]]
**When half a send succeeds.** The relay runs before the thread write, so a message can reach the client and then fail to be recorded. The composer keeps the encrypted copy it already built, says that the message was delivered but not saved, and retries the thread write alone, so a retry never puts a second text on the client's phone. The opposite ordering would trade this failure for a thread showing a message that was never sent. [[#failure-states #telephony]]
**What the server keeps of a reply.** The follow-up row's content is ciphertext and the rest of the row is not. Its case id, its source, its type, its private flag, the account that wrote it, the pseudonyms mentioned in it and its creation time are plaintext columns, so a database dump shows that a particular account sent a text on a particular case at a particular minute, and shows neither the text nor whom the case concerns. The content is sealed with an authenticated stream cipher, so ciphertext length follows message length and separates a one-word reply from a long one. [The trust boundary](#deep-dive/the-trust-boundary) lists the plaintext columns elsewhere in the schema. [[#metadata #server-holds #client-data]]
**Drafts.** Unsent compose text is held in memory for the life of the tab and never written to storage, so a draft on a device someone else can reach does not outlive the session, and one store backs both the user's thread and the client's. [[#client-data #privacy]]
**Who may send on which channel.** Each relay endpoint is gated on its own permission, with text, email and calls separated so an organization can staff them differently, and the check runs on the server for every request rather than in the compose bar that hides the option. [The permission system](#deep-dive/the-permission-system) covers moving those between roles. [[#permissions #telephony]]
**The send path and the relay handlers.** The compose surfaces are \`ReplySheet.svelte\` and \`TicketCompose.svelte\` under \`packages/client/src/lib/components/tickets/\`, and the send paths are \`create-send-message.svelte.ts\`, \`create-sms-send.svelte.ts\` and the shared \`relay-then-record.ts\` under \`packages/client/src/lib/composables/ticket-detail/\`. The relay handlers are \`packages/server/src/routes/relay.ts\` with shared body parsing and authentication in \`relay-utils.ts\`, and the thread row is written through \`packages/server/src/tickets/followup-service.ts\`. The row's shape comes from \`packages/server/src/db/migrations/tenant/026_create_followups.ts\` with \`047_add_followup_authoring.ts\`. [[#client-data #server-holds]]`)
};

const es_demo_narrative_topic_reply_body = /** @type {(inputs: Demo_Narrative_Topic_Reply_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Una respuesta escrita en un caso se cifra en el navegador con la clave propia de ese caso antes de salir a ninguna parte, y el servidor guarda el resultado sin tener ninguna clave que lo abra. Cuánto del trayecto queda protegido a partir de ahí depende del canal, porque un mensaje enviado a un canal cifrado del portal se sella para el propio navegador del cliente, mientras que un mensaje de texto hay que entregarlo a una compañía telefónica en una forma con la que pueda operar. La persona usuaria elige el canal antes de redactar, y elegir uno que sale de la ruta cifrada muestra un aviso que lo indica una vez por sesión. [[#encryption #telephony]]
**Las dos copias que produce una respuesta.** El envío escribe el mensaje dos veces, una para la organización y otra para el cliente, y cada una se abre con una clave distinta. [[#encryption #portal]]
- La copia de la organización se cifra con la clave simétrica del caso y se guarda como una fila de seguimiento en ese caso, legible para las personas usuarias para las que está envuelta la clave de ese caso. [[#encryption #client-data]]
- La copia del cliente se sella con la clave pública de su canal activo del portal y se guarda junto a ese canal, legible en su propio navegador y en ningún otro sitio. [[#portal #encryption]]
Cuando no hay ningún canal cifrado abierto, la segunda copia no se escribe y la respuesta llega por el canal por el que entró el cliente. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la jerarquía de claves que hay detrás de ambas copias. [[#encryption #portal]]
**Enviar un mensaje de texto.** El navegador envía el identificador del caso y el mensaje a un extremo de relevo, y el servidor resuelve y descifra por su cuenta el número de teléfono del cliente en lugar de aceptar uno del navegador, lo que mantiene el número fuera de la solicitud. Entrega ambos al proveedor de telefonía y después pone a cero, en un bloque \`finally\`, todos los búferes que tocaron texto plano, lo que cubre el cuerpo crudo de la solicitud, el identificador del caso, el mensaje y el número de teléfono. El extremo no registra ningún cuerpo de solicitud, no devuelve contenido en una respuesta de error y limita el mensaje a 1600 bytes. Un riesgo residual queda anotado en el código junto a la línea que lo crea, y es que la interfaz del proveedor acepta cadenas en lugar de búferes, así que existen dos copias inmutables del número y del mensaje durante una sola llamada HTTP saliente y persisten hasta la recolección de basura. Un mensaje de texto se rechaza de plano cuando la organización ha desactivado el canal SMS. [El relevo de telefonía](#deep-dive/the-telephony-relay) trata lo que ven la operadora y el proveedor una vez que sale. [[#telephony #server-holds #encryption]]
**Cuando un envío solo se completa a medias.** El relevo se ejecuta antes de la escritura en el hilo, así que un mensaje puede llegar al cliente y luego fallar al registrarse. El redactor conserva la copia cifrada que ya había construido, avisa de que el mensaje se entregó pero no se guardó, y reintenta solo la escritura en el hilo, de modo que un reintento nunca pone un segundo mensaje de texto en el teléfono del cliente. El orden inverso cambiaría este fallo por un hilo que muestra un mensaje que nunca se envió. [[#failure-states #telephony]]
**Lo que el servidor guarda de una respuesta.** El contenido de la fila de seguimiento es texto cifrado y el resto de la fila no lo es. El identificador del caso, su origen, su tipo, su marca de privada, la cuenta que la escribió, los seudónimos mencionados en ella y su hora de creación son columnas en texto plano, así que un volcado de la base de datos muestra que una cuenta concreta envió un mensaje de texto en un caso concreto en un minuto concreto, y no muestra ni el texto ni a quién concierne el caso. El contenido se sella con un cifrado de flujo autenticado, así que la longitud del texto cifrado sigue a la del mensaje y separa una respuesta de una palabra de una larga. [La frontera de confianza](#deep-dive/the-trust-boundary) enumera las columnas en texto plano del resto del esquema. [[#metadata #server-holds #client-data]]
**Borradores.** El texto sin enviar del redactor se guarda en memoria mientras vive la pestaña y nunca se escribe en almacenamiento, así que un borrador en un dispositivo al que otra persona puede llegar no sobrevive a la sesión, y un mismo almacén sirve tanto al hilo de la persona usuaria como al del cliente. [[#client-data #privacy]]
**Quién puede enviar por cada canal.** Cada extremo de relevo está protegido por su propio permiso, con los mensajes de texto, el correo y las llamadas separados para que una organización pueda asignar personal de forma distinta a cada uno, y la comprobación se ejecuta en el servidor en cada solicitud y no en la barra de redacción que oculta la opción. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se trasladan esos permisos entre roles. [[#permissions #telephony]]
**La ruta de envío y los manejadores de relevo.** Las superficies de redacción son \`ReplySheet.svelte\` y \`TicketCompose.svelte\` en \`packages/client/src/lib/components/tickets/\`, y las rutas de envío son \`create-send-message.svelte.ts\`, \`create-sms-send.svelte.ts\` y el compartido \`relay-then-record.ts\` en \`packages/client/src/lib/composables/ticket-detail/\`. Los manejadores de relevo son \`packages/server/src/routes/relay.ts\` con el análisis del cuerpo y la autenticación compartidos en \`relay-utils.ts\`, y la fila del hilo se escribe mediante \`packages/server/src/tickets/followup-service.ts\`. La forma de la fila viene de \`packages/server/src/db/migrations/tenant/026_create_followups.ts\` junto con \`047_add_followup_authoring.ts\`. [[#client-data #server-holds]]`)
};

const en_xa2_demo_narrative_topic_reply_body = /** @type {(inputs: Demo_Narrative_Topic_Reply_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Whèn à vòlùntèèr sènds à rèply, thè mèssàgè ìs èncryptèd òn thè dèvìcè wìth thè pèr tìckèt kèy bèfòrè ìt rèàchès thè sèrvèr. Thè sèrvèr stòrès thè cìphèrtèxt ànd dèlìvèrs ìt tò thè rècìpìènt.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**SMS rèplìès. ••••** Ìf thè chànnèl ìs SMS, thè sèrvèr fòrwàrds thè mèssàgè tò thè tèlèphòny pròvìdèr thròùgh à stàtèlèss rèlày thàt rèàds thè rèqùèst bòdy às à ràw bùffèr ànd zèròs ìt fròm mèmòry ìmmèdìàtèly àftèr fòrwàrdìng. Thè rèlày nèvèr crèàtès à JàvàScrìpt strìng fròm thè còntènt, ànd thè sèrvèr dòès nòt stòrè òr lòg thè òùtbòùnd mèssàgè. À rèsìdùàl rìsk ìs àcknòwlèdgèd ìn thè còdè: thè tèlèphòny pròvìdèr's SDK mày crèàtè ìntèrnàl strìng còpìès thàt pèrsìst ùntìl gàrbàgè còllèctìòn.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dèlìvèry cònfìrmàtìòn. •••••••** Thè thrèàd shòws dèlìvèry stàtùs fòr èàch òùtbòùnd mèssàgè sò thè vòlùntèèr knòws whèthèr thè mèssàgè rèàchèd thè clìènt. •••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A reply written on a case is encrypted in the browser under that case's own key before it goes anywhere, and the server stores the result without holding a k..." |
*
* @param {Demo_Narrative_Topic_Reply_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_reply_body = /** @type {((inputs?: Demo_Narrative_Topic_Reply_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Reply_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_reply_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_reply_body(inputs)
	return en_demo_narrative_topic_reply_body(inputs)
});