/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Filters_BodyInputs */

const en_demo_narrative_topic_filters_body = /** @type {(inputs: Demo_Narrative_Topic_Filters_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Filters narrow the case list by status, queue, priority, assignee, on-hold state, creation date range, unread state and needs-attention, and several can be active at once. [[#metadata #trust-boundary]]
**Which side each filter runs on.** The list is assembled in two passes. [[#metadata #trust-boundary]]
- The server evaluates queue, priority, assignee, on-hold state and creation date range against plaintext columns on the case row, and returns matching rows whose title and description it cannot decrypt. [[#server-holds #metadata]]
- The browser evaluates unread and needs-attention against read cursors only it can decrypt, and it also separates New from Active, which the server cannot do because it stores open and closed alone. [[#client-data #encryption]]
Before either pass runs, the server scopes the query to the queues the signed-in account has access to, so filtering can only narrow what it already has permission to see. Membership in a queue is what grants that access, and [The permission system](#deep-dive/the-permission-system) covers it. [[#permissions]]
**What a filter request tells the server.** A filter the server evaluates is a filter the server can read, so the request itself says which queue, which priority, which assignee and which date window the account is browsing, and when it browsed. Keeping unread in the browser hides how far into a case an account has read and how much of it is left unread, and it does not hide that the account opened the case, because a read cursor row exists for each case an account has opened with only the cursor position encrypted. [The trust boundary](#deep-dive/the-trust-boundary) sets out that row and the others like it. [[#metadata #server-holds #privacy]]
**How unread is decided.** A case counts as unread when its cursor decrypts to a real position and activity by someone other than the signed-in account has happened since. A case nobody has opened yet is not unread, because its New mark already announces it, and an account's own reply is never unread to the account that wrote it. Decrypted read state lives in the browser for the session, is cleared when the idle timer zeroes keys and the filters are unavailable until the next sign-in, and nothing derived from it is ever sent back. [[#client-data #encryption #privacy]]
**How needs attention is decided.** The filter keeps an open case that is not on hold and is marked urgent or high priority, and then keeps that case if it is unassigned, or if it is assigned to the signed-in account and unread. The dashboard bucket of the same name reads from this one rule rather than a second copy of it, so the two surfaces cannot drift apart. [[#metadata]]
**Unread beyond the loaded window.** The list loads a window rather than a whole queue, so an unread filter reading only loaded rows would miss unread cases the window has not loaded. A separate sweep enumerates the account's cursor rows across every open case it has access to, fetches the unread ones the window has not loaded, and merges them in only after they pass the same narrowing the loaded rows went through, which is what keeps an unread case the active filters exclude out of the list. [[#client-data #failure-states]]
**What survives a reload.** Filter selections live in memory and reset with the tab. A saved filter is written to the device's local storage with its name encrypted under the organization key and its filter state stored as readable JSON, so anyone with the device can read which queue and priority a saved view targets without reading what it is called. [Saved filters](#tickets/saved-filters) covers the rest of that surface. [[#privacy #client-data]]
**The filter query path.** The store is \`packages/client/src/lib/stores/filters.svelte.ts\`, which holds the display statuses and maps them onto server parameters, with the persisted ones in \`saved-filters.svelte.ts\`. The browser-side passes run in \`packages/client/src/routes/(app)/tickets/+page.svelte\` against \`packages/client/src/lib/tickets/create-list-read-state.svelte.ts\`, and the needs-attention rule is \`isNeedsAttention\` in \`packages/client/src/lib/components/dashboard/filters.ts\`. The server clauses are in \`packages/server/src/tickets/ticket-service.ts\`. Anyone adding a filter dimension chooses a side for it, and a dimension the server evaluates is a dimension the server can read. [[#trust-boundary #permissions]]`)
};

const es_demo_narrative_topic_filters_body = /** @type {(inputs: Demo_Narrative_Topic_Filters_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los filtros reducen la lista de casos por estado, cola, prioridad, persona asignada, estado de espera, rango de fechas de creación, estado de lectura y «necesita atención», y se pueden activar varios a la vez. [[#metadata #trust-boundary]]
**En qué lado se ejecuta cada filtro.** La lista se compone en dos pasadas. [[#metadata #trust-boundary]]
- El servidor evalúa la cola, la prioridad, la persona asignada, el estado de espera y el rango de fechas de creación contra columnas en texto plano de la fila del caso, y devuelve las filas coincidentes cuyo título y descripción no puede descifrar. [[#server-holds #metadata]]
- El navegador evalúa el estado de lectura y «necesita atención» contra cursores de lectura que solo él puede descifrar, y además separa lo nuevo de lo activo, algo que el servidor no puede hacer porque solo guarda abierto y cerrado. [[#client-data #encryption]]
Antes de cualquiera de las dos pasadas, el servidor acota la consulta a las colas a las que tiene acceso la cuenta que ha iniciado sesión, así que filtrar solo puede reducir lo que ya tiene permiso para ver. La pertenencia a una cola es lo que concede ese acceso, y [El sistema de permisos](#deep-dive/the-permission-system) lo trata. [[#permissions]]
**Lo que una consulta de filtro le dice al servidor.** Un filtro que evalúa el servidor es un filtro que el servidor puede leer, así que la propia consulta dice qué cola, qué prioridad, qué persona asignada y qué ventana de fechas está mirando la cuenta, y cuándo lo miró. Mantener el estado de lectura en el navegador oculta hasta dónde ha leído una cuenta dentro de un caso y cuánto le queda sin leer, y no oculta que esa cuenta abrió el caso, porque existe una fila de cursor de lectura por cada caso que una cuenta ha abierto y solo la posición del cursor está cifrada. [La frontera de confianza](#deep-dive/the-trust-boundary) expone esa fila y las demás de su tipo. [[#metadata #server-holds #privacy]]
**Cómo se determina lo no leído.** Un caso cuenta como no leído cuando su cursor se descifra a una posición real y desde entonces ha habido actividad de alguien distinto de la cuenta que ha iniciado sesión. Un caso que nadie ha abierto todavía no cuenta como no leído, porque su marca de nuevo ya lo anuncia, y la propia respuesta de una cuenta nunca queda sin leer para quien la escribió. El estado de lectura descifrado vive en el navegador durante la sesión, se borra cuando el temporizador de inactividad pone las claves a cero y los filtros no están disponibles hasta el siguiente inicio de sesión, y nada derivado de él se devuelve jamás al servidor. [[#client-data #encryption #privacy]]
**Cómo se determina «necesita atención».** El filtro conserva un caso abierto que no esté en espera y esté marcado con prioridad urgente o alta, y a continuación lo conserva si no tiene a nadie asignado, o si está asignado a la cuenta que ha iniciado sesión y sin leer. El grupo del mismo nombre del panel principal lee de esta única regla en lugar de una segunda copia, así que las dos superficies no pueden separarse. [[#metadata]]
**Lo no leído más allá de la ventana cargada.** La lista carga una ventana en vez de una cola entera, así que un filtro de no leídos que mirara solo las filas cargadas se dejaría los casos no leídos que la ventana no ha cargado. Un barrido aparte enumera las filas de cursor de la cuenta en todos los casos abiertos a los que tiene acceso, recupera los no leídos que la ventana no ha cargado y los incorpora solo después de que pasen el mismo acotamiento por el que pasaron las filas cargadas, que es lo que deja fuera de la lista un caso no leído excluido por los filtros activos. [[#client-data #failure-states]]
**Qué sobrevive a una recarga.** Las selecciones de filtro viven en memoria y se reinician con la pestaña. Un filtro guardado se escribe en el almacenamiento local del dispositivo con su nombre cifrado con la clave de la organización y su estado de filtro guardado como JSON legible, así que quien tenga el dispositivo puede leer a qué cola y a qué prioridad apunta una vista guardada sin leer cómo se llama. [Filtros guardados](#tickets/saved-filters) trata el resto de esa superficie. [[#privacy #client-data]]
**La ruta de consulta de filtros.** El almacén es \`packages/client/src/lib/stores/filters.svelte.ts\`, que guarda los estados de presentación y los traduce a parámetros del servidor, con los persistentes en \`saved-filters.svelte.ts\`. Las pasadas del lado del navegador se ejecutan en \`packages/client/src/routes/(app)/tickets/+page.svelte\` sobre \`packages/client/src/lib/tickets/create-list-read-state.svelte.ts\`, y la regla de «necesita atención» es \`isNeedsAttention\` en \`packages/client/src/lib/components/dashboard/filters.ts\`. Las cláusulas del servidor están en \`packages/server/src/tickets/ticket-service.ts\`. Quien añada una dimensión de filtro le elige un lado, y una dimensión que evalúa el servidor es una dimensión que el servidor puede leer. [[#trust-boundary #permissions]]`)
};

const en_xa2_demo_narrative_topic_filters_body = /** @type {(inputs: Demo_Narrative_Topic_Filters_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Fìltèr pìlls nàrròw thè tìckèt lìst by stàtùs, qùèùè, prìòrìty, àssìgnèè, òn hòld stàtè, dàtè ràngè, òr ùnrèàd stàtè. Mùltìplè fìltèrs càn bè àctìvè àt òncè.
 ••••••••••••••••••••••••••••••••••••••••••••••••**Sèrvèr sìdè fìltèrs. ••••••** Qùèùè, prìòrìty, àssìgnèè, òn hòld stàtè, ànd dàtè ràngè àrè èvàlùàtèd òn thè sèrvèr ùsìng plàìntèxt mètàdàtà còlùmns, ànd thè sèrvèr rètùrns màtchìng ròws wìthòùt àccèssìng èncryptèd tìckèt còntènt. Thè sèrvèr fìltèrs òn thè ràw stàtùs còlùmn (òpèn òr clòsèd), whìlè thè nèw ànd àctìvè dìstìnctìòn ìs dèrìvèd ìn thè bròwsèr fròm thè mèssàgè còùnt.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Clìènt sìdè fìltèrs. ••••••** Ùnrèàd ànd nèèds àttèntìòn fìltèrs rùn ìn thè bròwsèr bècàùsè rèàd stàtè ìs pèr vòlùntèèr ànd nòt qùèryàblè by thè sèrvèr.
 ••••••••••••••••••••••••••••••••••••••**Ùnrèàd fìltèr. •••••** À dèdìcàtèd fìltèr shòws ònly tìckèts wìth ùnrèàd mèssàgès. Còmbìnèd wìth thè nèw rèplìès fìrst sòrt òptìòn, thìs gìvès vòlùntèèrs à fòcùsèd vìèw òf càsès thàt nèèd àttèntìòn. •••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Filters narrow the case list by status, queue, priority, assignee, on-hold state, creation date range, unread state and needs-attention, and several can be a..." |
*
* @param {Demo_Narrative_Topic_Filters_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_filters_body = /** @type {((inputs?: Demo_Narrative_Topic_Filters_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Filters_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_filters_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_filters_body(inputs)
	return en_demo_narrative_topic_filters_body(inputs)
});