/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Retention_BodyInputs */

const en_demo_narrative_admin_retention_body = /** @type {(inputs: Demo_Narrative_Admin_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Automatic deletion is off when an organization starts, and turning it on means choosing a window between 1 and 3,650 days, with 365 filled in as a starting point. Cases, messages and caller personal information older than that window are deleted permanently. Switching the policy on and changing the number afterwards both ask for confirmation, and the confirmation says that deleted data cannot be recovered even from the escrow file, because escrow holds key material rather than rows. Switching the policy back off asks as well, and returns the organization to keeping those records until someone deletes them by hand. [[#retention]]
**One window for the whole organization.** The window is a single organization-wide setting rather than a choice per queue or per case type, so nobody has to get a retention period right on the day they create a queue. Audit entries are exempt from it, so the record that something happened outlives the content of what happened. [[#retention #metadata]]
**What the window does not reach.** Three other clocks delete data on their own schedules and are unaffected by this setting, covering the client-side copies of portal messages, one-time share links, and the logs held at the telephony provider. [Data retention](#deep-dive/data-retention) sets out each one. Nothing outside the organization's own database is in scope either, so a copy a client kept on their own phone, a message sitting in someone else's mailbox and a record a third party holds all survive the window, which is part of why the client-facing pages offer [a quick exit](#client-portal/quick-exit). Deletion runs one way, and no escrow ceremony and no backup restores a row the policy removed. [[#retention #failure-states]]
**What the setting itself discloses.** The window is stored as a plaintext integer column beside the encrypted columns in the same organization configuration row, so a database dump shows the organization's retention choice in the clear. After a deletion runs, audit rows keep their event type, actor id, case id and timestamp, and the row counts and foreign key relationships that remain stay readable structurally, so a dump taken after a sweep still shows the shape of the work that was deleted. [The trust boundary](#deep-dive/the-trust-boundary) covers what that shape gives away. [[#server-holds #metadata #retention]]
**Who can change it.** Configuring the window requires the Manage retention permission, which sits with Admin by default and can be moved to another role. [The permission system](#deep-dive/the-permission-system) covers how a permission moves and which three can never move. [[#permissions]]
**The retention column and its write path.** The control is \`packages/client/src/lib/components/admin/RetentionSection.svelte\`, which the organization admin page renders as one of its sections and the first-run setup flow renders again with its save button supplied from outside, so the same component states the same consequence in both places. The value is written through \`setPiiRetentionDays\` in \`packages/server/src/auth/service.ts\` behind a permission-gated procedure in \`packages/server/src/routes/auth.ts\`, and read back for display through the admin hub status query. The column is defined in \`packages/server/src/db/migrations/tenant/003_create_org_config.ts\`. [[#retention #server-holds]]`)
};

const es_demo_narrative_admin_retention_body = /** @type {(inputs: Demo_Narrative_Admin_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La eliminación automática está desactivada cuando una organización empieza, y activarla implica elegir una ventana de entre 1 y 3.650 días, con 365 como punto de partida ya escrito. Los casos, los mensajes y la información personal de quienes llaman con una antigüedad mayor que esa ventana se eliminan de forma permanente. Tanto activar la política como cambiar después la cifra piden confirmación, y la confirmación indica que los datos eliminados no se pueden recuperar ni siquiera con el archivo de custodia, porque la custodia guarda material de claves y no filas. Desactivar la política también pide confirmación, y devuelve a la organización a conservar esos registros hasta que alguien los elimine a mano. [[#retention]]
**Una sola ventana para toda la organización.** La ventana es un único ajuste para toda la organización en lugar de una elección por cola o por tipo de caso, así que nadie tiene que acertar con un periodo de retención el día que crea una cola. Las entradas de auditoría están exentas de ella, de modo que el registro de que algo ocurrió sobrevive al contenido de lo que ocurrió. [[#retention #metadata]]
**Lo que la ventana no alcanza.** Otros tres relojes eliminan datos según sus propios plazos y no se ven afectados por este ajuste, y cubren las copias del lado del cliente de los mensajes del portal, los enlaces compartidos de un solo uso y los registros que guarda el proveedor de telefonía. [Retención de datos](#deep-dive/data-retention) expone cada uno de ellos. Tampoco entra en su alcance nada que esté fuera de la base de datos de la propia organización, así que una copia que el cliente guardó en su teléfono, un mensaje que está en el buzón de otra persona y un registro en manos de un tercero sobreviven a la ventana, y en parte por eso las páginas del cliente ofrecen [una salida rápida](#client-portal/quick-exit). La eliminación va en un solo sentido, y ninguna ceremonia de custodia ni copia de seguridad restaura una fila que la política haya quitado. [[#retention #failure-states]]
**Lo que revela el propio ajuste.** La ventana se guarda como una columna de entero en texto plano junto a las columnas cifradas de esa misma fila de configuración de la organización, así que un volcado de la base de datos muestra en claro la elección de retención de la organización. Después de una eliminación, las filas de auditoría conservan su tipo de evento, el identificador de quien actuó, el identificador del caso y la marca de tiempo, y los recuentos de filas y las relaciones de clave foránea que quedan siguen siendo legibles a nivel estructural, de modo que un volcado tomado tras un barrido aún muestra la forma del trabajo que se eliminó. [La frontera de confianza](#deep-dive/the-trust-boundary) trata lo que esa forma deja ver. [[#server-holds #metadata #retention]]
**Quién puede cambiarlo.** Configurar la ventana requiere el permiso de gestión de la retención, que por defecto corresponde a Admin y puede trasladarse a otro rol. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se traslada un permiso y cuáles son los tres que nunca pueden trasladarse. [[#permissions]]
**La columna de retención y su ruta de escritura.** El control es \`packages/client/src/lib/components/admin/RetentionSection.svelte\`, que la página de administración de la organización renderiza como una de sus secciones y el flujo de configuración inicial vuelve a renderizar con el botón de guardado aportado desde fuera, de manera que el mismo componente enuncia la misma consecuencia en ambos sitios. El valor se escribe mediante \`setPiiRetentionDays\` en \`packages/server/src/auth/service.ts\` detrás de un procedimiento protegido por permiso en \`packages/server/src/routes/auth.ts\`, y se vuelve a leer para mostrarlo a través de la consulta de estado del panel de administración. La columna se define en \`packages/server/src/db/migrations/tenant/003_create_org_config.ts\`. [[#retention #server-holds]]`)
};

const en_xa2_demo_narrative_admin_retention_body = /** @type {(inputs: Demo_Narrative_Admin_Retention_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Àùtòmàtìc dèlètìòn àccèpts à wìndòw òf 1 tò 3,650 dàys, ànd bòth ènàblìng ànd chàngìng thè vàlùè àsk fòr cònfìrmàtìòn. Thè cònfìrmàtìòn stàtès thàt dèlètèd dàtà cànnòt bè rècòvèrèd èvèn wìth thè èscròw fìlè.
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Scòpè. ••** Thè rètèntìòn pòlìcy àpplìès tò tìckèts, mèssàgès, ànd càllèr pèrsònàl ìnfòrmàtìòn òldèr thàn thè cùtòff, ànd ìt ìs sèt òncè fòr thè whòlè òrgànìzàtìòn ràthèr thàn pèr qùèùè òr pèr tìckèt typè. Àùdìt èntrìès àrè èxèmpt fròm thìs pòlìcy.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pèrmìssìòns. ••••** Cònfìgùrìng thè rètèntìòn pòlìcy rèqùìrès thè Mànàgè rètèntìòn pèrmìssìòn. •••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Automatic deletion is off when an organization starts, and turning it on means choosing a window between 1 and 3,650 days, with 365 filled in as a starting p..." |
*
* @param {Demo_Narrative_Admin_Retention_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_retention_body = /** @type {((inputs?: Demo_Narrative_Admin_Retention_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Retention_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_retention_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_retention_body(inputs)
	return en_demo_narrative_admin_retention_body(inputs)
});