/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Trust_Boundary_BodyInputs */

const en_demo_narrative_deepdive_trust_boundary_body = /** @type {(inputs: Demo_Narrative_Deepdive_Trust_Boundary_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The trust boundary is the line between what the server can read and what only a browser can read, and knowing where it sits is how an organization decides whether CARE-Y is safe enough for the people it serves. [[#trust-boundary #encryption]]
The browser side of the line holds the content that identifies or quotes anyone. [[#trust-boundary #encryption #client-data]]
- A client's alias, which is the name the organization records for them. [[#trust-boundary #client-data]]
- Messages, case notes, and the files attached to a case. [[#trust-boundary #client-data]]
- Queue names, library articles and note types. [[#trust-boundary #encryption]]
- An intake form's questions and the answers a client submitted. [[#trust-boundary #client-data]]
The server side of the line holds the facts the server needs to do its job without a person present. [[#trust-boundary #server-holds #metadata]]
- It knows a case exists, when it was created, which queue it belongs to, what status and priority it carries, and which account is assigned to it. [[#trust-boundary #server-holds]]
- It knows how many messages a case has and when each arrived. [[#trust-boundary #metadata]]
- It knows which accounts exist, when they signed in, and which second-factor methods they enrolled. [[#trust-boundary #metadata]]
- It knows the credentials for the phone system and the mail server, because it has to use them. [[#trust-boundary #server-holds]]
- It has access to a client's phone number and email address, because it is what dials the number and addresses the mail, and those two values are sealed under the server's own operational key rather than under the organization's. [[#trust-boundary #server-holds #client-data]]
- Shift schedule assignments record which account covers which hours in plaintext. [[#trust-boundary #server-holds #metadata]]
Metadata is the cost of that arrangement, and activity patterns are visible in it. A dump shows when the organization is busy, which queues carry the most work, how long cases stay open, how often a particular account is active, and when someone signed in. Relationship structure is visible too, because the assignment column names a real account and there is one read-marker row per user per case they opened. None of that identifies a client, and all of it describes the organization to anyone holding the database. An organization whose threat model includes an adversary interested in staffing patterns rather than case contents should weigh this exposure before adopting the system. [[#metadata #privacy #trust-boundary]]
The following sit outside the encryption boundary entirely by design. [[#trust-boundary #privacy]]
- Intake page branding is public, so a client can recognize who they are contacting. [[#trust-boundary #privacy]]
- A notification email address stored on an account is readable by the server under the operational key, because the server is what addresses the message. Removing email as a second factor clears the address unless the user has chosen to keep it for notifications. In-app and push notifications exist for users who would rather not store an address the server can read. [[#trust-boundary #privacy]]
Third parties hold their own copies of some things, and CARE-Y cannot encrypt what it never touched first. A text message existed in the carrier's network and at the telephony provider before it reached CARE-Y. An email existed in the sender's own mail system. [The telephony relay](#deep-dive/the-telephony-relay) covers what CARE-Y does about that, and [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers the channels that avoid third parties altogether. [[#telephony #portal #trust-boundary]]
**Plaintext columns, named.** The tables below carry the bulk of the plaintext metadata. [[#server-holds #metadata #client-data]]
- On \`tickets\`, the plaintext columns are \`id\`, \`client_id\`, \`queue_id\`, \`status\`, \`priority\`, \`on_hold\`, \`assigned_to\`, \`key_generation\` and \`created_at\`, while \`encrypted_title\` and \`encrypted_description\` are bytea. [[#server-holds #client-data]]
- On \`clients\`, \`encrypted_alias\` is bytea under the organization key with an \`alias_hash\` blind index beside it, \`communication_tier\` is plaintext and names which channel tier the client is on, \`phone_id\` and \`email_id\` are foreign keys to \`phones\` and \`emails\` respectively. On \`phones\`, \`encrypted_number\` is bytea under the server's operational key beside a \`phone_hash\` blind index, with \`locale\`, \`location_city\` and \`location_region\` in plaintext. On \`emails\`, \`encrypted_address\` is bytea under the operational key beside an \`email_hash\` blind index. [[#server-holds #client-data]]
- On \`portal_channels\`, the channel id, client id, auth hash, client public key, passphrase flag, status and activity timestamps are plaintext while every message body in \`portal_messages\` is ciphertext. [[#server-holds #portal]]
- On \`ticket_read_cursors\`, the case id and user id are the plaintext primary key with only the cursor value encrypted, so the row's existence discloses that the user opened that case while the position stays unreadable. [[#server-holds #metadata]]
Row counts, foreign key relationships and timestamp sequences are readable structurally throughout, which is what makes the activity inference above possible. Narrowing the case list is a SQL query the server runs over those same plaintext columns, so the queue, status, priority, hold state and assignment someone filtered to are visible to it, while a saved filter's name and stored state are sealed to the organization key and are not. [[#metadata #server-holds]]
**Audit and operational records.** The audit log is pseudonymous and largely plaintext by design, holding an event type, an actor id, an optional case id and a JSON metadata object, so an administrator's browser can query it without a decryption pass. It carries no case content, no phone numbers and no client aliases. A failed audit write is retried, and persistent failures surface in the operational health check. Rate-limit counters, job queue rows, session tokens and the key-evaluation audit log are operational-tier data the server reads directly, while the IP address and user agent recorded on a session are sealed to the organization key and are not. [[#server-holds #metadata #privacy]]
**Where does enforcement live?** Every access decision is server-authoritative, and the client hiding a control is convenience only. [[#permissions #trust-boundary]]
- Case access runs through \`packages/server/src/tickets/access.ts\`. [[#permissions #trust-boundary]]
- Permission gates run through \`packages/server/src/auth/roles.ts\` and \`role-middleware.ts\`. [[#permissions]]
- Per-channel policy runs through service-layer assertions at every relay handler and tRPC procedure. [[#permissions #telephony]]
- Organization isolation runs through Kysely schema scoping in \`packages/server/src/db/\`. [[#permissions #server-holds]]
A contributor adding a query decides which side of the boundary its filter runs on, and a filter the server evaluates is a filter the server can read. [[#permissions #trust-boundary]]`)
};

const es_demo_narrative_deepdive_trust_boundary_body = /** @type {(inputs: Demo_Narrative_Deepdive_Trust_Boundary_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La frontera de confianza es la línea entre lo que el servidor puede leer y lo que solo un navegador puede leer, y saber dónde está es como una organización decide si CARE-Y es lo bastante seguro para las personas a las que sirve. [[#trust-boundary #encryption]]
El lado del navegador de la línea guarda el contenido que identifica o cita a alguien. [[#trust-boundary #encryption #client-data]]
- El alias de un cliente, que es el nombre con el que la organización lo registra. [[#trust-boundary #client-data]]
- Los mensajes, las notas de caso y los archivos adjuntos a un caso. [[#trust-boundary #client-data]]
- Los nombres de cola, los artículos de la biblioteca y los tipos de nota. [[#trust-boundary #encryption]]
- Las preguntas de un formulario de ingreso y las respuestas que un cliente envió. [[#trust-boundary #client-data]]
El lado del servidor de la línea guarda los hechos que el servidor necesita para hacer su trabajo sin una persona presente. [[#trust-boundary #server-holds #metadata]]
- Sabe que un caso existe, cuándo se creó, a qué cola pertenece, qué estado y prioridad lleva y qué cuenta está asignada a él. [[#trust-boundary #server-holds]]
- Sabe cuántos mensajes tiene un caso y cuándo llegó cada uno. [[#trust-boundary #metadata]]
- Sabe qué cuentas existen, cuándo iniciaron sesión y qué métodos de segundo factor registraron. [[#trust-boundary #metadata]]
- Conoce las credenciales del sistema telefónico y del servidor de correo, porque tiene que usarlas. [[#trust-boundary #server-holds]]
- Tiene acceso al número de teléfono y a la dirección de correo de un cliente, porque es lo que marca el número y dirige el correo, y esos dos valores van sellados bajo la clave operativa del propio servidor y no bajo la de la organización. [[#trust-boundary #server-holds #client-data]]
- Las asignaciones de turno registran qué cuenta cubre qué horas en texto plano. [[#trust-boundary #server-holds #metadata]]
Los metadatos son el precio de ese arreglo, y los patrones de actividad se ven en ellos. Un volcado muestra cuándo la organización tiene mucho trabajo, qué colas cargan con más, cuánto tiempo siguen abiertos los casos, con qué frecuencia está activa una cuenta concreta y cuándo inició sesión alguien. La estructura de las relaciones también se ve, porque la columna de asignación nombra una cuenta real y hay una fila de marca de lectura por persona y por caso que abrió. Nada de eso identifica a un cliente, y todo ello describe a la organización ante cualquiera que tenga la base de datos. Una organización cuyo modelo de amenaza incluye un adversario interesado en los patrones de personal más que en el contenido de los casos debería pesar esta exposición antes de adoptar el sistema. [[#metadata #privacy #trust-boundary]]
Lo siguiente queda por completo fuera de la frontera de cifrado por diseño. [[#trust-boundary #privacy]]
- La identidad visual de la página de ingreso es pública, para que un cliente pueda reconocer con quién está contactando. [[#trust-boundary #privacy]]
- Una dirección de correo de notificación almacenada en una cuenta es legible por el servidor bajo la clave operativa, porque el servidor es lo que dirige el mensaje. Eliminar el correo como segundo factor borra la dirección a menos que la persona usuaria haya elegido conservarla para notificaciones. Las notificaciones dentro de la aplicación y las push existen para quienes prefieran no almacenar una dirección que el servidor pueda leer. [[#trust-boundary #privacy]]
Terceras partes tienen sus propias copias de algunas cosas, y CARE-Y no puede cifrar lo que nunca tocó primero. Un mensaje de texto existió en la red de la compañía telefónica y en el proveedor de telefonía antes de llegar a CARE-Y. Un correo existió en el propio sistema de correo de quien lo envió. [El relay de telefonía](#deep-dive/the-telephony-relay) trata lo que CARE-Y hace al respecto, y [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) trata los canales que evitan a terceras partes por completo. [[#telephony #portal #trust-boundary]]
**Columnas en texto plano, nombradas.** Las tablas a continuación llevan el grueso de los metadatos en texto plano. [[#server-holds #metadata #client-data]]
- En \`tickets\`, las columnas en texto plano son \`id\`, \`client_id\`, \`queue_id\`, \`status\`, \`priority\`, \`on_hold\`, \`assigned_to\`, \`key_generation\` y \`created_at\`, mientras que \`encrypted_title\` y \`encrypted_description\` son bytea. [[#server-holds #client-data]]
- En \`clients\`, \`encrypted_alias\` es bytea bajo la clave de la organización con un índice ciego \`alias_hash\` al lado, \`communication_tier\` está en texto plano y nombra en qué nivel de canal está el cliente, y \`phone_id\` y \`email_id\` son claves externas a \`phones\` y \`emails\` respectivamente. En \`phones\`, \`encrypted_number\` es bytea bajo la clave operativa del servidor junto a un índice ciego \`phone_hash\`, con \`locale\`, \`location_city\` y \`location_region\` en texto plano. En \`emails\`, \`encrypted_address\` es bytea bajo la clave operativa junto a un índice ciego \`email_hash\`. [[#server-holds #client-data]]
- En \`portal_channels\`, el identificador del canal, el del cliente, el hash de autenticación, la clave pública del cliente, la marca de frase de paso, el estado y las marcas de tiempo de actividad están en texto plano mientras que el cuerpo de cada mensaje en \`portal_messages\` es texto cifrado. [[#server-holds #portal]]
- En \`ticket_read_cursors\`, el identificador del caso y el de la persona usuaria son la clave primaria en texto plano y solo el valor del cursor está cifrado, así que la existencia de la fila revela que la persona abrió ese caso mientras la posición queda ilegible. [[#server-holds #metadata]]
El número de filas, las relaciones de claves externas y las secuencias de marcas de tiempo son legibles estructuralmente en todo el sistema, que es lo que hace posible la inferencia de actividad anterior. Acotar la lista de casos es una consulta SQL que el servidor ejecuta sobre esas mismas columnas en texto plano, así que la cola, el estado, la prioridad, el estado de espera y la asignación a los que alguien filtró le resultan visibles, mientras que el nombre y el estado guardado de un filtro guardado van sellados con la clave de la organización y no. [[#metadata #server-holds]]
**Registros de auditoría y operativos.** El registro de auditoría es seudónimo y en gran parte texto plano por diseño, y contiene un tipo de evento, un identificador de actor, un identificador de caso opcional y un objeto JSON de metadatos, de modo que el navegador de una persona administradora puede consultarlo sin una pasada de descifrado. No lleva contenido de casos, ni números de teléfono, ni alias de clientes. Una escritura de auditoría fallida se reintenta, y los fallos persistentes se muestran en la comprobación de salud operativa. Los contadores de límite de tasa, las filas de la cola de trabajos, los tokens de sesión y el registro de auditoría de evaluación de claves son datos del nivel operativo que el servidor lee directamente, mientras que la dirección IP y el agente de usuario registrados en una sesión van sellados con la clave de la organización y no lo son. [[#server-holds #metadata #privacy]]
**¿Dónde vive la aplicación de las reglas?** Toda decisión de acceso es autoritativa en el servidor, y que el cliente oculte un control es solo comodidad. [[#permissions #trust-boundary]]
- El acceso a los casos pasa por \`packages/server/src/tickets/access.ts\`. [[#permissions #trust-boundary]]
- Las comprobaciones de permisos pasan por \`packages/server/src/auth/roles.ts\` y \`role-middleware.ts\`. [[#permissions]]
- La política por canal pasa por aserciones en la capa de servicios en cada manejador de relay y en cada procedimiento tRPC. [[#permissions #telephony]]
- El aislamiento entre organizaciones pasa por el ámbito de esquema de Kysely en \`packages/server/src/db/\`. [[#permissions #server-holds]]
Quien contribuye una consulta decide en qué lado de la frontera se ejecuta su filtro, y un filtro que el servidor evalúa es un filtro que el servidor puede leer. [[#permissions #trust-boundary]]`)
};

const en_xa2_demo_narrative_deepdive_trust_boundary_body = /** @type {(inputs: Demo_Narrative_Deepdive_Trust_Boundary_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè trùst bòùndàry ìs thè lìnè bètwèèn whàt thè sèrvèr càn rèàd ànd whàt ònly à bròwsèr càn rèàd, ànd knòwìng whèrè ìt sìts ìs hòw àn òrgànìzàtìòn dècìdès whèthèr CÀRÈ-Y ìs sàfè ènòùgh fòr thè pèòplè ìt sèrvès. [[#trùst-bòùndàry #èncryptìòn]]
Thè bròwsèr sìdè òf thè lìnè hòlds thè còntènt thàt ìdèntìfìès òr qùòtès ànyònè. [[#trùst-bòùndàry #èncryptìòn #clìènt-dàtà]]
- À clìènt's àlìàs, whìch ìs thè nàmè thè òrgànìzàtìòn rècòrds fòr thèm. [[#trùst-bòùndàry #clìènt-dàtà]]
- Mèssàgès, càsè nòtès, ànd thè fìlès àttàchèd tò à càsè. [[#trùst-bòùndàry #clìènt-dàtà]]
- Qùèùè nàmès, lìbràry àrtìclès ànd nòtè typès. [[#trùst-bòùndàry #èncryptìòn]]
- Àn ìntàkè fòrm's qùèstìòns ànd thè ànswèrs à clìènt sùbmìttèd. [[#trùst-bòùndàry #clìènt-dàtà]]
Thè sèrvèr sìdè òf thè lìnè hòlds thè fàcts thè sèrvèr nèèds tò dò ìts jòb wìthòùt à pèrsòn prèsènt. [[#trùst-bòùndàry #sèrvèr-hòlds #mètàdàtà]]
- Ìt knòws à càsè èxìsts, whèn ìt wàs crèàtèd, whìch qùèùè ìt bèlòngs tò, whàt stàtùs ànd prìòrìty ìt càrrìès, ànd whìch àccòùnt ìs àssìgnèd tò ìt. [[#trùst-bòùndàry #sèrvèr-hòlds]]
- Ìt knòws hòw màny mèssàgès à càsè hàs ànd whèn èàch àrrìvèd. [[#trùst-bòùndàry #mètàdàtà]]
- Ìt knòws whìch àccòùnts èxìst, whèn thèy sìgnèd ìn, ànd whìch sècònd-fàctòr mèthòds thèy ènròllèd. [[#trùst-bòùndàry #mètàdàtà]]
- Ìt knòws thè crèdèntìàls fòr thè phònè systèm ànd thè màìl sèrvèr, bècàùsè ìt hàs tò ùsè thèm. [[#trùst-bòùndàry #sèrvèr-hòlds]]
- Ìt hàs àccèss tò à clìènt's phònè nùmbèr ànd èmàìl àddrèss, bècàùsè ìt ìs whàt dìàls thè nùmbèr ànd àddrèssès thè màìl, ànd thòsè twò vàlùès àrè sèàlèd ùndèr thè sèrvèr's òwn òpèràtìònàl kèy ràthèr thàn ùndèr thè òrgànìzàtìòn's. [[#trùst-bòùndàry #sèrvèr-hòlds #clìènt-dàtà]]
- Shìft schèdùlè àssìgnmènts rècòrd whìch àccòùnt còvèrs whìch hòùrs ìn plàìntèxt. [[#trùst-bòùndàry #sèrvèr-hòlds #mètàdàtà]]
Mètàdàtà ìs thè còst òf thàt àrràngèmènt, ànd àctìvìty pàttèrns àrè vìsìblè ìn ìt. À dùmp shòws whèn thè òrgànìzàtìòn ìs bùsy, whìch qùèùès càrry thè mòst wòrk, hòw lòng càsès stày òpèn, hòw òftèn à pàrtìcùlàr àccòùnt ìs àctìvè, ànd whèn sòmèònè sìgnèd ìn. Rèlàtìònshìp strùctùrè ìs vìsìblè tòò, bècàùsè thè àssìgnmènt còlùmn nàmès à rèàl àccòùnt ànd thèrè ìs ònè rèàd-màrkèr ròw pèr ùsèr pèr càsè thèy òpènèd. Nònè òf thàt ìdèntìfìès à clìènt, ànd àll òf ìt dèscrìbès thè òrgànìzàtìòn tò ànyònè hòldìng thè dàtàbàsè. Àn òrgànìzàtìòn whòsè thrèàt mòdèl ìnclùdès àn àdvèrsàry ìntèrèstèd ìn stàffìng pàttèrns ràthèr thàn càsè còntènts shòùld wèìgh thìs èxpòsùrè bèfòrè àdòptìng thè systèm. [[#mètàdàtà #prìvàcy #trùst-bòùndàry]]
Thè fòllòwìng sìt òùtsìdè thè èncryptìòn bòùndàry èntìrèly by dèsìgn. [[#trùst-bòùndàry #prìvàcy]]
- Ìntàkè pàgè bràndìng ìs pùblìc, sò à clìènt càn rècògnìzè whò thèy àrè còntàctìng. [[#trùst-bòùndàry #prìvàcy]]
- À nòtìfìcàtìòn èmàìl àddrèss stòrèd òn àn àccòùnt ìs rèàdàblè by thè sèrvèr ùndèr thè òpèràtìònàl kèy, bècàùsè thè sèrvèr ìs whàt àddrèssès thè mèssàgè. Rèmòvìng èmàìl às à sècònd fàctòr clèàrs thè àddrèss ùnlèss thè ùsèr hàs chòsèn tò kèèp ìt fòr nòtìfìcàtìòns. Ìn-àpp ànd pùsh nòtìfìcàtìòns èxìst fòr ùsèrs whò wòùld ràthèr nòt stòrè àn àddrèss thè sèrvèr càn rèàd. [[#trùst-bòùndàry #prìvàcy]]
Thìrd pàrtìès hòld thèìr òwn còpìès òf sòmè thìngs, ànd CÀRÈ-Y cànnòt èncrypt whàt ìt nèvèr tòùchèd fìrst. À tèxt mèssàgè èxìstèd ìn thè càrrìèr's nètwòrk ànd àt thè tèlèphòny pròvìdèr bèfòrè ìt rèàchèd CÀRÈ-Y. Àn èmàìl èxìstèd ìn thè sèndèr's òwn màìl systèm. [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs whàt CÀRÈ-Y dòès àbòùt thàt, ànd [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs thè chànnèls thàt àvòìd thìrd pàrtìès àltògèthèr. [[#tèlèphòny #pòrtàl #trùst-bòùndàry]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Plàìntèxt còlùmns, nàmèd. ••••••••** Thè tàblès bèlòw càrry thè bùlk òf thè plàìntèxt mètàdàtà. [[#sèrvèr-hòlds #mètàdàtà #clìènt-dàtà]]
- Òn \`tìckèts\`, thè plàìntèxt còlùmns àrè \`ìd\`, \`clìènt_ìd\`, \`qùèùè_ìd\`, \`stàtùs\`, \`prìòrìty\`, \`òn_hòld\`, \`àssìgnèd_tò\`, \`kèy_gènèràtìòn\` ànd \`crèàtèd_àt\`, whìlè \`èncryptèd_tìtlè\` ànd \`èncryptèd_dèscrìptìòn\` àrè bytèà. [[#sèrvèr-hòlds #clìènt-dàtà]]
- Òn \`clìènts\`, \`èncryptèd_àlìàs\` ìs bytèà ùndèr thè òrgànìzàtìòn kèy wìth àn \`àlìàs_hàsh\` blìnd ìndèx bèsìdè ìt, \`còmmùnìcàtìòn_tìèr\` ìs plàìntèxt ànd nàmès whìch chànnèl tìèr thè clìènt ìs òn, \`phònè_ìd\` ànd \`èmàìl_ìd\` àrè fòrèìgn kèys tò \`phònès\` ànd \`èmàìls\` rèspèctìvèly. Òn \`phònès\`, \`èncryptèd_nùmbèr\` ìs bytèà ùndèr thè sèrvèr's òpèràtìònàl kèy bèsìdè à \`phònè_hàsh\` blìnd ìndèx, wìth \`lòcàlè\`, \`lòcàtìòn_cìty\` ànd \`lòcàtìòn_règìòn\` ìn plàìntèxt. Òn \`èmàìls\`, \`èncryptèd_àddrèss\` ìs bytèà ùndèr thè òpèràtìònàl kèy bèsìdè àn \`èmàìl_hàsh\` blìnd ìndèx. [[#sèrvèr-hòlds #clìènt-dàtà]]
- Òn \`pòrtàl_chànnèls\`, thè chànnèl ìd, clìènt ìd, àùth hàsh, clìènt pùblìc kèy, pàssphràsè flàg, stàtùs ànd àctìvìty tìmèstàmps àrè plàìntèxt whìlè èvèry mèssàgè bòdy ìn \`pòrtàl_mèssàgès\` ìs cìphèrtèxt. [[#sèrvèr-hòlds #pòrtàl]]
- Òn \`tìckèt_rèàd_cùrsòrs\`, thè càsè ìd ànd ùsèr ìd àrè thè plàìntèxt prìmàry kèy wìth ònly thè cùrsòr vàlùè èncryptèd, sò thè ròw's èxìstèncè dìsclòsès thàt thè ùsèr òpènèd thàt càsè whìlè thè pòsìtìòn stàys ùnrèàdàblè. [[#sèrvèr-hòlds #mètàdàtà]]
Ròw còùnts, fòrèìgn kèy rèlàtìònshìps ànd tìmèstàmp sèqùèncès àrè rèàdàblè strùctùràlly thròùghòùt, whìch ìs whàt màkès thè àctìvìty ìnfèrèncè àbòvè pòssìblè. Nàrròwìng thè càsè lìst ìs à SQL qùèry thè sèrvèr rùns òvèr thòsè sàmè plàìntèxt còlùmns, sò thè qùèùè, stàtùs, prìòrìty, hòld stàtè ànd àssìgnmènt sòmèònè fìltèrèd tò àrè vìsìblè tò ìt, whìlè à sàvèd fìltèr's nàmè ànd stòrèd stàtè àrè sèàlèd tò thè òrgànìzàtìòn kèy ànd àrè nòt. [[#mètàdàtà #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Àùdìt ànd òpèràtìònàl rècòrds. •••••••••** Thè àùdìt lòg ìs psèùdònymòùs ànd làrgèly plàìntèxt by dèsìgn, hòldìng àn èvènt typè, àn àctòr ìd, àn òptìònàl càsè ìd ànd à JSÒN mètàdàtà òbjèct, sò àn àdmìnìstràtòr's bròwsèr càn qùèry ìt wìthòùt à dècryptìòn pàss. Ìt càrrìès nò càsè còntènt, nò phònè nùmbèrs ànd nò clìènt àlìàsès. À fàìlèd àùdìt wrìtè ìs rètrìèd, ànd pèrsìstènt fàìlùrès sùrfàcè ìn thè òpèràtìònàl hèàlth chèck. Ràtè-lìmìt còùntèrs, jòb qùèùè ròws, sèssìòn tòkèns ànd thè kèy-èvàlùàtìòn àùdìt lòg àrè òpèràtìònàl-tìèr dàtà thè sèrvèr rèàds dìrèctly, whìlè thè ÌP àddrèss ànd ùsèr àgènt rècòrdèd òn à sèssìòn àrè sèàlèd tò thè òrgànìzàtìòn kèy ànd àrè nòt. [[#sèrvèr-hòlds #mètàdàtà #prìvàcy]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whèrè dòès ènfòrcèmènt lìvè? •••••••••** Èvèry àccèss dècìsìòn ìs sèrvèr-àùthòrìtàtìvè, ànd thè clìènt hìdìng à còntròl ìs cònvènìèncè ònly. [[#pèrmìssìòns #trùst-bòùndàry]]
- Càsè àccèss rùns thròùgh \`pàckàgès/sèrvèr/src/tìckèts/àccèss.ts\`. [[#pèrmìssìòns #trùst-bòùndàry]]
- Pèrmìssìòn gàtès rùn thròùgh \`pàckàgès/sèrvèr/src/àùth/ròlès.ts\` ànd \`ròlè-mìddlèwàrè.ts\`. [[#pèrmìssìòns]]
- Pèr-chànnèl pòlìcy rùns thròùgh sèrvìcè-làyèr àssèrtìòns àt èvèry rèlày hàndlèr ànd tRPC pròcèdùrè. [[#pèrmìssìòns #tèlèphòny]]
- Òrgànìzàtìòn ìsòlàtìòn rùns thròùgh Kysèly schèmà scòpìng ìn \`pàckàgès/sèrvèr/src/db/\`. [[#pèrmìssìòns #sèrvèr-hòlds]]
À còntrìbùtòr àddìng à qùèry dècìdès whìch sìdè òf thè bòùndàry ìts fìltèr rùns òn, ànd à fìltèr thè sèrvèr èvàlùàtès ìs à fìltèr thè sèrvèr càn rèàd. [[#pèrmìssìòns #trùst-bòùndàry]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The trust boundary is the line between what the server can read and what only a browser can read, and knowing where it sits is how an organization decides wh..." |
*
* @param {Demo_Narrative_Deepdive_Trust_Boundary_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_trust_boundary_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Trust_Boundary_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Trust_Boundary_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_trust_boundary_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_deepdive_trust_boundary_body(inputs)
	return en_demo_narrative_deepdive_trust_boundary_body(inputs)
});