/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Library_Attachments_BodyInputs */

const en_demo_narrative_library_attachments_body = /** @type {(inputs: Demo_Narrative_Library_Attachments_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Articles accept file attachments that the browser encrypts with the organization key before upload. Accepted types are images (JPEG, PNG, GIF, WebP), PDFs and Word documents, each up to ten megabytes. Uploading requires the Edit knowledge base permission; downloading requires the View knowledge base permission. [[#encryption #permissions]]
**What does the server hold for each file?** The file bytes and the filename are each sealed as organization-key ciphertext and stored separately. The declared content type, the byte count, the upload timestamp and a storage key remain in plaintext. A seized database reveals how many files an article carries, each file's approximate kind and size, but no filename and nothing from inside the file. [The trust boundary](#deep-dive/the-trust-boundary) covers the plaintext columns across the schema. [[#server-holds #metadata]]
**What can the server check?** The server validates the declared content type against its allowlist, the byte count against its ten-megabyte limit, and that the declared size matches the bytes received. It cannot inspect the file itself, because what arrives is ciphertext with no file signature. A file whose declared type passes the allowlist but does not match its actual content becomes an image the reader's browser cannot render. The server accepts at most five uploads per minute per account. [Article editor](#library/editor) covers the consequences when a first save exceeds that limit. The attachment list shows at most fifty files per article, oldest first; the fifty-first and later uploads do not appear. [[#failure-states]]
**Downloads.** The server responds with raw bytes, sets \`Cache-Control: private, no-store\`, and decrypts nothing. The browser decrypts the file on the device; the plaintext never leaves that device. [The permission system](#deep-dive/the-permission-system) covers where the download permission comes from. [[#encryption]]
**The upload route and the attachment service.** \`uploadAttachment\` in \`packages/server/src/routes/kb.ts\` writes through \`BlobStore\` under the \`kb-attachment\` category and records the row via \`packages/server/src/kb/kb-media-service.ts\`. When the row insert fails, the route deletes the blob it wrote. Downloads run through \`createBlobDownloadHandler\` in \`packages/server/src/routes/blob-download.ts\`. The list query applies a cap of fifty with no paging cursor. [[#client-data]]`)
};

const es_demo_narrative_library_attachments_body = /** @type {(inputs: Demo_Narrative_Library_Attachments_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Los artículos aceptan archivos adjuntos que el navegador cifra con la clave de la organización antes de subirlos. Los tipos aceptados son imágenes (JPEG, PNG, GIF, WebP), PDF y documentos de Word, cada uno de hasta diez megabytes. Subir requiere el permiso Editar base de conocimiento; descargar requiere el permiso Ver base de conocimiento. [[#encryption #permissions]]
**¿Qué guarda el servidor de cada archivo?** Los bytes del archivo y el nombre se sellan por separado como texto cifrado con la clave de organización. Permanecen en texto plano el tipo de contenido declarado, el conteo de bytes, la marca de tiempo de subida y una clave de almacenamiento. Una base de datos incautada revela cuántos archivos lleva un artículo y el tipo y tamaño aproximado de cada uno, pero ningún nombre de archivo ni nada de su contenido. [La frontera de confianza](#deep-dive/the-trust-boundary) trata las columnas en texto plano de todo el esquema. [[#server-holds #metadata]]
**¿Qué puede comprobar el servidor?** El servidor valida el tipo de contenido declarado contra su lista de tipos permitidos, el conteo de bytes contra su límite de diez megabytes, y que el tamaño declarado coincida con los bytes recibidos. No puede inspeccionar el archivo en sí, porque lo que llega es texto cifrado sin firma de formato. Un archivo cuyo tipo declarado pasa la lista pero no coincide con su contenido real se convierte en una imagen que el navegador de quien lee no logra representar. El servidor acepta como máximo cinco subidas por minuto por cuenta. [Editor de artículos](#library/editor) trata las consecuencias cuando un primer guardado supera ese límite. La lista de adjuntos muestra como máximo cincuenta archivos por artículo, del más antiguo al más reciente; la subida número cincuenta y uno en adelante no aparece. [[#failure-states]]
**Descargas.** El servidor responde con bytes crudos, establece \`Cache-Control: private, no-store\` y no descifra nada. El navegador descifra el archivo en el dispositivo; el texto en claro nunca sale de ese dispositivo. [El sistema de permisos](#deep-dive/the-permission-system) trata de dónde sale el permiso de descarga. [[#encryption]]
**La ruta de subida y el servicio de adjuntos.** \`uploadAttachment\`, en \`packages/server/src/routes/kb.ts\`, escribe a través de \`BlobStore\` bajo la categoría \`kb-attachment\` y registra la fila mediante \`packages/server/src/kb/kb-media-service.ts\`. Cuando la inserción de fila falla, la ruta borra el blob que escribió. Las descargas pasan por \`createBlobDownloadHandler\`, en \`packages/server/src/routes/blob-download.ts\`. La consulta aplica un tope de cincuenta sin cursor de paginación. [[#client-data]]`)
};

const en_xa2_demo_narrative_library_attachments_body = /** @type {(inputs: Demo_Narrative_Library_Attachments_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Àrtìclès àccèpt fìlè àttàchmènts thàt thè bròwsèr èncrypts wìth thè òrgànìzàtìòn kèy bèfòrè ùplòàd. Àccèptèd typès àrè ìmàgès (JPÈG, PNG, GÌF, WèbP), PDFs ànd Wòrd dòcùmènts, èàch ùp tò tèn mègàbytès. Ùplòàdìng rèqùìrès thè Èdìt knòwlèdgè bàsè pèrmìssìòn; dòwnlòàdìng rèqùìrès thè Vìèw knòwlèdgè bàsè pèrmìssìòn. [[#èncryptìòn #pèrmìssìòns]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr hòld fòr èàch fìlè? ••••••••••••** Thè fìlè bytès ànd thè fìlènàmè àrè èàch sèàlèd às òrgànìzàtìòn-kèy cìphèrtèxt ànd stòrèd sèpàràtèly. Thè dèclàrèd còntènt typè, thè bytè còùnt, thè ùplòàd tìmèstàmp ànd à stòràgè kèy rèmàìn ìn plàìntèxt. À sèìzèd dàtàbàsè rèvèàls hòw màny fìlès àn àrtìclè càrrìès, èàch fìlè's àppròxìmàtè kìnd ànd sìzè, bùt nò fìlènàmè ànd nòthìng fròm ìnsìdè thè fìlè. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs thè plàìntèxt còlùmns àcròss thè schèmà. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt càn thè sèrvèr chèck? ••••••••** Thè sèrvèr vàlìdàtès thè dèclàrèd còntènt typè àgàìnst ìts àllòwlìst, thè bytè còùnt àgàìnst ìts tèn-mègàbytè lìmìt, ànd thàt thè dèclàrèd sìzè màtchès thè bytès rècèìvèd. Ìt cànnòt ìnspèct thè fìlè ìtsèlf, bècàùsè whàt àrrìvès ìs cìphèrtèxt wìth nò fìlè sìgnàtùrè. À fìlè whòsè dèclàrèd typè pàssès thè àllòwlìst bùt dòès nòt màtch ìts àctùàl còntènt bècòmès àn ìmàgè thè rèàdèr's bròwsèr cànnòt rèndèr. Thè sèrvèr àccèpts àt mòst fìvè ùplòàds pèr mìnùtè pèr àccòùnt. [Àrtìclè èdìtòr](#lìbràry/èdìtòr) còvèrs thè cònsèqùèncès whèn à fìrst sàvè èxcèèds thàt lìmìt. Thè àttàchmènt lìst shòws àt mòst fìfty fìlès pèr àrtìclè, òldèst fìrst; thè fìfty-fìrst ànd làtèr ùplòàds dò nòt àppèàr. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dòwnlòàds. •••** Thè sèrvèr rèspònds wìth ràw bytès, sèts \`Càchè-Còntròl: prìvàtè, nò-stòrè\`, ànd dècrypts nòthìng. Thè bròwsèr dècrypts thè fìlè òn thè dèvìcè; thè plàìntèxt nèvèr lèàvès thàt dèvìcè. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs whèrè thè dòwnlòàd pèrmìssìòn còmès fròm. [[#èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè ùplòàd ròùtè ànd thè àttàchmènt sèrvìcè. ••••••••••••••** \`ùplòàdÀttàchmènt\` ìn \`pàckàgès/sèrvèr/src/ròùtès/kb.ts\` wrìtès thròùgh \`BlòbStòrè\` ùndèr thè \`kb-àttàchmènt\` càtègòry ànd rècòrds thè ròw vìà \`pàckàgès/sèrvèr/src/kb/kb-mèdìà-sèrvìcè.ts\`. Whèn thè ròw ìnsèrt fàìls, thè ròùtè dèlètès thè blòb ìt wròtè. Dòwnlòàds rùn thròùgh \`crèàtèBlòbDòwnlòàdHàndlèr\` ìn \`pàckàgès/sèrvèr/src/ròùtès/blòb-dòwnlòàd.ts\`. Thè lìst qùèry àpplìès à càp òf fìfty wìth nò pàgìng cùrsòr. [[#clìènt-dàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Articles accept file attachments that the browser encrypts with the organization key before upload. Accepted types are images (JPEG, PNG, GIF, WebP), PDFs an..." |
*
* @param {Demo_Narrative_Library_Attachments_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_library_attachments_body = /** @type {((inputs?: Demo_Narrative_Library_Attachments_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Library_Attachments_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_library_attachments_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_library_attachments_body(inputs)
	return en_demo_narrative_library_attachments_body(inputs)
});