/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Notes_BodyInputs */

const en_demo_narrative_topic_notes_body = /** @type {(inputs: Demo_Narrative_Topic_Notes_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`An internal note records what the organization wants to remember about a ticket. Nothing from a note reaches the client. The note is encrypted with the ticket key, the same key that protects the messages around it. [[#client-data #encryption]]
**What does the server hold?** The note's content is ciphertext. The note's type, author, creation time, mentioned accounts, and private flag are stored in plaintext. A database dump shows that a user wrote a note of a given type on a ticket at a given hour and mentioned two people in it, but nothing of what the note says. [The trust boundary](#deep-dive/the-trust-boundary) lists those columns beside the rest of the schema. [[#server-holds #metadata]]
**Note types and visibility.** Each note carries a type. A type carries a minimum role for writing and a minimum role for seeing. The server removes the notes that the requesting user's role cannot see before building the response. A note below the user's threshold never leaves the server. An author always sees their own. A type's name, icon, and description are encrypted with the organization key, and the roles it restricts on are plaintext. The server enforces the rule without reading the type's name. [Note types](#admin-org/note-types) covers creating and editing them. [[#permissions #privacy #encryption]]
**Escalation targets.** A type can name who to notify when someone writes a note of that type. Those targets are encrypted with the server's operational key, not the organization key, because the server sends the notification without anyone signed in. Mentioning a user in a note pings them once rather than subscribing them to the ticket. [[#trust-boundary #server-holds]]
**Reactions, edits, and deletions.** The reactions are acknowledge, approve, disagree, flag, and complete. Each reaction is a plaintext row naming the account, the note, and the time. The user can edit their own notes and delete their own. An administrator can delete another user's note but cannot edit it. Deleting a note overwrites the content and keeps the row as a tombstone. [[#permissions #retention #metadata]]
**The compose surface and role filter.** The compose surface is \`InternalNoteSheet.svelte\`. The role filter is in \`listFollowUps\` in \`packages/server/src/tickets/followup-service.ts\`. Types come from \`058_create_note_types.ts\` with role columns from \`062_add_note_type_role_gating.ts\`. Reactions are \`063_create_followup_reactions.ts\`, and mention validation is \`packages/server/src/tickets/mentions.ts\`. [[#client-data]]`)
};

const es_demo_narrative_topic_notes_body = /** @type {(inputs: Demo_Narrative_Topic_Notes_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Una nota interna registra lo que la organización quiere recordar sobre un ticket. Nada de una nota llega al cliente. La nota se cifra con la clave del ticket, la misma clave que protege los mensajes que la rodean. [[#client-data #encryption]]
**¿Qué guarda el servidor?** El contenido de la nota es texto cifrado. El tipo de la nota, su autoría, su fecha de creación, las cuentas mencionadas en ella y la marca de privada se almacenan en texto plano. Un volcado de la base de datos muestra que una persona escribió una nota de cierto tipo en un ticket a cierta hora y mencionó en ella a dos personas, pero nada de lo que dice la nota. [La frontera de confianza](#deep-dive/the-trust-boundary) enumera esas columnas junto al resto del esquema. [[#server-holds #metadata]]
**Tipos de nota y visibilidad.** Cada nota lleva un tipo. Un tipo lleva un rol mínimo para escribirla y un rol mínimo para verla. El servidor elimina las notas que el rol de quien consulta no puede ver antes de armar la respuesta. Una nota por debajo del umbral de la persona usuaria nunca sale del servidor. Quien la escribió siempre ve las suyas. El nombre, el icono y la descripción de un tipo se cifran con la clave de la organización, y los roles con los que restringe están en texto plano. El servidor aplica la regla sin leer el nombre del tipo. [Tipos de nota](#admin-org/note-types) trata cómo se crean y se editan. [[#permissions #privacy #encryption]]
**Destinos de escalación.** Un tipo puede nombrar a quién avisar cuando alguien escribe una nota de ese tipo. Esos destinos se cifran con la clave operativa del servidor, no con la de la organización, porque el servidor envía el aviso sin nadie con la sesión iniciada. Mencionar a una persona en una nota la avisa una vez; no la suscribe al ticket. [[#trust-boundary #server-holds]]
**Reacciones, ediciones y borrados.** Las reacciones son reconocer, aprobar, en desacuerdo, marcar y completar. Cada reacción es una fila en texto plano que nombra la cuenta, la nota y la fecha. La persona usuaria puede editar sus propias notas y borrar las suyas. Una persona administradora puede borrar la nota de otra persona, pero no puede editarla. Borrar una nota sobreescribe el contenido y conserva la fila como lápida. [[#permissions #retention #metadata]]
**La superficie de composición y el filtro por rol.** La superficie de composición es \`InternalNoteSheet.svelte\`. El filtro por rol está en \`listFollowUps\`, en \`packages/server/src/tickets/followup-service.ts\`. Los tipos vienen de \`058_create_note_types.ts\` con las columnas de rol de \`062_add_note_type_role_gating.ts\`. Las reacciones son \`063_create_followup_reactions.ts\`, y la validación de menciones es \`packages/server/src/tickets/mentions.ts\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_notes_body = /** @type {(inputs: Demo_Narrative_Topic_Notes_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Àn ìntèrnàl nòtè rècòrds whàt thè òrgànìzàtìòn wànts tò rèmèmbèr àbòùt à tìckèt. Nòthìng fròm à nòtè rèàchès thè clìènt. Thè nòtè ìs èncryptèd wìth thè tìckèt kèy, thè sàmè kèy thàt pròtècts thè mèssàgès àròùnd ìt. [[#clìènt-dàtà #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr hòld? ••••••••** Thè nòtè's còntènt ìs cìphèrtèxt. Thè nòtè's typè, àùthòr, crèàtìòn tìmè, mèntìònèd àccòùnts, ànd prìvàtè flàg àrè stòrèd ìn plàìntèxt. À dàtàbàsè dùmp shòws thàt à ùsèr wròtè à nòtè òf à gìvèn typè òn à tìckèt àt à gìvèn hòùr ànd mèntìònèd twò pèòplè ìn ìt, bùt nòthìng òf whàt thè nòtè sàys. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) lìsts thòsè còlùmns bèsìdè thè rèst òf thè schèmà. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Nòtè typès ànd vìsìbìlìty. ••••••••** Èàch nòtè càrrìès à typè. À typè càrrìès à mìnìmùm ròlè fòr wrìtìng ànd à mìnìmùm ròlè fòr sèèìng. Thè sèrvèr rèmòvès thè nòtès thàt thè rèqùèstìng ùsèr's ròlè cànnòt sèè bèfòrè bùìldìng thè rèspònsè. À nòtè bèlòw thè ùsèr's thrèshòld nèvèr lèàvès thè sèrvèr. Àn àùthòr àlwàys sèès thèìr òwn. À typè's nàmè, ìcòn, ànd dèscrìptìòn àrè èncryptèd wìth thè òrgànìzàtìòn kèy, ànd thè ròlès ìt rèstrìcts òn àrè plàìntèxt. Thè sèrvèr ènfòrcès thè rùlè wìthòùt rèàdìng thè typè's nàmè. [Nòtè typès](#àdmìn-òrg/nòtè-typès) còvèrs crèàtìng ànd èdìtìng thèm. [[#pèrmìssìòns #prìvàcy #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èscàlàtìòn tàrgèts. ••••••** À typè càn nàmè whò tò nòtìfy whèn sòmèònè wrìtès à nòtè òf thàt typè. Thòsè tàrgèts àrè èncryptèd wìth thè sèrvèr's òpèràtìònàl kèy, nòt thè òrgànìzàtìòn kèy, bècàùsè thè sèrvèr sènds thè nòtìfìcàtìòn wìthòùt ànyònè sìgnèd ìn. Mèntìònìng à ùsèr ìn à nòtè pìngs thèm òncè ràthèr thàn sùbscrìbìng thèm tò thè tìckèt. [[#trùst-bòùndàry #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rèàctìòns, èdìts, ànd dèlètìòns. ••••••••••** Thè rèàctìòns àrè àcknòwlèdgè, àppròvè, dìsàgrèè, flàg, ànd còmplètè. Èàch rèàctìòn ìs à plàìntèxt ròw nàmìng thè àccòùnt, thè nòtè, ànd thè tìmè. Thè ùsèr càn èdìt thèìr òwn nòtès ànd dèlètè thèìr òwn. Àn àdmìnìstràtòr càn dèlètè ànòthèr ùsèr's nòtè bùt cànnòt èdìt ìt. Dèlètìng à nòtè òvèrwrìtès thè còntènt ànd kèèps thè ròw às à tòmbstònè. [[#pèrmìssìòns #rètèntìòn #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còmpòsè sùrfàcè ànd ròlè fìltèr. •••••••••••** Thè còmpòsè sùrfàcè ìs \`ÌntèrnàlNòtèShèèt.svèltè\`. Thè ròlè fìltèr ìs ìn \`lìstFòllòwÙps\` ìn \`pàckàgès/sèrvèr/src/tìckèts/fòllòwùp-sèrvìcè.ts\`. Typès còmè fròm \`058_crèàtè_nòtè_typès.ts\` wìth ròlè còlùmns fròm \`062_àdd_nòtè_typè_ròlè_gàtìng.ts\`. Rèàctìòns àrè \`063_crèàtè_fòllòwùp_rèàctìòns.ts\`, ànd mèntìòn vàlìdàtìòn ìs \`pàckàgès/sèrvèr/src/tìckèts/mèntìòns.ts\`. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "An internal note records what the organization wants to remember about a ticket. Nothing from a note reaches the client. The note is encrypted with the ticke..." |
*
* @param {Demo_Narrative_Topic_Notes_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_notes_body = /** @type {((inputs?: Demo_Narrative_Topic_Notes_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Notes_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_notes_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_notes_body(inputs)
	return en_demo_narrative_topic_notes_body(inputs)
});