/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Intake_Forms_BodyInputs */

const en_demo_narrative_admin_intake_forms_body = /** @type {(inputs: Demo_Narrative_Admin_Intake_Forms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The intake forms list holds every form an organization has built, and one switch beside it takes web intake off for the whole organization at once. [[#portal]]
**Saving a form does not publish it.** A form is created unpublished and stays unreachable until it is activated, activation is its own operation rather than a side effect of saving, and editing a live form therefore cannot take it off the public site by accident. Deactivating stops new submissions and leaves the form and every answer already given to it in place. [The form builder](#admin-forms/builder) covers what a save writes. [[#failure-states #portal]]
**What answers the public address when nothing is published.** With web intake on and no active form of the organization's own marked as the default, a built-in form of two fields, a name and a message, stands in so the public address always answers, in whichever of the two languages the visitor's browser asks for. That stand-in is switched off on its own, separately from the organization-wide switch. [The public intake form](#client-intake/form) covers what a visitor is asked for. [[#portal #client-data]]
**What the list row discloses and what it does not.** A form's internal name, its public slug, whether it is active, whether it is the default and which queue it feeds are plaintext columns. Everything a visitor reads, meaning the field labels, the field configuration and the form's own description and messages, is encrypted. A database dump therefore shows how many forms an organization runs, what it calls them internally, which public addresses they answer on and how many fields each one holds, and none of the wording of any question. [The trust boundary](#deep-dive/the-trust-boundary) covers the rest of that picture. [[#server-holds #metadata]]
**The key that opens a definition is not the key that opens an answer.** Form definitions are encrypted under a key anyone can derive from the organization's public key, which is what lets an anonymous visitor's browser render a form without an account while the stored bytes stay opaque. Answers are encrypted to a key that exists per case and is wrapped to individual accounts, so building and publishing a form gives no access to what anyone submitted through it. [Form responses](#admin-responses/responses) covers reading the answers. [[#encryption #keys]]
**Duplicating and deleting.** Duplicating loads a form, mints fresh field and option keys, suffixes the name and clears the slug, so the copy cannot collide with the original on a public address and shares none of its key material. Deleting is refused once any response exists, so the record a form produced cannot be removed by removing the form. [[#failure-states #encryption]]
**Two permissions that do not imply each other.** Manage intake forms is a Manager default and View intake responses is an Admin default, and neither carries the other, so an account that builds and publishes a form reads nothing submitted to it unless the organization grants the second permission too. [The permission system](#deep-dive/the-permission-system) covers moving either one. [[#permissions]]
**The forms table and the audit trail.** \`packages/server/src/portal/intake-form-service.ts\` holds the whole-form save, the slug uniqueness check, the atomic default swap and the single writer of the active flag, and \`packages/server/src/routes/intake-forms.ts\` gates every procedure on one of the two permissions. Saving, deleting and both of the switches write audit entries; activating and deactivating a form currently writes none. [[#server-holds #failure-states]]`)
};

const es_demo_narrative_admin_intake_forms_body = /** @type {(inputs: Demo_Narrative_Admin_Intake_Forms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La lista de formularios de admisión contiene todos los formularios que ha construido una organización, y un interruptor a su lado desactiva la admisión web de toda la organización de una vez. [[#portal]]
**Guardar un formulario no lo publica.** Un formulario se crea sin publicar y no es accesible hasta que se activa, la activación es una operación propia y no un efecto secundario de guardar, y por eso editar un formulario en uso no puede retirarlo del sitio público por descuido. Desactivarlo detiene los envíos nuevos y deja en su sitio el formulario y todas las respuestas que ya recibió. [El constructor de formularios](#admin-forms/builder) trata lo que escribe un guardado. [[#failure-states #portal]]
**Qué responde en la dirección pública cuando no hay nada publicado.** Con la admisión web activada y sin ningún formulario propio activo marcado como predeterminado, un formulario integrado de dos campos, un nombre y un mensaje, hace de suplente para que la dirección pública responda siempre, en el idioma que pida el navegador del visitante de los dos disponibles. Ese suplente se desactiva por su cuenta, aparte del interruptor de toda la organización. [El formulario público de admisión](#client-intake/form) trata lo que se le pide a un visitante. [[#portal #client-data]]
**Qué revela la fila de la lista y qué no.** El nombre interno de un formulario, su identificador público, si está activo, si es el predeterminado y a qué cola alimenta son columnas en texto plano. Todo lo que lee un visitante, es decir las etiquetas de los campos, su configuración y la descripción y los mensajes del propio formulario, va cifrado. Un volcado de la base de datos muestra entonces cuántos formularios tiene una organización, cómo los llama internamente, en qué direcciones públicas responden y cuántos campos tiene cada uno, y ninguna palabra de ninguna pregunta. [La frontera de confianza](#deep-dive/the-trust-boundary) trata el resto de ese panorama. [[#server-holds #metadata]]
**La clave que abre una definición no es la clave que abre una respuesta.** Las definiciones de formulario se cifran con una clave que cualquiera puede derivar de la clave pública de la organización, que es lo que permite que el navegador de un visitante anónimo dibuje un formulario sin cuenta mientras los bytes almacenados siguen siendo opacos. Las respuestas se cifran con una clave que existe por caso y se envuelve para cuentas concretas, así que construir y publicar un formulario no da ningún acceso a lo que alguien envió por él. [Respuestas de formularios](#admin-responses/responses) trata la lectura de las respuestas. [[#encryption #keys]]
**Duplicar y borrar.** Duplicar carga un formulario, acuña claves nuevas de campo y de opción, añade un sufijo al nombre y vacía el identificador público, de modo que la copia no puede chocar con el original en una dirección pública ni comparte su material de claves. Borrar se rechaza en cuanto existe una respuesta, así que el registro que produjo un formulario no se puede eliminar eliminando el formulario. [[#failure-states #encryption]]
**Dos permisos que no se implican.** Gestionar formularios de admisión corresponde por defecto al nivel de gestión y ver respuestas de admisión corresponde por defecto a Admin, y ninguno arrastra al otro, así que una cuenta que construye y publica un formulario no lee nada de lo enviado a él salvo que la organización conceda también el segundo permiso. [El sistema de permisos](#deep-dive/the-permission-system) trata cómo se traslada cualquiera de los dos. [[#permissions]]
**La tabla de formularios y el rastro de auditoría.** \`packages/server/src/portal/intake-form-service.ts\` contiene el guardado del formulario completo, la comprobación de unicidad del identificador, el cambio atómico de predeterminado y el único sitio que escribe la marca de activo, y \`packages/server/src/routes/intake-forms.ts\` protege cada procedimiento con uno de los dos permisos. Guardar, borrar y los dos interruptores escriben entradas de auditoría; activar y desactivar un formulario hoy no escribe ninguna. [[#server-holds #failure-states]]`)
};

const en_xa2_demo_narrative_admin_intake_forms_body = /** @type {(inputs: Demo_Narrative_Admin_Intake_Forms_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè ìntàkè fòrms sèctìòn lìsts èvèry fòrm thè òrgànìzàtìòn hàs crèàtèd. Wèb ìntàkè càn bè swìtchèd òn òr òff fòr thè whòlè òrgànìzàtìòn, ànd whèn ìt ìs òn ànd nò cùstòm fòrm ìs màrkèd às dèfàùlt, à dèfàùlt fòrm àppèàrs sò ìntàkè àlwàys hàs sòmèthìng tò sèrvè.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pèrmìssìòns. ••••** Thè Mànàgè ìntàkè fòrms pèrmìssìòn ìs à mànàgèr dèfàùlt, ànd thè Vìèw ìntàkè rèspònsès pèrmìssìòn ìs àn àdmìnìstràtòr dèfàùlt. Thè twò àrè ìndèpèndènt ànd èìthèr càn bè gràntèd tò thè òthèr ròlè, sò à ùsèr whò bùìlds ànd pùblìshès à fòrm cànnòt rèàd àny rèspònsès tò ìt ùnlèss thè òrgànìzàtìòn àlsò grànts thè Vìèw ìntàkè rèspònsès pèrmìssìòn.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èncryptìòn. ••••** Fòrm dèfìnìtìòns àrè èncryptèd ùndèr à kèy dèrìvèd fròm thè òrgànìzàtìòn's pùblìc kèy, sò thè ìntàkè pàgè rèàds à fòrm wìthòùt àn àccòùnt whìlè à dàtàbàsè dùmp stàys òpàqùè. Dùplìcàtè pròdùcès à nèw èncryptèd còpy wìth frèsh fìèld kèys ànd à clèàrèd slùg sò thè còpy cànnòt còllìdè òn à pùblìc ÙRL.
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Lìfècyclè. •••** Crèàtìng à fòrm dòès nòt pùblìsh ìt. À crèàtèd fòrm stàys ùnrèàchàblè ùntìl ìt ìs àctìvàtèd, ànd dèàctìvàtìng ìt làtèr stòps sùbmìssìòns wìthòùt dèlètìng thè fòrm òr ìts rèspònsès. •••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The intake forms list holds every form an organization has built, and one switch beside it takes web intake off for the whole organization at once. [[#portal..." |
*
* @param {Demo_Narrative_Admin_Intake_Forms_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_intake_forms_body = /** @type {((inputs?: Demo_Narrative_Admin_Intake_Forms_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Intake_Forms_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_intake_forms_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_intake_forms_body(inputs)
	return en_demo_narrative_admin_intake_forms_body(inputs)
});