/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Note_Types_BodyInputs */

const en_demo_narrative_admin_note_types_body = /** @type {(inputs: Demo_Narrative_Admin_Note_Types_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Each organization defines the categories that internal notes can carry, and each type has a name, an icon, and an optional description. The product also lists system types for events it records on its own, such as a status change, a call, or an assignment change. [[#client-data]]
**Per-type settings.** Each configurable type carries a notification switch for administrators, one for managers, and one for all accounts with ticket access. A switch can mark a note of that type as required before closing the ticket. Each type also sets a minimum role for reading notes filed under it and a minimum role for writing one, and the server enforces both. A type restricted to managers or administrators cannot be read or written by a lower role even through a direct request. [Internal notes](#ticket-detail/notes) covers how the user writes one. [[#permissions]]
**Starting types.** Comment, Resolution, Safety Concern, and Request ship as configurable types, not protected ones, so an organization can rename, reconfigure, or retire any of them. Comment is the default type for a new note. Resolution is marked as required before closing. Safety Concern and Request escalate to administrators and managers in addition to accounts with ticket access. Comment and Resolution notify only accounts with ticket access. [[#client-data]]
**What does the server store about a type?** The name, icon, and description are sealed with the organization key. The server holds the resulting bytes and has no key to open them. The notification targets are encrypted with the server's operational key and decrypted when a notification fires, because routing the notification is the server's job. The server can identify that a given category escalates without knowing that category's name. The minimum-role thresholds, the required-on-close flag, and the active flag are plaintext columns. A database dump reveals how many categories an organization runs, how each one gates access, and which ones escalate, without any of their names. [The trust boundary](#deep-dive/the-trust-boundary) covers what else a dump yields. [[#server-holds #encryption #metadata]]
**Deactivation.** Deactivating a type preserves every note already filed under it, and those notes remain filterable by category. The type set as the organization's default cannot be deactivated, which keeps at least one category available for writing. [[#failure-states]]
**Who can configure note types?** Configuring note types requires the Manage note types permission, which sits with Admin by default. [[#permissions]]
**The service and its two encryption layers.** \`packages/server/src/tickets/note-type-service.ts\` seals names and icons with the organization public key and encrypts notification targets with the operational secrets key. \`DEFAULT_NOTE_TYPES\` in the same file defines the starting types. The table comes from \`058_create_note_types.ts\`, with the description column added in \`061\` and the two role-threshold columns in \`062\`. The default-type pointer is \`org_config.default_note_type_id\` from \`060\`. [[#server-holds #client-data]]`)
};

const es_demo_narrative_admin_note_types_body = /** @type {(inputs: Demo_Narrative_Admin_Note_Types_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Cada organización define las categorías que pueden llevar las notas internas, y cada tipo tiene un nombre, un icono y una descripción opcional. El producto también lista tipos de sistema para eventos que registra por su cuenta, como un cambio de estado, una llamada o un cambio de asignación. [[#client-data]]
**Ajustes por tipo.** Cada tipo configurable lleva un interruptor de notificación para administradores, otro para gestores y otro para todas las cuentas con acceso al ticket. Un interruptor puede marcar una nota de ese tipo como obligatoria antes de cerrar el ticket. Cada tipo también fija un rol mínimo para leer las notas archivadas bajo él y un rol mínimo para escribir una, y el servidor aplica ambos. Un tipo restringido a gestores o administradores no se puede leer ni escribir desde un rol inferior ni siquiera mediante una solicitud directa. [Notas internas](#ticket-detail/notes) trata cómo la persona usuaria escribe una nota. [[#permissions]]
**Tipos iniciales.** Comentario, Resolución, Preocupación de seguridad y Petición se entregan como tipos configurables, no protegidos, de modo que una organización puede renombrar, reconfigurar o retirar cualquiera de ellos. Comentario es el tipo predeterminado para una nota nueva. Resolución está marcado como obligatorio antes de cerrar. Preocupación de seguridad y Petición escalan a administradores y gestores además de a las cuentas con acceso al ticket. Comentario y Resolución notifican solo a las cuentas con acceso. [[#client-data]]
**¿Qué almacena el servidor de un tipo?** El nombre, el icono y la descripción van sellados con la clave de la organización. El servidor conserva los bytes resultantes y no tiene clave para abrirlos. Los destinatarios de las notificaciones se cifran con la clave operativa del servidor y se descifran cuando se dispara una notificación, porque encaminar la notificación es tarea del servidor. El servidor puede identificar que una categoría dada escala sin conocer el nombre de esa categoría. Los umbrales de rol mínimo, la marca de obligatoria al cerrar y la marca de activo son columnas en texto plano. Un volcado de la base de datos revela cuántas categorías tiene una organización, cómo cada una restringe el acceso y cuáles escalan, sin ninguno de sus nombres. [La frontera de confianza](#deep-dive/the-trust-boundary) trata lo demás que revela un volcado. [[#server-holds #encryption #metadata]]
**Desactivación.** Desactivar un tipo preserva todas las notas ya archivadas bajo él, y esas notas se pueden seguir filtrando por categoría. El tipo puesto como predeterminado de la organización no se puede desactivar, lo que mantiene al menos una categoría disponible para escribir. [[#failure-states]]
**¿Quién puede configurar los tipos de nota?** Configurar los tipos de nota requiere el permiso Gestionar tipos de notas, que corresponde a Admin de forma predeterminada. [[#permissions]]
**El servicio y sus dos capas de cifrado.** \`packages/server/src/tickets/note-type-service.ts\` sella nombres e iconos con la clave pública de la organización y cifra los destinatarios de notificación con la clave de secretos operativos. \`DEFAULT_NOTE_TYPES\` en el mismo archivo define los tipos iniciales. La tabla proviene de \`058_create_note_types.ts\`, con la columna de descripción añadida en \`061\` y las dos columnas de umbral de rol en \`062\`. El puntero al tipo predeterminado es \`org_config.default_note_type_id\`, de \`060\`. [[#server-holds #client-data]]`)
};

const en_xa2_demo_narrative_admin_note_types_body = /** @type {(inputs: Demo_Narrative_Admin_Note_Types_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Èàch òrgànìzàtìòn dèfìnès thè càtègòrìès thàt ìntèrnàl nòtès càn càrry, ànd èàch typè hàs à nàmè, àn ìcòn, ànd àn òptìònàl dèscrìptìòn. Thè pròdùct àlsò lìsts systèm typès fòr èvènts ìt rècòrds òn ìts òwn, sùch às à stàtùs chàngè, à càll, òr àn àssìgnmènt chàngè. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Pèr-typè sèttìngs. ••••••** Èàch cònfìgùràblè typè càrrìès à nòtìfìcàtìòn swìtch fòr àdmìnìstràtòrs, ònè fòr mànàgèrs, ànd ònè fòr àll àccòùnts wìth tìckèt àccèss. À swìtch càn màrk à nòtè òf thàt typè às rèqùìrèd bèfòrè clòsìng thè tìckèt. Èàch typè àlsò sèts à mìnìmùm ròlè fòr rèàdìng nòtès fìlèd ùndèr ìt ànd à mìnìmùm ròlè fòr wrìtìng ònè, ànd thè sèrvèr ènfòrcès bòth. À typè rèstrìctèd tò mànàgèrs òr àdmìnìstràtòrs cànnòt bè rèàd òr wrìttèn by à lòwèr ròlè èvèn thròùgh à dìrèct rèqùèst. [Ìntèrnàl nòtès](#tìckèt-dètàìl/nòtès) còvèrs hòw thè ùsèr wrìtès ònè. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Stàrtìng typès. •••••** Còmmènt, Rèsòlùtìòn, Sàfèty Còncèrn, ànd Rèqùèst shìp às cònfìgùràblè typès, nòt pròtèctèd ònès, sò àn òrgànìzàtìòn càn rènàmè, rècònfìgùrè, òr rètìrè àny òf thèm. Còmmènt ìs thè dèfàùlt typè fòr à nèw nòtè. Rèsòlùtìòn ìs màrkèd às rèqùìrèd bèfòrè clòsìng. Sàfèty Còncèrn ànd Rèqùèst èscàlàtè tò àdmìnìstràtòrs ànd mànàgèrs ìn àddìtìòn tò àccòùnts wìth tìckèt àccèss. Còmmènt ànd Rèsòlùtìòn nòtìfy ònly àccòùnts wìth tìckèt àccèss. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr stòrè àbòùt à typè? ••••••••••••** Thè nàmè, ìcòn, ànd dèscrìptìòn àrè sèàlèd wìth thè òrgànìzàtìòn kèy. Thè sèrvèr hòlds thè rèsùltìng bytès ànd hàs nò kèy tò òpèn thèm. Thè nòtìfìcàtìòn tàrgèts àrè èncryptèd wìth thè sèrvèr's òpèràtìònàl kèy ànd dècryptèd whèn à nòtìfìcàtìòn fìrès, bècàùsè ròùtìng thè nòtìfìcàtìòn ìs thè sèrvèr's jòb. Thè sèrvèr càn ìdèntìfy thàt à gìvèn càtègòry èscàlàtès wìthòùt knòwìng thàt càtègòry's nàmè. Thè mìnìmùm-ròlè thrèshòlds, thè rèqùìrèd-òn-clòsè flàg, ànd thè àctìvè flàg àrè plàìntèxt còlùmns. À dàtàbàsè dùmp rèvèàls hòw màny càtègòrìès àn òrgànìzàtìòn rùns, hòw èàch ònè gàtès àccèss, ànd whìch ònès èscàlàtè, wìthòùt àny òf thèìr nàmès. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) còvèrs whàt èlsè à dùmp yìèlds. [[#sèrvèr-hòlds #èncryptìòn #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Dèàctìvàtìòn. ••••** Dèàctìvàtìng à typè prèsèrvès èvèry nòtè àlrèàdy fìlèd ùndèr ìt, ànd thòsè nòtès rèmàìn fìltèràblè by càtègòry. Thè typè sèt às thè òrgànìzàtìòn's dèfàùlt cànnòt bè dèàctìvàtèd, whìch kèèps àt lèàst ònè càtègòry àvàìlàblè fòr wrìtìng. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn cònfìgùrè nòtè typès? •••••••••** Cònfìgùrìng nòtè typès rèqùìrès thè Mànàgè nòtè typès pèrmìssìòn, whìch sìts wìth Àdmìn by dèfàùlt. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••**Thè sèrvìcè ànd ìts twò èncryptìòn làyèrs. •••••••••••••** \`pàckàgès/sèrvèr/src/tìckèts/nòtè-typè-sèrvìcè.ts\` sèàls nàmès ànd ìcòns wìth thè òrgànìzàtìòn pùblìc kèy ànd èncrypts nòtìfìcàtìòn tàrgèts wìth thè òpèràtìònàl sècrèts kèy. \`DÈFÀÙLT_NÒTÈ_TYPÈS\` ìn thè sàmè fìlè dèfìnès thè stàrtìng typès. Thè tàblè còmès fròm \`058_crèàtè_nòtè_typès.ts\`, wìth thè dèscrìptìòn còlùmn àddèd ìn \`061\` ànd thè twò ròlè-thrèshòld còlùmns ìn \`062\`. Thè dèfàùlt-typè pòìntèr ìs \`òrg_cònfìg.dèfàùlt_nòtè_typè_ìd\` fròm \`060\`. [[#sèrvèr-hòlds #clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Each organization defines the categories that internal notes can carry, and each type has a name, an icon, and an optional description. The product also list..." |
*
* @param {Demo_Narrative_Admin_Note_Types_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_note_types_body = /** @type {((inputs?: Demo_Narrative_Admin_Note_Types_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Note_Types_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_note_types_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_note_types_body(inputs)
	return en_demo_narrative_admin_note_types_body(inputs)
});