/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Notes_BodyInputs */

const en_demo_narrative_topic_notes_body = /** @type {(inputs: Demo_Narrative_Topic_Notes_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`An internal note records what the organization wants remembered about a ticket without sending anything to the client. The note is sealed with the same ticket key as the messages around it. [[#client-data #encryption]]
**What does the server hold?** The note's content is ciphertext. Its type, its author, its creation time, the accounts mentioned in it, and the private flag are plaintext columns. A database dump shows that an account wrote a note of a given type on a ticket at a given hour and named two accounts in it, and none of what it says. [The trust boundary](#deep-dive/the-trust-boundary) lists those columns beside the rest of the schema. [[#server-holds #metadata]]
**Note types and visibility.** Each note carries a type. A type carries a minimum role for writing and a minimum role for seeing. The server drops the notes a caller's role may not see before building the response. A note below the caller's threshold never leaves the server. An author always sees their own. A type's name, icon, and description are organization-key ciphertext, and the roles it gates on are plaintext. The server enforces the rule without reading what the type is called. [Note types](#admin-org/note-types) covers creating and editing them. [[#permissions #privacy #encryption]]
**Escalation targets.** A type can name who to notify when a note of that type is written. Those targets are sealed with the server's operational key rather than the organization key, because the server sends the notification with nobody signed in. Mentioning an account in a note pings it once rather than subscribing it to the ticket. [[#trust-boundary #server-holds]]
**Reactions, edits, and deletions.** The reactions are acknowledge, approve, disagree, flag, and complete. Each reaction is a plaintext row naming the account, the note, and the time. An account can edit its own notes and delete its own. An administrator can delete another account's note but cannot edit it. A deleted note is marked deleted and excluded from every read; its ciphertext stays in the row. [[#permissions #retention #metadata]]
**The compose surface and role filter.** The compose surface is \`InternalNoteSheet.svelte\`. The role filter is in \`listFollowUps\` in \`packages/server/src/tickets/followup-service.ts\`. Types come from \`058_create_note_types.ts\` with role columns from \`062_add_note_type_role_gating.ts\`. Reactions are \`063_create_followup_reactions.ts\`, and mention validation is \`packages/server/src/tickets/mentions.ts\`. [[#client-data]]`)
};

const es_demo_narrative_topic_notes_body = /** @type {(inputs: Demo_Narrative_Topic_Notes_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Una nota interna registra lo que la organización quiere recordar sobre un ticket sin enviarle nada al cliente. La nota se sella con la misma clave del ticket que los mensajes que la rodean. [[#client-data #encryption]]
**¿Qué guarda el servidor?** El contenido de la nota es texto cifrado. Su tipo, su autoría, su fecha de creación, las cuentas mencionadas en ella y la marca de privada son columnas en texto plano. Un volcado de la base de datos muestra que una cuenta escribió una nota de cierto tipo en un ticket a cierta hora y nombró en ella a dos cuentas, y nada de lo que dice. [La frontera de confianza](#deep-dive/the-trust-boundary) enumera esas columnas junto al resto del esquema. [[#server-holds #metadata]]
**Tipos de nota y visibilidad.** Cada nota lleva un tipo. Un tipo lleva un rol mínimo para escribirla y un rol mínimo para verla. El servidor descarta las notas que el rol de quien consulta no puede ver antes de armar la respuesta. Una nota por debajo del umbral de quien consulta nunca sale del servidor. Quien la escribió siempre ve las suyas. El nombre, el icono y la descripción de un tipo son texto cifrado con la clave de la organización, y los roles con los que restringe están en texto plano. El servidor aplica la regla sin leer cómo se llama el tipo. [Tipos de nota](#admin-org/note-types) trata cómo se crean y se editan. [[#permissions #privacy #encryption]]
**Destinos de escalación.** Un tipo puede nombrar a quién avisar cuando se escribe una nota de ese tipo. Esos destinos se sellan con la clave operativa del servidor y no con la de la organización, porque el servidor es quien envía el aviso sin nadie con la sesión iniciada. Mencionar a una cuenta en una nota la avisa una vez; no la suscribe al ticket. [[#trust-boundary #server-holds]]
**Reacciones, ediciones y borrados.** Las reacciones son reconocer, aprobar, en desacuerdo, marcar y completar. Cada reacción es una fila en texto plano que nombra la cuenta, la nota y la fecha. Una cuenta puede editar sus propias notas y borrar las suyas. Una persona administradora puede borrar la nota de otra cuenta, pero no puede editarla. Una nota borrada queda marcada como borrada y se excluye de todas las lecturas; su texto cifrado permanece en la fila. [[#permissions #retention #metadata]]
**La superficie de composición y el filtro por rol.** La superficie de composición es \`InternalNoteSheet.svelte\`. El filtro por rol está en \`listFollowUps\`, en \`packages/server/src/tickets/followup-service.ts\`. Los tipos vienen de \`058_create_note_types.ts\` con las columnas de rol de \`062_add_note_type_role_gating.ts\`. Las reacciones son \`063_create_followup_reactions.ts\`, y la validación de menciones es \`packages/server/src/tickets/mentions.ts\`. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_notes_body = /** @type {(inputs: Demo_Narrative_Topic_Notes_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Àn ìntèrnàl nòtè rècòrds whàt thè òrgànìzàtìòn wànts rèmèmbèrèd àbòùt à tìckèt wìthòùt sèndìng ànythìng tò thè clìènt. Thè nòtè ìs sèàlèd wìth thè sàmè tìckèt kèy às thè mèssàgès àròùnd ìt. [[#clìènt-dàtà #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèrvèr hòld? ••••••••** Thè nòtè's còntènt ìs cìphèrtèxt. Ìts typè, ìts àùthòr, ìts crèàtìòn tìmè, thè àccòùnts mèntìònèd ìn ìt, ànd thè prìvàtè flàg àrè plàìntèxt còlùmns. À dàtàbàsè dùmp shòws thàt àn àccòùnt wròtè à nòtè òf à gìvèn typè òn à tìckèt àt à gìvèn hòùr ànd nàmèd twò àccòùnts ìn ìt, ànd nònè òf whàt ìt sàys. [Thè trùst bòùndàry](#dèèp-dìvè/thè-trùst-bòùndàry) lìsts thòsè còlùmns bèsìdè thè rèst òf thè schèmà. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Nòtè typès ànd vìsìbìlìty. ••••••••** Èàch nòtè càrrìès à typè. À typè càrrìès à mìnìmùm ròlè fòr wrìtìng ànd à mìnìmùm ròlè fòr sèèìng. Thè sèrvèr dròps thè nòtès à càllèr's ròlè mày nòt sèè bèfòrè bùìldìng thè rèspònsè. À nòtè bèlòw thè càllèr's thrèshòld nèvèr lèàvès thè sèrvèr. Àn àùthòr àlwàys sèès thèìr òwn. À typè's nàmè, ìcòn, ànd dèscrìptìòn àrè òrgànìzàtìòn-kèy cìphèrtèxt, ànd thè ròlès ìt gàtès òn àrè plàìntèxt. Thè sèrvèr ènfòrcès thè rùlè wìthòùt rèàdìng whàt thè typè ìs càllèd. [Nòtè typès](#àdmìn-òrg/nòtè-typès) còvèrs crèàtìng ànd èdìtìng thèm. [[#pèrmìssìòns #prìvàcy #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Èscàlàtìòn tàrgèts. ••••••** À typè càn nàmè whò tò nòtìfy whèn à nòtè òf thàt typè ìs wrìttèn. Thòsè tàrgèts àrè sèàlèd wìth thè sèrvèr's òpèràtìònàl kèy ràthèr thàn thè òrgànìzàtìòn kèy, bècàùsè thè sèrvèr sènds thè nòtìfìcàtìòn wìth nòbòdy sìgnèd ìn. Mèntìònìng àn àccòùnt ìn à nòtè pìngs ìt òncè ràthèr thàn sùbscrìbìng ìt tò thè tìckèt. [[#trùst-bòùndàry #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rèàctìòns, èdìts, ànd dèlètìòns. ••••••••••** Thè rèàctìòns àrè àcknòwlèdgè, àppròvè, dìsàgrèè, flàg, ànd còmplètè. Èàch rèàctìòn ìs à plàìntèxt ròw nàmìng thè àccòùnt, thè nòtè, ànd thè tìmè. Àn àccòùnt càn èdìt ìts òwn nòtès ànd dèlètè ìts òwn. Àn àdmìnìstràtòr càn dèlètè ànòthèr àccòùnt's nòtè bùt cànnòt èdìt ìt. À dèlètèd nòtè ìs màrkèd dèlètèd ànd èxclùdèd fròm èvèry rèàd; ìts cìphèrtèxt stàys ìn thè ròw. [[#pèrmìssìòns #rètèntìòn #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè còmpòsè sùrfàcè ànd ròlè fìltèr. •••••••••••** Thè còmpòsè sùrfàcè ìs \`ÌntèrnàlNòtèShèèt.svèltè\`. Thè ròlè fìltèr ìs ìn \`lìstFòllòwÙps\` ìn \`pàckàgès/sèrvèr/src/tìckèts/fòllòwùp-sèrvìcè.ts\`. Typès còmè fròm \`058_crèàtè_nòtè_typès.ts\` wìth ròlè còlùmns fròm \`062_àdd_nòtè_typè_ròlè_gàtìng.ts\`. Rèàctìòns àrè \`063_crèàtè_fòllòwùp_rèàctìòns.ts\`, ànd mèntìòn vàlìdàtìòn ìs \`pàckàgès/sèrvèr/src/tìckèts/mèntìòns.ts\`. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "An internal note records what the organization wants remembered about a ticket without sending anything to the client. The note is sealed with the same ticke..." |
*
* @param {Demo_Narrative_Topic_Notes_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_notes_body = /** @type {((inputs?: Demo_Narrative_Topic_Notes_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Notes_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_notes_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_notes_body(inputs)
	return en_demo_narrative_topic_notes_body(inputs)
});