/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Voicemails_BodyInputs */

const en_demo_narrative_topic_voicemails_body = /** @type {(inputs: Demo_Narrative_Topic_Voicemails_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A voicemail left on the organization's line becomes a follow-up on the client's ticket, with audio the browser can play and the server cannot read. [[#telephony #encryption]]
**What happens to the audio before it is stored?** The server fetches the recording from the provider. It encrypts the recording with the ticket key, writes the ciphertext to blob storage, and asks the provider to delete the recording and the call log entry it belongs to. The audio exists in plaintext only during that single handler invocation, in buffers the code zeroes afterward. [Call log](#ticket-detail/call-log) covers the provider cleanup that follows, and [The telephony relay](#deep-dive/the-telephony-relay) covers the rules that endpoint works under. [[#server-holds #telephony #retention]]
**What happens when a recording cannot be matched?** A voicemail that cannot be matched to a client or a queue is encrypted with the organization key and held in quarantine for an administrator to route manually. The system does not store it unencrypted and does not discard it. [Voicemail quarantine](#admin-comms/quarantine) covers what an administrator can do with one. [[#failure-states #encryption]]
**Playback and metadata.** Fetching the ciphertext requires the Download case media permission. The endpoint hands back ciphertext and decrypts nothing itself. The browser decodes the audio on the device. The decrypted sound exists only in that tab and is dropped when the user closes the follow-up. The recording's size, duration, and timestamps are stored in plaintext, so a database dump shows that a ticket received a ninety-second voicemail on a given evening. [[#permissions #privacy #metadata]]
**How is a recording bound to its ticket?** A recording is encrypted directly with the ticket key, or encrypted with a separate key that the ticket key unwraps. In both cases the audio is bound to its record, so ciphertext moved to a different record fails to open. A copy is encrypted with the client's channel key when one is active, so the client can hear their own voicemail on their private page. [How encryption works](#deep-dive/how-encryption-works) covers the binding. [[#keys #encryption #portal]]
**The recording handler and the player.** \`packages/server/src/telephony/recording-handler.ts\` runs the store-then-delete sequence, \`voicemail-quarantine.ts\` holds the unroutable ones, and the row is \`recordings\` in \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. The player is \`VoicemailPlayer.svelte\`, which takes an injected decrypt callback built in \`packages/client/src/lib/tickets/recording-decrypt.ts\` so the ticket thread and the client's own thread share one player. [[#client-data]]`)
};

const es_demo_narrative_topic_voicemails_body = /** @type {(inputs: Demo_Narrative_Topic_Voicemails_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Un mensaje de voz dejado en la línea de la organización se convierte en un seguimiento en el ticket del cliente, con audio que el navegador puede reproducir y el servidor no puede leer. [[#telephony #encryption]]
**¿Qué ocurre con el audio antes de almacenarse?** El servidor obtiene la grabación del proveedor. La cifra con la clave del ticket, escribe el texto cifrado en almacenamiento de blobs y le pide al proveedor que elimine la grabación y la entrada del registro de llamadas a la que pertenece. El audio existe en texto plano solo durante esa única invocación del handler, en buffers que el código pone a cero después. [Registro de llamadas](#ticket-detail/call-log) trata la limpieza del proveedor que sigue, y [El relay de telefonía](#deep-dive/the-telephony-relay) trata las reglas bajo las que trabaja ese endpoint. [[#server-holds #telephony #retention]]
**¿Qué ocurre cuando una grabación no puede emparejarse?** Un mensaje de voz que no puede emparejarse con un cliente o una cola se cifra con la clave de la organización y se retiene en cuarentena para que una persona administradora lo enrute a mano. El sistema no lo almacena sin cifrar y no lo descarta. [Cuarentena de correo de voz](#admin-comms/quarantine) trata lo que una persona administradora puede hacer con uno. [[#failure-states #encryption]]
**Reproducción y metadatos.** Obtener el texto cifrado requiere el permiso Descargar archivos del caso. El endpoint devuelve texto cifrado y no descifra nada. El navegador decodifica el audio en el dispositivo. El sonido descifrado existe solo en esa pestaña y se descarta cuando la persona usuaria cierra el seguimiento. El tamaño, la duración y las marcas de tiempo de la grabación se almacenan en texto plano, así que un volcado de la base de datos muestra que un ticket recibió un mensaje de voz de noventa segundos en una tarde determinada. [[#permissions #privacy #metadata]]
**¿Cómo se vincula una grabación a su ticket?** Una grabación se cifra directamente con la clave del ticket, o se cifra con una clave separada que la clave del ticket desenvuelve. En ambos casos el audio está vinculado a su registro, así que un texto cifrado movido a otro registro no se abre. Una copia se cifra con la clave de canal del cliente cuando hay uno activo, para que el cliente pueda escuchar su propio mensaje de voz en su página privada. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la vinculación. [[#keys #encryption #portal]]
**El handler de grabación y el reproductor.** \`packages/server/src/telephony/recording-handler.ts\` ejecuta la secuencia de almacenar y eliminar, \`voicemail-quarantine.ts\` retiene los que no pueden enrutarse, y la fila es \`recordings\`, en \`packages/server/src/db/migrations/tenant/001_baseline.ts\`. El reproductor es \`VoicemailPlayer.svelte\`, que recibe un callback de descifrado inyectado construido en \`packages/client/src/lib/tickets/recording-decrypt.ts\` para que el hilo del ticket y el hilo propio del cliente compartan un reproductor. [[#client-data]]`)
};

const en_xa2_demo_narrative_topic_voicemails_body = /** @type {(inputs: Demo_Narrative_Topic_Voicemails_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦À vòìcèmàìl lèft òn thè òrgànìzàtìòn's lìnè bècòmès à fòllòw-ùp òn thè clìènt's tìckèt, wìth àùdìò thè bròwsèr càn plày ànd thè sèrvèr cànnòt rèàd. [[#tèlèphòny #èncryptìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns tò thè àùdìò bèfòrè ìt ìs stòrèd? ••••••••••••••** Thè sèrvèr fètchès thè rècòrdìng fròm thè pròvìdèr. Ìt èncrypts thè rècòrdìng wìth thè tìckèt kèy, wrìtès thè cìphèrtèxt tò blòb stòràgè, ànd àsks thè pròvìdèr tò dèlètè thè rècòrdìng ànd thè càll lòg èntry ìt bèlòngs tò. Thè àùdìò èxìsts ìn plàìntèxt ònly dùrìng thàt sìnglè hàndlèr ìnvòcàtìòn, ìn bùffèrs thè còdè zèròès àftèrwàrd. [Càll lòg](#tìckèt-dètàìl/càll-lòg) còvèrs thè pròvìdèr clèànùp thàt fòllòws, ànd [Thè tèlèphòny rèlày](#dèèp-dìvè/thè-tèlèphòny-rèlày) còvèrs thè rùlès thàt èndpòìnt wòrks ùndèr. [[#sèrvèr-hòlds #tèlèphòny #rètèntìòn]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn à rècòrdìng cànnòt bè màtchèd? •••••••••••••••** À vòìcèmàìl thàt cànnòt bè màtchèd tò à clìènt òr à qùèùè ìs èncryptèd wìth thè òrgànìzàtìòn kèy ànd hèld ìn qùàràntìnè fòr àn àdmìnìstràtòr tò ròùtè mànùàlly. Thè systèm dòès nòt stòrè ìt ùnèncryptèd ànd dòès nòt dìscàrd ìt. [Vòìcèmàìl qùàràntìnè](#àdmìn-còmms/qùàràntìnè) còvèrs whàt àn àdmìnìstràtòr càn dò wìth ònè. [[#fàìlùrè-stàtès #èncryptìòn]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Plàybàck ànd mètàdàtà. •••••••** Fètchìng thè cìphèrtèxt rèqùìrès thè Dòwnlòàd càsè mèdìà pèrmìssìòn. Thè èndpòìnt hànds bàck cìphèrtèxt ànd dècrypts nòthìng ìtsèlf. Thè bròwsèr dècòdès thè àùdìò òn thè dèvìcè. Thè dècryptèd sòùnd èxìsts ònly ìn thàt tàb ànd ìs dròppèd whèn thè ùsèr clòsès thè fòllòw-ùp. Thè rècòrdìng's sìzè, dùràtìòn, ànd tìmèstàmps àrè stòrèd ìn plàìntèxt, sò à dàtàbàsè dùmp shòws thàt à tìckèt rècèìvèd à nìnèty-sècònd vòìcèmàìl òn à gìvèn èvènìng. [[#pèrmìssìòns #prìvàcy #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw ìs à rècòrdìng bòùnd tò ìts tìckèt? ••••••••••••** À rècòrdìng ìs èncryptèd dìrèctly wìth thè tìckèt kèy, òr èncryptèd wìth à sèpàràtè kèy thàt thè tìckèt kèy ùnwràps. Ìn bòth càsès thè àùdìò ìs bòùnd tò ìts rècòrd, sò cìphèrtèxt mòvèd tò à dìffèrènt rècòrd fàìls tò òpèn. À còpy ìs èncryptèd wìth thè clìènt's chànnèl kèy whèn ònè ìs àctìvè, sò thè clìènt càn hèàr thèìr òwn vòìcèmàìl òn thèìr prìvàtè pàgè. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè bìndìng. [[#kèys #èncryptìòn #pòrtàl]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè rècòrdìng hàndlèr ànd thè plàyèr. ••••••••••••** \`pàckàgès/sèrvèr/src/tèlèphòny/rècòrdìng-hàndlèr.ts\` rùns thè stòrè-thèn-dèlètè sèqùèncè, \`vòìcèmàìl-qùàràntìnè.ts\` hòlds thè ùnròùtàblè ònès, ànd thè ròw ìs \`rècòrdìngs\` ìn \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/001_bàsèlìnè.ts\`. Thè plàyèr ìs \`VòìcèmàìlPlàyèr.svèltè\`, whìch tàkès àn ìnjèctèd dècrypt càllbàck bùìlt ìn \`pàckàgès/clìènt/src/lìb/tìckèts/rècòrdìng-dècrypt.ts\` sò thè tìckèt thrèàd ànd thè clìènt's òwn thrèàd shàrè ònè plàyèr. [[#clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "A voicemail left on the organization's line becomes a follow-up on the client's ticket, with audio the browser can play and the server cannot read. [[#teleph..." |
*
* @param {Demo_Narrative_Topic_Voicemails_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_voicemails_body = /** @type {((inputs?: Demo_Narrative_Topic_Voicemails_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Voicemails_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_voicemails_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_voicemails_body(inputs)
	return en_demo_narrative_topic_voicemails_body(inputs)
});