/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Topic_Portal_Tier_BodyInputs */

const en_demo_narrative_topic_portal_tier_body = /** @type {(inputs: Demo_Narrative_Topic_Portal_Tier_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The tier section reports how the client currently receives messages and offers the controls that change it: setting up a secure link, regenerating or revoking one, or resetting a client account. [[#portal #client-data]]
**One channel per client, not per ticket.** The tier is a column on the client record, not the ticket, and the database allows one active channel per client. Regenerating or revoking from one ticket changes how that client is reached on every ticket they have. The four tiers are text and email, secure link, continuation channel carried over from an intake form, and client account. Text and email is where every client starts. [The portal channel lifecycle](#deep-dive/portal-channel-lifecycle) covers how each channel ends. [[#portal #client-data #failure-states]]
**What does the section read?** The tier name, whether the channel has a passphrase, when it was created, and when the client was last seen on it. All four are plaintext columns. The server knows a client has a private page, whether a passphrase guards it, and how recently it was opened, and cannot read a word that passed through the channel. [[#server-holds #metadata #portal]]
**Who can change a channel?** Setting up, regenerating, and revoking a secure link each require the Manage portal channel permission. Resetting a client account requires the separate Reset client login permission. An organization that has switched secure links off at the policy level gets no setup offer. [Channel policy](#admin-comms/channel-policy) covers that switch. [The permission system](#deep-dive/the-permission-system) covers how grants work. [[#permissions #portal]]
**The tier column and its mutations.** \`communication_tier\` on \`clients\` and the \`portal_channels\` row both come from \`090_portal_channels.ts\`. A partial unique index filtered to active status allows at most one active channel per client while keeping revoked rows in the table. The mutations are \`upgradeToSecureLink\`, \`regenerateSecureLink\`, and \`revokeSecureLink\` on \`managePortalChannelProcedure\`, and \`resetClientAccount\` on \`resetClientLoginProcedure\`, all in \`packages/server/src/routes/tickets.ts\`. Each tier change writes an audit row of type \`client_tier_changed\` carrying the actor identifier and the operation name, with no client identifier. [Secure link setup](#ticket-detail/secure-link) covers what the browser does during a setup. [[#portal #metadata]]`)
};

const es_demo_narrative_topic_portal_tier_body = /** @type {(inputs: Demo_Narrative_Topic_Portal_Tier_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La sección de nivel informa cómo recibe mensajes el cliente actualmente y ofrece los controles para cambiarlo: configurar un enlace seguro, regenerar o revocar uno, o restablecer una cuenta de cliente. [[#portal #client-data]]
**Un canal por cliente, no por ticket.** El nivel es una columna en el registro del cliente, no en el ticket, y la base de datos permite un solo canal activo por cliente. Regenerar o revocar desde un ticket cambia cómo se contacta a ese cliente en todos los tickets que tenga. Los cuatro niveles son texto y correo electrónico, enlace seguro, canal de continuación trasladado desde un formulario de admisión y cuenta de cliente. Texto y correo electrónico es donde comienza cada cliente. [El ciclo de vida del canal del portal](#deep-dive/portal-channel-lifecycle) explica cómo termina cada canal. [[#portal #client-data #failure-states]]
**¿Qué lee la sección?** El nombre del nivel, si el canal tiene frase de paso, cuándo se creó y cuándo el cliente se conectó por última vez. Los cuatro son columnas en texto plano. El servidor sabe que un cliente tiene una página privada, si una frase de paso la protege y cuándo se abrió por última vez, y no puede leer una sola palabra que haya pasado por el canal. [[#server-holds #metadata #portal]]
**¿Quién puede cambiar un canal?** Configurar, regenerar y revocar un enlace seguro requieren el permiso Gestionar canal del portal. Restablecer una cuenta de cliente requiere el permiso separado Restablecer acceso del cliente. Una organización que haya desactivado los enlaces seguros a nivel de política no recibe oferta de configuración. [Política de canales](#admin-comms/channel-policy) trata ese interruptor. [El sistema de permisos](#deep-dive/the-permission-system) explica cómo funcionan las concesiones. [[#permissions #portal]]
**La columna de nivel y sus mutaciones.** \`communication_tier\` en \`clients\` y la fila \`portal_channels\` provienen de \`090_portal_channels.ts\`. Un índice único parcial filtrado por estado activo permite como máximo un canal activo por cliente mientras conserva las filas revocadas en la tabla. Las mutaciones son \`upgradeToSecureLink\`, \`regenerateSecureLink\` y \`revokeSecureLink\` en \`managePortalChannelProcedure\`, y \`resetClientAccount\` en \`resetClientLoginProcedure\`, todas en \`packages/server/src/routes/tickets.ts\`. Cada cambio de nivel escribe una fila de auditoría de tipo \`client_tier_changed\` con el identificador del actor y el nombre de la operación, sin identificador de cliente. [Configuración de enlace seguro](#ticket-detail/secure-link) trata lo que hace el navegador durante una configuración. [[#portal #metadata]]`)
};

const en_xa2_demo_narrative_topic_portal_tier_body = /** @type {(inputs: Demo_Narrative_Topic_Portal_Tier_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè tìèr sèctìòn rèpòrts hòw thè clìènt cùrrèntly rècèìvès mèssàgès ànd òffèrs thè còntròls thàt chàngè ìt: sèttìng ùp à sècùrè lìnk, règènèràtìng òr rèvòkìng ònè, òr rèsèttìng à clìènt àccòùnt. [[#pòrtàl #clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Ònè chànnèl pèr clìènt, nòt pèr tìckèt. ••••••••••••** Thè tìèr ìs à còlùmn òn thè clìènt rècòrd, nòt thè tìckèt, ànd thè dàtàbàsè àllòws ònè àctìvè chànnèl pèr clìènt. Règènèràtìng òr rèvòkìng fròm ònè tìckèt chàngès hòw thàt clìènt ìs rèàchèd òn èvèry tìckèt thèy hàvè. Thè fòùr tìèrs àrè tèxt ànd èmàìl, sècùrè lìnk, còntìnùàtìòn chànnèl càrrìèd òvèr fròm àn ìntàkè fòrm, ànd clìènt àccòùnt. Tèxt ànd èmàìl ìs whèrè èvèry clìènt stàrts. [Thè pòrtàl chànnèl lìfècyclè](#dèèp-dìvè/pòrtàl-chànnèl-lìfècyclè) còvèrs hòw èàch chànnèl ènds. [[#pòrtàl #clìènt-dàtà #fàìlùrè-stàtès]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès thè sèctìòn rèàd? •••••••••** Thè tìèr nàmè, whèthèr thè chànnèl hàs à pàssphràsè, whèn ìt wàs crèàtèd, ànd whèn thè clìènt wàs làst sèèn òn ìt. Àll fòùr àrè plàìntèxt còlùmns. Thè sèrvèr knòws à clìènt hàs à prìvàtè pàgè, whèthèr à pàssphràsè gùàrds ìt, ànd hòw rècèntly ìt wàs òpènèd, ànd cànnòt rèàd à wòrd thàt pàssèd thròùgh thè chànnèl. [[#sèrvèr-hòlds #mètàdàtà #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn chàngè à chànnèl? ••••••••** Sèttìng ùp, règènèràtìng, ànd rèvòkìng à sècùrè lìnk èàch rèqùìrè thè Mànàgè pòrtàl chànnèl pèrmìssìòn. Rèsèttìng à clìènt àccòùnt rèqùìrès thè sèpàràtè Rèsèt clìènt lògìn pèrmìssìòn. Àn òrgànìzàtìòn thàt hàs swìtchèd sècùrè lìnks òff àt thè pòlìcy lèvèl gèts nò sètùp òffèr. [Chànnèl pòlìcy](#àdmìn-còmms/chànnèl-pòlìcy) còvèrs thàt swìtch. [Thè pèrmìssìòn systèm](#dèèp-dìvè/thè-pèrmìssìòn-systèm) còvèrs hòw grànts wòrk. [[#pèrmìssìòns #pòrtàl]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè tìèr còlùmn ànd ìts mùtàtìòns. •••••••••••** \`còmmùnìcàtìòn_tìèr\` òn \`clìènts\` ànd thè \`pòrtàl_chànnèls\` ròw bòth còmè fròm \`090_pòrtàl_chànnèls.ts\`. À pàrtìàl ùnìqùè ìndèx fìltèrèd tò àctìvè stàtùs àllòws àt mòst ònè àctìvè chànnèl pèr clìènt whìlè kèèpìng rèvòkèd ròws ìn thè tàblè. Thè mùtàtìòns àrè \`ùpgràdèTòSècùrèLìnk\`, \`règènèràtèSècùrèLìnk\`, ànd \`rèvòkèSècùrèLìnk\` òn \`mànàgèPòrtàlChànnèlPròcèdùrè\`, ànd \`rèsètClìèntÀccòùnt\` òn \`rèsètClìèntLògìnPròcèdùrè\`, àll ìn \`pàckàgès/sèrvèr/src/ròùtès/tìckèts.ts\`. Èàch tìèr chàngè wrìtès àn àùdìt ròw òf typè \`clìènt_tìèr_chàngèd\` càrryìng thè àctòr ìdèntìfìèr ànd thè òpèràtìòn nàmè, wìth nò clìènt ìdèntìfìèr. [Sècùrè lìnk sètùp](#tìckèt-dètàìl/sècùrè-lìnk) còvèrs whàt thè bròwsèr dòès dùrìng à sètùp. [[#pòrtàl #mètàdàtà]] ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The tier section reports how the client currently receives messages and offers the controls that change it: setting up a secure link, regenerating or revokin..." |
*
* @param {Demo_Narrative_Topic_Portal_Tier_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_topic_portal_tier_body = /** @type {((inputs?: Demo_Narrative_Topic_Portal_Tier_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Topic_Portal_Tier_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_topic_portal_tier_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_topic_portal_tier_body(inputs)
	return en_demo_narrative_topic_portal_tier_body(inputs)
});