/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs */

const en_demo_narrative_deepdive_portal_channel_lifecycle_body = /** @type {(inputs: Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`A client's safest channel depends on their phone, their situation, and who else might be looking at their screen, so CARE-Y offers three and lets the client move up without asking anyone's permission. The three tiers differ in how much of the channel itself is protected. The help behind each tier is the same. [[#portal #privacy]]
Text and email is where every client starts. It works on any phone with no setup, the organization's stored copy of the conversation is encrypted like everything else, and the channel itself is not, because a text message is readable by the carrier and by the telephony provider on its way through. [The telephony relay](#deep-dive/the-telephony-relay) covers what that means in practice. [[#portal #telephony]]
A secure link is a private page for one client, reachable only by the exact link they were sent, with no account and no password to remember. Messages on that page are encrypted in the client's own browser, so neither the phone company nor the server can read them. The key material lives in the part of the link after the \`#\`, which browsers never send to a server, so the server can store the conversation without ever being able to open it. The limitation follows directly from that. Anyone who gets the whole link gets the conversation, which matters for a client whose phone might be looked through. For that case, a user can add a passphrase that is spoken aloud on the call and written down nowhere, so the link alone is no longer enough. [[#portal #encryption #failure-states]]
An encrypted account is the strongest of the three. The client chooses a username and a password, and the password derives their keys through the same protocol a staff member's password uses, which means the credential is something the client knows rather than something in a message someone else could find. The account can be installed to a home screen for repeat visits, and a subpoena to the phone company or the mail provider produces a login page address and nothing else. [[#portal #keys]]
Moving up a tier is the client's own decision, taken from inside their own session, and no member of staff has to enable it. What the client is offered depends on where they already are. [[#portal #privacy]]
- A client on a bare link is offered both the passphrase and the account. [[#portal]]
- A client on a passphrase link is offered the account. [[#portal]]
- A client already on an account is offered nothing further. [[#portal]]
That arrangement is deliberate, because adding a passphrase or an account is the mitigation for a captured link, and gating a mitigation behind someone else's attention works against it. [[#portal #privacy]]
One-time message links are a separate mechanism rather than a tier. A user sends a single encrypted message whose link stops working after its first read or after 72 hours, whichever comes first, which is how something sensitive travels over an insecure channel without living there. [[#portal #encryption]]
**Credential model per tier.** Each tier authenticates the client with something different. [[#portal #keys #encryption]]
- Text and email has no portal credential, because the client's phone number is the address. [[#portal #telephony]]
- A secure link's credential is a 24-byte random seed carried in the URL fragment. From that seed the browser derives a 48-character channel id, a 32-byte bearer token that authenticates every call the portal page makes, and an Argon2id salt, and the server stores only a BLAKE2b hash of the bearer token for timing-safe comparison. [[#portal #keys]]
- An account's credential is a username and a password, which run the full staff pipeline and yield both a keypair and an independent bearer token under separate labels, so neither reveals the other. [[#portal #keys]]
The channel keypair does not come from the seed directly. The seed, or the seed concatenated with the Argon2id stretch of the spoken passphrase, becomes the input to a key evaluation under a tag naming that organization and channel, and the evaluation's output derives the keypair. [[#portal #keys #encryption]]
**Why the evaluation step matters.** Routing channel derivation through a tagged evaluation buys two properties a seed-only derivation cannot have. A passphrase guess costs a rate-limited round trip under that channel's tag rather than a local hash, which is what makes a five-word spoken phrase worth using. And revocation becomes cryptographic rather than procedural, because the evaluation path refuses tags whose channel row is revoked or expired and no other credential is an oracle for that key, so a photographed link plus a later database dump stops decrypting at revocation. An unknown channel id is allowed because a link is minted before its row exists, an active row requires the bearer token, and revoked and expired rows are refused. [[#portal #keys #server-holds]]
**What the server holds for a channel.** The \`portal_channels\` row is plaintext throughout. [[#server-holds #metadata #portal]]
- The channel id, the bearer token hash, the client's public key and a passphrase flag. [[#server-holds #portal]]
- A key-check ciphertext with its ephemeral point and nonce. [[#server-holds #portal]]
- A status, plus created, last-seen, last-notified and revoked timestamps. [[#server-holds #metadata]]
- Message rows beside it carry direction, ephemeral point, nonce, ciphertext and timestamps. [[#server-holds #portal]]
So the server knows a channel exists, that it was opened, when, and how often, and it cannot read a word of it. A wrong passphrase is detected in the client's browser against the stored key check, so the server never learns whether a guess was right. [[#server-holds #metadata #portal]]
**Lifecycle and endings.** A channel can end four ways. [[#portal #retention #failure-states]]
- It expires lazily after 30 days without activity, at which point the client-side copies of messages, attachments and recordings are deleted while the organization's record of the case stays intact. [[#portal #retention]]
- Regenerating a link revokes the old channel and deletes the client's copies, so the old link shows a dead-link state on the next open. [[#portal #failure-states]]
- A user revokes it outright, and revoked, unknown and badly authenticated links all produce the same generic response, which is indistinguishable by design so a link cannot be probed. [[#portal #failure-states]]
- The organization switches the secure link channel off at the policy level, which freezes new channel creation and refuses replies while leaving a client holding a working link able to open it and read, because a freeze can be lifted later, while destroying a client's access to their own history cannot be undone. [[#portal #permissions]]
**Client-side custody.** Portal crypto runs in a dedicated worker rather than on the page, which owns the seed after the main thread's one unavoidable touch of parsing the URL fragment, along with the passphrase stretch, the blind and finalize halves of the evaluation, the keypair, message and attachment encryption, and a zeroing operation wired to quick exit and page hide. A script injected mid-session can still read plaintext already rendered on the page, which nothing can prevent, and it can no longer take the channel's private scalar out of a closure and decrypt the channel's future traffic offline. [[#portal #failure-states #encryption]]
**Contributor pointers.** Derivation, the worker, the services and the schema sit in four places. [[#portal]]
- Channel derivation is \`packages/crypto/src/portal.ts\` and account derivation is \`packages/crypto/src/client-account.ts\`, both on the shared \`keypairFromOprfOutput\` helper. [[#portal #keys]]
- The portal worker and its bridge are under \`packages/client/src/lib/workers/portal*\`, and the client surfaces are under \`packages/client/src/lib/portal/\`. [[#portal]]
- The server services are under \`packages/server/src/portal/\` with the tRPC surface in \`packages/server/src/routes/client-portal.ts\`. [[#portal #server-holds]]
- Schema is \`packages/server/src/db/migrations/tenant/090_portal_channels.ts\` with \`092_client_accounts.ts\`, \`104_portal_attachments.ts\` and \`105_portal_media_parity.ts\`, and the 30-day sweep is \`packages/server/src/jobs/portal-message-expiry.ts\`. [[#portal #retention]]`)
};

const es_demo_narrative_deepdive_portal_channel_lifecycle_body = /** @type {(inputs: Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El canal más seguro para un cliente depende de su teléfono, de su situación y de quién más podría estar mirando su pantalla, así que CARE-Y ofrece tres y deja que el cliente suba de nivel sin pedir permiso a nadie. Los tres niveles difieren en cuánto está protegido el canal mismo. La ayuda que hay detrás de cada nivel es la misma. [[#portal #privacy]]
El texto y el correo es donde empieza todo cliente. Funciona en cualquier teléfono sin configuración, la copia de la conversación que guarda la organización está cifrada como todo lo demás, y el canal mismo no lo está, porque un mensaje de texto es legible por la compañía telefónica y por el proveedor de telefonía a su paso. [El relay de telefonía](#deep-dive/the-telephony-relay) cubre lo que eso significa en la práctica. [[#portal #telephony]]
Un enlace seguro es una página privada para un solo cliente, alcanzable únicamente con el enlace exacto que se le envió, sin cuenta y sin contraseña que recordar. Los mensajes de esa página se cifran en el propio navegador del cliente, así que ni la compañía telefónica ni el servidor pueden leerlos. El material de claves vive en la parte del enlace posterior al \`#\`, que los navegadores nunca envían a un servidor, así que el servidor puede almacenar la conversación sin poder abrirla nunca. La limitación se sigue directamente de ahí. Quien consigue el enlace completo consigue la conversación, lo que importa para un cliente cuyo teléfono podría ser revisado. Para ese caso, una persona usuaria puede añadir una frase de paso que se dice en voz alta en la llamada y no se escribe en ninguna parte, de modo que el enlace por sí solo ya no basta. [[#portal #encryption #failure-states]]
Una cuenta cifrada es la más fuerte de las tres. El cliente elige un nombre de usuario y una contraseña, y la contraseña deriva sus claves mediante el mismo protocolo que usa la contraseña de quien trabaja en la organización, lo que significa que la credencial es algo que el cliente sabe y no algo que está en un mensaje que otra persona podría encontrar. La cuenta se puede instalar en la pantalla de inicio para visitas repetidas, y una orden judicial a la compañía telefónica o al proveedor de correo produce la dirección de una página de inicio de sesión y nada más. [[#portal #keys]]
Subir de nivel es una decisión del propio cliente, tomada desde dentro de su propia sesión, y ningún miembro de la organización tiene que habilitarla. Lo que se le ofrece al cliente depende de dónde está ya. [[#portal #privacy]]
- A un cliente con un enlace sin frase de paso se le ofrecen tanto la frase de paso como la cuenta. [[#portal]]
- A un cliente con un enlace con frase de paso se le ofrece la cuenta. [[#portal]]
- A un cliente que ya tiene una cuenta no se le ofrece nada más. [[#portal]]
Ese arreglo es deliberado, porque añadir una frase de paso o una cuenta es la mitigación para un enlace capturado, y poner una mitigación detrás de la atención de otra persona trabaja en su contra. [[#portal #privacy]]
Los enlaces de mensaje de un solo uso son un mecanismo aparte y no un nivel. Una persona usuaria envía un único mensaje cifrado cuyo enlace deja de funcionar tras su primera lectura o tras 72 horas, lo que ocurra primero, que es como algo sensible viaja por un canal inseguro sin vivir en él. [[#portal #encryption]]
**Modelo de credencial por nivel.** Cada nivel autentica al cliente con algo distinto. [[#portal #keys #encryption]]
- El texto y el correo no tiene credencial de portal, porque el número de teléfono del cliente es la dirección. [[#portal #telephony]]
- La credencial de un enlace seguro es una semilla aleatoria de 24 bytes que viaja en el fragmento de la URL. A partir de esa semilla el navegador deriva un identificador de canal de 48 caracteres, un token portador de 32 bytes que autentica cada llamada que hace la página del portal, y una sal de Argon2id, y el servidor almacena solo un hash BLAKE2b del token portador para una comparación segura en tiempo. [[#portal #keys]]
- La credencial de una cuenta es un nombre de usuario y una contraseña, que recorren la misma tubería completa que el personal de la organización y producen tanto un par de claves como un token portador independiente bajo etiquetas separadas, así que ninguno revela el otro. [[#portal #keys]]
El par de claves del canal no viene de la semilla directamente. La semilla, o la semilla concatenada con el estiramiento Argon2id de la frase de paso hablada, se convierte en la entrada de una evaluación de claves bajo una etiqueta que nombra esa organización y ese canal, y la salida de la evaluación deriva el par de claves. [[#portal #keys #encryption]]
**Por qué importa el paso de evaluación.** Encaminar la derivación del canal a través de una evaluación etiquetada compra dos propiedades que una derivación basada solo en la semilla no puede tener. Adivinar una frase de paso cuesta una ida y vuelta limitada por tasa bajo la etiqueta de ese canal en lugar de un hash local, que es lo que hace que valga la pena una frase hablada de cinco palabras. Y la revocación pasa a ser criptográfica en lugar de procedimental, porque la ruta de evaluación rechaza las etiquetas cuya fila de canal está revocada o caducada y ninguna otra credencial es un oráculo para esa clave, así que un enlace fotografiado más un volcado posterior de la base de datos deja de descifrar en el momento de la revocación. Un identificador de canal desconocido se permite porque un enlace se emite antes de que exista su fila, una fila activa exige el token portador, y las filas revocadas y caducadas se rechazan. [[#portal #keys #server-holds]]
**Qué guarda el servidor de un canal.** La fila de \`portal_channels\` está en texto plano de principio a fin. [[#server-holds #metadata #portal]]
- El identificador del canal, el hash del token portador, la clave pública del cliente y una marca de frase de paso. [[#server-holds #portal]]
- Un texto cifrado de comprobación de clave con su punto efímero y su nonce. [[#server-holds #portal]]
- Un estado, más las marcas de tiempo de creación, última vista, última notificación y revocación. [[#server-holds #metadata]]
- Las filas de mensaje que están al lado llevan dirección, punto efímero, nonce, texto cifrado y marcas de tiempo. [[#server-holds #portal]]
Así que el servidor sabe que un canal existe, que se abrió, cuándo y con qué frecuencia, y no puede leer una palabra de él. Una frase de paso incorrecta se detecta en el navegador del cliente contra la comprobación de clave almacenada, así que el servidor nunca se entera de si un intento fue correcto. [[#server-holds #metadata #portal]]
**Ciclo de vida y finales.** Un canal puede terminar de cuatro maneras. [[#portal #retention #failure-states]]
- Caduca de forma diferida tras 30 días sin actividad, momento en el que las copias del lado del cliente de mensajes, adjuntos y grabaciones se eliminan mientras el registro del caso que tiene la organización queda intacto. [[#portal #retention]]
- Regenerar un enlace revoca el canal antiguo y elimina las copias del cliente, así que el enlace antiguo muestra un estado de enlace muerto en la siguiente apertura. [[#portal #failure-states]]
- Una persona usuaria lo revoca sin más, y los enlaces revocados, desconocidos y mal autenticados producen todos la misma respuesta genérica, indistinguible por diseño para que no se pueda sondear un enlace. [[#portal #failure-states]]
- La organización desactiva el canal de enlace seguro a nivel de política, lo que congela la creación de canales nuevos y rechaza las respuestas mientras deja que un cliente que tiene un enlace en funcionamiento pueda abrirlo y leer, porque una congelación se puede levantar más tarde, mientras que destruir el acceso de un cliente a su propio historial no se puede deshacer. [[#portal #permissions]]
**Custodia del lado del cliente.** La criptografía del portal se ejecuta en un worker dedicado y no en la página, y ese worker es dueño de la semilla después del único contacto inevitable del hilo principal al analizar el fragmento de la URL, junto con el estiramiento de la frase de paso, las mitades de cegado y finalización de la evaluación, el par de claves, el cifrado de mensajes y adjuntos, y una operación de puesta a cero conectada a la salida rápida y al ocultado de la página. Un script inyectado a mitad de sesión todavía puede leer el texto plano ya representado en la página, lo que nada puede impedir, y ya no puede sacar el escalar privado del canal de un closure y descifrar sin conexión el tráfico futuro del canal. [[#portal #failure-states #encryption]]
**Indicaciones para quien contribuye.** La derivación, el worker, los servicios y el esquema están en cuatro lugares. [[#portal]]
- La derivación del canal es \`packages/crypto/src/portal.ts\` y la derivación de la cuenta es \`packages/crypto/src/client-account.ts\`, ambas sobre el ayudante compartido \`keypairFromOprfOutput\`. [[#portal #keys]]
- El worker del portal y su puente están bajo \`packages/client/src/lib/workers/portal*\`, y las superficies del cliente están bajo \`packages/client/src/lib/portal/\`. [[#portal]]
- Los servicios del servidor están bajo \`packages/server/src/portal/\` con la superficie tRPC en \`packages/server/src/routes/client-portal.ts\`. [[#portal #server-holds]]
- El esquema es \`packages/server/src/db/migrations/tenant/090_portal_channels.ts\` junto con \`092_client_accounts.ts\`, \`104_portal_attachments.ts\` y \`105_portal_media_parity.ts\`, y el barrido de 30 días es \`packages/server/src/jobs/portal-message-expiry.ts\`. [[#portal #retention]]`)
};

/**
* | output |
* | --- |
* | "A client's safest channel depends on their phone, their situation, and who else might be looking at their screen, so CARE-Y offers three and lets the client ..." |
*
* @param {Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs} inputs
* @param {{ locale?: "en" | "es" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_deepdive_portal_channel_lifecycle_body = /** @type {((inputs?: Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs, options?: { locale?: "en" | "es" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Deepdive_Portal_Channel_Lifecycle_BodyInputs, { locale?: "en" | "es" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_deepdive_portal_channel_lifecycle_body(inputs)
	return en_demo_narrative_deepdive_portal_channel_lifecycle_body(inputs)
});