/* eslint-disable */
import * as registry from '../registry.js'
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Search_Overlay_BodyInputs */

const en_demo_narrative_search_overlay_body = /** @type {(inputs: Demo_Narrative_Search_Overlay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`Global search opens as an overlay and shows recent searches and recently viewed cases and articles before the user enters a search term. Results appear after the user types at least two characters. [[#privacy #client-data #search]]
**Recent searches.** The list holds ten terms at most, in memory only. The terms are gone when the user signs out, reloads the page, or closes the browser. No search term is written to the device or sent to the server. A browser handed to someone else carries no record of what was searched for. [[#privacy #client-data]]
**Recently viewed cases and articles.** The server stores one envelope per account, sealed to that account's own public key. Only that user's browser can open it. The envelope holds the identifiers of up to twenty cases and articles and the times they were opened. It holds no titles. The server cannot read which case any identifier inside it belongs to, and no other user can open the envelope. [How encryption works](#deep-dive/how-encryption-works) covers the key it is sealed to. [[#encryption #server-holds]]
**What falls out of the list?** The overlay looks each identifier up against the same records it searches for a query. A case or article the account no longer has access to does not appear. A password change replaces the keys the envelope was sealed to and makes it unopenable. The app treats an unopenable envelope as empty history and overwrites it on the next view, so a password change silently clears the recently viewed list. [Password and key re-wrap](#settings/password) covers that rotation. [[#failure-states #keys]]
**How are results ordered?** Results are grouped by kind of record. The group matching the surface the search was opened from appears first, so the same query returns a different order from the ticket list than from the library. Each group reports how many records it searched against the total, so the user can tell when an answer covers only what is already unlocked on the device. [What global search covers](#search/entities) covers the kinds. [[#client-data #metadata]]
**The provider registry and the two lists.** The provider registry is \`packages/client/src/lib/search/registry.svelte.ts\`. The session term list is \`recents.svelte.ts\`. The recently viewed envelope is \`recent-views.ts\` against \`user_recent_views\` from \`packages/server/src/db/migrations/tenant/079_create_user_recent_views.ts\`. That table stores one row per account with no server-side timestamp. [[#server-holds #client-data]]`)
};

const es_demo_narrative_search_overlay_body = /** @type {(inputs: Demo_Narrative_Search_Overlay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`La búsqueda global se abre como una superposición y muestra las búsquedas recientes y los casos y artículos vistos recientemente antes de introducir un término. Los resultados aparecen al escribir al menos dos caracteres. [[#privacy #client-data #search]]
**Búsquedas recientes.** La lista retiene como máximo diez términos, solo en memoria. Los términos desaparecen cuando la persona usuaria cierra sesión, recarga la página o cierra el navegador. Ningún término de búsqueda se escribe en el dispositivo ni se envía al servidor. Un navegador entregado a otra persona no conserva ningún registro de lo que se buscó. [[#privacy #client-data]]
**Casos y artículos vistos recientemente.** El servidor almacena un sobre por cuenta, sellado con la clave pública de esa cuenta. Solo el navegador de esa persona puede abrirlo. El sobre contiene los identificadores de hasta veinte casos y artículos y los momentos en que se abrieron. No contiene títulos. El servidor no puede leer a qué caso pertenece cada identificador, y ninguna otra persona puede abrir el sobre. [Cómo funciona el cifrado](#deep-dive/how-encryption-works) trata la clave con la que se sella. [[#encryption #server-holds]]
**¿Qué sale de la lista?** La superposición busca cada identificador en los mismos registros que busca para una consulta. Un caso o artículo al que la cuenta ya no tiene acceso no aparece. Un cambio de contraseña reemplaza las claves con las que se selló el sobre y lo vuelve ilegible. La aplicación trata un sobre ilegible como historial vacío y lo sobrescribe en la siguiente vista, de modo que un cambio de contraseña borra silenciosamente la lista de vistos recientes. [Contraseña y re-envolvimiento de claves](#settings/password) trata esa rotación. [[#failure-states #keys]]
**¿Cómo se ordenan los resultados?** Los resultados se agrupan por tipo de registro. El grupo que corresponde a la superficie desde la que se abrió la búsqueda aparece primero, de modo que la misma consulta devuelve un orden diferente desde la lista de tickets que desde la biblioteca. Cada grupo informa cuántos registros buscó del total, para que la persona usuaria pueda saber cuándo una respuesta cubre solo lo que ya está desbloqueado en el dispositivo. [Qué cubre la búsqueda global](#search/entities) trata los tipos. [[#client-data #metadata]]
**El registro de proveedores y las dos listas.** El registro de proveedores es \`packages/client/src/lib/search/registry.svelte.ts\`. La lista de términos de sesión es \`recents.svelte.ts\`. El sobre de vistos recientes es \`recent-views.ts\` contra \`user_recent_views\` de \`packages/server/src/db/migrations/tenant/079_create_user_recent_views.ts\`. Esa tabla almacena una fila por cuenta sin marca de tiempo del lado del servidor. [[#server-holds #client-data]]`)
};

const en_xa2_demo_narrative_search_overlay_body = /** @type {(inputs: Demo_Narrative_Search_Overlay_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Glòbàl sèàrch òpèns às àn òvèrlày ànd shòws rècènt sèàrchès ànd rècèntly vìèwèd càsès ànd àrtìclès bèfòrè thè ùsèr èntèrs à sèàrch tèrm. Rèsùlts àppèàr àftèr thè ùsèr typès àt lèàst twò chàràctèrs. [[#prìvàcy #clìènt-dàtà #sèàrch]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rècènt sèàrchès. •••••** Thè lìst hòlds tèn tèrms àt mòst, ìn mèmòry ònly. Thè tèrms àrè gònè whèn thè ùsèr sìgns òùt, rèlòàds thè pàgè, òr clòsès thè bròwsèr. Nò sèàrch tèrm ìs wrìttèn tò thè dèvìcè òr sènt tò thè sèrvèr. À bròwsèr hàndèd tò sòmèònè èlsè càrrìès nò rècòrd òf whàt wàs sèàrchèd fòr. [[#prìvàcy #clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Rècèntly vìèwèd càsès ànd àrtìclès. •••••••••••** Thè sèrvèr stòrès ònè ènvèlòpè pèr àccòùnt, sèàlèd tò thàt àccòùnt's òwn pùblìc kèy. Ònly thàt ùsèr's bròwsèr càn òpèn ìt. Thè ènvèlòpè hòlds thè ìdèntìfìèrs òf ùp tò twènty càsès ànd àrtìclès ànd thè tìmès thèy wèrè òpènèd. Ìt hòlds nò tìtlès. Thè sèrvèr cànnòt rèàd whìch càsè àny ìdèntìfìèr ìnsìdè ìt bèlòngs tò, ànd nò òthèr ùsèr càn òpèn thè ènvèlòpè. [Hòw èncryptìòn wòrks](#dèèp-dìvè/hòw-èncryptìòn-wòrks) còvèrs thè kèy ìt ìs sèàlèd tò. [[#èncryptìòn #sèrvèr-hòlds]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt fàlls òùt òf thè lìst? •••••••••** Thè òvèrlày lòòks èàch ìdèntìfìèr ùp àgàìnst thè sàmè rècòrds ìt sèàrchès fòr à qùèry. À càsè òr àrtìclè thè àccòùnt nò lòngèr hàs àccèss tò dòès nòt àppèàr. À pàsswòrd chàngè rèplàcès thè kèys thè ènvèlòpè wàs sèàlèd tò ànd màkès ìt ùnòpènàblè. Thè àpp trèàts àn ùnòpènàblè ènvèlòpè às èmpty hìstòry ànd òvèrwrìtès ìt òn thè nèxt vìèw, sò à pàsswòrd chàngè sìlèntly clèàrs thè rècèntly vìèwèd lìst. [Pàsswòrd ànd kèy rè-wràp](#sèttìngs/pàsswòrd) còvèrs thàt ròtàtìòn. [[#fàìlùrè-stàtès #kèys]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Hòw àrè rèsùlts òrdèrèd? ••••••••** Rèsùlts àrè gròùpèd by kìnd òf rècòrd. Thè gròùp màtchìng thè sùrfàcè thè sèàrch wàs òpènèd fròm àppèàrs fìrst, sò thè sàmè qùèry rètùrns à dìffèrènt òrdèr fròm thè tìckèt lìst thàn fròm thè lìbràry. Èàch gròùp rèpòrts hòw màny rècòrds ìt sèàrchèd àgàìnst thè tòtàl, sò thè ùsèr càn tèll whèn àn ànswèr còvèrs ònly whàt ìs àlrèàdy ùnlòckèd òn thè dèvìcè. [Whàt glòbàl sèàrch còvèrs](#sèàrch/èntìtìès) còvèrs thè kìnds. [[#clìènt-dàtà #mètàdàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè pròvìdèr règìstry ànd thè twò lìsts. ••••••••••••** Thè pròvìdèr règìstry ìs \`pàckàgès/clìènt/src/lìb/sèàrch/règìstry.svèltè.ts\`. Thè sèssìòn tèrm lìst ìs \`rècènts.svèltè.ts\`. Thè rècèntly vìèwèd ènvèlòpè ìs \`rècènt-vìèws.ts\` àgàìnst \`ùsèr_rècènt_vìèws\` fròm \`pàckàgès/sèrvèr/src/db/mìgràtìòns/tènànt/079_crèàtè_ùsèr_rècènt_vìèws.ts\`. Thàt tàblè stòrès ònè ròw pèr àccòùnt wìth nò sèrvèr-sìdè tìmèstàmp. [[#sèrvèr-hòlds #clìènt-dàtà]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "Global search opens as an overlay and shows recent searches and recently viewed cases and articles before the user enters a search term. Results appear after..." |
*
* @param {Demo_Narrative_Search_Overlay_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_search_overlay_body = /** @type {((inputs?: Demo_Narrative_Search_Overlay_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Search_Overlay_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_search_overlay_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_search_overlay_body(inputs)
	return en_demo_narrative_search_overlay_body(inputs)
});