/* eslint-disable */
import { getLocale, experimentalStaticLocale } from '../runtime.js';

/** @typedef {import('../runtime.js').LocalizedString} LocalizedString */

/** @typedef {{}} Demo_Narrative_Admin_Form_Builder_BodyInputs */

const en_demo_narrative_admin_form_builder_body = /** @type {(inputs: Demo_Narrative_Admin_Form_Builder_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`The editor holds one working copy in the browser. Adding, removing, reordering and configuring fields all accumulate locally until the user saves. Each save replaces the entire field set on the server in one transaction. [[#client-data]]
**What types of field are available?** Text, text area, dropdown, checkboxes, checkbox, date and availability each collect an answer. Page break and text block shape the page without collecting one. A form accepts between one and a hundred fields, and at most one availability field. Both limits are enforced in the browser and again on the server. [Field settings](#admin-forms/field-config) covers what each type offers. [[#client-data]]
**What happens when a field is removed, reordered or relabeled?** Removing a field takes effect in the working copy and reaches the server only on the next save. Canceling a new field's settings before finishing them drops the field from the list. Removing or reordering a field clears any visibility rule that referenced it, because a rule can only reference a field that still exists and still comes earlier in the form. Answers already collected are stored separately from the form definition and survive every edit. The response viewer reads labels from the current definition, so an answer to a removed field shows under a generic label and an answer to a relabeled field shows under the new wording. [[#failure-states]]
**What does a save encrypt?** Each field's label, its configuration and its visibility rule are encrypted in the browser before the request leaves. The form's description, messages and banner are encrypted the same way. All of these are sealed under a key derived from the organization's public key. Because that public key is stored in the database and served on the public page, anyone who loads the form can derive the same key and read the definitions. Answers are protected separately, under a per-case key wrapped to individual accounts. [[#encryption #server-holds]]
**What travels in the clear?** Each field's key, its type, its semantic role, the queues an option routes to and whether it is required are plaintext columns. The escalation recipient list is encrypted under the server's operational key. A database dump shows how many fields a form has, of which types, in which order, and which roles they carry. [[#server-holds #metadata]]
**Who can edit a form?** Editing a form requires the Manage intake forms permission. That permission does not carry access to read what anyone submitted. [Intake forms list](#admin-org/intake-forms) covers the publishing step a save skips. [[#permissions]]
**The whole-form save transaction.** The editor is \`packages/client/src/lib/components/admin/IntakeFormEditor.svelte\`, and the encryption step is \`encryptFieldContent\` and \`encryptFormMeta\` in \`packages/crypto/src/intake-form.ts\`. On the server, \`saveForm\` in \`packages/server/src/portal/intake-form-service.ts\` deletes the existing field rows and reinserts the submitted list at positions zero upward, so field order is the array order and a field's identity across saves is the UUID minted when the field was first added. [[#client-data #encryption]]`)
};

const es_demo_narrative_admin_form_builder_body = /** @type {(inputs: Demo_Narrative_Admin_Form_Builder_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`El editor mantiene una copia de trabajo en el navegador. Agregar, eliminar, reordenar y configurar campos se acumula localmente hasta que la persona usuaria guarda. Cada guardado reemplaza todo el conjunto de campos en el servidor en una sola transacción. [[#client-data]]
**¿Qué tipos de campo hay disponibles?** Texto, área de texto, desplegable, casillas, casilla, fecha y disponibilidad recogen una respuesta cada uno. Salto de página y bloque de texto dan forma a la página sin recoger ninguna. Un formulario acepta entre uno y cien campos, y como máximo uno de disponibilidad. Ambos límites se aplican en el navegador y otra vez en el servidor. [Configuración de campo](#admin-forms/field-config) trata lo que ofrece cada tipo. [[#client-data]]
**¿Qué ocurre cuando se elimina, se reordena o se reetiqueta un campo?** Eliminar un campo surte efecto en la copia de trabajo y llega al servidor solo con el siguiente guardado. Cancelar la configuración de un campo nuevo antes de terminarla lo retira de la lista. Eliminar o reordenar un campo borra cualquier regla de visibilidad que lo referenciara, porque una regla solo puede apuntar a un campo que todavía existe y que aparece antes en el formulario. Las respuestas ya recogidas se almacenan por separado de la definición del formulario y sobreviven a cada edición. El visor de respuestas lee las etiquetas de la definición vigente, de modo que una respuesta a un campo eliminado aparece con una etiqueta genérica y una respuesta a un campo reetiquetado aparece con el texto nuevo. [[#failure-states]]
**¿Qué cifra un guardado?** La etiqueta de cada campo, su configuración y su regla de visibilidad se cifran en el navegador antes de que la solicitud salga. La descripción, los mensajes y el banner del formulario se cifran de la misma manera. Todo se sella con una clave derivada de la clave pública de la organización. Como esa clave pública se almacena en la base de datos y se sirve en la página pública, cualquiera que cargue el formulario puede derivar la misma clave y leer las definiciones. Las respuestas se protegen por separado, con una clave por caso envuelta para cuentas concretas. [[#encryption #server-holds]]
**¿Qué viaja en claro?** La clave de cada campo, su tipo, su rol semántico, las colas a las que encamina una opción y si es obligatorio son columnas en texto plano. La lista de destinatarios de escalación se cifra con la clave operativa del servidor. Un volcado de la base de datos muestra cuántos campos tiene un formulario, de qué tipos, en qué orden y qué roles llevan. [[#server-holds #metadata]]
**¿Quién puede editar un formulario?** Editar un formulario requiere el permiso Gestionar formularios de ingreso. Ese permiso no da acceso a leer lo que nadie haya enviado. [Lista de formularios de admisión](#admin-org/intake-forms) trata el paso de publicación que el guardado omite. [[#permissions]]
**La transacción de guardado completo.** El editor es \`packages/client/src/lib/components/admin/IntakeFormEditor.svelte\`, y el paso de cifrado es \`encryptFieldContent\` y \`encryptFormMeta\` en \`packages/crypto/src/intake-form.ts\`. En el servidor, \`saveForm\` en \`packages/server/src/portal/intake-form-service.ts\` borra las filas de campo existentes y reinserta la lista enviada en posiciones desde cero en adelante, de modo que el orden de los campos es el orden del arreglo y la identidad de un campo entre guardados es el UUID acuñado cuando se añadió por primera vez. [[#client-data #encryption]]`)
};

const en_xa2_demo_narrative_admin_form_builder_body = /** @type {(inputs: Demo_Narrative_Admin_Form_Builder_BodyInputs) => LocalizedString} */ () => {
	return /** @type {LocalizedString} */ (`⟦Thè èdìtòr hòlds ònè wòrkìng còpy ìn thè bròwsèr. Àddìng, rèmòvìng, rèòrdèrìng ànd cònfìgùrìng fìèlds àll àccùmùlàtè lòcàlly ùntìl thè ùsèr sàvès. Èàch sàvè rèplàcès thè èntìrè fìèld sèt òn thè sèrvèr ìn ònè trànsàctìòn. [[#clìènt-dàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt typès òf fìèld àrè àvàìlàblè? •••••••••••** Tèxt, tèxt àrèà, dròpdòwn, chèckbòxès, chèckbòx, dàtè ànd àvàìlàbìlìty èàch còllèct àn ànswèr. Pàgè brèàk ànd tèxt blòck shàpè thè pàgè wìthòùt còllèctìng ònè. À fòrm àccèpts bètwèèn ònè ànd à hùndrèd fìèlds, ànd àt mòst ònè àvàìlàbìlìty fìèld. Bòth lìmìts àrè ènfòrcèd ìn thè bròwsèr ànd àgàìn òn thè sèrvèr. [Fìèld sèttìngs](#àdmìn-fòrms/fìèld-cònfìg) còvèrs whàt èàch typè òffèrs. [[#clìènt-dàtà]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt hàppèns whèn à fìèld ìs rèmòvèd, rèòrdèrèd òr rèlàbèlèd? •••••••••••••••••••** Rèmòvìng à fìèld tàkès èffèct ìn thè wòrkìng còpy ànd rèàchès thè sèrvèr ònly òn thè nèxt sàvè. Càncèlìng à nèw fìèld's sèttìngs bèfòrè fìnìshìng thèm dròps thè fìèld fròm thè lìst. Rèmòvìng òr rèòrdèrìng à fìèld clèàrs àny vìsìbìlìty rùlè thàt rèfèrèncèd ìt, bècàùsè à rùlè càn ònly rèfèrèncè à fìèld thàt stìll èxìsts ànd stìll còmès èàrlìèr ìn thè fòrm. Ànswèrs àlrèàdy còllèctèd àrè stòrèd sèpàràtèly fròm thè fòrm dèfìnìtìòn ànd sùrvìvè èvèry èdìt. Thè rèspònsè vìèwèr rèàds làbèls fròm thè cùrrènt dèfìnìtìòn, sò àn ànswèr tò à rèmòvèd fìèld shòws ùndèr à gènèrìc làbèl ànd àn ànswèr tò à rèlàbèlèd fìèld shòws ùndèr thè nèw wòrdìng. [[#fàìlùrè-stàtès]]
 •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt dòès à sàvè èncrypt? ••••••••** Èàch fìèld's làbèl, ìts cònfìgùràtìòn ànd ìts vìsìbìlìty rùlè àrè èncryptèd ìn thè bròwsèr bèfòrè thè rèqùèst lèàvès. Thè fòrm's dèscrìptìòn, mèssàgès ànd bànnèr àrè èncryptèd thè sàmè wày. Àll òf thèsè àrè sèàlèd ùndèr à kèy dèrìvèd fròm thè òrgànìzàtìòn's pùblìc kèy. Bècàùsè thàt pùblìc kèy ìs stòrèd ìn thè dàtàbàsè ànd sèrvèd òn thè pùblìc pàgè, ànyònè whò lòàds thè fòrm càn dèrìvè thè sàmè kèy ànd rèàd thè dèfìnìtìòns. Ànswèrs àrè pròtèctèd sèpàràtèly, ùndèr à pèr-càsè kèy wràppèd tò ìndìvìdùàl àccòùnts. [[#èncryptìòn #sèrvèr-hòlds]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whàt tràvèls ìn thè clèàr? ••••••••** Èàch fìèld's kèy, ìts typè, ìts sèmàntìc ròlè, thè qùèùès àn òptìòn ròùtès tò ànd whèthèr ìt ìs rèqùìrèd àrè plàìntèxt còlùmns. Thè èscàlàtìòn rècìpìènt lìst ìs èncryptèd ùndèr thè sèrvèr's òpèràtìònàl kèy. À dàtàbàsè dùmp shòws hòw màny fìèlds à fòrm hàs, òf whìch typès, ìn whìch òrdèr, ànd whìch ròlès thèy càrry. [[#sèrvèr-hòlds #mètàdàtà]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Whò càn èdìt à fòrm? ••••••** Èdìtìng à fòrm rèqùìrès thè Mànàgè ìntàkè fòrms pèrmìssìòn. Thàt pèrmìssìòn dòès nòt càrry àccèss tò rèàd whàt ànyònè sùbmìttèd. [Ìntàkè fòrms lìst](#àdmìn-òrg/ìntàkè-fòrms) còvèrs thè pùblìshìng stèp à sàvè skìps. [[#pèrmìssìòns]]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••**Thè whòlè-fòrm sàvè trànsàctìòn. ••••••••••** Thè èdìtòr ìs \`pàckàgès/clìènt/src/lìb/còmpònènts/àdmìn/ÌntàkèFòrmÈdìtòr.svèltè\`, ànd thè èncryptìòn stèp ìs \`èncryptFìèldCòntènt\` ànd \`èncryptFòrmMètà\` ìn \`pàckàgès/cryptò/src/ìntàkè-fòrm.ts\`. Òn thè sèrvèr, \`sàvèFòrm\` ìn \`pàckàgès/sèrvèr/src/pòrtàl/ìntàkè-fòrm-sèrvìcè.ts\` dèlètès thè èxìstìng fìèld ròws ànd rèìnsèrts thè sùbmìttèd lìst àt pòsìtìòns zèrò ùpwàrd, sò fìèld òrdèr ìs thè àrrày òrdèr ànd à fìèld's ìdèntìty àcròss sàvès ìs thè ÙÙÌD mìntèd whèn thè fìèld wàs fìrst àddèd. [[#clìènt-dàtà #èncryptìòn]] •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••⟧`)
};

/**
* | output |
* | --- |
* | "The editor holds one working copy in the browser. Adding, removing, reordering and configuring fields all accumulate locally until the user saves. Each save ..." |
*
* @param {Demo_Narrative_Admin_Form_Builder_BodyInputs} inputs
* @param {{ locale?: "en" | "es" | "en-XA" }} options
* @returns {LocalizedString}
*/
export const demo_narrative_admin_form_builder_body = /** @type {((inputs?: Demo_Narrative_Admin_Form_Builder_BodyInputs, options?: { locale?: "en" | "es" | "en-XA" }) => LocalizedString) & import('../runtime.js').MessageMetadata<Demo_Narrative_Admin_Form_Builder_BodyInputs, { locale?: "en" | "es" | "en-XA" }, {}>} */ ((inputs = {}, options = {}) => {
	const locale = experimentalStaticLocale ?? options.locale ?? getLocale()
	if (locale === "es") return es_demo_narrative_admin_form_builder_body(inputs)
	if (locale === "en-XA") return en_xa2_demo_narrative_admin_form_builder_body(inputs)
	return en_demo_narrative_admin_form_builder_body(inputs)
});