/**
 * First-login E2E: volunteer invite acceptance flow.
 *
 * Reads the invite URL generated by onboarding.spec.ts (stored in
 * .auth/invite-url.txt) and completes the 3-step volunteer wizard:
 * account creation, security briefing, 2FA enrollment.
 *
 * Uses the same page.route() org-slug bypass as onboarding.spec.ts.
 */

import { test, expect, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  auditA11y,
  dismissBackupCodesSheet,
  generateTotpCode,
} from "./helpers.js";

const ONBOARD_SLUG = "e2e-onboard";
const API_PORT = "3000";
const AUTH_DIR = join(process.cwd(), ".auth");
const INVITE_URL_PATH = join(AUTH_DIR, "invite-url.txt");

const CRYPTO_TIMEOUT = 30_000;
const VOLUNTEER_PASSWORD = "e2e-volunteer-password-1234!";

function readInviteUrl(): string {
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- test infra, constant path
  return readFileSync(INVITE_URL_PATH, "utf-8").trim();
}

async function routeToOnboardOrg(page: Page): Promise<void> {
  await page.route(
    (url) => {
      const path = url.pathname;
      return (
        path.startsWith("/trpc/") ||
        path.startsWith("/api/branding") ||
        path === "/manifest.webmanifest"
      );
    },
    async (route) => {
      const originalUrl = new URL(route.request().url());
      originalUrl.port = API_PORT;

      if (originalUrl.pathname.startsWith("/trpc/")) {
        originalUrl.pathname = originalUrl.pathname.replace(/^\/trpc\//, "/");
      }

      const response = await route.fetch({
        url: originalUrl.toString(),
        headers: {
          ...route.request().headers(),
          "x-org-slug": ONBOARD_SLUG,
        },
      });
      await route.fulfill({ response });
    },
  );
}

test.describe.serial("Volunteer First Login", () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await routeToOnboardOrg(page);
  });

  test.afterAll(async () => {
    await page.unrouteAll({ behavior: "ignoreErrors" });
    await page.close();
  });

  // ── Step 0: Invite landing + Account Creation ──

  test("navigates to invite URL", async () => {
    const inviteUrl = readInviteUrl();
    await page.goto(inviteUrl);

    // Wait for the account creation form (step 1 of 3)
    await expect(
      page.locator(".step-text").getByText(/step 1 of 3/i),
    ).toBeVisible({
      timeout: CRYPTO_TIMEOUT,
    });
  });

  test("invite account step passes the axe accessibility audit", async () => {
    await auditA11y(page);
  });

  test("fills volunteer account form and submits", async () => {
    // Fill username
    await page.locator('input[autocomplete="username"]').fill("volunteer-e2e");

    // Konsta ListInput: use placeholder since label isn't associated via for/id.
    await page
      .getByPlaceholder(/how others will see you/i)
      .fill("E2E Volunteer");

    // Fill password fields
    const passwordInputs = page.locator('input[autocomplete="new-password"]');
    await passwordInputs.first().fill(VOLUNTEER_PASSWORD);
    await passwordInputs.last().fill(VOLUNTEER_PASSWORD);

    // Submit
    const submitBtn = page.getByRole("button", { name: /create account/i });
    await expect(submitBtn).toBeEnabled();
    await submitBtn.click();

    // Crypto pipeline runs. Wait for step 2 (briefing).
    await expect(
      page.locator(".step-text").getByText(/step 2 of 3/i),
    ).toBeVisible({
      timeout: CRYPTO_TIMEOUT,
    });
  });

  // ── Step 1: Security Briefing ──

  test("completes security briefing (4 sub-pages)", async () => {
    await expect(page.getByText(/how care-y protects/i)).toBeVisible({
      timeout: 5_000,
    });

    const nextLink = page.locator('[role="banner"]').getByText("Next");

    // Pages 1-3: Next
    for (let i = 0; i < 3; i++) {
      await nextLink.click();
      await page.waitForTimeout(300);
    }

    // Page 4: Confirm
    const confirmLink = page
      .locator('[role="banner"]')
      .getByText("Confirm", { exact: true });
    await confirmLink.click();

    // Should advance to step 3 (2FA)
    await expect(
      page.locator(".step-text").getByText(/step 3 of 3/i),
    ).toBeVisible({
      timeout: 5_000,
    });
  });

  // ── Step 2: Two-Factor Authentication ──

  test("enrolls TOTP via authenticator app", async () => {
    // Click the authenticator app option
    const totpItem = page
      .locator("a")
      .filter({ hasText: /authenticator app/i });
    await totpItem.first().waitFor({ state: "visible", timeout: 10_000 });
    await totpItem.first().click();

    // Wait for TOTP secret
    const secretEl = page.locator(".secret-text");
    await secretEl.waitFor({ state: "visible", timeout: 10_000 });
    const secret = await secretEl.textContent();
    expect(secret).toBeTruthy();

    // Generate and enter code
    const code = generateTotpCode(secret!);
    const codeInput = page.getByPlaceholder("000000");
    await codeInput.waitFor({ state: "visible", timeout: 5_000 });
    await codeInput.fill(code);

    // Verify
    const verifyBtn = page.getByRole("button", { name: /verify/i });
    await verifyBtn.click();

    // Dismiss backup codes via the "Save your codes" confirm dialog
    await dismissBackupCodesSheet(page);
  });

  test("completes 2FA and advances to dashboard", async () => {
    // Click Next after enrollment
    const nextLink = page.locator('[role="banner"]').getByText("Next");
    await expect(nextLink).not.toHaveAttribute("aria-disabled", "true", {
      timeout: 5_000,
    });
    await nextLink.click();

    // After completing all 3 steps, the first-login wizard redirects to /
    await page.waitForURL(/\/$/, { timeout: CRYPTO_TIMEOUT });
  });

  test("lands on dashboard with app shell", async () => {
    // The app shell tablist confirms we're on the authenticated dashboard
    await page.locator('[role="tablist"]').waitFor({
      state: "attached",
      timeout: CRYPTO_TIMEOUT,
    });
  });

  test("can access tickets tab", async () => {
    const ticketsTab = page.getByRole("tab", { name: /tickets/i });
    await ticketsTab.click();

    await expect(page).toHaveURL(/\/tickets/, { timeout: 10_000 });
  });
});
