/**
 * Stub for $lib/paraglide/runtime.
 *
 * Re-exports everything from the real compiled runtime (generated by
 * build:paraglide, gitignored but always present before dev/build via
 * the script chain), then overrides setLocale to suppress the default
 * page reload. Without this, tapping the navbar language picker nukes
 * the demo SPA.
 *
 * Known limitation: locale-reactive re-render does not happen because
 * the demo is a plain Vite SPA with no SvelteKit routing. The locale
 * value updates in memory but paraglide message functions that already
 * evaluated will not re-run until the component re-mounts.
 */

// Re-export everything from the real runtime.
export {
  baseLocale,
  locales,
  cookieName,
  cookieMaxAge,
  cookieDomain,
  localStorageKey,
  strategy,
  routeStrategies,
  urlPatterns,
  getStrategyForUrl,
  isExcludedByRouteStrategy,
  serverAsyncLocalStorage,
  disableAsyncLocalStorage,
  experimentalMiddlewareLocaleSplitting,
  isServer,
  experimentalStaticLocale,
  overwriteServerAsyncLocalStorage,
  getLocale,
  getLocaleForUrl,
  overwriteGetLocale,
  getTextDirection,
  overwriteSetLocale,
  getUrlOrigin,
  overwriteGetUrlOrigin,
  toLocale,
  isLocale,
  assertIsLocale,
  extractLocaleFromRequest,
  extractLocaleFromRequestWithStrategies,
} from "../../../client/src/lib/paraglide/runtime.js";

import { setLocale as realSetLocale } from "../../../client/src/lib/paraglide/runtime.js";

type DemoLocale = Parameters<typeof realSetLocale>[0];

/**
 * Override setLocale to always pass { reload: false }. The real
 * implementation defaults reload to true, which triggers
 * window.location.reload() or a full navigation.
 */
export async function setLocale(
  newLocale: DemoLocale,
  options?: { reload?: boolean },
): Promise<void> {
  await Promise.resolve(
    realSetLocale(newLocale, { ...options, reload: false }),
  );
}
