/**
 * Stub for $lib/paraglide/runtime.
 *
 * Re-exports everything from the real compiled runtime (generated by
 * build:paraglide, gitignored but always present before dev/build via
 * the script chain), then overrides setLocale to suppress the default
 * page reload and wires a reactive getLocale via locale-state.svelte.ts.
 *
 * The reactive getLocale means every paraglide message function called
 * during template render tracks the locale as a Svelte 5 dependency.
 * Changing the locale re-renders all visible messages without a reload
 * or component remount.
 *
 * Each browsing context (outer page, phone iframe) gets its own module
 * instance from this stub because they load from separate HTML entry
 * points with separate module graphs.
 */

// Re-export everything from the real runtime except setLocale, which
// is overridden below.
export {
  baseLocale,
  locales,
  cookieName,
  cookieMaxAge,
  cookieDomain,
  localStorageKey,
  strategy,
  routeStrategies,
  urlPatterns,
  getStrategyForUrl,
  isExcludedByRouteStrategy,
  serverAsyncLocalStorage,
  disableAsyncLocalStorage,
  experimentalMiddlewareLocaleSplitting,
  isServer,
  experimentalStaticLocale,
  overwriteServerAsyncLocalStorage,
  getLocale,
  getLocaleForUrl,
  overwriteGetLocale,
  getTextDirection,
  overwriteSetLocale,
  getUrlOrigin,
  overwriteGetUrlOrigin,
  toLocale,
  isLocale,
  assertIsLocale,
  extractLocaleFromRequest,
  extractLocaleFromRequestWithStrategies,
  getServerAsyncLocalStorage,
  extractLocaleFromCookie,
  extractLocaleFromHeader,
  extractLocaleFromNavigator,
  extractLocaleFromUrl,
  localizeUrl,
  deLocalizeUrl,
  aggregateGroups,
  findMatchingRouteStrategy,
  shouldRedirect,
  localizeHref,
  deLocalizeHref,
  trackMessageCall,
  generateStaticLocalizedUrls,
  isCustomStrategy,
  defineCustomServerStrategy,
  defineCustomClientStrategy,
  trailingSlash,
  extractLocaleFromRequestAsync,
  customServerStrategies,
  customClientStrategies,
} from "../../../client/src/lib/paraglide/runtime.js";

import { setLocale as realSetLocale } from "../../../client/src/lib/paraglide/runtime.js";
import {
  installReactiveLocale,
  setReactiveLocale,
} from "./locale-state.svelte.js";
import type * as ThisStub from "./paraglide-runtime.js";
import type * as Real from "../../../client/src/lib/paraglide/runtime.js";
import type { NoStubDrift, StubDrift } from "./stub-contract.js";

// Fails typecheck when an export drifts from the real module.
type _Contract = NoStubDrift<StubDrift<typeof ThisStub, typeof Real>>;

// Install the reactive getLocale override at module evaluation time.
// This runs once per browsing context (outer page or phone iframe).
installReactiveLocale();

type DemoLocale = Parameters<typeof realSetLocale>[0];

/**
 * Override setLocale to always pass { reload: false } and update the
 * reactive locale state. The real implementation defaults reload to
 * true, which triggers window.location.reload() or a full navigation.
 *
 * After calling the real setLocale (which writes cookies, localStorage,
 * etc.), the reactive state is updated so Svelte re-renders all visible
 * messages.
 */
export async function setLocale(
  newLocale: DemoLocale,
  options?: { reload?: boolean },
): Promise<void> {
  await Promise.resolve(
    realSetLocale(newLocale, { ...options, reload: false }),
  );
  setReactiveLocale(newLocale);
}
