/** UI actions available from the ticket panel. */
export type TicketAction =
  | "call"
  | "phone"
  | "email"
  | "take"
  | "release"
  | "assign"
  | "changePriority"
  | "changeQueue"
  | "hold"
  | "unhold"
  | "close"
  | "reopen"
  | "watch"
  | "unwatch"
  | "editContent"
  | "notifications"
  | "shareLink"
  | "revokeReplyToken"
  | "linkCases"
  | "cancel";
